### ISSUE TITLE
Progressive switch to npm

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#1009]
As the amount of js handled by webpack increases in the platform, the need for a flat public directory of packages becomes less relevant. We can thus plan a progressive abandon of bower in favour of a npm-only solution.

Steps: 
- [x] Remove the frontend bundle.
- [x] Abandon the distinction: "bower for frontend, npm for js dev tools". Move dev packages present in the `dependencies` of the distribution's package.json to the `devDependencies` of claroline/Claroline's package.json (as dev deps arent installed recursively). Regular frontend packages specified in package.json (if any) must stay in the deps of the distribution.
- [x] Remove librairies that have been added and used only in a webpack context from bower.json and add them to the npm deps of the distribution.
- [x] Convert remaining js parts to webpack and move their specific deps (if any) to npm.
- [x] Remove bower-related stuff (lib, config, webpack plugins, etc.) completely.

**Comment by Elorfin** [comment]
`FrontEndBundle` seems to be only used in `blog` (jquery-ui, tag-it), `website` (jquery-ui, angular-ui-tree) and `path`.

I've made a pull-request to remove it from PathBundle.

**Comment by stefk** [comment]
Thanks. Your PR highlights another aspect that I completely forgot: dealing with other kind of static assets that packages may contain (css, images, etc.). We'll have to investigate that. Quick thougths:

- bundle third-party less/css with webpack
- load them via less's import statements
- copy/publish assets to the public dir

**Comment by stefk** [comment]
> FrontEndBundle seems to be only used in blog (jquery-ui, tag-it), website (jquery-ui, angular-ui-tree) and path.

Actually there's a bit more than that. It might be good to have a separate issue to track the remaining bundles.

**Comment by ngodfraind** [comment]
Close this when #3516 is merged
