### ISSUE TITLE
ExoBundle : Papers are not saved when in a formative exercise

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#101]
_From @Elorfin on March 31, 2016 7:31_

When the Exercise is formative, at the end, the Paper of the student is not saved.
Reported by UJM but not yet reproduced by Innova.

_Copied from original issue: claroline/ClaroSupport#19_

**Comment by purplefish32** [comment]
_From @marion42 on March 31, 2016 8:59_

Do you reproduced the problem ?
Do you want I take a look on the problem ?

**Comment by purplefish32** [comment]
_From @Elorfin on March 31, 2016 9:28_

I just tried and there is no problem on my install. When I start to respond to a Formative exercise : 
- If I have an unfinished paper, this one is updated at the end of the Exercise
- If I have no unfinished paper, a new one is created at the beginning of the Exercise and is updated at the end.

So yes, give it a try please and tell me your results.

**Comment by purplefish32** [comment]
_From @charlotte42 on March 31, 2016 12:33_

C'est quand on n'est pas en formatif que l'entité paper reste vide à la fin du passage de l'exercice.

It is when we are not training that the entity remains blank paper at the end of the passage of the exercise.

**Comment by purplefish32** [comment]
_From @Elorfin on March 31, 2016 12:36_

It works for any type of Exercise for me. So I will let you check this one.

**Comment by purplefish32** [comment]
_From @charlotte42 on March 31, 2016 12:38_

En étant sur la branche V6 tu n'as pas ce souci ?

**Comment by purplefish32** [comment]
_From @charlotte42 on March 31, 2016 12:46_

C'est pas l'entité Paper qui est vide mais Response

**Comment by purplefish32** [comment]
_From @marion42 on March 31, 2016 12:55_

Duplicate with #25

**Comment by Elorfin** [comment]
This has been fixed and need to be merged.
