### ISSUE TITLE
Remove frontend bundle references

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#1013]
See #1009. Concerned bundles:
- [ ] agenda
- [ ] badge
- [ ] blog
- [ ] competency
- [ ] cursus
- [x] dropzone
- [ ] exo
- [ ] lesson
- [x] website
- [ ] wiki

**Comment by Elorfin** [comment]
I think it will be closed by #3516

**Comment by Elorfin** [comment]
removed
