### ISSUE TITLE
[ExoBundle] Editor

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#1014]
Rewrite of the current editor, enabling a smoother user experience when creating or editing exercises and questions, as well as a better integration of additional question types.

Features:
- in-place creation/edition
- fully editable objects (might be locked under certain conditions)
- local work, one-time sync (with regular backups on client-side)
- exposition of all the fields added to the model in 16.05:
  - additional description
  - object
  - resources
  - type (formative, certificative, ...)
- ability to make some fields hidden by default via a platform config parameter

Additional features (could be in the same release, otherwise will follow immediately):
- time limit on steps
- blocking/non-blocking steps
- allow or disallow going back to previous steps

**Comment by stefk** [comment]
Must have:

- [ ] #1083
- [ ] #49 

Nice to have:

- [ ] #1063 
- [ ] #1085

**Comment by jj-quintin** [comment]
Peut-on ajouter une référence au ticket #1111 ? Merci

**Comment by jj-quintin** [comment]
et... #1131

**Comment by jj-quintin** [comment]
Calcul du score en version formative, tenant compte du nbre d'essai à l'étape :  #1146

**Comment by stefk** [comment]
https://github.com/claroline/Distribution/projects/1

**Comment by jj-quintin** [comment]
@stefk 

J'ai ajouté le ticket #1187 (Editor : analyse des réponses par (auto) comparaison à un modèle)

Je ne sais pas à quelle hauteur sont les impacts sur l'éditeur et le player  (désolé)

**Comment by stefk** [comment]
@jj-quintin, ça va demander des changement des deux côtés, mais rien de dramatique en principe (ce sera après septembre de toute façon). Je l'ajoute ici et dans le [kanban](https://github.com/claroline/Distribution/projects/1).
