### ISSUE TITLE
[ExoBundle] Palef question types

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#1016]
- [ ] select/highlight text in a document
- [ ] point out layout parts in a document
- [ ] complete a conceptual map
- [ ]  fill in empty fields in a table

**Comment by jj-quintin** [comment]
Merci

**Comment by Pauooo** [comment]
For the "fill in empty fields in a table" can we imagine have both score possibility : either for the whole line or just for each cell ?

**Comment by stefk** [comment]
@Pauooo, that type isn't fully specified yet but yes, it sounds like a reasonable option to me.

**Comment by LaurentGruber** [comment]
reférencé dans Taiga
