### ISSUE TITLE
[ExoBundle] Bug affichage code HTML

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1021]
Situation : sommatif, non publié, une seule question (association), test de l'exercice

Bug rencontrer après deuxième "Tester l’exercice" (se produit une fois sur deux)
![2](https://cloud.githubusercontent.com/assets/16414632/18137740/f8d9bb7a-6fa9-11e6-9945-963ad9c5a31e.png)

**Comment by Elorfin** [comment]
duplicate #1020
