### ISSUE TITLE
ExoBundle : add missing translations

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#103]
_From @Elorfin on March 31, 2016 7:33_

Some translations are missing for the new features (like add step, remove step).

_Copied from original issue: claroline/ClaroSupport#21_

**Comment by Elorfin** [comment]
Translations have been added.
It only misses the translations for the Question type in the list of Questions.

**Comment by Elorfin** [comment]
This has been fixed and need to be merged.
