### ISSUE TITLE
[ExoBundle] Hint

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1036]
When there is a hint in a question : 
- [x] Add the possibilty to use an URL in an Hint
- [x] Display the penalty on the hint (not only in the confirm modal)

**Comment by Elorfin** [comment]
The second point can be easily done.

For the first one, @stefk is working on the new version of the Question editor. We will integrate it in this version.
In fact it may be interesting to add the possibility to use any Resource. What do you think ?

**Comment by Pauooo** [comment]
I agree.
