### ISSUE TITLE
[PathBundle] Deleting a path partially delete linked Activities

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#1037]
When a path is deleted the linked Activities are deleted but not the ResourceNode.
In fact the Activities must remain untouched as they can be linked to other Paths or used in stand-alone.

**Comment by CPASimUSante** [comment]
It seems that if the Activity was created with the resource manager, neither the activity nor the resourcenode are deleted when they are attached to a path which is deleted.
But for an activity created **within** the path, if the path is deleted, the activity gets deleted, but not the resourcenode. 
So, IMO, in the end, this behaviour could seems normal : what is created inside a specific path belongs to it and is deleted with it : if a user wants an activity shared between path, he has to create the activity outside the path.

**Comment by LaurentGruber** [comment]
not reproduce
