### ISSUE TITLE
[ActivityToolBundle] Rethink activity system

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#1040]
A few months ago, we have discussed about the possibility to remove the Activity Resource.

The idea was to create additionnal metadata on a ResourceNode to hold the activity parameters.

Is this still relevant (ping @LaurentGruber ) ? 
If yes we need to work on the specifications of the new system.

Steps : 
- [x] Implement the new system
- [x] Migrate old activities
- [x] Use the new system in Paths
- [x] Migrate path data
- [x] Remove Activity resource and ActivityTool bundle

**Comment by stefk** [comment]
This is a big change and we should add that activities being a core resource, other plugins/tools might be affected by the change. This is the case at least for the workspace dashboard and the competency plugin.

**Comment by LaurentGruber** [comment]
It's necessary to clarify the usage for user. But a good thinking is needed.
