### ISSUE TITLE
[Website] Bug visualisation & collaborateur

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1042]
Pas moyen de visualiser le site créé (à partir du bouton visualiser en mode édition ou en mode excution collaborateur).

![image](https://cloud.githubusercontent.com/assets/16414632/18197179/361e1aa6-70f6-11e6-9f55-ca0c09647652.png)

**Comment by jj-quintin** [comment]
16.12 c'est gênant car on ne pourra plus utiliser cette ressource en attendant

**Comment by ptsavdar** [comment]
Je vais essayer de corriger ca pour semptembre. Le plustot possible en fait.
