### ISSUE TITLE
[Website] Alerte intempestive

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1043]
S'affiche systématique même après sauvegarde de toutes les modifications et des pages : 

![image](https://cloud.githubusercontent.com/assets/16414632/18197292/a36c92ae-70f6-11e6-8ac9-74fdbfc4e943.png)

**Comment by ptsavdar** [comment]
C'est a cause de tinymce cela. Le navigateur il affiche le message automatiquement. Je ne sais pas si on peut faire grands choses. Je vais regarder quand j'aurais le temps.

**Comment by ptsavdar** [comment]
J'ai enleve le label "bug" parce que ce n'est pas un vrai bug en fait. IMO
