### ISSUE TITLE
[CoreBundle] Bug in "Recent activities" widget

### ISSUE THREAD

**Issue by kitan1982** [claroline/Distribution#1047]
Since desktop refactoring the "Recent activities" widget causes a white page if "jquery.jqplot.js" is not removed from "vendor/claroline/distribution/main/core/Resources/views/Log/count_by_day_chart.html.twig".

Howerver, when removed, the graph in the widget doesn't show anymore and there are issues with the Javascript.

**Comment by LaurentGruber** [comment]
@ptsavdar tu as réglé ça non ?
