### ISSUE TITLE
Problème HTML Champ description (parcours et exercice)

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1048]
Le HTML des champs description (parcours et exercices) n'est pas exécuté totalement ou proprement

Bug différent selon parcours ou exercice :  

Champ description dans une étape d'un parcours (cf. player vidéo différent avec boutons inopérants) : 
![image](https://cloud.githubusercontent.com/assets/16414632/18201258/665317f4-7109-11e6-96f6-4e6639d6e07b.png)

Champ description d'un exercice (couleur, ressource vidéo entre autres non interprétés). A noter que la visualisation disponible à partir de l'éditeur riche donne un résultat correct : 

![image](https://cloud.githubusercontent.com/assets/16414632/18202312/967a67d8-710f-11e6-88b8-4ccadd715539.png)

**Comment by LaurentGruber** [comment]
@jj-quintin sur le master également, j'ai l'impression qu'on a corrigé des soucis similaire la semaine passée ?

**Comment by jj-quintin** [comment]
@LaurentGruber 

Point sur le Master : 

Pour les champs descriptions des exercices

- description de l'exercice : ne fonctionne pas
- description de l'étape : non plus
- description de la question : ça fonctionne

Pour les champs description du parcours, cela marche

En réalité cela ne fonctionne pas quand j'ai l'ancienne version de l'éditeur TinyMCE, se présentant sous cette forme : 

![image](https://cloud.githubusercontent.com/assets/16414632/18992970/5c357c52-8721-11e6-8d38-32f76d59029c.png)

**Comment by Elorfin** [comment]
The bug on Path in no longer present in the `master`.
