### ISSUE TITLE
[CoreBundle] Bug ? Téléchargement MP4

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1050]
Via espace ressources (ajouter fichier) ou via resource texte par exemple, sur Master, pas possible de télécharger un fichier vidéo (mp4) même petit (2 Mo) 

Ajouter fihier
![image](https://cloud.githubusercontent.com/assets/16414632/18204983/ea765c38-711f-11e6-9a55-94ce09070f56.png)

![image](https://cloud.githubusercontent.com/assets/16414632/18205065/5b0b38b0-7120-11e6-8d5d-0fdb14ae94f6.png)

**Comment by Elorfin** [comment]
fixed
