### ISSUE TITLE
[Collecticiel] Bug - Affichage note ou appréciation côté étudiant

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1055]
Valable pour l'évaluation par notation et par appréciation

Notation : enlever l'affichage de Note : xx (sur xx) ainsi que la ligne et le bouton Ok (ne laisser que le lien avec la note, en bleu)
Appréciation : ne pas afficher Appréciation S Commentaire, ligne bleu, bouton Ok (ne laisser que le résultat de l'appréciation en lien (dans la seconde saisie d'écran : "S")
![image](https://cloud.githubusercontent.com/assets/16414632/18205668/7f39230c-7123-11e6-9255-5f71b5fd6b2e.png)

![image](https://cloud.githubusercontent.com/assets/16414632/18205892/a4c20282-7124-11e6-8f09-21f30b24f4d2.png)

**Comment by pitrackster** [comment]
duplicate https://github.com/claroline/Distribution/issues/1078.
Please pay attention
