### ISSUE TITLE
Lisibilité du formulaire "question de type texte à trous"

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#1063]
Il est très compliqué de savoir dans la liste des trous quels réponses correspondent à quels trous dans le texte. Particulièrement quand on utilise la liste de choix pour faire un "vrai ou faux". Il serait pratique d'avoir dans le formulaire un petit numéro en exposant à côté de chaque trou qui permettrait de facilement retrouver les réponses associées.

**Comment by jj-quintin** [comment]
Demande de détail supplémentaire : dans le player, augmenter légèrement l'interligne (les trous/lacunes empiètent sur la ligne texte du dessous)

**Comment by Elorfin** [comment]
Dans l'affichage de la correction aussi ce serait intéressant. 
Avec la possiblilité de masquer les réponses possibles pour un trou. La correction devient illisible quand on a plusieurs trous dans la même question.

**Comment by Elorfin** [comment]
This is solved by the new version of cloze questions.
