### ISSUE TITLE
[CoreBundle] Let the user configure the tmp directory

### ISSUE THREAD

**Issue by ngodfraind** [claroline/Distribution#1065]
Instead of using sys_get_temp_dir everywhere.

**Comment by CPASimUSante** [comment]
Would that be a terrible idea to have a /claroroot/upload/tmp or claroroot/files/tmp ? they have to be write enabled.

**Comment by stefk** [comment]
@ngodfraind, what's the problem with the system tmp dir? AFAIK even if we don't use it, other libs might do it anyway. Plus it's cleaned by the OS, that's one thing we don't have to take care of.

@CPASimUSante, we can't use the upload dir because it's public. The files dir should also be writable.

**Comment by ngodfraind** [comment]
On most linux OS's (it's what every debian/ubuntu I ever used did) it's only cleaned after a reboot. It's ok a for a dev computer, but for a server it's a bit problematic. This is a quite a common request actually.

**Comment by CPASimUSante** [comment]
@stefk i know they are public folder. But aren't those uploaded files (csv user list, WS...) temp files, wich are deleted (?) automatically after the corresponding script is done? But yeah, for certainty i agree a totally  unreachable dir would be best

**Comment by stefk** [comment]
@ngodfraind, good point.

> But aren't those uploaded files (csv user list, WS...) temp files, wich are deleted (?)

I hope so ;)

**Comment by charlotte42** [comment]
Currently our / tmp directory on the production server is filled quickly. We had to put a script that cleans every 30 minutes ...
