### ISSUE TITLE
[ExoBundle] Red pen

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1068]
Would be nice to display the meaning of the red pen in the bank of question and the exercise list.

**Comment by purplefish32** [comment]
@Pauooo What is the meaning of the red pen ?, how should it be displayed (tooltip) ?

**Comment by Pauooo** [comment]
the red pen means that the exercise is linked to papers. There is already a tooltip "edit" but maybe, since the edition is locked (issue #76), we could change "edit" for the explanation of the red pen ?

**Comment by jj-quintin** [comment]
D'après ce que je comprends le red pen signifie éditer avec restriction. Correct ?

**Comment by Pauooo** [comment]
Duplicate #556

**Comment by Pauooo** [comment]
After searching, looks like last week at the dev meeting its been decided : "Solution retenue: ne permettre que l'édition des contenus de texte des questions."

**Comment by Elorfin** [comment]
This is no longer relevant in the last version of quizzes. There is no more restriction on question edition.
