### ISSUE TITLE
Exobundle : Notation des questions dans les copies

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#107]
_From @marion42 on March 31, 2016 8:34_

Regarder pourquoi les réponses de l'exercice ne sont pas remontées dans l'affichage de la correction, ce qui entraine des notes nulles.

_Copied from original issue: claroline/ClaroSupport#25_

**Comment by charlotte42** [comment]
- QCM :             
  - multiple weighted [ ] 
  - multiple no weighted [ ] 
  - simple weighted [ ] 
  - simple no weighted [ ]

Match : 
  - to blind [ok]
  - to drag [ok ]
Open :
  - short [ok ]
  - onWord [ok ]
  - long [ ]
Graphic : [ ]
Hole : [ ]
