### ISSUE TITLE
[Collecticiel] Affichage modale détails notation/appréciation

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1079]
Un clic sur la note ou l'appréciation entraîne l'affichage d'une modale avec rappel consignes, types doc et doc, note ou l'appréciation + les commentaires. Problèmes d'affichage/taille de la modale ? Voir ci-dessous

![image](https://cloud.githubusercontent.com/assets/16414632/18264940/60a7cf5e-7413-11e6-8cbb-42cb38b22be1.png)

**Comment by LaurentGruber** [comment]
duplicate https://github.com/claroline/Distribution/issues/1057
