### ISSUE TITLE
[ExoBundle] Nouveau type de question : production orale

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1084]
Peut-on viser la 16-12 ?

Implémenter l'enregistrement audio et vidéo (deux sous-types) pour en faire une question à l'occasion de laquelle l'étudiant s'enregistre en ligne. L'étudiant a la possibilité de comparer sa production à celle fournie dans le champ objet de la question (ou question). Voir si adopter le système de correction enseignant adopté dans le type de question à réponse (écrite) ouverte longue.

A noter que, en version formative, la validation de la réponse de ce type débloque automatiquement le passage à l'étape suivante puisque que, actuellement, la version actuelle de cette version formative bloque le passage à la question  suivante tant que pas correct ou max essai atteint.

**Comment by Elorfin** [comment]
C'est une évolution de la question ouverte.
