### ISSUE TITLE
[ExoBundle] Navigation étape, version formative

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1085]
Amélioration : proposer deux modes de navigation en mode formatif, paramètre niveau exercice j'imagine : 
- blocage du passage à l'étape suivant tant que pas correct ou max essai atteint (situation actuelle)
- libre (comme en version sommative je pense)

**Comment by stefk** [comment]
@jj-quintin, @Pauooo, @claroline/commiters, je propose de réferencer les tickets concernant l'éditeur d'exercices [ici](https://github.com/claroline/Distribution/issues/1014#issuecomment-244880801), histoire de voir plus clair dans le travail restant à faire et de séparer l'urgent du moins urgent.
