### ISSUE TITLE
[ExoBundle] Current step attempt is not correct

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#1094]
I have not done any research for this, but I've seen many times in a formative exercise that the current step attempt has not the correct value.

@eldoniel : can you have a look please ?

**Comment by eldoniel** [comment]
After a quick check (on a formative exercise, 2 steps, 2 questions on the first one, 1 question on the second), I didn't see any anomaly. I'll keep looking.
If anyone gets this bug, can he please give me some more details about how it occured?

**Comment by Elorfin** [comment]
I think it occurs when you continue an interrupted paper. 
It restarts the count from 0 instead of getting `nbTries` from the DB.
