### ISSUE TITLE
[ExoBundle] Impossible to validate step if no max attempts set

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#1095]
In a formative exercise, if the max attempts property of a step is not set (default to 0), the "Validate" button is hidden (because the player catch it as if max attempts are reached).

**Comment by LaurentGruber** [comment]
c'est névessaire avant de mettre à jour l'ENPA @eldoniel tu aurais le temps de jeter un oeil ?

**Comment by eldoniel** [comment]
Checking it right now
