### ISSUE TITLE
[ExoBundle] Bug export questions

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1097]
Dans les questions avec audio, message système qui commence par : 

`Warning: DOMDocument::loadHTML(): Tag audio invalid in Entity, line: 3 in /var/www/html/claroline/vendor/claroline/distribution/plugin/exo/Services/classes/QTI/QtiExport.php on line 168`

**Comment by Elorfin** [comment]
@jj-quintin  : Post the archive you try to import here please so we can test it.

**Comment by Elorfin** [comment]
No longer relevant. The export system has been rewritten.
