### ISSUE TITLE
Small bug in message display for role adding in user list

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#1099]
As administrator, on the user list page, i check one or more user, then select one or more roles in the second dropdown, and then i click on "Add roles".
1) The button "Add roles" is not translated
2)  the confirmation message miss the role list : 

> Êtes-vous sûr de vouloir rajouter les rôles suivants [ **%role_list** ] aux utilisateurs [ admin, user0 ] ?

**Comment by CPASimUSante** [comment]
This one should clearly not be a priority :)

**Comment by ngodfraind** [comment]
This is already fixed.
