### ISSUE TITLE
ExoBundle : Export / import d'exo dans un workspace

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#110]
_From @charlotte42 on March 31, 2016 8:37_

Intégrer les étapes dans l'import / export de workspaces

_Copied from original issue: claroline/ClaroSupport#28_

**Comment by LaurentGruber** [comment]
A tester

**Comment by charlotte42** [comment]
- [ ]  Export WS

- [ ] Import WS

- [ ] Export WS

- [ ] Import WS

**Comment by david42** [comment]
fixed in #429
