### ISSUE TITLE
Ergonomy : remove the WS list a user is registered to icon

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#1100]
In the user list as admin, 
![user-list](https://cloud.githubusercontent.com/assets/14015697/18302415/0d0e33e0-74d8-11e6-8f5b-393b68c3e2d6.jpg)

the icon 
![action-wslist](https://cloud.githubusercontent.com/assets/14015697/18302341/a55e7430-74d7-11e6-8387-3ae9305d6ed1.jpg)
is pretty useless because all the important informations (the WS the user is registered to), and more are in the next icon : 
![action-wslist2](https://cloud.githubusercontent.com/assets/14015697/18302360/c29e07a4-74d7-11e6-9bcc-b72aa52f16fd.jpg)

**Comment by LaurentGruber** [comment]
il ne serve pas à la même chose, le livre permet d'arriver aux espaces.
Mais une refonte de l'ergonomie serait utile, par contre il faudrait le faire dans une vue d'ensemble pas juste pour un icone.

**Comment by CPASimUSante** [comment]
I persist : the book icon allow to access the WS the user is registered to, BUT in the **i** icon, you have all the user informattion AND the list of WS you can also access to
![sans-titre-2](https://cloud.githubusercontent.com/assets/14015697/18302831/4e13d672-74da-11e6-8a07-71a4662a4744.jpg)

But i agree, this should not be only a touch of ergonomy remodeling.
