### ISSUE TITLE
Nouvelle ressource : l'image interactive

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#1102]
http://www.larribe.fr/faire-une-image-interactive/

**Comment by jj-quintin** [comment]
Très bonne idée. Si on peut afficher une image interactive dans l'accueil de l'espace d'activités cela nous permettrait de nous passer du chipotage que nous devons faire de notre côté (image mapping) pour offrir  un menu visuel (à partir d'une image) permettant aux utilisateurs d'accéder aux ressources et aux parcours en cliquant sur une zone de l'image en question

**Comment by Pauooo** [comment]
On pourrait imaginer une ressource "interactive"  qui serait une video/audio/image/texte/carte (cf. https://github.com/claroline/Distribution/issues/1348) qui servirait de réceptacle pour différentes insertions (txt/questions/images/etc. créées au préalable dans les ressources ou non). Selon le "media réceptacle", les possibilités d'insertions seraient différentes. 
Exemple pour la vidéo : https://h5p.org/tutorial-interactive-video
