### ISSUE TITLE
[PathBundle] Add theme features

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#1109]
permettre l'édition des propriétés du background de chaque étape d'un parcours

+un bouton sur la step qui te dis "appliquer à toutes les étapes" à coté des propriétés

**Comment by Elorfin** [comment]
This cancel and replace the first specifcations.

The goal is to permits to fully changes the look & feel of a Path through a theme system.

The themes can be managed in the configuration of the plugin.
A theme : 
- has a `name`.
- has a LESS file.
- can be accessible by a list of platform roles.
- completly replaces the path styles.

The current LESS files used to style the Path for now must be considered as the default theme.

The LESS files must be compiled when a theme is created/updated through node less compiler. 
The LESS files must be compiled when we update/install a platform.

TODO :
- [ ] **Plugin configuration :** Create the UI for theme management
- [ ] **Plugin configuration :** Create the API for theme management
- [ ] **Edition of a Path  :** Add a dropdown with the list of available themes to select the one to use.
- [ ] **Edition of a Step  :** Permit to add custom CSS classes (to be able to override the styles for a set of steps).
- [ ] **Player :** Replace LESS files by the selected theme.
- [ ] **Player :** Add an HTML id on the current step panel with the ID of the step (to be able to customize a specific step in the theme).

For the future : 
We want to be able to add and edit custom animation like : https://impress.github.io/impress.js/#/ing.
Using the impress library or a custom implementation must be thought.

In the first version, basic animations can be set with CSS3 transitions directly in the theme file.

**Comment by LaurentGruber** [comment]
on peut modifier l'apparence des parcours depuis un thème
