### ISSUE TITLE
ExoBundle : Passsage questions exercice : indices

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#111]
_From @charlotte42 on March 31, 2016 8:39_

Finir d'ntégrer les indices dans le player angular

_Copied from original issue: claroline/ClaroSupport#29_

**Comment by purplefish32** [comment]
_From @Elorfin on April 5, 2016 14:27_

C'est à dire ?

**Comment by purplefish32** [comment]
_From @charlotte42 on April 5, 2016 14:38_

On ne peut pas l'ouvrir avec une question asso et je crois que pour les autres types de questions il n'enlève pas les points.

**Comment by purplefish32** [comment]
A completer (manque d'infos)

**Comment by Elorfin** [comment]
There was a bug in the API which has been fixed.
I have tested it and the score is correctly updated with the Hint penalty.

This fix has to be merged.
