### ISSUE TITLE
[ExoBundle] Allow to create exercise without score

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1114]
- In the metadata, under "score_displaying", add a check-box to create an exercise without score.
- when checked, it will hide all the score fields in the question editor and hide the score in the player.

What do you think ? @LaurentGruber @Gatomlo @stefk

**Comment by stefk** [comment]
Good idea. It might be worth including it in the next release.

**Comment by CPASimUSante** [comment]
I've already asked this to @Elorfin (not a ticket). He said he was on it.
IMO, since the ExoBundle is having more and more potentiality, in middle term, with just the score hidding feature, it could be used and replace the Survey resource.

**Comment by Elorfin** [comment]
@CPASimUSante : finally it's @pitrackster who is working on a first version of this. It will permit to hide the score for the students (but not the admins, like other correction/score filters).

I don't think it can replace the Survey as the main goal of Exercise is to validate user answers based on the configured correct answers. 
There is no correct answer in a Survey. It just need to collect answers to be able to make stats.

That's a main functional difference between both.

**Comment by CPASimUSante** [comment]
In the end, if there is in the stats for the exo : 
For question  A (QCU/QCM) : 45% of users answered Yes, 55% answered No
For question  B (open): 
       user 1 answered blaba
       user 2 answered blibi
...
this ressource can be used as a Survey.

**Comment by Gatomlo** [comment]
Very good idea.

logo 	
*Thomas Verniers*
Technopédagogue
mobile
0032 472 33 39 54 <#>
office
0032 10 87 04 94 <#>
email <#thomas.verniers@claroline.com> thomas.verniers@claroline.com 
<mailto:thomas.verniers@claroline.com>
website <#www.claroline.com> www.claroline.com <http://www.claroline.com>

*Claroline.com*
chemin du cyclotron 6
1348 Louvain La Neuve
Belgique
