### ISSUE TITLE
[ExoBundle] Bank of question

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1115]
- [x] #1098 
- [x] #1096 
- [x] #76
- [x] #22
- [x] #1127
- [x] #1165
- Rajouter un message dans la suppression d'une question si elle est partagée + Revoir message suppression d'une question dans l'exo

**Comment by jj-quintin** [comment]
#1127

**Comment by Elorfin** [comment]
I have removed #1097 from the list. It's an import/export problem. It's not directly related to the bank.
