### ISSUE TITLE
Video player - Pas possible de réduire la taille de la vidéo

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1117]
Depuis la 16-05, l'insertion d'une vidéo avec le ressource picker génère ce code : 

`<div><video class="video-js vjs-big-play-centered vjs-default-skin vjs-16-9" preload="auto" controls="controls" width="744" height="372" data-setup="{}">
                 <source src="/video-player/api/video/43462/stream" type="video/mp4" />
                             </video></div>`

Il faut supprimer dans ce code "vjs-16-9" pour que l'on puisse réduire la taille (ce qu'on est obligé de faire dans les exercices par exemple)

**Comment by jj-quintin** [comment]
Dans le code généré, 
`<div class="container">
<div class="span12">
<div><video` etc.

La balise <div class="container"> pose aussi des problèmes (quand on veut aligner la vidéo à gauche par exemple : pas moyen)

**Comment by ngodfraind** [comment]
Il faudra que je regarde avec @Gatomlo comment régler le problème. Le système a été changé pour un de ses client (pour que ça soit plus agréable visuellement).

Dans le cas des exercices, la vidéo doit rester "petite" c'est ça ?

**Comment by jj-quintin** [comment]
@ngodfraind 
Dans tous les cas où une vidéo est placée (par import ou resource picker) dans TinyMCE (ce peut être un exercice mais également une ressource texte, un cours ou autre) : 

- on peut redimensionner la vidéo dans l'éditeur mais dans les player (que ce soit l'exercice ou ailleurs), la taille de la vidéo est tjs en plein écran (vjs-16-9 pose problème)
- on ne pas peut modifier l'alignement dans la page de l'éditeur, et cela déconne dans les players (en supprimant le container dans l'HTML (<div class="container"> pose problème)

Ceci ne fonctionne pas (voir la vidéo 2 dans la saisie d'écran d'une ressource texte) : 
`<div class="container">
<div class="span12">
<div><video class="video-js vjs-big-play-centered vjs-default-skin vjs-16-9" style="float: left;" controls="controls" width="300" height="150" data-setup="{}">
                 <source src="/video-player/api/video/166/stream" type="video/mp4" />
                             </video></div>`
Ceci fonctionne  (voir la vidéo 1)
`<div class="span12">
<div><video class="video-js vjs-big-play-centered vjs-default-skin" controls="controls" width="300" height="150" data-setup="">
                 <source src="/video-player/api/video/166/stream" type="video/mp4" />
                             </video></div>`

![image](https://cloud.githubusercontent.com/assets/16414632/18946054/8eddbc04-862d-11e6-9f9b-10da8d4916dc.png)
