### ISSUE TITLE
[PathBundle] Sommaire bouton "épingle"

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1118]
D'après les retours utilisateurs, il serait préférable d'opter par défaut pour l'option **non** chevauchement du sommaire sur la page (ils optent tous pour cette solution), cela éviterait un clic

De plus, il faut leur expliquer (ils ne trouvent pas spontanément comment  "éviter le chevauchement et certains le voient comme un dysfonctionnement)

Ce serait donc bien d'ajouter une info-bulle et, tant qu'à faire sur le bouton sommaire bleu également (deux en réalités : ouvrir le sommaire, fermer le sommaire)

**Comment by Elorfin** [comment]
The summary is pinned by default in the master.
