### ISSUE TITLE
Exobundle : Copie anonyme

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#112]
_From @marion42 on March 31, 2016 8:40_

Flag dans la BDD fait. Il faut implémenter le code pour que les copies passer en anonyme reste en anonyme tout le temps.

_Copied from original issue: claroline/ClaroSupport#30_

**Comment by purplefish32** [comment]
_From @charlotte42 on April 1, 2016 7:40_

ok sur la v6-UJM

**Comment by charlotte42** [comment]
merge dans la v6
