### ISSUE TITLE
PDF Reader plante si apostrophe dans le nom du fichier

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1123]
Plantage du lecteur pdf si on met une apostrophe dans le nom du fichier / ressource
Un back slash devant l'apostrophe permet la lecture

**Comment by ngodfraind** [comment]
J'ai déjà corrigé il y a pas longtemps: https://github.com/claroline/Distribution/commit/d0d48ebc1922c64a84133f646011b2bbbae970ac

**Comment by clarophil** [comment]
Ok
