### ISSUE TITLE
[ExoBundle] Bug bloquant. Bloqué à l'étape 2 : {{ 'step'|trans:{}:'ujm_exo' }} {{ stepShowCtrl.stepIndex*1 + 1 }}

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1129]
Master. Version sommative ou formative. Voir ci-dessous lors d'un passage à l'épate suivante. On est bloqué à l'étape 2

![image](https://cloud.githubusercontent.com/assets/16414632/18416115/bf761e0a-780a-11e6-9c59-c0d24c1441b1.png)

**Comment by pitrackster** [comment]
Non reproduit sur la master travis. POurrais-tu essayer de vider ton cache navigateur ?

**Comment by jj-quintin** [comment]
ok

**Comment by jj-quintin** [comment]
J'ai vidé le cache. J'ai toujours le bug, mais pas au premier coup. En réalité, comme je teste les exercices, je change la version de l'exercice (sommative à version formative), et les option d'affichage de la correction et des scores. A un moment donné, en cliquant sur tester l'exercice, j'ai le bug, tjs après la première question

**Comment by pitrackster** [comment]
seems to be resolved
ping @jj-quintin please reopen if not

**Comment by jj-quintin** [comment]
@pitrackster : effectivement, je n'ai plus rencontré ce problème. Je continuerai à tester
