### ISSUE TITLE
[ExoBundle] Bug "Disponibilité de la correction" jamais ou au-delà de date du jour 

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1130]
Version sommative : Paramètre "Disponibilité de la correction"

La correction est affichée à la fin du test malgré tout (si paramètre su la valeur Jamais ou A partir d'une date donnée

![image](https://cloud.githubusercontent.com/assets/16414632/18416135/50e37748-780b-11e6-8031-c2b1c971193f.png)
Exo

**Comment by Elorfin** [comment]
C'est normal, les admins ont accès à tout, tout le temps.
Cette option n'impacte que les utilisateurs qui n'ont pas les droits d'édition sur l'Exercice.

**Comment by jj-quintin** [comment]
Idem remarques précédentes : l'ayant-droit de l'édition de l'exercice devrait pouvoir voir le résultat de ses changements de paramètres, ce qui est déjà le cas pour certains paramètres, mais pas tous
