### ISSUE TITLE
[ExoBundle] Editeur, player ? : paramétrer l'affichage de la correction dans la version formative

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1131]
Dans la version formative, actuellement, il y a toujours un affichage de la correction après un max essai atteint pour une question

Paramétrer cette option (dans l'éditeur il existe cette option pour la version sommative, mais semble sans sans effet dans le player)

**Comment by stefk** [comment]
@jj-quintin, si l'option est correctement enregistrée, le problème se situe au niveau du lecteur.

**Comment by jj-quintin** [comment]
A relier aux autres tickets peut-être traitant de l'affichage de la correction dans le player même quand pas demandé
Vérifier si cette option de non affichage (jamais ou à partir d'une certaine date) est opérationnelle dans la version formative

**Comment by Elorfin** [comment]
C'est normal.
Cette option n'impacte que l'affichage des corrections pour les étudiants (pour tous les types d'exercice).
Elle n'est pas disponible dans les feedbacks. 

D'ailleurs la seule option pertinente dans ce cas est "Jamais".

**Comment by Elorfin** [comment]
L'option est maintenant prise en compte dans les feedbacks.
Je crois que c'est Nico qui s'en ai occupé.
