### ISSUE TITLE
[CoreBundle] soft delete failed on Shortcup resource

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1136]
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function isSoftDelete() on null" at /home/hevinci/claroline/vendor/claroline/distribution/main/core/Manager/ResourceManager.php line 1008 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function isSoftDelete() on null at /home/hevinci/claroline/vendor/claroline/distribution/main/core/Manager/ResourceManager.php:1008)"} []

**Comment by kitan1982** [comment]
I couldn't reproduce the issue.

**Comment by LaurentGruber** [comment]
@clarophil tu sais expliquer comment reproduire ?

**Comment by clarophil** [comment]
ça a l'air bon maintenant, je clos le ticket
