### ISSUE TITLE
[CoreBundle] Impossible to access administration / plateform logs

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1137]
When I click on plateform logs in the Administration menu this is the message I have : 
"Fatal error: Uncaught Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "claro_admin_user_of_group_list" as such route does not exist. in /var/www/html/claroline/app/cache/prod/appProdUrlGenerator.php:1689 Stack trace: #0 /var/www/html/claroline/app/cache/prod/classes.php(3883): appProdUrlGenerator->generate('claro_admin_use...', Array, false) #1 /var/www/html/claroline/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Extension/RoutingExtension.php(45): Symfony\Component\Routing\Router->generate('claro_admin_use...', Array, false) #2 /var/www/html/claroline/app/cache/prod/twig/99/99f22c1c0950e56821c64af9d5f988d30b51489dc4a5a636108563aa9a426738.php(27): Symfony\Bridge\Twig\Extension\RoutingExtension->getPath('claro_admin_use...', Array) #3 /var/www/html/claroline/app/cache/prod/classes.php(2393): __TwigTemplate_84a32a516b715381cafaafda87aa7a9d676136303ec4b1f6ebd62e6c663f55ab->doDisplay(Array, Array) #4 /var/www/html/claroline/app/cache/prod/classes.php(2369): Twig_Templa in /var/www/html/claroline/app/cache/prod/classes.php on line 2295"

**Comment by ptsavdar** [comment]
Yes indeed this path while it is used inside two twig templates, it is not defined in a controller. Someone must have removed the path without changing the views.

**Comment by ptsavdar** [comment]
After some research, I found out that the functionality was deleted at Feb 9 in commit https://github.com/claroline/Distribution/commit/f1db9b370a22b23499ff165829d8b7407cd8c993 by @ngodfraind . However, two views still using it [groupListPager.html.twig](https://github.com/claroline/Distribution/blob/master/main/core/Resources/views/Administration/WorkspaceRegistration/groupListPager.html.twig) and [view_list_item_receiver_group.html.twig](https://github.com/claroline/Distribution/blob/master/main/core/Resources/views/Log/view_list_item_receiver_group.html.twig).

**Comment by ngodfraind** [comment]
I'm looking at it.

**Comment by ngodfraind** [comment]
Fixed by  #1242
