### ISSUE TITLE
[ExoBundle] tjs bug analyse de réponse formative (réf ticket fermé 1088)

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1140]
Réf au ticket #1088 fermé

On rencontre tjs le même bug dans l'analyse de la réponse en version formative, voir 2ème image ci-dessous, à partir du master et cache vidé ;-) avec les paramètres version formative et : 

![image](https://cloud.githubusercontent.com/assets/16414632/18445270/189f4570-791d-11e6-92e9-1cb37aab82e1.png)

![image](https://cloud.githubusercontent.com/assets/16414632/18445195/b442c782-791c-11e6-8e2e-1c6089947cc5.png)

**Comment by Elorfin** [comment]
To check on `claroline-master` when #1154 will be merged.

**Comment by Elorfin** [comment]
Seems OK on `claroline-master`
