### ISSUE TITLE
[ExoBundle] Editor : Score et nbre d'essais en version formative

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1146]
@stefk 

Dans la situation actuelle, les scores sont calculés de la même manière dans les différentes versions de l'exercice (formative et sommative du moins, je n'ai pas encore testé la version évaluative)

Ce score attribue + x pt(s) lorsque la réponse a été trouvée, ce qui ne pose pas de problème pour la version sommative, puisque nombre d'essai est de fait = à 1 

En version formative, le nombre d'essais est souvent > 1 et, dans ce cas, ce système de score aboutit généralement à l'obtention d'un maximum de pts (+ x quand la réponse a été trouvée), ce qui ne permet pas de révéler les difficultés rencontrées

Dans cette version formative, la proposition est d'offrir un calcul de score supplémentaire, présenté par défaut, quitte à l'enseignant d'opter pour l'actuel

Une proposition de calcul avait été faite en son temps. Elle est destinée à tenir compte du nombre d'essais réalisé avant de trouver les réponses attendues. Mais elle est un peu complexe à implémenter pour l'être maintenant.

Peut-être pourrions-nous, pour commencer, pondérer le score par le nbre d'essais utilisé pour trouver les bonnes réponses. Du style : 
- score \* 1/nbre d'essais (bémol : cela pénalise fortement dès le deuxième essai (50% du score max de l'étape). Je pense (mais de mémoire) que c'est la solution adoptée par HotPotatoes)
  Alternative, plus douce, moins pénalisant plus favorable à l'étudiant
- (score \* 1/nbre d'essais)\* racine du nbre d'essais, ce qui pour 1 pt donne la suite : 

![image](https://cloud.githubusercontent.com/assets/16414632/18467111/ef35c128-799e-11e6-9e55-39df2216a23a.png)

Alors que la première solution de score donnait : 

![image](https://cloud.githubusercontent.com/assets/16414632/18467153/17479f60-799f-11e6-953c-0da913da4152.png)

Tu en penses quoi ?

En relation avec #1111 qui constitue un calcul complémentaire de type moins scolaire, plus ludique, pour un public de professionnel en formation continue

**Comment by stefk** [comment]
Ça me semble faisable et pertinent mais ce n'est pas tellement au niveau de l'éditeur que ça se joue (ce n'est qu'une option en plus dans le formulaire) mais à celui du lecteur. Il faut qu'on fasse le point sur les ressources disponibles avant de déterminer une date pour l'implémentation.
