### ISSUE TITLE
Ajout de paramètres concernant les utilisateurs

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1157]
Je propose d'ajouter 2 paramètres à la création des utilisateurs (interface et ligne de commande)
- Demander ou pas la validation du mail 
- Recevoir une copie des messages sur ... (case à cocher dans la messagerie)

**Comment by LaurentGruber** [comment]
paramètre à gérer de façon global via plateforme option pas à chaque création (la validation du mail doit pouvoir être rendue obligatoire sauf cas exceptionnel pour éviter le spam et le blacklisting des serveurs mail)

**Comment by clarophil** [comment]
Résolu
