### ISSUE TITLE
Bug on audio resource

### ISSUE THREAD

**Issue by eldoniel** [claroline/Distribution#1181]
The audio resources currently present a bug: when accessing it in the Resource Manager, there is no player shown but a big empty rectangle:

![bug_audio_resource](https://cloud.githubusercontent.com/assets/7665692/18674330/23e2b07e-7f4f-11e6-9972-4eecd20d5c0a.png)

When clicking on it, it still plays the audio though.

**Comment by pitrackster** [comment]
@eldoniel the audio is opened inside a video tag. So the "big rectangle" is normal but the "empty" is not. There is no control bar nor "big play button" to handle resource playback as usual.

If you look at the first video-js container div class attribute you can see it contains ```vjs-controls-disabled``` class.  In the next div tag class attribute there is ```vjs-controls-enabled``` ... This is somewhow odd.

Anyway the fact is that the ```.vjs-control-bar``` css class has the ```display:none;``` property. And we have the same problem with the ```.vjs-big-play-button``` css class.

Could you investigate and make a PR ?

Thanks
