### ISSUE TITLE
Editeur tinymce - Bug - Accès code HTML depuis l'éditeur

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1182]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Editeur d'une question ou éditeur riche ailleurs : clic sur code source de l'éditeur riche => bug

![image](https://cloud.githubusercontent.com/assets/16414632/18674599/06437b60-7f50-11e6-9bb5-06da30941dbc.png)

**Comment by Pauooo** [comment]
Not just for exercises, maybe could be linked to  #1183

**Comment by Elorfin** [comment]
This is a configuration problem (the config has been updated on `claroline-master`).
See #1195.
