### ISSUE TITLE
Editeur tinymce : taille champ surdimensionnée, couleur grisée

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1183]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Problème de taille du champ, avec répectution en particulier côté éditeur des questions de l'exerice
Couleur de fond grise et non blanche comme avant

![image](https://cloud.githubusercontent.com/assets/16414632/18674748/91dcb83a-7f50-11e6-81b3-3eb63964a104.png)

**Comment by Pauooo** [comment]
Not just for exercises

**Comment by Elorfin** [comment]
This is a configuration problem (the config has been updated on `claroline-master`).
See #1195.
