### ISSUE TITLE
Organisation et recherche liste d'utilisateurs (gestion des utilisateurs)

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1185]
| Q | A |
| --- | --- |
| Bug report? | no |
| Version? | master |

Création d'une organisation "test" avec affectation d'un administrateur
Création d'un utilisateur test2 et affectation de l'organisation "test"
Dans la fonction de recherche par organisation, on n'obtient que l'administrateur (voir image ci-dessous)
- Ce serait bien de voir l'ensemble des utilisateurs rattachés à l'organisation filtrée
- Voire, si jugé intéressant, d'ajouter une colonne avec l'affichage de l'organisation auquel les utilisateurs sont rattachés

![image](https://cloud.githubusercontent.com/assets/16414632/18675563/0a8eed5a-7f53-11e6-9556-286292e6ad49.png)

**Comment by CPASimUSante** [comment]
For the first part, i've tested on master, and i have all the users belonging to the organization. Maybe did you try the search right after the test2 creation (there is a refreshing problem)
