### ISSUE TITLE
[ChatBundle] Bug Création d'un compte utilisateur pour le chat

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1186]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master |

1- Bug lors d'une tentative de créer un compte utilisateur Chat (bloqué sur "Veuillez patienter...") après clic sur Créer des comptes pour le chat

2- "des" comptes.. mais une liste avec des radiobuttons

![image](https://cloud.githubusercontent.com/assets/16414632/18676787/140adcbe-7f57-11e6-896f-14df515d196d.png)

**Comment by LaurentGruber** [comment]
cela se produit car le serveur de chat n'est pas configuré ce n'est donc pas un bug, par contre l'outil ne devrait pas être utilisable si le serveur n'est pas configurer.
Il faut rajouter une condition qui fait apparaitre la gestion des utilisateurs du chat uniquement quand le plugin est configuré
