### ISSUE TITLE
[Notification] Une ressource effacée est toujours présentes dans la notification

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1188]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Créer une ressource puis l'effacer.
Elle est toujours signalée dans la notification, on reçoit alors soit une erreur interne soit un refus d'accès.
Ne faudrait-il pas effacer simplement la notification ?

**Comment by ptsavdar** [comment]
En fait, ceci est un comportement voulu. En fait les notifications servent à garder un sort des logs pour les gens qui suivent les resources ou les espaces de travail. Si on supprime la notification on supprime cet info. Si elle est là et qu'elle pointe vers une resource inexistante, dans ce cas, la personne se rend compte qu'il y avait une action de suppression entre-temps. Même s'il ne peut pas voir la ressource, il a une info qu'autrement il aurait jamais eu. (Il est informé que qqn à effectué des actions sur une resource mais après il a tout supprimé).

**Comment by LaurentGruber** [comment]
@clarophil ça te convient ? tu penses à une autre solution ?

**Comment by clarophil** [comment]
oui je comprends Panos mais le message c'est "La page que vous cherchez n'existe pas. " ce serait mieux "Cette page a été supprimée" et mettre le message en orange plutôt que rouge.  Il  y a trop de message qui ressemble à des erreurs mais qui n'en sont pas.
