### ISSUE TITLE
[ExoBundle] Player affichage du score

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1190]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Big : Le score est affiché quand l'option Affichage du score dans les paramètre est placée sur la valeur Jamais

**Comment by Elorfin** [comment]
Déjà expliqué : cette option n'impacte que les étudiants, pas les administrateurs de l'exo.

**Comment by jj-quintin** [comment]
Il faudrait rouvrir ce ticket. On ne s'est pas compris apparemment. Je vais en expliquer les raisons dans un nouveau ticket
