### ISSUE TITLE
[ExoBundle] Paramètre "disponibilité de la correction" associé à "vue minimale de la correction"

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1192]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no ?
| Version?      | master

En version formative

Lorsque la "Vue minimale de la correction" est sélectionnée, on ne voit aucun changement/effet dans le player suite au changement de valeur de l'option Disponibilité de la correction, que ce soit la valeur jamais, ou à la fin du test par exemple

**Comment by Elorfin** [comment]
voir #1190.
