### ISSUE TITLE
[CoreBundle] Bug with default value of the platform domain

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#1195]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

The parameters contains a default value "Nom de domaine".
If it is not manually modified by the User the path to assets generated is "http://Nom de domaine" and it breaks the file loading.

I'm not sure if the field should be optional or if the domain must be validated.
@ngodfraind ?

**Comment by ngodfraind** [comment]
Maybe the domain should be validated. It's null by default. I'll add a validator.

**Comment by ngodfraind** [comment]
Should be fixed/improved by #1243
