### ISSUE TITLE
[CoreBundle] Import d'utilisateurs dans un espace d'activité depuis un fichier csv

### ISSUE THREAD

**Issue by charlotte42** [claroline/Distribution#1207]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 7.x-dev.

 Bonjour,
Lorsque l'on est dans un espace d'activité et que l'on veut importer des utilisateurs depuis un fichier csv, on a l'erreur suivante : 
![error-importcsv](https://cloud.githubusercontent.com/assets/11042666/18753978/5d58f9c8-80e7-11e6-806b-e37e54bcf0a8.png)
On est en version :
![version](https://cloud.githubusercontent.com/assets/11042666/18753995/6da89fe0-80e7-11e6-802b-2bfa9748b845.png)

Si mon fichier ne respecte pas <Username>;<Role> ou que les utilisateurs n'existent pas dans la plateforme j'ai bien les bons messages d'erreurs. ex :
![selection_062](https://cloud.githubusercontent.com/assets/11042666/18754133/df12af2c-80e7-11e6-8306-124c29b7dc3a.png)

**Comment by ngodfraind** [comment]
It was fixed by #795
