### ISSUE TITLE
[PathBundle] Adaptive content as a primary resource : display issue

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1208]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

When the primary resource of a step is an adaptive content (for exemple a SCORM), the iframe height is oversized. It makes it impossible to display properly the SCORM in a step.
http://claroline-master.travis-build.claroline.net/innova_path/player/6#/8

**Comment by LaurentGruber** [comment]
voir pr : https://github.com/claroline/Distribution/pull/878
