### ISSUE TITLE
[ExoBundle] Add a score by proposal in the drag question (panier)

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1210]
| Q | A |
| --- | --- |
| Bug report? | no |

In the drag question, the points are given for each label and not for the proposals dragged in the label. It would be more logical to have the score linked to the proposals.

**Comment by jj-quintin** [comment]
Nous avons les mêmes remontées des utilisateurs. Ceci vaut non seulement pour le score d'ailleurs, mais également pour l'analyse des réponses en version formative. 

En réalité, il semblerait que ce soit effectivement la proposition qu'il faudrait analyser et non le label. Du coup, le total des points serait le total des points des propositions et non des labels

**Comment by Pauooo** [comment]
This has been implemented in the new version of the plugin.
