### ISSUE TITLE
[ExoBundle] Player auteur/gestionnaire : fonctionnement non conforme aux paramètres fixés

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1212]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Référence aux tickets 
 #1190  #1192 à rouvrir, ou garder celui-ci (à vous de voir)

Le bouton tester permet à l'auteur de l'exercice de vérifier ce qu'il a réalisé, ainsi que les paramètres qu'il a fixés pour son exercice. Cela fonctionne déjà pour le "type" d'exercice entre autres. Ainsi, si je fixe un type formatif, quand je teste l'exercice on me montre bien un fonctionnement de type formatif dans le player (en tent que gestionnaire de l'exercice).

Cela ne fonctionne pas encore avec certains paramètres, dont l'affichage du score et la disponibilité de la correction (en réalité l'affichage de la solution) par exemple.

Il faudrait que, pour l'auteur/gestionnaire de l'exercice également, celui-ci fonctionne dans le player conformément à ce qu'il a fixé dans les paramètres, qu'il clique sur Tester l'exercice ou sur (Re)Commencer l'exercice

**Comment by Elorfin** [comment]
Les options "Affichage du score" et "Affichage de la correction" n'impacte pas les admins car :
- Lors du test de l'exercice, l'admin doit pouvoir valider les attributions de points et les réponses correctes.
- Après le test, l'admin doit pouvoir consulter les notes des étudiants, même si elles n'ont pas encore été publiées pour les étudiants (que se soit pour consulter les données ou pour noter manuellement une question).

Il y a un ticket ouvert pour ajouter des textes d'information sur ces 2 champs pour prévenir que ces options n'impactent pas l'admin.

Il y a également un ticket pour supprimer totalement (admin + étudiant) la notion de score d'un exercice.

Le fonctionnement est donc celui souhaité et ne sera pas changé.
