### ISSUE TITLE
[PathBundle] Info-bulles sur boutons Sommaire et "épingle"

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1214]
| Q | A |
| --- | --- |
| Bug report? | no |
| Version? | master |

Le ticket #1118 (fermé) faisait référence à deux demandes : non chevauchement par défaut (fait) et info-bulle sur les bouton sommaire et épingle (non fait)

Proposition d'info-bulle 
- Sommaire : 
  -- Ouvrir le sommaire (quand sommaire fermé)
  -- Fermer le sommaire (quand sommaire ouvert)
- Epingle (pas trouvé mieux que) : 
  -- Avec chevauchement (si épingle verte)
  -- Sans chevauchement (si épingle grise)

**Comment by LaurentGruber** [comment]
refonte ergonomique résoud le souci
