### ISSUE TITLE
[Collecticiel] Rappel des instructions/Consignes : Terminologie - Traduction ?

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1215]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master

Le terme "Consignes" a été (récemment ?) modifié par "Rappel des instructions"

Merci de bien vouloir remettre Consignes

**Comment by om64** [comment]
Quelle différence fait-on entre consignes et instructions? Ce sont des synonymes, non?

**Comment by om64** [comment]
@jj-quintin Je présume que le changement souhaité serait à faire dans le fichier innova_collecticiel.fr.yml

**Comment by jj-quintin** [comment]
@om64 Non, c'est une terminologie du collecticiel que nous avons développé et qui est valable en base pour Claroline, ce n'est pas une adaptation propre. Il y a environ une vingtaine de termes propres au collecticiel qu'on a pris soin d'élaborer et qui, à l'issue d'échanges entre les enseignants, fait consensus. Merci de ne pas modifier les termes choisis pour le collecticiel, sauf erreur orthographique bien entendu, ce qui, après vérification, ne semble pas le cas (sauf erreur d'inattention de ma part bien sûr)

Le terme "Consignes" est celui qui a été adopté

Je peux t'en expliquer les raisons bien sûr

**Comment by om64** [comment]
@jj-quintin  Je m'occupe du changement dans les fichiers concernés. Pour info et dans l'attente de l'outil de traduction, je suis repassé sur la totalité des fichiers .yml en français et en anglais. Il y avait énormément d'erreurs.

**Comment by jj-quintin** [comment]
@om64 Merci. Oui, je m'en doute. On lancera les chantiers de traduction de notre côté quand l'outil de traduction nous sera disponible

Pour le collecticiel, j'ai vu aussi que tu avais modifié  

Fichiers (téléversement depuis leur ordinateur)
Texte libre (rédaction en ligne)
Ressources (sélection depuis l'espace ressources de la formation)
Lien Internet (adresse URL)

par

Autoriser l'upload de fichiers
Zones de texte libre
Ressources (sélection depuis l'espace ressources de la formation)
Autoriser les liens web

Il y a une raison ?

**Comment by jj-quintin** [comment]
@om64 

Et puis, je vois que le texte ci-dessous comporte des erreurs stylistique, typo ou orthographique, mais je ne sais pas si c'est en dur, dans le code, ou dans les traductions (ce qui serait logique). Je pense que pour le collecticiel, si tu me donne accès à l'interface de traduction, ce sera plus simple que je vérifie moi-même

Cet outil met à **la** disposition des utilisateurs un espace dans lequel ils peuvent déposer des documents de différents types : fichier (à téléverser), texte libre (à rédiger en ligne) **virgule**	ressources (à sélectionner depuis **lespace des ressoures**) et lien Internet.
**Lutilisateur** peut demander une évaluation ou un simple commentaire pour **lun** ou **lautre** des documents déposés dans son espace. Ces deux types de demandes (simple commentaire ou évaluation) ont été regroupés sous le terme "demande de commentaire".
Dans cette version 1 du collecticiel seuls les enseignants reçoivent des "demandes de commentaires".

**Comment by jj-quintin** [comment]
@om64 

Ceci : 

À ce jour, aucune demande ne vous a été adressée

a également été modifié par :  

Aucune copie en attente de correction 

Le collecticiel ne fonctionne pas ainsi, pas comme l'évaluation par les pairs et il n'y a pas forcément d'évaluation (tout dépend des paramètres indiqués par l'enseignant), mais sous la forme de demande (de commentaire ou d'évaluation) adressée à un tiers. Les textes que nous avions conçus ont été choisis pour faire face au fonctionnement spécifique du collecticiel. J'ai ai passé du temps ;-) 

Je pense que le mieux, c'est que j'accède moi-même à l'interface de traduction car pas mal de changements posent problèmes

**Comment by jj-quintin** [comment]
@om64 

Ceci aussi : 

Ouverture

L'ouverture du collecticiel peut se réaliser de manière manuelle ou en fonction de dates, de début (ouverture du collecticiel) et de fin (fermeture).

Par : 

Ouverture

L'ouverture du collecticiel peut se réaliser de manière manuelle ou en fonction des dates	de début (ouverture du collecticiel) et de fin (fermeture).

Elle se divise en plusieurs étapes : l'ouverture de l'évaluation en autorisant le dépôt, début de l'évaluation par les pairs qui clôture le dépôt et la fin de l'évaluation.

Ce qui est erroné (ce n'est pas ainsi que fonctionne le collecticiel, le fonctionnement décrit est le fonctionnement de l'évaluation par les pairs à nouveau.

**Comment by om64** [comment]
@jj-quintin Je corrige les erreurs que tu as mentionnées au plus vite. Par ailleurs, il n'y a pas d'interface de traduction. Tu peux éditer et corriger des fichiers en cliquant sur les fichiers présents dans les PR, même si je pense qu'il est pluas sage d'attendre l'outil de traduction.

**Comment by om64** [comment]
@jj-quintin Pour le dernier point, je suis un peu étonné du résultat. Les deux clefs qui génèrent le texte sont présentes dans "collecticiel" et "innova_collecticiel". Le texte "Elle se divise en plusieurs étapes : l'ouverture de l'évaluation en autorisant le dépôt, début de l'évaluation par les pairs qui clôture le dépôt et la fin de l'évaluation." vient de la clef "Planification peer review instruction" qui traite bien de l'évaluation par les pairs. À corriger en dur ?

**Comment by om64** [comment]
@jj-quintin Corrigé et mergé. Dis-moi s'il y a encore des soucis.

**Comment by jj-quintin** [comment]
Je suis allé voir dans les différents fichiers de traduction en lien avec le collecticiel, c'est vrai que c'est un fouillis pas possible. A lire le fichier collecticiel on ne sait pas ce qui est encore utilisé et ce qui relève de l'obsolète (copie de dropzone). Faudrait faire le ménage. Comme le collecticiel a été développé sous la supervision de Donovan, le mieux je pense c'est de lui demander. Il doit savoir

**Comment by jj-quintin** [comment]
> @jj-quintin Corrigé et mergé. Dis-moi s'il y a encore des soucis.

 @om64  oui, je ne vois qui rien qui change dans les collectiel du Master

**Récap**

1)
Toujours 

- Autoriser l'upload de fichiers
- Zones de texte libre
- Ressources (sélection depuis l'espace ressources de la formation)
- Autoriser les liens web

Au lieu de 

- Fichiers (téléversement depuis leur ordinateur)
- Texte libre (rédaction en ligne)
- Ressources (sélection depuis l'espace ressources de la formation)
- Lien Internet (adresse URL)

2) Toujours : 

Ouverture

L'ouverture du collecticiel peut se réaliser de manière manuelle ou en fonction des dates de début (ouverture du collecticiel) et de fin (fermeture).

Elle se divise en plusieurs étapes : l'ouverture de l'évaluation en autorisant le dépôt, début de l'évaluation par les pairs qui clôture le dépôt et la fin de l'évaluation.

Au lieu de : 

Ouverture

L'ouverture du collecticiel peut se réaliser de manière manuelle ou en fonction de dates, de début (ouverture du collecticiel) et de fin (fermeture).

3) Toujours

Aucune copie en attente de correction

Au lieu de  : 

À ce jour, aucune demande ne vous a été adressée

4) Toujours

Rappel des instructions

Au lieu de

Consignes

**Comment by om64** [comment]
@jj-quintin Il faut mettre votre plateforme à jour pour que les changements apparaissent.

**Comment by jj-quintin** [comment]
@om64 

Je travaille sur le master, cf. ticket : 

| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master

**Comment by om64** [comment]
@jj-quintin TB, mais à mettre à jour par ton équipe informatique.

**Comment by jj-quintin** [comment]
@om64  Chez nous il n'y pas de souci. Les problèmes se situent uniquement sur le master, suite aux changements dans les fichiers de traduction
