### ISSUE TITLE
[PathBundle] Réf à #1149 : save & publication button. Le cas du parcours conditionnel

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1219]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

En référence à #1149 fermé

Cela fonctionne maintenanat sauf quand on inclut une condition. Dans ce cas, on retrouve le problème : la publication engendre le statut "non sauvegardé", la sauvegarde, "Publié avec des modifications en attente" et on boucle

**Comment by Elorfin** [comment]
PR #1394 has fixed this.
