### ISSUE TITLE
[CoreBundle] Webpack for plugin creation.

### ISSUE THREAD

**Issue by ngodfraind** [claroline/Distribution#122]
When creating a new plugin, webpack won't read the assets.json file unless you add it in the installed.json file.

We should either:
- Add some documentation to warn the users to do it manually if it doesn't work
- Use the bundles.ini file (because the plugin must be loaded here anyway).
- Use the composer.json plugin file (because it should be there if the plugin is ready)
- Fix the claroline:plugin:create command and ask developpers to use it instead of creating the structure manually (because we can edit the installed.json file here).

**Comment by stefk** [comment]
2 and 3 are doable, but imply also inspecting irrelevant bundles/packages. 4 is ok. Best IMO would be to extract registering logic (bundles.ini + autoload + installed.json) into a dedicated dev class, which could be used by both claroline:plugin:create and a future claroline:plugin:register (as there are cases where you just need registration).
