### ISSUE TITLE
[ExoBundle] Score (exercise, step and question) issues

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1231]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

- The score of a step is sometimes not the good one : the sum is wrong (-1 ?)
http://claroline-master.travis-build.claroline.net/resource/open/ujm_exercise/421#/papers/280
http://claroline-master.travis-build.claroline.net/resource/open/ujm_exercise/421#/papers/281

**Comment by Elorfin** [comment]
@pitrackster : can you have alook please ?

**Comment by pitrackster** [comment]
@eldoniel I'm on it !
