### ISSUE TITLE
Gestion des organisation

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1234]
- [x] Permettre à l'administrateur de l'organisation d’accéder à tous les espaces de l'organisation
- [x] Permettre l'import des membres de l'organisation

**Comment by ngodfraind** [comment]
Ça pourra venir en parallèle lorsque la PR de gestion des modèles sera mergée (car elle modifie la gestion des EA... elle est maintenant en javascript).

Je vais le faire de là.
