### ISSUE TITLE
[CoreBundle] Plugin enable/disable

### ISSUE THREAD

**Issue by ngodfraind** [claroline/Distribution#124]
A few use cases wich should be clarified imo.

1) Cache clearing and bundles.ini. When a plugin is disabled, the cache could be cleared after the bundles.ini file is updated. Cache clearing is very dicey through gui... it's much more safe to do it manually. Also it could have a lot of weird side effects for the user if we're not carreful (like a partial update or sthg like that).

2) Let's assume you created the last post widget of a forum and a forum. Now you disable the plugin. What does happen ? it stays ? it goes away ? New creations are disabled ?

More issues will probably come later on.

**Comment by stefk** [comment]
> like a partial update

What do you mean?

> Let's assume you created the last post widget of a forum and a forum. Now you disable the plugin. What does happen ? it stays ? it goes away ? New creations are disabled ?

All the functionality related to the forum must be disabled IMO, which includes viewing/creating/etc. any related content (resources, widgets, etc.). But as the plugin is just deactivated, I guess it would be a kind of soft delete.

**Comment by ngodfraind** [comment]
Reminder file here: https://github.com/claroline/Distribution/blob/bundle-activation/main/core/PLUGIN_DISABLED.md

If the plugin is disabled, related updates may not be fired although it would still be needed.

Also, please note that I'm using the bundles.ini file to know what's already installed or not (instead of the composer.json) simply because this file already exists in old platforms.

see
-  Claroline\CoreBundle\Library\Installation\OperationExecutor::buildOperationList()
- Claroline\CoreBundle\Library\Installation\OperationExecutor::execute()

Finally, I'd like to remove the installFromKernel method in order to have a unified installation (it's still used in the webinstaller and that's all).

**Comment by ngodfraind** [comment]
Related to #125

**Comment by ngodfraind** [comment]
Fixed by #125
