### ISSUE TITLE
Widget ressources

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1244]
Il serait intéressant d'avoir un widget ressource qui permette de lister les ressources d'un dossier ou d'un tag.
On peut le faire manuellement avec un widget texte mais c'est fastidieux, il faut chaque fois l'adapter quand on veut ajouter ou supprimer un fichier.

L'idéal serait de pouvoir déposer de fichiers directement sur ce widget si on est gestionnaire, cela permettrait de rivaliser définitivement avec Moo...

**Comment by CPASimUSante** [comment]
:+1: for the resource listing in widget.
But i'm not sure dropping resources on that widget is a good idea : that's not done anywhere else on the platform but in the resource manager. A click on the link of the RM would not be that of a pain to upload new documents.

**Comment by clarophil** [comment]
Je pense que l'affichage doit se faire sous forme de liste et pas d'icones sinon cela prendra trop de place.
