### ISSUE TITLE
Problèmes de Responsive design 

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1245]
- Le menu du bureau n'est pas complet sur smartphone, la partie droite n'est pas accessible.
- En vue liste dans le gestionnaire de ressources, les noms de fichiers dépassent 
![image](https://cloud.githubusercontent.com/assets/895878/18880098/0591dfc2-84d7-11e6-8ceb-6f96e5356a90.png)

**Comment by ngodfraind** [comment]
Il faut le faire fonctionner sur quelle résolution ?

**Comment by LaurentGruber** [comment]
320 px ? http://www.creation-spip.fr/les-tailles-d-ecrans-et-le-responsive-design

**Comment by LaurentGruber** [comment]
plus tôt le breakpoint de bootstrap 480px
