### ISSUE TITLE
[CoreBundle] & [ExoBundle] Bug - exportation espace activités - QTI -Tag HTML audio

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1255]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Produit lors de l'exportation d'un espace d'activités 
![image](https://cloud.githubusercontent.com/assets/16414632/18914375/31bb6a44-858d-11e6-8b9e-2c964709cb04.png)

et exportation des questions de cet espace (Warning: DOMDocument::loadHTML(): Tag audio invalid in Entity, line: 2 in /var/www/html/claroline/vendor/claroline/distribution/plugin/exo/Services/classes/QTI/QtiExport.php on line 170)

> Problème HTML avec code de type 
`<audio preload="auto" controls="controls">
    <source src="/file/resource/media/110" type="audio/mp3" /></audio>`

**Comment by Elorfin** [comment]
duplicate #1097
