### ISSUE TITLE
[CoreBundle] Bug - Importation csv nouveaux utilisateurs - Nom/Prénom avec accents

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1261]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Import d’utilisateurs : problème avec les caractères accentués

Voir résultat ci-dessous : identifiant testaccent

Prénom "étudiant" => vide
Nom "Clémentine" => Cl

![image](https://cloud.githubusercontent.com/assets/16414632/18945088/14b5088c-8629-11e6-9e56-eb8df18a8b09.png)

**Comment by ngodfraind** [comment]
Le CSV était-il formatté en UTF-8 ? C'est un prérequis pour que les caractères spéciaux fonctionnent.

**Comment by jj-quintin** [comment]
.... notre administrateur avait oublié
Au temps pour nous
Désolé
