### ISSUE TITLE
[CoreBundle] Espace des ressources - Liste - % devant variable

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1262]
| Q | A |
| --- | --- |
| Bug report? | no |
| Version? | master |

% superflus : 

![image](https://cloud.githubusercontent.com/assets/16414632/18945507/2a32ebe6-862b-11e6-933d-669aaf233d07.png)

**Comment by ngodfraind** [comment]
Ce n'est pas le cas en local chez moi (master également).

**Comment by jj-quintin** [comment]
En ligne (master), le problème se poser 

Voici le lien  : 

http://claroline-master.travis-build.claroline.net/workspaces/7/open/tool/resource_manager

Mais c'est un détail à ce stade

**Comment by ngodfraind** [comment]
Ok, c'est vu.
