### ISSUE TITLE
[MessageBundle]  Préciser l'expéditeur en from lors de l'envoi par email 

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1264]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      |

Je propose de mettre l'expéditeur en from du mail envoyé par la messagerie à la place du mail générique du genre noreply.  Cela permet directement de répondre à une question sans passer par la messagerie.

**Comment by LaurentGruber** [comment]
On ne peut pas le faire, les serveur de mail ne l'accepterais pas et on risque encore plus d'être considéré comme spam. Donc ce qui a été fait ici c'est mettre le mail de l'expéditeur dans le reply-to comme ça si on fait répondre au mail ça envoie à l'adresse de l'expéditeur (voir https://github.com/claroline/Distribution/pull/1248 ).
