### ISSUE TITLE
Notification inutile aux collaborateurs

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1265]
| Q | A |
| --- | --- |
| Bug report? | no |
| Version? | master |

Une notification est envoyée à TOUS les collaborateurs à chaque soumission d'un fichier.  C'est d'autant plus inutile que si le collaborateur clique sur le lien dans la notification, il reçoit un message disant qu'il n'y a pas accès.
- [x] Je propose d'envoyer cette notification uniquement aux gestionnaires.

**Comment by clarophil** [comment]
De plus Collecticiel n'est pas paramétrable dans Préférence / Notification

**Comment by ngodfraind** [comment]
Je pense que ça vient d'ici:

https://github.com/claroline/Distribution/blob/master/plugin/collecticiel/Controller/DropzoneController.php#L149

https://github.com/claroline/Distribution/blob/master/plugin/collecticiel/Controller/DropzoneController.php#L308

Mais je n'en suis pas sûr:
@claroline/innova un peu d'aide ?

**Comment by clarophil** [comment]
Autre problème au niveau des notifications 

- [ ] Lorsqu'un étudiant dépose un document sur le collecticiel, c'est le nom du responsable de l'espace qui est indiqué comme "déposant" dans les notifications alors qu'on devrait y voir le nom de l'étudiant.  Par contre, c'est correcte lorsque l'étudiant fait la demande de correction.

**Comment by clarophil** [comment]
- [ ] Quand une note est attribuée, il faut notifier l'utilisateur

**Comment by nicolasjacquemet** [comment]
Compilé dans #4486
