### ISSUE TITLE
See default opend the activity spaces

### ISSUE THREAD

**Issue by MisterTarock** [claroline/Distribution#1266]
| Q | A |
| --- | --- |
| Bug report? | no |
| Version? | master |

It would be nice to see the different activity space opend by default
![screenshot_20160929-131923](https://cloud.githubusercontent.com/assets/9462706/18951815/62f63516-8647-11e6-9c52-7f1967b0d581.png)

**Comment by ngodfraind** [comment]
@MisterTarock  Can you explain a little bit more ? I don't really understand. You want everything opened by default ?

**Comment by MisterTarock** [comment]
Especially the 3BE and 2BE folders in my case :) 
The best would be a parameter where anyone could choose which one folders they want opend by default or not.

**Comment by MisterTarock** [comment]
Especially the 3BE and 2BE folders in my case :) 
The best would be a parameter where anyone could choose which one folders they want opend by default or not.

**Comment by LaurentGruber** [comment]
@clarophil c'est fait non ?
