### ISSUE TITLE
[CoreBundle] Page d'accueil avec listing de cours

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#1272]
| Q | A |
| --- | --- |
| Bug report? | no |
| Version? | 7.0.0 |

Sur les pages de la page d'accueil il me semble qu'il serait utile de pouvoir avoir un outil (Widget ?) qui permettrait de lister l'ensemble des espaces d'activité. Ce listing qui est sur Claroline 1.x - très traditionnel je suis d'accord - est utile pour montrer ce qui se fait sur la plateforme. C'est un moyen de communication vers les parents, les institutions, sans cela le monde extérieur n'a aucune idée de ce qui s'y fait.

**Comment by ngodfraind** [comment]
?

**Comment by Garakotxea** [comment]
Je ne pense pas l'avoir mis où il fallait, je n'ai pas su le supprimer alors je l'ai fermé. Désolé pour le dérangement. Je suis un peu perdu dans cet espace.
N'est-ce pas plutôt dans Pull requests ou Project.
Je ne suis pas assez à l'aise en anglais pour bien me repérer.

**Comment by ngodfraind** [comment]
Non, c'est très bien. C'est effectivement ce que nous appelons une issue.

Une pull request est un changement de code proposé par un développeur.

**Comment by Garakotxea** [comment]
Merci pour l'intervention.
