### ISSUE TITLE
[AnnonceBundle] Envoi d'une annonce à la messagerie impossible si des dates sont définies

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1275]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master |

Créer une annonce
Mettre une date passée et une date future
Cocher Notifier l'utilisateur n'est plus cochable alors que la date Du est passée

**Comment by clarophil** [comment]
Il faudrait aussi expliquer pourquoi la notification n'est pas possible.

**Comment by kitan1982** [comment]
A "send announcement" button will be added. It can temporarily solved this issue.

**Comment by clarophil** [comment]
Ok pour l'explication mais il reste qu'on pourrait autoriser l'envoi si on a dépassé le date indiquée dans le DU
Cas d'utilisation, un prof met une annonce avec des dates DU et AU.  Une fois le DU dépassé il veut faire une relance de l'annonce en envoyant un email.
