### ISSUE TITLE
Amélioration des emails envoyés à partir de la messagerie

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1276]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | NA

- [ ] Envoyé le mail avec en From l'adresse email de l'expéditeur

- [x] Ajouter dans l'objet du mail le code de l'espace

- [x] Ajouter à la fin du message du code et du nom de l'espace

**Comment by ngodfraind** [comment]
@clarophil 
le champ from de l'adresse email de l'expéditeur, c'est pas possible. On peut mettre un reply-to mais sinon le serveur mail va raler.

**Comment by clarophil** [comment]
On peut mettre son mail dans la signature alors.
