### ISSUE TITLE
Modèle d'EA - Couleur, utilisateurs, groupes, raccourci

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1278]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master

La création d'un EA sur la base d'un modèle d'espace d'activités ne récupère pas 

- la couleur des onglets
- la couleur des caractères du titre des widget
- la couleur de fond de l'EA
- apparemment ni les utilisateurs ni les groupes inclus dans le modèle

- Un modèle avec une **copie** d'un raccourci fonctionne bien (le nouvel EA oriente bien vers la ressource en question)
- Un modèle avec un **lien** vers un raccourci ne fonctionne pas (le nouvel EA oriente vers une autre ressource)

**Comment by LaurentGruber** [comment]
les utilisateurs et les groupes c'est voulu. Le principe des modèles est de copier des contenus de formation pour permettre à d'autres utilisateurs de suivre la formation.

On ne devrait pas permettre de faire des lien avec des raccourci, cela crée des raccourcis de raccourcis ce qui devient ingérable. Le reste devrait être copié c'est à dire : 

- [ ] la couleur des onglets
- [ ] la couleur des caractères du titre des widget
- [ ] la couleur de fond de l'EA
