### ISSUE TITLE
Modèle & Gestion des formations

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1281]
| Q | A |
| --- | --- |
| Bug report? | yes/no |
| Version? | master |

D'une manière générale, les EA construits 
- sur la base d'un modèle d'un EA d'origine
- qui comportent des liens vers des ressources de l'EA d'origine 

orientent vers l'EA d'origine

L'utilisateur démarre donc normalement son EA
Clique sur  un ressource
et se retrouve dans une autre EA (EA qui a servi pour construire le modèle)

**Comment by LaurentGruber** [comment]
réglé avec https://github.com/claroline/Distribution/pull/2218
