### ISSUE TITLE
[PathBundle] Ressource URL non lue dans une étape du parcours

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1286]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Ajouter une ressource URL https://www.youtube.com/watch?v=6r63HXUMn1g 
Créer un parcours
Ajouter l'URL en ressource principale
Sauver et publier

L'étape ne lit pas l'URL, cela fonctionne avec certaines URL et pas avec d'autres

http://claroline-master.travis-build.claroline.net/innova_path/player/29#/98

**Comment by ngodfraind** [comment]
Reproduit:

```
Security Error: Content at https://www.youtube.com/watch?v=3LyFap2aUN0 may not load data from http://localhost/nico/ClaroMono/web/app_dev.php/innova_path/player/4#/8.Load denied by X-Frame-Options: https://www.youtube.com/watch?v=3LyFap2aUN0 does not permit cross-origin framing.
```

**Comment by ngodfraind** [comment]
http://stackoverflow.com/questions/6666423/overcoming-display-forbidden-by-x-frame-options

**Comment by CPASimUSante** [comment]
@clarophil Comme le suggère Nicolas, peux-tu tester dans un premier temps https://www.youtube.com/embed/6r63HXUMn1g à la place de https://www.youtube.com/watch?v=6r63HXUMn1g ?

**Comment by clarophil** [comment]
oui ça marche avec embed

**Comment by CPASimUSante** [comment]
@clarophil Faut il fermer ce ticket (quitte à expliquer aux utilisateurs la procédure) ?

**Comment by clarophil** [comment]
@ngodfraind @LaurentGruber @CPASimUSante il y a d'autres URL qui foire, une simple URL vers http://www.ecam.be
http://claroline-master.travis-build.claroline.net/innova_path/player/29#/97

**Comment by ngodfraind** [comment]
C'est pareil pour l'url de l'ecam

```
Load denied by X-Frame-Options: http://www.vinci.be/fr-be/ecam/Pages/Accueil.aspx does not permit cross-origin framing.
```

Le webserver ajoute des headers qui demandent au navigateur de ne pas permettre l'affichage dans une iframe. Il y a peut-être moyen de configurer le navigateur (et certainement des navigateurs qui n'implémentent pas cette norme) mais à partir du moment ou le site en question demande d'éviter d'afficher son contenu dans une iframe, je pense qu'il vaut mieux le laisser comme ça.
On pourrait sans doute trouver un hack mais ça me parait douteux comme manière de faire.

C'est aussi une protection contre le "clickjacking" apparement.

http://javascript.info/tutorial/clickjacking
