### ISSUE TITLE
Tableau dans Tiny Exos

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#1288]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 7.0

L'outil tableau n'est pas disponible dans l'éditeur de question. J'ai récupéré des questions de Claroline 1.11.10 mais il n'est modifiable qu'en html.
J'utilise pas mal cet outil pour y inclure des zones à écrire ou des listes déroulantes.
![exemple tableau exos](https://cloud.githubusercontent.com/assets/22524770/19013781/4a74d552-87db-11e6-9ca7-bd38194e17ec.png)

Bien à vous.

**Comment by Pauooo** [comment]
Il est possible de créer un tableau dans le "cloze text" (il faut que l'éditeur de texte soit en "fullscreen")  puis de rajouter des trous. 
![capture du 2016-10-03 09 56 30](https://cloud.githubusercontent.com/assets/15014599/19030777/4e3f6578-8950-11e6-9e4d-0c72ae7c7af8.png)
J'espère que ça répond à votre remarque.

**Comment by Garakotxea** [comment]
Merci beaucoup. J'utilise très peu le plein écran et je n'avais pas retenu que des menus s'ajoutaient.
Merci encore et bonne journée.

**Comment by ngodfraind** [comment]
Du coup je ferme.
