### ISSUE TITLE
[DevBundle]

### ISSUE THREAD

**Issue by ngodfraind** [claroline/Distribution#129]
Should this bundle be integrated here ?

**Comment by stefk** [comment]
See #5 and claroline/DevBundle#13. If it's integrated as a complete bundle, IMO it should go in *main* and a .gitattribute file must exclude it from prod archives.

Also the branch to fetch would be "monolith", not master.

**Comment by ngodfraind** [comment]
Ok, will do today.

**Comment by stefk** [comment]
Closed by #132.
