### ISSUE TITLE
[AgendaBundle] Ergonomie Encodage date et heure dans l'agenda

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1300]
| Q | A |
| --- | --- |
| Bug report? | no |
| Version? | master |

Ajouter un événement
La sélection de l'heure n'est pas facile, il faut sur l'heure puis effacer puis entrer les chiffres, idem pour les minutes, les flèches du clavier change la date même si on est sur l'heure.  Il y a bien un bouton en dessous mais personne ne le voit.

Je propose de séparer en 2 champs différents l'encodage de la date et de l'heure de l'événement, cela permettrait aussi de mettre datepicker et un timepicker, de pouvoir utiliser le tab pour passer de champ en champ et les flèches pour augmenter ou diminuer.

**Comment by om64** [comment]
Même souci dans le ReservationBundle.
