### ISSUE TITLE
[PDFPlayer]  Page inversée

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1303]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master |
- [x] Lors du visionnage d'un fichier PDF, si l'on change rapidement de page plus d'une fois, la page apparait inversée. La même chose arrive en cliquant rapidement sur le bouton de zoom. 
- [ ] On ne peut pas sélectionner le texte, serait-il possible d'avoir un lecteur qui le permette ?

![bugpdf](https://cloud.githubusercontent.com/assets/895878/19070685/cc6a382e-8a2c-11e6-876b-7ab0a71fee9a.jpg)

**Comment by CPASimUSante** [comment]
Concernant le texte inversé, testé sur le claroline master, je n'ai pas réussi à reproduire. Testé sur Chrome, IE11, Firefox
J'ai cliqué sur suivant rapidement (6 ou 7 pages en 1 s), j'ai cliqué alternativement sur suivant/précédent plusieurs fois sans avoir le problème : 
=> peux-tu indiquer l'OS/navigateur(+version) sur lequel ça plante
Y a t'il des erreurs js associées en console ?
Est-ce pour tous les pdf, ou bien certains ? => au pire, fournir un pdf qui pose problème

**Comment by pocpoc47** [comment]
[seance6-relations+2.pdf](https://github.com/claroline/Distribution/files/577984/seance6-relations.2.pdf)

Celui-ci pose problème lorsqu'on clique rapidement sur le bouton de zoom.

[EJB_3_-_seance_6.pdf](https://github.com/claroline/Distribution/files/577991/EJB_3_-_seance_6.pdf)

Et celui-ci lorsqu'on clique sur suivant rapidement.

![pageinversee](https://cloud.githubusercontent.com/assets/23334174/20097370/5dc70562-a5ae-11e6-8542-46c87aceacbd.png)

**Comment by CPASimUSante** [comment]
EJB_3_-_seance_6.pdf, testé sans bug sur Windows 7 (clics rapide sur suivant, précédent...) 
seance6-relations+2.pdf, testé sans bug sur Windows 7 (clics rapide sur zoom) 
- Chrome 54
- Internet Explorer 11
- Firefox 38 ( je ne peux pas mettre à jour FF dans mon entreprise)

Donc soit c'est un pb spécifique à FF > 38 pour le premier cas, soit windows 10 pour le second, auquel cas je ne peux reproduire. :(
