### ISSUE TITLE
[Administration] Impossible d'ajouter un rôle administrateur

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1304]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Adminstration / Gestion des utilisateurs
Ajouter un rôle administrateur à un utilisateur existant
J'ai essayé 2 modes, aucune ne fonctionne 
1.En éditant la fiche de l'utilisateur et en cochant Administrateur
2.En sélectionnant l'utilisateur  puis le rôle puis Ajouter des rôles

![image](https://cloud.githubusercontent.com/assets/895878/19072543/107249b8-8a36-11e6-9424-84bb74f79ac5.png)

**Comment by ngodfraind** [comment]
En éditant la fiche de l'utilisateur, ça a bien fonctionné pour moi (sur le master).
Depuis le listing par contre, pas moyen. Je cherche d'ou ça peut provenir.
