### ISSUE TITLE
[Ecoute active enrichie] : PB dans l'aide 

### ISSUE THREAD

**Issue by jypfcl** [claroline/Distribution#1315]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master |

La boucle ne fonctionne pas. Le segment est répété une fois, puis le texte est lu jusqu'au bout

**Comment by pitrackster** [comment]
@jypfcl Bonjour Jean-Yves

> Le segment est répété une fois, puis le texte est lu jusqu'au bout

S'agit-il de la lecture "backward building" utilisant le TTS ?

Pourrais-tu fournir un lien vers un exemple sur http://claroline-master.travis-build.claroline.net/ et indiquer la procédure à suivre pour reproduire le problème ? (via copies d'écran ou explications ?)

Merci d'avance

**Comment by jypanne** [comment]
Voici l'explication du pb de boucle
[PB_boucle_ecoute active.zip](https://github.com/claroline/Distribution/files/523719/PB_boucle_ecoute.active.zip)
