### ISSUE TITLE
[Ecoute active enrichie] PB de libellés

### ISSUE THREAD

**Issue by jypfcl** [claroline/Distribution#1316]
| Q | A |
| --- | --- |
| Bug report? | no |
| Version? | master |

Il faudrait changer les libellés comme suit : 1/ Ecoute avec pauses 2/ Ecoute libre 3/ Ecoute avec aides immédiates 4/ Ecoute avec aides différées

**Comment by Pauooo** [comment]
@jypfcl / Bertrand
Il faut aussi créer les textes des infos bulles nécessaires à la compréhension de l'éditeur et du player.
