### ISSUE TITLE
[MessageBundle] Une image dans le message n'apparaît pas dans le mail

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1317]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master |

Messagerie
Nouveau
Insérer un texte et une image soit téléchargée soit ajoutée à partir des ressources

Si le destinataire a coché Envoyer une copie des messages par email 
L'image n'apparaît pas dans le mail

**Comment by ngodfraind** [comment]
Est-ce qu'on veut vraiment envoyer les images par emails maintenant ?

Pour le moment je pense que ce n'est pas une bonne idée, nous avions parlé avec Laurent d'utiliser une techno spéciale (je ne me souviens plus du nom) pour permettre ce genre de chose plus facilement (avec un langage de markup spéciale qui générait du html valide derrière) car actuellement c'est un peu compliqué à faire quelque chose de passe partout.

@LaurentGruber C'était quoi d'ailleurs le mode de node qui faisait ça ?

**Comment by LaurentGruber** [comment]
c'était ceci : https://mjml.io/

**Comment by LaurentGruber** [comment]
@clarophil toujours présent sur le master ?

**Comment by clarophil** [comment]
@LaurentGruber 
Je ne sais pas tester car le master travis n'a pas de serveur mail configuré
