### ISSUE TITLE
Activity selection in background not selectable

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#1320]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

The ressource selection in Activity creation in background is not usable : the popup is behind.

![activite](https://cloud.githubusercontent.com/assets/14015697/19106890/f243a478-8ae9-11e6-912c-e3f3ea3c35cc.jpg)

**Comment by ngodfraind** [comment]
LGTM
