### ISSUE TITLE
Deconnection trop rapide

### ISSUE THREAD

**Issue by KB1395** [claroline/Distribution#1331]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master

ClaCo déconnecte les utilisateurs beaucoup trop rapidement (suffit de lire un PDF pendant quelques minutes et il faut a nouveau s'identifier).
De plus, il n'y a pas de connection automatique (pas besoin de identifier a chaque consultation: 1 compte sur 1PC privé)

**Comment by ngodfraind** [comment]
A mon avis il faut configurer la durée de vie du cookie dans l'administration.
