### ISSUE TITLE
Thème spécifique

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1336]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 

Ce serait intéressant de pouvoir créer un thème qui se base sur un thème de base.  Cela permet d'avoir les maj sur le thème de base et de n'avoir le spécifique que sur des détails de la CSS.

**Comment by LaurentGruber** [comment]
@stefk tu as mis easy-pick, tu imagines ça comment (je ne vois pas de solution simple et rapide) ?

**Comment by stefk** [comment]
@LaurentGruber, pour le moment, un thème custom, c'est une seule feuille css, qui remplace complètement la feuille de style par défaut. Avec cette fonctionnalité, on continuerait d'inclure une des css de base (i.e. un des thèmes standard choisis par l'utilisateur) et on ajouterait *à la suite* le fichier css custom fourni lors de la définition du thème. Ce dernier fichier pourrait donc ne contenir que des modifications mineures surchargeant le layout par défaut, et les mises à jour seraient nettement plus prévisibles.

**Comment by stefk** [comment]
Pour être clair : on rajoute un champ "base_theme" dans la table claro_theme et si ce champ n'est pas null, on inclut le css correspondant avant celui du thème sélectionné. Si c'est null, on garde le comportement actuel.

En gros, c'est juste une option supplémentaire dans le formulaire de création des thèmes, plus une propriété dans l'entité Theme et une ou deux lignes dans le layout twig.
