### ISSUE TITLE
[ExoBundle] Negative scores

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#1337]
| Q | A |
| --- | --- |
| Bug report? | no |

Negative scores should be allowed and taken into account when computing the score of an exercise. The score of both questions and steps may be negative. Only the total score of the exercise must be floored to >= 0.

**Comment by Elorfin** [comment]
To be done, we will need to find an other way to flag questions which need manual correction.

For now, we know it because in this case : score == -1. If we allow negative scores, this test is no more relevant.

**Comment by Elorfin** [comment]
the new version of quizzes allows negative scores.
