### ISSUE TITLE
[CoreBundle] Paramétrage du bouton login

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1339]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      |

Avec O365, on a lié le bouton login directement sur l'authentification o365 mais à chaque mise à jour c'est écrasé.

Ce serait bien d'avoir un paramètre de config de la plateforme du login target

Modification à faire actuellement
Fichier : main/core/Controller/LayoutController.php
Ligne 197: ("$loginTarget = $this->router...")
  -> remplacer 'claro_security_login' par 'claro_o365_get_token'

**Comment by ngodfraind** [comment]
Tu préfères mettre le nom de la route ou une url complête ?
