### ISSUE TITLE
Proposal for deprecated repos

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#135]
Repositories that were merged into this one must remain active for compatibility reasons, but it should be clear to everyone that their development has moved here. That information is particulary needed on github and packagist.

Proposed changes:

1. Prefix the description with `[Moved to claroline/Distribution]`
2. Disable issues and wiki in the settings.
3. Add a deprecation warning in the README: 

```markdown

WARNING
-------

**DEVELOPMENT HAS MOVED TO [claroline/Distribution](http://github.com/claroline/Distribution). 
THIS REPOSITORY IS NO LONGER MAINTAINED.**
```

Example [here](https://github.com/claroline/DevBundle).
 
@claroline/commiters

**Comment by purplefish32** [comment]
I have changed : 

https://github.com/InnovaLangues/PathBundle/blob/master/README.md
https://github.com/InnovaLangues/CollecticielBundle/blob/master/README.md
