### ISSUE TITLE
[CursusBundle] Register learners to a session button do not work

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1350]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

In the Trainings management, when I click on a training / open sessions panel, the "register learners to training session " doesn’t have any effect.
http://claroline-master.travis-build.claroline.net/admin/open/claroline_cursus_tool#/courses/4

**Comment by kitan1982** [comment]
This button shoudn't be there.
It will be removed.
