### ISSUE TITLE
[supportBundle] Fenêtre Création de ticket inaccessible

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1353]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master travis

La fenêtre de création de ticket apparaît à l'arrière et est donc inaccessible 
![image](https://cloud.githubusercontent.com/assets/895878/19228830/30dd3db0-8ec9-11e6-93ba-09432ff3338b.png)

**Comment by kitan1982** [comment]
I cannot reproduce the issue.
A similar bug has been fixed by #1324

**Comment by CPASimUSante** [comment]
same kind as https://github.com/claroline/Distribution/issues/1320 ? Isn't fixed on claroline-master.travis yet. How often the master build is updated ?

**Comment by clarophil** [comment]
Je n'ai plus l'erreur sur le master travis aujourd'hui
