### ISSUE TITLE
[CollecticielBundle] Transmette une évaluation par notation échoue

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1355]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master travis

Créer un collecticiel avec une notation pour l'évaluation
Soumettre un travail
Transmettre une demande d'évaluation
Cliquer sur l'icone évaluation
Ajouter une cote
Le bouton Enregistrer fonctionne 
Le bouton Echoue échoue et propose une création de ticket
![image](https://cloud.githubusercontent.com/assets/895878/19228946/1169702e-8eca-11e6-81c6-13ea2a4d7d4a.png)
Après en cliquant sur la bouton transmettre dans la liste des demandes adressées, cela fonctionne la note est bien transmise

**Comment by kitan1982** [comment]
Je n'ai pas réussir à reproduire le bug.
Je n'ai pas compris les étapes suivantes : 
- Le bouton Enregistrer fonctionne
- Le bouton Echoue échoue et propose une création de ticket

**Comment by clarophil** [comment]
update
Le bouton **Transmettre** échoue et propose une création de ticket

**Comment by clarophil** [comment]
@kitan1982 
il faut cliquer sur le /20
![image](https://cloud.githubusercontent.com/assets/895878/19269120/da4070d0-8fb8-11e6-8d44-f5b761359d94.png)

Encoder une cote
Puis transmettre

**Comment by kitan1982** [comment]
Je n'arrive pas à obtenir le "/20".
Chez moi, il met automatiquement "0/20" si aucune valeur n'est entrée au moment de l'enregistrement.
Par contre, si j'essaie de transmettre directement une cote vide sans l'enregistrer avant, j'obtiens bien une erreur avec la modal pour la création d'un ticket.

**Comment by clarophil** [comment]
Cette issue n'est pas résolue, voir url ci-dessus.  Si on encode une valeur et qu'on clique sur Transmettre, on n'a plus d'erreur mais il n'enregistre rien.

**Comment by kitan1982** [comment]
Chez moi, ça fonctionne.
Par contre, comme mentionné plus haut, je n'arrive pas à obtenir une cote vide (/20).
Par défaut, il me met 0/20.

**Comment by clarophil** [comment]
@kitan1982 @LaurentGruber chez nous (mis à jour le 16/10) et sur le master travis ça ne fonctionne pas donc il faudrait réinstaller une version clean chez toi car je ne vois pas ce que je peux faire de plus ?

**Comment by kitan1982** [comment]
C'est bon. J'ai réussi à reproduire le bug.
Il est juste présent en prod.
En dev, les notes s'affichent correctement.
C'est vraiment bizarre.

**Comment by clarophil** [comment]
Bonne nouvelle :)
