### ISSUE TITLE
[Collecticielbundle] Alerte intempestive 

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1356]
| Q | A |
| --- | --- |
| Bug report? | yes/no |
| Version? | master/7.0/etc. |
- [x] Les alertes apparaissent inutilement 
- [x] Le bouton Suavegarder n'est pas dans le cadre

![image](https://cloud.githubusercontent.com/assets/895878/19229397/7f2d1ff4-8ecd-11e6-8850-27e7072bc0dc.png)

![image](https://cloud.githubusercontent.com/assets/895878/19229387/69ed6022-8ecd-11e6-8ae6-5b64c22fcb55.png)

**Comment by CPASimUSante** [comment]
Not related specifically to Collecticiel : same on PathBundle

**Comment by CPASimUSante** [comment]
I close this one : tested on master, the bug are not there anymore
