### ISSUE TITLE
[AgendaBundle] Import ICS échoue

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1360]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

- [x] Import ICS échoue

- [x] Libellé de la case d'import non traduit

- [ ] Amélioration : permettre l'import et l'export d'un flux plutôt que d'un fichier

Ouvrir le calendrier du bureau
Importer un fichier ICS

![image](https://cloud.githubusercontent.com/assets/895878/19233416/a5336740-8ee5-11e6-975e-6d9b0166e23b.png)

**Comment by ngodfraind** [comment]
Pour l'amélioration il faudra un ticket séparé je pense. L'import d'un flux je vois pas trop, (mais faire un flux RSS à partir du calendrier devrait pas y avoir de problème).
