### ISSUE TITLE
[ExoBundle] Bind question feedback issue

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1361]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master/7.0/etc. |

In a question to bind (match type) If a user make all the connections possible, the immediate feedback is valid. 

![](https://files.gitter.im/pitrackster/QO9R/to_bind_youpi.png)

**Comment by Pauooo** [comment]
Its the same for all type of question : if the number of valid answer = number of expected answer, so the feedback is valid

**Comment by CPASimUSante** [comment]
What is the policy for the question marking (regardless of the kind of question)? 

If one answer A is expected, and the answers A (good answer) and B and C (bad answer) are given.
In a matching question or in a multiple choice, this is obviously wrong : anyone would match everything to have a perfect score (unless the expected answer is no match at all, is that possible yet ?)

In any way, the full point should not be given. The point should be 0 ATM, but (and i think we're not there yet), a rule with decreasing point could also be set (the more you make connection, the less you have point : something like A => 1 point. B or C => 0. A and B or A and C=> 0.33 (1/3), A and B and C => 0 ...)


Maybe for now, somewhere near https://github.com/claroline/Distribution/blob/master/plugin/exo/Resources/modules/question/Services/Type/MatchQuestionService.js#L173 
in the match question (but the same goes for multiple choice, there should be a test to check if the answer is unique (one good answer and NO bad answer)
