### ISSUE TITLE
[ExoBundle] Importation impossible à partir de la banque de questions

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1362]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master travis

Créer un exercice
Importer des questions 
Sélectionner une question 
Importer 
-> Erreur de la console Uncaught SyntaxError: missing ) after argument list

**Comment by ngodfraind** [comment]
J'ai rajouté urgent car c'est cassé chez un de nos clients qui en a besoin. Ça à l'air simple à corriger.
