### ISSUE TITLE
[CoreBundle]  Administration / Mise à jour des utilisateurs efface la case cochée dans la messageire

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1364]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master |

Dans Administration
Gestion des utilisateurs
Importer 
Mode Mise à jour
Sélectionner le csv
Tous les utilisateurs sont mis )à jour 
MAIS ils ont perdu la case Recevoir une copie des messages sur ... dans la messagerie, 
Après la mise à jour toutes les cases ont été décochées

**Comment by ngodfraind** [comment]
Je peux avoir un exemple de csv ? je me demande s'il ne manque pas un flag dedans.

**Comment by clarophil** [comment]
[test.txt](https://github.com/claroline/Distribution/files/521683/test.txt)
Le csv fonctionne très bien, le problème c'est qu'il met à jour des informations qu'il ne devrait.

**Comment by ngodfraind** [comment]
merci

**Comment by ngodfraind** [comment]
@clarophil 

A mon avis c'est car la checkbox "activer les notifications par emails" n'était pas sélectionnée. Je me demande s'il n'est pas pertinent de la retirer car on peut le configurer dans le csv.

**Comment by LaurentGruber** [comment]
@clarophil c'est ok pour toi ?

**Comment by clarophil** [comment]
@LaurentGruber @ngodfraind 
oui c'est bon pour moi mais cela vaudrait la peine de documenter toutes les options de l'import csv dans la page d'import
