### ISSUE TITLE
Error with copy/paste resource from one WS to another

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#1390]
| Q | A |
| --- | --- |
| Bug report | yes |
| Version | master |

On the latest master (travis), i am the admin john doe, and i am in a WS : i copy a resource there. I go in another WS and i want to paste that resource : i have an error 500

**Comment by LaurentGruber** [comment]
tu fais comment ton copier / coller, je n'arrive pas à reproduire

**Comment by CPASimUSante** [comment]
Bon je speak french alors ...
en tant que John Doe sur le master, dans l'espace de ressources de mon espace "test SimUSanté" je coche la ressource "test cartes", je clique sur l'icone copier.
je clique sur le lien "Ressources" dans le fil d'Ariane
je choisis un dossier d'un autre Espace
je clique sur l'icone "coller"

j'ai l'erreur 500
http://claroline-master.travis-build.claroline.net/resource/copy/97?ids%5B%5D=424

**Comment by CPASimUSante** [comment]
Déjà, est-ce prévu de pouvoir faire des copier coller entre espace ? (ça serait bien)

**Comment by LaurentGruber** [comment]
je n'arrive pas à avoir l'icone coller actif dans un autre espace. Normalement oui c'est possible.
Tu peux essayer avec une autre ressource que flashcard, je pense que la copie de flashcard n'est pas implémentée encore

**Comment by CPASimUSante** [comment]
1) Le résultat que je viens de te donner est reproductible avec la méthode que j'ai indiqué.
2) tu as je pense raison pour la flashcard : j'ai testé la même méthode avec un exercice et ça fonctionne : la copie n'est pas implémentée (et lache un bug)
3) j'ai tenté de faire une copie d'un exercice dans un espace, puis d'aller dans le menu déroulant en haut pour choisir un autre espace, j'ai choisi un autre espace, je suis allé dans son gestionnaire de ressource : **on ne peut pas coller** (icone inactive) : je pense que le copie coller doit intégrer des variables JS qui ne sont pas transportées de page en page...

**Comment by kitan1982** [comment]
Le copier/coller dans des espaces d'activités différents ne fonctionne que depuis l'outil "Ressources" du bureau
