### ISSUE TITLE
how to update from claroline-1.9.7 to claroline-1.11.1

### ISSUE THREAD

**Issue by jemmeli** [claroline/Distribution#1398]
hi,

how to update from one claroline older version like 1.9.7 to a 1.11.1 version ?

**Comment by stefk** [comment]
Hello,

Claroline 1.x isn't officially supported anymore. This repository contains the sources of the next version of the platform ("connect"), which is totally new and different. We can't provide any advice related to the 1.x series. However, if you have a specific question, you might get an answer there: https://github.com/zefredz/claroline.

**Comment by jemmeli** [comment]
stefk , thank you for responding me , I am developper and have client have many contents e-learning built up on 1.9.7 version i want to update to specific version like 1.11.1 without losing the data . 
it is possible to do the update ?
