### ISSUE TITLE
ExoBundle : Bug exercise correction

### ISSUE THREAD

**Issue by charlotte42** [claroline/Distribution#140]
Dans un exercice si on change les questions et qu'il y a deja des copies, l'affichage de la correction des anciennes copies sont avec les nouvelles questions.

In an exercise when you change questions and which already has copies, the display of the correction of old copies with new questions.

**Comment by Elorfin** [comment]
@marion42 : Can you checkout the branch `exo-improve-papers` and test it ? It's possible that it fixes the problem.

It's still WIP so you may encounters other bugs.

**Comment by Elorfin** [comment]
The code which fix the problem is the methods `PaperManager::exportPaperQuestions(Paper $paper)` and `PaperManager::getPaperQuestions(Paper $paper)`.

**Comment by marion42** [comment]
@Elorfin : Thanks you, but the problem isn't correct. I think the mistake is in PaperManager::exportPaperQuestions(Paper $paper), $question couldn't be find by exercise but by paper.

**Comment by Elorfin** [comment]
@marion42 : Yes the method uses `getOrderQuestion` to get the list of Questions to load. So you only get list of questions linked to the Paper.

```
private function getPaperQuestions(Paper $paper)
    {
        $ids = explode(';', substr($paper->getOrdreQuestion(), 0, -1)); // <-- HERE YOU ONLY GET QUESTIONS LINKED TO THE PAPER

        $questions = [];
        foreach ($ids as $id) {
            $question = $this->om->getRepository('UJMExoBundle:Question')->find($id);
            $questions[] = $question;
        }

        return $questions;
    }
```

**Comment by Elorfin** [comment]
OK, I understand the problem. It's in `PaperManager::getStepsQuestions`, it uses the `StepQuestion` to create the `paper.order` array which is used to display questions in the Player and in the Paper.

**Comment by marion42** [comment]
Yes, I think too, because in `PaperService.js::orderQuestions` don't return all the questions of the paper. And it's base one the paper order.
