### ISSUE TITLE
[CoreBundle] Administration>Parameters>General : display issue

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1406]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master/ |

In Administration>Parameters>General the radio button for the portfolio url has a display issue : tne radio button is displayed on "start with http://"

http://claroline-master.travis-build.claroline.net/admin/parameters/general

**Comment by CPASimUSante** [comment]
This is for me on Chrome and IE11 on the master. Could you check again or give the browser you test on.
![portfolio](https://cloud.githubusercontent.com/assets/14015697/19835524/de471a32-9e89-11e6-86e2-5e6d612c0366.png)

**Comment by Pauooo** [comment]
I'm on Firefox and it's like that when screen is 1280x600 and bigger
![capture du 2016-11-02 09 47 19](https://cloud.githubusercontent.com/assets/15014599/19922101/60f2d332-a0e1-11e6-8216-00b6699081b0.png)

**Comment by CPASimUSante** [comment]
With the fix, on FF : tested on the PR's travis build
![adminff](https://cloud.githubusercontent.com/assets/14015697/19932138/332079d6-a10f-11e6-9c12-1d395206ee7e.jpg)
