### ISSUE TITLE
Détail : info bulle outil Portfolio dans Topbar/menu bar

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#1409]
| Q | A |
| --- | --- |
| Bug report? | no |
| Version? | master |

Seul l'outil portfolio n'a pas d'infobulle dans la topbar

**Comment by ptsavdar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue https://github.com/claroline/Distribution/issues/1409 for portfolio and tool on top](https://trello.com/c/2mzRuQar/80-issue-https-github-com-claroline-distribution-issues-1409-for-portfolio-and-tool-on-top)
