### ISSUE TITLE
ExosBundle : Nouvelle question de type dictée

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#1412]
| Q | A |
| --- | --- |
| Bug report? | no |
| Version? | master |

Aujourd'hui l'UCL faisait campagne pour son nouveau partenariat : http://www.ortalia.com

J'imaginerai bien un exercice de type dictée pour l'apprentissage des langues ou l'enseignement obligatoire.

Première partie de la question : un fichier audio qui propose tout le texte. 
Deuxième partie de la question: un découpage du texte phrase par phrase. (Il faudrait pouvoir directement enregistrer le texte dans la question à l'aide de la ressource enregistrement.)

Dans Ortalia, il propose un champ texte différent pour chaque phrase dictée. Il est aussi possible pour l'utilisateur de ralentir ou d'augmenter la vitesse du fichier audio. 

Il serait très pratique que le formateur puisse associer à n'importe quel mot un commentaire qui serait visible lors de la correction. Et ce afin de pouvoir repréciser un point de grammaire par exemple. On pourrait aussi envisager d'intégrer un référentiel de grammaire vers lequel l'enseignant pourrait faire des liens dans le corrigé.

Pour la correction, le formateur devrait fournir la version "corrigée" du texte. Pour la notation, il faudrait choisir la note maximum et le nombre de point retiré à chaque faute.

Une autre alternative pour la correction serait un partenariat avec ce projet: https://www.languagetool.org/. 

@Pauooo & @LaurentGruber Vous en pensez quoi ?

**Comment by Pauooo** [comment]
Je suis pas sûre que ça doivent constituer un type de question différent de la question de type libre, puisque mis à part le feedback par mot et le type de notation (qui sont 2 choses intéressantes) on peut/pourra faire ça.

**Comment by Gatomlo** [comment]
Pas faux, ce sera vite intégré alors :+1: ...lol.
