### ISSUE TITLE
Plusieurs problèmes dans la détection de la version du navigateur

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1422]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master |
- [ ] sous Mac la dernière version de firefox affiche on a quand même le message que le navigateur n'est pas à jour (voir ci-dessous)
- [x] sous Android, la dernière version installable est la 53 et happybrowser annonce la version 54, donc  impossible d'enlever ce message
- [x] quand on a cliqué sur le x pour effacer le message il revient à chaque page, c'est exagéré, il faudrait l'afficher à chaque connexion.
  ![capture d ecran 2016-10-17 a 08 32 50](https://cloud.githubusercontent.com/assets/895878/19430149/750f5696-9453-11e6-8ef6-21692edc2d31.png)

**Comment by Batier** [comment]
effectivement c'est plus que pénible et ça revient avec n'importe quel type de navigateur....pfffff
![image](https://cloud.githubusercontent.com/assets/5484259/19469910/abe4fb10-951d-11e6-900a-819f98ae372e.png)

**Comment by ngodfraind** [comment]
A voir avec la #1422 et les changements que @ptsavdar est en train de faire.

**Comment by Pauooo** [comment]
Mozilla FF me dit que j'ai la dernière version de FF (49.0), mais le bandeau est toujours présent
