### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#1424]
| Q | A |
| --- | --- |
| Bug report? | no |
| Version? | master/7.0/etc. |

When clicking on "?" in the top bar, you should now be redirected to the documentation in GitBook.

**Comment by om64** [comment]
@ngodfraind Could you have a look at this, please?

**Comment by LaurentGruber** [comment]
mettre doc.claroline.com par défaut dans le lien de documentation de la plateforme. (et mettre à jour le lien si c'était toujours celui d'avant)
