### ISSUE TITLE
Questionnaires apparaissent en anglais suite à la mise a jour

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#1431]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master/8.0.0/etc.

![image](https://cloud.githubusercontent.com/assets/5484259/19471983/b2456136-9525-11e6-9d8f-629f05727a92.png)

**Comment by ptsavdar** [comment]
Fixed after updaters execution.

**Comment by Garakotxea** [comment]
Bonjour,
Quelle mise à jour/fix avez-vous utilisé ? 
Merci par avance
