### ISSUE TITLE
[CoreBundle] Bug using model

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1435]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master |

When I tried to create a WS using a model, several issues occured :
- [ ] An error message is displayed when the WS is created and the path widget don't display the path 
  ![capture du 2016-10-18 14 47 19](https://cloud.githubusercontent.com/assets/15014599/19478686/ceb350e4-9543-11e6-9a48-7c5fe633fbef.png)
- [ ] When I use a model with copies, my path is unpublished and I have duplication of some resources
  http://claroline-master.travis-build.claroline.net/workspaces/76/open/tool/resource_manager#resources/2199

(model : http://claroline-master.travis-build.claroline.net/workspaces/tools/model/workspace/73/model/index)

**Comment by ngodfraind** [comment]
There are issues with the pathbundle copy afaik. It's not really related to the model.

**Comment by ngodfraind** [comment]
the 2nd point related to #1283

**Comment by Pauooo** [comment]
So I close this issue @ngodfraind ?

**Comment by LaurentGruber** [comment]
closed with https://github.com/claroline/Distribution/pull/2218
