### ISSUE TITLE
Téléchargement d'un dossier dont le nom contient un simple opening curly quote

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1448]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master |

Créer un dossier dont le nom est "Développement d’Applications Entreprise"
On peut voir que le guillemet n'est ni un simple ni un double quote, c'est un simple opening curly quote ALT 0146 visiblement courant sour Mac
Le téléchargement démarre et on reçoit un zip mais il n'y a rien dedans

**Comment by ngodfraind** [comment]
C'est sur mac que le problème se produit ?

**Comment by clarophil** [comment]
C'est l'encodage sous Mac, après la conséquence au niveau téléchargement est génaralisée

**Comment by ngodfraind** [comment]
Sur le master, depuis le fix de panos (#2281)

Notice: iconv(): Detected an illegal character in input string
