### ISSUE TITLE
[ExoBundle] Add a flag for the right response in Cloze question

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#145]
When you configure your Cloze question to use <select> inputs, it might be useful to add an "expected answer" flag like we have on the Choice question.

For this moment, there is a check on the response which have the most points.

**Comment by charlotte42** [comment]
In creating a question hole, we can not choose "expected answer". It will just be reviewing the system when you switch to Angular.

**Comment by Elorfin** [comment]
I don't understand why it's not possible.
What I was thinking is just a regular checkbox on the expected answer in the editor like there is in the Choice type.

**Comment by charlotte42** [comment]
Je n’ai pas dit que ce n’était pas possible... Je voulais dire que ça n'y était pas pour l'instant et que l'on pourrait le faire quand on passera la création des questions en angular. Après si pour toi c'est bloquant, on peut voir pour le faire tout de suite en PHP.

**Comment by Elorfin** [comment]
Yes I know that's not implemented, that's why I have opened an issue ;).
No it's not urgent for us because we can calculate it with the score (I have edited the API to expose it), but it will be an improvement to integrate while refactoring the code (to have the most identical workflow between question types).

**Comment by Elorfin** [comment]
It's no longer needed as we use the score to know which answer is expected (the one with the higher score). The choice question has been updated to work the same way (as described in the JSON-Quizz schema).

**Comment by LaurentGruber** [comment]
il n'était pas question que ce soit nécessaire pour la partie formative ?

**Comment by LaurentGruber** [comment]
voir pour les barème de lyon ?

**Comment by Elorfin** [comment]
Pas que je saches, c'est moi qui le voulait à la base pour que le fonctionnement soit homogène avec ce qui était fait dans les QCM.

Mais en fait, c'est juste que les QCM ne respectait pas le schema défini. Ce qui a été corrigé.
Pour la partie formative de Grenoble, on utilise le choix avec le score le plus élevé, on a pas besoin de cette information en plus.
Pour ce qui est des barèmes de Lyon, je ne penses pas que ça entre en ligne de compte. Il faudra voir quand on implémentera leurs systèmes de notation.

Dans tous les cas, ce ticket fait doublon avec #238 qui est plus général et vise à régler le problème des systèmes de notation non implémentés pour le moment.
