### ISSUE TITLE
self::ORDER_BY_DATE

### ISSUE THREAD

**Issue by jemmeli** [claroline/Distribution#1450]
hi ,
after i insttaled my 1.9.7 version and login into admin successfully bur when i click to a link for example 'my desktop' (http://localhost/claroline197/claroline/desktop/index.php) i got this error 

----------------------
Fatal error: Undefined class constant 'self::ORDER_BY_DATE' in C:\xampp\htdocs\claroline197\claroline\messaging\lib\messagebox\inbox.lib.php on line 37
---------------------

how can i solve this error please knowing i am using XAMPP 3.2.1 

and thank you

**Comment by LaurentGruber** [comment]
Hi,

Claroline 1.x isn't officially supported anymore. This repository contains the sources of the next version of the platform ("connect"), which is totally new and different. We can't provide any advice related to the 1.x series.
