### ISSUE TITLE
[PathBundle] Add an option to play Path in fullscreen mode

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#1453]
| Q | A |
| --- | --- |
| Bug report? | no |
| Version? | master |

Fullscreen means that the summary is closed and all the claroline navigations are removed (no leftbar, no topbar, no footer).

A toggle fullscreen button must be added to the player.
An option must be added in the editor to open the path in fullscreen by default.

**Comment by LaurentGruber** [comment]
done
