### ISSUE TITLE
Ordonner les ressources dans le gestionnaire

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1458]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master |

Dans le gestionnaire de ressources, il est possible d'ordonner les ressources sous chrome mais pas sous firefox ni sous safari même si on utilise les toutes dernières versions.

**Comment by ngodfraind** [comment]
Reproduit. Ça ne dépend pas du navigateur. Il y a autre chose (et ce n'est pas systématique non plus).

**Comment by ngodfraind** [comment]
J'ai même la procédure pour le faire planter à chaque fois:
De droite à gauche => OK
De gauche à droite => Pas OK
