### ISSUE TITLE
[media ressource audio segmenté] association d'exercice

### ISSUE THREAD

**Issue by jypfcl** [claroline/Distribution#1461]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Dans l'aide associée à un segment, pour la lecture "continu actif" et "scénarisé actif", il est impossible d'associer une exercice crée dans l'environnement claroline. Le lien prévu n'apparait pas.

**Comment by pitrackster** [comment]
Le problème reproduit est le suivant : 

- Création d'une ressource Ecoute active enrichie
- Création d'une région
- Ouverture de la modale de configuration de l'aide pour la région
- Les champ "Liens d'aide" n'acceptent pas certaines url (exemple avec l'url d'un exercice)
- Le(s) lien(s) n'est donc pas associé à l'aide pour la région

**Comment by pitrackster** [comment]
closed via https://github.com/claroline/Distribution/pull/1480
