### ISSUE TITLE
[média ressource audio segmenté] TTS en mode lecture normal

### ISSUE THREAD

**Issue by jypfcl** [claroline/Distribution#1462]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master |

dans la panoplie des aides possibles, l'option "TTS" en mode lecture normale n'apparait pas. Le TTS ne fonctionne qu'en mode backward, ce qui était aussi prévu.

**Comment by pitrackster** [comment]
Bonjour @jypfcl !
Merci pour ce retour... à ma connaissance il n'a jamais été question d'implementer l'utilisation du TTS hors backward building. Il s'agit donc de l'ajout d'une fonctionnalité.

Pour rappel le support du TTS est expérimental dans les deux principaux navigateurs recommandés (Firefox et Chrome). Autant pour la backward building nous n'avions pas franchement le choix autant pour le reste je déconseillerai l'utilisation de cette technologie pour le moment.
