### ISSUE TITLE
[PdfGenerator] Knp Snappy doesn't handle images well

### ISSUE THREAD

**Issue by ngodfraind** [claroline/Distribution#1463]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master |

It happened for me when printing a lesson. Knp snappy works that way in the lesson bundle.
1: generate content from twig
2: generate html from content
3: generate pdf from html

During the step 2, stuff like this is happens in the html file

```
<div id="wst-2020" class="lesson-chapter-text"><p><img style='max-width: 100%;' src='/file/resource/media/6773' alt='p24_2.jpg'></p>
```

The src is not reachable by wkhtmltopdf and it crashes with the error code 1, making it more or less useless.
I still don't know if it crashes because it's a relative uri or because it gets an AccessDeniedException from Claroline.

**Comment by LaurentGruber** [comment]
si on met ip wan du server de le ip_whitelist c'est ok
