### ISSUE TITLE
Affichage des ressources de type fichier texte et rtf

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1468]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master |
- [ ] Les ressources type fichier texte (.txt, .csv, .java,...) ne sont pas correctement affichés car les retours lignes ne sont pas pris en compte.
- [ ] Les fichiers  rtf sont affichés mais cela n'a aucun intérêt de voir le balisage rtf.  Il ne faut pour cette extension que proposer le téléchargement.

Il faut prévoir en configuration de la plateforme, les extensions affichées en type txt et celle qui sont directement téléchargeables.

**Comment by ngodfraind** [comment]
Reproduit.
