### ISSUE TITLE
Headers already sent exception

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#147]
This error keeps showing up in the logs of a v5 prod:

> request.CRITICAL: Exception thrown when handling an exception (RuntimeException: Failed to start the session because headers have already been sent by "[...]/vendor/claroline/core-bundle/Claroline/CoreBundle/Controller/FileController.php" at line 52.

I don't see any difference between v5 and v6 for this file, so if it's a bug, v6 might be affected as well.

@clarophil, can you provide the complete stack trace for this error (if any)?

**Comment by ngodfraind** [comment]
Could it be linked to #119  ?

**Comment by stefk** [comment]
Both response types do streaming so I don't think so. Problem seems to be that the streaming begins before the session is opened. I don't know how it's possible.
