### ISSUE TITLE
[SurveyBundle] None anonymous survey

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1470]
| Q | A |
| --- | --- |
| Bug report? | no |
| Version? | master/7.0/etc. |

In the survey, it would be nice to have a non anonymous mode. As an admin or also as a user you can see who chose what after voting. It could be useful to be able to export a list of the votes with the participants name.

**Comment by Gatomlo** [comment]
The future resource "DataBase" can do that.
