### ISSUE TITLE
Lien incomplet dans les annonces envoyées par email

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1474]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master |

Dans l'annonce, un lien vers une ressource est complet
exemple : http://claco.vinci.be/resource/open/file/21604
Quand cette annonce part par email le lien ne contient plus le domaine et donc le lien ne fonctionne pas
exemple : http://resource/open/file/21604

**Comment by CPASimUSante** [comment]
A ma connaissance il ne s'agit pas seulement des annonces, mais de lien vers n'importe quelle ressource qui n'est pas utilisable via l'outil mail.
C'est très génant, surtout pour les utilisateurs (formateurs) qui ne sont pas constamment sur Claroline et pourraient néanmoins recevoir des emails de Claroline.

**Comment by CPASimUSante** [comment]
@ngodfraind peut être utiliser un regexp (plus évolué que celui-ci) pour les url

dans claroline/distribution/plugin/message/Listener/MessageListener.php

```
        $config = $this->container->get('claroline.config.platform_config_handler');
        $domain = $config->getParameter('domain_name');
        $uri = ($config->getParameter('ssl_enabled') === true) ? 'https://'.$domain : 'http://'.$domain;
        $content = $ancestors[0]->getContent();
        $content = preg_replace('/href="(?!http:\/\/)([^"]+)"/', "href=\"$uri\\1\"", $content);
```
ce qui permet de remplacer les liens du type: <a href="quelquechose"> par <a href="http://domainename/quelquechose">.
Il faudrait vérifier dans le masque que le quelquechose ne contient pas déjà http(s)://

Qu'est-ce que tu en penses ?

**Comment by ngodfraind** [comment]
J'ai évidemment pu reproduire mais je n'ai pas encore réussi à corriger (le router se comporte bizarrement).

**Comment by clarophil** [comment]
Merci @ngodfraind
