### ISSUE TITLE
[TeamBundle] Max inscrit atteint et droit d'accès

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1478]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master |
- [x] Retirer le bouton d'inscription si le nombre d'inscrits est atteint
- [x] Avec "voir en tant que" Collaborateur, on à accès à l'édition alors que ce n'est pas autorisé dans les paramètres de l'outil et que si on essaie avec un vrai collaborateur on n'a effectivement pas accès
- [ ] Le mode édition n'est pas accessible alors que les droits d'édition ont été donnés à un rôle dans les paramètres de l'outil

**Comment by CPASimUSante** [comment]
- ok pour point 1
par contre : qu'est-ce que tu appelles "avoir l'accès à l'édition", "mode édition" ? C'est "Modifier les paramètres de l'équipe" ?
Si je me connecte en tant que collaborateur, je n'ai pas accès à l'outil équipe

**Comment by clarophil** [comment]
Sur le master travis 
![image](https://cloud.githubusercontent.com/assets/895878/20878284/69fab98e-bace-11e6-9efc-04e2acf2bf3e.png)

**Comment by CPASimUSante** [comment]
Tu n'as pas à laisser de droits d'édition normalement. Juste la visualisation (icone oeil dans le paramétrage de l'espace pour l'outil équipe : Paramètres > Outils )
![team](https://cloud.githubusercontent.com/assets/14015697/20965343/7c01f8ba-bc75-11e6-966a-ea04445df018.png)

Par contre il y a le même problème qu'à ton premier point : il peut cliquer pour s'inscrire même s'il n'y a plus de place (par contre l'inscription ne s'effectue pas)

**Comment by clarophil** [comment]
non c'est bien configuré mais attention c'est avec "Voir en tant que" par contre quand je me connecte comme collaborateur, j'ai le bon affichage.

**Comment by ngodfraind** [comment]
J'ai pu reproduire le 3ième point mais pas le second.

Il y a d'autres changement à apporter à l'outil ?

**Comment by LaurentGruber** [comment]
je ne pense pas

**Comment by LaurentGruber** [comment]
@clarophil toujours d'actualité ?

**Comment by clarophil** [comment]
oui le 3ème point
