### ISSUE TITLE
[ExoBundle] Graphic question not doable

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1481]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master |

Two kind of problems when I want to respond to a graphic question : 
- Like asked, I click on the image but the pointer stays on the left upper corner and its impossible to drag and drop it. 
  http://claroline-master.travis-build.claroline.net/resource/open/ujm_exercise/2214#/play
  When I go to edit the question this is what I see : 
  ![capture du 2016-10-25 10 04 24](https://cloud.githubusercontent.com/assets/15014599/19678055/7417def8-9a9c-11e6-83dd-1c7d03e37426.png)
- In an other case, the player says : "There is no more pointer to place on the picture. Click on the picture to place a pointer", I can't reset and no pointer is on the page. 
  http://claroline-master.travis-build.claroline.net/resource/open/ujm_exercise/2245#/play 
  When I go to edit the question, it's like no zone had been saved.

**Comment by CPASimUSante** [comment]
I also can add  : 
- in the markings, the expected answer is not a the image with the pointer at the right place, it says :  expected answer : "rectangle" !

PS : i added urgent label, because this is a blocking bug (a regression because this kind of question is now unusable, but wasn't before)

**Comment by Elorfin** [comment]
> in the markings, the expected answer is not a the image with the pointer at the right place, it says : expected answer : "rectangle" !

Normally, in the corrections of a Graphic question you see : 
- The image with the pointers + the correct areas
- A table with all the area with scores and feedbacks

Do you mean the image is not displayed ?

**Comment by CPASimUSante** [comment]
yes for the fact that the image is not displayed.

**Comment by CPASimUSante** [comment]
https://github.com/claroline/Distribution/issues/1221 and https://github.com/claroline/Distribution/issues/1362 seem to have the same error `Uncaught SyntaxError : missing ) after argument list`, but i still have the error, even with the fix https://github.com/claroline/Distribution/pull/1387

**Comment by CPASimUSante** [comment]
I think i found the culprit for the edit part, (not for the player part) : in https://github.com/claroline/Distribution/blob/master/plugin/exo/Resources/views/InteractionGraphic/edit.html.twig#L37 `'{{ 'no_answer_zone' | trans({}, 'ujm_exo') }} ...'`is translated in `'Vous n'avez mis aucune zone de réponse ...'`, thus adding  an extra unescaped quote.

**Comment by CPASimUSante** [comment]
For the `GET http://myserver/bundles/ujmexo/js/ext/images/ui-icons_222222_256x240.png 500 (Internal Server Error)` error, it seems that's because of https://github.com/claroline/Distribution/blob/master/plugin/exo/Resources/public/js/ext/jquery-ui-smoothness.css#L933 : The problem is : the `images/ui-icons_222222_256x240.png` exists in the core : https://github.com/claroline/Distribution/tree/master/main/core/Resources/public/css/common/jquery-ui-bootstrap/images ...
