### ISSUE TITLE
[ExoBundle] List of results : paper consultation

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1486]
| Q | A |
| --- | --- |
| Bug report? | no |
| Version? | master/7.0/etc. |

In the list of results, when you consult a paper it would be nice to have a button "go back to the list of results" and to remove the button "start exercise" at the button of the paper.
This "start exercise" button could also be removed of the list of results.

**Comment by Elorfin** [comment]
Done in the last version.
