### ISSUE TITLE
[ExoBundle] Vidéos dans la description d'une étape

### ISSUE THREAD

**Issue by ngodfraind** [claroline/Distribution#1487]
| Q | A |
| --- | --- |
| Bug report? | yes |
| Version? | master |

1) je rajoute une vidéo dans la description d'une étape
2) je créé un exercice et le teste

=> la vidéo n'est pas affichée

Si je veux éditer la description de l'étape, je constate que la vidéo est bien dans le html

=> il y a vraissemblablement un problème lorsque le html est injecté dans la page (la div cachée s'affiche, la balise vidéo n'est pas reprise)

**Comment by CPASimUSante** [comment]
j'ai testé avec une vidéo Youtube : en fait lors de l'intégration, de la balise iframe, celle-ci est échapée (par sécurité j'imagine. j'ai donc &lt;iframe ... &gt;&lt;/iframe&gt;
Si je "corrige à la main dans l'éditeur le code source, pour avoir <iframe ...></iframe> et que j'enregistre, la vidéo s'affiche bien dans la description.
