### ISSUE TITLE
[ExoBundle] Reset timer

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#149]
The localStorage is never reset, so if you start a new attempt, the calculated duration is wrong.

Add a TimerService in combination with the TimerDirective, and call a reset() method while Exercise is ended (ExercisePlayerCtrl.end())

**Comment by Cindy42** [comment]
yes it's reset in the ExercisePlayerCtrl.js, in the function handleStepNavigation from line 236 to 241 (in branch v6-UJM).
Do you have this problem after moving the timer into a stand alone directive or before ?

**Comment by Elorfin** [comment]
You only reset the var `counter`, but not the vars that contain hours, minutes, seconds. So when you restart the exercise the calculation is made on the old values because this part of code : 

```
exoPlayer.$localStorage.$default({
        counter: 0,
        hours: 0,
        minutes: 0,
        secondes: 0
});
```

only set values in local storage if they are undefined (and they are defined by the previous attempt).
