### ISSUE TITLE
New Ressource: MindMap

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#1501]
| Q             | A
| ------------- | ---
| Bug report?   |no
| Version?      | master/7.0/etc.

Here is a solution to create a new ressource MindMap:

https://github.com/mindmup/mapjs

**Comment by Pauooo** [comment]
https://outilstice.com/2016/11/mindomo-proposer-des-devoirs-sous-la-forme-de-mind-maps-a-vos-etudiants/?utm_content=bufferbb327&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer
