### ISSUE TITLE
[PathBundle] Unable to select more than one status in the widget filters

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#1516]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

If you select more than one status in the filters of the widget, only the last selected one in the list is kept.

**Comment by CPASimUSante** [comment]
I tried to give it a try but couldn't find the culprit (yet). The html form is ok, but in the PathWidgetController::updateConfigAction(), the value for `$form->get('status')->getData()` (or or `$form->getData()->getStatus()`) is an array with a single value, whatever number of choice you take !

The tags seems not to be saved either (or maybe i didn't get the way they are supposed to be used)
