### ISSUE TITLE
[CoreBundle] Error handling broken when dealing with templates

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#155]
Happens in v5 when using self-registration, if the default workspace template archive is not available:

> Undefined property: Claroline\CoreBundle\Library\Workspace\Configuration::$data in [...]/vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Workspace/Configuration.php on line 173

There's still no `$data` property currently, and error management in this class seems broken.

**Comment by ngodfraind** [comment]
The default.zip archive should always be available. The error handling could be changed but that's the only thing I can think of.

**Comment by stefk** [comment]
That's not the first time this error appears. I know the archive is *supposed* to be there but the fact is sometimes it's not and that problem shouldn't be hidden behind programming errors.

**Comment by stefk** [comment]
Another pain point: when the unzip binary isn't available, the code fails silentiously at `$archive->open($path)`. No error, no ouput, just like a `die`.

**Comment by ngodfraind** [comment]
What do you think about removing the configuration class ?

**Comment by stefk** [comment]
I don't know, it depends on what the new design would be. On the other hand, archive manipulation with proper error handling is clearly not tied to workspace creation, so that part could/should probably be extracted.
