### ISSUE TITLE
Ressources résultats - Permettre différents types de valeurs.

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#1556]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master/7.0/etc.

Résultats: pouvoir mettre un élève absent, mettre plus que le maximum (pour des points bonus) et éventuellement aussi choisir une notation en lettres.

**Comment by stefk** [comment]
Au départ la notation était complètement libre (y compris en lettres, donc) mais il a été demandé de la restreindre à des chiffres. Si je me souviens bien, c'était pour permettre une intégration avec les badges (attribution automatique si score > x). cc @LaurentGruber

**Comment by LaurentGruber** [comment]
Une réflection plus global devrait être faite sur la notation dans la plateforme, sinon il ne sera pas possible de tout faire fonctionner ensemble (badge, tableau de bord, ...)
