### ISSUE TITLE
[ExoBundle] Timer bug when set under 0.1

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1557]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

I tried to set my exercise with a 3s. timer. It looked like if it was working with my admin account but when I tried to test the exercise with a collaborator account there was no timer in the player : http://claroline-master.travis-build.claroline.net/resource/open/ujm_exercise/2624#/edit

**Comment by LaurentGruber** [comment]
le timer a été désactivé, ça sera résolu quand on réimplémentera le timer
