### ISSUE TITLE
Décalage d'une heure sur la liste des résultats

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#1561]
| Q             | A
| ------------- | ---
| Bug report   | yes
| Version      | 8.x.

Problème constaté sur une plateforme 

Je cite : 
"
Voici le problème d'heures dans l'exerciseur en PJ. La liste des résultats est à l'heure d'été.
J'ai fermé mon exam hier à 23:59 et les utilisateurs connectés depuis 23:00 étaient identifiés hors délai.
Ailleurs sur [[la plateforme]], pour la création d'une ressource par exemple, l'heure est correcte.
"

**Comment by LaurentGruber** [comment]
la liste des résultats à été réécrite
