### ISSUE TITLE
Change administration menu for usability

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#157]
The menu for the administrator contains too much items (and will surely contain more).
I can't see the items at the bottom unless i zoom out the browser. 
Why not use submenus ? it would help classify the content
![menu](https://cloud.githubusercontent.com/assets/14015697/14586044/2c05dea0-048b-11e6-8d42-9c5e64ae4f5d.png)

**Comment by clarophil** [comment]
Jean-Jacques has already proposed a new organization  of this menu :
http://www.crea-tice.org/mediawiki/index.php?title=Outils_d%27administration

De : CPASimUSante [mailto:notifications@github.com]
Envoyé : dimanche 17 avril 2016 10:58
À : claroline/Distribution <Distribution@noreply.github.com>
Objet : [claroline/Distribution] Change administration menu for usability (#157)


The menu for the administrator contains too much items (and will surely contain more).
I can't see the items at the bottom unless i zoom out the browser.
Why not use submenus ? it would help classify the content
[menu]<https://cloud.githubusercontent.com/assets/14015697/14586044/2c05dea0-048b-11e6-8d42-9c5e64ae4f5d.png>

**Comment by jj-quintin** [comment]
Voici une vue de la nouvelle classification proposée. Elle fait suite à notre dernière réunion ergonomie mais doit encore être confirmé

![interface-generale-topbar](https://cloud.githubusercontent.com/assets/16414632/14979600/a54ca600-1123-11e6-8a62-351476877747.png)

**Comment by CPASimUSante** [comment]
In your present proposition, you display sub-menus "plugins", "chat", "cursus"... If that is the case, there is little use (and a waste of space in the topbar) to multiply the admin menus (Software management, Administrative management, Pedagogic management) which could be set as well as submenus for Management.
If a user has only pedagogic management access, then he would only see the corresponding sbmenu Management > Pedagogic management > Tag, badges...

I thought we were discussing about having a plain simple menu, only with separators. But if you suggest (it is ok with me), there could be submenus (accordion style for instance), then i think multiplying the top menus would be a waste.

As a sidenote, what would there be in the workspace menu ("Chime Organique") when you log in ? There is no WS selected yet ?

**Comment by jj-quintin** [comment]
On fera le point j'imagine lors de notre prochaine réunion ergonomie, car cela mérité échange entre nous

Pour la dernière question, si je n'ai pas (encore) sélectionné  de WS, le menu en question (Chimie organique) n'apparaît pas. On doit cependant discuter des cas adjacents : le cas où j'en ai sélectionné un mais que je suis retourné dans le bureau par exemple.
