### ISSUE TITLE
Remove vendor deps from portfolio

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#158]
The portfolio plugin has a *Resources/js/vendor* with a lot of copy/pasted dependencies. Most of them are already available in *web/packages*.

cc @claroline/icap-ec.

**Comment by ngodfraind** [comment]
Also, the @InnovaXxxBundle aren't found anymore so you get a blank page on the index. I don't know why.

**Comment by stefk** [comment]
@ngodfraind, that bug should be fixed by #163.

**Comment by stefk** [comment]
Reopening, the original problem is still there.

**Comment by ptsavdar** [comment]
Fixed in #196
