### ISSUE TITLE
[CoreBundle] Cannot generate user from workspace public user account creation form

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#1582]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 8.0

When trying to create a new user through workspace public user account creation/generation I got the following error:

![user_generate_anonymous](https://cloud.githubusercontent.com/assets/3414935/20518058/0ecbd622-b09e-11e6-8699-ecc3e77c24fa.jpg)

**Comment by CPASimUSante** [comment]
It seems some attributes shouln't be mandatory. Or if they have to be then the help text in the import page or the create page should be updated.

**Comment by ptsavdar** [comment]
Fixed in dev-master
