### ISSUE TITLE
[CoreBundle] Export Excel users in xlsx

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1583]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Worskpace
User management
It should be interesting to export users in xlsx format in place to xls to be easily import by google drive and so on.

**Comment by CPASimUSante** [comment]
For a simple listing as simple text listing (users, workspace...) in a single tab, it is the same i think. You can import xls as well as xlsx in Google Drive, Google Sheets... they will be opened the same.

**Comment by LaurentGruber** [comment]
non reproduit
