### ISSUE TITLE
[CursusBundle] All new cursus created is blocking

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1585]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

When I create a new cursus in the cursus management, the cursus is blocking even if I didn't checked the box. When I want to change the blocking option by editing, it doesn't change anything.
http://claroline-master.travis-build.claroline.net/admin/open/claroline_cursus_tool#/cursus/11

**Comment by Gatomlo** [comment]
Done https://github.com/claroline/Distribution/pull/1584
