### ISSUE TITLE
[EvaluationBundle] Impossible de refuser une correction

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1586]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Lorsque des étucdiants ont évalué un travail, il est 
- [x] Impossible de refuser une correction par l'étudiant auteur du travail
![image](https://cloud.githubusercontent.com/assets/895878/20523350/eb759016-b0b4-11e6-81ef-5c23bb613b1e.png)

- [x] Perte des paramètres du collecticiel  quand on l'édite
-- Les apprenants se corrigent entre eux (Évaluation par les pairs)
-- Manuellement

**Comment by clarophil** [comment]
Il faut cocher toutes ces options pour voir le bug
![image](https://cloud.githubusercontent.com/assets/895878/20523856/712cc51a-b0b7-11e6-894b-5ad5db04199f.png)

**Comment by ptsavdar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DropZone bundle issue #1586](https://trello.com/c/HCf92ol2/153-dropzone-bundle-issue-1586)
