### ISSUE TITLE
on pourrait rajouter un état à chaque ticket de l'outil support?

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#1593]
Avec par exemple ces intitulés
Urgent
A traiter
En traitement
Traité

cet état étant éditable par les admins et visible par tous
t coté admin la possiblité de liste les ticket par état

| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master/7.0/etc.

**Comment by Batier** [comment]
c'est un concept ?
Une philosophie?
sur claroline connect le statut probleme résolu n'existe pas :-(
![image](https://cloud.githubusercontent.com/assets/5484259/20631973/61a5251c-b33a-11e6-9eca-e2b557c26b09.png)

**Comment by Batier** [comment]
C'est un concept?
une philosophie?
le statut résolu n'est pas présent

![image](https://cloud.githubusercontent.com/assets/5484259/20632069/12459348-b33b-11e6-9294-b84f0c3ac8dd.png)

**Comment by Batier** [comment]
en même quand enfin au créé un état résolu...
il ne s'affiche pas 
![image](https://cloud.githubusercontent.com/assets/5484259/20632583/f86ce904-b33e-11e6-935a-e5949f8181a1.png)

**Comment by LaurentGruber** [comment]
closed by : https://github.com/claroline/Distribution/pull/2182
