### ISSUE TITLE
Gros Soucis de performance dans la requette etablissant la liste des derniers espaces de travail

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#1594]
| Q             | A
| ------------- | ---
| Bug report?   | yes/
| Version?      | 8.0.2.

Nous avons du retirer la requette établissant la liste des derniers espaces de travail
dans le menu utilisateurs
celle ci parcours les log pour établir la liste...ça va bien sur des petits serveurs sans trop de log
sur mon profil cette requette prend plus de 20s ce qui est bcp trop long
et en plus c'est bloquant car en attendant on se retrouve devant un écran blanc
il serait plus judicieux de prevoir des champs liés à l'utilisateur pour stoker les 2, 3, ou 10 dernier espaces consultés on gagnera en temps de connexion....

en attendant mieux sur notre serveur nous avons retiré cette fonctionnalité et on se log rapidement

**Comment by CPASimUSante** [comment]
@ptsavdar @ngodfraind @david42 Peut-être faire une option d'administration pour désactiver cette fonctionnalité ?

**Comment by Batier** [comment]
oui mais surtout penser différemment cette fonction en stockants les 3 5 ou 10 derniers espaces de travail parcouru ce qui permettra d'afficher selon option admin les 3 ou 5 ou 10 derniers espaces .
ce qui prendra moins de ressources CPU à la connexion de l'utilisateurs que de parcourir l'ensemble des log de la plateforme...
parce que c'est une fonction bien sympa à la base
