### ISSUE TITLE
A quoi sert le champ description dans la modification du profil d'un utilisateur ?

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#1595]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

car il ne s'affiche nul par ailleurs qu'en mode édition....  

a minima l'afficher sur la partie publique du profil 
http://claco.univ-lyon1.fr/profile/christophe.batier

**Comment by Batier** [comment]
sur l'ecran de gauche j'ai un champ information de base 
 a quoi il correspond ?

y a pas de coherence fonctionnelle et ergonomique entre ces 3 écrans

![image](https://cloud.githubusercontent.com/assets/5484259/20599797/7c7e0ab0-b250-11e6-886b-9b4e378350a1.png)

**Comment by Batier** [comment]
Le champs description du profil ne s'affiche pas hors du mode edition

**Comment by Elorfin** [comment]
La gestion du profil a complètement été revue et les problèmes cités n'existent plus.
