### ISSUE TITLE
[exoBundle] Option pour enlever le bouton "commencer l'exercice"

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#1604]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master

Ajouter une option pour arriver directement sur la première question à la place d'avoir l'écran d'accueil avec le bouton commencer l'exercice (pour l'intégration dans les parcours notemment)

! cela supposera probablement de bloquer l'option timer !

**Comment by Elorfin** [comment]
available in master branch.
