### ISSUE TITLE
[Parcours] plugin tiniMCE lien interne au parcours

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#1605]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master

Permettre via un icone dans le tinyMCE de faire des liens vers d'autres étapes à l'intérieur d'un même parcours (voir d'autres parcours ?)

**Comment by CPASimUSante** [comment]
1) Why this feature in TinyMCE ? This would be very confusing from a user point of view : the manager sets its steps in forms, with the hierachy in the menu on the left, and you would add a crossover feature inside a text editor with already many buttons...
2) This feature needs a complete rethinking of the path before : a step linked to step(s) not adjacent, or not even in the same path...
3) at worst, i guess you could manually set links in tiny to the steps you want to link to. But if any kind of condition is set it could be a mess...
