### ISSUE TITLE
Profil a facette : champ type date si obligatoire, toujours concidéré comme non valide

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#1606]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.
le champ date d'entrée bloque la création de compte
il se met systématiquement en champ invalide

 mettre uniquement (l'année champ libre)
http://hilearngo.handicap-international.org/register/form

![image](https://cloud.githubusercontent.com/assets/5484259/20744909/ce8a5e98-b6de-11e6-97aa-60c7b2692cb0.png)

**Comment by Batier** [comment]
Pour contourner, j'ai changé le type du champ date et je l'ai passé en champ texte ce qui supprime le soucis

**Comment by ngodfraind** [comment]
Reproduit.
