### ISSUE TITLE
[CoreBundle] TinyMCE

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#1608]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Avoir un aperçu direct du style final de la plateforme dans le tinyMCE (application des styles CSS du templates)

**Comment by CPASimUSante** [comment]
Ca part d'une bonne intention, mais à l'utilisation c'est peu probant. D'expérience vouloir faire du une mise en page pixel perfect dans un editeur wysiwig est impossible : ici dans claro généralement la création se fait dans une modale, donc la mise en page sera différente du résultat final qui s'affiche dans un div élastique. Les tableaux risquent d'être décalés, les titres sur un nombre de ligne différent...

**Comment by LaurentGruber** [comment]
l'intérêt est d'avoir notemment des styles de titres et de texte cohérant avec ceux qui seront afficher sur la page. Typiquement si ta css spécifie le H2 en bleu sur la page que le H2 soit également en bleu dans le tinyMCE

**Comment by Elorfin** [comment]
C'est le cas dans la version actuelle.
