### ISSUE TITLE
TinyMCE perte de focus dans l'éditeur html

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#1609]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Éditeur html perte du focus rend la partie inutilable (depuis qu'on a ajouté la coloration syntaxique)

**Comment by CPASimUSante** [comment]
Can you explain ? I'm on master and i don't see what you're saying. In which instance ? in a specific resource ?

**Comment by Elorfin** [comment]
fixed
