### ISSUE TITLE
Portfolio html dans champs tinymce

### ISSUE THREAD

**Issue by JeanSebastienDijoux** [claroline/Distribution#1613]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 8.0.2

si je mets du html (lien ou image) dans le champs dans n'importe quel champ du portfolio. Il ne s'enregistre pas et ne s'affiche pas dans la visualisation

**Comment by CPASimUSante** [comment]
@see also https://github.com/claroline/Distribution/issues/1503
