### ISSUE TITLE
Add a version next to the master

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#1618]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master/7.0/etc.

When using the master, we may encouter bug. But by definition the master is constantly evolving so if i install a version of the master day 1, encouter a bug day 3, there may be a fix day 2 that i missed.

So it could be useful, (for the github report), to add a extended version for the master that is displayed in the footer : master + date of install or github hash or ....

**Comment by ngodfraind** [comment]
Done by the recent change on the installation/update process
