### ISSUE TITLE
RessourceWeb faciliter le démarrage

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1619]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      |

Actuellement pour que la ressource fonctionne il faut exactement index.html et index.htm
Je propose d'accepter aussi Index.html, Index.htm (i majuscule)

**Comment by CPASimUSante** [comment]
@clarophil : je viens de tester sur travis master une ressource avec un Index.htm et ça fonctionne. As-tu un exemple de fichier qui ne fonctionne pas ?

**Comment by clarophil** [comment]
@CPASimUSante 
Le voici 
[res_web.zip](https://github.com/claroline/Distribution/files/651784/res_web.zip)

**Comment by CPASimUSante** [comment]
je viens de faire une PR, mais c'est étrange après coup que ma ressource web avec un fichier Index.htm soit passé sans correction (sur le master) !
