### ISSUE TITLE
[Administration] Account creation, Roles not saved

### ISSUE THREAD

**Issue by eddymarques** [claroline/Distribution#162]
In Administration > User Management

When you want to create a New Account, the Roles you'd check at the creation are not saved.
You need to edit again the account just created to add Roles.

![image](https://cloud.githubusercontent.com/assets/3414956/14608030/6959b78c-0584-11e6-8c51-b91ca420f8b0.png)

**Comment by ngodfraind** [comment]
Reproduced.
