### ISSUE TITLE
Inscription à un espace : ajouter à mes espaces 

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1620]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master

Dans Mes espaces d'activités, on peut se désinscrire mais par s'inscrire, pour cela il faut aller dans Tous les espaces d'actiivté.
Je propose d'ajouter aussi "S'inscrire à un espace" dans "Mes espaces d'activité"

**Comment by LaurentGruber** [comment]
La liste Mes espaces d'activités est celle des espaces auxquels tu es déjà inscrit si je ne m'abuse donc ça n'aurait pas vraiment de sens ? Ou je n'ai pas bien compris la demande ?

**Comment by clarophil** [comment]
Oui c'est bien la liste des espaces auxquels je suis inscrit mais si un utilisateur constate qu'il y a un espace auxquels il n'est pas encore inscrit,  il doit savoir qu'il doit aller ailleurs dans la liste de Tous les espaces publics et ce n'est pas du tout naturel pour lui.  La preuve, j'ai du faire une vidéo pour expliquer comment faire et elle a été visionnée plus de 1000x pour 3000 utilisateurs ...
