### ISSUE TITLE
Add for a user one or two "contacts"

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#1621]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master/7.0/etc.

The school teachers would like to be able to contact the father or the mother of a student. So it's maybe a good idea to add two Email fields for each user. With that the teacher can choice if he want to send a message at the users or at the users and his parents.

**Comment by LaurentGruber** [comment]
A voir quand on retravaille l'outil contact

**Comment by Elorfin** [comment]
Le plus simple serait d'ajouter 2 champs emails dans le profile à facette pour faire ça (sans modification de la messagerie).

**Comment by Elorfin** [comment]
Duplicate https://github.com/claroline/Distribution/issues/1555.
