### ISSUE TITLE
[ExoBundle]Exo v2 [Preview/WIP] #1578 improvements

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1625]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master/7.0/etc.

**-Bug on http://pr-1578-1485844237.travis-build.claroline.net/claroline/**

- [x] Set : Montrer l'icone de feedback sur les intrus quand ils sont placés 
- [x] Graphique : impossible de déplacer ou redimentionner une zone dans l'éditeur
- [x] Cloze : error when saving
- [x] Bug erreur 500
- [x] Migration des clozes
- [x] le créateur de la question n'est pas positionné ( on ne trouve pas la valeur)
- [x] enregistrement description paramètres n'est pas effectif (je peux sauvegarder mais si f5 disparait)
- [x] dans pair afficher message d'erreur "you must pin at least one item to use random.".
- [x] Pair : quand plus de 2 odd, impossible de les supprimer.

**- Must have :**
- [x] on n'arrive pas sur la correction à la fin de l'exercice (gérer selon paramètre)
- [x] Donner accès au menu résultat dès qu'une copie est créé
- [x] hide docimology, export csv, publish button, in bank of question hide : create, import.
- [x] Hide the quiz type dropdown menu (sommatif/formatif/évaluatif)
- [x] Error message when the browser version is not suitable [**Note**: Verify if the platform platform-wide check, is enough for the quizz requirement?]
- [x] Mettre un numéro de version sur le json schéma [**Note**: les schémas sont identifiés par des urls -> il faut réorganiser la spec]

**- Very Nice to have :**
- [x] La liste des copies à corriger doit être inaccessible ou présenter un message approprié s'il n'y a aucune copie à corriger
- [x] rafraichir les paper quand il y en a de nouveaux (il charge que quand on rentre dans l'exercice)
- [x] In the paper list, display the score max : 8/22
- [x] Rajouter un message dans la suppression d'une question si elle est partagée + Revoir message suppression d'une question dans l'exo.
- [x] When I create a "questionnaire", I should arrive directly on the edit page and not the overview.
- [x] Correction : change "anonyme" for "rendre les copies anonymes" ( not in the translations keys, translation by library ?)
- [x] Match : Add "cliquez sur le lien pour avoir plus d'informations"/"cliquez sur le lien pour pouvoir éditer les paramètres de l'association" 

**- Nice to have :**
- [ ] Put an information to explain "random picking" "random order"
- [ ] piking step : préciser erreur si nb de step rentré plus grand que nb de step existant + si on passe de step picking > step existant à never picking => garde en mémoire l'erreur
- [x] "show_feedback" : put this option in correction and not signing
- [x] Set : Bring the feedback icon and the delete icon closer
- [x] Set : Impossible to delete an item of the left column
- [x] Set : change the message error position : it should be under "ordre des items aleatoire"

**- If there is time :**
- [ ] Montrer un spinner dans le corps de la page pour les requêtes provoquant un changement de section (ex: liste résultats)
- [ ] dans set, match, pair contraindre la hauteur max des items (ajouter scrolling bar)
- [ ] the step title is followed by the numbers of attempt : "Essai n° 1 / 3 (Vous avez droit à 3 essais)"
- [ ] When I choose to display feedback at the end of the step, I should be able to check an other option "let go to the next step only if all good answers are find or if the number max attempt is reached".
- [ ] be able to drag and drog a question in a step to an other
- [ ] In paper : Feedback component add pointer cursor on feedback icon hover
- [ ] Be sure that you can not delete a question (shared or not) that has a paper. [**Note**: still needed?]
- [ ] Les nombres qui ne sont pas dans cette plage [-2147483648;2147483647] ont l'air d'être tronqué lors de la sauvegarde.
- [ ] Dans set/pair/match si "set_no_orphean_items" signaler l'item qui pose problème.

**- General (impact important) :**
- [x] Write the script for old data migration (Updater)
- [x] Solve the re-authentication issue (the modal has to manage sigle sign-on) when the user loses the session. Idea : use local storage to be able to display the quiz like it was when the user lost the session.
- [X] Handle validation
- [X] Implement a global validation handling mechanism
- [X] BUG when in an item data is only composed with an image / video / sound user is told to set item data which is irrelevant
- [x] Message quand on quitte sans avoir sauvegarder
- [x] Change constraint version for updaters (use 9 instead of 8)

**- Create all questions type (editor, payer, correction) :** 
- [x] Choice (QCM)
- [x] Words (mot clé)
- [x] Open (ouverte)
- [x] Pair (appariement)
- [x] Set (classement)
- [x] Match (association)
- [x] Graphical (graphique)
- [x] Cloze (texte à trous)

**- Player/testing question**
- [x] the question is always followed by a "< br >"
- [x] the step title have to be changed by the name if a name has been given.
- [x] the step description shouldn't be in a panel

**- bank of question**
- [x] cabler l'interface avec l'API

**- Editor General :**
- [x] When I save my quiz, it would be nice to have a visual that makes me know that the quiz is saved. On the contrary it would be nice to have a message saying so.
- [x] add the validate icons (svg need to be exported again) and the description of the different types of question https://oc.forma-libre.net/index.php/apps/files/?dir=%2FEquipe%20Technop%C3%A9da%2FProjets%20Dev%2FExos%20Bundle%2FIc%C3%B4nes%2F161128 
- [X] Thumbnails container should stick to the left / top / bottom of the page in normal view and stick to left / top / right in small view
- [X] nav containers should take the entire width so that items would have there proper places
- [x] make quiz readonly for non-admin users
- [x] ![parametres](https://cloud.githubusercontent.com/assets/15014599/22339577/b8a314c4-e3ea-11e6-8a94-8dc46209c789.PNG) Make the S visible

**- Editor thumbnails :** 
- [X] Replace questionnaire with parameters on the quiz thumbnail when in big screen view
- [X] Replace title with `fa-cog` on the quiz thumbnail when in small screen view

**- Editor exercise parameters :** 
- [x] Correction : change "afficher les solutions" for "afficher la réponse attendue dans la correction"

**- Editor question metadata for any question type :** 
( - [ ] add the category field, )
( - [ ] add the "objet de la question" field )
- [X] Add question title field
- [X] Add question description field
- [X] remove "informations complémentaires" and "consigne pedagogique" fields
 - [x] Change "titre et métadonnées" for "titre et champs supplémentaires"

**- Editor for any question type :** 
(- [ ] you can not see if a question has an hint or a feedback without expanding the panel. If there is any, maybe display an help message or open the panel.)
- [X] Change the "add a question" button for a github type button (without confirmation)
- [X] Import question modal should wait for the user to search before loading any question
- [X] When I give a step a title, this title should be displayed in the left thumbnail.
- [X] When I create a "questionnaire" the first step should be already created.
- [X] Homogenize the tooltips style (use bootstrap everywhere)
- [x] Change "Show_the_interact_fields" for "hints and feedback"
- [x] In some types (set and match) the delete icon is blurry due to a CSS rule https://github.com/claroline/Distribution/blob/exo-v2/plugin/exo/Resources/less/override.less#L53

- [X] For any item of any type of question, the feedback icon must be on the left of the bin.

**- Error message in editor for all type of question**
- [x] When I create a question, after filling just one text field (question or other field) error messages appears immediately 

**- Choice question type editor :** 
- [X] change the checkbox "réponses multiples" for 2 radio buttons  : "réponse multiple"/"réponse unique" on the same line
- [X] change the label "résultat fixe" by "score global"
- [X] add colours depending on the score (red for =< 0 or green >0)
- [x] add a message error if there is no answer with a score > 0 "au moins un des choix doit avoir un score supérieur à 0."
- [x] When forgetting to give values to MCQ, the notification appears in Dutch. This is a bit weird. (issue #1749 )

**- Match editor :** 
- [X] [BUG] Endpoints are misplaced
- [X] Make feedback toggleable via icon and remove field label in association popover
- [X] [BUG] When I click on an association (green or red) the configuration popover does not show.
- [X] Save Match question properly (solutions, firstSet, secondSet)
- [x] Issue : when I want to create a new link from item A to item Z when item A is already linked to item Y, I need to delete the first link to create 2 link in a row.
- [X] change tooltip "commentaire" for match/pair/set type for "commentaire si cette association est créée"
- [X] change "pénalité pour toute mauvaise réponse" for " pénalité pour toute mauvaise réponse non définie"

**- Set editor :** 
- [x] If I add an image to an item, when I drag this item to the right column, it displays html. 
- [X] The feedback field has to be bigger, it could be extended to under the delete icon.
- [X] Change "set" = "panier" in french
- [X] change tooltip "commentaire" for match/pair/set type for "commentaire si cette association est créée"
- [X] change "pénalité pour toute mauvaise réponse" for " pénalité pour toute mauvaise réponse non définie"

**- Pair editor**
- [X] change tooltip "commentaire" for match/pair/set type for "commentaire si cette association est créée"
- [X] change "pénalité pour toute mauvaise réponse" for " pénalité pour toute mauvaise réponse non définie"

**- Keywords editor**
- [x] When I add a keyword and one is already filled, an error message is immediately displayed. This message error should be displayed just if the user try to save the quiz or add a new question.
- [x] In the < div class="word-item positive/negative-score" > remove the border radius, like for the others type of question.

**- Bug/enhancement on http://pr-1578-1484234840.travis-build.claroline.net/claroline/**
- [x] Bug :  when I want to do the quiz http://pr-1578-1484234840.travis-build.claroline.net/claroline/resource/open/ujm_exercise/192#overview
- [x] add a blue background color in the expected answer
- [x] the description should be out of the "your answer/expected answer" panel
- [x] check the warnings

**Comment by pitrackster** [comment]
>  improve validation

It's a bit vague ;-)
