### ISSUE TITLE
[ExoBundle] Random picking questions by category in a step

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1635]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master/7.0/etc.

In a step, it would be nice to be able to pick randomly several questions according to a category.
For example, in my step 2 I want to import 5 random questions with the category "french A2" from my bank of questions.
It means that category are no more personal.

**Comment by Elorfin** [comment]
Possible dans la dernière version des exos.
