### ISSUE TITLE
Soucis à la création de compte il est toujours possible d'avoir un doublon comme réponse à la requête de log

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#1638]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master/7.0/etc.

J'avais déjà signalé ce soucis toujours présent dans la version 8.0.2
on a un utilisateur dont le code  (d’ailleurs à  quoi sert ce code??????) est le même qu'un nom utilisateur (champ User_name) d'un autre compte du coup les deux comptes sont HS quand ils essayent de se connecter...
2 demandes
1- Rendre impossible la création de compte avec des valeurs identiques
2- Peut on mettre en option  ces champs code  au niveau utilisateur  et aussi sur l'espace de travail

**Comment by LaurentGruber** [comment]
Le champs code sert pour lié claroline connect avec des SI interne chez différent utilisateur. Par exemple, le code administratif de l'utilisateur correspond au matricule de l'étudiant dans le SI de l'établissement d'enseignement, ce qui permet de lier les deux.

Pour la demande 1 oui, ça devrait déjà être le cas, on vérifie.
Pour la demande 2 non, car l'objectif est de pouvoir s'identifier via ce champ (le matricule d'un étudiant par exemple) et de pouvoir identifier des EA également via leur code. Si on ne les rends pas obligatoire, on rendrait cela impossible. Je vois au moins une vingtaine d'établissement qui ont toutes leur plateforme claroline basé sur ces liens avec leur SI interne

**Comment by CPASimUSante** [comment]
@LaurentGruber pour le 2 : si le code est optionnel, où est le problème ? Il est présent sur les plateformes qui veulent l'utiliser. C'est rendre obligatoire un champ qui est plus gênant, car il contraint à donner une valeur (dont il n'est indiqué nulle part qu'il ne faut pas qu'elle soit unique).

**Comment by LaurentGruber** [comment]
@CPASimUSante le problème est que ce sont des champs qui servent d'identification. Dans le cas où ils sont utilisé, s'ils manquaient pour un seul user ou WS toutes l'intégrité des données serait compromise.
ça reviendrait à rendre une clé primaire optionnel, ce n'est pas possible tout en gardant l'intégrité de la DB...

**Comment by CPASimUSante** [comment]
comme je dis si le champ est optionnel, ceux qui l'utilisent en connaissance de cause (donc le remplissent)... Celà dit, s'il faut le laisser obligatoire, alors si cela génère des problèmes comme rapporté dans ce ticket, il FAUDRAIT au moins clairement indiquer le fait qu'il est obligatoire, les contraintes (pas de doublon...), et les caractères autorisés

**Comment by LaurentGruber** [comment]
ça revient à dire qu'il faut faire confiance aux utilisateurs ce qui n'est jamais une bonne idée.

Et oui, il faut ajouter les contraintes qui sont déjà en DB, le champs doit être unique ...

**Comment by Batier** [comment]
effectivement ce n'est pas une bonne idée car 1 on a aucune info dans l'interface pour le guider
2 ce n'est pas la première fois qu'on tombe sur ce problème,
