### ISSUE TITLE
[CoreBundle] Technical information in the admin menu

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#1639]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master/7.0/etc.

In the admin menu some technical information is displayed. 
Maybe all of this information is not relevant even for an admin.
On the contrary, it would be nice to have some information like the max upload for a file (often asked).

**Comment by purplefish32** [comment]
Needs information.

**Comment by CPASimUSante** [comment]
It could be a summary of important values : 
php version
mysql version
php settings : 
- php memory limit
- upload_max_filesize
- post_max_size
...
as a table : left side : your configuration, right side : advised minimum configuration
