### ISSUE TITLE
[SocialBundle] Warning in profile widget 

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#164]
In the profile widget on desktop 

Warning: Division by zero in /home/claco/vendor/claroline/core-bundle/Controller/ProfileController.php on line 232

**Comment by ngodfraind** [comment]
I didn't reproduce the error but I know where it come from thanks to the log.

**Comment by clarophil** [comment]
It works as admin but not as simple user

![image](https://cloud.githubusercontent.com/assets/895878/14609378/d7120c0c-0589-11e6-899e-da80f771c3a3.png)

**Comment by ngodfraind** [comment]
Yes, I saw it. The fixe is coming soon !
