### ISSUE TITLE
Pb de logique et de lien ergonomie sur l'option redirection

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#1645]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Il faudrait que le lien sur la petite maison de la barre en haut
![image](https://cloud.githubusercontent.com/assets/5484259/21013486/95373eae-bd5a-11e6-83a0-56678bba14bb.png)

soit lié au choix fait par l'admin à ce niveau Redirection après login

![image](https://cloud.githubusercontent.com/assets/5484259/21013296/c5912db8-bd59-11e6-982f-ab2aa740d411.png)

**Comment by LaurentGruber** [comment]
@Batier si on fait ça, cela signifiera que pour ceux qui mettront autre chose que le bureau, le bureau deviendra définitivement innaccessible (il n'y a pas d'autres façon d'accéder au bureau que cet icone) ...
C'est voulu ?

**Comment by Batier** [comment]
oui c'est pas tres logique on se prive de pas mal de fonctionnalité de la plateforme...mais ça peut etre un choix de simplification pour les organisation en formation pro qui auront des utilisateurs qui viendront que quelques heures par an sur la plate forme et qui iront plus directement au contenu

**Comment by LaurentGruber** [comment]
La solution que j'ai adopté pour ce cas là pas plus tard que cette semaine, c'est de verouiller le bureau via l'administration. De mettre sur le bureau des widgets textes qui présente les 3 modules de formation présent sur la plateforme et qui ont des liens vers les espaces correspondant.

Donc quand tu arrives sur le bureau tu ne vois que les 3 modules qui t'envoie vers les 3 espaces que tu peux utiliser.

J'ai également masqué tous les autres icones de la barre (il ne reste que la maison qui ramène vers cet accueil).

Chaque module correspondant uniquement à un scorm, j'ai configuré les 3 espaces pour qu'à l'ouverture on rentre directement dans le scorm qu'on masque le breadcrum et le menu de gauche... Pour l'occasion on a également ajouter une option au scorm pour permettre de masquer la top barre quand on est dans un scorm, le scorm est donc en plein écran (disponible dès à présent sur le master).

Changé la redirection de l'icone du bureau me semble intéressant que dans un nombre très réduit de cas, essentiellement quand il y a une seul formation sur une plateforme, ce qui me parrait très peu courant mais je me trompe peut être. On pourrait ajouter une option dans les paramètres de redirection après login qui si elle est cochée appliquerait la modification également à l'icone du bureau.
@Batier cela te parraitrait utile ?
