### ISSUE TITLE
Affichage sommaire dans le parcours

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#1646]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Dans le paramétrage d'un parcours, si la case "ouvrir le sommaire par défaut" n'est pas cochée, quand on affiche le parcours et qu'on ouvre manuellement le sommaire il recouvre l'étape du parcours. Il devrait modifier la largeur du parcours pour que les deux informations soient disponibles en même temps. C'est le comportement qui se produit quand on laisse le sommaire affiché par défaut.

**Comment by LaurentGruber** [comment]
pour ça il faut cliqué sur la pin pour piner le sommaire
