### ISSUE TITLE
[CollecticielBundle] Ouverture par date 

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1655]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Créer un collecticiel
Paramètres
Coher par dates
Ajouter une date d'ouverture mais pas de l'heure
Cliquer sur Sauvegarder
Uncaught PHP Symfony\Component\Debug\Exception\FatalErrorException Exception: "Error: Call to a member function getTimestamp() on null" at /home/hevinci/claroline/vendor/claroline/distribution/plugin/collecticiel/Manager/DropzoneManager.php line 289
![image](https://cloud.githubusercontent.com/assets/895878/21099403/4f5c8c4c-c06e-11e6-831c-04e90c6e0302.png)

**Comment by CPASimUSante** [comment]
je viens de reproduire : il s'agit, comme indiqué dans ta capture du fait que tu ne définis pas de date de fermeture.
C'est certes une erreur, mais pour cet outil, est-on obligé de définir une date de fermeture @jj-quintin ?
si la date de fermeture est obligatoire, il faut un message et empécher l'enregistrement, sinon, il y a la condition qui plante qu'il faut changer pour ne pas prendre en compte une date vide
