### ISSUE TITLE
[collecticielBundle] Echelle d'appréciation sans critère

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1657]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Créer un collecticiel
Sélectionner dans Evaluation -> Echelle d'appréciation
Supprimer le critère (la liste est alors vide)
Sauvegarder
EntityManager#persist() expects parameter 1 to be an entity object, NULL given.

**Comment by CPASimUSante** [comment]
(presque) reproduit : 
quand je suis dans 
Sélectionner dans Evaluation -> Echelle d'appréciation
je clique sur le bouton : "gérer l'évaluation"
j'ai des degrés d'appreciation et des critères d'appréciation
- si je supprime les degrés (aucun intérêt mais possible) et sauvegarde : 
Notice: Undefined index gradingScales
- si je supprime le critère et sauvegarde : 
Notice: Undefined variable : gradingCriteriaData

Cependant dans les 2 cas, si on revient sur la page précédente, l'enregistrement ne s'est pas fait et on conserve les données.

=> Question : @jj-quintin a t'on le droit de ne pas avoir de critères d'appréciation  ?
![collect](https://cloud.githubusercontent.com/assets/14015697/21103157/8de4f518-c081-11e6-921e-28ec0af903d3.jpg)

Il y a bien un bug, mais comment le traiter dépend de comment on le considère...
