### ISSUE TITLE
[CoreBundle] Import users with csv file is broken

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#167]
Notice: Undefined offset: 1 in /home/claco/vendor/claroline/core-bundle/Manager/UserManager.php on line 338

Notice: Undefined offset: 2 in /home/claco/vendor/claroline/core-bundle/Manager/UserManager.php on line 339

Notice: Undefined offset: 3 in /home/claco/vendor/claroline/core-bundle/Manager/UserManager.php on line 340

Notice: Undefined offset: 4 in /home/claco/vendor/claroline/core-bundle/Manager/UserManager.php on line 341

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'first_name' cannot be null' in /home/claco/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91 Stack trace: #0 /home/claco/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL) #1 /home/claco/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(165): Doctrine\DBAL\Driver\PDOStatement->execute(NULL) #2 /home/claco/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(281): Doctrine\DBAL\Statement->execute() #3 /home/claco/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1018): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts() #4 /home/claco/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(378): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata)) #5 /home/claco/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL) #6 /hom in /home/claco/app/cache/prod/classes.php on line 5320
[listeA.txt](https://github.com/claroline/Distribution/files/224195/listeA.txt)

**Comment by ngodfraind** [comment]
Wich version are your running ? the import works fine on this repo.

**Comment by ngodfraind** [comment]
@clarophil 
Any news ?

**Comment by clarophil** [comment]
It seems to be resolved
