### ISSUE TITLE
[MessageBundle] Un lien vers un fichier téléchargé ne fonctionne pas si on n'a pas d'espace perso

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1674]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 8.x

Aller dans Messagerie
Nouveau
Dans le texte, Télécharger un fichier
Envoyer

Le lien marche dans le mail reçu si on a un espace perso
Le lien ne marche pas si on n'en a pas

**Comment by ngodfraind** [comment]
Je sais pas si c'est la faute de l'espace perso, mais j'ai reproduit le problème avec une vidéo (normal qu'on ne puisse pas avoir les balises dans l'email).
