### ISSUE TITLE
[CoreBundle] Update failed after a new install

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#168]
After a pre built installation, I tried to do a composer update but it failed.
I had tried to relaunch but I had the same result

composer update
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
> php scripts/check.php
> php scripts/save-repo.php
> Claroline\CoreBundle\Library\Maintenance\MaintenanceHandler::enableMaintenance
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing paragonie/random_compat (v1.3.0)
  - Removing symfony/polyfill-apcu (v1.1.1)
  - Removing monolog/monolog (1.18.1)
  - Installing monolog/monolog (1.19.0)
    Downloading: 100%

  - Removing symfony/symfony (v2.7.10)
  - Installing symfony/symfony (v2.7.7)
    Downloading: 100%

  - Removing symfony/monolog-bundle (v2.10.0)
  - Installing symfony/monolog-bundle (2.11.1)
    Downloading: 100%

  - Removing zendframework/zend-stdlib (3.0.0)
  - Installing zendframework/zend-stdlib (3.0.1)
    Downloading: 100%

  - Removing zendframework/zend-math (2.6.0)
  - Installing zendframework/zend-math (2.7.0)
    Downloading: 100%

  - Removing friendsofsymfony/oauth2-php (1.2.0)
  - Installing friendsofsymfony/oauth2-php (1.2.1)
    Downloading: 100%

  - Removing seld/cli-prompt (1.0.1)
  - Installing seld/cli-prompt (1.0.2)
    Downloading: 100%

  - Removing composer/spdx-licenses (1.1.2)
  - Installing composer/spdx-licenses (1.1.3)
    Downloading: 100%

  - Removing composer/semver (1.3.0)
  - Installing composer/semver (1.4.0)
    Downloading: 100%

  - Removing composer/composer (1.0.0-beta1)
  - Installing composer/composer (1.0.0)
    Downloading: 100%

  - Removing claroline/core-bundle (6.8.4)
  - Installing claroline/core-bundle (6.9.0)
    Downloading: 100%

  - Removing claroline/cursus-bundle (6.1.13)
  - Installing claroline/cursus-bundle (6.2.0)
    Downloading: 100%

  - Removing claroline/message-bundle (6.0.6)
  - Installing claroline/message-bundle (6.0.7)
    Downloading: 100%

  - Removing icap/dropzone-bundle (v6.2.0)
  - Installing icap/dropzone-bundle (v6.2.1)
    Downloading: 100%

  - Removing innova/path-bundle (v6.1.9)
  - Installing innova/path-bundle (v6.1.11)
    Downloading: 100%

  - Removing ujm/exo-bundle (6.1.1)
  - Installing ujm/exo-bundle (6.1.3)
    Downloading: 100%

  - Installing mikey179/vfsstream (v1.6.3)
    Downloading: 100%

  - Installing sebastian/diff (1.4.1)
    Downloading: 100%

  - Installing fabpot/php-cs-fixer (v1.11.2)
    Downloading: 100%

  - Installing phpunit/php-timer (1.0.7)
    Downloading: 100%

  - Installing sebastian/recursion-context (1.0.2)
    Downloading: 100%

  - Installing sebastian/exporter (1.2.1)
    Downloading: 100%

  - Installing sebastian/comparator (1.2.0)
    Downloading: 100%

  - Installing phpdocumentor/reflection-docblock (2.0.4)
    Downloading: 100%

  - Installing phpspec/prophecy (v1.6.0)
    Downloading: 100%

  - Installing sebastian/environment (1.3.5)
    Downloading: 100%

  - Installing phpunit/php-text-template (1.2.1)
    Downloading: 100%

  - Installing sebastian/version (1.0.6)
    Downloading: 100%

  - Installing sebastian/global-state (1.1.1)
    Downloading: 100%

  - Installing phpunit/phpunit-mock-objects (2.3.8)
    Downloading: 100%

  - Installing phpunit/php-token-stream (1.4.8)
    Downloading: 100%

  - Installing phpunit/php-file-iterator (1.4.1)
    Downloading: 100%

  - Installing phpunit/php-code-coverage (2.2.4)
    Downloading: 100%

  - Installing phpunit/phpunit (4.8.24)
    Downloading: 100%

  - Installing claroline/dev-bundle (dev-master 80d96fe)
    Cloning 80d96fe1ef8fbb9f6770529cd78bd26b75b5dc59

  - Installing symfony/phpunit-bridge (v3.0.4)
    Downloading: 100%

  - Removing nelmio/api-doc-bundle (dev-master 2a0f95e)
  - Installing nelmio/api-doc-bundle (dev-master 718dfc6)
    Cloning 718dfc6e9c2b37000c3dd0740ebd09cffd3bc022

  - Removing johngrogg/ics-parser (dev-master 3b56078)
  - Installing johngrogg/ics-parser (dev-master 8ed85e9)
    Cloning 8ed85e9ce540f0ebea43f5d6789a984e3138380f

  - Removing stefk/jval (dev-master b663b82)
  - Installing stefk/jval (dev-master d0b5dd6)
    Cloning d0b5dd610caaa7a06e882f3ac1e607f725a73d76

phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Writing lock file
Generating autoload files
> composer bundles
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
> Claroline\BundleRecorder\ScriptHandler::buildBundleFile
Script Claroline\BundleRecorder\ScriptHandler::buildBundleFile handling the bundles event terminated with an exception

                                                                                                                                                                
  [ErrorException]                                                                                                                                              
  Argument 4 passed to Composer\DependencyResolver\Solver::__construct() must implement interface Composer\IO\IOInterface, none given, called in /home/claco/vendor/claroline/bundle-recorder/Recorder.php on line 93 and defined
                                                                                                                                                                

bundles [--dev] [--no-dev] [--] [<args>]...

Script composer bundles handling the post-update-cmd event returned with an error

  [RuntimeException]
  Error Output: Running composer as root/super user is highly discouraged as
  packages, plugins and scripts cannot always be trusted
  > Claroline\BundleRecorder\ScriptHandler::buildBundleFile
  Script Claroline\BundleRecorder\ScriptHandler::buildBundleFile handling the
   bundles event terminated with an exception

    [ErrorException]

    Argument 4 passed to Composer\DependencyResolver\Solver::__construct() mu
  st implement interface Composer\IO\IOInterface, none given, called in /home
  /claco/vendor/claroline/bundle-recorder/Recorder.php on line 93 and defined

  bundles [--dev] [--no-dev] [--] [<args>]...

**Comment by stefk** [comment]
The error is due to an API change in recent versions of composer. This is already fixed here. I added the fix to the old repo (see claroline/BundleRecorder#13), so it shouldn't happen again on the current v6.
