### ISSUE TITLE
Automate translation process

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#1712]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master/7.0/etc.

We need proper tooling to address current translation issues:

- [ ] a cli linter for translation files (at least for sorting translation keys)
- [ ] a git hook executing the previous tool locally
- [ ] a travis build step checking translations files are correctly linted
- [ ] a cli tool reporting any mismatch (ie missing translations) in a set of translation files
- [ ] a travis build step executing the previous tool, creating a dedicated github issue with detailed information if needed

**Comment by LaurentGruber** [comment]
Intégrer weblate pour la gestion des traductions : https://weblate.org/fr/
Il est gratuit pour les logiciels libre et est intégré à github ...
@om64

**Comment by om64** [comment]
@stefk @LaurentGruber After testing it locally, I'm quite sure Weblate is the tool we need.

**Comment by om64** [comment]
@stefk Just tell me when I can go on testing Weblate online and push to GitHub.

**Comment by om64** [comment]
@stefk 
Last configurations needed on Weblate:
- subscription via email
- subscription via social media
- enable automatic translation

**Comment by LaurentGruber** [comment]
http://translate.claroline.com/
