### ISSUE TITLE
Problem with the display of secondary resources in the path

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#1729]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

When there is lots of secondary resources of resource with a long name the display is not very ergonomics. Maybe it's better to create a panel of something els to display this resources.

**Comment by Gatomlo** [comment]
It would also be useful to choice the order of the resources.

**Comment by Elorfin** [comment]
First point is fixed with the new theme and there is another issue for the second one.
