### ISSUE TITLE
Import WS and Create a WS with model

### ISSUE THREAD

**Issue by david42** [claroline/Distribution#174]
- I  imported a WS with a zip file generated by an export, the announcements resourses are not created in the import
- Also, I have a problem to create a WS with a model (the same WS in the first point), I have these logs:
_
[Tue Apr 19 16:17:16.731620 2016] [:error] [pid 7875] [client
161.3.1.101:51358] PHP Notice: Undefined variable: resourceNode in
/webapps/claroline-connect/vendor/claroline/core-bundle/Manager/WorkspaceModelManager.php
on line 807, referer:
https://claroline-connect.univ-st-etienne.fr/web/app.php/workspaces/new/form
[Tue Apr 19 16:17:16.731837 2016] [:error] [pid 7875] [client
161.3.1.101:51358] PHP Fatal error: Call to a member function getName()
on null in
/webapps/claroline-connect/vendor/claroline/core-bundle/Manager/WorkspaceModelManager.php
on line 807, referer:
https://claroline-connect.univ-st-etienne.fr/web/app.php/workspaces/new/form_

I attach the zip file of the WS:
[MODELE_MEDECINE_9_COURS.zip](https://github.com/claroline/Distribution/files/226686/MODELE_MEDECINE_9_COURS.zip)

**Comment by stefk** [comment]
Import/export of announcements doesn't seem to be implemented yet. Maybe we should open a ticket for that feature?

As for the workspace creation, I can confirm the bug is still here but on line 793. It seems that this code has never been tested.

**Comment by ngodfraind** [comment]
+1

I'm on it.

**Comment by ngodfraind** [comment]
Fixed by #178.
