### ISSUE TITLE
Change export button in exercises

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#1750]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master

 The export button in the exercises has to be changed. The popover should tell the user it's a QTI export.

![export-button](https://cloud.githubusercontent.com/assets/14308826/21568902/815e22e8-ceb8-11e6-9ef6-916cee7b7b5f.png)

**Comment by LaurentGruber** [comment]
tout la top barre a été refaite
