### ISSUE TITLE
[CoreBundle] Administration Code 'uniqueness' side effects

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#1788]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 8.0.2

The use of the administration code in user as a 'unique' field (and thereby as an identification field) has some serious side effects in systems that already used the same code for multiple users. First of all, the fact that there is no 'uniqueness' restriction in administration code (as there is for email and login for example) leaves the possibility to attribute the same code to multiple users. That is the case for many instances that use this code to group together some of their users (it's easier for them to search these users afterwards using this code and as there was no restriction prohibiting this action). The problem is that now, the code is used as an identification field for users, so issue number one: if the username of user X is the same as the administration code of user Y then trying to usurp user X or Y is impossible as there is a 'NoUniqueException' returned from method 'findUserByUsernameOrMailOrCode', used to retrieve the user. That is a minor issue. The big problem comes with account creation via a CSV file. If there are multiple accounts in the CSV file with the same Administration Code ONLY THE LAST ONE IS CREATED, while the message displayed says that every account was created. You can test this with this 
[file](https://github.com/claroline/Distribution/files/695636/FR.PDL.Directeurs.FPC2.txt) (rename it to .csv first). Even worse, if an account with the same code already exists in plateforme it GETS UPDATED with the new user's data even though 'Creation only' option was chosen in the submit form. The result is that many accounts have 'what seems to be' deleted (as the users can no longer log in nor can be found by the search engine) while others (the new accounts) have the content (workspaces, resources etc.) of these 'deleted' accounts. So instead of creating a new account for the CSV user data, an existing account with the same code gets updated to contain these new user data. Which is a big security issue but also a big functional issue.

What would you propose for those instances that have users with the same administration codes? (knowing that changing them manually is not an option as they may have some thousands of users in their DB).

@LaurentGruber @ngodfraind 

Thank you in advance for your replies.

**Comment by CPASimUSante** [comment]
OMG : i do use the same code for many user (even though i should use groups to do this). This issue is then very serious : "changing the rules" (registration mandatory fields, uniqueness or not) when the platforms in prod is indeed a dangerous idea.

**Comment by ngodfraind** [comment]
I'm looking at this.
