### ISSUE TITLE
Add an anonyme mode.

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#1824]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Add the possibility to make a clacoForm anonymous. At the file creation the user and the date are note save in the db.

**Comment by LaurentGruber** [comment]
si on fait ça, le user ne pourra plus modifier le contenu qu'il a mis (on ne sait pas qui a mis quoi) ... De plus c'est plus une fonction utile pour un sondage que pour une suite de fiche. On devrait éviter de créer de la supperposition de périmètre fonctionnel entre les ressources, sinon on a va se compliquer la vie ... A réfléchir donc ...
