### ISSUE TITLE
Edition de question sur un exercice

### ISSUE THREAD

**Issue by geezot** [claroline/Distribution#1828]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | dev-master

Lors de l'édition (en modification) de question sur un exercice la question n'est pas éditée et l'on est redirigé vers la banque de questions de la plateforme 
plus d'infos envoyées à @ngodfraind

**Comment by LaurentGruber** [comment]
la nouvelle version des exercices sort fin du mois, cela y est corrigé
