### ISSUE TITLE
Add a Photos Album

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#1831]
Maybe we can user this simple Bootstrap Gallery : https://github.com/michaelsoriano/bootstrap-photo-gallery

**Comment by Gatomlo** [comment]
This is an example in Claroline : http://claroline-master.travis-build.claroline.net/resource/open/claroline_web_resource/2789

You can see that this gallery is responsible. 

Here it is include in the plaform with "Website Resource"

**Comment by Batier** [comment]
effectivement c'est plus qu'interessant

**Comment by Elorfin** [comment]
Il y a la nouvelle ressource "Diaporama".
