### ISSUE TITLE
on ne peux plus rajouter de widget dans un espace de travail?

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#1852]
![image](https://cloud.githubusercontent.com/assets/5484259/22325400/1b41b546-e3ae-11e6-98ea-d854b9dd323c.png)

je viens de créer un esapce de travail 
je viens de creer l'onglet accueil
le bouton aujouter un widget n'apparait pas 

| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version    | (8.0.2

**Comment by Batier** [comment]
en fait en fermant le navigateur et en rechargeant la page,
 le bouton apparait
![image](https://cloud.githubusercontent.com/assets/5484259/22325674/7a3e5328-e3af-11e6-85e9-95e705998f69.png)

**Comment by CPASimUSante** [comment]
Un raffraichissement de la page suffit. C'est cependant effectivement perturbant.

**Comment by LaurentGruber** [comment]
Faire ceci https://github.com/claroline/Distribution/issues/1796 devrait résoudre le souci de rechargement
