### ISSUE TITLE
[Administration tools] Group Management

### ISSUE THREAD

**Issue by eddymarques** [claroline/Distribution#186]
in Administration/User Management/Group Management
the possibility to populate the groups by CSV file as disapeared in the last version of the tool

**Comment by ngodfraind** [comment]
Sur la 6.9.x c'est réimplémenté.

https://github.com/claroline/CoreBundle/commit/74800c833fbea0f78b74c9fc2643edfd6ce2a841

J'ai pas retesté par contre.

**Comment by ngodfraind** [comment]
Ou alors on parle de  créer la liste des groupes et là elle a effectivement disparue. Je remet ça en place.
