### ISSUE TITLE
[Administration tools] Labels in Desktop tools

### ISSUE THREAD

**Issue by eddymarques** [claroline/Distribution#187]
in Administration / Desktop tools
changing labels seem visible anywhere, whether on old or new workspaces.

How to apply modifications? Or where should we see them?

**Comment by ngodfraind** [comment]
The tool bar has been removed for the desktop. That's why it's pretty much useless imo. Should I remove this part of the administration ?

Tools name can still be changed in workspace in workspace => parametres => tools
@claroline/maintainers
