### ISSUE TITLE
Notification d'une publication ne fonctionne pas

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#1890]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      |  master travis

La case Publication Ressource est cochée dans la préférence
Publier une ressource (tester avec fichier et texte) dans un espace

La notification n'apparaît pas chez les utilisateurs de l'espace

**Comment by ngodfraind** [comment]
Sur ta plateforme tu as le problème ou c'est uniquement sur le master ?

**Comment by ngodfraind** [comment]
Je n'ai pas pu reproduire l'erreur.

J'ai testé de la façon suivante:

- 2 users dans mon EA
- une ressource exo non publiée

=> je publie l'exo => les 2 users sont notifiés
