### ISSUE TITLE
Evaluation avec lien

### ISSUE THREAD

**Issue by david42** [claroline/Distribution#1929]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 8.0.3

Bonjour,

Une évalution dans laquelle un lien est demandé a été créée.
Lorsque l'on souhaite enregistrer le lien nous avons cette erreur : 

PHP Fatal error:  Call to a member function getId() on null in /webapps/claroline-connect/vendor/claroline/distribution/plugin/dropzone/Controller/DropController.php on line 109, referer: https://claroline-connect.univ-st-etienne.fr/web/app.php/icapdropzonebundle/712/drop

**Comment by LaurentGruber** [comment]
@ptsavdar @dtisch l'un de vous pourrait regarder ?
