### ISSUE TITLE
Bug site web suite à la mise a jour en 9.0

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#1950]
le site web ne s'affiche plus correctement ça mouline sans fin et sans message d'erreur
![image](https://cloud.githubusercontent.com/assets/5484259/22684397/709d2512-ed1c-11e6-8ef2-5644e6a03f4a.png)

| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master/9.0.0

**Comment by ngodfraind** [comment]
Je vais regarder pour reproduire/corriger ce matin.

**Comment by Batier** [comment]
j'ai vu le soucis sur http://accu2016.univ-lyon1.fr
Panos regarde d'où cela pourrait provenir

**Comment by ngodfraind** [comment]
Fixed by #1953
