### ISSUE TITLE
Bug Blog Suite à mise à jour 9.0.0

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#1951]
le blog ne s'affiche plus dans le navigateur
![image](https://cloud.githubusercontent.com/assets/5484259/22686272/bef68ee0-ed23-11e6-85bf-c3df9d0750ef.png)

| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master/9.0.0

**Comment by ngodfraind** [comment]
Il y a un truc de bizarre avec du json en bas. C'est pas Panos qui debug ?

**Comment by ngodfraind** [comment]
Reproduit.

**Comment by Batier** [comment]
j'ai identifié le soucis dans le cas present dans la partie information qui est du texte enrichi dans lequel se trouve un embed youtube

**Comment by ngodfraind** [comment]
Il y a d'autres problèmes pour le blog j'ai l'impression de toute façon.
Panos a déjà corrigé le site web.

**Comment by ptsavdar** [comment]
Fixed by #1973
