### ISSUE TITLE
Soucis sur les onglets d'un espace de travail contenant un widget Blog

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#1968]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 9.0.0

Quand dans un onglet on a un widget blog ...
Suite à la mise a jour impossible d'afficher le contenu de l'onglet
aucun message d'erreur en retour
David a commencé à regarder d'où vient le soucis.

**Comment by ptsavdar** [comment]
Fixed by #1973
