### ISSUE TITLE
[Ergonomie] : Il faut distinguer deux types d'icones une pour les espace de travail et une pour les dossiers

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#1996]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 9.0

Aujourd'hui nous avons la même icone entre espace de travail et dossier dans un espace de travail
![image](https://cloud.githubusercontent.com/assets/5484259/22824855/443bc6ca-ef8a-11e6-80ed-0c9510bf4225.png)

du coup quand on passe par le pickeur de ressource et qu'on cherche des ressource on peut sortir de son espace de travail sans graphiquement sans rendre compte et prendre des ressources d'autres espace de travail où les etudiant n'auront pas les droits...

je pense qu'il faut distinguer les deux visuellement

**Comment by ngodfraind** [comment]
C'est une bonne idée, et relativement simple à implémenter en plus je pense.

**Comment by Batier** [comment]
bonjourPetit rappel surtout si c'est pas compliqué
 ça devient urgent il se passe pas une journée sans que l'on constate de multiple confusion surtout quand les gens passe par le selecteur de ressource ou tout est à plat.

**Comment by Batier** [comment]
et si on pouvait attribuer aussi des vignettes aux espaces d'activité ça éviterai d'avoir un sélecteur de ressource  tristouille :
![image](https://user-images.githubusercontent.com/5484259/27484912-30ab6516-582b-11e7-8b9e-943c213909da.png)

**Comment by LaurentGruber** [comment]
c'est une demande d'amélioration, le tag urgent est pour les bug bloquant...
