### ISSUE TITLE
[BadgeBundle] Claming a badge throws this error

### ISSUE THREAD

**Issue by ngodfraind** [claroline/Distribution#1998]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

 User was reloaded from a user provider. {"username":"root","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
853 [2017-02-10 14:19:01] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Object of class Icap\BadgeBundle\Entity\Badge could not     be converted to string" at /home/egreta/claroline/vendor/zenstruck/form-bundle/Zenstruck/Bundle/FormBundle/Form/DataTransformer/AjaxEntityTransformer.php line 87 {"exception":"[object] (Symfony\\Compo    nent\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Object of class Icap\\BadgeBundle\\Entity\\Badge could not be converted to string at /home/egreta/claroline/vendor/zenstr    uck/form-bundle/Zenstruck/Bundle/FormBundle/Form/DataTransformer/AjaxEntityTransformer.php:87)"} []

**Comment by ptsavdar** [comment]
@ngodfraind I'm looking after this.

**Comment by ngodfraind** [comment]
I fixed it locally already

**Comment by ptsavdar** [comment]
Ok np.
