### ISSUE TITLE
user csv import add group option

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#200]
Ajout d'une colonne supplémentaire au fichier csv (inscription d'utilisateurs) dans laquelle
l'administrateur indique le nom d'un groupe existant dans la plateforme. Lors de l'import de
ce fichier, la plateforme inscrit les utilisateurs non existants et les ajoute au groupe
référencé. Si l'utilisateur existe déjà, la plateforme se contente de l'ajouter au groupe
référencé.

**Comment by clarophil** [comment]
Il est déjà possible d'ajouter des utilisateurs dans un groupe à l'aide d'un csv mais séparément de l'importatiton.

**Comment by LaurentGruber** [comment]
En effet, l'objectif ici est à la création de pouvoir attribuer directement un groupe au user.
