### ISSUE TITLE
Issue : missing file on installing release 9.0.1

### ISSUE THREAD

**Issue by NicolasHairon** [claroline/Distribution#2021]
| Bug report?   | yes
| Version?      | release/9.0.1

Issue on installing release 9.0.1 with : 

$ wget https://github.com/claroline/Claroline/archive/9.0.1.zip
$ unzip 9.0.1.zip
$ cd Claroline-9.0.1
$ php scripts/configure.php
$ composer fast-install

`Script php app/console doctrine:database:create --if-not-exists handling the fast-install event returned with an error
                                                                                                                                                                              
  [RuntimeException]                                                                                                                                                           
  Error Output: PHP Warning:  require_once(/var/www/html/Claroline-9.0.1/app/bootstrap.php.cache): failed to open stream: No such file or directory in /var/www/html/Claroline-9.0.1/app/console on line 10                                                                                                                                               
  PHP Fatal error:  require_once(): Failed opening required '/var/www/html/Claroline-9.0.1/app/bootstrap.php.cache' (include_path='.:/usr/share/php') in /var/www/html/Claroline-9.0.1/app/console on line 10`

**Comment by kitan1982** [comment]
The installation from a pre-built archive requires that you fetch the archive from http://packages.claroline.net/releases/
This installation method is not available for release 9.0.1 as there is no archive for this version yet

**Comment by kitan1982** [comment]
The archive for release 9.0.1 has been generated.

You can install it with the following commands :

$ curl packages.claroline.net/releases/latest/claroline-9.0.1.tar.gz | tar xzv
$ php scripts/configure.php
$ composer fast-install
