### ISSUE TITLE
problème d'installation bundle 

### ISSUE THREAD

**Issue by clacoDeBDev** [claroline/Distribution#2037]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 9.1.0

Bonjour,

J'ai installé la dernière version 9.1.0. Cette version nécessite la version php >=5.6.
Lors de l'installation de mon bundle avec cette version de php, j'ai eu cet erreur:

PHP Fatal error:  Class 'XXX\XXXXBundle\XXXXXBundle' not found in /home/XXX/public_html/Claroline/vendor/claroline/distribution/main/kernel/Manager/BundleManager.php on line 55

J'ai essayé aussi de générer un bundle suivant cette procédure:
 
php app/console claroline:plugin:create Claroline Etherpad --resource_type=EtherpadDoc -i
php app/console claroline:plugin:install
php app/console claroline:migration:generate ClarolineEtherpadBundle
php app/console claroline:migration:upgrade ClarolineEtherpadBundle

Mais au niveau de cette commande php app/console claroline:plugin:install la même erreur php fatal persiste aussi.

Merci par avance pour votre aide.

Cordialement,

**Comment by Elorfin** [comment]
Bonjour,

Il est possible que ce soit parce que l'autoloader ne connait pas les classes de ton nouveau plugin.
Tu peux le mettre à jour avec la commande : 

```
composer dump-autoload -o
```

A noté que l'utilisation du flag `-i` dans la commande `claroline:plugin:create` permet d'installer directement le plugin à la création. Cela rend donc inutil l'usage de `claroline:plugin:install` (qui d'ailleurs prend en argument le num du plugin à installer, aka ClarolineEtherpadBundle).
