### ISSUE TITLE
Wiki accessible aux anonymes

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#2054]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 9.1

Quand je veux mettre un wiki accessible aux anonymes j'ai l'erreur : 

request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function getId() on null" at /home/3l/www/vendor/claroline/distribution/plugin/wiki/Repository/SectionRepository.php line 40 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function getId() on null at /home/3l/www/vendor/claroline/distribution/plugin/wiki/Repository/SectionRepository.php:40)"} []

**Comment by dtisch** [comment]
@LaurentGruber : Je n'arrive pas à reproduire cette erreur. Est-ce bien par ici que tu cherches à rendre le wiki accessible aux anonymes ? 
![image](https://cloud.githubusercontent.com/assets/10739686/23354649/83b27178-fcd2-11e6-87d7-385f124fae01.png)
De plus, est-ce que l'erreur apparaît sur un ancien wiki ou sur un nouveau créé après la mise à jour ?

**Comment by Gatomlo** [comment]
@dtisch C'est bien par là! 
Il s'agit d'un ancien Wiki.

**Comment by dtisch** [comment]
@LaurentGruber @Gatomlo Est-ce que la ligne 33 du fichier SectionRepository.php qui pose souci sur votre installation correspond  à ce code :
`if ($isAdmin === false && $user !== null) {` ?
Cette correction a déjà été apportée sur la branche 9.x. Vous êtes sûrs de bien être en version 9.1 ?

**Comment by Gatomlo** [comment]
@dtisch On vient de mettre à jour sur la dernière version et le problème persiste.
Pourrais-tu me préciser où se trouve le fichier SectionRepository ?

**Comment by dtisch** [comment]
@Gatomlo Distribution/plugin/wiki/Repository/SectionRepository.php (https://github.com/claroline/Distribution/blob/9.x/plugin/wiki/Repository/SectionRepository.php)

**Comment by dtisch** [comment]
@Gatomlo, c'était une correction apportée dans l version tagguée 9.0.1 : https://github.com/claroline/Distribution/commit/993e3dd92b107800ad5ad0d368aefaa196579393

**Comment by Elorfin** [comment]
Après mise à jour de la plateforme et suppression du cache de symfo (y a un bug fix dans le template twig aussi) tout est correct.
Merci pour le coup de main @dtisch.
