### ISSUE TITLE
[ExoBundle] Give access to the results to users

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#2055]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 9.x

The results menu is hidden for users who can not edit the quiz.
We need to make it available to them.

**Comment by om64** [comment]
I think results are visible to connected users even if they're not allowed to edit.

**Comment by pitrackster** [comment]
@om64 from what I saw results are visible at the end of the assessment but the student can not access his papers from the exercise overview (no menu shown)

**Comment by om64** [comment]
@pitrackster That's it !

**Comment by pitrackster** [comment]
This PR https://github.com/claroline/Distribution/pull/2164 allow users to access there papers.

IMHO we need to elucidate some questions

- For now the paper list does not take into account `showScoreAt`  && `showCorrectionAt` parameters
  - Which parameters do we need ? Which ones are really implemented ?
- What should we do for anonymous users (the access to paper list seems to be forbidden for such users) 
- The quiz overview can be disabled... how the user is supposed to access his papers in this case ?
