### ISSUE TITLE
[CoreBundle] Resource rights edit problem

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#2057]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 9.1.0

When trying to edit resource rights for a user (by importing user using the button "Add user") on submit I have this error:
```
[2017-02-27 14:43:44] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getName() on null" at 
/data/www/clarolineconnect/claroline/vendor/claroline/distribution/main/core/Controller/ResourceRightsController.php 
line 372 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): 
Call to a member function getName() on null at 
/data/www/clarolineconnect/claroline/vendor/claroline/distribution/main/core/Controller/ResourceRightsController.php:372)"} []
```

It does't occur for every user I'm trying to add but for some users I have this error.

**Comment by ptsavdar** [comment]
I found the root of the problem and I think it's a big one! When a user changes his username, he "loses" his personal user role because it the RoleRepository the method findUserRoleByUser uses the username to retrieve the user role. But now the username is not the same...

**Comment by Elorfin** [comment]
In fact role should stay sync with the current username : https://github.com/claroline/Distribution/blob/master/main/core/Manager/UserManager.php#L297.

I will investigate further.

**Comment by ptsavdar** [comment]
Well, when I tried to edit the user from user administration form it didn't change the user role name.

**Comment by ptsavdar** [comment]
I think the problem lies here: https://github.com/claroline/Distribution/blob/master/main/core/Controller/ProfileController.php#L278

The $user object passed to method "rename" already contains the new username, as a result the old username and thus the old user role gets lost.
