### ISSUE TITLE
[ExoBundle] Score sur 10 ou sur 20 aux questionnaires

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2060]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 9.x

**Comment by Pauooo** [comment]
Le score max est la simple somme des scores max de chaque question du questionnaire. 
Il n'y a actuellement pas de fonctionnalité permettant de faire la conversion sur 10 ou sur 20.

**Comment by Batier** [comment]
?? c'est une blague? à rajouter d'urgence!
et ou est passé le moteur de recherche qui permettait de trouvé tout les résultats d'un étudiant sur un questionnaire?

**Comment by Pauooo** [comment]
Si je ne dis pas de bêtises, dans l'ancienne version il n'y avait pas d'option "convertir sur 10 ou 20", le score était directement sur 20 et ce seulement pour le score de la copie. 
Pour la recherche, en effet elle n'a pas été remise, elle le sera.

**Comment by Batier** [comment]
toutes les plateformes permettent un score sur 10 ou 20.....

**Comment by Pauooo** [comment]
Besoin recensé dans Taïga

**Comment by Batier** [comment]
?? c'est quoi  Taiga?
