### ISSUE TITLE
quand on désactive le pdfplayer on a une erreur 

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2062]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 9.0
![image](https://cloud.githubusercontent.com/assets/5484259/23400410/3bea0298-fda4-11e6-9925-802155f052d6.png)
apres avoir desactivé ce plugin quand je clique sur un pdf j'ai une erreur 500
alors qu'on devrait proposer d'ouvrir le pdf sur le pdf reader installé sur le client

**Comment by ptsavdar** [comment]
Voici l'erreur:

```
Unable to find template "ClarolinePdfPlayerBundle::pdf.html.twig" (looked into: 
/data/www/clarolineconnect/claroline/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form, 
/data/www/clarolineconnect/claroline/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views).
```

**Comment by LaurentGruber** [comment]
il y a un workaround (ne pas désactiver le pdf player). Donc ça ne peut pas être vu comme urgent, vu que ce n'est pas bloquant ...
