### ISSUE TITLE
Quelle mise à jour pour régler ce problème : Questionnaires apparaissent en anglais suite à la mise a jour #1431

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#2074]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 8.0.4
![exo1](https://cloud.githubusercontent.com/assets/22524770/23544628/fba20f18-fff7-11e6-9a03-d481f8e86693.jpg)
![exo2](https://cloud.githubusercontent.com/assets/22524770/23544629/fbc5c2dc-fff7-11e6-8723-0a3da2420ea0.jpg)

Ce sujet à été clos et je ne pourrai probablement pas avoir de réponse à ma question posée dans #1431 donc je la renouvelle ici. Quelle mise à jour faut-il faire pour régler ce problème ?
Merci par avance.

**Comment by LaurentGruber** [comment]
Il faut exécuter les updaters avec la command test_update de app/console

**Comment by Garakotxea** [comment]
Bonsoir,
En fait il avait suffit d'enlever le nom de domaine et de cocher SSL dans les paramètres de la plateforme pour que cela fonctionne.
Nicolas m'avait indiqué ces paramétrages pour que le site cesse ces requêtes en boucle et cela avait du coup également réglé le problème des boutons en anglais.
Merci pour votre retour.
Bien à vous.
