### ISSUE TITLE
Editeur d'équation "absent"

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#2076]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 8.0.4
En survolant l'emplacement du bouton on voit bien que l'outil est là mais son icône n'apparaît pas et une page blanche s'affiche quand on le lance.
Quel paquet faut-il réinstaller ?
Merci par avance
![image](https://cloud.githubusercontent.com/assets/22524770/23544860/089a715a-fff9-11e6-9f82-ddc77dcd9c6d.png)
![image](https://cloud.githubusercontent.com/assets/22524770/23544907/40fcc73c-fff9-11e6-9a54-ea3e376a19db.png)

**Comment by ngodfraind** [comment]
Vous avez configuré le "nom de domaine" et "ssl" dans les paramètres de l'appli ?

**Comment by Garakotxea** [comment]
Pas ssl. Il me semblait avoir lu dans un post que cela posait problème parfois. Je teste en suivant.

**Comment by ngodfraind** [comment]
Essayez de supprimer le nom de domaine des paramètres.

**Comment by Garakotxea** [comment]
Ça a été long (clé 3G + onglets qui "tourne en boucle" : j'ai ça aussi à régler).
Ca ne change rien.

**Comment by Garakotxea** [comment]
Je tente la suppression du nom de domaine.

**Comment by Garakotxea** [comment]
Super, je n'ai plus le site qui "tourne en boucle" et j'ai l'éditeur d'équation.
Ouah, un grand MERCI Nicolas :))))
