### ISSUE TITLE
Missing functionnnalities and ergonomy improvements in Support Bundle

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#2078]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master

I've been testing the Support bundle and I noted several problems : 

- Obiously there is this one : https://github.com/claroline/Distribution/issues/1593 
There is no real closed state for a ticket.

But, apart from that :
- When a administrator answers a ticket, there are 2 messages : message client (the real answer i guess) and internal message, but the client who opened the tiket doesn't see the message ! He only sees potential comments.
![support4](https://cloud.githubusercontent.com/assets/14015697/23552400/fbac153e-001b-11e7-9cd4-4d7ed51988c8.png)

- More generally, ther is no list of ticket tracking : only the code of the last intervention appears on the client side. He should see the whole list of the interventions.
![support5](https://cloud.githubusercontent.com/assets/14015697/23552534/be6dca9a-001c-11e7-985d-cc768e13083e.png)

- In french, Status management is translated into "Gestion des Statuts" : it should be "Gestion des états d'avancement des tickets" or something more explanatory than this ugly "frenglish" word Statut.
![support1](https://cloud.githubusercontent.com/assets/14015697/23551774/9af249c8-0018-11e7-8061-70089205235d.png)

- The phone number shouldn't be mandatory when creating a ticket (or at least the admin should be able to choose) : in 90% of the cases i think, if this is a platform related question, the mail should suffice.

- On the administrator side, in the list of tickets : there should be a popover title added for the icon which changes the support type. this icon is not self explanatory and you have to click to see what it is about
![support2](https://cloud.githubusercontent.com/assets/14015697/23551969/b5b503f8-0019-11e7-9149-1ddfd00d4b9e.png)

- Adding a new intervention has several hard to understand features : 
Begin and end date are OK (1 on the capture), and ther is Duration (2 on the capture).
From what i understand, after a big while, it's one or another, that you choose with the "calcul mode" (3) : using end date, or using duration.
Ergonomically, it would be much more explicit if this calculation mode selection would appear first, and then would appear **only** the selected mode : the duration or the begin/end date.
![support3](https://cloud.githubusercontent.com/assets/14015697/23552294/68f6407a-001b-11e7-93de-702d2c245048.png)

**Comment by LaurentGruber** [comment]
closed by https://github.com/claroline/Distribution/pull/2182
