### ISSUE TITLE
Anti Plagiat

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#2080]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 8.0.4, 9.10 et futures

Bonjour,
Un outil anti plagiat propre à Claroline Connect ou un plugin genre http://plagiarisma.net/ pour Moodle est-il envisageable/prévu ?
Je n'ai rien trouvé sur le sujet dans les pages de Claroline.net.
Bien à vous.

**Comment by LaurentGruber** [comment]
L'ajout du support LTI est en cours : https://github.com/claroline/Distribution/pull/2048 il permettra notemment de connecter des outils antiplagiat supportant la norme LTI.

**Comment by Garakotxea** [comment]
Merci beaucoup pour le retour.
