### ISSUE TITLE
[ExoBundle] numérotation des questions dans un exercice

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#2090]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 9.1

Les questions portent toujours le numéro 1 dans un exercice : 
![image](https://cloud.githubusercontent.com/assets/895878/23754649/0a6e8ec8-04de-11e7-8b0e-e341b974ab11.png)

**Comment by Pauooo** [comment]
Je ne reproduis pas le problème. Ce sont des questions qui existaient avant la mise à jour ?

**Comment by Elorfin** [comment]
Il faut aller dans le contenu HTML de la question. Il doit y avoir un `<ul><li></li></ul>` qui traine.
Sauf erreur de ma part, les questions ne sont pas numérotées.

**Comment by clarophil** [comment]
@Elorfin c'est bien ça, un grand merci
