### ISSUE TITLE
[ExoBundle] Export des résultats

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#2091]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 9.1

Il n'est plus possible d'exporter les résultats des exercices
Dans les versions précédentes, on pouvait exporter les résultats en csv.

**Comment by Pauooo** [comment]
Oui c'est vrai, tout comme la docimologie, nous n'avons pas eu le temps de la remettre, c'est prévu.

**Comment by clarophil** [comment]
oui mais ça me semble plus simple à remettre en place

**Comment by Pauooo** [comment]
oui tout à fait.

**Comment by cecile-rockefeller** [comment]
Bonjour, quand pensez-vous remettre à disposition l'outil d'export...Cela est important pour nos entrainements aux examens.

**Comment by LaurentGruber** [comment]
Cela sera dans la version prévue pour le début du mois de juin et sur le master dans les jours à venir

**Comment by LaurentGruber** [comment]
https://github.com/claroline/Distribution/pull/2295
