### ISSUE TITLE
[BlogBundle] Can't configure the blog

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#2101]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 9.1

The configuration of the blog in the resource manager fails

Uncaught PHP Symfony\Component\Routing\Exception\RouteNotFoundException Exception: "Unable to generate a URL for the named route "icap_blog_configure" as such route does not exist." at /home/hevinci/claroline/app/cache/prod/appProdProjectContainerUrlGenerator.php line 1702

![image](https://cloud.githubusercontent.com/assets/895878/23858615/4e9d8696-0801-11e7-9439-08c9256f5c09.png)

**Comment by LaurentGruber** [comment]
@dtisch @ptsavdar une idée ?

**Comment by dtisch** [comment]
@clarophil @LaurentGruber @ptsavdar J'ai vu où se situe le problème, je prépare une correction.
