### ISSUE TITLE
Ordre des soumissions lors du téléchargement

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#2103]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 9.1

Dans  collecticiel et évaluation, on peut récupérer des dizaines voire de centaines de soumissions.
On les récupère actuellement dans l'ordre de soumission, cet ordre n'a aucun intérêt pour l'enseignant, l'ordre alphabétique des noms / prénoms serait beaucoup plus intéressant.
Dans le dossier caché, on aurait donc un dossier "Dupont Pierre" plutôt que "Document n°21 Pierre Dupont"

**Comment by ptsavdar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DropZone bundle issues:](https://trello.com/c/OWW4xfBy/152-dropzone-bundle-issues)

**Comment by clarophil** [comment]
Le problème reste pour le collecticiel.
