### ISSUE TITLE
[Résolu] Collaborateurs avec droits gestionnaire : urgent

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#2104]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 8.0.4

Bonjour,
Je viens de me rendre compte que les élèves sont gestionnaires, peuvent modifier les cours et ressources et même poster sur la page d'accueil. Que dois-je faire pour remédier à cela ?
Il se pourrait que cela soit le cas depuis la mise à jour même si je n'ai remarqué aucune modification dans les cours (widget redimensionné par mégarde par exemple). C'est arrivé à un élève à l'instant et c'est ainsi que je suis rendu compte du problème. Un Chmod a modifier ?
J'espère que ce problème n'a pas déjà été posé, je n'ai pas trouvé de correspondance en tapant "gestionnaire".

Merci par avance.
Bien à vous.

**Comment by Gatomlo** [comment]
C'est normal le rôle "gestionnaire" correspond à l'admin de l'espace d'activités.
Le rôle "étudiant" est "collaborateur".

**Comment by Garakotxea** [comment]
Les élèves sont en collaborateurs mais ont les droits gestionnaires.

**Comment by Garakotxea** [comment]
C'est peut-être parce que j'avais changé le nom en "étudiant" et qu'avec la mise à jour Claroline ne connait que "Collaborateur" ?

**Comment by Garakotxea** [comment]
J'ai plutôt un problème de chmod je suppose car la page d'accueil est modifiable sans connexion. Gros problème :(.

**Comment by Garakotxea** [comment]
Je n'y comprends rien. Si je tape l'URL depuis l'extérieur j'arrive sur la page d’accueil en mode création (modification possible), si je tape l'ip pour y accéder depuis el réseau interne je suis en mode utilisateur basique sans droit anormal. Ce n'est pas un bug de Claroline , je m'excuse pour le dérangement.
Bien à vous

**Comment by Garakotxea** [comment]
En fait depuis l'extérieur c'est bon. C'est en tapant l'URL d'un LAN vers un autre LAN du lycée (en passant par  le proxy) que l'on accède au mode modification de la page d'acceuil sans même avoir à se connecter. Je ne sais pas si quelqu'un a déjà ça mais c'est vraiment étrange :
- depuis l'extérieur on arrive sur la page d'accueil en mode "lecture" : OK
- en tapant l'adresse IP privée depuis le LAN du serveur hébergeant Claroline Connect : OK
- en tapant l'adresse IP publique depuis n'importe quel LAN : KO, page d'accueil en mode édition.

**Comment by Garakotxea** [comment]
Grâce à Nicolas dans un post du support communautaire: "Videz les fichiers app/config/ip_white_list.yml et app/config/white_list_ip_range.yml."

L'IP publique était entrée (comment ?) dans la liste blanche et du coup les élèves étaient en gestionnaire voire admin (édition de la page d'accueil) en tapant l'URL publique pour entrer dans un autre LAN du Lycée.

Bien à vous.
