### ISSUE TITLE
[ExoBundle] Cloze question problems

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#2106]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 9.1.0

First Issue: When keywords are added they are not trimmed, thus any trailing spaces are saved with the keyword. As a result correct answers are not recognized (because they're missing trailing spaces).

Second Issue: On gap fill questions with drop-down keyword list, when new keywords are added their values are often interchanged. E.g. When modifying the second keyword the first gets modified too and receives the same value as the second one. I think it might be a problem with angular's scope. I don't know. The result is that is difficult for users to fill in with different values since when they fill in the second value, this value is also copied in the first keyword.

**Comment by ptsavdar** [comment]
I'm providing here with some more information / feedback about the errors we're having:
Even if answers are correct, they are marked as false. More than that, some options won't show their complete contect (in the example below the answer "most" should be "most recent" but it gets cut to most)
![image](https://cloud.githubusercontent.com/assets/3414935/24137282/5f9f79b4-0e13-11e7-89c1-99ebc7bbff88.png)

Correction of the above answer:

![image](https://cloud.githubusercontent.com/assets/3414935/24137353/a2c9fbe2-0e13-11e7-9066-42e208045c8b.png)

The score (visible in second image) also remains a mystery... It's neither 0 (since all the answers are considered false nor 3/3 if we assume that it's an UI problem, it's 2/3).

**Comment by om64** [comment]
I've got exactly the same problem.

![cloze_false_gaps](https://cloud.githubusercontent.com/assets/14308826/24239650/14a6d838-0faf-11e7-8567-33314be9557e.png)
