### ISSUE TITLE
Chemin resources relatif ou absolu

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#2117]
| Q             | A
| ------------- | ---
| Bug report?   | yes or no
| Version?      | 8.0.4

Bonjour,
Claroline Connect est hébergé dans un serveur du lycée. On peut donc y accéder soit par l'IP/URL publique soit par l'IP/URL privé.
Quand on insère une image, contenue dans un répertoire des ressources d'un espace d'activité, dans un texte d'un widget, elle s'affiche dans le texte.
Je constate - nouvellement ? - que l'image ne s'affichera que si on la lit depuis le LAN ou le WAN selon qu'elle a été insérée depuis l'URL WAN ou l'URL LAN.
Il me semble qu'auparavant je n'avais pas ce problème. Le lien vers la ressources peut-il être en référencement relatif depuis le workspace ? Actuellement le "pointage" de la ressources se fait en mode absolu.
Exemple : /resource/open/file/6448

- Externe : https://connect.xxxxxxxxxxxxxxxxx.fr/resource/open/file/6448
- Interne : https://claroline/resource/open/file/6448

Bien à vous

**Comment by LaurentGruber** [comment]
la meilleur solution est de configurer le serveur dns du lan pour qu'il route correctement connect.xxxxxxx.fr vers l'ip lan également.

Si on ne met que des url relative quand des éléments sont envoyé par mail par exemple les images / liens ne passe pas ...

**Comment by Garakotxea** [comment]
D'accord, merci pour le retour. 
Je ne pourrai faire ça que pour un lan. L'autre administré par un collègue est derrière un serveur Kwartz qui ne permet pas ce type de pointeur DNS.  
Envoyé depuis mon mobile

-----Original Message-----
