### ISSUE TITLE
[CoreBundle] Notification de la publication d'un répertoire

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#2128]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      |  9.1

Créer un répertoire
Une notification est reçue par les utilisateurs
Le lien dans la notification génère un téléchargement du dossier plutôt qu'une ouverture du dossier dans le gestionnaire de ressources

**Comment by ngodfraind** [comment]
Erreur reproduite (ou en tout cas un erreur dans le lien de la notif même si c'est différent).
