### ISSUE TITLE
[CoreBundle]  Récursivité de la publication

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#2129]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      |  9.1

Dépublier un dossier ne dépublie pas toutes les ressources qui s'y trouvent.
Cela engendre beaucoup d'incompréhensions des enseignants car les étudiants peuvent toujours accéder aux ressources à l'intérieur du dossier dépublié.
Le comportement normal est d'appliquer la récursivité sur toutes les ressources qui sont incluses dans le dossier.  Quand on crée un ressource dans ce dossier, elle est d'office dépubliée.

Il y a un cas où l'on veut caché un dossier mais pas les ressources qui s'y trouvent, par exemple des ressources qui sont incluses à un parcours ou un exercice.  Pour ce cas, la ressource est dépubliée à la création et il suffit de forcer sa publication, on peut aussi casser la non publication en publiant un sous dossier.

**Comment by ngodfraind** [comment]
Tjrs d'actu je suppose.
