### ISSUE TITLE
[ExoBundle] - Toutes les questions ne sont pas immédiatement ajoutées à la banque de question

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#2140]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Il semblerait que les questions que je crée ne soient ajoutées à la banque de question que lorsque je crée une nouvelle étape dans le questionnaire.

**Comment by Pauooo** [comment]
Il se peut que le problème ait un rapport avec le fait que certaines questions ne soient pas liées à des users dans la DB : user_id=NULL

**Comment by pitrackster** [comment]
closed via https://github.com/claroline/Distribution/pull/2147
