### ISSUE TITLE
Suppression des essais des exercices

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#2141]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 8.0.4

Bonjour,
On peut supprimer les essais des QCM pour les exercices nouvellement créés dans les 8.0.4 mais pas ceux effectués sur la version 7.0.0. Je viens de créer un QCM avec des questions importées depuis Claroline 11.1.10 pour une collègue qui travaille encore sur l'ancienne plateforme du lycée et je ne peux donc pas effacer mes essais (j'avais oublié ce problème). De la même façon nous aurons tous les résultats de cette année à effacer dans nos multiples QCM importés depuis Claroline 11.1.10. Puisque cela n'est pas prévu depuis l'interface graphique pouvez-vous m'indiquer comment le faire "à la main" en ligne de commande ou dans la base de donnée (je ne connais pas MySql).
Bien à vous.

**Comment by LaurentGruber** [comment]
Je ne pense pas qu'il y ai de solution sur la version 7, sur la 9 ça doit être possible depuis l'interface...

**Comment by Garakotxea** [comment]
D'accord, merci pour le retour.
Bonne journée.



Admin ENT pédagogique Claroline
Jakes Irazoqui
claroline@ent-st-joseph-hasparren.fr
 
expéditeur: Gruber Laurent
Envoyé: 2017-03-20 10:26
A : claroline/Distribution
Cc : Garakotxea; Author
Sujet: Re: [claroline/Distribution] Suppression des essais des exercices (#2141)
 
Je ne pense pas qu'il y ai de solution sur la version 7, sur la 9 ça doit être possible depuis l'interface...
