### ISSUE TITLE
Can't save a widget text

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#215]
If I have a very long text and want to insert a new image at the end, the Ok Button can't be accessible even if the scrollbars are at the bottom.
Solutions 
- put the Ok button on the top of the popup
- add a button to save in the tynimce toolbar

![image](https://cloud.githubusercontent.com/assets/895878/14881498/90752330-0d34-11e6-8220-c280712e54cd.png)

**Comment by clarophil** [comment]
I think also that the pop up could be wider

**Comment by CPASimUSante** [comment]
-> To increase the modal width, override the bootstrap css : 
.modal-dialog {
    width: 75%;
}
-> to add a button in the TinyMce would be ergonomically awkard IMO : 
- this button would not clearly appear (at the end of the form, or duplicated in the begining)
- it would not appear in other modal forms where there are no rich text
(it would be overkill to make an exception to display it only in text widget)

-> put the ok button at the top of the popup : why not.

Another solution would be to set a fixed modal height, with scrollbar for long form (the modal are used for all kind of forms : 1 field or up to 10, with one or many rich text)

**Comment by kitan1982** [comment]
This issue comes from the fact that 2 modals are opened at the same time.
When closing the latest modal (the one to pick the image) the focus is set back to the main page and not the first modal.
Therefore the scrollbar is bound to the main page and not the first modal.
I think this issue is linked to Bootstrap.

**Comment by kitan1982** [comment]
Apparently a little fix can be applied :
https://github.com/nakupanda/bootstrap3-dialog/issues/70
