### ISSUE TITLE
[ExoBundle] Hyphenation issue in Quiz description

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#2151]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 9.1.0

In quiz description the text is aligned "justified". As a result we have the below collateral hyphenation issue:

![image](https://cloud.githubusercontent.com/assets/3414935/24137767/8c7fa39e-0e15-11e7-81bb-e82814e4933a.png)

No - present to cut words. In a small text it might seem fine but a long text gets difficult to read.

**Comment by LaurentGruber** [comment]
Correct by new thème on master
