### ISSUE TITLE
[ExoBundle] Banque de questions

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#2153]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Quand je vais dans ma banque de question j'ai une page blanche.

Dans la console : Error: Unknown item type text/html

**Comment by om64** [comment]
I had the same problem, but don't have it anymore. That bug seems to be corrected. Close the issue?

**Comment by LaurentGruber** [comment]
non le problème est toujours là
