### ISSUE TITLE
[ExoBundle] Enhancement: being able to customize end text

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#2155]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master

For now we are only able to show a generic message as end text, but it would be nice if the user was able to customize it, preferably with rich text. Teachers could use it to add specific instructions, link to another resource, display the examination correction date etc

**Comment by Elorfin** [comment]
This is available in the 10.x
