### ISSUE TITLE
Total score when editing questions

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#2165]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master

When editing exercises, it'd be nice to have the total score of the question mentioned next to the title of the question to have a quick check.

![score](https://cloud.githubusercontent.com/assets/14308826/24235847/601ea56c-0f9f-11e7-87a8-e772b6c9d578.png)

**Comment by Pauooo** [comment]
- [ ] This score max should be displayed in the header of the question panel (paper list style).
- The user should be able to set a score max <= sum of the score of all the items (but not 
   - [ ] Add this field after the question/title and other fields zone
   - [ ] QRU : the max set should be the score max item (not the sum)
