### ISSUE TITLE
Change incrementation of scores when editing items of a question.

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#2168]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master/7.0/etc.

Many questions use items. Their default scores are incremented by 1 unit. Is it possible to have a default incrementation of 0,5 as they are used very often?

**Comment by LaurentGruber** [comment]
ça à déjà été modifié ça non : https://github.com/claroline/Distribution/pull/2121

Dans quel type de questions ce n'est pas encore possible ?

**Comment by Pauooo** [comment]
@LaurentGruber ds les clozes on ne pouvait pas avoir de score décimal ce problème a été réglé en effet.
Par défaut pour tous les types de questions on a 1 dans le score, si on veut mettre des décimales, il faut le taper à la main.

**Comment by LaurentGruber** [comment]
Tout comme si on veut changer les points, il faut bien un nombre par défaut, et 1 parait le plus logique. Vous voudriez 1,0 ?

**Comment by om64** [comment]
Simplement, en cliquant sur les petites flèches vers le haut et vers le bas, incrémenter par défault de 0,5 point.

**Comment by LaurentGruber** [comment]
ok, je n'avais pas compris
