### ISSUE TITLE
"Table" questions - Positioning of modals and popup messages.

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#2173]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master/7.0/etc.

When editing in a table, the modals don't appear at the right place, at least don't allow to reach the bottom of the items to add more.
Moreover, the popup messages don't disappear.

![tables](https://cloud.githubusercontent.com/assets/14308826/24244232/4c098370-0fbe-11e7-9c49-75f8dd3a585a.png)

**Comment by pitrackster** [comment]
@om64 sorry but I just cant reproduce... Can you tell me the steps you are following to reach this state ?
