### ISSUE TITLE
Question à relier / Question classement impossible de joindre le bas d'une liste au haut de l'autre liste.

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#2177]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Quand l'une voire les deux listes dépasse la hauteur de l'écran, il n'est plus possible de relier ou de glisser les éléments qui sont dans le bas d'une liste vers l'autre.

![capture du 2017-03-23 13-55-45](https://cloud.githubusercontent.com/assets/13197179/24248690/b26cac7a-0fd0-11e7-8ff3-fd6befd202fb.png)

J'ai un 4ème élément à gauche, je ne sais pas le glisser vers le premier élément car il n'est plus visible.

**Comment by Pauooo** [comment]
same then #2171

**Comment by cecile-rockefeller** [comment]
J'ai un problème similaire. MAis je peux faire les liens entre les questions à relier mais il y a un décalage entre les images et les points à relier. Du coup les erreurs sont possibles et les questions peuvent être invalidées par les étudiants:

![image](https://cloud.githubusercontent.com/assets/26797359/25179629/01481290-250b-11e7-8d21-9951b42e8b70.png)

**Comment by Pauooo** [comment]
@cecile-rockefeller Ceci est un problème lié à une connexion trop lente, j'ouvre un nouveau ticket à ce sujet
