### ISSUE TITLE
[ExoBundle] Paper score is not displayed if it has decimal

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#2181]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

![capture du 2017-03-23 17-39-10](https://cloud.githubusercontent.com/assets/15014599/24259850/6608c720-0ff2-11e7-9908-166a601055eb.png)

**Comment by Batier** [comment]
meme si c'est pas décimal le score global ne s'affiche pas
et a quand la note sur 20?
![image](https://cloud.githubusercontent.com/assets/5484259/25039156/8dc0e45c-2102-11e7-9deb-df3e34783578.png)
