### ISSUE TITLE
CEB - Notifications are duplicated.

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#2185]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master/7.0/etc.

In ceb.claroline.com, the notifications are duplicated.

![notifications](https://cloud.githubusercontent.com/assets/14308826/24300019/4c05c1a2-10ab-11e7-920f-ac0d8e8639dd.png)

![notifications_2](https://cloud.githubusercontent.com/assets/14308826/24300069/7d0fab64-10ab-11e7-845b-6fb3d853e047.png)

**Comment by om64** [comment]
@Elorfin Serait-ce dû au changement de template ?

**Comment by Elorfin** [comment]
Non peu de chances.

**Comment by om64** [comment]
This is still the case on 3L.
