### ISSUE TITLE
[ExoBundle] iOS div content editable not working

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#2192]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master/7.0/etc.

On tablet, iOS div content editable not working : not able to enter text
It's the case with safari, chrome and FF focus.

For the moment we can avoid the problem by using the tinyMCE, but in this case it's not possible to create questions using selection in the div : cloze, selection and future insertion.

**Comment by Pauooo** [comment]
the div content editable (simple version : https://plnkr.co/edit/i2ND6w9Cuxp4Abp7C1v7?p=preview) works on safari OS and iOS

**Comment by Elorfin** [comment]
http://stackoverflow.com/questions/21295698/html5-contenteditable-attribute-not-working-properly-on-ios7-mobile-safari
