### ISSUE TITLE
[ExoBundle] Plantage éditeur lors de la supression d'une question après avoir ajouté une copie dans une autre étape.

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#2193]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Je créé une étape
Je crée une question dedans
Je crée une seconde étape
Je mets dans cette étape via l'import de question la question créé dans la 1ère étape
Je supprime la question dans la 1ère étape
Ouverture de modale "êtes-vous sûr ?"
Je valide
La question n'est pas supprimée et l'éditeur se fige

Retour console:
![capture du 2017-03-28 15-18-25](https://cloud.githubusercontent.com/assets/13197179/24407839/58fd5cd4-13cc-11e7-9d5f-9c2ddecc9112.png)

**Comment by ngodfraind** [comment]
Je n'ai pas eu la même erreur dans la console, mais j'ai pu reproduire.
