### ISSUE TITLE
[ExoBundle] Error when trying to delete a quiz with papers

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#2204]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

An error occurs when trying to delete a quiz with papers:

![image](https://cloud.githubusercontent.com/assets/3415139/24496509/b7cfbe92-1538-11e7-83c3-7a40bf30a482.png)

**Comment by LaurentGruber** [comment]
Voir : https://github.com/claroline/Distribution/issues/1351
