### ISSUE TITLE
Fichiers invisibles dans le Resource picker

### ISSUE THREAD

**Issue by bonavitacola** [claroline/Distribution#2211]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 9.1.0

dans la configuration d'un widget de type "resource list",  en mode répertoire, les ressources fichiers ne sont pas visibles. Pour les voir, il faut les taguer et passer en mode tag.

**Comment by cecile-rockefeller** [comment]
J'ai constaté la même chose, mais cela se manifeste lorsque les ressources sont à la racine du dossier ressources de l'espace d'activités.
En créant un répertoire et en y déplaçant les ressources, elles apparaissent bien depuis le resource piker.
Cela reste néanmoins un bug, car le comportement n'est pas normal.

**Comment by ngodfraind** [comment]
Je pense que c'est surtout que la racine ne peut pas être sélectionnée.
