### ISSUE TITLE
Pour etre amis avec une autre plateforme

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2219]
| Q             | A
| ------------- | ---
| Bug report?   |no
| Version?      | master/7.0/etc.
qu'est ce que je dois mettre dans les champs?

![image](https://cloud.githubusercontent.com/assets/5484259/24660705/8383de86-1950-11e7-9976-d9837ae39619.png)

**Comment by LaurentGruber** [comment]
Il y a un / en trop à la fin de l'url. Il faudrait vérifier que si url termine par un / il faut le supprimer
