### ISSUE TITLE
Notation érronée 

### ISSUE THREAD

**Issue by david42** [claroline/Distribution#2228]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 8.0.2

Problème de notation seulement en vue "étudiant" lorsque l'option de la disponibilité de la correction est "Jamais". L'étudiant voit une note érronée, par exemple 66/20, le gestionnaire quant à lui voit une note correcte.

**Comment by LaurentGruber** [comment]
Corrected on v9
