### ISSUE TITLE
[Orgas] Problème d'accent lors d'un import csv d'utilisateurs

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#2231]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master/7.0/etc.

Si le nom de l'orga comprend des accents, il y a un problème lors de l'import CSV des utilisateurs directement dans l'orga. L'import ne gère pas les accents.

**Comment by ptsavdar** [comment]
@Gatomlo Normalement cet issue doit être reglé avec ma PR #2281 . Est-ce que tu pourrais verifier?
