### ISSUE TITLE
barres de scroll qui ne disparaissent pas

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2234]
| Q             | A
| ------------- | ---
| Bug report?   | non bloquant pb ergonomie
| Version?      | 17-9.

Comment enlever les barres de sroll horizontale et verticale
sur la home et dans les espace d'activité

![image](https://cloud.githubusercontent.com/assets/5484259/24747842/f7aa2b8a-1abd-11e7-9f58-59dcf7273387.png)

**Comment by ptsavdar** [comment]
Je re-ouvre l'issue parce qu'il y a toujours des widgets qui s'affichent pas bien. Voici un exemple: 
![image](https://cloud.githubusercontent.com/assets/3414935/25748539/b3bed556-31ab-11e7-8757-d4d508609e3c.png)

C'est lié au display en mode 'flex'.
