### ISSUE TITLE
Mistake in expected answers in Cloze questions.

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#2237]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

When answering a cloze question, there's a discrepancy between the right solutions and the expected answers.

In the first figure, the answers are correct and the score is 2 out of 2, which is right.

The second picture marks the second answer as false, gives no point for that answer but weirdly gives the same total score.

![db6202bd-13c5-44d0-9b66-4d7a687dee88](https://cloud.githubusercontent.com/assets/14308826/24760784/ec7deaae-1ae9-11e7-92a0-c66585ebccb7.png)

![cloze_error](https://cloud.githubusercontent.com/assets/14308826/24760774/e9c7c208-1ae9-11e7-94a5-8c6f59710b50.png)

**Comment by om64** [comment]
17.06 seems a bit late because of the CEB.

**Comment by ngodfraind** [comment]
Je n'ai pas pu reproduire en local (même avec des valeurs entre 0 et 1). Je me demande si ce n'est pas déjà corrigé sur le master.
