### ISSUE TITLE
[ExoBundle] Copier/Coller un questionnaire dans le gestionnaire de ressources

### ISSUE THREAD

**Issue by mikanau** [claroline/Distribution#2241]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 9.1.0

Bonjour,

L'utilisateur a créé un premier questionnaire servant de modèle et l'a dupliqué plusieurs fois par copier/coller.
La modification d'une copie d'un de ces questionnaires a pour effet de se reporter sur tous les questionnaires dupliqués.

Est-il possible de changer ce comportement pour ne pas devoir créer un nouveau questionnaire à chaque fois mais utiliser un modèle ?

Merci pour votre retour.

**Comment by Pauooo** [comment]
reproduit sur la master.
