### ISSUE TITLE
la ressource à ouvrir n'est pas conservée

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2247]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | dev-master

dans le paramétrage d'un espace d'activité Paramètres Affichage
quand on va re éditer un paramètre on perd la ressource à ouvrir déjà enregistrée

![image](https://cloud.githubusercontent.com/assets/5484259/24992837/c6951620-2023-11e7-9a17-7d79095f4e9a.png)

**Comment by ngodfraind** [comment]
Reproduit.

**Comment by Batier** [comment]
MERCI
