### ISSUE TITLE
Impossible to add an object to the questions

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#2251]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

On the master, it's impossible to add any kind of object to the questions.

![object](https://cloud.githubusercontent.com/assets/14308826/25128250/5b9d71d6-2439-11e7-8923-8b094b1f0628.png)

**Comment by LaurentGruber** [comment]
ça doit être un problème de droit sur le master, je vais regarder, je ne pense pas que ça soit un bug de la plateforme

**Comment by kitan1982** [comment]
Ça ne m'étonnerais pas que ça vienne du problème de migrations corrigé par cette PR #2249.
Je pense que la DB du master n'est plus correcte.

**Comment by LaurentGruber** [comment]
resolved by https://github.com/claroline/Distribution/pull/2249
