### ISSUE TITLE
MAJ 8.0.4 vers 9.1.0 fatal: Not a git repository

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#2252]
| Q             | A
| ------------- | ---
| Bug report?   | yes ?
| Version?      | 8.0.4

Bonjour,
Je retente la MAJ de 8.0.4 vers 9.1.0.
La fois précédente j'y étais parvenu mais avec un problème d'accès à la banque de question.
Cette fois-ci je n'arrive pas à démarrer la procédure car git ne pointe pas sur la bonne branche ? Que dois-je faire ?
Bien à vous.

Procédure : 
git checkout .
git fetch
git checkout 9.x
git pull origin 9.x
(composer update)
composer update --prefer-source
npm install && npm run bower && npm run themes && npm run webpack

**Comment by Garakotxea** [comment]
Merci Laurent pour le passage en question mais c'est bon. Je viens de retenter et c'est passé mais je ne sais pas pourquoi cela avait échoué. Je démarre la tentative de MAJ.

**Comment by ngodfraind** [comment]
Probablement pas au bon niveau dans l'arborescence en fait. Il faut être à la racine pour que ça fonctionne.

**Comment by Garakotxea** [comment]
Je travaille depuis /var/www/Claroline/ pour les MAJ mais peut-être avais-je oublié de m'y placer tout à l'heure ? C'est possible. Désolé pour le dérangement si c'est le cas.

**Comment by Garakotxea** [comment]
A nouveau le problème avec **composer.lock**
_[ErrorException] file_put_contents(./composer.lock): failed to open stream: Permission denied_

Lors de la dernière tentative de MAJ vers 9.1.0 "réussie", lassé des problèmes d'accès, j'avais radicalement supprimé tous les composer.lock avec **find . -name composer.lock | xargs rm**. Puis-je procéder ainsi ?

**Comment by Garakotxea** [comment]
A nouveau le problème avec **composer.lock**
_[ErrorException] file_put_contents(./composer.lock): failed to open stream: Permission denied_

Lors de la dernière tentative de MAJ vers 9.1.0 "réussie", lassé des problèmes d'accès, j'avais radicalement supprimé tous les composer.lock avec **find . -name composer.lock | xargs rm**. Puis-je procéder ainsi ?

**Comment by ngodfraind** [comment]
composer n'a pas le droit d'écrire dans le dossier racine. Il suffit de modifier le permissions (chmod 777 /var/www/Claroline)

**Comment by Garakotxea** [comment]
J'avais débuté ainsi avant d'effacer me semble-t-il. 
J'essaierai à nouveau jeudi. Merci. 
Envoyé depuis mon mobile

-----Original Message-----
