### ISSUE TITLE
Widget BLOG - lien des articles  qui bug

### ISSUE THREAD

**Issue by cecile-rockefeller** [claroline/Distribution#2256]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Bonjour, 
Lorsque je crée un widget blog, et que je clique sur les articles du blogs qui sont remontés via le widget cela m'envoie sur la page d'accueil de mon espace d'activité et non sur mon blog, or cela devrait pointer sur l'outil blog ou l'article sélectionné.

**Comment by ptsavdar** [comment]
@cecile-rockefeller Fixed by #1973
