### ISSUE TITLE
Widget texte -> lien qui demande de se reconnecter

### ISSUE THREAD

**Issue by cecile-rockefeller** [claroline/Distribution#2257]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Bonjour, 
j'ai créé un widget texte ( ou page) dans lequel un lien  pointe sur un dossier dans mes ressources. Celui-ci contient plusieurs sous-dossiers et le but est de faire pointer l'étudiant à l'intérieur du dossier pour avoir accès directement aux sous-dossiers.
Autrement dit, le lien pointe sur un dossier nommé par exemple Année1 qui contient des sous dossiers UE1, UE2...etc. 

Lorsque je clique pour la première fois  sur ce lien après mêtre connectée à mon compte et mon espace d’activités sur CLaco je dois me reconnecter.
Et une fois reconnectée, je pointe directement sur les ressources mais pas dans le dossier soit à la racines des ressources. Enfin lorsque je clique une seconde fois sur le lien, le chemin est respecté, il point au bon endroit et je n'ai pas à me reconnecter.
J'ai vérifié le l'url du lien ainsi que les droits de publication/et les propriétés pour les dossiers/sous-dossiers, tout est ok.

**Comment by LaurentGruber** [comment]
@ptsavdar c'est lié à la config du routing après connection non ? On devrait peut être modifier le comportement pour que si on vient depuis une url précise de la plateforme on soit rediriger là plus tôt que vers le paramètre choisi ? Qu'en penses tu ?

**Comment by ptsavdar** [comment]
@cecile-rockefeller @LaurentGruber En fait le problem c'est qu'on a plusieurs nom de domaines. Du coup, les cookies de session se portent sur differents domains c'est pour ca qu'on a ce probleme. @cecile-rockefeller au lieu d'utiliser le mooc.univ-lyon1.fr il faut utiliser le claco.univ-lyon1.fr.

**Comment by cecile-rockefeller** [comment]
@ptsavdar<https://github.com/ptsavdar> J’ai refait des tests. En fait je me loggais bien avec claco.univ-lyon1. Mais le lien que j’avais renseigné pointait sur une ressource avec l’url Mooc.univ-lyon1.fr d’où la demande de reconnexion.
Je le note, et je transmets aux collègues qui risquent d’avoir le même cas.
