### ISSUE TITLE
[ExoBundle] Association question : anchors not placed properly

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#2258]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

@cecile-rockefeller in #2177
*J'ai un problème similaire. Mais je peux faire les liens entre les questions à relier cependant il y a un décalage entre les images et les points à relier. Du coup les erreurs sont possibles et les questions peuvent être invalidées par les étudiants:*

![image](https://cloud.githubusercontent.com/assets/26797359/25179629/01481290-250b-11e7-8d21-9951b42e8b70.png)

It's seems like js-plumb is drawing anchors when component is not fully rendered.

**Comment by cecile-rockefeller** [comment]
Merci  :)
