### ISSUE TITLE
Attribution de badge qui ne fonctionne pas

### ISSUE THREAD

**Issue by cecile-rockefeller** [claroline/Distribution#2259]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

J'ai défini plusieurs règle pour attribuer un badge de participation. Si l'étudiant consulte les ressources définies dans les règles du badge, alors il obtient son badge de participation.
Il y a 6 documents à consulter soit à ouvrir. Je vous joins une capture de ma page de règles. cf. Capture 1
J'ai testé avec mon compte aucune attribution ne se fait.

Idem sur l’attribution d'un badge pour la réussite à des questionnaires. Si l'étudiant obtient un score =>à 75% de réponses juste à ses questionnaires alors il obtient un badge de réussite. Il y a 4 questionnaire concernés. cf. Capture2
 

Capture 1
![image](https://cloud.githubusercontent.com/assets/26797359/25184758/a82e6f18-251b-11e7-817d-4696f86aa142.png)

Capture2
![image](https://cloud.githubusercontent.com/assets/26797359/25184949/2cea49de-251c-11e7-963b-f586aea265ec.png)

**Comment by ptsavdar** [comment]
@cecile-rockefeller Il faut decocher la case "L'utilisateur est la cible de l'action"

**Comment by cecile-rockefeller** [comment]
J'ai testé en le cochant et en le décochant...Je viens de tout redécocher à l'instant et aucun badge n'est attribué...Pourtant j'ai bien respecté les règles.
Pour info:
Mes espaces d'activités/MOOCBIOMATERIAUX (MOOCBIOMAT)/ Gestion des badges de l'espace de travail

**Comment by cecile-rockefeller** [comment]
@ptsavdar<https://github.com/ptsavdar> Je ne sais pas si tu as fait une modif  (à la décoche de l’utilisateur/cible ça ne fonctionnait pas), mais là ça marche ! les badges sont ok. ☺
