### ISSUE TITLE
inscription d'utilisateurs à un espace d'activités via un fichier csv => import

### ISSUE THREAD

**Issue by cecile-rockefeller** [claroline/Distribution#2260]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Bonjour,
je dois inscrire des utilisateurs (liste de 250 utilisateurs en moyenne) à des espaces d'activités.
Les champs requis  dans le csv pour cette inscription sont "identifiant" et "rôle". 
Or il est impossible de connaitre les identifiants des utilisateurs qui se sont créés des comptes en amont, et il n'est pas possible (gérable) pour les gestionnaires d'espace (soit les enseignants) d'aller rechercher chaque compte pour en connaitre l'identifiant.

Est-il possible d'avoir des champs type : <Nom> <Prénom> et <Mail> qui sont des données fixes ? (parce que titi69 ou tatadu42...Pas top comme requête :) )

C'est indispensable pour la gestion de nos utilisateurs

Merci

**Comment by LaurentGruber** [comment]
Les champs prénom et nom ne sont pas unique, donc ça n'est pas possible de les choisirs comme référence pour inscrire des utilisateurs. Seul les champs USERNAME, MAIL et CODE ADMINISTRATIF sont unique et peuvent servir de référence pour l'import par CSV.
Par contre via l'outil d'ajout des utilisateurs, on peut voir les nom et prénom et choisir les bons utilisateurs...

**Comment by cecile-rockefeller** [comment]
Bonjour Laurent,
Le nom et le prénom d’une personne sont des données strictes…Le USER name ne l’est pas , chacun peut choisir un identifiant de son choix. Cela est problématique pour les comptes qui sont déjà existants et qui vont être migrés, nous n’avons pas la possibilité de nous baser sur leur identifiant.
D’autre part, nous ne pouvons pas aller chercher manuellement chaque utilisateur via le moteur de recherche, c’est une gestion impossible à l’échelle de l’université.

Merci pour ton retour,

Cécile


[Description : cid:image002.jpg@01CD5384.DB207BA0]

Cécile CHENAVAS
Chef de projets pédagogiques innovants - Santé
Service  iCAP
Médiathèque Paul ZECH
Université Claude Bernard LYON 1
8 Avenue Rockefeller
69372 LYON CEDEX 08
Tel:  04 78 78 56 82
Mob: 06 72 20 96 38
http://icap.univ-lyon1.fr<http://icap.univ-lyon1.fr/>
http://spiralconnect.univ-lyon1.fr<http://spiralconnect.univ-lyon1.fr/>
P Merci de penser à l'environnement avant d'imprimer ce courriel



De : Gruber Laurent [mailto:notifications@github.com]
Envoyé : jeudi 20 avril 2017 09:39
À : claroline/Distribution <Distribution@noreply.github.com>
Cc : CHENAVAS MORIN CECILE <cecile.chenavas@univ-lyon1.fr>; Author <author@noreply.github.com>
Objet : Re: [claroline/Distribution] inscription d'utilisateurs à un espace d'activités via un fichier csv => import (#2260)


Les champs prénom et nom ne sont pas unique, donc ça n'est pas possible de les choisirs comme référence pour inscrire des utilisateurs. Seul les champs USERNAME, MAIL et CODE ADMINISTRATIF sont unique et peuvent servir de référence pour l'import par CSV.
Par contre via l'outil d'ajout des utilisateurs, on peut voir les nom et prénom et choisir les bons utilisateurs...

**Comment by clarophil** [comment]
Il faut se méfier du nom prénom, outre le problème des doublons, il y aussi des différences parfois sur les majuscules, les accents, ceux qui n'ont pas de prénom,...
Est-ce que vous ne pouvez pas vous baser sur l'email qui devrait être unique et connu ?

**Comment by cecile-rockefeller** [comment]
Nous devons être en mesure de vérifier l’état civil de nos utilisateurs. Un compte qui se déclare gestionnaire doit être vérifiable, on ne peut pas attribuer des droits uniquement sur la bonne foi des gens.
Et les personnes qui n’ont pas de prénom…Je ne connais pas ☺
Si on peut avoir des champs modifiables pour l’import basés sur Nom/prenom/mail mais que l’identifiant n’est pas requis obligatoirement cela me va.
Ma seule préoccupation est de devoir remplir un champ obligatoire à savoir l’identifiant, information que je ne peux pas obtenir.
Est-ce possible ?


[Description : cid:image002.jpg@01CD5384.DB207BA0]

Cécile CHENAVAS
Chef de projets pédagogiques innovants - Santé
Service  iCAP
Médiathèque Paul ZECH
Université Claude Bernard LYON 1
8 Avenue Rockefeller
69372 LYON CEDEX 08
Tel:  04 78 78 56 82
Mob: 06 72 20 96 38
http://icap.univ-lyon1.fr<http://icap.univ-lyon1.fr/>
http://spiralconnect.univ-lyon1.fr<http://spiralconnect.univ-lyon1.fr/>
P Merci de penser à l'environnement avant d'imprimer ce courriel



De : clarophil [mailto:notifications@github.com]
Envoyé : jeudi 20 avril 2017 13:24
À : claroline/Distribution <Distribution@noreply.github.com>
Cc : CHENAVAS MORIN CECILE <cecile.chenavas@univ-lyon1.fr>; Author <author@noreply.github.com>
Objet : Re: [claroline/Distribution] inscription d'utilisateurs à un espace d'activités via un fichier csv => import (#2260)


Il faut se méfier du nom prénom, outre le problème des doublons, il y aussi des différences parfois sur les majuscules, les accents, ceux qui n'ont pas de prénom,...
Est-ce que vous ne pouvez pas vous baser sur l'email qui devrait être unique et connu ?
