### ISSUE TITLE
[ExoBundle] Inconsistent score on certain question types (at least on Choice question)

### ISSUE THREAD

**Issue by pitrackster** [claroline/Distribution#2265]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Some question types can give an inconsistant score.
For exemple 
- create a choice question
- set unique choice to true
- keep the two default choices as they are
- add a third choice with a positive score
- play the exercise and answer the question (obviously only one choice can be selected)
- in the paper page you'll have 1 of 2 points... which is inconsistent

**Comment by ngodfraind** [comment]
Reproduit
