### ISSUE TITLE
[Gestion des espaces activités] ne renvoie aucun résultat

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#2268]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Depuis la mise à jour vers la dernière version de Claroline en date,
la liste des espaces activités ne s'affiche pas lors de la consultation de ceux-ci via la page "gestion des espaces activités" du menu Administration. 
Le filtre "Les espaces non personnels seulement" semble poser problème.
Les autres fonctionnent.

Est-ce un problème de requête ?

Merci

**Comment by LaurentGruber** [comment]
La dernière version, vous voulez dire la 9.2 ou le master (si oui de quel jour ?) ou ?

**Comment by l-matt** [comment]
Bonjour, merci pour votre réponse.
Nous sommes passé d'une version 8 à 9 en resynchronisant sur la branche master en date du 18/04
Je vois que le composer.lock (dernière maj) est daté du 22/04, y'a t'il une autre méthode pour connaître précieusement le commit ?

**Comment by ngodfraind** [comment]
Vous avez lancer les scritps de mise à jour de la db ? Il y a eu des changements entre la 8 et la 9.

**Comment by l-matt** [comment]
De quelle procédure parlez-vous? Vous parlez de test_update ? il semblerait que la base soit à jour.
A l’exécution de cette dernière commande il me renvoie une erreur Duplicate entry, j'en conclu donc que la base est à jour.
J'ai le même problème sur une installation sur serveur local. 
Le problème est présent uniquement quand on passe par le menu admin -> gestion des espaces d'activités.
Le filtre "les espaces non personnels seulement" ne renvoie rien.

Merci

**Comment by l-matt** [comment]
J'ai crée un nouvel espace d'activité il apparaît bien dans la liste, pourtant je ne vois aucune différence avec les autres espaces d'activités au niveau de la base de donnée dans les tables claro_workspaces et claro_workspace_option. Est-ce qu'une autre table contient des paramètres additionnels aux espaces d'activités? Merci

**Comment by LaurentGruber** [comment]
La gestion des espaces d'activité à été refaite dans la version 10, cela devrait régler les soucis.
