### ISSUE TITLE
[CoreBundle]  Affichage en gras des nouvelles ressources

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#2274]
| Q             | A
| ------------- | ---
| Bug report?   |  yes
| Version?      |  9.1

Les nouvelles ressources s'affichent en gras dans le gestionnaire de ressources.
En les consultant, le gras disparaît.

Mais certaines ressources ne peuvent être consultées directement dans la plateforme comme les fichiers pptx ou xlsx,...  donc elles restent pour l'éternité en gras ce qui perturbe les étudiants car ils ne peuvent plus se fier sur la notion de gras pour savoir ce qui est nouveau ou pas.

Il faut donc enlever le gras à tout fichier (plus globalement ressource) téléchargé.

**Comment by kitan1982** [comment]
Testé avec un fichier zip et je n'ai pas eu de problèmes.
Le fichier n'est plus en gras après un rafraîchissement de la page.

**Comment by clarophil** [comment]
Effectivement ça marche, merci

**Comment by clarophil** [comment]
Si on met 2 fichiers un pdf et un ppt par exemple, le ppt perd le gras mais pas le pdf !
