### ISSUE TITLE
Add VideoJsBundle to distribution

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#228]
https://github.com/claroline/VideoJsBundle

Adapt to use bower to add videoJS (http://videojs.com/) | bower install video.js

**Comment by ngodfraind** [comment]
It's already done.

https://github.com/claroline/Distribution/blob/master/bower.json#L63
https://github.com/claroline/Distribution/blob/master/plugin/video-player/Resources/views/videojsplayer.js.twig#L1
