### ISSUE TITLE
[ExoBundle] Global score not displayed

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#2284]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

When I set the score of a question to "global", this score is not displayed in the paper : 
![capture du 2017-04-25 12-23-37](https://cloud.githubusercontent.com/assets/15014599/25380882/18eae070-29b2-11e7-8a9d-7b6757514f8f.png)
![capture du 2017-04-25 12-23-52](https://cloud.githubusercontent.com/assets/15014599/25380890/1e2a924c-29b2-11e7-9b22-119f42bc66ee.png)

**Comment by ngodfraind** [comment]
J'ai pas réussi à reproduire. Tu peux me guider ?

**Comment by ngodfraind** [comment]
Je n'arrive tjrs pas à reproduire. En revanche, je peux mettre un score global à 0...

**Comment by ngodfraind** [comment]
Reproduit sur les questions de type "choice" lorsque je teste l'exercice.

**Comment by LaurentGruber** [comment]
resolved in https://github.com/claroline/Distribution/pull/2433
