### ISSUE TITLE
Hovers don't disappear

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#2293]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Hovers don't disappear after clicking on the new buttons in the exercises.

![hover](https://cloud.githubusercontent.com/assets/14308826/25422190/4adde2e0-2a60-11e7-849e-3afff776fad2.png)

**Comment by om64** [comment]
The problem also appears when editing a path on CEB platform.

![hovers2](https://cloud.githubusercontent.com/assets/14308826/25479492/51c0a7ce-2b45-11e7-9dd3-11ffb7ea4630.png)

**Comment by Elorfin** [comment]
Fixed in last versions.
