### ISSUE TITLE
Too many decimals in scores

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#2313]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

When defining a **global score for a path**, which is now possible (many thanks for this!), too many decimals appear. They should be limited to two.

![too_many_decimals](https://cloud.githubusercontent.com/assets/14308826/25478707/8049fc24-2b42-11e7-9aaa-b673b07eea26.png)

**Comment by LaurentGruber** [comment]
corrigé ici : https://github.com/claroline/Distribution/pull/2278
