### ISSUE TITLE
[BUG TICKET/REPORT] Impossible de générer un ticket

### ISSUE THREAD

**Issue by bonavitacola** [claroline/Distribution#2336]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 9.1.0

cliquer sur "créer un ticket pour cette erreur" lève une erreur
"une erreur s'est produite. Veuillez réessayer plus tard ou vérifier votre connexion Internet"

![screen shot 05-03-17 at 11 25 am](https://cloud.githubusercontent.com/assets/15154013/25654941/60c028b4-2ff3-11e7-8412-a27594a16466.PNG)

**Comment by LaurentGruber** [comment]
Il y avait quoi dans les logs ?

**Comment by bonavitacola** [comment]
Salut,

 

Voilà : 

2017/05/04 11:03:35 [error] 13655#0: *1153956 FastCGI sent in stderr: "Unable to open primary script: /data/www/clarolineconnect/claroline/web/app.php//formalibresupportbu

ndle/user/2/ticket/from/issue/Doctrine\ORM\Query\QueryException/message/Too many parameters: the query defines 0 parameters and you bound 1/file/data/www/clarolineconnect/

claroline/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php (No such file or directory)" while reading response header from upstream, client: XXX.XXX.XXX.XXX,

server: claco.univ-lyon1.fr, request: "GET /formalibresupportbundle/user/2/ticket/from/issue/Doctrine%5CORM%5CQuery%5CQueryException/message/Too%20many%20parameters:%20the

%20query%20defines%200%20parameters%20and%20you%20bound%201/file//data/www/clarolineconnect/claroline/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php/end_fil

e/line/103/url/http://claco.univ-lyon1.fr/resource/rename/58014/end_url/referer/https://claco.univ-lyon1.fr/workspaces/12666/open/tool/resource_manager%3F%26/end_referer/c

reate/form HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "claco.univ-lyon1.fr", referrer: "https://claco.univ-lyon1.fr/workspaces/12666/open/tool/

resource_manager?&"

De : Gruber Laurent [mailto:notifications@github.com] 
Envoyé : jeudi 4 mai 2017 08:24
À : claroline/Distribution <Distribution@noreply.github.com>
Cc : BONAVITACOLA GILLES <gilles.bonavitacola@univ-lyon1.fr>; Author <author@noreply.github.com>
Objet : Re: [claroline/Distribution] [BUG TICKET/REPORT] Impossible de générer un ticket (#2336)

 

Il y avait quoi dans les logs ?

**Comment by LaurentGruber** [comment]
Le système a été revu sur le master donc ça ne devrait plus arriver sur la 10
