### ISSUE TITLE
[ExoBundle] Bug in tables questions

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#2338]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master.

In http://ceb.claroline.com/resource/open/172, nothing happens when clicking on "Terminer" at the end of the exercise.

The console mentions this:

![capture du 2017-05-03 11-48-31](https://cloud.githubusercontent.com/assets/14308826/25656178/100b91b0-2ff8-11e7-92a0-b8f54569aeb3.png)

**Comment by Gatomlo** [comment]
Up :-)

**Comment by ngodfraind** [comment]
Reproduit.
