### ISSUE TITLE
Harmonisation interface utilisateur Texte

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#234]
Voir [http://www.crea-tice.org/mediawiki/index.php?title=Texte](http://www.crea-tice.org/mediawiki/index.php?title=Texte)

**Comment by ngodfraind** [comment]
@clarophil 
@LaurentGruber 

J'ai commencé à regarder mais certains points sont très flous.

En ce qui concerne le texte (mais ça va se reproduire ailleurs aussi), on propose une série de boutons.
Dans l'étal actuel du projet, la liste d'action ne peut pas être proposée sans changement. Concrètement, pour les ressources, voici ce qu'il en sort

suivre
-------
"OK" pour le texte mais ce n'est pas implémenté partout ! Faut-il l'implémenter ou il ne l'est pas encore ou le supprimer le suivit n'est pas possible ? Et si suivre certaines ressources n'a aucun sens (comme un pdf), on fait quoi ?

tagger
------
OK

favori
-------
OK

chercher
-------- 
PAS OK. Ça n'a aucun sens dans la ressource texte et ça n'en aura aucun dans un paquet de ressource tout court. Il y a le forum (c'est implémenté). Certaines ressources comme wiki/lesson ça peut être justifié (mais pas implémenté je pense). C'est plus lourd que refaire la peinture pour le coup.

annoter
----------
PAS OK. C'est simple, rien n'est implémenté nulle part pour ça. Je veux bien qu'on le fasse mais pour fin mai/début juin ça risque de pas être possible.

j'aime
--------
OK

commenter
----------------
PAS OK. Comme annoter, rien n'a été dev

"..."
-----
Intérêt ? On a déjà mit toute la liste. Ou alors on ne le met que lorsqu'on réduit la taille de l'écran avec un système pour faire apparaitre le reste. Dans une des captures d'écrans ce n'est pas la dernière icône par contre donc je ne suis pas sûr d'avoir compris ce que ce bouton doit faire.


La route dentée (fa fa-cog)
-------------------------------------
Encore une fois, dans l'exemple il y a un paquet de boutons incohérents:
- voir en tant que n'a aucun sens pour le texte ni pour un paquet de ressource. Ça fait doublon avec la barre à gauches des WS.
- activitié: ça veut dire quoi ?
- onglet(s): ça veut dire quoi ?

La conséquence de tout ça, c'est que pour texte, le seul truc utile c'est "éditer", ce bouton est d'ailleurs présent dans l'interface. Donc c'est inutile de le mettre en double avec un clique en plus. Ces questions vont se reposer pour d'autres ressources.

**Comment by clarophil** [comment]
De : Godfraind [mailto:notifications@github.com]
Envoyé : lundi 2 mai 2016 14:57
À : claroline/Distribution <Distribution@noreply.github.com>
Cc : Philippe DEKIMPE <philippe.dekimpe@ecam.be>; Mention <mention@noreply.github.com>
Objet : Re: [claroline/Distribution] Harmonisation interface utilisateur Texte (#234)


@clarophil<https://github.com/clarophil>
@LaurentGruber<https://github.com/LaurentGruber>

J'ai commencé à regarder mais certains points sont très flous.

En ce qui concerne le texte (mais ça va se reproduire ailleurs aussi), on propose une série de boutons.
Dans l'étal actuel du projet, la liste d'action ne peut pas être proposée sans changement. Concrètement, pour les ressources, voici ce qu'il en sort

suivre

"OK" pour le texte mais ce n'est pas implémenté partout ! Faut-il l'implémenter ou il ne l'est pas encore ou le supprimer le suivit n'est pas possible ? Et si suivre certaines ressources n'a aucun sens (comme un pdf), on fait quoi ?

Pour les fichiers, on pourrait quand même notifier une nouvelle version du fichier avec « Mettre à jour le fichier »

Je pense qu’il y a un intérêt partout à suivre une ressource, on travaille actuellement sur les notifications.

Je pense qu’on devrait aussi notifier la publication pour toutes les ressources.

tagger

OK

favori

OK

chercher

PAS OK. Ça n'a aucun sens dans la ressource texte et ça n'en aura aucun dans un paquet de ressource tout court. Il y a le forum (c'est implémenté). Certaines ressources comme wiki/lesson ça peut être justifié (mais pas implémenté je pense). C'est plus lourd que refaire la peinture pour le coup.

Et bien donc on ne le met que pour le forum puis on peut voir si ça vaut la peine de le developer la fonction pour d’autres ressources.

annoter

PAS OK. C'est simple, rien n'est implémenté nulle part pour ça. Je veux bien qu'on le fasse mais pour fin mai/début juin ça risque de pas être possible.

Peut être fait une issue spécifique pour une release ultérieure

j'aime

OK

commenter

PAS OK. Comme annoter, rien n'a été dev

"..."

Intérêt ? On a déjà mit toute la liste. Ou alors on ne le met que lorsqu'on réduit la taille de l'écran avec un système pour faire apparaitre le reste. Dans une des captures d'écrans ce n'est pas la dernière icône par contre donc je ne suis pas sûr d'avoir compris ce que ce bouton doit faire.

Ça mérite une réflexion, je propose de reporter à une release ultérieure.

La route dentée (fa fa-cog)

Encore une fois, dans l'exemple il y a un paquet de boutons incohérents:

  *   voir en tant que n'a aucun sens pour le texte ni pour un paquet de ressource. Ça fait doublon avec la barre à gauches des WS.
  *   activitié: ça veut dire quoi ?
  *   onglet(s): ça veut dire quoi ?


Là il faudrait un éclairage de Jean-Jacques

La conséquence de tout ça, c'est que pour texte, le seul truc utile c'est "éditer", ce bouton est d'ailleurs présent dans l'interface. Donc c'est inutile de le mettre en double avec un clique en plus. Ces questions vont se reposer pour d'autres ressources.

Non il y  a aussi suivre, tagger et favori

**Comment by ngodfraind** [comment]
J'ai vu pour les commentaires que j'ai dit des bétises. Ça a été écrit par Lyon. Mais ça ne change rien à la roue dentée.

Je peux laisser tomber les "...".

Je vais faire une PR cette après-midi pour la ressource "texte". Si ça ne consiste qu'a réécrire le header, ces changements pourront être très rapides.

**Comment by clarophil** [comment]
Bonjour,

Merci à Philippe de m'avoir transféré ce mail (je ne suis pas je pense 
dans la mailing list)

Je suis à votre disposition pour répondre à toutes demandes 
d'explications. Mon adresse mail est celui qui figure dans ce mail

Les indications sur le Wiki, correspondent, sauf décision contraire (car 
trop compliqué, pas utle...) à cette release (V7). A ce stade et dans 
l'esprit de ce travail sur l'interface, l'idée est de placer les options 
du menu déroulant actuellement associées à une ressource, directement 
visible lors de l'ouverture de la ressource pour 1) les rendre plus 
visible et 2) pour que ces options bénéficient également à ceux qui 
n'ont pas ouvert la ressource depuis l'espace des ressources mais depuis 
les parcours par exemple ou depuis un lien hypertexte depuis une autre 
ressource

Nous partons donc de l'esprit qu'une option présente dans le menu est 
réellement opérationnelle et peut être placée également dans la nouvelle 
interface de la ressource. Il s'agit de :

Tagger (info-bulle = Tagger)
Favoris (info-bulle = Placer dans les favoris ou si déjà placé dans les 
favoris (Enlever des favoris)
Annoter (info-bulle = Annoter (privé)
J'aime (info-bulle = J'aime)
Commenter (info-bulle = Déposer un commentaire (public)
... (info-bulle = Voir plus)

Note : "Commenter" est le nouveau terme choisi et correspond à "Laisser 
un commentaire" déjà implémenté

"Suivre cette ressource" et "Chercher" ont été ajouté à ces boutons : 
voir où c'est utile, ce point n'ayant pas été abordé encore en groupe 
ergonomie. Philippe donne déjà quelques indications ci-dessous

Suivre cette ressource :

> Pour les fichiers, on pourrait quand même notifier une nouvelle 
> version du fichier avec « Mettre à jour le fichier »
>
> Je pense qu’il y a un intérêt partout à suivre une ressource, on 
> travaille actuellement sur les notifications.
>
> Je pense qu’on devrait aussi notifier la publication pour toutes les 
> ressources.

Chercher :

> Et bien donc on ne le met que pour le forum puis on peut voir si ça 
> vaut la peine de le developer la fonction pour d’autres ressources.
On peut le faire plus tard si pas implémenté, mais il me semble que 
chercher du texte dans du texte (blog, wiki, texte, forum, exercice, 
support de cours etc) a un certain sens, oui

"..."

L'icône "..." permet d'alléger l'interface en n'affichant pas certains 
de ces 7 icônes directement à l'écran. Il faut donc faire un choix de ce 
qui est considéré comme important et moins essentiel. dans ce cas 
l'activation de ... permet d'obtenir un menu déroulant avec les options 
qui n'ont pas été affichée directement dans l'interface

>
>     La route dentée (fa fa-cog)
>
> Encore une fois, dans l'exemple il y a un paquet de boutons incohérents:
>
>   * voir en tant que n'a aucun sens pour le texte ni pour un paquet de
>     ressource. Ça fait doublon avec la barre à gauches des WS.
>   * activitié: ça veut dire quoi ?
>   * onglet(s): ça veut dire quoi ?
>

A) Activité et Onglet(s) du menu des actions

On avait pris la décision en début d'année de supprimer la ressource 
activité en tant que telle

De ce fait, ce qu'on pouvait faire avec l'activité doit être possible 
directement dans chacune des ressources

Actuellement, si on place un forum par exemple dans une activité ou si 
l'on crée une étape d'un parcours en y associant une ressources, que 
peut-on faire ?

 1. on peut ajouter un onglet avec une ressource complémentaire
 2. on peut ajouter une consigne
 3. on peut évaluer l'activité

Le point 1 correspond à l'option "Onglet" du menu des actions de la 
nouvelle interface

Les points 2 et 3 à l'option "Activité"

Voir le document attaché daté du 8 janvier pour plus de détails

B) Voir en tant que...

Le demande est effectivement de contextualiser cette fonctionnalité et 
de la placer dans le menu des actions de chacune ressource.

A noter que, actuellement, "Se connecter en tant que" produit une 
"sortie" de la ressource où l'on était pour revenir à la page d'accueil 
de l'espace d'activité, ce qui est gênant si l'on veut seulement et 
rapidement voir ce que donne la ressource côté collaborateur par exemple

Cette proposition de "Voir en tant que" correspond à ce qui existe déjà 
dans le blog (sous le terme "Se connecter en tant que") et fonctionne 
comme on le voudrais, c-à-d, en restant dans la ressource

Bien à vous,

JJ

**Comment by ngodfraind** [comment]
@LaurentGruber 

J'ai commencé à le faire en angular. Bon, je peux le faire de 2 manières:

- "q&d": Je n'ajoute quasi rien au backend. Le serveur renvoie les formulaires. En gros je transpose ce que le ressource manager fait déjà. Ça peut être assez rapide.

- "propre": Je refais les formulaires/modal en angular avec une API en json pour le backend mais il y a quand même beaucoup de choses à faire donc ça prendra pas mal de temps (et vaut mieux que je termine les facettes avant pour me servir du composant de formulaire que j'ai commencé).

C'est juste une question de délai en fait.

**Comment by ngodfraind** [comment]
Aussi, de la manière propre, j'ai aucune idée de comment rajouter des points d'extensions vu que c'est le backend qui gère ça atm et qu'on a pas (encore ?) de solution en angular.
