### ISSUE TITLE
Ajout d'un thème - plantage

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#2343]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

En voulant ajouter un thème
Administration>Paramètres>Apparence>Nouveau thème puis en validant.
je suis tombé sur une page blanche. 
En cliquant sur précédent j'ai pu supprimer le thème à l'aide de la croix mais depuis la page d'accueil n'affiche plus rien. 
En visualisant la source on peut voir "class="claroline-app-container claro-violette"" claro-violette etant le nom du theme...
Nous ne pouvons plus accéder à la plateforme, comment est-il possible de réinitialiser le thème par default?
je ne vois rien dans la base de donnée.
J'ai mis a jour avec composer, lancé npm run themes et npm run webpack, supprimé le cache mais rien n'y fait. HELP

merci

**Comment by Elorfin** [comment]
Bonjour,

La fonction de création de thème depuis l'interface ne fonctionne plus dans la version actuelle.
Pour restaurer le thème par défaut, le plus simple est de modifier le fichier `app/config/platform_options.yml`. Recherchez la clé `theme` et changez la valeur pour `claroline`.

Tout devrait rentrer dans l'ordre.

**Comment by l-matt** [comment]
j'allais le dire... merci beaucoup je viens de trouver la solution

**Comment by Elorfin** [comment]
Parfait. Bonne journée.

**Comment by l-matt** [comment]
Merci pour votre réactivité
Bien cordialement
