### ISSUE TITLE
[Collecticiel]Harmonisation interface utilisateur

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#235]
Voir [http://www.crea-tice.org/mediawiki/index.php?title=Texte](http://www.crea-tice.org/mediawiki/index.php?title=Texte)

**Comment by ericvincenterv** [comment]
@clarophil : what can I do with this issue ?

**Comment by jj-quintin** [comment]
Ce sont les améliorations qui seront progressivement apportées en vue d'harmoniser les interfaces des ressources. 

Je propose d'attendre qu'une première ressource, autre que le collecticiel, ait subi ces changements et se conformer ensuite à cette ressource modèle
