### ISSUE TITLE
[ExoBundle] Final Comment can't be deleted

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#2358]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

In a questionnaire I can add a final comment to a question but if finally I want to delete it (after I saved a first time), there is no delete button. 
![capture du 2017-05-09 09-39-34](https://cloud.githubusercontent.com/assets/15014599/25841968/7d4fe272-34a2-11e7-8a0a-d94a27c31e7c.png)
I can empty the comment but in the player the div is still displayed (even if empty) : 
![capture du 2017-05-09 09-39-56](https://cloud.githubusercontent.com/assets/15014599/25841954/730e7260-34a2-11e7-968a-38e4b90fea6b.png)

**Comment by Elorfin** [comment]
I think it's because it remains an empty HTML tag in the field.
If you need a quick fix, you can try to edit HTML code in TinyMCE to remove all.

**Comment by Pauooo** [comment]
@Elorfin you are right "`<p></p>`" remains. Thank you :-)

**Comment by ngodfraind** [comment]
J'ai pas réussi à reproduire même en modifier moi même le html.
