### ISSUE TITLE
Amélioration du menu d'accès aux Espaces

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#236]
![image](https://cloud.githubusercontent.com/assets/895878/14909540/076ac322-0de5-11e6-8447-cc9628219fb4.png)
Ne pas tenir compte de la punaise
Les sous-menus (historique, favoris, ...) sont rétractables/déployables. Le menu historiques est déployés par défaut

**Comment by clarophil** [comment]
Attendre la décision de savoir si on laisse dans la top bar ou dans un nouveau menu child à gauche

**Comment by jj-quintin** [comment]
Effectivement, ce sera soit la proposition du wiki (http://www.crea-tice.org/mediawiki/index.php?title=Menus_Child_et_Book) soit ceci : 

![interface-generale-topbar](https://cloud.githubusercontent.com/assets/16414632/14979808/ea0329e4-1124-11e6-8143-81730b402393.png)

A noter que la position du menu qui correspond à l'espace sélectionné par l'utilisateur (ici Chimie organique) sera paramétrer : soit dans la topbar comme dans l'illustration ci-dessus, soit, come maintenant dans la sidebar
