### ISSUE TITLE
[ExoBundle] Display the score when score = 0

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#2360]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

When I have a score = 0, in the correction, no score is displayed in the progression ring (when we should see something like 0/n in the ring): 
![capture du 2017-05-09 13-39-42](https://cloud.githubusercontent.com/assets/15014599/25849003/02b46392-34bd-11e7-8550-2c36c442be50.png)

**Comment by ngodfraind** [comment]
Reproduit.
