### ISSUE TITLE
Widget Agenda > scrolling vertical

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#2364]
| Q             | A
| ------------- | ---
| Bug report?   |no
| Version?      | master.

Bonsoir,

Est-il possible d'afficher les informations du widget agenda/événements les unes en dessous des autres.
En effet l'affichage de plusieurs événements se fait par défilement horizontal.

![widget_evenements](https://cloud.githubusercontent.com/assets/27862129/25872629/c80de3c2-350b-11e7-8a05-6b72c0813d27.png)
Merci,
Bien cordialement.

**Comment by LaurentGruber** [comment]
Même solution que pour : https://github.com/claroline/Distribution/pull/2355/files

**Comment by l-matt** [comment]
Bonjour, j'avais effectivement effectué cette mise à jour avant d'ouvrir ce ticket.
Cela ne change rien, j'ai aussi rafraichis le cache.

**Comment by l-matt** [comment]
Super, merci

**Comment by Batier** [comment]
agenda et prochain evenement c'est le meme widget?

**Comment by LaurentGruber** [comment]
Le widget s'appelle prochains événements dans la liste des widgets mais il est dans le bundle Agenda et affiche les prochains événements de l'agenda donc oui
