### ISSUE TITLE
Ressourceweb : comment avec la bonne taille au départ?

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2366]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 9.1.0

quand je lance une resource web elle apparait toute petite
![image](https://cloud.githubusercontent.com/assets/5484259/25900791/ea73be62-3594-11e7-8c57-f86b1d13e558.png)
il faut que je passe par mettre plein écran puis taper sur la touche echppe pour avoir la vue à la bonne taille
![image](https://cloud.githubusercontent.com/assets/5484259/25901175/34393a9e-3596-11e7-8bc8-36ee3fcd3165.png)

**Comment by LaurentGruber** [comment]
Le souci doit venir du zip fournit pour créer la ressource web, j'ai fait le test avec un zip simple et il prend bien toute la place : 
![capture d ecran de 2017-05-12 09-38-48](https://cloud.githubusercontent.com/assets/5804394/25988061/dbad6e6a-36f6-11e7-81d2-7db8fda4895c.png)
