### ISSUE TITLE
Harmonisation interface utilisateur Bureau et Espace

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#237]
Voir [http://www.crea-tice.org/mediawiki/index.php?title=Bureau_et_espace_d%27activit%C3%A9s](http://www.crea-tice.org/mediawiki/index.php?title=Bureau_et_espace_d%27activit%C3%A9s)
Ne pas tenir compte du menu de gauche, une autre proposition est en cours de réflexion.

**Comment by clarophil** [comment]
L'idéal serait de proposer une palette de quelques couleurs.

**Comment by LaurentGruber** [comment]
duplicate of #205
