### ISSUE TITLE
sur mon navigateur chrome le menu de gauche n’apparaît pas

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2372]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 10.0.0-alpha.1

Soucis sur mon navigateur chrome le menu de gauche n’apparaît pas
alors que pas de soucis sur mozilla
cela vient de ma config car sur d'autres postes cela fonctionne

![image](https://cloud.githubusercontent.com/assets/5484259/25960943/d5022480-3678-11e7-9fd6-6cb5335f6776.png)

**Comment by LaurentGruber** [comment]
Quel est la particularité de ta config chrome ?

**Comment by Batier** [comment]
Version 57.0.2987.133 avec adblock comme extension

**Comment by ngodfraind** [comment]
Ça peut être un problème de cache.

Ctrl + f5 pour recharger la page.

**Comment by Batier** [comment]
effectivement c’était ça
