### ISSUE TITLE
Widget - background color uniquement pour le titre du panel

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2373]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.0-alpha.1

![image](https://cloud.githubusercontent.com/assets/5484259/25986654/15be5a7a-36f1-11e7-8b92-f378f87364d4.png)

ou limiter la couleur du widget au titre

**Comment by LaurentGruber** [comment]
Je suis pour limiter la couleur du widget à la barre de titre comme dans la v9, ça créera moins de confusion

**Comment by LaurentGruber** [comment]
En faite il y a maintenant une variable dans le thème qui permet de gérer ça ici :  https://github.com/claroline/Distribution/blob/master/main/core/Resources/less/themes/default/variables.less#L207 on l'a mise sur blanc dans le thème par défaut pour avoir un comportement similaire à avant.
