### ISSUE TITLE
Dans le widget prochain évènement toutes les dates sont sur une ligne

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2374]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.0-alpha.1

widget a droite sur cette capture écran

![image](https://cloud.githubusercontent.com/assets/5484259/25986962/386ee6a6-36f2-11e7-96ed-04516a025d2a.png)

**Comment by LaurentGruber** [comment]
duplicate of : https://github.com/claroline/Distribution/issues/2364 already correct ...
