### ISSUE TITLE
[ergonomie] Pour la configuration de tout les widgets

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2375]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 10.0.0-alpha.1

Il faut rajouter le type du widget qu'on configure
quand on est plusieurs a travailler sur un espace on passe après 
la création pas facile de trouver le type de widget

trouvez quel widget je modifie ci dessous????? 

![image](https://cloud.githubusercontent.com/assets/5484259/25987003/685ac2f4-36f2-11e7-8b85-431014de5114.png)

**Comment by ngodfraind** [comment]
C'est parce qu'il y a du html dans le nom sinon c'est clair. On peut rajouter le type comme info sinon effectivement.

**Comment by Batier** [comment]
non le html masque le titre mais on peut scroller dans le texte et le voir
tandis que le type lui est complètement absent
