### ISSUE TITLE
[ExoBundle] Managing score

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#238]
In the current version of the ExoBundle, you can specify a global score for a Choice question : if the User respond correctly, we assign a score and if it's false, we assign another. The "regular" way is to assign  a score to each choice and give the student the point if this choice is selected.

The problem is this not managed (or partially) outside of the question editor : the api, the json quiz schema and the player can not handle it. Another problem is that the unit tests fail on this point because we can not import question which use this notation rule (the imported data are incomplete) and the total score of the question is not calculable.

As this point involves managing a new type of notation, we need to create a system which will permits to respond to the @claroline/icap-ec requirements (they have many notation systems to implement), even if we don't implement all the rules by now.

We have discussed about a possible implementation with @stefk (thanks ;)).

The idea is to add a `score` property in the Question object.

```
"score": {
  "type": "sum"
}
```

The `score` is an `Object` with a required property `type` which will define the notation rule for this question. So we will be able to make the correct calculation based on the score `type`. The `score` object will also define relevant property for the score `type`.

So a possible format for the global score could be : 

```
"score": { 
  "type": "fixed", 
  "threshold": 2, 
  "success": 10, 
  "failure": 3 
}
```

`success` : The score the student gets if his answer is right
`failure` : The score the student gets if his answer is false
`threshold` : The threshold from which the answer is considered right. @stefk if I have correctly understood the purpose of this property it's only relevant for question which have multiple reponses (like, multiple Choices, Holes, Match).

For the time being, we need only two rules : 
- type: sum. Currently used by Choice, Match, Graphic, Hole
- type: fixed. Currently used by Open, Choice (not implemented). We might also want to use it for Match, Hole and Graphic

To implement this, we have to : 
- [x] Upgrade the json-quiz schema to validate and handle this new property.
- [ ] Change the API mark workflow to handle multiple score calculation rules.
- [ ] Change the API to export this info into JSON.
- [ ] Check the Choice question import and modify it to handle global score.
- [ ] Update Tests suite (update existing + write new one for this particular point)

I open this issue to have your feedback and improve the implementation if you think this will not be sufficient to manage all our cases. We can discuss it in the team meeting.

I think this an important point to solve quickly : the editor permits to add global score for Choice, so somebody will rapidly find the bug.

@claroline/maintainers 
@claroline/ujm 
@claroline/icap-ec 
@claroline/innova

**Comment by david42** [comment]
Yes, it should be better to implement notation into the API and the JSON schema.
The format proposed seems good.
However and unless I am mistaken, we decided in hangout to use the php services to calculate the score in order to advance on the others points. The integration in the API (for the offline) should be done in a second time.

**Comment by pitrackster** [comment]
@Elorfin seems good to me.
@david42 I think the problem is for tests. This has to be implemented ASAP so that tests can pass and bundle can be merged into distribution

**Comment by jj-quintin** [comment]
A toutes fins utiles, le détail du calcul du score en version formative se trouve ici http://www.crea-tice.org/mediawiki/index.php?title=Score

A noter donc que le calcul du score ne consiste pas simplement à affecter des points cas de mauvais ou bonne réponses, mais tient également compte du nombre d'essais et, dans le cas de questions de sélections, des choix possible

**Comment by charlotte42** [comment]
In the JSON schema for QCM questions: (Tests/Data/json/question/valid/complete/qcm-1.json)
 "choices": [
    {
      "id": "1",
      "type": "text/html",
      "data": "True"
    },

"data": "True" -> It's the expected answer ?

**Comment by charlotte42** [comment]
@Elorfin 
@stefk 
@david42 
Where in the schema JSON is the expected answer ?

**Comment by stefk** [comment]
@charlotte42, it's in the (optional) `solutions` property. Examples visible [here](http://json-quiz.github.io/json-quiz/spec/choice-question.html).

**Comment by Elorfin** [comment]
The score type `fixed` should be implemented for all question types (not only for Choices).

**Comment by Elorfin** [comment]
This has been implemented in the new version of the plugin.
