### ISSUE TITLE
[CoreBundle] Set platform logo to empty will still try to load a logo

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#2387]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

When setting platform's logo to "None" or empty, the platform still tries to load a logo (with the following url: http://DOMAIN/uploads/logos/)

This can result to something like this (depending the browser):
![image](https://cloud.githubusercontent.com/assets/3414935/26057963/0331767a-397c-11e7-9036-deb780a59b5d.png)

**Comment by ngodfraind** [comment]
Reproduit.
