### ISSUE TITLE
[ExoBundle] Make "correction manuelle" not accessible for anonymous and collaborator

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#2395]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

In the menu "more actions" as anonymous I can see and clic on "manual correction". Of course if I clic on it, I´m not able to go to the manual correction page, but it looks logical to not display this action for anonymous and collaborator.

**Comment by LaurentGruber** [comment]
je pense plus que ça ne doit être visible que si on a les droits d'édition sur l'exo, voir ceux de "coach"

**Comment by Pauooo** [comment]
@LaurentGruber oui oui

**Comment by Pauooo** [comment]
- administrateur => accès et droits d'éditions sur l'ensemble du questionnaire et tous droits sur copies.
- administrateur des copies => accès et droits d'édition sur : liste des résultats, export csv, docimologie.
- utilisateur =>accès au questionnaire et liste des résultats.
- anonymes => questionnaire seulement.
