### ISSUE TITLE
Importer une question graphique

### ISSUE THREAD

**Issue by david42** [claroline/Distribution#2397]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Lorsque j'importe une ancienne question graphique dans un exercice, j'obtiens le message "Le fichier selectionné n'est pas une image"

**Comment by LaurentGruber** [comment]
l'export vient d'où ? tu pourrais donner un exemple d'export que tu ne peux pas importer ?

**Comment by david42** [comment]
C'est une question présente dans ma banque, créée avec une version antérieure de CC

**Comment by david42** [comment]
Le répertoire files/data est vide, visiblement lors de la mise à jour les images n'ont pas été déplacée.
Je suis passé du V8 vers le master.
Vaut il mieux faire une mise à jour par étape en faisant V8 -> V9 -> master ?

**Comment by Elorfin** [comment]
Comme pour le #2399 :
Il n'est pas possible d'importer une question exportée depuis une v8 dans un claro >=9. 
Le modèle a trop changé entre les 2 versions et nous n'avons pas pu préserver la compatibilité.

Pour les autres points : 

- je ne penses pas qu'il y ait de soucis à passer directement de v8 à la master. Passer par la v9 permet surtout de faire un backup au cours du processus pour éviter de devoir tout rejouer en cas de bug.

- le problème sur le répertoire `files/data` n'a pas d'incidence sur ton problème initial. Est-ce que la PR de @ngodfraind corrige ce soucis (pour savoir s'il faut ouvrir un autre ticket pour ce point précis) ?

**Comment by david42** [comment]
Je pensais retrouver dans files/data les images liées aux anciennes questions graphiques.
Mais si je comprends bien ce n'est pas prévu de les récupérer ?

**Comment by Elorfin** [comment]
Elles devraient y être en effet...

**Comment by david42** [comment]
Mon répertoire data est bien créé mais reste vide. Du coup je ne peux pas utiliser les questions graphiques existantes.

**Comment by Elorfin** [comment]
Il doit manquer quelque chose dans la migration.
J'ai ouvert un nouveau ticket pour suivre le soucis https://github.com/claroline/Distribution/issues/2432.

**Comment by david42** [comment]
OK

**Comment by david42** [comment]
Visiblement il y avait aussi un problème de mime type pour quelques images.
Souci non lié à la migration. Ca ne résout pas le problème d'import qui semble plus général et pas forcément lié aux questions graphiques.
L'erreur  "Le fichier selectionné n'est pas une image" est quant à elle résolue
