### ISSUE TITLE
Import d'une ancienne question à trous

### ISSUE THREAD

**Issue by david42** [claroline/Distribution#2399]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Erreur lors de l'import d'une ancienne question à trous

Log console : 
"NetworkError: 422 Unprocessable Entity - http://localhost/cc_prod/web/app_dev.php/api/exercises/93ec74ee-6476-4798-9be7-b5890ec17e1b"

Log dev.log voir PJ

[dev.log.import.old.question.txt](https://github.com/claroline/Distribution/files/1007021/dev.log.import.old.question.txt)

**Comment by LaurentGruber** [comment]
L'export de la question à trou vient d'où ?

**Comment by david42** [comment]
C'est une question présente dans ma banque, créée avec une version antérieure de CC

**Comment by Elorfin** [comment]
Il n'est pas possible d'importer une question créée en v8 dans un claro >=9. 
Le modèle a trop changé entre les 2 versions et nous n'avons pas pu préserver la compatibilité.

**Comment by david42** [comment]
Ca va être très problèmatique pour nous car on ne peut pas monter de version sans pouvoir ré-utiliser l'existant. On ne pourrait pas s'aider de QTI (je sais que la norme n'a pas été encore reportée) ?

**Comment by Elorfin** [comment]
Qu'entends-tu par "réutiliser l'existant" ? Car lors de la mise à jour, les données des exo sont migrées et sont utilisables. 

La compatibilité a juste été cassée au niveau de l'import/export : il ne fonctionne qu'entre plateformes de version >9 (ou entre anciennes versions).

Pour ce qui est de QTI ce serait en effet un moyen de contourner le problème. Cependant c'est un gros morceau à développé et je ne sais pas quand ce sera dans la plateforme.

**Comment by david42** [comment]
On n'a pas dû se comprendre ce qui me rassurerait.
Je ne parle pas d'export mais juste d'import dans le sens de réutiliser dans un exercice une question créée avec une version <=8. Je ne fais pas référence à l'échange de données entre 2 plateformes.

**Comment by Elorfin** [comment]
Si il n'y a pas de communication entre plateforme, alors il n'y a pas de soucis.

Le modèle de données des questions est migré lors de la mise à jour donc tu pourras utilisées tes anciennes questions dans tes nouveaux exercices (et réutiliser les anciens exercices).

Par contre, si tu veux les utiliser dans une plateforme, c'est là que ça coince si tes plateformes ont des versions différentes.

**Comment by david42** [comment]
C'est bien dans une même plateforme. Mais je rencontre des soucis avec les questions graphiques à cause de images non migrées dans le répertoire data et avec les questions à trous.
