### ISSUE TITLE
[Collecticiel]Changer les options de la ressource

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#24]
_From @purplefish32 on March 30, 2016 12:1_

_From @ericvincenterv on July 16, 2015 7:45_

Dans la liste des collectiels, il faut enlever les 3 ou 4 dernières possibilités.

Et dans l'édition des propriétés, il faut modifier le type en "Collecticiel".

_Copied from original issue: InnovaLangues/CollecticielBundle#84_

_Copied from original issue: claroline/Claroline#765_

**Comment by purplefish32** [comment]
_From @ericvincenterv on September 10, 2015 9:1_

A revoir pour la prochaine version.

**Comment by purplefish32** [comment]
_From @ericvincenterv on September 23, 2015 9:56_

Vu avec Donovan : 
voir avec JJQ car il est l'initiateur.

**Comment by jj-quintin** [comment]
@ericvincenterv 
Peux-tu voir si ceci est tjs ouvert et la cas échéant préciser de quoi il s'agit ? Merci

**Comment by ericvincenterv** [comment]
@jj-quintin : 
Si mes souvenirs sont bons, c'était pour mettre à jour la liste des options possibles : 
![capture d ecran - 19072016 - 11 03 32](https://cloud.githubusercontent.com/assets/5363344/16944347/655884e2-4da0-11e6-928f-6c81737d2b8f.png)

**Comment by jj-quintin** [comment]
Je vois que pour le type de ressource dans Propriétés c'est ok

Pour "Dans la liste des collectiels, il faut enlever les 3 ou 4 dernières possibilités.", si cela fait référence aux espaces partagés, je ne vois pas de quoi il s'agit
