### ISSUE TITLE
Création d'une question graphique

### ISSUE THREAD

**Issue by david42** [claroline/Distribution#2400]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Erreur lors de l'enregistrement d'une nouvelle question graphique : 

"Une erreur est survenue pendant l'exécution de la requête."

dev.log voir PJ qui termine par une requête
[dev.log.creation.graph.txt](https://github.com/claroline/Distribution/files/1007041/dev.log.creation.graph.txt)

**Comment by LaurentGruber** [comment]
il y a quoi dans la console ? Comme réponse à la requête ?

**Comment by david42** [comment]
Pas grand chose : 

"NetworkError: 500 Internal Server Error - http://localhost/cc_prod/web/app_dev.php/api/exercises/93ec74ee-6476-4798-9be7-b5890ec17e1b"

En revanche dans la console réseau j'ai pu avoir des logs plus probants : 
CRITICAL - Uncaught PHP Exception InvalidArgumentException: "The "/media/david/DATA/claro-prod/claroline-connect/app/../files/data" directory does not exist." at /media/david/DATA/claro-prod/claroline-connect/vendor/symfony/symfony/src/Symfony/Component/Finder/Finder.php line 635 

Le répertoire data n'est pas présent dans files.

**Comment by david42** [comment]
En créant manuellement le répertoire je peux ensuite créer ma question graphique

**Comment by LaurentGruber** [comment]
Le dossier data est créé par un updater, d'autres updater convertissent le format des questions de l'ancienne version vers la nouvelle.
Je pense que tous les updater ne sont pas passé correctement, lors de ta MaJ

**Comment by david42** [comment]
Ce qui expliquerait certainement le problème #2397

**Comment by LaurentGruber** [comment]
oui, l'updater, déplace également tous les fichiers existant normalement

**Comment by david42** [comment]
J'ai relancer la procédure, le répertoire data est bien présent mais je n'arrive toujours pas à créer une question graphique.
Voici la réponse (json) obtenue via la console réseau : 
[{"path":"\/parameters\/type","message":"should match one element in enum"}]

**Comment by david42** [comment]
Je viens de faire un nouveau test de migraiton mais pas de la V8 au master mais de la V8 à la V9.
J'ai un problème durant la mise à jour de la BD : 

An exception occurred while executing '                                                         
              INSERT INTO ujm_grid_row_item (row_id, item_id, entity_order) (                     
                  SELECT r.id AS row_id, gi.id AS item_id, 0 AS entity_order                      
                  FROM ujm_proposal AS p                                                          
                  JOIN ujm_grid_item AS gi ON (p.uuid = gi.uuid)                                  
                  JOIN ujm_proposal_label AS pl ON (p.id = pl.proposal_id)                        
                  JOIN ujm_label AS l ON (pl.label_id)                                            
                  JOIN ujm_grid_row AS r ON (l.uuid = r.original_label)                           
              );                                                                                  
              ALTER TABLE ujm_grid_row DROP original_label;                                       
          ':                                                                                      
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-32' for key 'PRIMARY'  
                                                                                                  

                                                                                                  
  [Doctrine\DBAL\Driver\PDOException]                                                             
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-32' for key 'PRIMARY' 

Problème que je n'ai pas lors d'un update de la V8 au master.
Nombre d'entrées dans ujm_grid_row_item lors d'un update en V9 :  20
Nombre d'entrées dans ujm_grid_row_item lors d'un update vers le master :  440
Cette table est créée à partir de la V9

**Comment by david42** [comment]
Ce problème ne se pose que dans un exercice créée en version <=8 et n'est pas liée spécialement aux questions graphiques. Je clos ce ticket. J'en ouvre un nouveau avec de nouvelles données
