### ISSUE TITLE
[ExoBundle] CSV Export

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#2406]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master

When I export my results, all the columns of the list of results are in my csv. 
The column "paper_finished" displays nothing if finished and 1 if not finished.
Could it be possible to display "finished"/"not finished".

**Comment by kitan1982** [comment]
Right now the value exported in the csv is not for "paper_finished" but for "paper_is_interrupted".
Should it be inversed ?
