### ISSUE TITLE
[ExoBundle] : déplacement des questions entre étape en drag and grop

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2407]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 10.0.0-alpha.1

Permettre le drag & drop de questions entre étape

**Comment by LaurentGruber** [comment]
Il n'a jamais fonctionné, on l'a envisagé, mais vu le nombre de drag and drop déjà présent, c'est compliqué à mettre en place. Donc pour le moment, tu supprimes la question d'une étape et tu l'importe depuis ta banque dans l'autre.

**Comment by Batier** [comment]
Merci de rouvrir l'issue et la taguer ? faire plus tard :-)

Christophe BATIER
Batier@univ-lyon1.fr<mailto:Batier@univ-lyon1.fr>
+33 6 31 69 78 93
Http://www.twitter.com/Batier

Le 18 mai 2017 ? 07:23, Gruber Laurent <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Il n'a jamais fonctionn?, on l'a envisag?, mais vu le nombre de drag and drop d?j? pr?sent, c'est compliqu? ? mettre en place. Donc pour le moment, tu supprimes la question d'une ?tape et tu l'importe depuis ta banque dans l'autre.

-
