### ISSUE TITLE
[ExoBundle] Manual correction : need to refresh to have a update list of the papers + add a tool tip

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#2414]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master/7.0/etc.

- [ ] I answer to an opened question. My first try is directly added to the list of the copy to correct, but the following answers are not : if I go to " manual correction" the new opened question is not in the list, I need to refresh to see it.
- [x] it would be nice to have a tool tip on the fa-check-square-o icon saying "corriger"
- [x] When I want to save my correction, I have an error (422).

**Comment by Elorfin** [comment]
I don't reproduce the last point.

**Comment by Pauooo** [comment]
@Elorfin I do reproduce it on the 3L and I still have an error when I want to save my corrections.

**Comment by Elorfin** [comment]
It will be fixed by https://github.com/claroline/Distribution/pull/2465.
