### ISSUE TITLE
Incorrect score when testing an exercise.

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#2427]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

The final score given in the circle at the top left of the page is not correct when testing an exercise in LEA.

![lea](https://cloud.githubusercontent.com/assets/14308826/26406368/63a0a486-4098-11e7-9a6b-6e4716874fda.png)

**Comment by ngodfraind** [comment]
Also I cannot import the LEA workspace.

**Comment by ngodfraind** [comment]
Impossible d'éditer l'exo suivant: C'est ça qui cause l'erreur à l'import:
http://lea.claroline.com/resource/open/ujm_exercise/739#editor

**Comment by ngodfraind** [comment]
D'ailleurs il ne s'affiche pas dans la liste des exercices là ou il devrait être.

**Comment by ngodfraind** [comment]
Supprimer puis remettre les liaisons a "réparé" le problème ? Erreur lors d'une maj ?

**Comment by ngodfraind** [comment]
Reproduit en local...

**Comment by ngodfraind** [comment]
Le score affiché diffère suivant que l'on teste ou non l'exo.
Il est correcte lorsqu'on ne teste pas, erroné sinon.
