### ISSUE TITLE
impossible de consulter les copies d'un questionnaire

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2435]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.0-alpha.1

Je n’ai pas trouvé le bouton consulter mes copies dans un quiz
en vue etudiant
J’ai cliqué sur ce bouton… mais rien ne s’est passé.
https://clarolineconnect.univ-lyon1.fr/resource/open/ujm_exercise/60026#papers

 
![image](https://cloud.githubusercontent.com/assets/5484259/26628615/1025cef0-45ff-11e7-8f18-b0ccf656f429.png)

**Comment by LaurentGruber** [comment]
@ptsavdar tu peux voir si c'est encore le cas sur le master, il y a déjà eu plusieur pr pour corriger ces comportements ...

**Comment by ptsavdar** [comment]
@LaurentGruber @Batier en fait le pb ce ne passe rien mais que se passe lentement. Moi j'ai eu des resultats par contre j'ai du attendre 30seconds. Voici la capture de mon ecran. 
![image](https://cloud.githubusercontent.com/assets/3414935/26679635/4ccafec0-46d6-11e7-95fe-18f8f908f141.png)
Quand j'ai teste en local, il n'a pas mis autant de temps (~800ms pour 2 jeux des reponses). Comme je n'ai pas des questionnaires avec bcp des questions et des reponses avec des scores en local je ne peux pas malhereusement tester plus profondement en local.

**Comment by david42** [comment]
Je n'avais pas vu cette issue, il doit y avoir un lien avec mon ticket #2437 
Le problème de mon coté se pose après migration vers le master pour les exercices créés avec une version de CC <=V8
