### ISSUE TITLE
Consultation des copies des exercices créés en V <= 8

### ISSUE THREAD

**Issue by david42** [claroline/Distribution#2437]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

La consultation des copies génère une erreur : 
Notice: Trying to get property of non-object
in vendor/claroline/distribution/plugin/exo/Serializer/Attempt/PaperSerializer.php at line 160

**Comment by Elorfin** [comment]
Dans la base que tu m'as envoyée il y a : 
- 4 questions qui ont mal été migrées (le plus souvent il s'agit d'anciennes questions mal supprimées).
- 290 copies qui ne contiennent pas la structure de l'exercice.

Il faut que je creuse plus.

**Comment by david42** [comment]
Je viens de tester la migration en V10.
J'ai ce problème sur un exo où les copies s'affichent bien en V8.
Exemple avec l'id (resourceNode) 67079

**Comment by Elorfin** [comment]
tu pourrais m'envoyer la nouvelle base générée stp ?

**Comment by david42** [comment]
Impossible de supprimer les logs de la base beaucoup trop de références. Mysql n'accepte pas que je vide la table

**Comment by david42** [comment]
Finalement j'ai pu supprimer les données en supprimant physiquement les autres tables de logs et 2 tables liées aux activitées. Les vider ne suffisait pas à mysql pour qu'il accepte de vider claro_log ...
Je t'envoie l'export par mail

**Comment by david42** [comment]
Précision que je n'ai pas donné, depuis ma migration d'hier je n'arrive pas à lister les copies d'un exercice, il ne s'agit donc pas seulement de la consultation d'une copie

**Comment by Elorfin** [comment]
L'explication, c'est quand dans les bases que tu m'as envoyées, la structure des papers n'a pas été migrée.

Pourrais-tu me dire sur quel commit de la 10.x tu es sur ta plateforme stp ?
