### ISSUE TITLE
Modifier un exercice créé avec une version <= V8

### ISSUE THREAD

**Issue by david42** [claroline/Distribution#2438]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Problème rencontré suite à la migration V8 vers master : 

Tests effectués indépendament des un des autres :

- Céation d'une nouvelle question

- Import d'une ancienne question (créée en <= V8)

- Suppression de toutes les questions et des étapes sans rien ajouter

- Modification du titre de l'exercice depuis le menu "Paramètres"

Même résultat pour ces différents tests.
Toutes modifications sur un exercice créé en version <= V8 aboutissent à l'erreur :
Code http : 422
JSON  retourné  : Object { path="/parameters/type",  message="should match one element in enum"}

**Comment by Elorfin** [comment]
Il semblerait que cette migration ne se soit pas exécutée (je ne sais pas pourquoi) :
https://github.com/claroline/Distribution/blob/master/plugin/exo/Installation/Updater/Updater090000.php#L81

Tu peux facilement régler le soucis en exécutant les requête suivantes sur la base **après migration** : 

```
UPDATE ujm_exercise SET `type` = "summative" WHERE `type` = "sommatif";
UPDATE ujm_exercise SET `type` = "summative" WHERE `type` = "1";
UPDATE ujm_exercise SET `type` = "evaluative" WHERE `type` = "2";
UPDATE ujm_exercise SET `type` = "formative" WHERE `type` = "3";
UPDATE ujm_exercise SET show_feedback = true WHERE `type` = "formative";
```

Pour vérifier que cette fois c'est bon : 

```
SELECT COUNT(*), `type` FROM ujm_exercise GROUP BY `type`;
```

(Tu ne devrais plus avoir que les 3 valeurs `summative`, `evaluative`, `formative`).

**Comment by david42** [comment]
Ok merci.
Je viens de passer les requêtes.
J'ai modifié le titre de l'exercice est j'ai une autre erreur lors de l'enregistrement : 
	Object { path="/parameters/endMessage",  message="instance must be of type string"}

**Comment by Elorfin** [comment]
Ce problème a été corrigé ici : https://github.com/claroline/Distribution/pull/2517.
Une maj devrait régler le soucis.
