### ISSUE TITLE
Importer une question existante dans un exercice

### ISSUE THREAD

**Issue by david42** [claroline/Distribution#2439]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Tests effectués dans un exercice créé en V10, l'import étant impossible dans un exercice créé dans une version inférieure (#2438)

Import d'une question QCM créée en <=8
ok

Import d'une question Assoc créée en <=8
ok

Import d'une question Open créée en <=8
ok

Imports questions graphique et à trous
Code http : 422
Retour JSON similaire à :

> Object { path="/steps/0/items/5",  message="property "data" is missing"}
	Object { path="/steps/0/items/5",  message="property "url" is missing"}
	Object { path="/steps/0/items/5",  message="instance must match exac...schemas listed in oneOf"}
	Object { path="/steps/0/items/5",  message="instance must match all ...schemas listed in allOf"}
	Object { path="/steps/0/items/5",  message="property "random" is missing"}
	Object { path="/steps/0/items/5",  message="property "multiple" is missing"}
	Object { path="/steps/0/items/5",  message="property "choices" is missing"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "id" is missing"}
	Object { path="/steps/0/items/5/solutions/0/feedback",  message="instance must be of type string"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "id" is missing"}
	Object { path="/steps/0/items/5/solutions/1/feedback",  message="instance must be of type string"}
	Object { path="/steps/0/items/5/type",  message="should match one element in enum"}
	Object { path="/steps/0/items/5",  message="instance must match all ...schemas listed in allOf"}
	Object { path="/steps/0/items/5",  message="property "random" is missing"}
	Object { path="/steps/0/items/5",  message="property "penalty" is missing"}
	Object { path="/steps/0/items/5",  message="property "firstSet" is missing"}
	Object { path="/steps/0/items/5",  message="property "secondSet" is missing"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "firstId" is missing"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "secondId" is missing"}
	Object { path="/steps/0/items/5/solutions/0/feedback",  message="instance must be of type string"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "firstId" is missing"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "secondId" is missing"}
	Object { path="/steps/0/items/5/solutions/1/feedback",  message="instance must be of type string"}
	Object { path="/steps/0/items/5/type",  message="should match one element in enum"}
	Object { path="/steps/0/items/5",  message="instance must match all ...schemas listed in allOf"}
	Object { path="/steps/0/items/5",  message="property "items" is missing"}
	Object { path="/steps/0/items/5/type",  message="should match one element in enum"}
	Object { path="/steps/0/items/5",  message="instance must match all ...schemas listed in allOf"}
	Object { path="/steps/0/items/5",  message="property "text" is missing"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "holeId" is missing"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "answers" is missing"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "holeId" is missing"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "answers" is missing"}
	Object { path="/steps/0/items/5/type",  message="should match one element in enum"}
	Object { path="/steps/0/items/5",  message="instance must match all ...schemas listed in allOf"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "text" is missing"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "caseSensitive" is missing"}
	Object { path="/steps/0/items/5/solutions/0/feedback",  message="instance must be of type string"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "text" is missing"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "caseSensitive" is missing"}
	Object { path="/steps/0/items/5/solutions/1/feedback",  message="instance must be of type string"}
	Object { path="/steps/0/items/5/type",  message="should match one element in enum"}
	Object { path="/steps/0/items/5",  message="instance must match all ...schemas listed in allOf"}
	Object { path="/steps/0/items/5",  message="property "contentType" is missing"}
	Object { path="/steps/0/items/5/type",  message="should match one element in enum"}
	Object { path="/steps/0/items/5",  message="instance must match all ...schemas listed in allOf"}
	Object { path="/steps/0/items/5/solutions/0/feedback",  message="instance must be of type string"}
	Object { path="/steps/0/items/5/solutions/1/feedback",  message="instance must be of type string"}
	Object { path="/steps/0/items/5",  message="instance must match all ...schemas listed in allOf"}
	Object { path="/steps/0/items/5",  message="property "random" is missing"}
	Object { path="/steps/0/items/5",  message="property "penalty" is missing"}
	Object { path="/steps/0/items/5",  message="property "sets" is missing"}
	Object { path="/steps/0/items/5",  message="property "items" is missing"}
	Object { path="/steps/0/items/5/solutions",  message="instance must be of type object"}
	Object { path="/steps/0/items/5/type",  message="should match one element in enum"}
	Object { path="/steps/0/items/5",  message="instance must match all ...schemas listed in allOf"}
	Object { path="/steps/0/items/5",  message="property "random" is missing"}
	Object { path="/steps/0/items/5",  message="property "penalty" is missing"}
	Object { path="/steps/0/items/5",  message="property "items" is missing"}
	Object { path="/steps/0/items/5",  message="property "rows" is missing"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "itemIds" is missing"}
	Object { path="/steps/0/items/5/solutions/0/feedback",  message="instance must be of type string"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "itemIds" is missing"}
	Object { path="/steps/0/items/5/solutions/1/feedback",  message="instance must be of type string"}
	Object { path="/steps/0/items/5/type",  message="should match one element in enum"}
	Object { path="/steps/0/items/5",  message="instance must match all ...schemas listed in allOf"}
	Object { path="/steps/0/items/5/type",  message="should match one element in enum"}
	Object { path="/steps/0/items/5",  message="property "mode" is missing"}
	Object { path="/steps/0/items/5",  message="property "selections" is missing"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "selectionId" is missing"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "answers" is missing"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "selectionId" is missing"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "answers" is missing"}
	Object { path="/steps/0/items/5",  message="property "mode" is missing"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "selectionId" is missing"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "begin" is missing"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "end" is missing"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "selectionId" is missing"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "begin" is missing"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "end" is missing"}
	Object { path="/steps/0/items/5",  message="property "mode" is missing"}
	Object { path="/steps/0/items/5",  message="property "selections" is missing"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "selectionId" is missing"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "selectionId" is missing"}
	Object { path="/steps/0/items/5",  message="instance must match exac...schemas listed in oneOf"}
	Object { path="/steps/0/items/5",  message="instance must match all ...schemas listed in allOf"}
	Object { path="/steps/0/items/5",  message="property "penalty" is missing"}
	Object { path="/steps/0/items/5",  message="property "cells" is missing"}
	Object { path="/steps/0/items/5",  message="property "rows" is missing"}
	Object { path="/steps/0/items/5",  message="property "cols" is missing"}
	Object { path="/steps/0/items/5",  message="property "border" is missing"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "cellId" is missing"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "answers" is missing"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "cellId" is missing"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "answers" is missing"}
	Object { path="/steps/0/items/5/type",  message="should match one element in enum"}
	Object { path="/steps/0/items/5",  message="instance must match all ...schemas listed in allOf"}
	Object { path="/steps/0/items/5",  message="property "penalty" is missing"}
	Object { path="/steps/0/items/5",  message="property "items" is missing"}
	Object { path="/steps/0/items/5",  message="property "mode" is missing"}
	Object { path="/steps/0/items/5",  message="property "direction" is missing"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "itemId" is missing"}
	Object { path="/steps/0/items/5/solutions/0/feedback",  message="instance must be of type string"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "itemId" is missing"}
	Object { path="/steps/0/items/5/solutions/1/feedback",  message="instance must be of type string"}
	Object { path="/steps/0/items/5/type",  message="should match one element in enum"}
	Object { path="/steps/0/items/5",  message="instance must match all ...schemas listed in allOf"}
	Object { path="/steps/0/items/5",  message="property "choices" is missing"}
	Object { path="/steps/0/items/5/solutions/0",  message="property "id" is missing"}
	Object { path="/steps/0/items/5/solutions/0/feedback",  message="instance must be of type string"}
	Object { path="/steps/0/items/5/solutions/1",  message="property "id" is missing"}
	Object { path="/steps/0/items/5/solutions/1/feedback",  message="instance must be of type string"}
	Object { path="/steps/0/items/5/type",  message="should match one element in enum"}
	Object { path="/steps/0/items/5",  message="instance must match all ...schemas listed in allOf"}
	Object { path="/steps/0/items/5",  message="instance must match exac...schemas listed in oneOf"}

**Comment by Elorfin** [comment]
Le problème se produit uniquement avec les questions Graphiques et A trous créé en v8 ou même avec les questions créées en v10 ?

**Comment by Elorfin** [comment]
ping @david42

**Comment by david42** [comment]
Pour un exo en V8 on ne peut pas importer des questions en V8 ni en V10
Pour un exo en V10 on peut importer des questions créées en V10 mais pas V8

**Comment by LaurentGruber** [comment]
je n'arrive pas à reproduire
