### ISSUE TITLE
[ExoBundle] exercice d'associations : bug. Impossible de remonter l'écran

### ISSUE THREAD

**Issue by CatherineVinci** [claroline/Distribution#2455]
Il n'est pas possible de faire remonter/descendre/défiler l'écran quand on souhaite associer un élément en bas de page à un élément de haut de page (idem dans l'autre sens). 

Voir 
http://lea.claroline.com/resource/open/ujm_exercise/712#play

| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

**Comment by LaurentGruber** [comment]
Idem que : https://github.com/claroline/Distribution/issues/2177
