### ISSUE TITLE
[ExoBundle] Exercices de pointeurs et couleurs différentes. Bug

### ISSUE THREAD

**Issue by CatherineVinci** [claroline/Distribution#2456]
Pas possible d'avoir différentes couleurs de pointeurs quand il faut sélectionner des éléments dans un texte 
![image](https://user-images.githubusercontent.com/29223614/26921724-2c65e340-4c3d-11e7-8412-6f0095578bc6.png)

voir exercice : 
http://lea.claroline.com/resource/open/ujm_exercise/705#play
Merci 
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

**Comment by LaurentGruber** [comment]
Ce n'est pas implémenté. La couleur de la zone sert pour se repérer dans la correction.
Les pointeurs ne sont pas spécifiquement lié à une zone. C'est une évolution, possible...

**Comment by CatherineVinci** [comment]
Ce serait important de le faire, car dans les consignes, certains concepteurs d'exercices demandent explicitement de pointer par exemple en bleu le titre, en vert les arguments, etc.
