### ISSUE TITLE
[WS] Tri par date plante

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#2457]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Quand on essaie de trier le tableau par date de création, un message d'erreur s'affiche.

Test effectué sur 3l.

**Comment by Gatomlo** [comment]
La pagination pose le même problème. Impossible de changer de page.

**Comment by ngodfraind** [comment]
reproduit
