### ISSUE TITLE
[Plugin][Collecticiel] Add criterion && tags

### ISSUE THREAD

**Issue by pitrackster** [claroline/Distribution#247]
Currently add grading scale and add grading criteria form is not working properly.
- [ ] Remove alerts
- [ ] Extract js methods from popup.js into proper js file
- [ ] Add translations

**Comment by ericvincenterv** [comment]
Ce que j'ai fait pour les traductions : 
Dans le fichier "layout.html.twig" : 
````
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset("bundles/innovacollecticiel/js/datatables.min.js") }}" ></script>
    <script src="{{ asset("bundles/innovacollecticiel/js/datatables-init.js") }}" ></script>
    **<script type="text/javascript" src="{{ url('bazinga_jstranslation_js', { 'domain': 'innova_collecticiel' }) }}"></script>**
{% endblock %}
````
et dans le popup.js : 
````
    var $gradingScaleTranslator = Translator.trans('Add grading scale', {}, 'innova_collecticiel');
````

**Comment by pitrackster** [comment]
Yep that's the way to do it !
I'm also creating a separate js file to handle criterion management

**Comment by ericvincenterv** [comment]
If you want, I will make this part of this issue.

**Comment by pitrackster** [comment]
that's ok for me I'll handle it ! thx ;-)
