### ISSUE TITLE
[ExoBundle] Appariements : pas moyen de remonter l'écran

### ISSUE THREAD

**Issue by CatherineVinci** [claroline/Distribution#2485]
Même pb (résolu maintenant) que dans les associations : pas possible de descendre ou remonter l'écran pour mettre un item de gauche dans la sélection de droite si elles ne sont pas visibles sur le même écran. 

Voir http://lea.claroline.com/resource/open/ujm_exercise/727#play

![image](https://user-images.githubusercontent.com/29223614/27121547-1d72e996-50e8-11e7-8ac0-e8b2acc6b78a.png)

Et si on descend ... (plus d'accès au premier appariement)

![image](https://user-images.githubusercontent.com/29223614/27121589-3b4df33e-50e8-11e7-94cd-69b75705a00f.png)

Merci 

| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

**Comment by clarophil** [comment]
Je n'ai pas réussi à reproduire ton problème, peux-tu essayer avec chrome ?

**Comment by CatherineVinci** [comment]
C'est avec Chrome... même pb que celui avec les flèches : une fois qu'on a pointé un item à associer à droite, pas moyen de remonter l'écran pour accéder au cadre à associer
