### ISSUE TITLE
[ExoBundle] Consigne : pb de mise en page (passage à la ligne)

### ISSUE THREAD

**Issue by CatherineVinci** [claroline/Distribution#2486]
Dans certaines consignes le traitement de texte fait des passages à la ligne en coupant les mots 
![image](https://user-images.githubusercontent.com/29223614/27129531-0edd3d80-5103-11e7-8679-8064249e3ff1.png)

Merci
Exemple avec URL de l'exo

http://lea.claroline.com/resource/open/ujm_exercise/824#play 

| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

**Comment by clarophil** [comment]
Tu sais donner l'url de l'exercice car je ne pense pas que ça vient de l'éditeur.

**Comment by CatherineVinci** [comment]
Fait (dans la requête principale)... le jobiste signale ne pas savoir comment faire pour éviter le pb

**Comment by clarophil** [comment]
Il faut mettre le texte dans description et ne rien mettre dans le titre.

**Comment by CatherineVinci** [comment]
OK je transmets au jobiste. Par contre les autres ont souvent mis la référence en titre et pas de pb…


De : clarophil [mailto:notifications@github.com]
Envoyé : jeudi 15 juin 2017 11:14
À : claroline/Distribution <Distribution@noreply.github.com>
Cc : Catherine Deschepper <catherine.deschepper@vinci.be>; Author <author@noreply.github.com>
Objet : Re: [claroline/Distribution] [ExoBundle] Consigne : pb de mise en page (passage à la ligne) (#2486)


Il faut mettre le texte dans description et ne rien mettre dans le titre.
