### ISSUE TITLE
[Collecticiel]Modifier le fonctionnement des fichiers cachés

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#25]
_From @purplefish32 on March 30, 2016 12:1_

_From @ericvincenterv on July 16, 2015 7:46_

Les fichiers/répertoires cachés s'affichent au même niveau que la liste des collecticiels.

Ceci est à revoir.

_Copied from original issue: InnovaLangues/CollecticielBundle#85_

_Copied from original issue: claroline/Claroline#764_

**Comment by purplefish32** [comment]
_From @ericvincenterv on September 10, 2015 9:32_

A voir pour la prochain version?
A voir avec Nathalie ?

**Comment by purplefish32** [comment]
_From @ericvincenterv on September 23, 2015 9:55_

Vu avec Donovan : stand-by.

**Comment by jj-quintin** [comment]
Discussion générale nécessaire avant de décider. De toute manière, tant qu'on a pas la fonction d'exportation implémentée dans le collecticiel lui-même (cf. menu des actions dans demandes adressées), on ne peut rien changer à ce niveau il me semble

**Comment by jj-quintin** [comment]
L'emplacement des dossiers cachés ainsi que leur "fonctionnement" devrait faire l'objet d'une dioscussion générale, y compris avec Philippe Dekimpe. Il a, par ailleurs, communiqué une demande de bloquer les droits, offerts aux étudiants, de modifier les propriétés ou les droits, ce qui semble avoir été fait. Tu confirmes Eric ?
