### ISSUE TITLE
[ExoBundle] pointeurs : pas de possibilité d'annuler un pointeur précis (amélioration)

### ISSUE THREAD

**Issue by CatherineVinci** [claroline/Distribution#2501]
Dans les exercices où il faut utiliser les pointeurs, en cas d'erreur, on peut annuler le dernier pointeur utilisé (puis l'avant dernier et ainsi de suite). Ce serait plus pertinent de pouvoir annuler n'importe quel pointeur au choix (en recliquant dessus par exemple).

Cas de figure : on doit poser 10 marques de ponctuation. A la fin de l'exercice on trouve une ponctuation à mettre et on n'a plus de pointeur. A ce stade, on doit annuler en cascade jusqu'à trouver l'erreur. Ce serait plus simple et pédagogiquement judicieux de pouvoir identifier le pointeur mal placé, de le retirer et de disposer du pointeur récupéré pour l'utiliser ensuite. 

Merci

| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

**Comment by clarophil** [comment]
Cela concerne les questions graphiques uniquement ?

**Comment by CatherineVinci** [comment]
Je pense. Dans les autres types de question une petite poubelle permet de "jeter" l'élément sélectionner ou alors il suffit de l'enlever du mode de sélection appelé par la question.
