### ISSUE TITLE
l'editeur enrichi toujours en anglais :-(

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2533]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.0-RC.4
alors que mon interface est bien FR

![image](https://user-images.githubusercontent.com/5484259/27469107-04bc0c54-57ee-11e7-89be-54e9c4c5ced5.png)

**Comment by ptsavdar** [comment]
Same as #2410. Closing this one

**Comment by Batier** [comment]
ben non c'est pas sur la meme version :-)
