### ISSUE TITLE
[AnnouncementBundle] Il n'est plus possible de modifier ou supprimer les annonces

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2534]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.0-RC.4
une fois crée on ne peut plus ni modifier ni supprimer une annonce?
pourquoi?

![image](https://user-images.githubusercontent.com/5484259/27470153-cfab3616-57f2-11e7-83c8-2dd2f416cf8e.png)

**Comment by ngodfraind** [comment]
Aucune idée. J'ai eu le même problème. Pas encore compris pourquoi.

**Comment by ptsavdar** [comment]
![image](https://user-images.githubusercontent.com/3414935/27472745-d9b50092-57fc-11e7-8cab-8202f4ce9eb9.png)

**Comment by Elorfin** [comment]
Je penses qu'il s'agit d'un problème de styles : les liens de votre plateforme sont du même vert que les widgets. 

Pourriez-vous me confirmer que les boutons sont bien là ?

**Comment by Batier** [comment]
non non y a pas de texte ...en plus c'etait des boutons avant...

**Comment by Batier** [comment]
si je mets le texte en surbrillance y a pas line non plus 
![image](https://user-images.githubusercontent.com/5484259/27483600-661d685c-5826-11e7-80c1-9465584a1dd9.png)

**Comment by ngodfraind** [comment]
Reproduit en local.

**Comment by ngodfraind** [comment]
Je confirme que c'est un problème de css. Les boutons sont bien là mais... caché.
En faisant un dump() du isGranted (https://github.com/claroline/Distribution/blob/master/plugin/announcement/Resources/views/announcementsList.html.twig#L64) juste dans la div dont la classe est pull-right, j'obtiens ça:

![screenshot from 2017-06-23 16-00-04](https://user-images.githubusercontent.com/1397430/27485537-68a21e72-582d-11e7-9271-61fbc604f2e6.png)

On peut voir qu'un des div se trouve sur l'autre et c'est ça qui cause problème.
@Elorfin  Une idée d'ou ça peut venir ?

**Comment by ngodfraind** [comment]
Corrigé avec @Elorfin
