### ISSUE TITLE
[Activity] Every resource added in an activity gets "cropped". It's full content is not visible

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#2540]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

When adding a resource in an Activity (blog, wiki, etc.) it's content is not visible. The resource gets cropped. Even if immediately after insertion the content sometimes is available (resize happens with no problem), when refreshing the page, the content is not loaded properly (no resizing).

![image](https://user-images.githubusercontent.com/3414935/27475340-25b00dcc-5805-11e7-89c2-f747d12c39db.png)

**Comment by Batier** [comment]
![image](https://user-images.githubusercontent.com/5484259/27730246-e1fcda18-5d88-11e7-9c8a-d60ece042c08.png)
MAJ soucis tjs présent dans la version  10.0.0-RC.4

**Comment by ngodfraind** [comment]
J'ai pu reproduire mais c'est bizarre.

J'ai rajouté un blog: tout allait bien.
J'ai rajouté un wiki: tout allait bien
J'ai rajouté un pdf: rien ne va plus (et le problème est reproduit). Enfin rien ne va plus... le pdf s'affiche proprement mais le reste ne suis plus.
