### ISSUE TITLE
[CoreBundle] Les droits sur les ressources sont incohérents (plusieurs fois le même droit et le même rôle sur une même ressource avec des perms différentes)

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2546]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.0-RC.4

sur le même objet j'ai des droits différents en fonction de l'endroit où je les édite

![image](https://user-images.githubusercontent.com/5484259/27483420-9b080bc2-5825-11e7-91c4-6d4f73064473.png)

**Comment by ngodfraind** [comment]
Je ne sais pas, mais j'ai vu un problème similaire à un endroit.

Je suis dessus (enfin sur ce genre d'issues) pour le moment.

**Comment by Batier** [comment]
a vue de nez quand on fait avec la nouvelle interface il remonte pas la modif simple des droits mais uniquement les droits avancés systématiquement

**Comment by ngodfraind** [comment]
Corrigé dans le Datasewriter sur la 10.x (je retrouve plus le commit par contre).
