### ISSUE TITLE
[CoreBundle] Workspace manager admin tool -> administrator list display issue

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#2555]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

In the new workspace manager admin tool, the popup to display the list of this workspace's administrators contains only one line. As a result when the list is long, it gets out of the visible area.

![image](https://user-images.githubusercontent.com/3414935/27545960-90a802c2-5a91-11e7-88d5-f574cdd3efbc.png)

**Comment by ngodfraind** [comment]
Reproduit.
