### ISSUE TITLE
[PathBundle] Incoherences between condition statuses and actual status in player

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#2581]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

There are some issues that come up when a user (who's not WS admin) runs the a path with conditions. In edit mode the statuses do not correspond with the ones in the player interface. As a result a user cannot access the next step, as he can not validate the required condition.

Edit mode:
![image](https://user-images.githubusercontent.com/3414935/27738897-2079d574-5dad-11e7-818e-eca9a8e76c6f.png)

Player:

![image](https://user-images.githubusercontent.com/3414935/27738921-32010b28-5dad-11e7-8704-a4abaceea44d.png)

**Comment by LaurentGruber** [comment]
ce n'est pas incohérant, ça n'a juste rien avoir.

Les statuts : A faire, Fait et A refaire sont déclaratif pour l'apprenant, c'est lui qui se donne cela.

L'état de l'activité, il s'agit de la réussite ou non d'une activité qui est géré par le système ou par le formateur.

A savoir que les activités vont disparaitre d'ici peu ...

**Comment by ptsavdar** [comment]
D'accord. Ok. Merci Laurent. Du coup les activites existantes elles passent en parcours? Ou elles seront supprimées?

**Comment by LaurentGruber** [comment]
A terme elles seront supprimé, probablement d'abord en soft delete et dans la v11 définitivement.
