### ISSUE TITLE
[ExoBundle] Probleme exporting -> importing a WS containing quizzes

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#2593]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

When a user exports a WS in order to re-import it afterwards and this WS contains quizzes, while the export completes with no error, during import there is the following error:

Uncaught PHP Exception
Exercise : import data are not valid. { { path: /steps/4/items/0, msg: property "data" is missing }, { path: /steps/4/items/0, msg: property "url" is missing }, { path: /steps/4/items/0, msg: instance must match exactly one of the schemas listed in oneOf }, { path: /steps/4/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/4/items/0, msg: property "random" is missing }, { path: /steps/4/items/0, msg: property "multiple" is missing }, { path: /steps/4/items/0, msg: property "choices" is missing }, { path: /steps/4/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/4/items/0/type, msg: should match one element in enum }, { path: /steps/4/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/4/items/0, msg: property "random" is missing }, { path: /steps/4/items/0, msg: property "penalty" is missing }, { path: /steps/4/items/0, msg: property "firstSet" is missing }, { path: /steps/4/items/0, msg: property "secondSet" is missing }, { path: /steps/4/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/4/items/0/type, msg: should match one element in enum }, { path: /steps/4/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/4/items/0, msg: property "items" is missing }, { path: /steps/4/items/0/type, msg: should match one element in enum }, { path: /steps/4/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/4/items/0, msg: property "text" is missing }, { path: /steps/4/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/4/items/0/type, msg: should match one element in enum }, { path: /steps/4/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/4/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/4/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/4/items/0, msg: property "contentType" is missing }, { path: /steps/4/items/0/type, msg: should match one element in enum }, { path: /steps/4/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/4/items/0, msg: property "image" is missing }, { path: /steps/4/items/0, msg: property "pointers" is missing }, { path: /steps/4/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/4/items/0/type, msg: should match one element in enum }, { path: /steps/4/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/4/items/0, msg: property "random" is missing }, { path: /steps/4/items/0, msg: property "penalty" is missing }, { path: /steps/4/items/0, msg: property "sets" is missing }, { path: /steps/4/items/0, msg: property "items" is missing }, { path: /steps/4/items/0/solutions, msg: instance must be of type object }, { path: /steps/4/items/0/type, msg: should match one element in enum }, { path: /steps/4/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/4/items/0, msg: property "random" is missing }, { path: /steps/4/items/0, msg: property "penalty" is missing }, { path: /steps/4/items/0, msg: property "items" is missing }, { path: /steps/4/items/0, msg: property "rows" is missing }, { path: /steps/4/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/4/items/0/type, msg: should match one element in enum }, { path: /steps/4/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/4/items/0/type, msg: should match one element in enum }, { path: /steps/4/items/0, msg: property "mode" is missing }, { path: /steps/4/items/0, msg: property "selections" is missing }, { path: /steps/4/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/4/items/0, msg: property "mode" is missing }, { path: /steps/4/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/4/items/0, msg: property "mode" is missing }, { path: /steps/4/items/0, msg: property "selections" is missing }, { path: /steps/4/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/4/items/0, msg: instance must match exactly one of the schemas listed in oneOf }, { path: /steps/4/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/4/items/0, msg: property "penalty" is missing }, { path: /steps/4/items/0, msg: property "cells" is missing }, { path: /steps/4/items/0, msg: property "rows" is missing }, { path: /steps/4/items/0, msg: property "cols" is missing }, { path: /steps/4/items/0, msg: property "border" is missing }, { path: /steps/4/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/4/items/0/type, msg: should match one element in enum }, { path: /steps/4/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/4/items/0, msg: property "penalty" is missing }, { path: /steps/4/items/0, msg: property "items" is missing }, { path: /steps/4/items/0, msg: property "mode" is missing }, { path: /steps/4/items/0, msg: property "direction" is missing }, { path: /steps/4/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/4/items/0/type, msg: should match one element in enum }, { path: /steps/4/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/4/items/0, msg: property "choices" is missing }, { path: /steps/4/items/0/solutions, msg: number of items should be greater than or equal to 2 }, { path: /steps/4/items/0/type, msg: should match one element in enum }, { path: /steps/4/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/4/items/0, msg: instance must match exactly one of the schemas listed in oneOf }, { path: /steps/6/items/0, msg: property "data" is missing }, { path: /steps/6/items/0, msg: property "url" is missing }, { path: /steps/6/items/0, msg: instance must match exactly one of the schemas listed in oneOf }, { path: /steps/6/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/6/items/0, msg: property "random" is missing }, { path: /steps/6/items/0, msg: property "multiple" is missing }, { path: /steps/6/items/0, msg: property "choices" is missing }, { path: /steps/6/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/6/items/0/type, msg: should match one element in enum }, { path: /steps/6/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/6/items/0, msg: property "random" is missing }, { path: /steps/6/items/0, msg: property "penalty" is missing }, { path: /steps/6/items/0, msg: property "firstSet" is missing }, { path: /steps/6/items/0, msg: property "secondSet" is missing }, { path: /steps/6/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/6/items/0/type, msg: should match one element in enum }, { path: /steps/6/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/6/items/0, msg: property "items" is missing }, { path: /steps/6/items/0/type, msg: should match one element in enum }, { path: /steps/6/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/6/items/0, msg: property "text" is missing }, { path: /steps/6/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/6/items/0/type, msg: should match one element in enum }, { path: /steps/6/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/6/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/6/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/6/items/0, msg: property "contentType" is missing }, { path: /steps/6/items/0/type, msg: should match one element in enum }, { path: /steps/6/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/6/items/0, msg: property "image" is missing }, { path: /steps/6/items/0, msg: property "pointers" is missing }, { path: /steps/6/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/6/items/0/type, msg: should match one element in enum }, { path: /steps/6/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/6/items/0, msg: property "random" is missing }, { path: /steps/6/items/0, msg: property "penalty" is missing }, { path: /steps/6/items/0, msg: property "sets" is missing }, { path: /steps/6/items/0, msg: property "items" is missing }, { path: /steps/6/items/0/solutions, msg: instance must be of type object }, { path: /steps/6/items/0/type, msg: should match one element in enum }, { path: /steps/6/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/6/items/0, msg: property "random" is missing }, { path: /steps/6/items/0, msg: property "penalty" is missing }, { path: /steps/6/items/0, msg: property "items" is missing }, { path: /steps/6/items/0, msg: property "rows" is missing }, { path: /steps/6/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/6/items/0/type, msg: should match one element in enum }, { path: /steps/6/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/6/items/0/type, msg: should match one element in enum }, { path: /steps/6/items/0, msg: property "mode" is missing }, { path: /steps/6/items/0, msg: property "selections" is missing }, { path: /steps/6/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/6/items/0, msg: property "mode" is missing }, { path: /steps/6/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/6/items/0, msg: property "mode" is missing }, { path: /steps/6/items/0, msg: property "selections" is missing }, { path: /steps/6/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/6/items/0, msg: instance must match exactly one of the schemas listed in oneOf }, { path: /steps/6/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/6/items/0, msg: property "penalty" is missing }, { path: /steps/6/items/0, msg: property "cells" is missing }, { path: /steps/6/items/0, msg: property "rows" is missing }, { path: /steps/6/items/0, msg: property "cols" is missing }, { path: /steps/6/items/0, msg: property "border" is missing }, { path: /steps/6/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/6/items/0/type, msg: should match one element in enum }, { path: /steps/6/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/6/items/0, msg: property "penalty" is missing }, { path: /steps/6/items/0, msg: property "items" is missing }, { path: /steps/6/items/0, msg: property "mode" is missing }, { path: /steps/6/items/0, msg: property "direction" is missing }, { path: /steps/6/items/0/solutions, msg: number of items should be greater than or equal to 1 }, { path: /steps/6/items/0/type, msg: should match one element in enum }, { path: /steps/6/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/6/items/0, msg: property "choices" is missing }, { path: /steps/6/items/0/solutions, msg: number of items should be greater than or equal to 2 }, { path: /steps/6/items/0/type, msg: should match one element in enum }, { path: /steps/6/items/0, msg: instance must match all the schemas listed in allOf }, { path: /steps/6/items/0, msg: instance must match exactly one of the schemas listed in oneOf } }
File
/data/www/clarolineconnect/claroline/vendor/claroline/distribution/plugin/exo/Transfer/ExerciseImporter.php
Line
52

I think, the problem is during the quizz export, as it seems that some data won't get exported and thus are afterwards missing from the required schema on import.

**Comment by ngodfraind** [comment]
C'est possible de m'envoyer l'archive ?
N'importe quel quizz pose problème ?
