### ISSUE TITLE
[ExoBundle] Impossible to get back to quiz from docimology page

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#2595]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

When I'm viewing the docimology page of a quiz, it is then impossible to head back to the quiz using the icon on the upper right side. I get the following error:

![image](https://user-images.githubusercontent.com/3414935/27798031-14059ae8-6010-11e7-9be9-4aef49c1eaf9.png)

**Comment by ngodfraind** [comment]
Reproduit
