### ISSUE TITLE
[ExoBundle] Restore roundtrip tests

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#261]
Those tests where skipped by @c5143ba to allow merging the exo branch but they're valuable and reveal 2 weaknesses of the current model:
- the need of a real `score` property (already discussed in #238)
- the inconsistent support/definition of `typeMatch`

**Comment by stefk** [comment]
cc @claroline/ujm, @claroline/innova.

**Comment by Elorfin** [comment]
I move this for 16.12.
The solution is to break the actuel match type into 3 different types.
