### ISSUE TITLE
ExoBundle (Questionbank) : Problème de rendu du tableau dans liste des questions 

### ISSUE THREAD

**Issue by Levis0045** [claroline/Distribution#2629]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.x

1) Le rendu de la liste des questions est décalé vers la droite.
2) Les icônes de filtre des colonnes sont toutes concaténées à l'angle droit du tableau.

**Comment by Levis0045** [comment]
![image](https://user-images.githubusercontent.com/13846122/27958605-3b2f5b60-6324-11e7-8d3a-d49c053d6025.png)

**Comment by LaurentGruber** [comment]
normalement la pr ici : https://github.com/claroline/Distribution/pull/2618 corrige le problème

**Comment by Levis0045** [comment]
C'est juste !

**Comment by Levis0045** [comment]
![](https://user-images.githubusercontent.com/13846122/27958605-3b2f5b60-6324-11e7-8d3a-d49c053d6025.png)

**Comment by Levis0045** [comment]
![image](https://user-images.githubusercontent.com/13846122/27962923-a167c66a-6333-11e7-9fbc-038d78781d0c.png)
