### ISSUE TITLE
PathBundle : sommaire et fullscreen

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#2639]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.5

Dans le parcours en fullscreen, le sommaire ne se replie pas... (test sur firefox)

![capture d ecran de 2017-07-10 09-00-31](https://user-images.githubusercontent.com/5804394/28006181-836c4196-654e-11e7-912b-9bd7b3ce79ad.png)

**Comment by LaurentGruber** [comment]
J'ai toujours le souci même après application du fix, le sommaire ne se replie pas en full screen

**Comment by Elorfin** [comment]
T'as recompilé le thème?

**Comment by LaurentGruber** [comment]
non, en effet, c'était ça... merci
