### ISSUE TITLE
CursusBundle création ou ajout d'une formation dans un cursus ne fonctionne pas

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#2643]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.7

Après avoir crée un cursus, la création ou l'ajout d'une formation ne fonctionne pas.

![image](https://user-images.githubusercontent.com/7293233/28016977-20a6427c-6577-11e7-8f54-f20f486d97fc.png)

**Comment by ngodfraind** [comment]
J'ai reproduis (je crois).

C'est le 'Add training' qui ne fait rien du tout.
