### ISSUE TITLE
Ouverture espace d'activité amène sur ses ressources

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#2647]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master

Bonjour,

A l'ouverture d'un espace d'activité nouvellement créé, j'arrive directement dans les ressources de celui-ci.
Est-il possible de changer ce paramètre afin d'arriver sur l'accueil de cet espace ?
Je n'ai rien trouvé dans les paramètres liés aux espaces, je suis surement passé à coté de quelque chose. 

Je précise qu'avant la refonde du gestionnaire des espaces d'activités, l'ouverture d'un espace amenait sur la page d'accueil.

Merci

**Comment by LaurentGruber** [comment]
Oui dans paramètres > outils
Il faut réordonner les outils en mettant l'accueil en premier

**Comment by l-matt** [comment]
Merci
