### ISSUE TITLE
Improvement : prevent downloading a pdf in the viewer

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#265]
Even when the user has only rights to "read" the PDF, in the viewer, he can do a right click and do a "Save image as" for each slide. Could there be a way to prevent it ? 
For instance like in[ this kind of question](http://stackoverflow.com/questions/10864249/disabling-right-click-context-menu-on-a-html-canvas)   (since this is a canvas)

**Comment by arnaudbey** [comment]
from the moment the client got it on his browser, IMO there's no robust way to prevent him from saving it but I may miss something...

**Comment by ngodfraind** [comment]
The simple fact that the pdf is shown means that he's already downloaded
somewhere. If a user is clever, he probably can go in its browser temporary
files and find it here anyway.

2016-05-11 10:35 GMT+02:00 Arnaud Bey <notifications@github.com>:

> from the moment the client got it on his browser, IMO there's no robust
> way to prevent him from saving it but I may miss something...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Distribution/issues/265#issuecomment-218396392>
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by CPASimUSante** [comment]
I thought the pdf viewer from claroline was converting pdf into canvas images ? That's what i have when i upload a pdf (drag drop) and open it.
If there is actually somewhere the real pdf in the tmp, this is no problem (for the moment) : it has just not to be easy (like right-click on the slide)
