### ISSUE TITLE
[CoreBundle] Cannot create a new Workspace after update to 10.0.4

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#2650]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.4

Each time someone tries to create a new WS the following error occurs:

![image](https://user-images.githubusercontent.com/3414935/28025000-7a39184e-6592-11e7-91a9-aa1dc0ba10bc.png)

**Comment by ngodfraind** [comment]
Do you use a custom model ? I'm unable to reproduce.

**Comment by ngodfraind** [comment]
I had the same issue on our server. I cleaned the PR fixing this issue for me here

https://github.com/claroline/Distribution/pull/2624
