### ISSUE TITLE
Pas de validation de l'inscription dans un espace d'activité pour les comptes déjà créés 

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2667]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.9

Dans un espace d’activité, quand on sélectionne validation de l'inscription dans les paramètres généraux

![image](https://user-images.githubusercontent.com/5484259/28130487-19cf164c-6737-11e7-8ecf-06c77ebd6ade.png)
on pense retrouver tout les demandeur dans l'onglet En attente 
Et bien non ceux qui ont deja un compte sur la plate forme se trouvent immédiatement inscrit à l'espace d'activité en voici 6 que je n'ai pas inscrits ni validés :-(
![image](https://user-images.githubusercontent.com/5484259/28130560-63af4246-6737-11e7-9c4d-407d482e3b83.png)

la logique voudrait que meme ces 6 la soient dnas l'onglet En attente

**Comment by LaurentGruber** [comment]
close for #3085
