### ISSUE TITLE
Non-support du protocole https (protocole hard-codé)

### ISSUE THREAD

**Issue by romaricdrigon** [claroline/Distribution#2679]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 9.0 / 10.0?

Hello,

Lors de l'exécution d'une version 17.01 sur un serveur en HTTPS, dans la console remontent plusieurs erreurs de ressources - surtout des CSS - chargés en HTTP et donc bloqués par le navigateur.

Par exemple dans l'administration, sur la gestion des rôles:
![image](https://user-images.githubusercontent.com/919405/28169194-e03f303c-67e1-11e7-86ec-61b98c8d0708.png)

**Comment by LaurentGruber** [comment]
il y a un paramètre dans le plateforme option pour régler ça normalement

**Comment by romaricdrigon** [comment]
Claroline n'essaie pas aussi de détecter si la requête est en HTTPS?

**Comment by LaurentGruber** [comment]
Je ne pense pas, juste @ngodfraind ?

Mais si vous avez une proposition ou un modèle d'implémentation, on est preneur.

**Comment by romaricdrigon** [comment]
Changer `ssl_enabled` dans `platform_options` a en effet résolu le problème. Merci!
Je ferme le ticket.
