### ISSUE TITLE
Alerte envoi d'information

### ISSUE THREAD

**Issue by romaricdrigon** [claroline/Distribution#2683]
| Q             | A
| ------------- | ---
| Bug report?   | yes?
| Version?      | 9.0

Y a-t-il moyen de désactiver l'alerte "L'envoi d'information est désactivé"?

Le message d'alerte étant dans un élément de taille 100% de la page et en `position: fixed`, il va parfois se superposer et empêcher le clic sur les boutons "close" des modals (sur 80% d'entre elles). C'est gênant.

**Comment by LaurentGruber** [comment]
le plus simple : en acceptant l'envoie d'information.

Sinon à priori en mettant le paramètre suivant :  confirm_send_datas: OK
dans app/config/platform_options.yml ça devrait le faire également et à priori les informations ne seront pas envoyées.
