### ISSUE TITLE
[Exo] Q. association lier plusieurs choix

### ISSUE THREAD

**Issue by govanylakost** [claroline/Distribution#2686]
Question d'association : Il est impossible de lier un choix à plusieurs autres choix proposée côté Edition, alors que c'est bien mentionné comme quoi il est possible de le faire

**Comment by LaurentGruber** [comment]
J'ai splitter en 2 tickets car ce sont deux éléments totalement indépendant, le second ticket est ici : https://github.com/claroline/Distribution/issues/2754
