### ISSUE TITLE
Bug with pdf viewer

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#269]
I generally use Chrome and everything works fine. But i have sevral reports, i've tested and its a problem for us (since corporate computer are constraints to  use IE) : the pdf viewer doesn't work or partially, sometimes, on IE (tested on IE11)
When i open with the pdf viewer : at best i have the first slide (when i click on next pages i have a blank canvas), or just a blank canvas. I can be administrator or Collaborator, it's the same.

When i open the Dev console for IE11 i just have : 

```
Fichier : 1086
Warning: Setting up fake worker.
Warning: Switching TrueType encoding to MacRomanEncoding for ABCDEE+Garamond font
page=1 - getOperatorList: time=302ms, len=219
CSS3114: @font-face a échoué OpenType intégrant une vérification des autorisations. L’autorisation doit être Installable.
Fichier : AAcAkAEvQEAHkMMHkJkHkJgHkIMHkIAHkGMHkF8HkFcHJAgiCCAIHggcCBoIGAgWCBQIEggQCA4IDAgKCAgIBggECAIIAAg.....

```

I've done a simple test : a pdf with just images is readable, but the problem seems to lies in the fonts...
The pdf is generated from a PPT : 

- i had to export as jpg all images 
- then generate a pdf with PDFCreator

This procedure is not usable for anyone but a dev :-(

Claroline version 6.6.4.2
![ie11](https://cloud.githubusercontent.com/assets/14015697/15178993/4de48872-1779-11e6-87a4-31f3b811b75e.jpg)

**Comment by ngodfraind** [comment]
This should be fixed on the monolithic build.
Otherwise you can try to update your platform. It'll update the pdf player aswell afaik. 

It worked on my w7 virtual machine so I'm closing it.
