### ISSUE TITLE
Publication parcours

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2692]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      |10

Quand je veux publier le parcours et que je clique sur le bouton PUBLIER, rien ne se passe...  Pas de message d'erreur non plus et le message "Sauvegardé avec des publications en attente" reste à affiché

**Comment by LaurentGruber** [comment]
Quand je veux publier le parcours et que je clique sur le bouton PUBLIER, rien ne se passe...  Pas de message d'erreur non plus et le message "Sauvegardé avec des publications en attente" reste à affiché

**Comment by Elorfin** [comment]
fixed.
