### ISSUE TITLE
quand on copie un parcours la copie est vide :-(

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2693]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.9
parcours copié
![image](https://user-images.githubusercontent.com/5484259/28412234-cfddc854-6d43-11e7-93c0-fe49f8447315.png)
parcours collé
![image](https://user-images.githubusercontent.com/5484259/28412246-db9dcad6-6d43-11e7-9ec1-ae2a07b92dc3.png)

**Comment by Batier** [comment]
en fait non...
en l'editant jhe retrouve les contenus mais
mais je ne peux pas modifier le parcours ni l'enregistrer
![image](https://user-images.githubusercontent.com/5484259/28414390-b8a0cf3a-6d4b-11e7-8aeb-f73ae9b4298b.png)

**Comment by Batier** [comment]
en fait si...mais c'est super lent

**Comment by ngodfraind** [comment]
Le parcours est grand ?

Sinon pour résoudre les problèmes de performances, le plus simple c'est de nous envoyer la db (sans les logs sinon elle est trop lourde) pour regarder quels sont les requêtes qui sont faites lorsqu'on reproduit le problème.

C'est pas forcément facile/possible à résoudre autrement.

**Comment by Elorfin** [comment]
fixed.
