### ISSUE TITLE
Pour info  : problème de migration de Jessie vers stretch

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#2697]
| Q             | A
| ------------- | ---
| Bug report?   | 
| Version?      | 10.0.11

Suite à la migration vers Debian stable Strech, qui installe MariaDB 10.1 à la place de mysql-server 5.5, l'affichage des espaces de travail (workspaces) ne fonctionne pas et affiche les erreurs suivants dans /var/log/apache2/error.log

[Fri Jul 21 15:09:25.459780 2017] [:error] [pid 2817] [client
217.128.72.135:4047] PHP Fatal error:  Uncaught PDOException:
SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in
/var/www/Claroline/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack
trace:\n#0
/var/www/Claroline/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91):
PDOStatement->execute(NULL)\n#1
/var/www/Claroline/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(828):
Doctrine\\DBAL\\Driver\\PDOStatement->execute()\n#2
/var/www/Claroline/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50):
Doctrine\\DBAL\\Connection->executeQuery('SELECT c0_.id A...', Array,
Array, NULL)\n#3
/var/www/Claroline/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(321):
Doctrine\\ORM\\Query\\Exec\\SingleSelectExecutor->execute(Object(Doctrine\\DBAL\\Connection),
Array, Array)\n#4
/var/www/Claroline/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(969):
Doctrine\\ORM\\Query->_doExecute()\n#5
/var/www/Claroline/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(924):
Doctrine\\ORM\\AbstractQuery->execut in
/var/www/Claroline/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on
line 195, referer:
https://connect.ent-st-joseph-hasparren.fr/admin/open/platform_logs
 
 
 
 
[Fri Jul 21 15:09:51.157158 2017] [:error] [pid 8906] [client
217.128.72.135:4050] PHP Warning:  PDOStatement::execute(): MySQL server
has gone away in
/var/www/Claroline/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php
on line 91, referer:
https://connect.ent-st-joseph-hasparren.fr/workspaces/search
[Fri Jul 21 15:09:51.157285 2017] [:error] [pid 8906] [client
217.128.72.135:4050] PHP Warning:  PDOStatement::execute(): Error
reading result set's header in
/var/www/Claroline/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php
on line 91, referer:
https://connect.ent-st-joseph-hasparren.fr/workspaces/search
[Fri Jul 21 15:09:51.199070 2017] [:error] [pid 8906] [client
217.128.72.135:4050] PHP Fatal error:  Uncaught PDOException:
SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in
/var/www/Claroline/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack
trace:\n#0
/var/www/Claroline/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91):
PDOStatement->execute(NULL)\n#1
/var/www/Claroline/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(828):
Doctrine\\DBAL\\Driver\\PDOStatement->execute()\n#2
/var/www/Claroline/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50):
Doctrine\\DBAL\\Connection->executeQuery('SELECT c0_.id A...', Array,
Array, NULL)\n#3
/var/www/Claroline/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(321):
Doctrine\\ORM\\Query\\Exec\\SingleSelectExecutor->execute(Object(Doctrine\\DBAL\\Connection),
Array, Array)\n#4
/var/www/Claroline/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(969):
Doctrine\\ORM\\Query->_doExecute()\n#5
/var/www/Claroline/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(924):
Doctrine\\ORM\\AbstractQuery->execut in
/var/www/Claroline/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on
line 195, referer:
https://connect.ent-st-joseph-hasparren.fr/workspaces/search

**Comment by Elorfin** [comment]
C'est un problème de conf MySQL, pas de l'application.

Il faut augmenter les valeurs des variables :

wait_timeout
max_allowed_packet

**Comment by Garakotxea** [comment]
Ça n'a rien changé, retour vers la Jessie avec le pb d'affichage à finaliser.
Merci pour votre aide et bon week-end.
