### ISSUE TITLE
Problème d'affichage logo de la plateforme

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#2698]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Bonjour, suite aux dernières maj le logo de la plateforme ne s'affiche plus dans la topbar.
En allant dans paramètres > apparence > choix du logo, aucune image n'est affiché sauf le texte de son attribut alt="", logo 1, logo 2 par exemple.

Un message m'annonçant un problème d’écriture m'a poussé a modifié les permissions/propriétaire du dossier data/aaaaaaaaaaaaaaaaaaa mais rien ne s'affiche pour autant.
De plus à l'upload d'une nouvelle image, celle ci s'envoie correctement sur le serveur mais elle perd son type mime pour se nommer "nom_du_fichier."

Merci

**Comment by Garakotxea** [comment]
Rajouts mineurs:
Si je ne clique pas sur "Aucun logo" le nom de la plateforme s'affiche 2 fois, dont une fois à la place du logo.
Cocher ou décocher "Afficher le nom de la plateforme dans la barre supérieure" ne change rien. Quand on ouvre à nouveau la page la case est à nouveau cochée alors que je l'avais décochée.

**Comment by ngodfraind** [comment]
J'ai déjà vu ce problème (c'est effectivement la maj).

En fait, c'est sans doute un problème de symlink. Ceci dit les nouveaux logos devraient s'afficher correctement si l'upload se passe proprement.

**Comment by l-matt** [comment]
Lors de l'update, un petit message indiquait de supprimer manuellement le repertoire web/data .
Le problème venait effectivement des liens symboliques "themes" et "uploads" présent dans le répertoire "web".
Il suffit de supprimer ces liens et de les recréer en veillant à ce qu'il pointe bien vers files/data/themes et files/data/uploads.

**Comment by Garakotxea** [comment]
Le problème n'existe plus dans la 10.0.21 (sur ma plateforme en tout cas).
