### ISSUE TITLE
Typer les keyword et permettre d'ajouter des options de tolérance d'erreur

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#2716]
Objectif : dans les textes à trou pour les champs libre avoir une option permettant de typer le champ : 

- string
- numérique (seul des nombres sont accepté comme réponse)

- [ ] Si le type est numérique : l’enseignant doit pouvoir définir un intervalle acceptable de réponse (marge erreur en % ou en valeur absolue) 
- [x] Si le type est string avoir la possibilité de rendre la réponse à la question insensible à l'accentuation et insensible à la casse et au espace

**Comment by Batier** [comment]
voila une petite idee de l'ergonomie possible 
![image](https://user-images.githubusercontent.com/5484259/28825760-dcea250a-76c7-11e7-970e-be55b033422b.png)
