### ISSUE TITLE
[QUESTION] Nettoyage base de donnée

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#2723]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master

Bonjour,
Comment nettoyer la base de donnée efficacement? 
Certains users supprimés (username# encore présent dans la bdd) sont par exemple liés aux posts du forum.
Peut-on les supprimer sans crainte?
Quelles sont les autres tables pouvant être vidées ? (tables de log, notifs etc..)
Merci.

**Comment by LaurentGruber** [comment]
Non on ne peut par les supprimer sans risque de casser des accès.

Nous n'avons jamais testé de vider les tables de log et de notifs, ça pourrait créer des effets de bord.

Github est à priori la pour les rapports de bug, les questions on plus leur place sur le forum : http://forum.claroline.net/forum/11/category

**Comment by l-matt** [comment]
Merci
