### ISSUE TITLE
[QUESTION] Widget affichage utilisateurs d'un EA

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#2724]
| Q             | A
| ------------- | ---
| Bug report?   |no
| Version?      | master

Bonjour,
Est-il possible d'afficher les utilisateurs d'un espace d'activité au travers d'un widget sur l'accueil d'un EA par exemple?

**Comment by LaurentGruber** [comment]
non, il n'y a pas de widget pour ça.
Idem, ce genre de question à plus sa place dans le forum : http://forum.claroline.net/forum/11/category (il va être refait bientôt)
