### ISSUE TITLE
Improvement : Add a class (color) for downloadable resource

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#273]
In our resources, some are downloadable, some are not, and they could be all mixed. It would be nice if a (at least) a css class was added to the resource if it is downloadable or not, so that we could add a custom css rule to make the difference (for instance green color - or whatever - for a downloadable resource).
It would also be easier and faster for the manager : at single glance we would now which is which, without having to check one by one, if we forgot one.

**Comment by LaurentGruber** [comment]
ça doit être réfléchis de façon plus global, on a le même genre de demande pour savoir les droits d'éditions ou non, la visibilité aux anonymes, ... 
Donc il faut revoir complètement l'apparence du ressource manager pour répondre ces demandes de façon cohérente ...
