### ISSUE TITLE
TinyMCE : couleur de texte et surlignage

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#2750]
| Q             | A
| ------------- | ---
| Bug report?   | ?
| Version?      | 10.0.11

Bonjour,
Après quelques saisies les boutons de couleur et de surlignages sont devenus inopérants. J'ai du modifier les couleurs depuis le code HTML.
<h4><strong>&nbsp;<span class="js-issue-title">
en 
<h4 class="gh-header-title"><span style="color: #008080;"><strong><span class="js-issue-title">

Bien à vous

**Comment by ngodfraind** [comment]
Bonjour, 

C'est général à la plateforme ? ou c'était dans un tinymce "custom" des exercices ?

**Comment by Garakotxea** [comment]
Bonjour,
En fait c'est sur les pages d'info de la page d'accueil. En dézoomant (90% ou moins) je vois apparaître la palette. Plus l'article est long et plus la palette est basse dans la page et je dois davantage dézoomer.
En revanche je viens d'essayer sur une page d'exos en HTML et dans une question à choix multiples et je n'ai pas de problème ; désolé j'aurais du davantage fouiller avant de poster, ce n'est pas une gêne importante puisque en dézoomant j'accède à la palette et que ça ne semble concerner que la page d'accueil.

Encore désolé, vous pouvez supprimer ce post.
Bien à vous.

Image d'une petit article avec page Firefox à 90%. Pour un long je dois descendre à 70%.
![image](https://user-images.githubusercontent.com/22524770/29037623-a3a4eb22-7ba4-11e7-841d-70c55d9feeb8.png)
