### ISSUE TITLE
Effacer les résultats des exos

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#2756]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 10.0.11

Bonjour,
Est-t-il possible de "purger" la base de données des anciennes compositions ? Ces résultats restent même lorsque les élèves sont supprimés de la plateforme ou qu'ils n'appartiennent plus à ce groupe (changement de classe pou 2017-18).
![image](https://user-images.githubusercontent.com/22524770/29069883-183174f4-7c3d-11e7-88d2-da8d4779a46c.png)
![image](https://user-images.githubusercontent.com/22524770/29070678-af0c9536-7c40-11e7-9ce7-4af287138576.png)

Bien à vous.

**Comment by LaurentGruber** [comment]
Non, il n'y a pas d'option pour le moment, le questionnaire est notamment utilisé pour faire des examens, ce qui entraine une obligation légal de conserver les copies.

**Comment by Garakotxea** [comment]
D'accord, merci bien pour le retour
Bonne journée.

**Comment by Batier** [comment]
Je relance la demande #2975
ce qui n’empêche en rien de garder les réponses d'examens
