### ISSUE TITLE
Users perd ses groupes

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#2762]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Bonjour, 

En modifiant le profil d'un utilisateur via "liste des utilisateurs" et après validation, celui-ci perd tout les groupes auxquels il est associé.

Cordialement

**Comment by LaurentGruber** [comment]
@l-matt Pourriez-vous passer sur la branche 10.x la plus avancé aujourd'hui et nous préciser le numéro de version si vous rencontrez toujours le bug.

**Comment by l-matt** [comment]
Bonsoir,

je redoute un peu cette manipulation car il s'agit de notre serveur de production...
J'essaie en attendant de le faire en local, je vous tiens au courant.
Merci

**Comment by l-matt** [comment]
opération effectuée, je suis sur une 10.0.16, l'utilisateur perd toujours ses groupes après modification de son profil via le gestionnaire d'utilisateurs.

**Comment by LaurentGruber** [comment]
corrigé
