### ISSUE TITLE
[CompetencyBundle] si un exercice est effacé sa référence à la compétence ne l'est pas

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#2777]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10

Associer un exercice à une capacité
Effacer l'exercice
L'exercice est toujours référencé dans le référentiel de compétences et le parcours ne fonctionne donc plus

**Comment by kitan1982** [comment]
Y a-t-il un message d'erreur spécifique ?

**Comment by kitan1982** [comment]
Ok. Ça vient du fait que les exercices ne sont pas vraiment supprimés.
Un "soft delete" est appliqué.
