### ISSUE TITLE
[CoreBundle] Create Angular utilities to manage tinyMCE

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#278]
Add a TinymceConfigService and trustAsHtml filter in the CoreBundle.
- The config service will permit to always have the same config for all TinyMCE fields.
- We need to regularly redefine trustAsHtml (we have the same filter in ExoBundle).

For now, PathBundle / ExoBundle and WebsiteBundle have their own implementation.

@ptsavdar : to respond to what you say on #277, we can use the ES6 compiled code in assetic and so mix ES6 / ES5. 

I remember, we have done that with @ngodfraind when he has shown me how I can use ES6 + webpack for PathBundle. That was a try so only one of the module is in ES6 and the others in ES5 and it doesn't seem to be a problem.

Someone know issues when mixing ES5 and ES5 compiled from ES6 ?

**Comment by stefk** [comment]
I agree, we can use ES6 compiled code in ES5 code. The only thing we must take care of is the size/content of compiled modules. AFAIK all the modules we've built with webpack are completely self-contained (i.e. include the module code + its dependencies: angular, angular-ui, etc.). Obviously if we want to reuse modules in non es6/webpack code, we must make them lighter. But that's a kind of webpack config tweaking we must do anyway.

**Comment by CPASimUSante** [comment]
I'm not sure what sort of config you're talking about : only main general configuration (just the init), or complete configuration with the list of plugins and toolbars ? 
For the latter, i think this part should be kept separated or at least be overridable :
- Some bundle could require less (or more plugins)
- some Claroline instances could be more or less permissive for the editing tools (for instance prevent using text or background color feature...)

So, centralizing the Tinymce code is necessary, but i think it should not be done at the expense of customization.
