### ISSUE TITLE
[SensioInsights] exit() and die() functions should be avoided

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#282]
Corresponding phpmd rule: *design.xml/ExitExpression*

**Comment by stefk** [comment]
All remaining `exit` and `die` calls are now in build scripts, where they're legit. There may be a way to tell sensio insight to ignore certain files/folders, IDK. Postponing to 16.09.

**Comment by Elorfin** [comment]
FYI, you can do it in the configuration of the project.
There is a field when you can write YAML configuration (to exclude dirs, execute scripts before analyze, exclude rules, etc). There is a sample config YAML provided to know what you can do.

**Comment by Elorfin** [comment]
I have updated the configuration in SensioInsight to exclude : 
- /merge.php
- /import.php
- /dev/Resources/travis/*
- all Tests Folder
- all Doctrine Migrations folders

So I think we can close the issue.

**Comment by stefk** [comment]
Thanks.
