### ISSUE TITLE
Récursivité de la publication se limite à un niveau

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#2831]
| Q             | A
| ------------- | ---
| Bug report?   |
| Version?      | 10.0.21

Bonjour,

Pardon si le retour a déjà été effectué mais je ne l'ai pas trouvé j'ai juste retrouvé celui d'avril (Récursivité de la publication #2129).

J'avais remarqué le problème dès la 10.0.11 mais sans le remonter vu tout le travail que vous avez déjà. Toutefois cela est apparu vraiment gênant et source de problème (épreuve d'examen incomplètement dépubliée).

Il y-a-t-il eu un fix pour ce problème ?
Bien à vous.

**Comment by ngodfraind** [comment]
Okay, quelle manip faites vous pour dépublier ? (il y a plusieurs moyen de le faire et le fix ne les prend sans doute pas toute en compte).

**Comment by Garakotxea** [comment]
Moi je procède par dossier mais d'autres collègues gèrent toutes les ressources depuis l'espace d'activité et cachent les widget évaluations. Ils bloquent l'accès aux ressources donc. Moi je les laisse à disposition.
Par dossier
![image](https://user-images.githubusercontent.com/22524770/29783102-65793052-8c1f-11e7-8415-b749d1240640.png)

Depuis les paramètres de l'EA pour certains collègues.
![image](https://user-images.githubusercontent.com/22524770/29783170-b8ea7dfe-8c1f-11e7-8b0b-3fc25169890c.png)

**Comment by Garakotxea** [comment]
Bonsoir Nicolas,
Avez-vous trouvé une solution ?
Bien à vous

**Comment by LaurentGruber** [comment]
des fix ont été mis dans la version .28 .29, il faudrait appliquer les mises à jour et retester

**Comment by Garakotxea** [comment]
OK merci.
Une question : pour des MAJ intermédiaire dois-je relancer toute l'installation* ou existe-t-il un update simple ?

*Installation complète
sudo git checkout .
sudo git fetch
sudo git checkout 10.x
sudo git pull origin 10.x
composer update --prefer-source

$ npm install && npm run bower && npm run themes &&  npm run webpack

sudo php app/console claroline:update
sudo php app/console assets:install
sudo rm -rf app/cache/* && php app/console claroline:maintenance:disable

**Comment by LaurentGruber** [comment]
tout dépend de quel version on vient, et de ce qu'il y a dans la maj, pour être sur le mieux c'est de faire la procédure complète ...

**Comment by ngodfraind** [comment]
https://github.com/claroline/Distribution/pull/2881

**Comment by Garakotxea** [comment]
OK, merci. Je tenterai la MAJ.
