### ISSUE TITLE
[ExoBundle] Impossible de terminer un exercice si aucune bonne réponse n'est cochée par le répondant

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#2840]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.x

Le répondant ne peut pas terminer sa session de réponse s'il n'a pas répondu juste à au moins une question de l'exercice, le clic sur "Terminer" à la fin ne redirige alors pas sur la page de fin de l'exercice et aucun feedback ne lui est envoyé. Si on reclic alors sur "Terminer", une erreur "forbidden" est levée car la session de réponse a en fait été close de manière silencieuse.

Pour reproduire le  problème: 
- créer un exercice avec une ou plusieurs questions (je n'ai pas testé tous les types de question, mais le problème impact au moins les questions à choix simple/multiple, trous et associations)
- lancer une session de réponse (via 'répondre' ou 'tester', peu importe)
- ne saisir que des réponses fausses (choix faux, texte non attendu dans un trou etc)
ou
- ne rien répondre du tout
- le clic sur le bouton "Terminer" ne redirige pas vers la page de fin de l'exercice et semble visuellement ne rien faire.

**Comment by ngodfraind** [comment]
Est-ce tjrs d'actu ? Je n'ai pas réussi à reproduire.

**Comment by LaurentGruber** [comment]
non reproduit sur 10.5.0

**Comment by nicolasjacquemet** [comment]
pas réussi à réitérer non plus en 10.5.0, c'était probablement lié aux anciens problèmes d'affichage de la page de fin qui ont été corrigé depuis
