### ISSUE TITLE
Invitation à un événement [événement non trouvé]

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#2843]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Bonjour, 
Suite à la création et à l'invitation à un événement depuis l'agenda, je reçois correctement le mail intitulé "invitation à un événement" mais en cliquant sur une des réponses proposées, je tombe sur ce message d'erreur : "L'invitation à l'évènement n'a pas été trouvée. Il a peut-être été modifié ou supprimé. " 

Est-ce une erreur de ma part ou y a t'il une manipulation parallèle à effectuer ?
Merci

**Comment by LaurentGruber** [comment]
Bonsoir,
Les questions doivent être posé sur le forum afin que tout le monde en profite. Il a été migré et les inscriptions sont à nouveau publique. Je vous invite donc à poser votre question sur forum.claroline.com et le cas échéant, s'il y a un bug à faire un ticket ici.
