### ISSUE TITLE
quand j'importe un espace d'activité...les droits ne sont pas attribués

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2847]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.9

personne peut rentrer dans cet espace...meme  pas le créateur :-(

![image](https://user-images.githubusercontent.com/5484259/29858543-2bff54f6-8d5e-11e7-9663-c62187bb4911.png)
alors qu'au niveau du gestionnaire d'espace d'activité les droit sont bons
![image](https://user-images.githubusercontent.com/5484259/29858590-62df25e6-8d5e-11e7-8556-c38e8456e84a.png)

**Comment by ngodfraind** [comment]
Dans un cas comme celui là il nous faudrait les logs d'erreurs je pense (app/logs/prod.log) s'il y a quelque chose.

Sinon en mode de dev il donne la stacktrace.
