### ISSUE TITLE
erreur 500 sur affichage des ressources dans un espace d'activité

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#2852]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.23

Lorsqu'un utilisateur, qui n'est pas gestionnaire d'un espace d'activité essaye d'afficher les ressources de cet espace, il obtient l'erreur suivante :

Uncaught PHP Exception
Type error: Argument 1 passed to ClarolineCoreBundleManagerResourceManager::getResourceFromNode() must be an instance of ClarolineCoreBundleEntityResourceResourceNode, null given, called in /home/bimgame/www/vendor/claroline/distribution/main/core/Listener/Exception/OpenResourceListener.php on line 55
File
/home/bimgame/www/vendor/claroline/distribution/main/core/Manager/ResourceManager.php
Line
1533
HTTP code
500

**Comment by ngodfraind** [comment]
Je me demande si on ne l'a pas corrigé il y a peu (genre vendredi).

**Comment by LaurentGruber** [comment]
déjà corrigé, je fais la maj bientôt
