### ISSUE TITLE
erreur 500 sur affichage d'un pdf dans un espace d'activité

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#2853]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.23

Uncaught PHP Exception
Attempted to call an undefined method named "getResources" of class "ClarolineCoreBundleEntityResourceResourceNode". Did you mean to call "getResourceType"?
File
/home/bimgame/www/vendor/claroline/distribution/main/core/Library/Security/Voter/ResourceVoter.php
Line
444
HTTP code
500

**Comment by LaurentGruber** [comment]
déjà corrigé, je fais la maj d'ici demain
