### ISSUE TITLE
les permissions appliquées à un onglet dans un modèle d'espace ne sont pas reproduites lors de la création d'une session de formation

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#2863]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.27

J'ai crée un modèle d'espace d'activité. Sur l'accueil de cet espace, j'ai crée des onglets avec des permissions d'accès restreintes pour certains d'entre eux.
Lorsque je crée une session à partir de la formation utilisant ce modèle, les permissions sur les onglets ne sont pas reproduites dans l'espace de la session.

**Comment by ngodfraind** [comment]
Je regarde tout de suite.
J'ai pu reproduire. Il y a moyen de se dépatouiller en rajoutant le role collaborator manuellement mais il aurait du le faire de manière automatique.
