### ISSUE TITLE
Automate update of claroline/Claroline

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#287]
Currently each time this repo is updated, we have to update manually the dependencies of claroline/Claroline. Problem:
- it's boring/time-consuming
- we don't do it regularly

As a result, the main repo isn't always up-to-date with the last developements of the distribution...

We should find a way to automate the process somehow. For example, on each merge into the master branch of the distribution, we could have a script/hook which:

- creates a branch on claroline/Claroline, with updated dependencies
- triggers a build (that build should be more complete than now, i.e. include tests, etc.)
- automatically merges the branch if the build is successful

A similar process will be helpful when we'll be releasing stable versions (on each tag, generate a release archive, etc.).

**Comment by ngodfraind** [comment]
@stefk 
Can I close this issue ? It looks like it works pretty well now !

**Comment by stefk** [comment]
Yep, closing.
