### ISSUE TITLE
[CoreBundle] Modification de l'email impossible

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#2874]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.29

Administration
Gestion des utilisateurs
Modification d'un utilisateur
Si l'identifiant et l'email sont identiques
On ne peut plus changer son email
Message : "L'identifiant test2@test.be est déjà utilisé"

**Comment by LaurentGruber** [comment]
normalement ça devrait être impossible de mettre un identifiant identique au mail ...

**Comment by clarophil** [comment]
je ne vois pas pourquoi c'est un problème ?

**Comment by LaurentGruber** [comment]
parce qu'on peut s'identifier soit avec le user, soit avec le mail (soit avec le code admin)... donc ça n'a aucun sens de faire ça et ce n'est pas prévu pour

**Comment by clarophil** [comment]
Jusqu'à présent c'était possible et chez nous cela posera un problème car l'authentification O365 utilise l'adresse email et donc pour utiliser le sso, on doit la mettre aussi en tant que login.

**Comment by clarophil** [comment]
Résolu
