### ISSUE TITLE
Bug when deleting a Path widget

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#288]
Tested on a monolithic build (Distribution bundle), 
I've created a path, and created a Path widget.

When i'm trying to remove that widget i have this error : 

`[Syntax Error] line 0, col 98: Error: Expected Doctrine\ORM\Query\Lexer::T_EQUALS, got 'whtc'
500 Internal Server Error - QueryException
1 linked Exception: QueryException »

[2/2] QueryException: [Syntax Error] line 0, col 98: Error: Expected Doctrine\ORM\Query\Lexer::T_EQUALS, got 'whtc'   +
[1/2] QueryException: 
UPDATE Claroline\CoreBundle\Entity\Widget\WidgetHomeTabConfig whtc
LEFT JOIN whtc.widgetInstance instance
JOIN instance.widget widget
LEFT JOIN widget.plugin plugin

SET whtc.widgetOrder = whtc.widgetOrder - 1
WHERE whtc.homeTab = :homeTab AND 
(CONCAT(plugin.vendorName, plugin.bundleName) IN (:bundles)
OR widget.plugin is NULL)

AND whtc.user = :user
AND whtc.workspace IS NULL
AND whtc.widgetOrder > :widgetOrder`

**Comment by stefk** [comment]
I have the following error instead:

> No alias was set before invoking getRootAlias().

This might be related to @4757b85863e9. I'm on it.

**Comment by stefk** [comment]
@ngodfraind, #125 broke widget suppression. You can't use joins in update statements. See:
- https://groups.google.com/forum/#!topic/doctrine-user/OaK0FrUItE8
- http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#statements
