### ISSUE TITLE
[ExoBundle] Le rôle par défaut "gestionnaire" ne donne pas tous les droits sur les exercices

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#2887]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.x

Un utilisateur inscrit au rôle par défaut "Gestionnaire" n'a que des droits en lecture sur les exercices (dont il n'est pas le créateur), il n'a accès à aucune option d'édition à l'intérieur de la ressource.

Reproduire:
Inscrire un utilisateur au profil par défaut Gestionnaire, puis ensuite lui faire ouvrir un exercice dont il n'est pas le créateur, il n'aura accès à l'exercice qu'en lecture et pas aux outils d'édition:

![image](https://user-images.githubusercontent.com/3415139/30153480-16dcdf76-93b7-11e7-9fa8-b2eaefe65702.png)

Inscrire cet utilisateur à un rôle personnalisé avec des droits d'édition sur les exercices contourne le problème.

**Comment by ngodfraind** [comment]
Reproduit
