### ISSUE TITLE
Admin should be able to change the icons for resources

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#289]
Maybe a new feature, surely an enhancement : 
Having the possibity, at the platform level (in an admin menu), to change the icons set by default by the resources. Since there will never be a "perfect" set of icons (corresponding to different taste "sensibilties" and platform orientations), it would be nice if the admin of a platform had the possibility to choose and set the icons for each resource.
The current possibility to change the icon for a specific resource should also remain of course.

**Comment by LaurentGruber** [comment]
Done
