### ISSUE TITLE
On ne peut pas Désinscrire un utilisateur d'un espace d’activité ...

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2893]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.9

j'ai une liste de participant à mon espace d'activité
je veux en supprimer...
je n'ai pas de fonction pour le faire

![image](https://user-images.githubusercontent.com/5484259/30172269-a8fc63ee-93f4-11e7-8308-bfaba3cedddc.png)

**Comment by LaurentGruber** [comment]
il faut cliquer sur la croix à coté du rôle, une fois qu'il n'a plus aucun rôle il est supprimé ...

**Comment by Batier** [comment]
J'en ai 200 à supprimer... il faut que je clic 400 fois!
