### ISSUE TITLE
PB COULEUR MENU HAUT sur CC 10.031

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#2899]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?     CC 10.031

Bonjour,
La couleur choisie est masquée en grande partie par une autre couleur noire. voir PJ
![capture 2017-09-08 a 12 02 00](https://user-images.githubusercontent.com/21193255/30207420-c0dfbace-948f-11e7-97d4-1095debbe148.jpg)

**Comment by LaurentGruber** [comment]
La couleur noir vient du thème lui même. Pour le modifier il faut créer un nouveau thème ...
