### ISSUE TITLE
Logos are not found in admin/parameters/appearance

### ISSUE THREAD

**Issue by ChMat** [claroline/Distribution#2904]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.23

In the Appearance customization form in the admin, the form should display approx. 10 Claroline Connect logos. I don't see where they are coming from.
And the upload form does not look to be uploading anything.

Is it just a matter of write rights that do not trigger an error?

**Comment by LaurentGruber** [comment]
il faut vérifier que les liens symbolique sont correct ...
web/data doit pointer vers ../files/data/
web/themes vers ../files/data/themes
web/uploads vers ../files/data/uploads (c'est probablement celui ci le problème)

**Comment by ChMat** [comment]
C'est bien ça. J'avais des liens symboliques qui étaient créés automatiquement et ils bouclaient sur eux-mêmes (pour `themes` si mes souvenirs sont exacts).

Comme je l'ai constaté en prod, j'ai fait la correction à la main en croisant les doigts pour la prochaine mise à jour.

**Comment by ChMat** [comment]
Ces liens symboliques étaient créés par la commande `npm run themes` si ma mémoire ne me joue pas des tours.
