### ISSUE TITLE
Only latest migration version is inserted into history table

### ISSUE THREAD

**Issue by ChMat** [claroline/Distribution#2905]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.x

When executing a `php app/console claroline:update --env=prod` with a clean repo on branch 10.x, doctrine migrations are executed but only the latest version reference is added into the `doctrine_clarolinecorebundle_versions` table (and other tables as well).

This leads to MySQL errors and hangs the update process.

**Comment by LaurentGruber** [comment]
je n'arrive pas à reproduire, quels sont les erreurs mysql ?

**Comment by ChMat** [comment]
Les erreurs MySQL correspondaient à des colonnes ou à des tables créées par une des migrations doctrine mais dont l'identifiant n'était pas dans la table `doctrine_clarolinecorebundle_versions`.

Peut-être un problème lié à la mise à jour chaotique de Claroline que j'ai tentée avec @ngodfraind dernièrement.
