### ISSUE TITLE
Pb - insertion fichier image PNG JPG

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#2908]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?   10.1.0   

Bonjour,
Impossible d'injecter un fichier image dans les ressources.
Même problème pour changer le logo dans Apparence.
Les autres formats comme PDF et mp4 par exemple passent très bien.

**Comment by LaurentGruber** [comment]
impossible de reproduire avec ces infos ...
Il y a un log d'erreur ? quelque chose dans la console ?
Comment peut-on reproduire ?

**Comment by greg49** [comment]
Rappelez moi où se situe le fichier LOG ?
La console ?

**Comment by greg49** [comment]
bonjour Laurent,
dans la console Oops ! voici le message lorsque l'on essaie de publier un logo en PNG :
Pour info : J'ai essayé sur une autre plateforme et ça fonctionne avec le même fichier

Uncaught PHP Exception
Unable to write in the "/var/www/clients/client1/web23/web/claroline-16.09/app/../files/data/aaaaaaaaaaaaaaaaaaaa" directory
File
/var/www/clients/client1/web23/web/claroline-16.09/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/File/File.php
Line
113
URL
http://ourss.isrpp-formation.com/claroline-16.09/web/admin/parameters/appearance
Referer
http://ourss.isrpp-formation.com/claroline-16.09/web/admin/parameters/appearance
HTTP code
500

**Comment by LaurentGruber** [comment]
le message d'erreur le dit : Unable to write in the "/var/www/clients/client1/web23/web/claroline-16.09/app/../files/data/aaaaaaaaaaaaaaaaaaaa
il y a un souci de droit dans files/data/
le serveur web doit pouvoir y écrire...

**Comment by greg49** [comment]
oui pourtant j'ai fait : sudo chmod -R 777 app

**Comment by LaurentGruber** [comment]
ce n'est pas app mais files ...

**Comment by greg49** [comment]
Ok super c'est mieux et ça fonctionne.

Par contre, on ne peut pas supprimer les anciens logo. Voici le message 

![capture 2017-09-13 a 10 51 58](https://user-images.githubusercontent.com/21193255/30368559-cd1540c6-9871-11e7-98ce-40f79d5a9717.jpg)
