### ISSUE TITLE
User can't upload if no personnal workspace

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#2914]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      |  10.0.29

Utilisateur n'ayant pas de workspace personnel
Ajouter un widget texte
Télécharger un image à partir de l'ordianteur

Erreur 
Uncaught PHP Exception 
Type error: Argument 1 passed to ClarolineCoreBundleManagerRightsManager::isManager() must be an instance of ClarolineCoreBundleEntityResourceResourceNode, null given, called in /home/hevinci/www/vendor/claroline/distribution/main/core/Library/Security/Voter/ResourceVoter.php on line 455 
________________________________________
File 
/home/hevinci/www/vendor/claroline/distribution/main/core/Manager/RightsManager.php 
________________________________________
Line 
726 
________________________________________
URL 
http://claco.vinci.be/file/tinymce/upload/undefined 
________________________________________
Referer 
http://claco.vinci.be/workspaces/131/open/tool/home 
________________________________________
HTTP code 
500

**Comment by ngodfraind** [comment]
Reproduit

**Comment by ngodfraind** [comment]
https://github.com/claroline/Distribution/pull/2958
