### ISSUE TITLE
message d'erreur à l'entrée sur le référentiel de compétence

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#2919]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.1.0
Après avoir cliqué sur l'entrée référentiel de compétence dans le menu d'administration. Nous avons l'erreur suivante 

Uncaught PHP Exception
An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.description AS description_3, t0.resourceCount AS resourceCount_4, t0.lft AS lft_5, t0.lvl AS lvl_6, t0.rgt AS rgt_7, t0.root AS root_8, t0.scale_id AS scale_id_9, t0.parent_id AS parent_id_10 FROM hevinci_competency t0 WHERE t0.parent_id IS NULL': SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.resourceCount' in 'field list'
File
/home/egreta/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
Line
71
URL
https://egreta.claroline.com/admin/open/competencies
Referer
https://egreta.claroline.com/desktop/tool/open/dashboard
HTTP code
500

**Comment by LaurentGruber** [comment]
solved by replay migration
