### ISSUE TITLE
Questionnaire : PB au niveau des droits

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#2927]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?     10.1

Bonjour,
il semble qu'il y ait un problème au niveau des droits pour les quiz.
Dans un WS nous avons créé un rôle auquel nous autorisons une simple Ouverture du Quiz.
Pb : en affichant la page du rôle, on s'aperçoit que la personne a accès à tout càd à l'éditeur de questions, et au reste des fonctions. Voici 2 copies d'écran pour compléter mes dires.
![capture 2017-09-15 a 17 14 26](https://user-images.githubusercontent.com/21193255/30490222-9d880054-9a39-11e7-87bd-0f5bf0e2b0a1.jpg)
![capture 2017-09-15 a 17 15 01](https://user-images.githubusercontent.com/21193255/30490245-b04f9f80-9a39-11e7-9a03-c2bccc796863.jpg)

**Comment by ngodfraind** [comment]
Je me demande si c'est n'est pas un bug lié à l'impersonation car... le propriétaire a toujours le droit. Or, en se connectant avec un role particulier, le propriétaire ne change pas. Mais c'est une bonne remarque.

**Comment by greg49** [comment]
Oui effectivement, en se connectant avec un autre compte utilisateur, tout va  bien... Merci Bon WE

**Comment by Garakotxea** [comment]
J'avais déjà remarqué ce problème de droits dans Claroline 1.x et du coup je créé pour chaque enseignant qui le désire un élève test personnel. Ainsi on est sûr des droits, on voit les agendas, etc.
