### ISSUE TITLE
Echec passage de 10.0.21 à 10.1.0 au moment du php app/console claroline:update

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#2928]
| Q             | A
| ------------- | ---
| Bug report?   | question
| Version?      | 10.0.21

Bonjour,
La MAJ bloque au moment de l'update
php app/console claroline:update

J'ai le message suivant:
[Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
  You have requested a non-existent parameter "database_version".

Avez-vous une piste ?
Bien à vous

**Comment by Garakotxea** [comment]
Deuxième essai même erreur. MAJ impossible.

J'ai eu ce message et renommeé themes en themesold pour poursuivre.
_sudo git pull origin 10.x
Depuis https://github.com/claroline/Claroline
 branch            10.x       -> FETCH_HEAD
Mise à jour 0f5843a..bb3bcac
error: The following untracked working tree files would be overwritten by merge:
        web/themes
Please move or remove them before you can merge._

J'ai eu un problème de path lors de thèmes WEB.
_npm run themes

> claroline@1.0.0 themes /var/www/Claroline
> node vendor/claroline/distribution/main/core/Resources/server/themes/bin build

Run `build` command with **cache**.
Theme path (-t) is required._

**Comment by Elorfin** [comment]
Bonjour,

1. il faut ajouter `database_version` dans `app/config/parameters.yml`. La valeur doit être la version de votre MySQL (un `mysql -v` dans un terminal permet de savoir quoi mettre).

2. Il semblerait que vous n'ayez pas mis à jour claroline/Claroline. Un `git pull` à la racine du projet devrait vous ramener les bons scripts.

**Comment by Garakotxea** [comment]
Bonjour et merci pour le retour
1. Ma version de BD est mysql  Ver 14.14 Distrib 5.5.57 donc j'écris _database_version 14.14_ à priori
2. Je ne comprends pas votre retour, je suis allé chercher la branche comme habituellement mais les messages du commentaires 2 concernant les thèmes sont nouveaux.

Les commandes git que je passe pour chaque mise à jour, faut-il les modifier ?
git checkout .
git fetch
git checkout 10.x
git pull origin 10.x

**Comment by Elorfin** [comment]
Non il faut mettre `5.5`. Le 14 doit correspondre à la version de votre système (il n'y a pas de MySQL 14).

Les commandes que vous faites habituellement, je penses que vous les faites dans le dossier : 

`VOTRE_PROJET/vendor/claroline/distribution`

(qui correspond au repo https://github.com/claroline/Distribution)

Là il faut faire les même commandes mais dans le dossier :

`VOTRE_PROJET/`

(qui correspond au repo https://github.com/claroline/Claroline)

La nouvelle version de mise à jour des thèmes nécessite des changements dans les scripts de l'application symfony.

**Comment by Garakotxea** [comment]
1. Oups, la boulette :) je le sais en plus :)
2 . je me place toujours dans @claroline:/var/www/Claroline pour lancer toutes les commandes. Je ne peux pas monter plus haut ?

Je ne lance rien depuis @claroline:/var/www/Claroline/vendor/claroline/distribution

**Comment by Garakotxea** [comment]
Ok, j'ai fait un mv themes themesold pour éviter de le supprimer donc ça allait. Merci pour l'info je n'hésiterai plus à le supprimer maintenant

Vous avez trouvé l'erreur je pense car j'ai fait un npm install comme pour les MAJ précédentes. Je vous mets toutes les commandes passées habituellement ci-dessous. J'ai donc ce npm install. Les autres npm sont bons ?
git checkout .
git fetch
git checkout 10.x
git pull origin 10.x

composer update --prefer-source
**npm install** && npm run bower && npm run themes && npm run webpack. 
sudo php app/console claroline:update
sudo php app/console assets:install
sudo rm -rf app/cache/* && php app/console claroline:maintenance:disable

**Comment by Elorfin** [comment]
Oui c'est bon. 
Vous aviez planté à cause de git sur `git checkout 10.x`. Le mv des thèmes a corrigé le problème.

**Comment by Elorfin** [comment]
> npm install && npm run bower && npm run themes && npm run webpack.
sudo php app/console claroline:update

Plus de `npm run themes` dans cette version. 
Maintenant, la commande est lancée par `php app/console claroline:update`

**Comment by Garakotxea** [comment]
Donc si je prépare la liste de commandes cela ferait dans l'ordre de passage des commandes (nouveauté en gras)?

git checkout .
git fetch
git checkout 10.x
git pull origin 10.x

composer update --prefer-source

**composer install
npm run bower && npm run webpack.**

sudo php app/console claroline:update
sudo php app/console assets:install
sudo rm -rf app/cache/* && php app/console claroline:maintenance:disable

**Comment by Elorfin** [comment]
En fait c'est : 

```
git checkout .
git fetch
git checkout 10.x
git pull origin 10.x

composer sync <-- s'occupe de tout pour vous ;)
```

**Comment by Garakotxea** [comment]
Merci infiniment, je tenterai à nouveau vendredi prochain.
Je vous ferai un retour même si ça se passe bien.
Bon week-end et encore merci.
