### ISSUE TITLE
CEB

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#2951]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.21

See attached picture:

-    Questions don't appear: replaced by "null".
-     weird character before the bullets

![ceb](https://user-images.githubusercontent.com/14308826/30644067-730bf606-9e11-11e7-8775-efcb3f592920.PNG)

**Comment by LaurentGruber** [comment]
déjà corrigé
