### ISSUE TITLE
Can't add user

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#2952]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.21

I can't add users to a workspace as shown on the picture. The click on "Ajouter" doesn't work.

![bug_add_user](https://user-images.githubusercontent.com/14308826/30644139-b9a896fa-9e11-11e7-89db-ac84600a722a.PNG)

**Comment by LaurentGruber** [comment]
déjà corrigé (il n'y pas de rôle lié au ws, un updater le fix)
