### ISSUE TITLE
"Null" in questions

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#2955]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.21

The indication "null" appears before the questions in learning path as shown in the picture below.

Is it necessary to upgrade the Platform ?

![bug_null](https://user-images.githubusercontent.com/14308826/30686108-766f9e1e-9eb7-11e7-9dc1-559eee1e07d2.PNG)

**Comment by LaurentGruber** [comment]
déjà corrigé

**Comment by om64** [comment]
J'ai quand même encore ceci... 

![bug_null_2](https://user-images.githubusercontent.com/14308826/30703155-2e0485b2-9eef-11e7-8820-07c3c64036b7.PNG)

**Comment by LaurentGruber** [comment]
il faut mettre la plateforme à jour, c'est corrigé sur la 10.x

**Comment by om64** [comment]
Tu peux faire ça pour CEB et IEJN ? Déjà un grand merci !
