### ISSUE TITLE
[ExoBundle] Crashs lors de la génération de la docimologie d'un exercice

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#2957]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.2.3

La génération de la docimologie d'un exercice crash lorsque:

- l'exercice contient une question ouverte:
![docimo_free](https://user-images.githubusercontent.com/3415139/30695388-490ae2be-9ed8-11e7-8f59-84baab3c01ac.png)

- l'exercice contient un contenu de type texte/image/video/audio:
![docimo_text](https://user-images.githubusercontent.com/3415139/30695373-3d44f9ce-9ed8-11e7-8688-fdb5747f7e23.png)

**Comment by ptsavdar** [comment]
En essayant de resoudre ca rapidement j'ai change la ligne en question (368) en:
```
if ($corrected instanceof CorrectedAnswer && count($corrected->getMissing()) === 0 && count($corrected->getUnexpected()) === 0) {
```

Mais après j'ai un pb JS:


![image](https://user-images.githubusercontent.com/3414935/30696277-5badc0dc-9edb-11e7-93df-ba0309489b0b.png)

**Comment by ngodfraind** [comment]
Avec la question ouverte, j'ai eu ça:
 
![divisionby0](https://user-images.githubusercontent.com/1397430/31392640-13e5dd6c-adda-11e7-883d-c53b4fc57d7e.png)

C'est beau.

**Comment by ngodfraind** [comment]
No registered question handler for mime "text/html" reproduit
