### ISSUE TITLE
impossible de rattacher une compétence à une ressource URL

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#2959]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.1.0

je souhaite rattacher une compétence à la ressource URL mais ça ne fonctionne pas 

Uncaught PHP Exception
An exception occurred while executing 'SELECT h0_.id AS id_0, h0_.name AS name_1, h0_.minResourceCount AS minResourceCount_2, h0_.resourceCount AS resourceCount_3, h1_.id AS id_4, h2_.id AS id_5, h2_.name AS name_6, h2_.description AS description_7, h2_.resourceCount AS resourceCount_8, h2_.lft AS lft_9, h2_.lvl AS lvl_10, h2_.rgt AS rgt_11, h2_.root AS root_12, h3_.id AS id_13, h3_.name AS name_14, h3_.value AS value_15, h1_.competency_id AS competency_id_16, h1_.ability_id AS ability_id_17, h1_.level_id AS level_id_18, h2_.scale_id AS scale_id_19, h2_.parent_id AS parent_id_20, h3_.scale_id AS scale_id_21 FROM hevinci_ability h0_ INNER JOIN hevinci_ability_resource h5_ ON h0_.id = h5_.ability_id INNER JOIN claro_resource_node c4_ ON c4_.id = h5_.resourcenode_id INNER JOIN hevinci_competency_ability h1_ ON h0_.id = h1_.ability_id INNER JOIN hevinci_competency h2_ ON h1_.competency_id = h2_.id INNER JOIN hevinci_level h3_ ON h1_.level_id = h3_.id WHERE c4_.id = ?' with params [10430]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'h0_.minResourceCount' in 'field list'
File
/home/egreta/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
Line
71
URL
https://egreta.claroline.com/resource/custom/manage_competencies/10430
Referer
https://egreta.claroline.com/workspaces/357/open/tool/resource_manager
HTTP code
500

**Comment by LaurentGruber** [comment]
résolu en rejouant les migrations
