### ISSUE TITLE
Toutes les messages ont la même date

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2962]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      |10.1.0
Du coup j'ai eu un choc de voir Nicolas parler de la version 5.1.15 en cette fin de mois d'aout!

![image](https://user-images.githubusercontent.com/5484259/30704144-0d1c5d40-9ef2-11e7-987e-19ee8eedd2ce.png)

**Comment by LaurentGruber** [comment]
c'est du à la migration de serveur, je ne sais plus le changer ...
