### ISSUE TITLE
erreur 500 sur tentative de modification des droits d'une ressource

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#2963]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.1.0

Sur l'instance egreta, le compte utilisateur N° 39 provoque une erreur lorsqu'il essaye de modifier les droits d'une ressource de type questionnaire.
Je ne rencontre pas ce problème avec mon compte administrateur.

Dans la liste des ressources, clic sur la ressource pour choisir l'option Editer les droits
Uncaught PHP Exception
The file could not be accessed
File
/home/egreta/www/vendor/claroline/distribution/main/core/Controller/ResourceRightsController.php
Line
402
URL
https://egreta.claroline.com/resource/10435/rights/form/role
Referer
https://egreta.claroline.com/workspaces/360/open/tool/resource_manager
HTTP code
500

**Comment by ngodfraind** [comment]
Reproduit.

**Comment by ngodfraind** [comment]
J'ai patché en vitesse sur egreta, mais c'est juste pour dépanner. Je corrige proprement maintenant.

**Comment by flow39** [comment]
Apparemment, le patch sur l'instance egreta ne fonctionne pas. Si vous avez la possibilité de faire une nouvelle correction cela nous aiderait. Merci.

**Comment by LaurentGruber** [comment]
@flow39 le problème est toujours là ?

**Comment by flow39** [comment]
A priori c'est réglé
