### ISSUE TITLE
Erreur sur réponse à un questionnaire

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#2964]
| Q                 | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.1.0

Quand j'essaye de pratiquer le questionnaire (ressource n° 10435), j'ai le message d'erreur suivant 

<img width="960" alt="sans titre" src="https://user-images.githubusercontent.com/7293233/30705179-10086cd0-9ef5-11e7-8a43-824ea77c7cbd.png">

**Comment by LaurentGruber** [comment]
corrigé
