### ISSUE TITLE
Vue liste le point rouge porte confusion [Ergonomie]

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2968]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.2.3

Soucis de cohérence d'interface gestionnaire de ressource en vue liste
seul le titre de la ressource non publiée est grisé , pas son icone
et le point rouge semblerai donc indiquer que la ressource n'est pas publiée
= trop de confusion 

![image](https://user-images.githubusercontent.com/5484259/30754749-42406cd2-9fc4-11e7-98ea-59779a8baa6d.png)

faut enlever ce point rouge et mettre les icone des ressource non publiée grisées
= coherence avec la vue vignette

**Comment by clarophil** [comment]
J'ai aussi fait plusieurs propositions concernant la vue liste dans le ticket https://github.com/claroline/Distribution/issues/1235

**Comment by Batier** [comment]
Ahhh oui j'avais oublié ce ticket #1235 !
ça fait un moment que ce point rouge empoissonne notre vie!  :-)
je viens de rajouter aussi pour cette vue #2971
