### ISSUE TITLE
Création d'une liste de toutes les ressources d'un espace d'activité [enhancement]

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#2971]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 10.2.3
La vue liste actuelle n'est pas exhaustive.
Sur l es versions actuelles, on ne peut lister que répertoire par répertoire

Je vois Deux solutions :
Soit sur la vue actuelle on permet de dérouler les dossiers
 soit fait un listing global exportable en CSV

![image](https://user-images.githubusercontent.com/5484259/30772446-717de41a-a05b-11e7-9a69-c657c9529ca2.png)

**Comment by Elorfin** [comment]
Dispo en 12.5. Par contre toutes ressources de l'ea sont affichée à plat
