### ISSUE TITLE
Questionnaire plus de Chrono ?

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#2977]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 10.0.21

Bonjour,
La durée de l'évaluation pouvait être paramétrée auparavant si je ne me trompe pas. Est-il envisagé de réintégrer cette fonction bien utile ?
De même que la suppression des réponses mais j'ai déjà posé la question et eu une réponse. Mais je rejoins M. Batier, c'est un peu le bazar dans les résultats et les stats. Il faudrait au moins que les résultats soient effacés quad l'utilisateur est supprimé de la plateforme?
Bien à vous.
![image](https://user-images.githubusercontent.com/22524770/30799540-77897eae-a1dd-11e7-949d-9e85b03ceebb.png)

**Comment by LaurentGruber** [comment]
des tickets exist déjà

**Comment by Garakotxea** [comment]
OK, autant pour moi, je n'ai pas su les trouver.
