### ISSUE TITLE
Erreur copier/coller lien dans message sur forum

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#2980]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master

Bonjour,
En copiant/collant un lien absolu (vers fichier.pdf) dans un post du forum l'utilisateur à ouvert ce ticket :
Le lien a tout de même pu être posté.

Uncaught PHP Exception
The current node list is empty.
File
public_html/vendor/symfony/symfony/src/Symfony/Component/DomCrawler/Crawler.php
Line
557

J'ai reproduis la même erreur, il semblerait qu'en copiant/collant le lien, la cible tente de s'afficher.
Essayez avec l'adresse de votre site par exemple...

**Comment by LaurentGruber** [comment]
ça peut se désactivé en décochant l'option openGraph dans l'administration > paramètre de la plateforme > général ...
Sinon le faite d'aller chercher la source est une fonctionnalité demandée ...

**Comment by l-matt** [comment]
merci
