### ISSUE TITLE
[ExoBundle] La pénalité de mauvaise réponse de la question ordonnancement empêche de sauvegarder l'exercice

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#2982]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.2.3

Lorsque l'on saisie une valeur dans le champs "Pénalité pour toute mauvaise réponse non définie" d'une question de type **ordonnancement** et que l'on veut sauvegarder son exercice, une erreur est levée:

![ordo_field](https://user-images.githubusercontent.com/3415139/30814919-daeb1820-a211-11e7-8069-3887bd24937b.png)
![ordonnancement2](https://user-images.githubusercontent.com/3415139/30814944-e7f9009a-a211-11e7-96a2-2ee10b350650.png)
![ordonnancement1](https://user-images.githubusercontent.com/3415139/30814934-e31993be-a211-11e7-9807-6fb449d2a8b6.png)

Remettre 0 dans le champs ne résout pas le problème, il faut recharger la page.

**Comment by ngodfraind** [comment]
Reproduit
