### ISSUE TITLE
[ExoBundle] When a question type "classifying" is present impossible to terminate Quizz. Paper is saved but cannot be displayed.

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#2985]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.2.2

Impossible to terminate answering a Quizz. The following error gets displayed:
![image](https://user-images.githubusercontent.com/3414935/30847592-5c006ba6-a29c-11e7-82de-06aa71766ae8.png)

However, the paper is created but cannot be displayed (upon click on the eye button to display it). The following error pops in console:

![image](https://user-images.githubusercontent.com/3414935/30847643-8ecbec90-a29c-11e7-998a-3d782974fd3d.png)

**Comment by ptsavdar** [comment]
To be more specific, the problem seems to be due to a "classement" type question. When the question is deleted, both issues are resolved.

**Comment by ptsavdar** [comment]
Here's a .zip with a Quizz to import in a Workspace to reproduce the issue.
[awerasdf+asdfasdfasdf.zip](https://github.com/claroline/Distribution/files/1336821/awerasdf.asdfasdfasdf.zip)

**Comment by ptsavdar** [comment]
In fact when a question type "classifying" is present impossible to terminate quizz. The above error shows up.

**Comment by ngodfraind** [comment]
Reproduit.
