### ISSUE TITLE
Nouvel échec MAJ depuis 10.0.21

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#2987]
| Q             | A
| ------------- | ---
| Bug report?   | question
| Version?      | 10.0.21

Bonjour,
Voici le détail des commandes et messages.
Bien à vous

**git checkout .
git fetch
git checkout 10.x
git pull origin 10.x**
Depuis https://github.com/claroline/Claroline
 * branch            10.x       -> FETCH_HEAD
Already up-to-date.
**composer sync**
> composer fetch
PHP Warning:  require(/var/www/Claroline/vendor/composer/../symfony/phpunit-bridge/bootstrap.php): failed to open stream: No such file or directory in /var/www/Claroline/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/var/www/Claroline/vendor/composer/../symfony/phpunit-bridge/bootstrap.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/Claroline/vendor/composer/autoload_real.php on line 66
Script composer fetch handling the sync event returned with error code 255

**Comment by LaurentGruber** [comment]
ce n'est pas un bug, les questions doivent aller sur le forum : https://forum.claroline.com/

**Comment by Garakotxea** [comment]
Ce n'est pas un bug, à voir. Pourquoi alors que fais avec extrêmement de difficultés les mises à jour au fur et à mesure ai-je ces fichiers manquants ? Pourquoi est-ce toujours aussi compliqué avec chaque fois des difficultés nouvelles ? Voulez-vous vraiment que Claroline Connect s'étende comme le fut Claroine 1.x. ? Dans mon lycée je me démène pour essayer, tout seul de faire vivre Calroline Connect, d'accompagner mes collègues, car JAMAIS ils ne paieront pour Connect alors qu'ils ont GSuite gratuit.
Je vais poster sur le forum mais sans aucun espoir.
