### ISSUE TITLE
Bug MAJ 10.0.21 : le script n'est pas adapté à une plateforme Lambda

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#2991]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.0.21

Le script recherche un fichier qui n'existe pas dans une plateforme non hébergée. Il manque une MAJ intermédiaire pour exécuter ce script en l'état.
git checkout .
git fetch
git checkout 10.x
git pull origin 10.x
_Depuis https://github.com/claroline/Claroline

    branch 10.x -> FETCH_HEAD
    Already up-to-date._
    
composer sync

    _composer fetch
    PHP Warning: require(/var/www/Claroline/vendor/composer/../symfony/phpunit-bridge/bootstrap.php): failed to open stream: No such file or directory in /var/www/Claroline/vendor/composer/autoload_real.php on line 66
    PHP Fatal error: require(): Failed opening required '/var/www/Claroline/vendor/composer/../symfony/phpunit-bridge/bootstrap.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/Claroline/vendor/composer/autoload_real.php on line 66
    Script composer fetch handling the sync event returned with error code 255_

**Comment by LaurentGruber** [comment]
tu as fais un composer --no-dev à un moment et une autre fois, sans, donc il a ajouter et ou supprimer des dépences de dev qui manque. tu fais un composer update éventuellement 2 fois et ça passera.

**Comment by Garakotxea** [comment]
Je n'ai jamais fait de composer --no-dev mais Nicolas un jour m'a fait passer sur la dev car il y avait un bug et qeu c'était la stable du moment mais j'essaierai ta proposition, merci pour l'info. J'ai essayé un composeur install suite à une proposition dans un forum symphnoy mais cela n'a pas foncrionné.
Se placer à la racine pour la MAJ
cd /var/www/Claroline/
sudo git checkout .
sudo git fetch
sudo git checkout 10.x
sudo git pull origin 10.x
Modifier MAINTENANT composer.son
Commenter ou modifier la ligne
#"claroline/distribution": "~9.0"
devient
"claroline/distribution": "9.x-dev"

(composer update)
composer update --prefer-source
