### ISSUE TITLE
[ExoBundle] En mode "tester" la question ordonnancement ne mélange pas l'ordre des items

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#2992]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.2.3

Lorsque l'on répond à un questionnaire via l'option "Tester le questionnaire", les items de la question **ordonnancement** ne sont pas mélangés et apparaissent toujours dans le même ordre. Par contre les items sont correctement mélangés lorsque l'on répond réellement au questionnaire. Le comportement en mode test laisse à penser que ce type de question ne mélange pas les items et en limite donc l’intérêt.

**Comment by Elorfin** [comment]
Duplicate #2179.
