### ISSUE TITLE
Questionnaire : impossible d'ordonnancer les questions

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#2996]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.1.0

Lors de l'édition d'un questionnaire. J'essaye d'utiliser l'icône de déplacement pour faire glisser les questions dans la position voulue. Cela ne marche pas, la question que je veux déplacer reviens toujours à sa position initiale.

**Comment by ptsavdar** [comment]
Oui, en effet. Meme en version 10.3.1 j'arrive pas deplacer les questions.

**Comment by Batier** [comment]
Je confirme...
le truc pourri quand on duplique une question la copie passe en dernier...
c'est bidouille mais en attendant un debug j'ai pu m'organiser avec ça

**Comment by ngodfraind** [comment]
Reproduit (je suppose).

J'ai rien qui fonctionne chez moi pour le drag & drop.

**Comment by Batier** [comment]
oui c'est ça
