### ISSUE TITLE
Null in questions

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#2997]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.21

Still "null" present in the questions. Impossible to correct it in editing mode.

![bug_null](https://user-images.githubusercontent.com/14308826/30911388-a522e768-a388-11e7-9f75-3a7a3f534e67.PNG)

**Comment by LaurentGruber** [comment]
déjà corrigé sur 10.x
