### ISSUE TITLE
Bug when testing questionnaire

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#3000]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.0.21

When testing a questionnaire with fixed marks, the total isn't correct.

![bug_test_questionnaire](https://user-images.githubusercontent.com/14308826/30915760-0aed0bf0-a398-11e7-9af6-fc991485914b.png)

**Comment by LaurentGruber** [comment]
ça doit être corrigé sur la 10.5.1à venir
