### ISSUE TITLE
[ExoBundle] Les solutions de la question association ne sont pas rechargées à l'affichage

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#3017]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.2.3

Les solutions d'une question association ne sont pas affichées lorsque l'on recharge la page d’édition de l'exercice:

creer une question association, définir des solutions et sauvegarder:
![image](https://user-images.githubusercontent.com/3415139/31076864-9cf22bd8-a77c-11e7-92e4-1e170d4ad518.png)

recharger la page, les solutions ne sont plus affichées:
![image](https://user-images.githubusercontent.com/3415139/31076821-58f862b2-a77c-11e7-8b9e-ac2360af513d.png)

par contre, elles sont bien sauvegardées car on peut les forcer à se ré-afficher en cliquant sur une icone "+" de l’éditeur de texte riche:
![image](https://user-images.githubusercontent.com/3415139/31077003-26ea7ae8-a77d-11e7-8dd7-d9c80fc60786.png)

**Comment by ngodfraind** [comment]
Reproduit.
