### ISSUE TITLE
[Collecticiel]Paramètres-Evaluation-Notation-Maximum

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#302]
@ericvincenterv 

**Maximum (note sur)** 

Champ 

- 20 par défaut (placer le nombre 20 dès que sélection de notation dans type d'évaluation)
- réduire fortement la longueur du champ (viser 4 caractères)
- champ autorisant 4 caractères maxi

**Comment by ericvincenterv** [comment]
Au niveau de la longueur, voir également ce ticket https://github.com/claroline/Distribution/issues/304 afin d'uniformiser.
