### ISSUE TITLE
Mise à jour de fichiers ramène l'utilisateur à la racine à chaque MAJ quelque soit le sous-dossier traité

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#3025]
| Q             | A
| ------------- | ---
| Bug report?   | oui/no
| Version?      | 10.0.21

Bonjour,
C'est une gêne mineure et qui n'existe peut-être déjà plus dans les 10.3.x mais sur la 10.0.21 chaque fois que l'on met un document à jour on est ramené à la racine de Ressources. Il faut alors recliquer jusqu'à 5 fois pour revenir au sous-dossier à traiter.
Quand on a une dizaine de fichiers à mettre à jour l'outil perd de son intérêt. Il vaut mieux tout téléverser d'un coup et refaire les liens dans les widgets.
Il serait mieux - à mon sens - que l'on puisse rester dans le sous-dossier à traiter tant qu'on le souhaite.
Bien à vous

**Comment by Garakotxea** [comment]
Un retour arrière du navigateur et un click pour remonter de l'upload au sous-dossier permet de contourner le problème..

**Comment by ngodfraind** [comment]
reproduit
