### ISSUE TITLE
[Collecticiel]Paramètres-Evaluation-Notation-Critères

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#303]
@ericvincenterv 

Implémenter la gestion des critères d'évaluation, pas seulement pour l'appréciation, mais également pour la notation (cf. page 7 du doc)

**Comment by Elorfin** [comment]
@jj-quintin : can you put the content of the "page 7" for those who don't have access to the original document please ?

**Comment by jj-quintin** [comment]
[Collecticiel-Evaluation-JJQ-08-12-2015.pdf](https://github.com/claroline/Distribution/files/268493/Collecticiel-Evaluation-JJQ-08-12-2015.pdf)

**Comment by ericvincenterv** [comment]
See this issue : https://github.com/claroline/Distribution/issues/507
