### ISSUE TITLE
[Collecticiel]Paramètres-Evaluation-Appréciation-Critères

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#304]
@ericvincenterv 

1) Changer bouton Crayon + "Gérer les évaluations" par Crayon + "Echelle et critères"
2) Placer ce bouton à droite du menu déroulant qui correspond à "Les documents du collecticiel font l'objet d'une évaluation ?"
3) Si clic sur gérer les évaluations + sauvegarder alors retour dans Paramètres avec les valeurs de notation et non d'appréciation comme attendu. Préserver et afficher les dernières valeurs (celles avant clic sur gérer les évaluations)

**Comment by ericvincenterv** [comment]
1) et 2) : OK.

Pour le 3), le fonctionnement est-il correct sur demo-v6 après l'actualisation du jour ?

**Comment by ericvincenterv** [comment]
@jj-quintin : 
1) une autre demande de label a été formulée plus récemment, j'ai pris en compte la dernière. Celle de cette issue n'avait pas été faite.
3) cette partie a été corrigée, un autre ticket a été créé.

Pour la 2), est-ce que ce résultat est correct ?
![bouton](https://cloud.githubusercontent.com/assets/5363344/16803632/bb5c7058-4907-11e6-9dc4-f9053134f152.png)

**Comment by jj-quintin** [comment]
ok, et peux donc fermé ou supprimé ce ticket. La dernière proposition 'Gérer les évaluations" pour les deux cas (notation et appréciation) est plus simple et plus rapide. On verra plus tard si l'on différence ce bouton dans le cas d'une appréciation ("+ Echelle et critères") et dans celui d'une notation (qui pourrait être "+ Critères")

**Comment by ericvincenterv** [comment]
@jj-quintin : 
Pour le point 2, tu as écrit "2) Placer ce bouton à droite du menu déroulant qui correspond à "Les documents du collecticiel font l'objet d'une évaluation ?"
Est-ce que la capture d'écran publiée et visible dans ma réponse ci-dessus est correct ?

**Comment by jj-quintin** [comment]
Parfait pour moi
