### ISSUE TITLE
[ExoBundle] 

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#3041]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.3.1

Ajouter une question classement à un questionnaire 
Répondre
Terminer 

Et rien ne se passe
Le comportement est identique avec Tester et Répondre

Dans la console js
TypeError: parentDocShell.getDocShellEnumerator is not a function[En savoir plus]  tab.js:62:23
ReferenceError: exports is not defined[En savoir plus]  angular-ui.js:90:25439

**Comment by LaurentGruber** [comment]
Duplicate https://github.com/claroline/Distribution/issues/2996
