### ISSUE TITLE
exclusion de groupe après édition du profil

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3048]
| Q | 1
| ------------- | ---
| Bug report?   | yes
| Version?      | master/10.1.0

J'ai créé un SPOC via un EA, pour inscrire les utilisateurs à cet EA, j'ai créé un groupe.
J'ai plusieurs utilisateurs qui perdent l'accès à l'EA après avoir édité leur profil. 
Après vérification, il s'avère que l'action d'éditer leur profil provoque une exclusion du groupe et donc une désinscription de l'EA sur lequel est inscrit le groupe.

![image](https://user-images.githubusercontent.com/32478422/31222149-66ae7e0e-a9c6-11e7-8259-62fd75927428.png)

**Comment by ngodfraind** [comment]
reproduit
