### ISSUE TITLE
[Collecticiel]Paramètres-Evaluation-Menu déroulant

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#305]
@ericvincenterv 

Réduire la largeur du menu déroulant (de "Les documents du collecticiel font l'objet d'une évaluation ?") à la largeur nécessaire + sécurité autres langues (50 caractères)

**Comment by ericvincenterv** [comment]
@jj-quintin : à quel niveau faut-il positionner ce menu déroulant ? Au niveau des dates d'ouvertures ?

**Comment by ericvincenterv** [comment]
A rapprocher de ce ticket : https://github.com/claroline/Distribution/issues/304
