### ISSUE TITLE
[TeamBundle] Team members can't access WS Resources tool even if they have the right to view this tool

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#3052]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.3.6

In a WS that is not public (and its resources are not open to everybody) when we create a new team (let's say Team 1) and give the right to this team to access tools Home and Resources, when we test by usurping this role, the Resources tool is not accessible. Possible due to the fact that the team roles are not displayed in the WS Parameters -> Resources rights management. IMHO the roles are not created for the WS root folder. Thus, it is imposible to give access to these roles.

**Comment by LaurentGruber** [comment]
tu as essayé le claroline:role:check sur le ws ?

**Comment by ptsavdar** [comment]
Oui, le role check a corrige le soucis. Par contre le probleme est la a chaque fois qu'on cree une equipe.

**Comment by ngodfraind** [comment]
Reproduit (je crois).
