### ISSUE TITLE
[AnnouncementBundle] Sending by email an announcement crash if no title

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#3055]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.3.1

Create a new announcement without title
Check Send the notification

I think that the title should be required in the form.

Uncaught PHP Exception 
An exception occurred while executing 'INSERT INTO claro_message (object, content, date, is_removed, lft, lvl, rgt, root, sender_username, receiver_string, sender_id, parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [**null,** "<div class="panel-body"> <p>Bonjour,</p> <p>Voici l'&eacute

**Comment by Elorfin** [comment]
Now, we create a default title based on the Resource name in the case the title is missing (like for emails).
