### ISSUE TITLE
[ExoBundle] Faille de sécurité

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#3056]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.x

Il y a une grosse faille de sécurité dans l'outil exercice, le répondant a accès à la correction de sa copie pendant qu'il est en train d'y répondre.
Pendant que l'utilisateur (avec droits de lecture seulement) répond il a toujours accès au menu contextuel en haut à droite pour avoir accès à la liste de ses copies, ce qui inclut la copie en cours de rédaction:
![image](https://user-images.githubusercontent.com/3415139/31282052-aa151cde-aab1-11e7-8f49-9617cf53baaf.png)

L'icone d'oeil est grisé avec un sens interdit au survol, mais le lien est quand même cliquable:
![image](https://user-images.githubusercontent.com/3415139/31282149-ef05d16c-aab1-11e7-893c-23bbf352cfe7.png)

Ce qui permet d’accéder à la copie en cours de rédaction:
![image](https://user-images.githubusercontent.com/3415139/31282187-11ebb926-aab2-11e7-96ab-beecf6fb25f0.png)

Ce qui permet dans un questionnaire à plusieurs étapes, de répondre à une étape, ouvrir la correction dans un autre onglet et vérifier si sa réponse est juste ou non, revenir au questionnaire, revenir à l'étape précédente et corriger son choix en conséquence. En essayant les choix un par un on peut ainsi savoir lesquels sont justes.

**Comment by Garakotxea** [comment]
L'élève peut carrément afficher 2 fenêtres par exemple et cliquer sur "Réponse attendue" pour avoir le résultat à forunir. Je viens de faire l'essai et je n'ai pas eu de problème pour terminer le test. La note a été prise en compte. 
![image](https://user-images.githubusercontent.com/22524770/31290594-548d9518-aacd-11e7-8fd8-c3c2c6c1b873.png)

**Comment by ngodfraind** [comment]
Reproduit
