### ISSUE TITLE
[CoreBundle] Un espace créé n'apparait plus dans la liste de son créateur

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#3057]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.4.1

Lorsque l'on créé un espace d'activité celui-ci n’apparaît plus dans la liste d'espaces de son créateur. L'utilisateur n'est apparemment plus automatiquement ajouté au rôle gestionnaire. On peut résoudre le problème en passant par l'administration et en allant inscrire manuellement l'utilisateur dans le rôle gestionnaire.

**Comment by ngodfraind** [comment]
Reproduit (je crois)

**Comment by ngodfraind** [comment]
C'est en cours, j'termine après. y a a priori pas trop de choses à régler.
