### ISSUE TITLE
Weblink as a resource

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#3062]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.3.2

![bug_create_link_resource](https://user-images.githubusercontent.com/14308826/31319913-098618ba-ac6c-11e7-84a8-5a1a2a90180e.JPG)

When trying to save a weblink as a resource, I'm asked to create a ticket on iejn.claroline.com

**Comment by Batier** [comment]
problème déjà remonté ici
https://github.com/claroline/Distribution/issues/2846

**Comment by LaurentGruber** [comment]
duplicate
