### ISSUE TITLE
[Collecticiel]Paramètres-Evaluation-Appréciation-Echelle et critères

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#307]
@ericvincenterv 

1) Utiliser plutôt une fenêtre modale
2) Titre de la fenêtre modale = Echelle d'appréciation
3) Modifier de ce fait le sous-titre "Echelle d'appréciation" par "Echelle"
4) Permettre le déplacement des degrés de l'échelle
5) Interdire la suppression des deux derniers degrés (comme discuté entre nous)
6) Bouton + Ajouter un degré d'apréciation à modifier par "+ Degré d'appréciation" (attention 2 p à appréciation)
7) Informations/critères accompagnant l'appréciation : 

- Permettre de déplacer les champs texte

8) Changer retour par Annuler (de manière à alerter sur la non sauvegarde dans ce cas, ce que Retour n'indique pas vraiment)

**Comment by ericvincenterv** [comment]
1) Est-ce que l'utilisation d'une fenêtre de type "modale" apporterait un plus ?
2) ok
3) ok
4) et 7) que veux-tu dire ? tu veux ajouter un drag-drop ?
5) ok. Faut-il également avoir un nombre minimum au niveau des critères ?
6) ok
8) ok

**Comment by ericvincenterv** [comment]
@jj-quintin : 
j'avais créé ce ticket où j'évoquais le nombre de critères minimum : 
https://github.com/claroline/Distribution/issues/689
On part sur 2 ou sur 3 ?

**Comment by ericvincenterv** [comment]
@jj-quintin : 
tu peux me donner ta décision sur ce ticket ?

**Comment by jj-quintin** [comment]
1) Utiliser plutôt une fenêtre modale
> Eric : Est-ce que l'utilisation d'une fenêtre de type "modale" apporterait un plus ?
> JJQ : **En théorie oui, mais il s'agit surtout maintenant de faire la même chose que pour la notation. On n'a plus le temps maintenant. Supprimer ce point du ticket. On y reviendra plus tard si l'expérience montre que c'était une bonne idée... ou pas**
4) Permettre le déplacement des degrés de l'échelle et 7) Informations/critères accompagnant l'appréciation : Permettre de déplacer les champs texte
> JJQ : **on reporte, plus le temps. Ce sera une amélioration  possible pour l'avenir. Créer un nouveau ticket avec le milestone Futur et le label Enhancement** 
5) Interdire la suppression des deux derniers degrés (comme discuté entre nous)
> Eric : 5) ok. Faut-il également avoir un nombre minimum au niveau des critères ?
> **On ne pas pas supprimer les deux derniers, donc oui, au minimum deux**

**Comment by ericvincenterv** [comment]
Ticket fermé car tous les points ont soit été résolus, soit créés sur un ticket pour une demande unitaire.
