### ISSUE TITLE
[Ergonomie] faire apparaître le Nb d'utilisateur dans la page Gestion des utilisateurs

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#3070]
| Q             | A
| ------------- | ---
| Bug report?   | no

 remonter le compteur des inscrits actuellement présent dans Paramétres/généraux 
->à la page Gestion des utilisateurs

**Comment by Elorfin** [comment]
L'info est dispo dans la nouvelle gestion des users.

**Comment by Batier** [comment]
top !!!!!!!!!!!!!!!!!!!!!!!!!!!!
et le top du top serai d'avoir le nb qui se sont connectés / nb inscrits
