### ISSUE TITLE
Exo - tag

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#3078]
- [x] quand on ajoute un tag sur une question sans faire aucune autre modification sur l'exercice, le bouton sauvegarder reste grisé.

- [x] si tu mets directement des tag à une question, sans avoir sauvé au moins une fois l'exo, la sauvegarde renvoie une erreur 500

d'autres soucis:

- [x] on ne peut pas enlever l'option de pioche par tag une fois activée, décocher "tag" dans paramètres/tirage des étapes puis sauvegarder ne fait rien, après rafraîchissement de la page "tag" est toujours coché.

- [x] si on coche l'option de pioche par tag sans préciser de tags/quantité à piocher, la sauvegarde lève une erreur 422 Unprocessable Entity

- [x] on ne peut pas répondre à un questionnaire avec pioche par tag activé, un erreur 500 est levée dés qu'on clic sur "commencer"

**Comment by ngodfraind** [comment]
Reproduit

**Comment by nicolasjacquemet** [comment]
d'autres soucis:

- [ ] on ne peut pas enlever l'option de pioche par tag une fois activée, décocher "tag" dans paramètres/tirage des étapes puis sauvegarder ne fait rien, après rafraîchissement de la page "tag" est toujours coché.

- [ ] si on coche l'option de pioche par tag sans préciser de tags/quantité à piocher, la sauvegarde lève une erreur 422 Unprocessable Entity

- [ ] on ne peut pas répondre à un questionnaire avec pioche par tag activé, un erreur 500 est levée dés qu'on clic sur "commencer"

**Comment by Batier** [comment]
Nico je me demande s'il faut pas faire une nouvelle Issue?
