### ISSUE TITLE
Collecticiel-Paramètres-Evaluation-Dates (ouverture/fermeture)

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#308]
@ericvincenterv 

Placer heure à côté de date tant que la largeur le permet

![image](https://cloud.githubusercontent.com/assets/16414632/15327034/5ff7f0e0-1c50-11e6-9a4e-1213bd962ae0.png)

**Comment by ericvincenterv** [comment]
@jj-quintin : 
sur demo-v6, j'ai ceci : 
![capture d ecran - 01072016 - 10 32 48](https://cloud.githubusercontent.com/assets/5363344/16516228/22f4c764-3f77-11e6-89b3-a6dc26b5e1c6.png)

sur quel support tu as eu cette vue ? Logiquement, quelque soit le support, on a la vue indiquée ci-dessus.

**Comment by ericvincenterv** [comment]
@jj-quintin : 
as-tu constaté un décalage ? est-ce que ce ticket est toujours d'actualité car je ne l'ai pas reproduit ?

**Comment by jj-quintin** [comment]
Oui, tjs d'actualité. Si tu réduis l'écran, tu verras le souci
Mais vu que cela ne bloque pas le fonctionnement et qu'il y a plus important, je propose de reporter le milestone
