### ISSUE TITLE
Affichage du score

### ISSUE THREAD

**Issue by david42** [claroline/Distribution#3086]
| Q             | A
| ------------- | ---
| Bug report?   | Yes
| Version          | 10.4.0

Retour utilisateur : 
"L'affichage du score se fait toujours même si on coche 'jamais' dans les paramètres."

J'ai testé, on n'a pas la note globale mais on a le score par question d'affiché

**Comment by Garakotxea** [comment]
Constaté sur la 10.0.21. Constaté également que la correction était visible alors que j'avais demandé de ne pas l'afficher. Non testé sur 10.5.0

**Comment by ngodfraind** [comment]
Reproduit

**Comment by ngodfraind** [comment]
En fait j'ai rien dit, il y a quelque chose de bizarre. Ça n'a pas fonctionné du premier coup mais maintenant, c'est bon alors que je n'ai rien changé (j'ai fait quelques essais pour mieux cerner le problèmes mais aucun changement dans le code).

Il y a quelque chose de bizarre. Je laisse ouvert en attendant.

**Comment by npaille** [comment]
Je rencontre le même problème. Le score et la réponse attendue s'affichent même quand je coche jamais pour les deux champs.

**Comment by Garakotxea** [comment]
Je viens de faire un essai à l'instant suite à votre retour car je n 'étais pas revenu sur ce problème. En voici le résultat pour la 10.5.8 :
L'élève ne peut plus accéder à la correction lors de l'évaluation.
L'élève a accès à ses réponses en fin d'évaluation mais ne voit pas la correction ni sa note.
Il me semble donc que cela fonctionne bien pour la 10.5.8
![image](https://user-images.githubusercontent.com/22524770/32122307-31e42542-bb60-11e7-9655-60647b33ecb0.png)
![image](https://user-images.githubusercontent.com/22524770/32122383-705188e2-bb60-11e7-9e5b-1c85c2797418.png)

**Comment by npaille** [comment]
Bien ! Merci pour votre retour, qui me rassure sur le fait que la mise à jour va résoudre ce souci.

**Comment by Garakotxea** [comment]
Surtout que les MAJ sont rapides maintenant :)

**Comment by Garakotxea** [comment]
Parc contre le prof ne voir pas la note globale lui non plus. La parade que j'utilise est d'exporter le résultat en csv et on obtient la notre globale sans avoir à faire la somme des points question par question :)
![image](https://user-images.githubusercontent.com/22524770/32122960-bbd26488-bb62-11e7-9c23-f2f2712d5575.png)

![image](https://user-images.githubusercontent.com/22524770/32122994-df17ec10-bb62-11e7-8f0b-897c4de007af.png)

**Comment by npaille** [comment]
J'ai 800 copies à la fois, donc oui csv obligatoire :)

**Comment by Garakotxea** [comment]
En effet !!!!
En plus cela vous permettra de les trier par nom. C'est une bonne option en fin de compte.

**Comment by LaurentGruber** [comment]
Pour info, le score s'affiche toujours si on a le droit d'éditer l'exo, par contre pour les autres ils ne s'affichent pas si l'option est choisie
