### ISSUE TITLE
Importing resources in the reservation bundle

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#3101]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 10.3.2

When trying to import resources from a csv file, Nothing happens.

This is the csv file. Is there a mistake in it?

Type de ressource, Nom,,,Occupation,Classe,
007 TBI,,,,,
009 Proj,,,,,
011 TBI,,,,,,
013 Proj,,,,,,

**Comment by LaurentGruber** [comment]
ça sera fait dans la 11.x
