### ISSUE TITLE
[ExoBundle] Erreur lorsqu'un utilisateur non connecté essaie de répondre à un exercice ouvert à tous

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#3109]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.5.0

Une erreur est levée lorsqu'un utilisateur non connecté essaie de valider sa réponse à un exercice accessible "à tous le monde". 

![image](https://user-images.githubusercontent.com/3415139/31539761-eb454f3c-b009-11e7-9b2a-7dee2fd197b9.png)
![image](https://user-images.githubusercontent.com/3415139/31540199-426cae44-b00b-11e7-9651-aa85a9e7ad3d.png)

Un erreur 500 est lévé lorsque l'on clic sur Terminer:

![image](https://user-images.githubusercontent.com/3415139/31539958-903473a6-b00a-11e7-9f38-c8ff2519667b.png)
![image](https://user-images.githubusercontent.com/3415139/31539939-73ebd5ae-b00a-11e7-99ef-556fcd450569.png)

Les réponses saisies semblent cependant bien enregistrées et la copie apparaît comme non terminée dans la liste des résultats.
![image](https://user-images.githubusercontent.com/3415139/31540384-cd1b98c0-b00b-11e7-8172-96200d31280e.png)

**Comment by LaurentGruber** [comment]
tu as l'erreur dans app/log/prod.log ?

**Comment by ngodfraind** [comment]
Reproduit.

J'ai aussi eu une autre erreur en ne répondant à rien dans l'exo (une erreur de js).

**Comment by ngodfraind** [comment]
![3109](https://user-images.githubusercontent.com/1397430/31552069-b384ac64-b036-11e7-8300-ad5a055d17ce.png)
