### ISSUE TITLE
[Collecticiel]Etudiant-Curseur (modification apparence main)

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#312]
@ericvincenterv 

Ici, Transmettre une demande de commentaire est une action, la règle d'apparence du curseur est, dans ce cas, d'afficher la main

![image](https://cloud.githubusercontent.com/assets/16414632/15327780/d6d2341c-1c52-11e6-8ef4-da927a323a8f.png)

**Comment by ericvincenterv** [comment]
OK, reproduit en local.
Il faut ajouter href="#" dans le fichier documentIsValidate.html.twig.

**Comment by ericvincenterv** [comment]
Fait ici : https://github.com/claroline/Distribution/issues/778
