### ISSUE TITLE
Pas d'affichage d'icône pour la ressource Dossier

### ISSUE THREAD

**Issue by txomin666** [claroline/Distribution#3125]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.x et master

Bonjour,

Après une install fraîche de la branche 10.x ou master, l'icône d'une ressource Dossier est cherchée dans :  
bundles/clarolinecore/images/resources/icons/res_folder.png (qui n'existe pas)

au lieu de :

data/icon_sets/claroline/directory.svg 

Voici un extrait du log de Apache quand je rafraîchis une page contenant une ressource forum (où l'icône s'affiche bien) et une ressource dossier  : 

192.168.1.67 - - [15/Oct/2017:22:01:18 +0200] "GET /data/icon_sets/claroline/claroline_forum.svg HTTP/1.1" 304 181 "http://claroline-10-prod/workspaces/4/open/tool/resource_manager" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"

192.168.1.67 - - [15/Oct/2017:22:01:18 +0200] "GET /bundles/clarolinecore/images/resources/icons/res_folder.png HTTP/1.1" 404 20921 "http://claroline-10-prod/workspaces/4/open/tool/resource_manager" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
::1 - - [15/Oct/2017:22:01:23 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) OpenSSL/1.0.2l (internal dummy connection)"

--
Txomin

**Comment by LaurentGruber** [comment]
php app/console claroline:icon_set:calibrate
