### ISSUE TITLE
Proposition pour le téléchargement des fichiers [Ergonomie]

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#3129]
quand on sélectionne le droit au téléchargement sur une ressource fichier
est ce qu'il serait possible de mettre la ressource directement dans le player sur le poste local
?
cas typique le PDF qui s'ouvre directement dans accrobat 
on gagnerait le clic sur la ressource
le clic sur l'icone télécharger et le clic ouvrir

**Comment by LaurentGruber** [comment]
ça serait mélanger la gestion des droits (déjà complexe) avec les modes d'affiachages, pour moi ce sont 2 choses différentes ...
Il faudrait plus tôt ajouter une option d'affichage permettant ça (à côté de celle permettant de mettre une ressource en plein écran,... ?)

**Comment by Batier** [comment]
Oui mais cette option se trouverait sur quel écran

**Comment by LaurentGruber** [comment]
ici : 
![capture d ecran de 2017-10-16 15-32-51](https://user-images.githubusercontent.com/5804394/31614653-62216684-b287-11e7-8ed0-4548a519f164.png)

**Comment by Batier** [comment]
je n'ai pas accès a cette interface mais oui ça me semble etre la bonne place
