### ISSUE TITLE
[Collecticiel]Enseignant-Opérations en attente

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#313]
@ericvincenterv 

Problème de calcul du total des opérations en attente, comme ici pour le nombre de commentaire en attente. idem pour les accusés de réception, il indique 2 également

![image](https://cloud.githubusercontent.com/assets/16414632/15327950/89bc83de-1c53-11e6-9d26-d7d2ce0a96e1.png)

**Comment by ericvincenterv** [comment]
Issue : 
https://github.com/claroline/Distribution/issues/509
Commit : 
https://github.com/claroline/Distribution/commit/54a08e189dad217560ba0784eac868ebcf149f12
