### ISSUE TITLE
Impossible to save the changes in a learning path

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#3134]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.3.2

1. Open a learning path
2. Add a step
3. Save the changes
4. Publish the changes: after a few seconds, the message "Saved with unpublished changes" comes back (see link in picture below).

![bug_publish_path](https://user-images.githubusercontent.com/14308826/31666723-872d56ba-b34d-11e7-8563-9e2e93435983.JPG)

**Comment by LaurentGruber** [comment]
ctrl + F5 ?

**Comment by om64** [comment]
J'ai tenté ça, mais sans succès.

**Comment by Elorfin** [comment]
et les changements ont été publié quand même ou pas ?

**Comment by om64** [comment]
Non, malheureusement...
C'est clairement lié à ce parcours, mais pourquoi?

**Comment by Elorfin** [comment]
tu as quoi comme retour (dans la console du navigateur) lorsque que tu cliques sur publié ?
(sinon si tu me donnes un accès à ton instance, je pourrais aller jeter un œil)

**Comment by om64** [comment]
Thanks for your help, @Elorfin
