### ISSUE TITLE
Suppression d'un dossier

### ISSUE THREAD

**Issue by bartkimps** [claroline/Distribution#3175]
Un dossier a été créé dans mes ressources. Je le sélectionne. Je le supprime à l'aide de la poubelle.
Une boîte de dialogue apparaît me demandant la confirmation. Quand je clique sur OK, l'opération se bloque et il m'indique "Veuillez patienter". 
Que faire ?

**Comment by LaurentGruber** [comment]
Que dit la console ? que disent les logs ?

**Comment by bartkimps** [comment]
Il m'indique lors de la sélection de la poubelle : **Êtes-vous sûr de vouloir supprimer ces ressources ?** 
Ensuite j'appuie sur OK. Il m'indique alors : **Veuillez patienter....**
Voici un printscreen de la situation : 
![erreur suppression](https://user-images.githubusercontent.com/32710141/32176290-88fe908c-bd87-11e7-97dc-bbccd8eaa95c.png)
**
Ce message reste pendant plusieurs minutes et rien ne se passe. J'annule alors l'action.

**Comment by tikok974** [comment]
Bonjour,

Ce ticket ressemble au rapport de bug [3264](https://github.com/claroline/Distribution/issues/3264) que j'ai créé.

Est-ce que dans ton dossier tu as une ressource de type "questionnaire" ?
As-tu essayé de supprimer d'abord 1 à 1 les éléments qui sont dans le dossier pour voir lequel bloque ?

Bonne journée

**Comment by bartkimps** [comment]
Bonjour,

Dans le dossier à supprimer, il ne reste plus que des liens vers des activités.

Si je supprime tout et quand je ré-ouvre la ressource, tout ré-apparaît.

Si j'en supprime un à la fois, c'est le même problème, il ré-apparaît.

Je t'ai envoyé un printscreen des éléments à supprimer.


Merci et bonne journée

________________________________
De : tikok974 <notifications@github.com>
Envoyé : mardi 28 novembre 2017 13:49:31
À : claroline/Distribution
Cc : Bart KIMPS - IEJN; Author
Objet : Re: [claroline/Distribution] Suppression d'un dossier (#3175)


Bonjour,

Ce ticket ressemble au rapport de bug 3264<https://github.com/claroline/Distribution/issues/3264> que j'ai créé.

Est-ce que dans ton dossier tu as une ressource de type "questionnaire" ?
As-tu essayé de supprimer d'abord 1 à 1 les éléments qui sont dans le dossier pour voir lequel bloque ?

Bonne journée

**Comment by tikok974** [comment]
Salut,

J'ai pas reçu ton printscreen.
As-tu essayé de vider le cache Symfony lorsque tu as réalisé ces actions ?
Pour vider ce cache tu peux:

- Te rendre dans le répertoire racine de Claroline sur ton serveur Web (exemple "/var/www/Claroline") et taper la commande:
`php app/console cache:clear`
- Et...si cela ne suffit pas, supprime tout le contenu du dossier "cache" dans le répertoire "app". Exemple
`/var/www/Claroline/app/cache# rm -rf *`

Bonne journée

**Comment by bartkimps** [comment]
Désolé, je vais regarder les infos que tu m'as données et voici le Printscreen.

Ce sont des liens impossibles à supprimer directement. Ils reviennent chaque fois quand je ferme et que je ré-ouvre les ressources.


Bonne journée

________________________________
De : tikok974 <notifications@github.com>
Envoyé : mercredi 29 novembre 2017 08:48:31
À : claroline/Distribution
Cc : Bart KIMPS - IEJN; Author
Objet : Re: [claroline/Distribution] Suppression d'un dossier (#3175)


Salut,

J'ai pas reçu ton printscreen.
As-tu essayé de vider le cache Symfony lorsque tu as réalisé ces actions ?
Pour vider ce cache tu peux:

  *   Te rendre dans le répertoire racine de Claroline sur ton serveur Web (exemple "/var/www/Claroline") et taper la commande:
php app/console cache:clear
  *   Et...si cela ne suffit pas, supprime tout le contenu du dossier "cache" dans le répertoire "app". Exemple
/var/www/Claroline/app/cache# rm -rf *

Bonne journée

**Comment by bartkimps** [comment]
Petite question : suite à ton mail précédent je crois constater que tu travailles avec Linux. Je me trompe ?

  *   Te rendre dans le répertoire racine de Claroline sur ton serveur Web (exemple "/var/www/Claroline") et taper la commande:
php app/console cache:clear
  *   Et...si cela ne suffit pas, supprime tout le contenu du dossier "cache" dans le répertoire "app". Exemple
/var/www/Claroline/app/cache# rm -rf *

Moi, je suis sous Windows 10.


Bonne soirée

________________________________
De : Bart KIMPS - IEJN
Envoyé : jeudi 30 novembre 2017 09:23:49
À : claroline/Distribution
Objet : RE: [claroline/Distribution] Suppression d'un dossier (#3175)


Désolé, je vais regarder les infos que tu m'as données et voici le Printscreen.

Ce sont des liens impossibles à supprimer directement. Ils reviennent chaque fois quand je ferme et que je ré-ouvre les ressources.


Bonne journée

________________________________
De : tikok974 <notifications@github.com>
Envoyé : mercredi 29 novembre 2017 08:48:31
À : claroline/Distribution
Cc : Bart KIMPS - IEJN; Author
Objet : Re: [claroline/Distribution] Suppression d'un dossier (#3175)


Salut,

J'ai pas reçu ton printscreen.
As-tu essayé de vider le cache Symfony lorsque tu as réalisé ces actions ?
Pour vider ce cache tu peux:

  *   Te rendre dans le répertoire racine de Claroline sur ton serveur Web (exemple "/var/www/Claroline") et taper la commande:
php app/console cache:clear
  *   Et...si cela ne suffit pas, supprime tout le contenu du dossier "cache" dans le répertoire "app". Exemple
/var/www/Claroline/app/cache# rm -rf *

Bonne journée

**Comment by tikok974** [comment]
Salut !
Ah...Windows 10...oui tu as raison, je suis sous Linux (Debian 9.2 précisément).
Et bien... je présume que la structure des dossiers **concernant Claroline** ne change pas (à confirmer auprès de quelqu'un qui travaille aussi sous Windows et qui nous lit).

Il te suffirai alors de supprimer le contenu du dossier "\app\cache" situé dans le dossier racine de Claroline (voir ton instance Claroline sur ton serveur Web Windows).

Bonne journée

**Comment by bartkimps** [comment]
Et si je n'avais aucun hébergement sur un serveur dédié. Je travaille directement avec Claroline sur le net à partir de iejn.claroline.com

C'est donc pour cela que je ne trouve pas le dossier que tu me références.


Bon week-end


________________________________
De : tikok974 <notifications@github.com>
Envoyé : vendredi 1 décembre 2017 08:57:06
À : claroline/Distribution
Cc : Bart KIMPS - IEJN; Author
Objet : Re: [claroline/Distribution] Suppression d'un dossier (#3175)


Salut !
Ah...Windows 10...oui tu as raison, je suis sous Linux (Debian 9.2 précisément).
Et bien... je présume que la structure des dossiers concernant Claroline ne change pas (à confirmer auprès de quelqu'un qui travaille aussi sous Windows et qui nous lit).

Il te suffirai alors de supprimer le contenu du dossier "\app\cache" situé dans le dossier racine de Claroline (voir ton instance Claroline sur ton serveur Web Windows).

Bonne journée

**Comment by tikok974** [comment]
Re,
Ah, je pensais que tu avais accès au serveur hébergeant Claroline. 
À ma connaissance (là encore à confirmer par les développeurs / spécialistes de Claroline qui pourraient nous lire) on ne peut pas réinitialiser le cache Symfony depuis l'interface de Claroline.

Il faudra attendre une réponse des développeurs sur ce ticket pour confirmer, dans ton cas, si c'est un bug de la plateforme ou une manipulation sur le cache à réaliser.

Désolé de ne pas pouvoir t'aider plus que ça.
Bonne fin de journée

**Comment by bartkimps** [comment]
Un grand merci quand-même et je te souhaite une bon week-end.



________________________________
De : tikok974 <notifications@github.com>
Envoyé : vendredi 1 décembre 2017 12:30:11
À : claroline/Distribution
Cc : Bart KIMPS - IEJN; Author
Objet : Re: [claroline/Distribution] Suppression d'un dossier (#3175)


Re,
Ah, je pensais que tu avais accès au serveur hébergeant Claroline.
À ma connaissance (là encore à confirmer par les développeurs / spécialistes de Claroline qui pourraient nous lire) on ne peut pas réinitialiser le cache Symfony depuis l'interface de Claroline.

Il faudra attendre une réponse des développeurs sur ce ticket pour confirmer, dans ton cas, si c'est un bug de la plateforme ou une manipulation sur le cache à réaliser.

Désolé de ne pas pouvoir t'aider plus que ça.
Bonne fin de journée

**Comment by LaurentGruber** [comment]
toujours d'actualité ?
