### ISSUE TITLE
Accès aux activités sans inscriptions

### ISSUE THREAD

**Issue by bartkimps** [claroline/Distribution#3177]
Je crée un espace d'activité pour mes élèves avec notamment un URL vers une vidéo et ensuite un questionnaire.
Mais est-il possible d'accéder à ces activités sans inscription de l'élève? Et le questionnaire va t'il comptabiliser ses points enfin de parcours ?

**Comment by LaurentGruber** [comment]
il faut donner l'accès aux rôles anonymes, le questionnaire fera le compte mais pour un utilisateur fictif nommé anonymes.
Les questions ont normalement leur place dans le forum : forum.claroline.net
Github est réservé au rapport de bug, afin de pouvoir s'y retrouver.
