### ISSUE TITLE
Access denied sur le parcours donne comme message de contacter l'administrateur

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#318]
Quand j'ai une erreur de ce type : 

```
Uncaught PHP Symfony\Component\Finder\Exception\AccessDeniedException Exception: "-" at ../vendor/claroline/distribution/plugin/path/Manager/PathManager.php line 98

URL : http://domain/innova_path/player/637
Referer : http://domain/workspaces/216/open/tool/home
```

L'utilisateur reçoit comme message de contacter l'administrateur au lieu d'un message lui disant qu'il n'a pas les droits pour accéder à la ressource...

**Comment by CPASimUSante** [comment]
I'm not sure why, but could it be that the user had his session timedout ? He stayed on the path page during {cookie_session_duration} minutes and try to click => he's lost the session cookie => he's undefined => this error.
I've had these error 500 for several tools and resources when i was away for too long.

**Comment by LaurentGruber** [comment]
@CPASimUSante Not in this case

**Comment by CPASimUSante** [comment]
In any case, i have`500 Internal Servor Error - AccessDeniedException` when i try to access directly a page without being connected : i copy/ paste from admin account the url, to another browser.
This is related to the same function checkAccess()
