### ISSUE TITLE
[DropzoneBundle/Evaluation] Propositions d'amelioration pour la refonte de l'outil

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#3204]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master/7.0/etc.

- [x] Possibilité de réinitialiser la copie d'un étudiant qui a clôturer son dépôt

- [x] Quand on est côté étudiant, et qu’on upload un doc, une pop up s'ouvre en indiquant"
"Chaque document ajouté est sauvegardé automatiquement. Cependant, pensez à cliquer sur "Terminer" en bas à droite une fois que vous avez fini. Si vous ne le faites pas, votre copie sera considérée comme non-rendue."
Cette indication est  également affichée en permanence en haut de la zone de dépôt.
Ces indications ne sont pas claires. Les étudiants comprennent que s'ils ont fini de télécharger leurs documents ils doivent cliquer en bas à droite sur " sauvegarder" pour que leurs copies soient considérées comme rendues.
Or cette action clôture le dépôt de documents ce qui est nullement indiqué.
la pop-up "Vous êtes sur le point de rendre votre copie. Cette action est définitive. Êtes-vous sûr d'avoir terminé ?"  Ne permet pas de comprendre que cela ferme la zone de dépot.
Plusieurs étudiants sont dans ce cas, par peur que leurs documents ne soient pas sauvegardés ils cliquent sur le bouton "sauvegarder et terminer".

- [x] Possiblité d’avoir que 2 options dans les critereres pour la notation (type vrai/faux, minimun actuel 3)

- [x] Outil de gestion des copies :  permettre à l’enseignant de connaitre l’état des copies en cours de correction => ont-elles été attribuées si oui à qui ? sont-elle en attente de correction ou pas ? Avoir une visu de l'état d'avancement.

 - [x] Outil de recherche de copie :  Permettre une recherche par identifiant ou nom/prénom d'une copie et possibilité d'aller d'une page à une autre sans faire défiler toutes les pages

- [x] Dans la consultation des copies, nous avons la liste des devoirs rendus. Il serait bien d’avoir un listing des évaluateurs, le nom de l’étudiant avec les copies qu’il doit évaluer.

- [ ] Possibilité de corriger plus de copies que le nombre demandé

Bogues dans la version precedente a verifier/corriger

- [ ] Pas de copie attribuée pour certains étudiants, ils n’ont pas de copie à corriger (ils ont en revanche bien déposé la leur) voici quelques messages d’étudiants :
« aucune copie associée », ou « L'évaluation ne possède aucun critère pour corriger les copies. La correction est impossible »
- [ ] Lorsque la correction est possible, il y a plusieurs questions, certains n’ont pu corriger que la première, impossible de passer à la suite des questions et l’outil attribue la note de la première question pour la copie entière.
- [ ] Lors de retour en arrière côté correcteur, la plateforme indique un bug et valide la correction. Il n’est pas possible de faire de modification (soit afficher un message pour indiquant qu'une correction a deja ete soumise, soit permettre la reinitialisation/modification des correction - peut etre une option dans l'outil cote admin)
- [ ] Le mode anonyme, ne l’est pas :  En effet, en ouvrant le fichier deposé côté étudiant on voit en haut en vert le chemin d'accès informatique, indiquant le numéro d'étudiant et son nom/prénom ainsi que l'heure ou la copie a été envoyée
- [x] Le dossier generé par l'évaluation (hidden_...) ne contient pas toujours tous les rôles de l'EA ou du dossier parent des fois il y a des rôles qui manquent.

**Comment by clarophil** [comment]
Je pense qu'il vaut mieux pousser les étudiants à soumettre directement leur travail quitte à pouvoir le modifier ensuite (dans l'heure par exemple) sinon ils ne le font pas.

**Comment by LaurentGruber** [comment]
@ptsavdar @clarophil Pour le point 2, quelqu'un pourrait proposer des textes à la place de ceux existant ?

**Comment by LaurentGruber** [comment]
@ptsavdar pour le dernier point, ce serait via une option ? ça ne risque pas de déséquilibrer l'évaluation ? Pour le moment tu corriges le nombre de copie demandé et elles sont toutes corrigé ce nombre de fois ... Si on permet ça, on casse cet équilibre ...

**Comment by ptsavdar** [comment]
@LaurentGruber concernant le text, j'ai lance la demande de notre cote, je mets a jour dès que j'ai une réponse. Sinon pour le dernière point, des fois on a le problème qu'un etudiant a corrigé le nombre des copies requises mais comme il a soumis sa copie tard il y a personne pour le corriger. Si on permet aux gens de corriges plus des copies de ce qui est requis on pourrai faire face à ce problème. Et des fois on a aussi le problème inverse, qu'un étudiant a soumis sa copie mais il n'y a plus des copies à corriger du coup il ne peut pas avoir sa note (c'est le premier point de la partie bogues). Il faut prevoir soit de faire une liste avec des copies "bloqués" comme ceux-ci pour les afficher à l'enseignant soit qu'une copie soit corrigé pas plus de n personnes (mais là ça risque de changer la note déjà attribuée à la personne).

**Comment by clarophil** [comment]
Dans notre version il n'y a pas de popup lors de la soumission pourtant ce serait une bonne chose , proposition de texte 
"Votre ficher est sauvegardé, n'oubliez de cliquer sur le bouton Soumettre ma copie quand vous aurez ajouté tous les documents attendus."
Je propose donc de remplacer le bouton "Sauvegarder et terminer"  par "Soumettre ma copie"

Proposition de texte pour la soumission 
"Vous êtes sur le point de rendre votre copie. Cette action est définitive. Avez-vous vérifier que tous les documents sont bien présents dans le tableau des Documents ajoutés à la copie  ?"

**Comment by ptsavdar** [comment]
Les propositions de @clarophil me parraissent bonnes. De notre cote, la proposition que j'ai eu est la suivante:

"Votre ficher ou vos fichiers est ou sont  sauvegardé(s) dans votre zone de dépôt et peuvent être modifiés. Lorsque vous aurez finalisé votre dépôt,  cliquer sur le bouton « Soumettre ma copie » afin que celui ou ceux-ci passe(ent) soit(ent) corrigés par votre enseignant  . Votre travail sera alors considéré comme terminé, plus aucune modification ne sera possible ."

Quand on clique sur « soumettre ma copie » une pop-up pourrait indiquer :
« Attention en soumettant votre copie, vous considérez votre travail comme terminé, plus aucune modification ne sera possible.
Confirmez-vous que vous voulez-vous soumettre votre copie ? »
Oui / Non

Voila, sans etre oblige d'adopter ceci. Vous pouvez choisir ce qu'il vous parrait plus clair.

**Comment by nicolasjacquemet** [comment]
Compilé dans #4486
