### ISSUE TITLE
[CoreBundle] Trouver une alternative pour afficher les ressources "vus" et "non-vus"

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#3205]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master/7.0/etc.

Actuellement, la requette pour definir si une ressource à été déjà « vue » par un utilisateur fait une jointure avec le table des logs. Ceci, ne sera plus possible avec la nouvelle structure des logs (MongoDB). En plus cette jointure est trop couteuse pour une BDD avec un nombre de logs très important. Il serait preferé de créer une table uniquement pour ceci (ex. claro_resource_node_user_view) et faire la jointure avec ceci.

**Comment by Elorfin** [comment]
Je penses que @dtisch a déjà résolu le soucis : https://github.com/claroline/Distribution/commit/b3695aafbe1119a45bc2e4e9d58b844666342ae5.
