### ISSUE TITLE
[ExoBundle] Question graphique, bug d'affichage des zones en mode édition pour les images redimensionnées

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#3209]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.5.8

Bonjour,
En images ci-dessous.

Elles peuvent bouger pour une question et pas pour une deuxième puis après édition bouger pour toutes, bref c'est assez aléatoire.
Je peux rajouter que même pour un exo qui fonctionne son édition peut faire bouger toutes les zones des questions graphiques.
Bien à vous.

![image](https://user-images.githubusercontent.com/22524770/32697910-6bf3c32c-c79b-11e7-82fa-70b7213a2fb0.png)

![image](https://user-images.githubusercontent.com/22524770/32698164-8ecd921a-c7a0-11e7-9d52-944fc270bf99.png)

**Comment by alainertveldt** [comment]
J'ai le même comportement sur notre plate-forme. Et aussi la difficulté à redimensionner la zone. Version 10.6.2

**Comment by nicolasjacquemet** [comment]
je confirme le problème, en fait ce n'est pas aléatoire c'est un problème de redimensionnement des zones dans la vue d'édition lorsque l'on utilise de grandes images:
je prend une image assez grande (1024*769), qui nécessite d’être rétréci par la vue, et défini une zone:
![image](https://user-images.githubusercontent.com/3415139/33211677-e575a570-d11f-11e7-8517-b25b1329b99e.png)

après sauvegarde puis rafraîchissement de la page, la zone apparaît plus grande et correspond en fait à la zone pour l'image à sa taille d'origine:
![image](https://user-images.githubusercontent.com/3415139/33211744-2fd86364-d120-11e7-88b0-b10262c4782d.png)

Mais la zone est en fait enregistré correctement, c'est juste l'affichage en édition qui bug. Le comportement est correct en mode réponse:
![image](https://user-images.githubusercontent.com/3415139/33212084-b5ef2e64-d121-11e7-844d-0b87a93f1070.png)

Du coup en mode édition si on pense corriger la zone, c'est la qu'en fait on la fausse. Si je tente de lui remettre ses bonne dimensions, que je sauvegarde et rafraîchi la page, l'image apparaît cette fois correctement dans la vue d'édition, mais c'est en fait faux. Si je regarde la zone en mode réponse:
![image](https://user-images.githubusercontent.com/3415139/33212331-dd459dbc-d122-11e7-888a-c0669daa2ed7.png)

**Comment by Garakotxea** [comment]
**Merci pour cette info si détaillée.** 
En effet le collègue qui m'avait soumis le problème avait pensé que le taille de l'image pouvait être la cause de ce dysfonctionnement puisque d'autres exos fonctionnaient correctement, mais on n'avait pas pensé à ce que vous nous démontrez.
