### ISSUE TITLE
[ExoBundle]  Messages explicites 

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#3213]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      |  10.6.0/ 

Bonjour,
1) Quand l'utilisateur est autorisé à voir un quiz, dans un parcours, le bouton "Commencer" est présent.
![quiz1](https://user-images.githubusercontent.com/33163723/32839789-d8b83ac0-ca15-11e7-823c-cd5a4e7ebf81.png)
2) Quand l'utilisateur a déjà consommé ses essais, il n'y pas de messages explicites du genre "vous avez utilisé vos essais".
![quiz2](https://user-images.githubusercontent.com/33163723/32839951-721b77c2-ca16-11e7-9f13-d1d85bd50210.png)
Dans d'autres cas, j'ai même des messages d'erreur "contacter l'administrateur" quand l'erreur n'était qu'un quota consommé.

Est-ce possible d'avoir des messages plus précis : des critères ergonomiques de gestion des Erreurs qui soient différents de ceux informatifs qui ne sont pas des erreurs?

**Comment by npaille** [comment]
Quand le quiz est clos, idem = un message explicite dans un cadre "le quiz est fermé" serait une bonne chose.

**Comment by ngodfraind** [comment]
"Dans d'autres cas, j'ai même des messages d'erreur "contacter l'administrateur" quand l'erreur n'était qu'un quota consommé."

Comment la reproduire ? vous nous l'aviez dit mais j'ai oublié (je viens de corriger l'autre problème - il faudra attendre une future maj chez vous pour avoir le fix).
