### ISSUE TITLE
Radier utilisateurs d'espace

### ISSUE THREAD

**Issue by david42** [claroline/Distribution#3219]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.6.3

La suppression des rôles d'un utilisateur pour le radier d'un espace n'a plus d'effet.
L'utilisateur disparait bien de l'interface mais visiblement il n'y a pas d'effet en back, l'utilisateur ré-apparaît après rafraichissement de l'interface.

**Comment by david42** [comment]
Info complémentaire, voici l'URL appellée :  
DELETE /web/app.php/apiv2/role/7a99fe73-aa78-11e7-b642-0050568dc553/user?**ids[]**
Manquerait pas les ids dans le paramètre ids ?

**Comment by david42** [comment]
Cette route est appellée mais rien derrière pour traiter : 
apiv2/role/ => DELETE /web/app.php/apiv2/role/7b4f1871-aa78-11e7-b642-0050568dc553/user?ids[]=13764

Ne devrait on pas appeler celle-ci : 
{workspace}/remove/role/{role}/user/{user}

???

**Comment by LaurentGruber** [comment]
https://github.com/claroline/Distribution/pull/3220

**Comment by LaurentGruber** [comment]
le bugfix ne fonctionne que pour les admin ...
