### ISSUE TITLE
[ExoBundle] Export résultats/statistiques détaillé

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#3233]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.7.2

Plusieurs problèmes lié à l'export csv détaillé des résultats/statistiques des exercice (Afficher les statistiques > Export CSV):

- [x] Les réponses saisies ne sont pas placées dans la bonne colonne dans le cas d'un exercice avec affichage aléatoire des étapes. Les réponses sont insérées dans l'ordre de réponse du répondant, et ne sont pas triées pour correspondre à l'ordre général des questions/colonnes:
![image](https://user-images.githubusercontent.com/3415139/33064246-5821bcc6-cea5-11e7-874d-b3714d0e3cf9.png)

- [x] Egalement un probleme de décalage dans le cas d'une reponse de la part d'un utilisateur anonyme/non connecté, comme il n'y a ni nom ni prénom à ecrire dans l'export, ses réponses sont décalés vers la gauche:
![image](https://user-images.githubusercontent.com/3415139/33066572-f99fea9a-ceab-11e7-862f-cbcf3c6aff56.png)

- [ ] Problème similaire dans le cas d'un exercice en avec pioche d'étapes. Ici exemple d'une pioche de 2 étape parmi 3, les réponses sont affichées de manière linéaire et ne sont pas redistribuées sous leur question respective:
![image](https://user-images.githubusercontent.com/3415139/33064232-4ae09b22-cea5-11e7-9adf-8e00cf39e5f0.png)

- [ ] Problème similaire en cas de pioche par tag (ici pioche de 2 questions parmi 4), les réponses ne sont pas sous les bonnes questions:
![image](https://user-images.githubusercontent.com/3415139/33369835-14a380cc-d4f6-11e7-9b02-618f1bc614a1.png)

**Comment by nicolasjacquemet** [comment]
Apres vérification, un problème parmi les trois est toujours présent, et il impact également la pioche par tag. Issue ré-ouverte et modifié en conséquence.

**Comment by ngodfraind** [comment]
J'ai pu reproduire mais pour ça j'ai du faire mon questionnaire, répondre (tout va bien)... modifier le questionnaire et rerépondre (là ça ne va plus).
