### ISSUE TITLE
[ExoBundle] Problème d'atomicité entre la sauvegarde de réponses d'une page et la clôture d'un exercice

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#3247]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.x

Lorsque que l'on répond à un exercice et que l'on valide une page, le succès de la requête de sauvegarde des réponses n'est pas obligatoire pour que l'action suivante s’exécute (par exemple charger la page suivante, ou clôturer la copie). C'est à dire que si on fait "Suivant" pour passer à la page suivante, et que pour X raison la sauvegarde échoue, un message d'erreur est levé mais la vue avance quand même à la page suivante, sans que les réponses de la page précédente n'aient été sauvegardé. 
On a par exemple eu plusieurs fois le cas d’échec de sauvegarde de réponses lors de problèmes de charge serveur, cette opération étant d'autant plus susceptible d’être impactée qu'elle est lourde (sauvegarde des réponses + calcul de note)

Et c'est également vrai quand on clic sur "Terminer", ce qui est plus grave puisque l'action suivante est la clôture de la copie. Du coup la copie est terminée, pas moyen de revenir dessus, et la dernière page de réponse est perdue. 
Le problème est accentué par le fait qu'un premier calcul de note est affiché à l’étudiant dans la vue, à partir de toutes les réponses effectivement cochées, et qu'un second est réalisé pour l'enseignant à partir des réponses présentes en base de données. Du coup on nous a remonté plusieurs cas de disparité de note affiché entre l’étudiant et l'enseignant, l’étudiant voit par exemple qu'il a eu un 16/20, alors que de son coté l'enseignant voit un 5/20 car il manque une page de réponse dans la copie.

Exemple:
La sauvegarde de réponse échoue (simulé en modifiant le controller), et la requête de clôture part tout de même: 
![image](https://user-images.githubusercontent.com/3415139/33129895-c95cc696-cf91-11e7-8957-a49444c1c25b.png)

Une erreur est levée mais la vue est redirigé vers le message de fin;
![image](https://user-images.githubusercontent.com/3415139/33130306-2caff690-cf93-11e7-938f-e53a7cac7ecc.png)

Note coté étudiant:
![image](https://user-images.githubusercontent.com/3415139/33130332-48314b62-cf93-11e7-893b-f2fc5b4932ca.png)

Note coté enseignant:
![image](https://user-images.githubusercontent.com/3415139/33167552-27e8a930-d03e-11e7-86a8-7d76b38b8059.png)

**Comment by dtisch** [comment]
Si la note coté étudiant est différente de la note coté enseignant, cela pourrait-il vouloir dire que la vue a accès aux réponses, et donc qu'un utilisateur mal intentionné pourrait les consulter pour savoir comment répondre au questionnaire au mieux avant de soumettre ses réponses ?
