### ISSUE TITLE
Impossible de supprimer des utilisateurs d'un espace d'activité...

### ISSUE THREAD

**Issue by tikok974** [claroline/Distribution#3255]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | Claroline 10.6.4

Bonjour,
Je viens d'installer Claroline (10.6.4) sur une VM (type KVM) Debian 9.2 (1 socket - 2 cores / 8Go RAM). J'utilise actuellement le navigateur Firefox version ESR (52.5.0 - 64bits).

J'ai tenté de supprimer un utilisateur d'un espace d'activité en supprimant son rôle dans la colonne "rôle" (je présume que c'est comme cela que l'on fait). Celui ci disparaît bien de la liste mais lorsque je change d'onglet (par exemple je clic sur l'onglet "groupe") puis je reviens sur l'onglet "Utilisateurs", l'utilisateur supprimé auparavant **réapparaît de nouveau** dans la liste des utilisateurs ayant accès à l'espace d'activité !!!
J'ai regardé dans "/app/logs" du serveur s'il y a avait une erreur qui apparaissait mais malheureusement...rien.

Est-ce que quelqu'un a déjà eu ce soucis ?
Merci

**Comment by clarophil** [comment]
Oui c'est résolu https://github.com/claroline/Distribution/commit/5d49119144bcc4e77bfa790b5e83f97f0be6e6a0

**Comment by tikok974** [comment]
Re,

J'ai modifié le fichier comme indiqué  [ICI](https://github.com/claroline/Distribution/commit/5d49119144bcc4e77bfa790b5e83f97f0be6e6a0#diff-4312566bf4f211b88a9ac198fe49e4eb)

`
vim +243 ./vendor/claroline/distribution/main/core/Resources/views/Tool/workspace/roles/workspaceUsers.html.twig

`

Mais le problème est toujours présent :(

Une idée ?
Merci

**Comment by david42** [comment]
Il faut vider le cache synfony.
Néanmoins il semblerait exister un autre problème au niveau des droits. La suppression fonctionne en tant qu'admin de plateforme mais pas en tant que gestionnaire d'espace.

**Comment by tikok974** [comment]
Re,
Merci pour votre réponse mais comment je peux vider ce cache sur Claroline ?
J'ai exécuté:
`root@monserveur:/var/www/Claroline/vendor/symfony# php symfony cc`

...mais cela a eu aucun effet :(
Est-ce que j'exécute mal la commande ? (je suis novice avec Symfony...désolé)

Merci

**Comment by david42** [comment]
Depuis /var/www/claroline : 
php app/console cache:clear

Ou plus radical et plus efficace à mon gout : 
depuis  /var/www/claroline/app/cache
rm -rf ./*

**Comment by tikok974** [comment]
Salut David42,
J'ai tenté d'executer la commande ci-dessous:
'
root@cadlms:/var/www/Claroline# php app/console cache:clear
Clearing the cache for the dev environment with debug true
root@cadlms:/var/www/Claroline#
'
Pourquoi cette commande se fait uniquement pour le cache "dev" et non "prod" ...car ma plateforme est en "prod" et non en "dev" ?

En effaçant les fichiers de cache dans "/var/www/Claroline/app/cache/prod" c'était OK j'ai pu supprimer les utilisateurs.

Merci
