### ISSUE TITLE
Impossible d'assigner un objectif d'apprentissage à un utilisateur...

### ISSUE THREAD

**Issue by tikok974** [claroline/Distribution#3260]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | Claroline 10.6.4

Bonjour à tous,

Je viens d'installer Claroline (10.6.4) sur une VM (type KVM) Debian 9.2 (1 socket - 2 cores / 8Go RAM). J'utilise actuellement le navigateur Firefox version ESR (52.5.0 - 64bits).
J'ai créé ce [POST](https://forum.claroline.net/forum/subject/1115/messages/page/1/max) le forum de Claroline. En effet, J'ai tenté d'assigner un objectif d'apprentissage à un utilisateur mais lorsque j'indique son nom dans le champ de recherche, une fenêtre d'authentification apparaît ...bizarre non ?

J'ai tenté de mettre le login et le mot de passe de l'utilisateur. La plateforme s'ouvre sur l'espace de l'utilisateur mais aucun objectif apparaît pour celui-ci.

Lorsque l'on regarde ensuite la liste des utilisateurs pour cet objectif d'apprentissage, aucun utilisateur apparaît.

Je trouve d'ailleurs très étrange cette fenêtre de login qui s'ouvre ?

Est-ce qu'il y aurait un bug sur cet outil ?

Merci

**Comment by clarophil** [comment]
Bonjour, on utilise aussi la 10.6.4 et je n'ai pas ce comportement.  Quand on introduit le nom ou le prénom, on reçoit une liste d'utilisateurs.

**Comment by tikok974** [comment]
Bonjour,
J'ai re-testé avec un utilisateur "Administrateur" et ça marche !
En revanche, j'ai créé un utilisateur qui dispose d'un rôle que j'ai créé et appelé "Formateur". Ce rôle à les droits suivants (dans le tableau Administration > Gestion des rôles > Gérer les outils ):

- Gestion des utilisateurs
- Gestion des espaces d'activités
- Inscription à des espaces d'activités
- Bureau et accueil
- Suivi de la plateforme
- Statistiques de la plateforme
- Gestion des widgets
- Planification de tâches 
- Configuration des notifications
- Présences
- Référentiels de compétences
- Objectifs d'apprentissage
- Gestion des badges

...et là...problème !...j'ai le phénomène que j'ai décris ci-dessus qui apparaît.

J'ai tenté de vider le cache de Symphony mais le problème persiste.

C'est visiblement un problème de droit mais lequel dois-je attribuer en plus au rôle ?

Merci
