### ISSUE TITLE
Problème d'affichage d'une ressource de type "Activitée" après sa création... 

### ISSUE THREAD

**Issue by tikok974** [claroline/Distribution#3261]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | Claroline 10.6.4

Bonjour à tous,

Je viens d'installer Claroline (10.6.4) sur une VM (type KVM) Debian 9.2 (1 socket - 2 cores / 8Go RAM). J'utilise actuellement le navigateur Firefox version ESR (52.5.0 - 64bits).
J'ai créé ce [POST](https://forum.claroline.net/forum/subject/1141/messages/page/1/max) sur le forum Claroline. 
En effet, J'ai créé une ressource de type "Activitée" puis ensuite j'ai ouvert cette ressource et j'ai ajouté (grâce au bouton "Ajouter une ressource" 2 autres ressources. La première est un fichier "Scorm" pour Lightroom et l'autre une ressource de type "Parcours" que j'ai créé.

Lorsque je visualise la ressource "Activitée" (clic sur celle-ci dans "Ressources") et que je clic par exemple sur l'onglet correspondant à la ressource "fichier Scorm" ou "Parcours" ...un phénomène très étrange se produit...l'affichage disparaît au fur et a mesure...très lentement (voir captures dans le post sur le forum) et on finit par ne plus voir le contenu de chaque ressource !

Est-ce que quelqu'un a déjà rencontré ce soucis ?

Merci

**Comment by LaurentGruber** [comment]
la ressource activité va disparaitre dans les mois à venir ...

**Comment by tikok974** [comment]
Bonjour,
Etant donné que celle-ci va disparaître, j'ai tenté de l'enlever du menu pour ne pas que les gestionnaires des espaces d'activités utilise cette ressource. Dans les espaces d'activités concernés, j'ai donc décoché celle-ci dans: Paramètres -> ressources -> onglet "avancée" -> options

Mais...la ressource "Activité" est toujours visible ...et on peut toujours en créer !

Comment peut-on supprimer celle-ci du système ou la masquer ?

Merci
