### ISSUE TITLE
Coche sur choix de l'organisation pas conservé lorsque l'on ré-édite un groupe d'utilisateur...

### ISSUE THREAD

**Issue by tikok974** [claroline/Distribution#3262]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | Claroline 10.6.4

Bonjour,
Je viens d'installer Claroline (10.6.4) sur une VM (type KVM) Debian 9.2 (1 socket - 2 cores / 8Go RAM). J'utilise actuellement le navigateur Firefox version ESR (52.5.0 - 64bits).

Dans "Liste des utilisateurs > Liste des groupes", lorsque je créé un groupe, que je lui affecte un rôle et une organisation et que je valide le tout, lorsque je veux ré-éditer ce groupe (par exemple pour modifier son nom) seule la coche sur le rôle est présente...il manque la coche sur l'organisation choisi précédemment.

Est-ce un comportement est normal ou c'est un bug ?

Merci.

**Comment by LaurentGruber** [comment]
fixed by https://github.com/claroline/Distribution/pull/2901

**Comment by tikok974** [comment]
Bonjour,

OK...j'ai vu le ticket [2901](https://github.com/claroline/Distribution/pull/2901).
J'attends donc que le problème soit résolu.

Merci
