### ISSUE TITLE
wma & m4a audio formats cannot be read with embedded audio player

### ISSUE THREAD

**Issue by ChMat** [claroline/Distribution#3267]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.1.0

Our users upload audio files in different formats using the resource tool.

MP3 format can be read online with the audio player available.
WMA and M4A, on the other hand, can only be downloaded and played on the computer.

Is it a limitation of the plugin?

**Comment by LaurentGruber** [comment]
non, ça dépend des codec disponible sur le pc pour le navigateur ...
