### ISSUE TITLE
Problème abscence éléments dans menu de gauche après duplication comme modèle d'un espace d'activité...

### ISSUE THREAD

**Issue by tikok974** [claroline/Distribution#3271]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | Claroline 10.6.4

Bonjour à tous,

Je viens d'installer Claroline (10.6.4) sur une VM (type KVM) Debian 9.2 (1 socket - 2 cores / 8Go RAM). J'utilise actuellement le navigateur Firefox version ESR (52.5.0 - 64bits).

Lorsque je **duplique comme template** un espace d'activité (que cela soit en administrateur ou en gestionnaire), seul les éléments "Accueil", "Ressources", "Paramètres" et "Utilisateurs" sont accessibles dans le menu de gauche pour le nouvel espace. 
En effet, "la gestion des badges pour l'espace de travail", "Le tableau de bord" et d'autres éléments attribués à l'espace d'activité qui a servi de modèle ne sont pas visible dans le menu de gauche du nouvel espace d'activité !

En revanche, lorsque je duplique (mais pas comme template) un espace d'activité, tous les éléments du menu de gauche de l'activité qui a servi de modèle sont conservés.

Est-ce que c'est un comportement normal ou un bug ?

Merci

**Comment by LaurentGruber** [comment]
c'est le comportement normal, seul les outils "copiable" sont éditable dans le modèle

**Comment by tikok974** [comment]
Re,

C'est noté...merci
Bonne journée
