### ISSUE TITLE
Problème avec la sélection de l'outil couleur arrière plan et couleur texte dans l'édition d'une réponse pour un questionnaire...

### ISSUE THREAD

**Issue by tikok974** [claroline/Distribution#3272]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | Claroline 10.6.4

Je viens d'installer Claroline (10.6.4) sur une VM (type KVM) Debian 9.2 (1 socket - 2 cores / 8Go RAM). J'utilise actuellement le navigateur Firefox version ESR (52.5.0 - 64bits).

Dans la ressource "Questionnaire", j'ai ajouté un nouveau questionnaire.
Dans le mode "Edition" de ce nouveau questionnaire si:
On ajoute, par exemple, une question de type "Choix multiple" -> on édite **une réponse** (car cela semble se produire uniquement pour les réponses) -> on déroule l'éditeur de texte pour obtenir plus d'outils -> on tente de mettre une couleur d'arrière plan ou une couleur pour le texte...**aucun tableau pour sélectionner les couleurs apparaît** !

Quelqu'un peut reproduire ce problème ?

Merci

**Comment by Garakotxea** [comment]
Une piste ?
J'ai remonté ce problème dans un vieux ticket précédent. Dans mon cas le palette est hors fenêtre (en bas) et elle apparaît en dézoomant fortement. Cela pourrait-il être votre cas ?
Bien à vous.

**Comment by tikok974** [comment]
Bonjour,
Merci pour votre réponse. Je confirme ce que vous dites, il faut dé-zoomer fortement son navigateur pour permettre à la palette d'apparaître !

Bonne journée
