### ISSUE TITLE
[ExoBundle] Comportement erratique du curseur de l'éditeur tinyMCE dans l'exercice

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#3275]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.x

Je me permet de recréer une issue pour un problème enterré plusieurs pages en arrière (#2138) sur lequel on nous a relancé .

Le comportement du curseur dans l'éditeur riche tinyMCE de l'exercice est erratique il a tendance à revenir au début du champs de saisie (peu importe le champs à priori, énoncé, choix etc).
Quand on passe un champ en mode texte riche en ouvrant le tinyMCE, après le premier caractère saisie le curseur va systématiquement revenir au début du champ, de même dés que l'on veut insérer un retour à la ligne en appuyant sur entrée, le curseur revient au début du champ. Même chose lorsque l'on insert un lien vers une ressource, le curseur revient au début :

![peek 29-11-2017 16-29](https://user-images.githubusercontent.com/3415139/33383068-a96bef4c-d522-11e7-89d8-bac940c2f96a.gif)
Pas de soucis tant qu'on ne charge pas tinymce dans le champ.
Problème reproduit sous Chrome et Firefox à jour, et à priori ne se produit pas ailleurs que dans l'exercice.

**Comment by Elorfin** [comment]
Fixed in 11.x.
