### ISSUE TITLE
PB questionnaire type association

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3285]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/10.6.5/instance egreta.claroline

Bonjour,

J'ai créé un questionnaire avec une question de type association qui est pourtant décrite comme une association de 1 à plusieurs mais je ne peux pas associer plus d'un item (contrairement à l’appariement qui lui associe exclusivement des paires).

**Comment by nicvallet** [comment]
Bonjour,
Je confirme que ce problème est toujours présent.
De plus la réouverture en mode modification de cette question présente une anomalie à l'affichage : les liens entre chacun des items ne s'affichent plus ou sinon s'affiche mais de façon fantaisiste !!
Je suis sous Mozilla Firefrox version 58.0 - Claroline 10.10.12
![bug quiz appariement](https://user-images.githubusercontent.com/36445768/36152258-af7730de-10ca-11e8-9b38-64a6daa7cc6b.gif)
s.

**Comment by lgeschwine** [comment]
up
