### ISSUE TITLE
[ExoBundle] Question "classement" - Les items déjà choisis restent dans les propositions

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#3294]
| Q             | A
| Bug report?   | yes 
| Version?      | master/10.6

Bonjour,
Pour l'**exercice type "classement"**, quand on place un item dans un ensemble, il reste encore proposé sur la partie gauche. Quand l'exercice comprend beaucoup de propositions, on ne s'y retrouve plus.
Il serait utile que l'item déplacé disparaissent des propositions, tout en pouvant revenir en arrière quand on change d'avis.

![image](https://user-images.githubusercontent.com/33163723/33559040-d7f21bec-d90b-11e7-822c-427f98b6c1bb.png)

**Comment by nicolasjacquemet** [comment]
Bonjour,
ce n'est pas un bug, un élément de la partie gauche peut être lié à plusieurs éléments de la partie droite, ex:
![image](https://user-images.githubusercontent.com/3415139/33560115-1a70c36c-d90f-11e7-82c5-f6562d327ca3.png)

Par contre il pourrait être intéressant de rajouter une indication visuelle qu'un élément de gauche a déjà été utilisé, de notre coté des utilisateurs nous ont également remonté le manque de lisibilité de ce type de question.
