### ISSUE TITLE
Questionnaires - Problèmes avec l'ajustement de la taille d'une zone de réponse pour une question de type "Graphique" + duplication...

### ISSUE THREAD

**Issue by tikok974** [claroline/Distribution#3306]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | Claroline 10.6.4

Bonjour,
J'ai installé Claroline (10.6.4) sur une VM (type KVM) Debian 9.2 (1 socket - 2 cores / 8Go RAM). J'utilise actuellement le navigateur Firefox version ESR (52.5.0 - 64bits).

Lorsque nous créons une étape dans un questionnaire et que nous choisissons d'ajouter une question de type "Graphique", la zone de réponse (rectangulaire ou ronde) est ajustable.
En revanche, dans la même étape, lorsque nous validons cette réponse et que l'on tente ensuite de re-modifier la taille de la zone de réponse, impossible d'utiliser les différents points d'ajustement. **Ces derniers restent figés !**

![capture d ecran_2017-12-08_16-10-27](https://user-images.githubusercontent.com/20242955/33772375-ba7f2eb6-dc34-11e7-9fe0-43e3bec372c0.png)

Par contre si nous créons une nouvelle étape du même type (graphique), la zone de réponse (rectangulaire ou ronde) peut-être ajusté.

En fait, tant que la réponse n'a pas été sauvegardé, la taille de la zone de réponse (rectangulaire ou ronde) reste modifiable !

De plus, j'ai remarqué aussi que lorsque je tentais de modifier la taille d'une zone de réponse et que je n'y arrivais pas, **je ne pouvais pas non plus dupliquer la question concerné !**

Quelqu'un a t'il déjà constaté ces problèmes ?

Merci

**Comment by Elorfin** [comment]
Duplicate: https://github.com/claroline/Distribution/issues/3660.
