### ISSUE TITLE
Problèmes de score (multiples) LEA

### ISSUE THREAD

**Issue by CatherineVinci** [claroline/Distribution#3315]
Lors du testing des exercices LEA, plusieurs pb de score apparaissent. 

**1) Des scores supérieurs au maximum lorsque plusieurs choix sont possibles MALGRE une limitation à un score défini.**

EX.

![image](https://user-images.githubusercontent.com/29223614/33986740-d02db6fe-e0be-11e7-88f8-08b83aae20a3.png)

 (ici, le nombre de pointeurs est supérieur au nombre de réponses attendues, mais le score de l'exercice est limité à 30)

![image](https://user-images.githubusercontent.com/29223614/33986851-297a61f8-e0bf-11e7-8bc2-14f7296aa505.png)
 (Même problème avec des choix de réponses multiples)

**2) Des scores inférieurs au résultat réellement obtenu** 

ex. 

![image](https://user-images.githubusercontent.com/29223614/33986968-970a3874-e0bf-11e7-933f-4ba3b12603ca.png)

(2 réponses correctes sur trois et pourtant un score de 0/3)

![image](https://user-images.githubusercontent.com/29223614/33987121-0d7bb096-e0c0-11e7-9cd4-2e33b248b504.png)

Même problème 

Ce pb de score est extrêmement récurrent. Il affecte et invalide près de la moitié des exercices. Il va aussi bien dans le sens de scores inférieurs à la réussite réelle que dans des réussites plus grandes que le maximum autorisé. Et ce malgré une définition du score attendu.

| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

**Comment by CatherineVinci** [comment]
http://lea.claroline.com/resource/open/ujm_exercise/818#/test

http://lea.claroline.com/resource/open/ujm_exercise/842#/test

http://lea.claroline.com/resource/open/ujm_exercise/807#/test

http://lea.claroline.com/resource/open/ujm_exercise/795#/test

**Comment by ngodfraind** [comment]
J'ai pu reproduire dans un cas un truc bizarre. Dans les questions graphiques, si la zone de réponses est assez grande, on peut y mettre plusieurs pointeurs. Chaque pointeur compte comme un point (ce qui est faux, un seul pointeur devrait être compté).

**Comment by ngodfraind** [comment]
Reproduit pour le 2nd (choix multiple).

**Comment by ngodfraind** [comment]
J'ai pu "reproduire" le 3ieme.

**Comment by ngodfraind** [comment]
Normalement tous ces problèmes sont corrigés par #3465.
La sensibilité aux majuscules n'est par contre pas encore implémentée dans les textes à trous.
