### ISSUE TITLE
Déplacement des zones de sélection de texte LEA

### ISSUE THREAD

**Issue by CatherineVinci** [claroline/Distribution#3317]
Pb lors de la modification pour amélioration des exercices : quand je veux déplacer ou redimensionner des zones graphiques de sélection, elles se "déplacent" entre le moment où on conçoit l'exercice et le moment où on le teste. 

Mode concepteur de l'exercice : les zones graphiques sont au bons endroits : 

![image](https://user-images.githubusercontent.com/29223614/33987727-339bae14-e0c2-11e7-8b66-a1cb1ea3d83c.png)

mode utilisateur qui fait l'exercice (et donc échoue) : les zones graphiques ont bougé
![image](https://user-images.githubusercontent.com/29223614/33987673-040e4936-e0c2-11e7-9d09-6b0ef5dec6ca.png)

| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

**Comment by clarophil** [comment]
http://lea.claroline.com/resource/open/ujm_exercise/820#/test

**Comment by clarophil** [comment]
C'est lors de la modification de la question qu'il y a un problème, voici ce que j'ai constaté 
1 créer la question graphique
2 tester -> ça marche
3 éditer directement la question et sauver
4 tester -> ça marche
5 quitter l'exercice
6 revenir dans l'exercice et éditer la question -> la zone de sélection à bouger !
7 mettre la zone à sa place initiale et sauver
8 tester -> ça ne marche plus et la réponse attendue montre bien que la zone à bouger

Conclusion quand on modifie une question graphique les zones ne sont pas correctement positionnées.

**Comment by nicolasjacquemet** [comment]
Doublon probable de #3209

**Comment by ngodfraind** [comment]
Reproduit.

Par contre c'était que dans l'éditeur que la réponse a bougé chez moi. En chipotant un peu tout s'est remit comme par magie (je ne sais pas sur quoi j'ai cliqué)/

**Comment by clarophil** [comment]
Oui c'est à l'édition que ça bug
