### ISSUE TITLE
Pb ordonnancement LEA

### ISSUE THREAD

**Issue by CatherineVinci** [claroline/Distribution#3319]
1) Les questions d'ordonnancement ne se "mélangent" pas toujours dans la version utilisateur... de sorte que c'est immédiatement le bon ordonnancement qui apparait 

EX. version conception de l'exercice : 

![image](https://user-images.githubusercontent.com/29223614/33990237-8465f4aa-e0ca-11e7-9109-de4bfb93624e.png)

Version de l'utilisateur qui fait l'exercice : 

![image](https://user-images.githubusercontent.com/29223614/33990190-62548c8c-e0ca-11e7-91ab-b298e601abd2.png)

2) j'ai modifié et supprimé deux sélection dans un exercice, mais le programme fait comme si elles étaient encore là et signale la réponse comme fausse...  + problème des sélections qui ne se mélangent pas !

ex.  nouvelle version avec 2 sélection en moins 
![image](https://user-images.githubusercontent.com/29223614/33990404-2378ab0a-e0cb-11e7-8fe1-fe6765a0b170.png)

Corrigé qui tient compte de ces 2 bandelettes comme si elles existaient encore
![image](https://user-images.githubusercontent.com/29223614/33990344-e7154f60-e0ca-11e7-95d8-7987a6c70e05.png)

et réponse attendue sans les 2 bandelettes 

![image](https://user-images.githubusercontent.com/29223614/33990380-0c59f924-e0cb-11e7-9d2b-1e622d47d71e.png)

| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

**Comment by CatherineVinci** [comment]
http://lea.claroline.com/resource/open/ujm_exercise/841#/test

**Comment by ngodfraind** [comment]
Je m'y attaque...
J'en profite pour dire que les liens sont vraiment pratique. Ça me permet de télécharger l'exercice et de reproduire localement.

**Comment by ngodfraind** [comment]
J'ai pu reproduire une erreur similaire lors du test de l'exercice, mais lorsqu'on le fait "pour de vrai" avec sauvegarde de la correction, c'est bon.

**Comment by clarophil** [comment]
oui j'ai remarqué la même chose
