### ISSUE TITLE
LEA exercice verrouillé? Comment déverrouiller? 

### ISSUE THREAD

**Issue by CatherineVinci** [claroline/Distribution#3321]
Un exercice semble verrouillé et pas moyen, même en mode administrateur de le déverrouiller 

![image](https://user-images.githubusercontent.com/29223614/33990652-03f5f6e2-e0cc-11e7-96fe-f13062a663f6.png)

Exercice concerné : C4-S2-APAN2-C-C1-AD1
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

**Comment by LaurentGruber** [comment]
http://lea.claroline.com/resource/open/ujm_exercise/902#/editor

Warning: Failed prop type: The prop `item.cells[1].data` is marked as required in `GridPlayer`, but its value is `undefined`.
    in GridPlayer (created by PlayerComponent)
    in PlayerComponent (created by Connect(PlayerComponent))
    in Connect(PlayerComponent) (created by Quiz)
    in div (created by PageContent)
    in PageContent (created by Resource)
    in main (created by PageWrapper)
    in PageWrapper (created by Page)
    in Page (created by RoutedPage)
    in Router (created by Router)
    in Router (created by RoutedPage)
    in RoutedPage (created by Resource)
    in Resource (created by Resource)
    in Resource (created by Connect(Resource))
    in Connect(Resource) (created by Connect(Connect(Resource)))
    in Connect(Connect(Resource)) (created by Quiz)
    in Quiz (created by Connect(Quiz))
    in Connect(Quiz) (created by DragDropContext(Connect(Quiz)))
    in DragDropContext(Connect(Quiz))
    in Provider
react_dll-bc8366747a0abc870291.js:1:19721
Warning: Failed prop type: The prop `cell` is marked as required in `GridCell`, but its value is `undefined`.
    in GridCell (created by GridPlayer)
    in GridPlayer (created by PlayerComponent)
    in div (created by ItemPlayer)
    in ItemPlayer (created by PlayerComponent)
    in div (created by Panel)
    in div (created by Panel)
    in Panel (created by PlayerComponent)
    in div (created by PlayerComponent)
    in PlayerComponent (created by Connect(PlayerComponent))
    in Connect(PlayerComponent) (created by Quiz)
    in div (created by PageContent)
    in PageContent (created by Resource)
    in main (created by PageWrapper)
    in PageWrapper (created by Page)
    in Page (created by RoutedPage)
    in Router (created by Router)
    in Router (created by RoutedPage)
    in RoutedPage (created by Resource)
    in Resource (created by Resource)
    in Resource (created by Connect(Resource))
    in Connect(Resource) (created by Connect(Connect(Resource)))
    in Connect(Connect(Resource)) (created by Quiz)
    in Quiz (created by Connect(Quiz))
    in Connect(Quiz) (created by DragDropContext(Connect(Quiz)))
    in DragDropContext(Connect(Quiz))
    in Provider
react_dll-bc8366747a0abc870291.js:1:19721
TypeError: this.props.cell is undefined
[En savoir plus]
claroline-distribution-plugin-exo-quiz-518e40e97a1a8e7efc59.js:30:15626
TypeError: internalInstance is null
[En savoir plus]
react_dll-bc8366747a0abc870291.js:18:12535
