### ISSUE TITLE
pas d'accès à la correction LEA

### ISSUE THREAD

**Issue by CatherineVinci** [claroline/Distribution#3322]
Sur un exercice, pas moyen d'avoir accès à la correction

Exercice 
TS-C4-S1-APAN1-C-B2-AB1

![image](https://user-images.githubusercontent.com/29223614/33990779-608669aa-e0cc-11e7-86c2-74deefc88385.png)
 Le bouton identifié ne fonctionne pas... 
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

**Comment by LaurentGruber** [comment]
http://lea.claroline.com/resource/open/ujm_exercise/738#/papers/d7e3632e-0ae8-45ea-8137-4000cc64932f

Warning: Failed prop type: The prop `stats.total` is marked as required in `AnswerStats`, but its value is `undefined`.
    in AnswerStats (created by WordsPaper)
    in WordsPaper (created by Paper)
    in div (created by Panel)
    in div (created by Panel)
    in Panel (created by Paper)
    in div (created by Paper)
    in div (created by Paper)
    in Paper (created by Connect(Paper))
    in Connect(Paper) (created by Quiz)
    in div (created by PageContent)
    in PageContent (created by Resource)
    in main (created by PageWrapper)
    in PageWrapper (created by Page)
    in Page (created by RoutedPage)
    in Router (created by Router)
    in Router (created by RoutedPage)
    in RoutedPage (created by Resource)
    in Resource (created by Resource)
    in Resource (created by Connect(Resource))
    in Connect(Resource) (created by Connect(Connect(Resource)))
    in Connect(Connect(Resource)) (created by Quiz)
    in Quiz (created by Connect(Quiz))
    in Connect(Quiz) (created by DragDropContext(Connect(Quiz)))
    in DragDropContext(Connect(Quiz))
    in Provider
react_dll-bc8366747a0abc870291.js:1:19721
Warning: Failed prop type: Invalid prop `valid` of type `number` supplied to `WarningIcon`, expected `boolean`.
    in WarningIcon (created by PairPaper)
    in PairPaper (created by Paper)
    in div (created by Panel)
    in div (created by Panel)
    in Panel (created by Paper)
    in div (created by Paper)
    in div (created by Paper)
    in Paper (created by Connect(Paper))
    in Connect(Paper) (created by Quiz)
    in div (created by PageContent)
    in PageContent (created by Resource)
    in main (created by PageWrapper)
    in PageWrapper (created by Page)
    in Page (created by RoutedPage)
    in Router (created by Router)
    in Router (created by RoutedPage)
    in RoutedPage (created by Resource)
    in Resource (created by Resource)
    in Resource (created by Connect(Resource))
    in Connect(Resource) (created by Connect(Connect(Resource)))
    in Connect(Connect(Resource)) (created by Quiz)
    in Quiz (created by Connect(Quiz))
    in Connect(Quiz) (created by DragDropContext(Connect(Quiz)))
    in DragDropContext(Connect(Quiz))
    in Provider
react_dll-bc8366747a0abc870291.js:1:19721
Unhandled promise rejection 
TypeError: props.stats.unpaired is undefined
Stack trace:
[object Object]
commons-518e40e97a1a8e7efc59.js:18:5274
TypeError: internalInstance is null
[En savoir plus]
react_dll-bc8366747a0abc870291.js:18:12535
