### ISSUE TITLE
Problème pour voir les utilisateurs et les groupes enregistrés...cela malgré les bons droits sur le rôle.

### ISSUE THREAD

**Issue by tikok974** [claroline/Distribution#3331]
| Q             | A
| ------------- | ---
| Bug report ?   | yes
| Version?      | Claroline 10.6.4

Bonjour,
J'ai installé Claroline (10.6.4) sur une VM (type KVM) Debian 9.2 (1 socket - 2 cores / 8Go RAM). J'utilise actuellement le navigateur Firefox version ESR (52.5.0 - 64bits).

J'ai créé un rôle "Collaborateurs" auquel j'ai affecté des droits (dont "Gestion des utilisateurs" et "Gestion des rôles") via le menu "Administration" -> "Gestion des rôles" -> "Gérer les outils" .
Lorsque je créé un utilisateur et que je lui donne le rôle "Collaborateurs", **celui-ci ne voit pas les autres utilisateurs de la plateforme...la liste est vide ! Il ne voit pas non plus les groupes créés !**
Par contre, il peut créer un nouvel utilisateur mais celui-ci ne sera pas non plus visible dans sa liste.
Il faut se déconnecter puis se reconnecter en "Administrateur" pour pouvoir voir tous les utilisateurs et groupes.
J'ai remarqué cependant que l'un de mes utilisateurs qui a été créé **avant** que le rôle "Collaborateurs" le soit et ...à qui j'ai affecté ce rôle "Collaborateurs"... peut voir tous les utilisateurs et les groupes. Cela, malgré qu'il ne soit pas administrateur de la plateforme !

Étrange tout cela...non ?
Est-ce que quelqu'un d'autre que moi a des problèmes de droits de ce genre sur sa plateforme ?

Merci

**Comment by LaurentGruber** [comment]
corrigé à partir de la 10.8.0
