### ISSUE TITLE
Gestion des utilisateurs ne renvoie plus rien

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#3338]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.8

Bonjour
Depuis la màj 10.8, la gestion des utilisateurs ne renvoie plus aucun résultat. 
La mise à jour de la db via claroline:test_update n'y change rien.
Je ne vois rien dans le fichier log.

Bonne journée,

**Comment by LaurentGruber** [comment]
npm install fullcalendar
npm run webpack

**Comment by l-matt** [comment]
super, merci beaucoup
