### ISSUE TITLE
[ExoBundle]Sauvegarde des options d'un questionnaire impossible

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#3356]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.8.1

Bonjour, 
Il est impossible de valider l'édition d'un questionnaire.
Dans les paramètres générales du questionnaire rubrique "passation", j'ai une erreur du type "cette valeur ne doit pas être vide", pourtant tous les champs sont renseignés (il manque cependant le champ : "Nombre de tentative maximum" présent dans les versions précédentes)
Aussi le petit triangle rouge indique cette erreur sur la rubrique Tirages des étapes où il ne manque là encore aucune valeur.
Ci-joint un screenshot de l'erreur empêchant la validation du questionnaire

![qcm](https://user-images.githubusercontent.com/27862129/34560298-8a8c62ca-f145-11e7-9cc8-3205b4b4e1d0.png)

**Comment by LaurentGruber** [comment]
fixe sur 10.9
