### ISSUE TITLE
Affichage des groupes et utilisateurs

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#3361]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.8.2

Bonjour,

Lorsqu'on édite le profil d'un utilisateur (qu'on a recherché par exemple), les groupes auxquels il appartient ne s'affichent toujours pas.
Après avoir réactualisé en cliquant sur l’icône utilisateurs, il est possible d'avoir accès aux groupes d'un utilisateur via la rubrique "groupes".
Il arrive que la recherche renvoie d'autres groupes auxquels l'utilisateur n'appartient pas.
En effet les groupes auxquels appartient l'utilisateur de la recherche précédente seront affichés ici.

Par ailleurs lorsque je souhaite consulter les utilisateurs inscrits dans un groupe en sélectionnant le groupe en question via l’icône groupe, je n'ai aucun résultat.

Merci

**Comment by LaurentGruber** [comment]
Corrige 10.8.3

**Comment by l-matt** [comment]
l'erreur est toujours présente, je n'ai pas lancé test_update entre 10.8.1 et 10.8.3.
Est-ce du à cela ? 
Merci
