### ISSUE TITLE
Ajouter photo au profil

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#3367]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 10.8.3

Bonjour, 

Je ne vois plus la possibilité d'ajouter une photo à son profil en éditant ce dernier.
Les photos associées au profil des utilisateurs depuis les versions précédentes de Claroline s'affichent très bien.
Merci

**Comment by alainertveldt** [comment]
Je me pose la même question. Et comment modifier la photo. Un élève aimerait modifier sa photo mais on ne trouve plus où?

**Comment by ngodfraind** [comment]
On l'a remit dans l'administration, je ne sais pas si c'est déjà dans le profil.

**Comment by ngodfraind** [comment]
C'était pas dans le profil mais ça a été fait sur #3457
