### ISSUE TITLE
[TinyMce] security holes

### ISSUE THREAD

**Issue by ngodfraind** [claroline/Distribution#337]
2 security holes:
- Tinymce allows iframe (so you can easily deface a page using them and a bit of css).
- Tinymce doesn't sanitize all javascripts 

```
<script src="xxx"></script> 
```

is allowed so it's not working at all.

**Comment by LaurentGruber** [comment]
users use it to embed service as googleForm ... and they must authenticate to do it soo must we corect it ?

**Comment by CPASimUSante** [comment]
maybe add a checkbox in the general admin : "allow unsecure scripts in editor" ?
