### ISSUE TITLE
import workspace

### ISSUE THREAD

**Issue by david42** [claroline/Distribution#339]
I have an error to import a WS.

> Unrecognized option "0" under "data" 

I join the zip of the export:
[DUT+ROANNE.zip](https://github.com/claroline/Distribution/files/272552/DUT.ROANNE.zip)

**Comment by ngodfraind** [comment]
Wich version are you using ?
It worked on my distribution installation.

**Comment by david42** [comment]
I use the dev-master in local

**Comment by ngodfraind** [comment]
from the distribution repo ?

**Comment by david42** [comment]
yes

**Comment by ngodfraind** [comment]
Are all plugins properly enabled ?
Do you have a more complete stacktrace ?

**Comment by david42** [comment]
Stack Trace

    in vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php at line 309  -
                // if extra fields are present, throw exception
                if (count($value) && !$this->ignoreExtraKeys) {
                    $msg = sprintf('Unrecognized option%s "%s" under "%s"', 1 === count($value) ? '' : 's', implode(', ', array_keys($value)), $this->getPath());
                    $ex = new InvalidConfigurationException($msg);
                    $ex->setPath($this->getPath());
                    throw $ex;

....
....
....

CRITICAL - Uncaught PHP Exception Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: "Unrecognized option "0" under "data"" at /var/www/Claroline/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php line 309
