### ISSUE TITLE
ANNONCES

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#3392]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      |10.9.0
Lors de la rédaction d'une annonce, le champ "contenu" est toujours considéré comme étant vide. De plus lorsqu'on désire utiliser les options de mise en page pour insérer une image un lien, le champ se vide même si on a déjà écrit quelque chose.
Donc comme le champ "contenu" est considéré comme vide l'annonce ne peut être enregistrée et donc publiée.

![image](https://user-images.githubusercontent.com/31481850/34826149-c78c9600-f6d5-11e7-886f-5b53c3ebd460.png)

**Comment by Elorfin** [comment]
Corrigé dans les 10.9.1
