### ISSUE TITLE
User management: impossible to create new user.

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#3397]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.9.0

Impossible to create new user. I don't see what has to be corrected in the given information.

![bug_user](https://user-images.githubusercontent.com/14308826/34878025-db7b7112-f7a8-11e7-8ee4-c5c442704f5d.JPG)

**Comment by lgeschwine** [comment]
Bonjour,
Le bug persiste sur la version 10.9.2.
Merci,

**Comment by ngodfraind** [comment]
Faut que j'essaye de reproduire, ça ne fonctionnait pas à un moment et j'ai pu le corriger. A voir si c'est la même erreur.

**Comment by om64** [comment]
Solved in 10.9.5
