### ISSUE TITLE
[Collecticiel]Remarques Philippe DEKIMPE

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#34]
_From @purplefish32 on March 30, 2016 12:0_

_From @ericvincenterv on November 3, 2015 9:9_

Reçus plusieurs emails (octobre 2015)
- mettre un bouton "Soumettre ou Envoyer" à la place de la demande de transmission
- lorsqu’un étudiant répond à un commentaire envoyé par un enseignant, l’enseignant ne le voit pas, je propose de renommer la colonne « Etat » par « Commentaire », d’y mettre un bouton « Commenter » tant qu’il n’y a pas de commentaire et mettre le nombre de commentaires avec les nouveaux comme dans l’interface de l’étudiant 

A discuter avec JJQ.

_Copied from original issue: InnovaLangues/CollecticielBundle#148_

_Copied from original issue: claroline/Claroline#762_

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#28

**Comment by ericvincenterv** [comment]
cc @jj-quintin : ton avis ?

**Comment by jj-quintin** [comment]
Pas certain que ce soit encore à l'ordre du jour dans la mesure où ces demandes datent me semble-t-il d'avant les changements apportés sur l'interface

Propositions : laisser en l'état pour l'instant et faire un point après retour d'usages du début de l'année. On rassemblera toutes les demandes d'améliorations de ce type

**Comment by jj-quintin** [comment]
De ce fait adapter le ticket en milestone futur + question (à discuter)
