### ISSUE TITLE
Administration : user management

### ISSUE THREAD

**Issue by david42** [claroline/Distribution#340]
I haven't the form to add a new user in the user management.

**Comment by ngodfraind** [comment]
![user](https://cloud.githubusercontent.com/assets/1397430/15394025/b5287c3e-1dd0-11e6-9e0a-2d7d4521bfb0.png)

"Nouveau"

Does it appear ?

**Comment by david42** [comment]
This is my screen:

![user_management](https://cloud.githubusercontent.com/assets/1311128/15395142/d6173c90-1dd6-11e6-9dac-509c365e9ac4.png)

**Comment by ngodfraind** [comment]
you must run ```npm run watch```

**Comment by david42** [comment]
Yes but I have the same problem.
The other menus work.

**Comment by ngodfraind** [comment]
Can you look at the console error ?

2016-05-19 15:43 GMT+02:00 david42 <notifications@github.com>:

> Yes but I have the same problem.
> The other menus work.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Distribution/issues/340#issuecomment-220327897>
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by david42** [comment]
Nothing in the console:

![console](https://cloud.githubusercontent.com/assets/1311128/15396158/15983302-1ddb-11e6-9b47-9263022ac4d5.png)

**Comment by ngodfraind** [comment]
This is weird. Is the user script found ?
=> 'Réseau' tab

**Comment by david42** [comment]
![network](https://cloud.githubusercontent.com/assets/1311128/15396486/b08250fe-1ddc-11e6-9696-0996e1affd3c.png)

**Comment by david42** [comment]
I didn't use in dev:
npm run-watch
