### ISSUE TITLE
Erreur : sudo npm run webpack

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#3400]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?     10.9.1

J'ai pas de bureau visible dans Claroline.
J'ai relancé sudo npm run webpack
voici le résultat

> claroline@1.0.0 webpack /var/www/clients/client1/web23/web/claroline-16.09
> export NODE_ENV=production && rm -rf web/dist/* && npm run dll && node_modules/webpack/bin/webpack.js --config=vendor/claroline/distribution/webpack.prod.js --progress --colors --display-error-details && npm run uglify

> claroline@1.0.0 dll /var/www/clients/client1/web23/web/claroline-16.09
> node_modules/webpack/bin/webpack.js --config=vendor/claroline/distribution/webpack.dll.js --progress --colors --display-error-details

sh: node_modules/webpack/bin/webpack.js: Aucun fichier ou dossier de ce type

npm ERR! Linux 2.6.32-042stab123.3
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dll"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! claroline@1.0.0 dll: `node_modules/webpack/bin/webpack.js --config=vendor/claroline/distribution/webpack.dll.js --progress --colors --display-error-details`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the claroline@1.0.0 dll script 'node_modules/webpack/bin/webpack.js --config=vendor/claroline/distribution/webpack.dll.js --progress --colors --display-error-details'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the claroline package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/webpack/bin/webpack.js --config=vendor/claroline/distribution/webpack.dll.js --progress --colors --display-error-details
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs claroline
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls claroline
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2018-01-12T18_28_24_351Z-debug.log

npm ERR! Linux 2.6.32-042stab123.3
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "webpack"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! claroline@1.0.0 webpack: `export NODE_ENV=production && rm -rf web/dist/* && npm run dll && node_modules/webpack/bin/webpack.js --config=vendor/claroline/distribution/webpack.prod.js --progress --colors --display-error-details && npm run uglify`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the claroline@1.0.0 webpack script 'export NODE_ENV=production && rm -rf web/dist/* && npm run dll && node_modules/webpack/bin/webpack.js --config=vendor/claroline/distribution/webpack.prod.js --progress --colors --display-error-details && npm run uglify'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the claroline package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     export NODE_ENV=production && rm -rf web/dist/* && npm run dll && node_modules/webpack/bin/webpack.js --config=vendor/claroline/distribution/webpack.prod.js --progress --colors --display-error-details && npm run uglify
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs claroline
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls claroline
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2018-01-12T18_28_24_385Z-debug.log

**Comment by ngodfraind** [comment]
Il faut lancer `npm install && npm run bower` avant.
