### ISSUE TITLE
BUG: "se connecter en tant que"

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#3403]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.9.2

Lorsque dans un espace d'activité, on utilise "se connecter en tant que"
![image](https://user-images.githubusercontent.com/31481850/34913489-403f53c8-f8ff-11e7-9f80-708473f38ed2.png)
ça bloque, plus rien ne se passe....
En fermant le navigateur on n'a plus accès non plus, on est obligé de "remettre le navigateur à zéro", vider cache et cookies pour pouvoir se reconnecter avec le navigateur. Tester avec firefox et chrome et même soucis.
Pour info, même si ça plante lorsqu'on est sous firefox, on peut travailler (sans utiliser "se connecter en tant que") sous chrome, donc la plate-forme reste accessible c'est vraiment l'appel à cette fonctionnalité qui plante.
D'avance merci

**Comment by flow39** [comment]
effectivement, c'est problématique. La procédure de réinitialisation des navigateurs n'est pas forcément simple pour certains utilisateurs.

**Comment by ngodfraind** [comment]
Corrigé pour la prochaine maj par https://github.com/claroline/Distribution/pull/3445.
