### ISSUE TITLE
Bug in the Announcement Bundle

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#3404]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.9.0

When trying to add an annoucement, even if a text is written, I'm asked to add a value.

![bug_announcement](https://user-images.githubusercontent.com/14308826/34913722-822d4762-f905-11e7-9a58-fb1901210abb.JPG)

**Comment by Elorfin** [comment]
This is fixed in 10.9.1
