### ISSUE TITLE
Erreur: boutons Date et heure ne fonctionnent pas dans évaluation

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#3407]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.9.2

On peut entrer manuellement mais pas en cliquant sur les boutons les dates et heures dans les paramètres de l'évaluation
![image](https://user-images.githubusercontent.com/31481850/34927756-dfc691f4-f9b8-11e7-86a0-2c9c148aa586.png)

**Comment by LaurentGruber** [comment]
évaluation est completement refait dans la v11 donc ça devrait être réglé
