### ISSUE TITLE
Bug: espace perso non accessible

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#3408]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.9.2

j'ai des utilisateurs qui ont été créés en ce début d'année scolaire (ceux du groupe 1c3_17_18) qui n'ont pas accès à leur espace perso alors qu'ils en auraient bien un

![image](https://user-images.githubusercontent.com/31481850/34931689-41d487f4-f9d0-11e7-84ee-ea14a4e4de3b.png)

![image](https://user-images.githubusercontent.com/31481850/34931710-5e04d2ee-f9d0-11e7-882c-d77771848f70.png)

cette élève a été transférée de 1c3_17_18 en 1c1_17_18 mais elle n'a toujours pas accès à son espace.

**Comment by ngodfraind** [comment]
Je vais voir ça.

**Comment by ngodfraind** [comment]
Yep, je confirme, j'investigue un peu.

**Comment by ngodfraind** [comment]
L'espace est bien créé mais il manque le role admin à l'utilisateur pour qu'il s'affiche dans les liste. L'utilisateur est bien le créateur de l'EA (probablement un bug d'une version antérieure lors de la création d'un EA).

Je vais rajouter un script qui permet de restaurer ce genre de problème.

**Comment by ngodfraind** [comment]
Faudra lancer la commande de restoration de https://github.com/claroline/Distribution/pull/3456 et ça sera réglé !
