### ISSUE TITLE
bug sur création d'une sous-organisation

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#3417]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.9.3
l'utilisation du menu "créer une sous-organisation" ne fonctionne pas, le formulaire de création n'apparait pas après avoir cliqué sur le bouton 
<img width="948" alt="claro_erreur-creation-orga" src="https://user-images.githubusercontent.com/7293233/34992534-c7801ab4-facd-11e7-92fd-5e23ec057983.png">

**Comment by ngodfraind** [comment]
Reproduit.

**Comment by ngodfraind** [comment]
Le bouton est là mais il n'y a pas d'implémentation derrière encore.
