### ISSUE TITLE
[CoreBundle] Use a more robust/standard way to generate UUIDs

### ISSUE THREAD

**Issue by ngodfraind** [claroline/Distribution#343]
And don't use the "claroline.utilities.misc" anymore.

**Comment by stefk** [comment]
The standard is: http://www.ietf.org/rfc/rfc4122.txt

If we plan to rely on these ids for things such as data exchange or replication, having a standard compliant implementation is crucial. Also, as generation may happen either on server or client side, we need a solution for each environment. 

Found so far:

- JS: https://github.com/broofa/node-uuid (looks good)
- PHP: ???
- MySQL: `uuid` native function
