### ISSUE TITLE
Sending new announcement

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#3430]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 10.9.5

When adding a new announcement and clicking on the checkboxes, no "V" appears in them.

![sending_annoucement](https://user-images.githubusercontent.com/14308826/35094858-e4b0fea8-fc46-11e7-9f28-09cf5021ebf2.JPG)

**Comment by LaurentGruber** [comment]
https://github.com/claroline/Distribution/pull/3436
