### ISSUE TITLE
Suppression d'un espace personnel depuis la gestion des utilisateurs

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#3437]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.9.7

Lorsque j'essaye de supprimer l'espace personnel d'un utilisateur depuis la gestion des utilisateurs :
<img width="960" alt="delete-personal-workspace-1" src="https://user-images.githubusercontent.com/7293233/35157261-b8adf08e-fd33-11e7-955e-f2739f3b6392.png">

Une notification apparait mais l'action n'aboutit pas :
<img width="960" alt="delete-personal-workspace-2" src="https://user-images.githubusercontent.com/7293233/35157324-ef024cc0-fd33-11e7-9e56-01593807d855.png">

**Comment by ngodfraind** [comment]
Reproduit.
