### ISSUE TITLE
Erreur ajour utilisateur dans espace d'activités

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#3447]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.9.2

En essayant d'ajouter un nouvel utilisateur dans un espace d'activités voilà ce que j'obtiens
![image](https://user-images.githubusercontent.com/31481850/35215935-293b5f10-ff66-11e7-91a6-9b79e53788b1.png)
![image](https://user-images.githubusercontent.com/31481850/35215951-362ac4fe-ff66-11e7-9240-c556a1af11d8.png)

**Comment by ngodfraind** [comment]
Pas pu reproduire, possible d'avoir les logs ?

Testé sur la version 10.10.1

**Comment by ngodfraind** [comment]
Ok, reproduit sur votre plateforme.

**Comment by ngodfraind** [comment]
C'est corrigé sur la 10.x en fait, j'ai mit le patch sur votre plateforme en attendant.

https://github.com/claroline/Distribution/pull/3410/files

**Comment by alainertveldt** [comment]
merci ça marche

**Comment by lgeschwine** [comment]
même problème sur notre instance egreta suite à la mise à jour 11.1.5
