### ISSUE TITLE
erreur 

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#3448]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.9.2

Pas possible d'ajouter un formateur supplémentaire à une session de formation (j'ai un stagiaire et j'aimerais l'ajouter comme formateur)... Il n'y a pas de message d'erreur mais rien ne se passe...
![image](https://user-images.githubusercontent.com/31481850/35216085-ae1a0f9c-ff66-11e7-9814-efdfd7434701.png)

**Comment by ngodfraind** [comment]
Pas pu reproduire sur la 10.10.1. Je vais voir directement sur notre serveur, j'ai l'impression que c'est une erreur de maj.

**Comment by ngodfraind** [comment]
Je pense que c'est lié à l'autre erreur, à tester maintenant que j'ai mit le patch. Je ferme en attendant.
