### ISSUE TITLE
[ExoBundle] Impossible de sauver des textes à trous

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#3459]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.10

Reproduit sur demo.claroline.com
Lors de la sauvegarde, il indique "Le texte doit contenir des trous" mais il y en a un !
Console : TypeError: html.trim is not a function
![image](https://user-images.githubusercontent.com/895878/35289248-0945795a-0067-11e8-8665-8bf8ff477009.png)
@CatherineVinci

**Comment by LaurentGruber** [comment]
fixé par : https://github.com/claroline/Distribution/pull/3458 ?

**Comment by ngodfraind** [comment]
oui
