### ISSUE TITLE
Impossible d'enregistrer le questionnaire texte à trous

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3463]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.9.7 egreta.claroline

Bonjour nous avons un bug sur le questionnaire de type texte à trou.
Impossible d'enregistrer le questionnaire texte à trous malgré les trous correctement disposés.

![image](https://user-images.githubusercontent.com/32478422/35330696-af5157f4-0104-11e8-9a71-f349532d3204.png)

Merci

**Comment by LaurentGruber** [comment]
probablement fixé par https://github.com/claroline/Distribution/pull/3458

**Comment by LaurentGruber** [comment]
duplicate of https://github.com/claroline/Distribution/issues/3459
