### ISSUE TITLE
Impossible de dupliquer un espace d'activité

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#3471]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.10.4

Bonjour
Lorsque je souhaite dupliquer un espace d'activité celui-ci ne se duplique pas.
Dans les notifications des actions réalisés sur le coté s'affiche "chargement en cours" en gris puis plus rien.

**Comment by ngodfraind** [comment]
Je crois que ça fonctionne mais que le fonctionnement n'est pas clair.
L'EA est bien copié mais il faut faire une recherche pour retomber dessus (utiliser le nom ou le code de l'espace que l'on copie).

**Comment by l-matt** [comment]
Même avec une recherche, cela ne donne rien

**Comment by lgeschwine** [comment]
idem, ça ne fonctionne pas sur la 10.10.6

**Comment by ngodfraind** [comment]
Ok, je vais y jeter un oeil dès que j'en ai l'occasion.

**Comment by nicvallet** [comment]
Bonjour,
Je viens de tester la duplication d'espace d'activité : cela ne fonctionne toujours pas 
Sur egreta.claroline version 10.10.12
Message d'erreur en rouge : **ECHEC DU CHARGEMENT : nous n'avons pas réussi à charger vos données**
