### ISSUE TITLE
[CoreBundle] Inscription publique à un workspace, bug et faille de sécurité

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#3475]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.10.4

Deux soucis avec l'option d'inscription publique à un workspace:
![image](https://user-images.githubusercontent.com/3415139/35446743-ff27d976-02b5-11e8-908b-96b7f7bff34d.png)

- [ ] L'option "Validation de l'inscription" est ignorée, un utilisateur qui accède au lien d'inscription est directement inscrit au workspace sans passer par la validation d'un gestionnaire. Sa demande n'attéri jamais dans l'onglet "en attente" et ai automatiquement validée.

- [ ] Le lien d'inscription ne vérifie pas que l'option d'inscription publique du workspace est activée. C'est à dire que si on prend un lien d'inscription:
http://localhost/Claroline/web/app_dev.php/workspaces/tool/properties/4/subscription/url/generate

et que l'on change manuellement l'ID du workspace, on peut s'inscrire au workspace que l'on veut même si ce dernier n'est pas ouvert en inscription.

**Comment by ngodfraind** [comment]
Reproduit (je crois).
