### ISSUE TITLE
L'extension html n'est pas reconnue comme navigable

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#3493]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Si une ressource est de type fichier html, claroline propose de le télécharger.
Par contre si le fichier a l'extension htm, là il propose de l'ouvrir dans un navigateur.

**Comment by ngodfraind** [comment]
Pas repoproduit. Toujours d'actualité ?

**Comment by clarophil** [comment]
Effectivement ça marche, je clos le ticket.
