### ISSUE TITLE
Profil : La photo présente dans le profil ne s'affiche pas dans d'autres outils/ressources

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#3494]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.10.6

L'image présente sur le profil de l'utilisateur ne s'affiche plus dans le portfolio ou le forum. L'emplacement est remplacé par une icône d'image comme si le lien était cassé.
![image profil 1](https://user-images.githubusercontent.com/35995165/35629123-230e8786-069e-11e8-9714-d91882844b46.png)
![image profil 2](https://user-images.githubusercontent.com/35995165/35629130-25bb7944-069e-11e8-84c5-8409541a965c.png)

**Comment by ngodfraind** [comment]
Il faut faire un lien de web/upload/pictures/data vers web/data
