### ISSUE TITLE
Profil : Comportement du champs "Description"

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#3495]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.10.6

Le champ de description de l'outil profil ne se comporte pas correctement : 
- Le texte ne s'affiche pas conformément à celui entré dans l'éditeur de texte (apparition des balises de code, non-prise en compte des images...)
Par exemple : 
![modif profil 3](https://user-images.githubusercontent.com/35995165/35629580-41a80432-069f-11e8-95d3-99c9e423d73f.png)

- Les modifications apportées au champs de description ne sont pas enregistrées malgré l’apparition du bandeau de réussite.
Par exemple, en cours de modification : 
![modif profil 1](https://user-images.githubusercontent.com/35995165/35629729-a947c74e-069f-11e8-8af0-6abd65ec4ccf.png)

Et après validation : 
![modif profil 2](https://user-images.githubusercontent.com/35995165/35629742-b25c98f0-069f-11e8-8aa2-4f15e593914d.png)

**Comment by Elorfin** [comment]
Le problème est corrigé dans la 10.10.7.
J'ai également fait un test sur mon environnement local tout semble OK.
