### ISSUE TITLE
gestionnaire d'organisations : impossible de créer un groupe et de le ratacher à son organisation

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#3506]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.10.6

Un utilisateur gestionnaire d'une organisation veut créer un groupe 

![image](https://user-images.githubusercontent.com/7293233/35723394-627e9624-07fa-11e8-9777-ddb81dfa3f04.png)

Après avoir cliquer sur l'icône "disquette" pour valider la création, il veut rattacher ce groupe à son organisation

![image](https://user-images.githubusercontent.com/7293233/35723408-70b9d47e-07fa-11e8-847a-4dd6cfb99f47.png)

Un message d'échec apparait. Le rattachement n'a pas fonctionné, il faut l'intervention d'un administrateur pour rattacher ce nouveau groupe à la bonne organisation

![image](https://user-images.githubusercontent.com/7293233/35723426-796985e2-07fa-11e8-8e78-cafddcad09ad.png)

**Comment by ngodfraind** [comment]
Note pour moi même: Ok, probablement une de permission.

**Comment by ngodfraind** [comment]
J'ai pu reproduire certaines incohérence (mais bon c'était d'autres choses).
Si je crée un orga, elle n'apparait pas dans ma liste si je suis pas manager (car je suis pas lié à l'orga même si j'en suis le créateur).

**Comment by ngodfraind** [comment]
J'ai pu reproduire après avoir corrigé mon erreur, je cherche une solution.

**Comment by ngodfraind** [comment]
C'est compliqué à résoudre en fait, on s'en occupera la semaine prochaine normalement.
