### ISSUE TITLE
[ExoBundle] Les elements "intrus" cassent la réponse aux questions classement

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#3523]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.10.10

Dans une question de type Classement, si on définit un élément intrus, par exemple:

![image](https://user-images.githubusercontent.com/3415139/35904867-0f1281e6-0be5-11e8-84c5-f4f646ccde6a.png)

il n'est plus possible de répondre à la question, une erreur js est levée lorsque l'on fait suivant/terminer:

![image](https://user-images.githubusercontent.com/3415139/35904875-1a4f4e9a-0be5-11e8-8a17-43bb7f3ffdfb.png)

**Comment by Elorfin** [comment]
Duplicate #3922.
