### ISSUE TITLE
Plus accès a mon compte ni au buro

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#3525]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.0.2
une fois connecté impossible de rentrer dans mon menu perso en haut a droite
l'icone buro n’apparaît plus
![image](https://user-images.githubusercontent.com/5484259/35910365-aa2dc44a-0bf6-11e8-8d66-b62852ee6b77.png)

**Comment by LaurentGruber** [comment]
c'est juste sur démo, je dois la réinstaller, on l'a trop maltraité
