### ISSUE TITLE
Utilisateur inscrit à un espace mais pas d'accès et le rôle attribué disparait

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#3533]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | MFR 10.10.12

Bonjour,
J'ai ajouté plusieurs fois un utilisateur (en administrateur) dans un espace en lui attribuant un rôle que j'ai créé, en plus de collaborateur et gestionnaire ("participant session") et il n'arrivait pas, malgré tout, à se connecter à l'espace.
![image](https://user-images.githubusercontent.com/24249636/35962191-d2e4cd7e-0cb0-11e8-86d6-0d31c6247ae8.png)

J'ai réussi à lui donner un accès en l'inscrivant dans un groupe, puis en inscrivant le groupe à l'espace.
C'est un espace à 534 utilisateurs sur 10000 maximum.

Avez vous déjà rencontré ce problème?
Y a -t-il une limite d'utilisateurs dans un espace, sans passer par un groupe d'utilisateurs?

Je vous remercie.

**Comment by ngodfraind** [comment]
Je cherche d'ou ça peut venir, mais je n'ai aucune idée pour le moment.
