### ISSUE TITLE
Import : Ajout d'utilisateurs dans un groupe

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#3539]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 10.10.12

Lors de l'import d'utilisateur dans un groupe (je souhaite ajouter des comptes qui existent déjà dans un groupe), la sauvegarde ne se fait pas. Message "Echec de la création"
![image](https://user-images.githubusercontent.com/35995165/36016990-12739220-0d76-11e8-895e-6cf0074fde2f.png)

Voici un visuel du fichier que je tente d'importer (enregistré en CVS séparateur point virgule)
![image](https://user-images.githubusercontent.com/35995165/36017023-3c559368-0d76-11e8-9830-1ccd1e0235c5.png)

Mon fichier est-il au bon format ?
Est ce un problème venant de l'import ?

**Comment by ngodfraind** [comment]
C'est possible de m'envoyer le fichier ? je regarde ça tout de suite.

**Comment by jbbrosset** [comment]
[https://drive.google.com/file/d/1q7Es2kgPQeld4_cegk92PdMN7R8vKX9q/view?usp=sharing](url)

J'en ai deux comme ça
