### ISSUE TITLE
[CoreBundle] L'export de ressources contenant des contenus riches ne fonctionne plus

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#3561]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.10.13 / 11.1.1

Lorsqu'une ressource contient dans son texte riche un lien vers une ressource file, son export plante. Le parser de texte riche leve une erreur:

![image](https://user-images.githubusercontent.com/3415139/36194666-e9bd2b40-116a-11e8-91f9-60c93b11aa8a.png)

Pour reproduire: uploader une image dans votre liste de ressource, creer une ressource texte, insérer l'image dans le texte riche. Essayer ensuite d'exporter la ressource.

Le bug est apparu dans les dernières version de la v10 et ai toujours présent en v11.

**Comment by ngodfraind** [comment]
Reproduit.

**Comment by ngodfraind** [comment]
A mon avis ça n'a jamais fonctionné dans ce cas.
