### ISSUE TITLE
Problème d'incohérence des restrictions d'un Role

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3573]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 10.10.12

J'ai paramétré un rôle, dans les restrictions, je mets 10 utilisateurs maxi.
![image](https://user-images.githubusercontent.com/32478422/36266787-a06f087e-1272-11e8-864a-ae74e81d404b.png)

J'ai rattaché un groupe de 14 personnes et ça fonctionne alors que ma limite est de 10 personnes.
![image](https://user-images.githubusercontent.com/32478422/36266816-b5eaf2b2-1272-11e8-86d0-bff640f36d6b.png)

Quand j'enregistre, pas de message donc je peux me questionner si les 14 personnes sont inscrites ou seulement 10.
Est-ce normal ?

**Comment by LaurentGruber** [comment]
Après réflexion, je pense que cette option n'est pas très pertinente et peut être couteuse en calcul à la création d'utilisateur particulièrement par groupe ou csv. On va donc la supprimer.

**Comment by lgeschwine** [comment]
c'est dommage c'est le seul moyen pour le moment de limiter les rôles pour éviter que n'importe qui donne un rôle à n'importe quel autre utilisateur

**Comment by ngodfraind** [comment]
La vérification est assez coûteuse et si l'implémentation des création/imports n'est pas bien optimisé, les choses peuvent devenir excessivement lente sur un très grosse plateforme (style Lyon). Je me souviens l'avoir désactivé pour cette raison à un moment.

Vu la nouvelle implémentation ça n'a jamais été rajouté, la fonction de validation existe toujours et est simple à remettre en place, énormément d'éléments sont basé sur les rôles et vérifier systématiquement n'est probablement pas une bonne idée.

Ça ne me dérange pas de la rajouter ici (c'est plutôt simple), mais ça peut être plutôt problématique à d'autres endroits.

Vu que la gestion d'erreur n'est pas au top non plus pour le moment, parfois on a un comportement un peu erratique au final (inscrit ? pas inscrit ? pourquoi ça plante ?). Y a aussi un gros travail à faire de ce coté là.

**Comment by lgeschwine** [comment]
Si nous avons la possibilité de "cloisonner" les rôles, je n'utiliserais pas la restriction sur les rôles.
Le problème, actuellement, est que n'importe qui peut devenir administrateur par exemple et que nous ne pouvons pas créer des rôles orga.
Dans notre réseau, nous avons plusieurs organisations (une par région) avec des référents pour ces organisations (rôle gestionnaire académique) et ces organisations se déclinent en sous-org appelées Greta avec des référents de Greta (rôles de gestionnaire de Greta). Actuellement, comme nous avons des rôles plateforme n'importe qui peut devenir référent académique ou de Greta. Ce qui serait intéressant, c'est de créer des rôles organisation comme les rôles d'EA par exemple ou la possibilité de faire valider par l’administrateur des rôles importants. Pour nous, l'administrateur devrait valider le rôle de gestionnaire d'académie et le gestionnaire d'académie devrait gérer les gestionnaires de Greta etc...

**Comment by ngodfraind** [comment]
Un début de solution que je vois 

- [ ] Au niveau des rôles plateformes: On ne peut distribuer que les rôles que l'on possède (y a pas de hiérarchie de rôle).

- [ ] Possibilité de lier une orga à un role (et limiter la gestion aux roles des orgas que l'on administre).

**Comment by lgeschwine** [comment]
la solution 1 semble répondre grandement à notre problématique
