### ISSUE TITLE
Cleaner published assets destination

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#359]
Actually, the assets of the application are published in : 
- `web/css`
- `web/dist`
- `web/js`
- `web/vendor`

This can be merge to obtain a cleaner `web` directory. For example we can have : 

```
web/
|-- dist/
    |-- css/
    |-- js/
```

**Comment by stefk** [comment]
@Elorfin, I agree the structure could be simplified. `web/dist` stores only webpack builds for the time being, and that's probably a good thing to keep it separate from other assets. Ideally, other directories should be emptied progressively, as we move to a full webpack stack. `web/vendor` should be removed as soon as possible IMO.

**Comment by ngodfraind** [comment]
J'ai rajouté urgent un peu arbitrairement mais c'est raccord avec notre volonté de simplifier la gestion des fichiers/assets.
