### ISSUE TITLE
Ressource base de donnée : manque de cohérence 

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#3606]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.7.9
Le champs que j'ai sélectionnés n'apparaissent pas dans la vue sélectionnée
![image](https://user-images.githubusercontent.com/5484259/36473213-2f141aee-16f4-11e8-88bc-c36e8d12b58c.png)

**Comment by Elorfin** [comment]
Ce que tu montres, c'est la configuration des colonnes des vues "Tableaux". La configuration des "cartes" pour les vues "Grille" (List détaillée est une grille) est juste en dessous, c'est les "Champ à afficher pour ...".

**Comment by Batier** [comment]
super l'ergonomie! ça saute aux yeux!   :-)
dans ce cas là ça serait bien de mettre un fond un peu différent et une séparation le rendant implicite
