### ISSUE TITLE
pb de droit Blog

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3612]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.1.5

Je souhaite mettre à disposition un blog à des utilisateurs d'un EA. J'ai créé un blog (avec un article) et un onglet pour y accéder via 
solution 1 - un widget texte avec une intégration du blog et 
solution 2 - un widget blog
solution 3 - liste des blogs

J'ai éditer les droits pour donner accès en écriture mais cela ne fonctionne pas 
![image](https://user-images.githubusercontent.com/32478422/36532709-c68b10ee-17c1-11e8-8d7f-0f5b44d8720f.png)
et donne trois résultats différents :
widget texte aucun article
![image](https://user-images.githubusercontent.com/32478422/36532737-d69b9bc0-17c1-11e8-8e40-e96b7917354f.png)
widget blog pas d'accès aux fonctionnalités
![image](https://user-images.githubusercontent.com/32478422/36533279-560df1ea-17c3-11e8-885e-1f837c5a24bc.png)
widget liste des blogs, l'accès aux fonctionnalités fonctionnent comme je le souhaite mais l'interface n'est pas très explicite.
![image](https://user-images.githubusercontent.com/32478422/36533318-7ab76bb6-17c3-11e8-9ff1-ddaba59abdaf.png)
![image](https://user-images.githubusercontent.com/32478422/36533406-be199ece-17c3-11e8-8ac6-13e4c108faea.png)

**Comment by lgeschwine** [comment]
Après plusieurs rafraichissement et reconnexion l'intégration du blog dans un widget texte s'affiche correctement avec tous les droits souhaités.
Par contre, le widget blog n'affiche que les articles, pas de bouton pour créer un article, est-ce normal ?

**Comment by ptsavdar** [comment]
Bonjour, oui c'est normal. C'est un widget de lecture.
