### ISSUE TITLE
erreur interne LTI

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3613]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      |11.1.5

Je n'arrive plus à accéder l'administration LTI 
![image](https://user-images.githubusercontent.com/32478422/36534200-2774f3f8-17c6-11e8-89c3-cfc01b0b1770.png)
![image](https://user-images.githubusercontent.com/32478422/36534222-3bf7e600-17c6-11e8-9b82-14f45f9a6173.png)

**Comment by flow39** [comment]
Problème toujours présent sur 11.1.11

**Comment by LaurentGruber** [comment]
https://github.com/claroline/Distribution/pull/3746
