### ISSUE TITLE
pb adresse mail d'une organisation

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3619]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.1.5

Dans le paramétrage d"une organisation, je souhaite remplir le champ "Mail(optionnel)" avec une adresse valide et j'obtiens le résultat suivant après avoir enregistré.
![image](https://user-images.githubusercontent.com/32478422/36583526-6fafe398-1876-11e8-8ab3-db2540585680.png)

**Comment by ngodfraind** [comment]
Corrigé ici normalement:
https://github.com/claroline/Distribution/pull/3550/files#diff-757e5e79e638034d53d3922a4fb44ff9L88

**Comment by lgeschwine** [comment]
ça fonctionne 
merci
