### ISSUE TITLE
[CoreBundle] Filtrage des utilisateurs par rôle dans un espace

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#3622]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master/7.0/etc.

Dans un espace d'activité, on peut filtrer par nom, prénom ou email mais pas par rôle.

Je propose donc d'ajouter un filtrage sur le rôle dans la gestion des utilisateurs d'un espace.  La sélection par rôle permettrait d'assigner un autre rôle ou de les supprimer ou ...

Cas d'utilisation ; 
J'ai 5 groupes et je veux faire 2 groupes qui rassemblent par exemple d'un côté les groupes 1et 5, 2 3 et 4 de l'autre.  En filtrant par rôle, je peux donner un nouveau rôle groupe A et groupe B, je peux ensuite leur donner des droits spécifiques, ou envoyer une annonce ou ...

**Comment by LaurentGruber** [comment]
c'est prévu lors du passage de la gestion des utilisateurs des espaces en react qui viendra dans les semaines qui viennent sur la V11

**Comment by clarophil** [comment]
Super :)
