### ISSUE TITLE
egreta PB widget

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3649]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.1.11

Lorsque je crée un widget, quel qu’il soit (texte, liste des ressources...) et quel que soit l'onglet, il disparaît systématiquement dès que je quitte l'écran d'accueil ou quand je réactualise la page :
![image](https://user-images.githubusercontent.com/32478422/36802072-08dc5268-1cb4-11e8-808d-0e783fb551a7.png)

Après réactualisation :
![image](https://user-images.githubusercontent.com/32478422/36802080-0d9274ae-1cb4-11e8-9f03-348b973a106a.png)

**Comment by lgeschwine** [comment]
je précise que le pb est dans un EA perso

**Comment by LaurentGruber** [comment]
fixé
