### ISSUE TITLE
pb affectation d'une organisation parent à une organisation déjà créée

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3653]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.1.11

Une organisation "CAFOC guadeloupe" a été créé lors du bug des sous organisations, donc elle a été créé à la racine des organisations.
Je souhaite que l'orga "CAFOC Guadeloupe" devienne une sous org de "académie de GUADELOUPE".
Je vais dans la gestions des orga
![image](https://user-images.githubusercontent.com/32478422/36850851-13c960a8-1d68-11e8-8f46-b74d02c7691e.png)
Je choisis dans parent : académie de GUADELOUPE mais j'ai un échec de mise à jour lors de l'enregistrement :
![image](https://user-images.githubusercontent.com/32478422/36850977-69304570-1d68-11e8-986c-e50e013297d1.png)

**Comment by ngodfraind** [comment]
Reproduit. Ça passe à la création mais pas à la maj.
