### ISSUE TITLE
Aucune info sur les erreur à la création de comptes 

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#3657]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      |  11.1.13

je suppose que pour importer des comptes il faut passer par  data import export
Car  ce n'est plus accessible par l'interface de gestion des utilisateurs :-(
j'ai essaye avec les fichiers que j'utilisais jusqu'a present et j'ai changé en mettant le meme ordre que sur la liste j'ai toujours le meme essage d'erreur...donc du coup  je ne sais pas d'ou vient l'erreur

![image](https://user-images.githubusercontent.com/5484259/36889397-ab3f0b84-1df1-11e8-9e8c-5a66c652364b.png)

**Comment by LaurentGruber** [comment]
Tu dois ajouter une ligne d'entête à ton fichier ...
On travail pour le moment sur cet outils pour l'améliorer ...

**Comment by ptsavdar** [comment]
Remplacé par ceci: #3661
