### ISSUE TITLE
pb de lecture d'une ressource scorm sur mozilla

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3658]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.1.11

J'ai un problème de lecture de ressource scorm sur mozilla
https://egreta.claroline.com/resource/open/claroline_scorm_12/16895
ça fonctionne sur chrome et ie

**Comment by LaurentGruber** [comment]
ça dépend du scorm, pas de claroline.
Il est en flash ce qui sera de toute manière problématique ... Et en faite il y a moyen de le faire fonctionner sur firefox en recliquant sur launch ...
A voir au niveau de la création du scrom ...
