### ISSUE TITLE
[CoreBundle] Creation des comptes utilisateurs via CSV

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#3661]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 10.10.13

Je reviens ici pour completer le ticket de Christophe #3657 . Voici une liste avec des fonctionnalités manquantes sur le nouveau outil de création des comptes via CSV:

- [x] Possibilité de preciser un rôle pour les utilisateurs (comme on peut preciser le group)

- [ ] Possibilité de preciser la création d'un espace personnel (actuellement même si le rôle étudiant a la création d'EP activée par défaut ceci n'est pas respecté par la creation via CSV)

- [x] option créer ou mettre à jour
- [x] Option de mettre à jour des comptes (s'ils existent déjà)

- [ ] Possibilité d'envoyer un mail aux utilisateurs créés (avec leurs coordonnées)

- [x] Possibilité de valider les adresses mail par défaut

- [x] Messages d'erreurs plus détaillés (si par exemple la création a echouée parce qu'un compte avec le même login existe déjà, afficher cette information comme c'était le cas avant)

- [x] Voir les logs de l'opération

- [ ] rendre le mot de passe optionnel et si tel est le cas en généré un automatiquement (avec envoie par mail)

- [x] url pour déposer fichier csv via API (vérifier oAuth2)

- [x] historique des imports / export

Pour l'instant c'est tout ce qui m'a était rémonté. Je cloture le ticket de Christophe, ceci etant plus détaillé.

**Comment by ngodfraind** [comment]
Ok, j'vais m'en occuper.

**Comment by LaurentGruber** [comment]
Possibilité de preciser l'organisation ! seulement des orga dont le user est admin ...

**Comment by ptsavdar** [comment]
J'ai enlever l'organisation, si cela pose pb.

**Comment by Batier** [comment]
et question complémentaire je remets la capture écran de l'issue #3657 
qui décide des champs obligatoires ou pas sur diiferents serveur je n'ai pas les meme choix
(bouton orange ou rouge) et je ne vois pas où cela se parametre les bouton n'étant pas cliquable

![image](https://user-images.githubusercontent.com/5484259/36889397-ab3f0b84-1df1-11e8-9e8c-5a66c652364b.png)

**Comment by lgeschwine** [comment]
serait-il possible de préciser plusieurs rôles ? et on parle bien de rôle plateforme ?

**Comment by ngodfraind** [comment]
Bon, c'est en route maintenant.

**Comment by LaurentGruber** [comment]
@Batier les champs obligatoires sont identique sur toutes les plateformes (il y a eu des souci d'affichage, mais corrigé aujourd'hui), il s'agit au moins du mail, nom, prénom, username, mot de passe.
On essaye de réduire cet liste au maximum, on va probablement rendre le mot de passe optionnel (il en générera un automatiquement, s'il n'est pas précisé, ...)
@lgeschwine oui séparé par une virgule

**Comment by lgeschwine** [comment]
Comment différencier les rôles plateforme et les rôles EA dans le fichier ?
Comment rattacher une organisation à l'utilisateur dans le fichier ?
