### ISSUE TITLE
Disparition des champs de texte riche

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#3691]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.1.18

Il n'est plus possible d'éditer la description des étapes dans un parcours depuis la mise à jour cette nuit.
De mémoire il s'agissait d'un champ de texte riche.
La partie "Description" apparaît bien mais le champ est invisible :
![image](https://user-images.githubusercontent.com/35995165/37079481-0cff37c8-21e3-11e8-9571-930d741e7d8a.png)

Le problème arrive sur tous les parcours de notre plateforme, sur Chrome comme Firefox.

**Comment by jbbrosset** [comment]
MAJ : 
Tous les champs de texte riche semblent avoir disparus de la plateforme !
On ne peut plus éditer les widget texte :
![image](https://user-images.githubusercontent.com/35995165/37079825-428004bc-21e4-11e8-99f2-1201b5306011.png)

Ni les articles de wiki : 
![image](https://user-images.githubusercontent.com/35995165/37079859-74d8dac4-21e4-11e8-88fb-aca752e08de4.png)

Les champs de texte simple fonctionnent encore.

**Comment by Elorfin** [comment]
C'est corrigé et disponible sur votre plateforme.
