### ISSUE TITLE
Page wiki impossible d'éditer une section

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#3692]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.1.18

 Impossible d'éditer une section (chrome et Firefox), le Wiki est donc bloqué.

![image](https://user-images.githubusercontent.com/24249636/37079878-8a7f5e52-21e4-11e8-9965-9538b7f51154.png)

**Comment by Elorfin** [comment]
lié à #3691.
