### ISSUE TITLE
Gestion du support impossible d'ajouter/saisir ou d'éditer une note

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#3694]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.1.18

Impossible de répondre dans la note interne ou discussion du support des tickets 
![image](https://user-images.githubusercontent.com/24249636/37080136-7b6cd254-21e5-11e8-9619-8cdc35975aa6.png)

**Comment by Elorfin** [comment]
lié à #3691
