### ISSUE TITLE
[Collecticiel]Envoi du commentaire dans la messagerie

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#37]
_From @purplefish32 on March 30, 2016 12:0_

_From @ericvincenterv on November 16, 2015 12:15_

ajouter une fonction "Notifier" (voir les fonctions similaires sur CC) => envoi du contenu du commentaire déposé dans la messagerie du ou des destinataires (ceux qui ont accès au collecticiel)

_Copied from original issue: InnovaLangues/CollecticielBundle#151_

_Copied from original issue: claroline/Claroline#759_

**Comment by purplefish32** [comment]
This issue was moved to claroline/Distribution#31

**Comment by jj-quintin** [comment]
Le bouton de notification (Suivre cette ressource) concerne d'autres événements que le dépôt d'un nouveau commentaire. Faire le point sur les événements du collecticiel déjà pris en charge
