### ISSUE TITLE
Notifications "Tout marquer comme lu"

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#3702]
| Bug report?   | no
| Version?      | 10.10.11

Mes notifications arrivent rapidement à des centaines et même à des milliers. Long de supprimer page par page. La possibilité de les sélectionner d'un clic de façon exhaustive ou en très grand nombre serait bienvenue.

![image](https://user-images.githubusercontent.com/33163723/37101941-feeca596-2226-11e8-96dc-fdba38eb1aa3.png)

**Comment by flow39** [comment]
Je plussoie :-)

**Comment by npaille** [comment]
Le problème n'est pas réglé.
Il est difficile de retrouver page par page les notifications non lues pour les grosses plateformes pour les supprimer.
Bouton "Afficher les non lues" ?  ou Filtre par 100 résultats ?

![image](https://user-images.githubusercontent.com/33163723/47579856-7b59ec00-d94d-11e8-8120-ab3dbaff44e4.png)
