### ISSUE TITLE
Ressources | Liste de ressources proposées paramétrable par "profils"

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#3703]
| Bug report?   |  no
| Version?      | 10.10.11

Quand un gestionnaire souhaite ajouter une ressources, la liste des propositions est longue et peu effrayer. Pour un ressenti d'interface "simple et user friendly" pour mes profs lambda, filtrer ce qui apparaît est-il possible ?
Pour un groupe donné, je souhaite ne faire apparaître que les principaux  (Fichier, Dossier, Annonce, Forum, Questionnaire, Texte, URL, Evaluation) et réserver le reste aux ingénieurs pédagogiques et/ou administrateurs.

![image](https://user-images.githubusercontent.com/33163723/37102366-fcd8ee9e-2227-11e8-8fd8-2f1014ccd56f.png)

**Comment by jbbrosset** [comment]
Hello,

Il me semble que dans le menu de l'espace: 
Paramètres -> Ressources -> Avancé

Dans la colonne "Création" en face de tes tôles personnalisés tu peux cocher certains type de ressources ce qui devrait avoir pour effet de ne faire apparaître que ces derniers  de la liste sans fin dont tu parle

**Comment by Elorfin** [comment]
- Cette liste a été retravaillée.
- Il est en effet possible de la configurer via les droits.
