### ISSUE TITLE
improvement [ExoBundle] : add synonyms for an open question with short anwser

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#371]
I have a WS manager asking me this : 
he creates open questions, with short answer (1 answer)
What he can do is for instance : 
- Word 1 : rayons X (0.5 pt)
- Word 2 : électicité (0.5 pt)
  => the 2 words give the full 1 point.

But what he would like to do is  : 
- Word 1 : rayons X (0.5 pt) or (rayons x, rayon x)
- Word 2 : électicité (0.5 pt) or (electicité)

=> If the user gives the synonyms, he has also the point
but of course these synonyms are not cumulative for the total : 
- rayon X + rayons x => 0.5 pt and not 1 pt
- rayon X + rayons x + électicité => 1 pt
- rayons x + électicité => 1 pt

So instead of having a word to match for, it should be an array of words.

**Comment by Elorfin** [comment]
This feature can be insteresting but will require lots of work as we will need to update all bundle layers (Model / API / Exchange Format / AngularJS).

Is this something you need quickly ?

**Comment by CPASimUSante** [comment]
Not really. The manager would like to have it for yesterday of course, but if it's planned it's ok, i think

**Comment by jj-quintin** [comment]
Important de l'avoir (un jour) et très courant dans les analyses de réponses ouvertes courtes

**Comment by LaurentGruber** [comment]
Ceci devrait permettre d'avoir le comportement voulu au moins en partie : https://github.com/claroline/Distribution/issues/2165
