### ISSUE TITLE
Liste des notifications "tout marquer comme lu"

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#3725]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.1.18

Dans la liste des notifications (utilisateur), l'option "tout marquer comme lu" ne fonctionne que sur une page au lieu de toutes les pages. L'opération de nettoyage devient alors vite fastidieuse si l'on dépasse les 3 pages.

**Comment by ngodfraind** [comment]
Double de #3702
