### ISSUE TITLE
[CoreBundle] Can no longer specify profile editable fields by role

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#3726]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.10.15/master

It seems that is no longer possible to specify which fields of profile users of a particular role can modify/edit.
Prior to the new interface there was a table that looked like this:
![profile_management](https://user-images.githubusercontent.com/3414935/37284631-93815188-25fc-11e8-8f50-80d71e84c917.png)

More than that, it seems that the options defined in this table are no longer taken into account in the new interface. E.g.: We had disabled the email modification for the role "User" but it seems that now "User"s can modify their mail at will.

![profile_edit](https://user-images.githubusercontent.com/3414935/37284717-f1d5be40-25fc-11e8-9207-cdf4af58e16f.png)

**Comment by LaurentGruber** [comment]
il faut revoir la gestion des rôles de façon global sur le profil à facette.
Jusque là seul les champs par défaut était pris en compte, ce qui n'est pas suffisant.
La solution fonctionnelle n'a pas encore été trouvée.
