### ISSUE TITLE
FORUM : Bundle de suggestions

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#3731]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 11.1.18

Bonjour, Laurent Gruber m’a suggéré de poster un bundle de suggestions pour le forum.
Voici donc ce que je propose pour le faire évoluer, le rendre plus dynamique et fonctionnel.
Je me base sur les fonctionnalités que j’ai l’habitude de voir sur d’autres forums sur lesquels je navigue depuis plus de 15 ans. Je me permets donc d’appeler ça un standard.
Je donne 3 niveaux d’urgence :
- Nécessaire : à régler rapidement car la navigation et l’utilisation du forum peuvent être compliquées pour un utilisateur lambda.
- Utile : À mettre en place à court terme.
- Gadget : À mettre en place à long terme.

1 : WIDGET « derniers messages du forum »
Nécessaire : Il manque un lien vers la page principale (accueil du forum) en tête de liste.

2 : Sur la page d’une catégorie de forum

Nécessaire :
- Renommer le bouton « retour aux forums » en « retour aux catégories »
- Ajouter une colonne « Nombre de vues »
- dans la colonne dernier message, un lien vers le dernier message du sujet

Utile quelque soit le lieu du forum
- [x] Chaque nom d’utilisateur affiché devrait être cliquable pour en voir le profil
- [ ] Afficher le rôle utilisateur si il est modérateur ou administrateur du forum

Gadgets :
- [x] afficher une icône qui permet d’identifier la popularité du sujet de conversation en fonction de son nombre de message par jour (par exemple fréquentation faible, bonne, forte, très forte…) Pouvoir proposer soit même ses propres icônes/pictogrammes.
- [x] Ajouter une colonne page qui affiche automatiquement 3 ou 5 boutons qui donnent accès aux 3 ou 5 dernières pages
-  une base de Smileys?

3 : Sur la page d’un sujet

Nécessaires :
- [x] Ne garder le bouton répondre que pour le dernier message. On évite une conversation qui passe du coq à l’âne et qui peut vite devenir un bazard. On garde un sens de lecture et il sera toujours possible de citer un message précédent. 
- [x] Le bloc d'informations du profil de chaque utilisateur figurant à gauche du message est centré sur la verticale. Si le message est long, il faut scroller tout au milieu pour en voir l’auteur. Il serait préférable d’aligner tout ça vers le haut pour identifier plus rapidement l’auteur.
- [x] Ajouter un bouton « signaler » qui envoie un message au gestionnaire du forum.

**Comment by jbbrosset** [comment]
![image](https://user-images.githubusercontent.com/35995165/45346321-2e8ea180-b5a9-11e8-974b-c8b9328ede7d.png)

- [ ] Enlever l'assignation automatique d'un tag à la création d'un nouveau sujet
- [ ] Pouvoir sélectionner un tag existant dans le champs tags et/ou en créer un nouveau.
