### ISSUE TITLE
Liste des utilisateurs d'un espace : erreur lors d'une recherche

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#3737]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.1.18

Bonjour, lorsque je saisi un nom et que je lance une recherche dans la liste des utilisateurs d'un espace, j'obtiens un message d'erreur. J'ai obtenu ce message d'erreur sur plusieurs espaces.
![image](https://user-images.githubusercontent.com/24249636/37328856-e3aa54a8-269b-11e8-841a-f7bf45a39f79.png)

**Comment by ngodfraind** [comment]
Cette PR refond complètement l'outil.

https://github.com/claroline/Distribution/pull/3641

A priori ça viendra bientôt.
