### ISSUE TITLE
perte du nom du créateur d'un EA

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3738]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.1.18

Dans les paramètres d'un EA, il n'est plus possible de voir le nom du créateur :
![image](https://user-images.githubusercontent.com/32478422/37290046-8ba65da0-260b-11e8-9a4d-c3b48001d705.png)

**Comment by ngodfraind** [comment]
Reproduit (je pense).
