### ISSUE TITLE
Widget Video Inwicast : pas d'accès au mediacenter

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#3740]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.1.18

Je peux créer un Widget video Inwicast mais je ne peux pas le paramétrer et accéder à ma banque de vidéos.
![image](https://user-images.githubusercontent.com/24249636/37335844-d6aeb514-26af-11e8-8278-17b18e4a5205.png)
Mon username Clarolineconnect et celui d'Inwicast sont pourtant strictement les mêmes pour le match.
Le widget fonctionnait avant notre migration de serveur/hébergeur.
J'ai réussi à mettre à jour l'URL du mediacenter (https://mfr.inwicast.tv) mais ca ne fonctionne toujours pas.
Est ce que je dois configurer des choses en plus? (je suis aussi en attente de réponse du responsable d'Inwicast)
![image](https://user-images.githubusercontent.com/24249636/37336332-56bfe876-26b1-11e8-854d-7492c2459b23.png)

**Comment by LaurentGruber** [comment]
l'accès à la db d'inwicast est autorisé depuis le serveur walter ?
