### ISSUE TITLE
Ressource Base de donnée : Je ne peux pas ajouter une fiche 

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#3742]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.10.13 et 10.10.15 (pas pu tester sur les autres)

J'ai créé un base
défini des champs....
quand je clique sur ajouter une fiche
rien ne se passe :-(

**Comment by LaurentGruber** [comment]
@ptsavdar tu as plus d'info ?

**Comment by Batier** [comment]
Sur demo  je n'ai même pas la possibilité d'ajouter la fiche
https://demo.claroline.com/resource/open/claroline_claco_form/61#/
ET sur notre serveur Lyon1 c'est dans mon espace d'activité communauté des alternants
je vous ai rajouté les droits
https://clarolineconnect.univ-lyon1.fr/resource/open/claroline_claco_form/1679844#/entry/create

**Comment by LaurentGruber** [comment]
https://github.com/claroline/Distribution/pull/3747
