### ISSUE TITLE
[Collecticiel] Can't request evaluation

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#375]
The Ok button doesn't work 
![image](https://cloud.githubusercontent.com/assets/895878/15472273/892815cc-20fa-11e6-8d0a-54f7f4c290e9.png)

**Comment by ericvincenterv** [comment]
@clarophil : I tested in 2 working environment and I didn't have any problem with this button. Do you have this problem with all your documents ?

**Comment by clarophil** [comment]
Now I can't create a new collecticiel  so I can't test the request
Tested on 7.0 and dev-master

**Comment by ericvincenterv** [comment]
@clarophil 
When you want to add a collecticiel, there is a bug.
It will be corrected in "16-05-1" : https://github.com/claroline/Distribution/issues/478
