### ISSUE TITLE
Questionnaires : plusieurs bugs

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#3755]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.1.18

Problèmes rencontrés :

- [x] La création d'un intrus bloque l'affichage de la correction et fige le questionnaire qui ne peut être poursuivi ou terminé.

- [ ] On ne peut plus régler la taille des trous. Qu'on mette 10 ou 30, ça ne change rien.

- [x] Dans le type de question (tableau) le curseur quitte la zone de saisie du mot clé après la frappe de la première lettre.

- [x] La banque de questions ne marche toujours pas. C'est mieux quand on fait un questionnaire, on peut accéder à ses questions antérieures. Par contre quand on veut consulter la banque par le menu utilisateur, on accède à la première page et rien d'autre. De plus, on ne peut pas supprimer de question.

Suggestions :

Lors de la création d'une ressource questionnaire et lorsque les la liste des questions est récapitulée à l'écran, il serait intéressant d'avoir plutôt la liste des questions (libellé) ou au moins leur variable au lieu de la liste du type de question pour que cela soit plus lisible.

**Comment by Elorfin** [comment]
> Lors de la création d'une ressource questionnaire et lorsque les la liste des questions est récapitulée à l'écran, il serait intéressant d'avoir plutôt la liste des questions (libellé) ou au moins leur variable au lieu de la liste du type de question pour que cela soit plus lisible.

Il est possible de mettre un titre (optionnel) aux questions (dans la section Titre et autre champs). Si spécifié, c'est lui qui es affiché dans la liste des questions de l'étape.

> On ne peut plus régler la taille des trous. Qu'on mette 10 ou 30, ça ne change rien.
Ce point a son propre ticket, le #5298.
