### ISSUE TITLE
Éditeur de texte riche : affichage du nuancier de couleur qui s'éloigne du bouton ou disparait

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#3779]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.3

Bonjour,
le nuancier de couleur de l’éditeur de texte riche ne s’affiche pas toujours à côté du bouton dédié, parfois très loin ou pas du tout voir probablement hors de la zone d'écran.
Cela dépend des outils/ressources utilisés, c’est peut être aléatoire ?

![image](https://user-images.githubusercontent.com/24249636/37601217-bb955cae-2b89-11e8-8477-d0be9a085dc6.png)

On peut retrouver l’affichage du nuancier de couleur en dézoomant le navigateur à 50% mais c'est très dommageable.
Une fonctionnalité initialement simple devient compliquée.

Au passage je tiens à remercier le travail des différents développeurs car je remonte beaucoup de choses ces derniers jours. On ne dit peut être pas toujours merci.
Donc bon boulot, merci de votre réactivité!

**Comment by Elorfin** [comment]
Merci pour le retour. Il s'agit de quel outil ? Je n'arrive pas à le reconnaître, l'impression écran est trop petite pour lire les textes.

**Comment by WalterMFR** [comment]
L'utilisateur ne m'a remonté qu'une petite capture d'écran.
Il s'agit du Porfolio.
