### ISSUE TITLE
[messagerie] Bouton OK inactif lorsque je selectionne mes destinataires

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#3782]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.3

Bonsoir, 
Impossible de valider la sélection d'utilisateurs et/ou de groupes dans la facebox lors de l'envoi d'un message via la messagerie
La checkbox est coché mais le bouton "OK" semble inactif.
La messagerie semble quand même fonctionner en entrant un destinataire manuellement.
Cordialement.

**Comment by l-matt** [comment]
Bug présent sur demo.claroline.com

**Comment by lgeschwine** [comment]
bug persistant sur la 11.2.27

**Comment by ngodfraind** [comment]
Reproduit avec cette erreur:
`The route "claro_usernames_from_users" does not exist.`
