### ISSUE TITLE
Gestion des utilisateurs ne renvoie aucun resultat

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#3784]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.3

Depuis le commit #3781 la gestion des utilisateurs ne renvoie aucun résultat : 
☹ Aucun résultat trouvé .
idem pour les groupes.

**Comment by LaurentGruber** [comment]
Tu peux être plus précis, dans l'admin ou dans les EA ? avec quel type de rôle ...

Là je viens de tester et pour moi tout est ok ...

**Comment by l-matt** [comment]
Bonjour,
C'est partir de la gestion des utilisateurs du menu admin avec un compte Administrateur.
Il m'affiche pourtant bien les utilisateurs et groupes en les consultants depuis un EA.

**Comment by ngodfraind** [comment]
Je regarde tout de suite.

**Comment by ngodfraind** [comment]
J'ai une piste: les utilisateurs ont-ils une organisation ?

**Comment by l-matt** [comment]
Je pensais qu'une organisation par défaut été attribuer donc je dirai oui l'organisation defaut

**Comment by ngodfraind** [comment]
Quel type de profil n'a plus accès à la liste ?

En principe, dans l'administration, on ne peut voir que la liste des utilisateurs dont on administre l'organisation.

**Comment by l-matt** [comment]
ok, je suis un administateur total

**Comment by ngodfraind** [comment]
Ok, compris.

Je vois ce qui ne va pas dans ce cas (je pense).

2 min le temps que je corrige.

**Comment by l-matt** [comment]
je les ai retrouvé : 
Quand je vais dans l'onglet organisation, depuis la gestion des utilisateurs.
J'ai une organisation qui contient tout mes users

**Comment by ngodfraind** [comment]
En fait, si vous mettez l'admin comme gestionnaire de l'orga par défaut tout va se réafficher. Je  vais mettre une condition pour que tout s'affiche tout le temps pour lui.

**Comment by l-matt** [comment]
Si je n'ai qu'une seule organisation, tous mes users et groupes doivent en faire partis ? pour éviter les soucis à l'avenir

**Comment by ngodfraind** [comment]
Le fix

https://github.com/claroline/Distribution/pull/3789

Il faut mettre l'admin comme gestionnaire de la seule organisation en fait. Sinon la pr corrige le truc.

**Comment by l-matt** [comment]
Merci

**Comment by l-matt** [comment]
Dans cette organisation j'ai quelques espaces personnels et un ea qui s'est glissé.
Je peux les détacher ?

**Comment by ngodfraind** [comment]
Oui mais c'est pas obligatoire. 
Normalement tout devrait y être relié donc c'est ceux qui n'y sont pas le problème. Normalement il y avait un updater qui aurait du s'en charger mais si vous ne vous servez pas des orgas ce n'est pas un problème.

**Comment by l-matt** [comment]
Je comprends mieux à présent. j'vais quand même tenter de me cantonner à l'organisation par défaut et rattacher ce qui ne l'est pas, on ne s'est jamais pour le futur.
Merci
