### ISSUE TITLE
ajout d'utilisateur dans un EA

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3788]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.2.3

Je souhaite ajouter un rôle (un utilisateur existant) dans un EA mais j'ai une erreur de chargement.
![image](https://user-images.githubusercontent.com/32478422/37643913-59c1f85e-2c22-11e8-8338-4fa9055eb48b.png)
Impossible d'aller plus loin et donc d'ajouter un utilisateur.

**Comment by LaurentGruber** [comment]
C'est corrigé par ceci : https://github.com/claroline/Distribution/pull/3781 Je termine les tests et ça arrive chez vous ...
