### ISSUE TITLE
[WikiBundle] Little mistake with the position of the radio buttons in the options

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#379]
![image](https://cloud.githubusercontent.com/assets/895878/15473197/334a4c10-20ff-11e6-8ebf-160ef836105a.png)

**Comment by CPASimUSante** [comment]
should be [fixed now](https://github.com/claroline/Distribution/issues/274)

**Comment by purplefish32** [comment]
@clarophil Can you confirm ?

**Comment by clarophil** [comment]
Ok it's resolved
