### ISSUE TITLE
Perte des utilisateurs inscrits dans les EA

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3791]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.2.3

Dans de nombreux EA nous avons perdu les utilisateurs inscrits et impossible des les inscrire de nouveau.
De plus nous ne pouvons plus voir les utilisateurs dans l'édition d'un EA.
![image](https://user-images.githubusercontent.com/32478422/37650397-19a10702-2c35-11e8-810c-3117ba59d83a.png)
Il ne reste plus que gestionnaires et organisations...

**Comment by LaurentGruber** [comment]
Quel user ? dans quel espace ? dans quel contexte ?

**Comment by jbbrosset** [comment]
Idem dans tous les espaces:
Le rôle Collaborateur à été supprimé de la plateforme
