### ISSUE TITLE
Impossible d'affecter EA à organisation

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#3793]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.4

En passant par le menu admin > gestion des utilisateurs > onglet organisation > espaces d'activités > + 
Aucune fenêtre n'apparaît afin d'ajouter un EA
Suite à cela, la navigation sur la page plante.

**Comment by ngodfraind** [comment]
Reproduit.
