### ISSUE TITLE
Annonce : Impossible d'envoyer à plusieurs rôles destinataires et d'enregistrer

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#3802]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.4

Impossible d'envoyer à plusieurs rôles destinataires et d'enregistrer une nouvelle annonce.
Cela fonctionne si l'on ne prend qu'un seul rôle.
![image](https://user-images.githubusercontent.com/24249636/37710548-44854e86-2d0e-11e8-8372-c61b36484b7d.png)

Soit il manque une précision du genre "selectionnez un seul rôle destinataire" soit c'est un bug.
Merci.

**Comment by ngodfraind** [comment]
Sur ma machine, j'ai créé une annonce. J'ai fait envoyé directement avec 2 rôles cochés.
Un message m'a été envoyé (vu que j'avais les rôles). Par contre dans le header, y avait pas le nombre de message non lu.

Je n'ai pas donc pas réussi à reproduire. Ça plante ? rien ne se passe ?

**Comment by WalterMFR** [comment]
J'ai essayé de reproduire le bug dans un espace "bac à sable" et RAS, ca fonctionne.

J'ai constaté le problème dans un autre espace en particulier où j'ai vu le petit bandeau rouge en haut a droite une fois le bouton "enregistrer" appuyé. (après avoir voulu envoyer "directement" à deux rôles en meme temps)

Je vais voir si il se produit à nouveau, je vous tiens au courant.

Merci.

**Comment by ngodfraind** [comment]
Reproduit.

**Comment by ngodfraind** [comment]
Trouvé je pense :)
