### ISSUE TITLE
Dans la gestion des utilisateurs la photo de profil n'apparait pas

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#3809]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.5
sur demo je viens d'ajouter une photo de profil a un utilisateur
![image](https://user-images.githubusercontent.com/5484259/37772885-58c49298-2ddc-11e8-9ef5-3ed7a268064b.png)

mais elle n'apparait pas sur le listing des utilisateurs

ni en mode liste détaillée
ni en mode grille
ni en mode grille large
![image](https://user-images.githubusercontent.com/5484259/37772938-87fc4876-2ddc-11e8-9118-cbd0cb0653e8.png)

**Comment by Elorfin** [comment]
Je ne reproduis pas 
![sans titre2](https://user-images.githubusercontent.com/5363219/37775061-2ce6d504-2de2-11e8-86dc-c7e5741c7bb2.png)

?

**Comment by Batier** [comment]
ah ben oui maintenant elle y est !!!
et bien tant mieux!!!
