### ISSUE TITLE
PDF viewer access with not connected/Anonymous users

### ISSUE THREAD

**Issue by eddymarques** [claroline/Distribution#381]
Even if the rights are set for anonymous/not connected people to access to a PDF directly from URL, the PDF viewer (and download button if checked) are inactives.

**Comment by ngodfraind** [comment]
I could see the bug myself.

**Comment by ngodfraind** [comment]
That one is not going to be easy. It's related to the API authentication/security (anonymous are kicked out no matter what currently).

It's (sort of) related to the issue in #338.

I'm working on it.

**Comment by ngodfraind** [comment]
It was easier to fix than I expected.
 I'll add a few tests to be sure I didn't broke anything, enhance the API security and try to fix #338 now.

**Comment by eddymarques** [comment]
Cool! Thx !

**Comment by ngodfraind** [comment]
En fait c'est pas facile du tout lol.
J'ai du me planter quelque part quand j'ai testé. Mais j'ai corrigé #338.
