### ISSUE TITLE
Profil utilisateur : Suppression de photo de profil impossible sur Mozilla Firefox

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#3811]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.4

Bonjour,
J'ai un utilisateur qui ne peut pas supprimer une photo de profil. Soit ca charge sans résultat ou alors il obtient l'écran suivant : 
![image](https://user-images.githubusercontent.com/24249636/37782607-9d1a11c2-2df3-11e8-9ddd-3dbf7f905a2b.png)

J'ai reproduit le bug sur Mozilla Firefox mais pas Google Chrome.
Je lui ai suggéré de passer sur Chrome en attendant.

Merci.

**Comment by ngodfraind** [comment]
Ça a du être corrigé à un moment car je n'ai pas pu reproduire. Je ferme.
