### ISSUE TITLE
Messagerie : Impossible de valider l'ajout d'un groupe destinataire

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#3812]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.4

Bonjour,

Je souhaite envoyer un message à un groupe pour ne pas saisir tous les utilisateurs de ce même groupe 1 par 1. Lorsque je valide l'ajout il ne se passe rien, pas de message d'erreur mais pas de validation non plus. Le resultat est le même sur Firefox et Chrome.
![image](https://user-images.githubusercontent.com/24249636/37783070-cf87a0b0-2df4-11e8-81c9-471703e5d701.png)

Merci.

**Comment by ngodfraind** [comment]
Voir #3872
