### ISSUE TITLE
Filtre sur organisations non fonctionnel

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#3815]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.4

![image](https://user-images.githubusercontent.com/35995165/37816553-c8c3218a-2e73-11e8-981c-558c7a98e2f1.png)

Dans la gestions des organisations, lors d'une recherche sur le nom ou le "parent" la recherche s'active mais aucun tri n'est appliqué à la liste .

**Comment by ngodfraind** [comment]
Reproduit
