### ISSUE TITLE
Improvement : Centralize user data

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#382]
i noticed there are 2 folders containing user data : 

- **/plateform_root/files**

directory for standard php uploaded files : WS directories, docx, images, files, templates....

- **/plateform_root/web/uploads**
  
directory for other uploaded files (from some plugins) : badges, logos, scormmresources, webresources, websites, ujmexo

I wanted to have a NFS mount for user uploaded data, to be backuped apart from the rest of the platform (which doesn't need much space and doesn't grow fast).
It would be great (if possible = not urgent) if all those data could be put in one directory.

**Comment by LaurentGruber** [comment]
one is strictly private (/files) and the other is public (/uploads) so we must keep the 2 folder. But you can mount the 2 folders with nfs

**Comment by CPASimUSante** [comment]
/files is private ? there are docx, jpg, ... files from users in it.

**Comment by LaurentGruber** [comment]
yes but there are only accessible with the ressource manager not directly via webserver

**Comment by purplefish32** [comment]
@CPASimUSante Can I close this ticket ?

**Comment by CPASimUSante** [comment]
if nothing can be done ... too bad some resources choose /files and some other choose web/uploads. It's just a pain for managing external backup of these 2 folders which contains the same kind of data
