### ISSUE TITLE
ExoBundle - point d'amélioration suivi

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3831]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.2.4

Je souhaite pouvoir obtenir dans un tableau (idéalement exportable en .csv), le détail des réponses de chaque apprenant PAR QUESTION.
Pour l'instant je m'aperçois que la ressource n'exporte que le score global de la personne.
Serait-il possible d'améliorer l'ergonomie du suivi par question?
Merci

**Comment by LaurentGruber** [comment]
Dans statistique tu as un export détaillé par question (qui est encore perfectible mais qui existe ...)
