### ISSUE TITLE
Gestion des droits pour inscrire des users aux EA

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#3834]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no ?
| Version?      | 11.2.4

Lors des précédentes versions, tous nos users pouvaient inscrire n'importe quel personnel depuis la base globale à un espace d'activité. 
Depuis la 11.2.4, les personnels sont maintenant affectés à des organisations (il me semble que ce n'était pas le cas avant), et ils ne peuvent donc plus inscrire des users que de leur orga.

En terme de sécurisation c'est intéressant MAIS nous avons beaucoup d'utilisateurs qui font du travail collaboratif inter-orga et qui ont donc nécessité d'ajouter des user d'autres orga à leur espace.

Comment pouvons nous retrouver cette fonctionnalité ?  
Dans l'immédiat je voulais créer une orga qui contiendrait tous les users salariés pour qu'ils aient tous accès dans l'inscription, mais je ne peux pas traiter cela en masse puisque je ne peux pas faire de tri sur l'adresse mail (les salariés ont un mail spécifique en @mfr.asso.fr).
Je me vois mal faire la manip à la main...

Si n'importe qui à une solution, je suis preneur.

**Comment by jbbrosset** [comment]
A priori, avant, les users pouvaient aussi inscrire les membre de leurs "groupes". Ce qui n'est plus le cas.

On a essayé d'affecter un groupe "Salariés" à une orga mais ça ne fonctionne pas (à quoi sert cette fonctionnalité ?)

**Comment by WalterMFR** [comment]
Bonjour,

Après plusieurs tests, voici ce que nous retenons de la nouvelle gestion des utilisateurs au sein d’un espace. 

- Donc pour ajouter un utilisateur ou un groupe (dans un espace) il faut passer par le troisième onglet  « Rôles », cliquer le nom du rôle souhaité et utiliser le bouton « + » qui se trouve à droite pour accéder à la liste des utilisateurs.

- On peut aussi ajouter des utilisateurs à un groupe et les inscrire à l’espace. (seulement si l’on est administrateur ou que l’on a la possibilité de gérer les utilisateurs d’une plateforme) 
Je suggère un message (ou bandeau d’information), si possible, du type « vous n’avez pas le droit » ou alors que le bouton « + » n’apparaisse pas pour ceux qui essaieraient d’ajouter des utilisateurs à un groupe, sans savoir qu’ils n’en n’ont pas le droit. (j’ai essayé la démarche jusqu’au bout et bien sûr ça ne marche pas mais on peut être induit en erreur, ça porte à confusion)

- Pourriez-vous confirmer que l’on ne peut pas ajouter d’utilisateurs dans un espace en passant par le premier onglet « utilisateurs » ?

Merci de votre attention.

**Comment by LaurentGruber** [comment]
corrigé
