### ISSUE TITLE
[ExoBundle] Implement lock Exercises

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#384]
When the Exercise is configured to not allow interrupts, we need to close the Paper if the User leave the Exercise player.

There was a function in the code but was never called :

```
public function forceFinishExercise($paperToClose)
    {
        $em = $this->doctrine->getManager();
        /** @var \UJM\ExoBundle\Entity\Paper $paper */
        $paper = $paperToClose;
        $paper->setInterupt(0);
        $paper->setEnd(new \Datetime());
        $em->persist($paper);
        $em->flush();

        $this->container->get('ujm.exo_exercise')->manageEndOfExercise($paper);

        return $paper;
    }
```

**Comment by Elorfin** [comment]
This test must be done while starting an attempt.

**Comment by Elorfin** [comment]
@david42 : the problem with the solution you propose is if the Student never try to start a new attempt, the Paper will never be marked as finished.

**Comment by Elorfin** [comment]
This is implemented in #452.

I don't want to close the issue has we need to find a better way to handle it.

**Comment by purplefish32** [comment]
@Elorfin : should we move this issue to the 16.09 milestone ?

**Comment by Elorfin** [comment]
yes it's done.
