### ISSUE TITLE
Afficher les groupes d'un utilisateur affiche les groupes de la fiche consultée précédement 

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#3849]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.11

Bonjour,
Dans le menu administration > gestion des utilisateurs lorsque je sélectionne un utilisateur et affiche les groupes qui lui sont affectés la requête me renvoie les bonnes informations.
Ensuite je clic  sur l'onglet utilisateur pour revenir à la liste, j'en sélectionne un nouveau et affiche ses groupes, ici ce sont les groupes de l'ancien utilisateur qui sont affichés.
Je reclic sur l'onglet utilisateur, je re-selectionne le même utilisateur et enfin les bons groupes associés s'affichent.
testé sur demo.claroline.com
Merci

**Comment by ngodfraind** [comment]
Reproduit.

**Comment by ngodfraind** [comment]
J'en profite pour dire que j'ai vu autre chose aussi:

Je suis dans la liste des utilisateurs, j'ai un groupe en base de données.
Je veux lui rajouter des groupes, il y a bien un groupe dans la liste.
Je cliquer sur l'onglet groupe et crée 2 groupes.
Je retourne sur mon utilisateur pour lui rajouter ces 2 groupes, seul le premier groupe est affiché (pas de requête en db).
