### ISSUE TITLE
cloisonnement d'organsiation inactif

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3859]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.4

J'ai créé une organisation de niveau 3 (sous-sous-organisation), RPIF 2017-2018
![image](https://user-images.githubusercontent.com/32478422/38243536-1c23ed1a-3738-11e8-95e2-3c19a6d1a20e.png)

Je nomme gestionnaire de organisation un utilisateur coordonnateurtest
![image](https://user-images.githubusercontent.com/32478422/38243826-0998a9be-3739-11e8-9ce0-26e29637c907.png)

Dans le gestionnaire des utilisateurs, le compte coordonnateurtest devrait voir son organisation et uniquement les utilisateurs rattachés à son organisation, mais il voit tous les utilisateurs de la plateforme et ne voit pas son organisation.
![image](https://user-images.githubusercontent.com/32478422/38243986-81fc54e6-3739-11e8-8f5f-c7a6fcd8d124.png)

**Comment by LaurentGruber** [comment]
Tu sais reproduire sur demo.claroline.com ?

**Comment by lgeschwine** [comment]
Dans demo.claroline.com
J'ai créé une organisation de niveau 3 : DFI-test
J'ai rattaché lgeschwine comme gestionnaire de DFI-test.
Lgeschwine voit tous les utilisateurs dans le gestionnaire des utilisateurs et ne voit pas son organisation. Par contre il peut créer des utilisateurs et les rattacher uniquement aux organisations dont il est le gestionnaire.

**Comment by ngodfraind** [comment]
Je confirme que ça fonctionne bien sur demo.
