### ISSUE TITLE
perte de l'onglet role dans le gestionnaire des utilisateurs

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3860]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.2.4

L'onglet rôle n'apparait plus dans l'interface de gestion des utilisateurs pour les utilisateurs non admin.
Est-ce normal?

**Comment by LaurentGruber** [comment]
oui, sinon, on peut se donner des droits admin ou s'octroyer d'autres rôles. C'est également le cas de la roue de paramètre et de la gestion des profils à facette

**Comment by lgeschwine** [comment]
est-ce une décision temporaire en attendant le cloisonnement des rôles ?

**Comment by LaurentGruber** [comment]
A priori non, si on laisse l'accès ouvert, rien n'empêcherait un utilisateur de créé un nouveau rôle auquel il donne plus de droit que le sien et de se l'assigner ...
