### ISSUE TITLE
Questionnaire : Mot anglais non traduit dans les paramètres de correction

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#3871]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | demo 11.2.13

Bonjour,

Dans un questionnaire, lorsque l'on ajoute des commentaires, il faut aussi les activer via les paramètres du questionnaire. Cela fonctionne. Cependant, le mot affiché est "feedback" au lieu d'activer les commentaires.
![image](https://user-images.githubusercontent.com/24249636/38300504-3f044648-37fd-11e8-9c66-72a36c51b7ae.png)
Merci.

**Comment by LaurentGruber** [comment]
C'est parce que cela fait plus que juste afficher les commentaires, cela affiche aussi la page de correction, avec l'info de savoir si la réponse est correct ou fausse sans pour au tant donner la bonne réponse ...

donc remplacer feedback par commentaire, n'est pas suffisant, par contre si tu as une meilleur proposition, volontier ...
