### ISSUE TITLE
pb publication parcours

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3908]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 10.2.4

Chaque étape se dupliquait en x exemplaire à chaque fois que je l'éditais et la publiais. Cela n'apparaît qu'en dehors de l'édition, donc impossible à modifier. 
![image](https://user-images.githubusercontent.com/32478422/38498668-7397eee4-3c05-11e8-84c9-d80a12e00823.png)
Maintenant, je n'arrive plus à publier le parcours.
![image](https://user-images.githubusercontent.com/32478422/38498725-a9c1b752-3c05-11e8-96e7-1a653d02e5e1.png)
![image](https://user-images.githubusercontent.com/32478422/38498753-ba6b9ffa-3c05-11e8-94ea-ee2f0843614c.png)

Deux exemples d'EA où j'ai le pb :
https://egreta.claroline.com/paths/301#/936
https://egreta.claroline.com/paths/354/

**Comment by LaurentGruber** [comment]
A priori c'est corrigé avec la nouvelle version de parcours, visible sur demo.claroline.com

**Comment by lgeschwine** [comment]
j'ai reproduit en partie l'EA sur démo, la suppression des étapes semblent fonctionner et la publication aussi.
Par contre, quand on pratique le parcours, la description des étapes ne s'affiche plus.
AVANT (version 10.2.4)
![image](https://user-images.githubusercontent.com/32478422/38499829-130b80d2-3c09-11e8-9187-c78f91924c7b.png)
APRES (version démo)
![image](https://user-images.githubusercontent.com/32478422/38499914-4a1d9876-3c09-11e8-821b-d58b04589df9.png)

**Comment by LaurentGruber** [comment]
corrigé : https://github.com/claroline/Distribution/pull/3909
