### ISSUE TITLE
accès au profil d'un ustilisateur impossible / idem pour l'accès aux groupes & roles

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#3913]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.16

Testé sur l'instance demo

A partir de la gestion des utilisateurs, je ne peux pas afficher le profil d'un utilisateur. Le clic est inopérant depuis le nom d'utilisateur ou le menu en bout de ligne.
<img width="960" alt="claro" src="https://user-images.githubusercontent.com/7293233/38550061-c1fa7510-3cb5-11e8-98c9-90d79f0855d8.png">

Lorsque je clic sur les onglets groupes / rôles / organisations... La liste ne se met pas à jour. La liste des utilisateur reste persistante.

<img width="960" alt="claro" src="https://user-images.githubusercontent.com/7293233/38550304-64c418a0-3cb6-11e8-8ec8-799747a3e377.png">

**Comment by ngodfraind** [comment]
Je n'ai pas pu reproduire, ni en local, ni sur demo.claroline.com.
Peut être raffraichir le cache avec ctrl+f5 ?

**Comment by flow39** [comment]
Oui c'est sans doute un problème de poste. J'ai refait des essais et ça fonctionne bien.
Merci.
