### ISSUE TITLE
améliorations ressources parcours

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3916]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.2.16

1. Lors de la création d'un parcours, la ressource est directement publiée (sur les versions précédentes elle était non publiée par défaut).

2. Lorsque je change le statut, la jauge de progression ne se met pas à jour.
![image](https://user-images.githubusercontent.com/32478422/38552113-6400b1ee-3cbb-11e8-8bc4-624790c42fd6.png)
Il faut rafraichir plusieurs fois la page pour obtenir les modifications enregistrées (comme image de la couverture par exemple).

3.  Il n'y a plus les conditions d'accès de passage à l'étape.
![image](https://user-images.githubusercontent.com/32478422/38566866-106cc156-3ce5-11e8-8b94-ae968221f243.png)
Ce qui serait intéressant de pouvoir mettre des conditions automatique ou manuelle de passage à l'étape suivante.

4.  Est-il possible de remettre le tableau de bord ?
![image](https://user-images.githubusercontent.com/32478422/38567071-8b7a58fe-3ce5-11e8-876e-63d53929663a.png)

**Comment by jbbrosset** [comment]
- [ ] En mode lecture/suivi de parcours, les ressources ne sont pas tout a fait responsive, par exemple quand on accède à une évaluation au sein d'un parcours les popups d'ajout sortent du cadre. On a un ascenseur mais niveau navigabilité c'est moyen.
![image](https://user-images.githubusercontent.com/35995165/38600243-c618ac9e-3d63-11e8-8474-14b69e3a9688.png)

**Comment by LaurentGruber** [comment]
1. C'est le comportement standard pour toutes les ressources désormais (on peut cocher de ne pas publier à la création)
2. la jauge de progression est lié à la vue non au statut
3. ça ne sera plus sur les étapes mais sur les ressources
4. Prévu pour plus tard
