### ISSUE TITLE
[CoreBundle] Resource Manager UX improvement proposals

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#3919]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | master

While in phase of refactoring, I would like to proceed with 2 UX improvement proposals that have been brought to my attention by our support team and our users.

1. Add resource indicators about the publication state (public, to platform users, to admins etc.) as well some info about the resource (resource type, creator etc.). Here's a mock-up example:
![screenshot_20180410_170059](https://user-images.githubusercontent.com/3414935/38565411-85d4d7d4-3ce1-11e8-954d-d9d61064a9b4.png)

2. Additional to that, it would be nice if some resource info could be shown in the "Edit rights" section, or in a "Resource state" section. As shown below:
![screenshot_20180410_170034](https://user-images.githubusercontent.com/3414935/38600768-8dfdc978-3d65-11e8-82af-d651f6676b0f.png)

**Comment by LaurentGruber** [comment]
! les couleurs ça ne fonctionne pas pour les daltonniens ...
