### ISSUE TITLE
Lecture des videos sur IOS ne se lance pas.

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#3947]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.2.21

Bonjour, 

La lecture des vidéos (mp4) sur les appareils IOS mouline.
En bombardant le bouton lecture une trentaine de fois, la lecture se lance parfois.
Testé sur demo.claro 
https://demo.claroline.com/resource/open/file/353#/play

**Comment by ngodfraind** [comment]
Reproduit.
