### ISSUE TITLE
[DropZone] divers

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#3950]
- [x] date de début et de fin de dépot écrite en dur dans l'interface de la page d'accueil (début toujours : 08/02/2018 08:30 et fin toujours : 28/02/2018 18:30) et ne récupère pas les paramètres
- [x] ajouter l'heure dans le choix de la date de début et de fin de l'évaluation
- [x] ajouter le ressource picker pour le dépôt de ressource
- [ ] dans la configuration des soumissions ajouter un paramètre nombre de fichier déposable par soumission (défaut 1). Si 1 sur ce param quand on dowload le zip des soumissions, il ne met pas les fichiers dans des dossier ...
- [ ] vérifier que les notifications au gestionnaire sur le dropzone arrivent bien (option recevoir une notification à la soumission de la copie)

**Comment by nicolasjacquemet** [comment]
Compilé dans #4486
