### ISSUE TITLE
Editeur texte riche : erreur avec ressource fichier AVI

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#3959]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.4

Bonjour,
J'ai un utilisateur qui a un message d'erreur lorsqu'il utilise l'éditeur de texte riche d'un widget texte et qu'il pointe vers une ressource fichier AVI d'un espace dont il est gestionnaire.

Sauf erreur de ma part, je sais que le format AVI ne peut pas être lu en ligne sur Claroline Connect mais il peut très bien être proposé en fichier téléchargeable comme un fichier Microsoft Office

Le format du fichier est reconnu dans les ressources mais impossible de faire le lien via le bouton ressource.

![image](https://user-images.githubusercontent.com/24249636/39037367-8bd5e64a-4480-11e8-88bb-f7b3398bbfd8.png)

Est ce que c'est un bug ou faut il bannir/déconseiller définitivement le format AVI? 

Merci de votre attention.

**Comment by ngodfraind** [comment]
Normalement ça ne de vrait pas arriver, je vais essayer aussi.

**Comment by WalterMFR** [comment]
Je rencontre le même problème avec les MP4.
