### ISSUE TITLE
Modification widget texte | bouton OK inactif

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#3978]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.27

Bonjour, 
Lorsque je modifie le contenu d'un widget texte et clique sur OK rien ne se passe, la facebox ne disparait pas.
Le contenu du widget texte a par ailleurs bien été modifié lorsque je réactualise la page.
Testé sur demo.claro

**Comment by LaurentGruber** [comment]
The route "claro_widget_instance_content" does not exist.

**Comment by ngodfraind** [comment]
Reproduit. Même erreur.
