### ISSUE TITLE
pb widget texte 

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3981]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.2.4

Lorsque j'essaie de faire un widget texte sur l'accueil de mon EA pour tester les iframe, je ne vois aucun des icônes de la barre des tâches :
![image](https://user-images.githubusercontent.com/32478422/39196466-802a99c0-47e2-11e8-8c7b-9b78b531e4b5.png)

et lorsque je vais dans Outils -> code source, Firefox m'affiche ce message d'erreur :
![image](https://user-images.githubusercontent.com/32478422/39196460-7b7896ac-47e2-11e8-8db7-1267982bfdd3.png)

**Comment by LaurentGruber** [comment]
Corrigé
