### ISSUE TITLE
(egretab) pb widget texte

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3993]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.2.27

J'ai créer un widget texte pour donner accès à une ressource par un lien
Je clique sur + pour ajouter la ressource
![image](https://user-images.githubusercontent.com/32478422/39254671-f548008a-48aa-11e8-8378-59812da6c311.png)
Mais je ne peux pas valider en cliquant sur OK

**Comment by LaurentGruber** [comment]
duplicate of : https://github.com/claroline/Distribution/issues/3978
