### ISSUE TITLE
Modification de widget

### ISSUE THREAD

**Issue by cmaccio** [claroline/Distribution#3995]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version 11.2.27  | egretab.claroline.com

**Comment by LaurentGruber** [comment]
Il n'y a pas de description, quel est le problèmes ?

**Comment by cmaccio** [comment]
Désolée. 
Quand je modifie un widget (avec le crayon) et que je valide (OK), je reste bloquée : rien ne se passe et les modifications ne sont pas prises en compte.

**Comment by LaurentGruber** [comment]
duplicate of https://github.com/claroline/Distribution/issues/3978
