### ISSUE TITLE
Ajout d'utilisateur dans un EA toujours impossible

### ISSUE THREAD

**Issue by cmaccio** [claroline/Distribution#3998]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?11.2.27      | egretab.claroline

**Comment by cmaccio** [comment]
L'ajout d'un utilsateur est toujours impossible dans un EA. Le bouton + est inactif

**Comment by flow39** [comment]
Complément par rapport à ce problème 
Avec un compte utilisateur disposant des outils gestion utilisateur & gestion espace d'activité, j'ai crée un EA. Lorsque je me rends dans l'outil utilisateur de cet EA, 
* je n'ai plus le bouton "créer un utilisateur"
![image](https://user-images.githubusercontent.com/7293233/39295180-0203b04c-493e-11e8-926d-45385b9b0c53.png)

* le bouton "inscrire un utilisateur" ne fonctionne pas

**Comment by LaurentGruber** [comment]
TypeError: props.callback is not a function
