### ISSUE TITLE
liste des rôles plateforme incomplète

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#3999]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.27

J'ai créé un utilisateur (formpdp) dans une nouvelle organisation (plan de pro). Je souhaite lui ajouter un rôle platforme mais je n'obtiens pas la liste complète quand je clique sur le plus.
![image](https://user-images.githubusercontent.com/32478422/39293638-ab922bca-4939-11e8-9462-afefcaa0784a.png)

![image](https://user-images.githubusercontent.com/32478422/39293608-980f5a3c-4939-11e8-8426-3524752b6507.png)

**Comment by ngodfraind** [comment]
Reproduit: l'admin ne voit que ses rôles.
