### ISSUE TITLE
problème chargement organisation dans la création d'un EA

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#4000]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.2.27

J'ai créé un EA avec un compte formateur test (formpdp) rattaché à l’organisation plan de pro.
Je souhaite rattacher l'EA à une organisation en cliquant sur le plus mais il doit y avoir un problème de performance de chargement qui fait planter le navigateur (sous chrome et firefox).
![image](https://user-images.githubusercontent.com/32478422/39295800-9aea288a-493f-11e8-9397-1b96d96b3b03.png)

**Comment by ngodfraind** [comment]
Pas reproduit en admin en local. J'essaye sur egretab.

**Comment by ngodfraind** [comment]
Problème reproduit sur egretab avec `formpdp` dans l'EA `formation test`.

**Comment by lgeschwine** [comment]
même pb pour le chargement des gestionnaires

**Comment by ngodfraind** [comment]
Pour ne rien arranger, "parfois", ça fonctionne.

**Comment by ngodfraind** [comment]
En faisant n'importe quoi j'ai finalement eu une erreur mais je pense que ça n'a rien à voir:

```
commons.js:130973 Uncaught Error: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bid%2C%20name%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at reactProdInvariant (commons.js:130973)
    at traverseAllChildrenImpl (commons.js:131378)
    at traverseAllChildrenImpl (commons.js:131327)
    at traverseAllChildren (commons.js:131406)
    at Object.instantiateChildren (commons.js:120000)
    at ReactDOMComponent._reconcilerInstantiateChildren (commons.js:125685)
    at ReactDOMComponent.mountChildren (commons.js:125718)
    at ReactDOMComponent._createInitialChildren (commons.js:121911)
    at ReactDOMComponent.mountComponent (commons.js:121730)
    at Object.mountComponent (commons.js:126358)
```

**Comment by ngodfraind** [comment]
Je vais passer sur un autre bug et garder celui là pour la fin.

**Comment by ngodfraind** [comment]
Je ne réussi plus à reproduire le problème de chargement de la liste des organisations.
Le chargement des gestionnaires lent est lié à https://github.com/claroline/Distribution/pull/4152
