### ISSUE TITLE
Gestion d'une sous organisation : plusieurs problèmes

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#4001]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.27

J'ai crée une sous-organisation de l'organisation académie de test. J'ai affecté un utilisateur en tant que gestionnaire de cet organisation. En me connectant avec ce le compte de ce dernier, lorsque je vais sur la gestion des organisations, rien n'apparait.
![image](https://user-images.githubusercontent.com/7293233/39296166-7c1b3146-4940-11e8-85a7-a201e1876171.png)

J'essaye quand même de créer une sous-sous-organisation. Elle est bien crée, mais n'apparait pas dans la liste. Je dois utiliser le compte admin pour la retrouver
![image](https://user-images.githubusercontent.com/7293233/39296278-c2826ba4-4940-11e8-8a88-b0c18431e01d.png)

Toujours connecté avec le compte gestionnaire de cette sous-sous-organisation, j'essaye d'affecter des utilisateurs. L'application me propose la liste de tous les utilisateurs de la plateforme alors que je ne devrai voir que les utilisateurs de cet organisation (liste vide puisque je viens de la créer)

**Comment by ngodfraind** [comment]
Reproduit localement.

**Comment by ngodfraind** [comment]
Compris et corrigé. Il y aura surement d'autres erreurs avec les organisations arborescente mais on corrigera. En tout cas celui là c'est bon.
