### ISSUE TITLE
Pb d'affichage d'un parcours

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#4005]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version? egretab     | 11.2.27

En voulant tester une ressource parcours, je m'aperçois qu'il y a des bugs d'affichage, le contenu n'apparait pas

![image](https://user-images.githubusercontent.com/32478422/39299334-c6d4fdd6-4948-11e8-9392-5483c2dee024.png)

![image](https://user-images.githubusercontent.com/32478422/39299290-ab20b1a2-4948-11e8-9710-2fb3b1eea673.png)

**Comment by LaurentGruber** [comment]
C'est réglé, un updater qui n'avait pas été exécuté.
Au passage ce sont des chouettes parcours, petit conseil pour l'auteur, désactiver la page d'accueil des exercices dans les options de l'exo ... ça donne mieux dans les parcours après ...
