### ISSUE TITLE
(egreta B) Problème parcours

### ISSUE THREAD

**Issue by pierrecamou** [claroline/Distribution#4012]
Vi| Q             | A
| ------------- | ---
| Bug report yes
| Version 11.2.27

Bonjour,

j'ai deux problèmes sur le parcours de mon EA dénommé "Suivi des Acquis".

1. J'ai créé des étapes mis des contenus mais la plateforme génèrent tout de seul de très nombreuses étapes vierges que je ne vois pas dans le menu édition de la ressource parcours mais qui en mode utilisateur rendent l'utilisation du parcours impossible. De plus ce problème n'apparait pas de la même façon sur egreta et gretab mais dans les deux cas le problème existe.
Voici les liens : https://egretab.claroline.com/resource/open/innova_path/19348#/   
et sur le egreta normal : https://egreta.claroline.com/paths/301/edit#/940 

2. Nous voulions pouvoir individualiser l'accès aux étapes dans le parcours en utilisant des rôles ou des mots de passes mais nous n'avons rien trouvé de bloquant qui fonctionne dans la ressource parcours. Par exemple, nous voulons pouvoir choisir à partir de quand tel stagiaire peut accéder à l'étape 3 du parcours. Nous avons besoin de vérifier manuellement des prérequis en amont.

Notre formation sur claroline doit démarrer au mois de juin 2018. Nous sommes donc impatient que cela puisse fonctionner.

Merci d'avance pour vos retour.

PIerre Camou (CFC à la DAFCO de Poitiers : 06 38 42 45 75)

**Comment by LaurentGruber** [comment]
1. Les étapes créées relètes les activités liées créé et publiées, elles n'ont pas été créées toutes seules... On voit sur le egreta de base qu'il y a tout une série de publication en attente..., cela reflète donc l'état tel que publié au moment de l'update. La notion de publication en attente, disparait.
2. Il n'y a pas à l'heure actuel de solution pour ça dans le parcours (c'est prévu mais pas d'ici juin). Par contre on peut le faire au niveau ressource en jouant avec les droits ...

**Comment by pierrecamou** [comment]
Bonjour,

 

En ce qui concerne la question des étapes vierges qui sont apparues. La question qui se pose est comment les faire disparaître puisqu’en mode édition on ne les voit pas ???

 

Merci d’avance de votre réponse.

 


Pierre CAMOU

Conseiller en Formation Continue

Délégation académique à la formation continue

– Rectorat de Poitiers

06 38 42 45 75 



 

 

 

De : Gruber Laurent <notifications@github.com> 
Envoyé : jeudi 26 avril 2018 15:54
À : claroline/Distribution <Distribution@noreply.github.com>
Cc : pierrecamou <pierre.camou@ac-poitiers.fr>; Author <author@noreply.github.com>
Objet : Re: [claroline/Distribution] (egreta B) Problème parcours (#4012)

 

1.	Les étapes créées relètes les activités liées créé et publiées, elles n'ont pas été créées toutes seules... On voit sur le egreta de base qu'il y a tout une série de publication en attente..., cela reflète donc l'état tel que publié au moment de l'update. La notion de publication en attente, disparait.
2.	Il n'y a pas à l'heure actuel de solution pour ça dans le parcours (c'est prévu mais pas d'ici juin). Par contre on peut le faire au niveau ressource en jouant avec les droits ...
