### ISSUE TITLE
Configuration de la barre des menus

### ISSUE THREAD

**Issue by cmaccio** [claroline/Distribution#4017]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version 11.2.29     | egretab.claroline

Dans les préférences, configuration de la barre des menus, je ne peux cocher que  les **3 derniers outils**. Ceux que j'avais coché initialement comme les ressources ont disparu de la barre des menus et je ne peux pas les rajouter. 
![image](https://user-images.githubusercontent.com/38736082/39327084-4364b6a4-4997-11e8-84d9-7546680676b5.png)

**Comment by LaurentGruber** [comment]
ce n'est pas un bug, c'est la configuration de l'admin qui le force

**Comment by lgeschwine** [comment]
c'est réglé
