### ISSUE TITLE
Editeur d'équations dans les questionnaires

### ISSUE THREAD

**Issue by cmaccio** [claroline/Distribution#4018]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version11.2.29   | egretab.claroline

Dans les outils du questionnaire, ne figure plus l'éditeur d'équation. 
![image](https://user-images.githubusercontent.com/38736082/39328449-badc72e0-499b-11e8-831f-405fcddb707c.png)

Est-ce un oubli ou doit-on s'en passer ?

**Comment by LaurentGruber** [comment]
Il reviendra dans quelques semaines, on doit le refaire ...

**Comment by cmaccio** [comment]
Je ne vois toujours pas l'éditeur d'équation dans les questionnaires. 
![image](https://user-images.githubusercontent.com/38736082/42471933-d62f0464-83bf-11e8-935b-1c6157067327.png)
Faut-il chercher ailleurs ?
