### ISSUE TITLE
Rôles attribués à un utilsateur  dans une organisation

### ISSUE THREAD

**Issue by cmaccio** [claroline/Distribution#4019]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version 11.2.29     | egretab.claroline

Je suis gestionnaire d'académie (Académie de LYON) et je crée un utilisateur (en passant par l'administration/gestion des utilsateurs). Quand je veux lui attribuer un rôle, j'ai le choix entre 9 rôles : 
![image](https://user-images.githubusercontent.com/38736082/39329511-d37da424-499e-11e8-8ca1-286dca266f32.png)

Or d'autres rôles ont été créés pour l'académie de Lyon ou d'autres. Comment faire pour les attribuer ? Par exemple le rôle stagiaire académie de Lyon. 
![image](https://user-images.githubusercontent.com/38736082/39329672-5cf80eb0-499f-11e8-939b-f051360161f6.png)
![image](https://user-images.githubusercontent.com/38736082/39329690-6e206ee4-499f-11e8-9c8f-8864fa0d6c76.png)

Pourquoi apparaissent uniquement ces 9 rôles ?

**Comment by LaurentGruber** [comment]
Seul les rôles que vous possédez apparaissent ...
