### ISSUE TITLE
Suppression de ressources dans le dossier d'un EA

### ISSUE THREAD

**Issue by ctouraille** [claroline/Distribution#4024]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | egretab.claroline

Il n'y a pas de bouton de confirmation pour la suppression
![image](https://user-images.githubusercontent.com/38788949/39367898-63307c06-4a38-11e8-9bcd-32de4a8ba1f8.png)

**Comment by flow39** [comment]
Le bouton réapparait au survol de la souris

**Comment by lgeschwine** [comment]
toutes les modales de demande de confirmation de suppression ou publication ont ce problème de bouton ok inactif mais visible au survol
