### ISSUE TITLE
[egretab] EA / widget texte / problème d'affichage pour l'ajout de ressources

### ISSUE THREAD

**Issue by ctouraille** [claroline/Distribution#4030]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | egretab.claroline.com

Dans le nouveau widget texte, sur google chrome, lorsque je clique sur le +, la fenêtre s'affiche en bas de l'écran (j'ai un petit portable) je n'ai accès qu'aux trois premières lignes.
![image](https://user-images.githubusercontent.com/38788949/39403599-ef8e112a-4b7f-11e8-844f-8e1e49c1b79e.png)
Sur Mozilla, au clic, le + devient noir, rien ne se passe
![image](https://user-images.githubusercontent.com/38788949/39403643-c3b5ffb2-4b80-11e8-9c17-6b3242ddc388.png)

**Comment by lgeschwine** [comment]
présent dans la version 11.2.31
pour compléter, lorsque le widget se trouve en haut de page pas de problème
![image](https://user-images.githubusercontent.com/32478422/39632419-550d474e-4fb5-11e8-8463-225d79ca21a5.png)
par contre plus le widget et bas plus le menu déroulant va descendre hors cadre et donc devenir invisible
![image](https://user-images.githubusercontent.com/32478422/39634825-1358f954-4fbc-11e8-85b4-9f2f3b278ef2.png)
