### ISSUE TITLE
perte des paramètres d'affichage des EA

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#4034]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.2.31

Je souhaite le faire s’ouvrir directement un EA sur une ressource mais dans les paramètres des informations générales, il n'y a plus possibilité de le faire, à la place 2 onglets vides ( !!) : Activation du compte et Affichage.
![image](https://user-images.githubusercontent.com/32478422/39426761-5bb71ac0-4c81-11e8-8fb4-773f81c3006e.png)

**Comment by ngodfraind** [comment]
Je regarde ça tout de suite.
