### ISSUE TITLE
TinyMCE bug d'affichage des menus déroulants

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#4036]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.31

J'édite une ressource de type blog. En voulant utiliser, par exemple, le menu "insérer", celui-ci s'affiche en bas de la page :
![image](https://user-images.githubusercontent.com/7293233/39429833-6fb175b0-4c8c-11e8-8c7e-c26d561d13e9.png)

**Comment by jbbrosset** [comment]
Nous avons le même problème dans les éditeurs de texte des widgets
