### ISSUE TITLE
Improvement: add a custom message upon registration

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#405]
When i register students, they receive a standard mail with the plateform adress; their username and password. But since they dont know the platform yet and where to go next, it woud be nice to have the possibility to add a custom html textarea for further explanation (available in the import page). for instance
"you will soon be registered in the [SomethingWorkspace](link)..."

The alternative would be : 
- to hope (!!) they would find the right place (even with a explicative text widget on their home, some can't understand. Not everybody is used to internet and e-learning)
- to send in a regular email (outside the platform) those informations => i don't think it can be done in the message tool, since by default they won't have the checkbox "receive messages in my external email"

**Comment by LaurentGruber** [comment]
dans admin > paramètres de la plateforme > mail > layout tu peux éditer le layout du mail envoyé à l'inscription, ça ne répondrait pas au moins en partie à ton besoin ?

**Comment by CPASimUSante** [comment]
@LaurentGruber no. as i said, the layout template allows to send a generic email ("you  are registered on %platfrom% with username %un% and password %pwd%
But this "template" is by definition generic. I would like to add some custom directions, like : you'll be registered to this WS(link to the WS) ..." . So in the import users page, add a tinymce whose content woud be added to the template.
