### ISSUE TITLE
Format fichier import

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4054]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.2.31

Dans les pages "Import/Export de données", lors de la sélection d'une action à effectuer dans le menu déroulant, les champs à indiquer dans le fichier csv n'apparaissent plus. J'ai essayé l'import en reprenant un ancien fichier comme base, l'enregistrement n'a pas fonctionné.
![image](https://user-images.githubusercontent.com/35995165/39562600-d4b6b8ea-4eac-11e8-9a13-a01d0c9c0ed7.png)

**Comment by LaurentGruber** [comment]
fix by : https://github.com/claroline/Distribution/pull/3961
