### ISSUE TITLE
Paramètres de l'EA > Informations Générales

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4060]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.31

En ouvrant la page, je tombe sur deux onglets cliquables, mais vides... 
![image](https://user-images.githubusercontent.com/35995165/39576741-771b90c4-4edf-11e8-9358-5cbb691aa765.png)

**Comment by LaurentGruber** [comment]
copie de https://github.com/claroline/Distribution/issues/4034
