### ISSUE TITLE
attribution badge impossible

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#4065]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.31

L'attribution d'un badge dans un espace est impossible, aucun outil de recherche de groupes ou d'utilisateurs n'est présent.
![image](https://user-images.githubusercontent.com/32478422/39618696-3276e5a8-4f85-11e8-99f7-976a095ff325.png)

**Comment by DanielGrondin85** [comment]
Bonjour,
dans web/packages il faut remplacer Select2 pat select2 tout simplement.

Bien cordialement

**Comment by rudzboy** [comment]
Toujours d'actu.
De mon point de vue c'est côté templates qu'il faut changer la cible vers Select2.
(v 11.3.15)
