### ISSUE TITLE
désincription dans un EA

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#4081]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11..2.31

Dans les EA, impossible de désinscrire les utilisateurs inscrits avant la nouvelle version. Pas de problème avec les nouveaux inscrits.
![image](https://user-images.githubusercontent.com/32478422/39807051-a9b88758-537b-11e8-99c9-9c5a45eaf118.png)

**Comment by LaurentGruber** [comment]
tu ne peux pas le déscinscrire car il est inscrit via un group ... ce n'est pas un bug, c'est normal, tu dois désinscrire le group
