### ISSUE TITLE
Pb ressource évaluation

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#4106]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.2.31

J'ai créé un sondage et en souhaitant le modifier en cliquant sur le crayon, impossible de faire quoique ce soit.
![image](https://user-images.githubusercontent.com/32478422/39987260-914df8f0-5764-11e8-8a0f-ca02da4cc193.png)
Si je clique sur éditer les propriétés, impossible de fermer la fenêtre et le navigateur reste planté sur la fenêtre des propriétés.
![image](https://user-images.githubusercontent.com/32478422/39986752-efb764e6-5762-11e8-84df-def5f9fec270.png)

**Comment by LaurentGruber** [comment]
les captures montrent une ressource évaluation, tu peux préciser ?

**Comment by lgeschwine** [comment]
autant pour moi, c'est une ressource évaluation
