### ISSUE TITLE
[ExoBundle] Les indices sans pénalité bloquent la correction manuelle des questions ouvertes

### ISSUE THREAD

**Issue by nicolasjacquemet** [claroline/Distribution#4115]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 10.x

Si l'on définit un indice sans pénalité sur une question ouverte :
![image](https://user-images.githubusercontent.com/3415139/40055864-b8597d8a-5849-11e8-8bbe-524de9770fa1.png)

et que les étudiants utilisent l'indice lors de leur réponse, il n'est alors pas possible de corriger la question ouverte via correction manuelle. Quand on essaye de sauvegarder le score, une erreur 422 Unprocessable Entity est levée:

![image](https://user-images.githubusercontent.com/3415139/40055776-5faef570-5849-11e8-8cd7-d481b7965943.png)
![image](https://user-images.githubusercontent.com/3415139/40055839-99939f16-5849-11e8-9f42-a0773d5408cf.png)

Le problème n'a pas l'air d’apparaître si une pénalité est définie ou si le répondant n'utilise pas l'indice.

**Comment by Elorfin** [comment]
Corrigé par https://github.com/claroline/Distribution/pull/5738.
