### ISSUE TITLE
perte de widget

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#4126]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| egretab     | 11.3.7

En testant le widget "derniers messages du forum", je m'aperçois qu'il s'affiche dans l'onglet de création après validation.
![image](https://user-images.githubusercontent.com/32478422/40118203-8aa1b166-5919-11e8-9c55-7bacca3d19fc.png)
Je vais dans ressources pour poster un sujet dans le forum et le widget disparait.
![image](https://user-images.githubusercontent.com/32478422/40118237-a5bada36-5919-11e8-84d3-8cd497c48717.png)

J'ai testé tous les widgets et aucun ne reste

**Comment by LaurentGruber** [comment]
@lgeschwine tu pourrais mettre des liens vers egretab où on peut voir le souci
