### ISSUE TITLE
page de login en partie en anglais

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#4131]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| egretab      | 11.3.7

Sur le clone egretab, la page de login est en partie en anglais

![image](https://user-images.githubusercontent.com/32478422/40124039-e7c31390-5927-11e8-81b1-a9c9629117a5.png)

**Comment by LaurentGruber** [comment]
le bouton c'est du à votre thème, la trad, c'est une mauvaise manip quand j'ai mis à jour, je vais corriger ...
