### ISSUE TITLE
couleur fond EA

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#4134]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| egretab      | 11.3.7

Workspace 1063 : Les couleurs de fond d’écran ne sont pas prises en compte (que ce
soit avec les couleurs de la palette par défaut, ou avec un code couleur autre) ni après
enregistrement, ni après reconnexion. 
![image](https://user-images.githubusercontent.com/32478422/40124563-1eac2b52-5929-11e8-84e6-72bf52708dc6.png)

**Comment by LaurentGruber** [comment]
c'est probablement une option qui va disparaitre ...

**Comment by vperlab** [comment]
Noon, surtout pas, c'est une des plus belles et originales fonctions de la plateforme, nous sommes nombreux à attendre sa restauration svp !
