### ISSUE TITLE
outil de recheche de ressources non cloisonné

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#4135]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.3.7

Lorsque nous recherchons une ressource pour l'intégrer dans un parcours ou dans un widget texte ou pour l'ouverture d'un EA sur une ressource etc, il n'y a pas de cloisonnement par organisation des ressources. 
Ce qui veux dire que n'importe qui peut utiliser n'importe quelle ressource de n'importe quelle organisation.
![image](https://user-images.githubusercontent.com/32478422/40125057-389ef246-592a-11e8-8a24-c1e28d8c9d03.png)

**Comment by lgeschwine** [comment]
c'est l'inverse, il semble que nous accédons à toutes ressources, même celles d'EAP
![image](https://user-images.githubusercontent.com/32478422/40163944-7c6f8d26-59b8-11e8-9393-fce8c6a1a999.png)

**Comment by ngodfraind** [comment]
Reproduit.

**Comment by lgeschwine** [comment]
problème toujours présent dans la v11.3.10
par exemple dans le parcours 0 de l'EA suivant https://egreta.claroline.com/resource/open/innova_path/26754#/edit/d4587f59-1c77-472a-bdb7-7f2cb2306226
impossible de retrouver la ressource évaluation suivante :
https://egreta.claroline.com/resource/open/claroline_dropzone/26744

**Comment by LaurentGruber** [comment]
Je viens d'essayer et ça fonctionne bien, tu verras que j'ai ajouter l'évaluation mentionner sur l'étape 2 (dernière étape) de ton parcours.
Je me suis biensur ajouter comme gestionnaire de l'espace avant afin de bien voir les ressources ...

**Comment by lgeschwine** [comment]
![image](https://user-images.githubusercontent.com/32478422/40372407-e8ccbc8e-5de4-11e8-9d8d-ea32557e09d3.png)
![image](https://user-images.githubusercontent.com/32478422/40372448-0007e5c2-5de5-11e8-8445-470a0a8bbb41.png)
je ne sais pas pourquoi mais moi ça ne marche pas en tant qu'admin, j'ai dû m'ajouter en tant que gestionnaire de l'EA. Il me semblait que tous les admin était par définition gestionnaire de tous les EA. Je le saurais pour la prochaine fois.
Merci

**Comment by LaurentGruber** [comment]
Non, ils ne sont pas gestionnaire, ils ont tous les droits, mais pour la recherche de ressource, on limite aux vrais gestionnaires, sinon l'admin verrait toutes les ressources de tous le monde, et ne saurait plus travailler du tout ...
