### ISSUE TITLE
Gestion des utilisateurs - aucun résultat trouvé

### ISSUE THREAD

**Issue by AnneZarka** [claroline/Distribution#4144]
| Q             | A
| Aucun utilisateur n'apparaît dans la liste des utilisateurs (aucun résultat trouvé), en revanche, les groupes apparaissent bien et les utilisateurs des groupes aussi.| ---
| Bug report?   | **yes**/no
| Version?      | https://egretab.claroline.com/admin/open/user_management#/users

**Comment by lgeschwine** [comment]
Avec quel compte ?
quel rôle ?

**Comment by AnneZarka** [comment]
Avec mon compte (azarka) et les multiples rôles associés (Utilisateur, Créateur d'espaces, Gestionnaire de l'accueil, Gestionnaire de compétences, Formateur - Fo, Gestionnaire d'académie, Gestionnaire de Greta (CO), Académie de PARIS ( 01 ), apprenant SPOC, stagiaire, Administrateur d'organizations, test)

**Comment by ngodfraind** [comment]
Reproduit.

**Comment by ngodfraind** [comment]
Corrigé sur egretab
