### ISSUE TITLE
désincription impossible des gestionnaires dans un EA

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#4145]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| egretab     | 11.3.7

Sur un EA dupliqué ou non, impossible de désinscrire un utilisateur gestionnaire autre que soit même. 
bouton désinscrire ou corbeille inactif
Est-ce normal ?

**Comment by ngodfraind** [comment]
J'ai pu reproduire quelque chose de similaire. Mais c'est le premier user qui peut être désinscrit (pas les autres).

**Comment by ngodfraind** [comment]
Et y a pas que ça la requête est lente. Je regarde pour optimiser comme dans les workspaces.

**Comment by ngodfraind** [comment]
note pour moi même, il faut faire un union (ou 2 requêtes).
Le problème c'est que notre backend supporte pas de faire 2 requêtes et que doctrine ne supporte pas union.
