### ISSUE TITLE
EA : Paramètres et suppression d'espace: écran vide

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#4146]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.2.31

![image](https://user-images.githubusercontent.com/24249636/40178359-8ee426fa-59e1-11e8-8ded-805b5d07fe52.png)
Bonjour,
Je n'ai plus accès aux paramètres d'un espace. 
J'ai un écran vide sur les deux onglets.
De ce fait je ne peux pas supprimer un espace.

**Comment by LaurentGruber** [comment]
vérifie sur mfrb mais normalement c'est résolu déjà
