### ISSUE TITLE
Widget texte / pas possible d'insérer

### ISSUE THREAD

**Issue by ctouraille** [claroline/Distribution#4150]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | version 11.3.7 (egretab)

Le bouton pour insérer ne fonctionne pas dans le widget texte sur chrome
![image](https://user-images.githubusercontent.com/38788949/40185836-e7682ed6-59f3-11e8-8fe0-0f0a11b81c61.png)

**Comment by lgeschwine** [comment]
c'est le même problème de menu déroulant hors du cadre de la fenêtre, plus le widget est bas plus le menu déroulant se décale vers le bas et au bout d'un moment il devient invisible car hors de la fenêtre
