### ISSUE TITLE
Évaluation : Impossible de configurer, ressource bloquée

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#4160]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | master/7.0/etc.

Bonjour,
Je ne peux pas configurer la ressource évaluation (consignes...)

https://w-alter.mfr.asso.fr/resource/open/claroline_dropzone/104499#/edit

![image](https://user-images.githubusercontent.com/24249636/40233417-315bec44-5aa3-11e8-919c-af963554ac6c.png)

Merci.

**Comment by LaurentGruber** [comment]
le lien dans le ticket n'amène nul part ... tu en aurais un autre ? où tu peux nous donner le chemin pour rejoindre la ressource (E.A. et dossier)

**Comment by LaurentGruber** [comment]
Je n'arrive pas à reproduire ...

**Comment by WalterMFR** [comment]
J'ai recrée une autre évaluation.
https://w-alter.mfr.asso.fr/resource/open/claroline_dropzone/104573#/edit

**Comment by LaurentGruber** [comment]
tu peux préciser ce qui ne fonctionne pas ?

**Comment by WalterMFR** [comment]
Bonjour,
Je viens de tester ce matin et l'écran de configuration apparaît de nouveau.
Je n'y avais pas accès jeudi et vendredi.
Merci.

**Comment by LaurentGruber** [comment]
parfait, la mise à jour l'a peut être résolu
