### ISSUE TITLE
Décentration du bouton “Inscription” sur la page de connexion.

### ISSUE THREAD

**Issue by vperlab** [claroline/Distribution#4174]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.3.10

Décentration du bouton “Inscription” sur la page de connexion.

![bug_decentration_inscription](https://user-images.githubusercontent.com/8589147/40351041-b913c1f6-5dab-11e8-8289-96552549f794.png)

**Comment by LaurentGruber** [comment]
c'est lié à votre theme, pas au theme par defaut
