### ISSUE TITLE
Problème de visualisation avec "Se connecter en tant que Collaborateur"

### ISSUE THREAD

**Issue by vperlab** [claroline/Distribution#4176]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.3.10

Gestionnaire de plusieurs EA, quand je me "Connecte en" Collaborateur pour visualiser le rendu de l'interface avec ce rôle, je reste toujours en édition sur les onglets et les widgets, avec ajout de widget possible. Je ne peux donc pas visualiser le rendu des EA que je gère pour leurs collaborateurs, sauf en créant un compte de test auquel j'attribue exclusivement le rôle Collaborateur. D'autres utilisateurs de mon organisation rencontrent le même souci.

![bug_edition_collaborateur](https://user-images.githubusercontent.com/8589147/40352026-26de477c-5dae-11e8-996c-1ac2c9bb7e96.png)

**Comment by flow39** [comment]
Quand je test "en tant que toi" ça fonctionne. L'édition disparait. Est ce que c'est patché ? Actuellement en v 11.3.12.

**Comment by vperlab** [comment]
Merci Florian de te pencher sur tous ces soucis qui nuisent à la qualité de mon expérience egreta.claroline !

Malheureusement, comme précédemment, j’ai toujours le souci à mon niveau ...

 



 

Bien cordialement,




 <http://www.ac-clermont.fr/> http://www.ac-clermont.fr/fileadmin/CSigne/logo_academique_simplife.png

Victoria PERES-LABOURDETTE LEMBE

Chargée de mission transformation digitale et systèmes d’informations pédagogiques 

-

Correspondante académique fonctionnelle et technique du consortium national e-GRETA

 

 

Pôle recherche et développement pédagogique - CAFOC

DAFPIC GIP : Délégation académique à la formation professionnelle initiale et continue tout au long de la vie - Groupement d'intérêt public Auvergne

04 73 99 35 47
victoria.peres@ac‑clermont.fr ‑ cafoc@ac‑clermont.fr

 


RECTORAT ‑ 3 avenue Vercingétorix - 63033 Clermont-Ferrand Cedex ‑  <http://www.ac-clermont.fr/> Site internet

 

De : ffroidurot [mailto:notifications@github.com] 
Envoyé : jeudi 7 juin 2018 14:39
À : claroline/Distribution
Cc : vperlab; Author
Objet : Re: [claroline/Distribution] Problème de visualisation avec "Se connecter en tant que Collaborateur" (#4176)

 

Quand je test "en tant que toi" ça fonctionne. L'édition disparait. Est ce que c'est patché ? Actuellement en v 11.3.12.
