### ISSUE TITLE
Problème de visibilité des EA modèles dans Administration / Gestion des espaces d'activités

### ISSUE THREAD

**Issue by vperlab** [claroline/Distribution#4177]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.3.10

Bonjour,

Dans Administration / Gestion des espaces d'activités, aucun EA modèle que j'ai créé (ou que d'autres ont créé) n'est visible.

Merci.

**Comment by lgeschwine** [comment]
Pourrais-tu nous faire une image de l'écran stp ?

**Comment by vperlab** [comment]
![bug_ea_modele_1](https://user-images.githubusercontent.com/8589147/40356437-51cc6cce-5db9-11e8-8305-eaf50d357b3d.png)
![bug_ea_modele_2](https://user-images.githubusercontent.com/8589147/40356438-51ee0578-5db9-11e8-9b43-870dac981d3d.png)

**Comment by LaurentGruber** [comment]
Tu as ajouter le filtre modèle : oui ?

**Comment by flow39** [comment]
@vperlab : lorsque je teste "en tant que toi", j'arrive bien à afficher les modèles dans la liste de tes EA après avoir effacé le filtre "Modèle : non".
Deux modèles sont alors présents dans la liste.
Peut être que ce problème à été patché depuis ? Nous sommes actuellement en v 11.3.12

**Comment by flow39** [comment]
@LaurentGruber 
En fait dans administration, -> gestion des EA, les modèles s'affichent bien lorsque l'on désactive le filtre par défaut "modèles : non"
Sur la deuxième capture d'écran, c'est la liste des EA qui est affichée (celle accessible à partir de la barre de menu ou du widget). 
C'est peut être voulu de ne pas voir les modèles d'EA à cet endroit ?

**Comment by flow39** [comment]
@LaurentGruber 
Le ticket est résolu et peut être fermé, nous avons vérifié les configurations des EA en questions. Je referai un nouveau ticket si je constate que c'est lié à une configuration qui ne persiste pas.
