### ISSUE TITLE
Pb import parcours

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#4178]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.3.10

Impossible d'importer un parcours entre deux EA.
Je souhaite importer un parcours de l'EA SPOC ... session 3 vers SPOC session 4 mais le parcours importé est vide.
![image](https://user-images.githubusercontent.com/32478422/40355358-719f4470-5db6-11e8-876e-b82518f728f3.png)

**Comment by LaurentGruber** [comment]
Et tu passes par quoi pour faire "l'import" ?

**Comment by lgeschwine** [comment]
Je vais dans l'EA de la session 3, je sélectionne le parcours, je clique sur exporter pour récupérer le fichier.
Ensuite, dans l'EA de ma session 4, je fais ajouter - parcours et je choisis le parcours précédemment exporter en .zip.
L'import semble se faire mais quand j'ouvre le parcours, il est vide de contenu.

**Comment by LaurentGruber** [comment]
Pourquoi ne pas directement aller dans EA ma session 4 cliquer sur ajouter et aller chercher le parcours de l'E.A. 3 via le gestionnaire de ressource ?

**Comment by LaurentGruber** [comment]
c'est ce que fait la fonction ajouter, elle fait une copie du parcours et de toutes les ressources associées
