### ISSUE TITLE
pb ressources annonce

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#4186]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.3.10

J'ai créé une ressource annonce mais quand je veux l'éditer, j'ai une page blanche qui s'affiche.
![image](https://user-images.githubusercontent.com/32478422/40435807-cf6cd49a-5eb1-11e8-9cc2-886eea55f438.png)

**Comment by LaurentGruber** [comment]
fix par https://github.com/claroline/Distribution/pull/4191
