### ISSUE TITLE
PB pour modifier un parcours

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#4204]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.3.10

Je n'arrive pas à effacer une page dans un parcours que j'ai fait il y a un mois : je clique sur la poubelle, la page disparait du menu mais quand je clique sur la disquette rien ne se passe et je ne peux plus rien faire sur la page, je dois rafraichir pour revenir en arrière.

![image](https://user-images.githubusercontent.com/32478422/40533160-17730ea2-6002-11e8-8a64-6f2d6d1db127.png)

**Comment by LaurentGruber** [comment]
tu pourrais mettre un lien et le nom des étapes que je peux supprimer ?

**Comment by flow39** [comment]
@LaurentGruber , vu avec @lgeschwine , le ticket peut être fermé. Merci.
