### ISSUE TITLE
Bug : no WS import on monolithic-build

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#423]
I've tested for https://github.com/claroline/Distribution/issues/89 to export the WS @LaurentGruber  gave me access to. I tried to import it on a local instance, but it failed : 

- no error displayed on screen
- no error displayed in dev.log

I logged out and reloaded : no WS imported.

**Comment by purplefish32** [comment]
@CPASimUSante, now that the monolithic-build branch has been merged into the master branch, is this issue still valid/open ?

**Comment by CPASimUSante** [comment]
For this one (no error dispalyed), it should be closed. But I open another one where i have an error

**Comment by purplefish32** [comment]
OK
