### ISSUE TITLE
Suivi utilisateur indisponible

### ISSUE THREAD

**Issue by AnneZarka** [claroline/Distribution#4245]
Quand je me connecte avec mon compte, et clique sur "voir le suivi" d'un utilisateur, je tombe sur une page blanche. Exemple d'url "vide" : https://egreta.claroline.com/user/tracking/nicolas.chaton#/

| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

**Comment by AnneZarka** [comment]
Bonjour,
Je constate ce matin que le pb persiste toujours. Page blanche au clic sur "voir le suivi", quel que soit l'utilisateur concerné.
Cdt

**Comment by LaurentGruber** [comment]
normal, c'est corrigé sur nos version de développement, ici la 12. Donc ça sera effectif après une prochaine mise à jour vers la 12

**Comment by AnneZarka** [comment]
OK, j'ai été trop rapide... merci.
