### ISSUE TITLE
Parcours : problème d'affichage Scorm

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#4295]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.3.10

Bonjour,
Nous utilisons des fichiers SCORM que nous avons intégré dans une ressource parcours.

Précédemment, nous avions trouvé une solution aux problèmes d’affichage des fichiers SCORM qui se réduisaient en fixant la hauteur en pixel dans les paramètres.

Actuellement sur la 11.3.10,  SCORM se réduit (sur certaines pas sur toutes alors que le paramétrage est le même) .

Exemple : https://w-alter.mfr.asso.fr/resource/open/innova_path/93347#/play/b901f37f-4c2b-11e8-98be-0cc47a960f96

Merci de votre attention.

**Comment by LaurentGruber** [comment]
On refait la ressource scorm en react, ce qui devrait complètement régler le problème ... Le travail est en cours ici : https://github.com/claroline/Distribution/pull/4240
