### ISSUE TITLE
pb d'affiche de bureau pour un utilisateur

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#4365]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.3.12

Lors de la connexion d'un utilisateur test **user@test.fr**, nous arrivons directement sur l'accueil d'un EA et non sur le bureau du compte.
![image](https://user-images.githubusercontent.com/32478422/42244858-d9b5b48c-7f16-11e8-9a38-1c3c4b43e504.png)

Comment est-ce possible ?

**Comment by flow39** [comment]
Sur notre instance, le workspace dont il est question est le 1449.
