### ISSUE TITLE
Bug : import WS in GUI 

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#450]
Iwanted to export a WS in the import page.
I have tested a WS import on a monolithic build with no success and talked about it in gitter with @ngodfraind : @charlotte42  has the same bug : error when uploading in GUI, but apparently ( @ngodfrain tested it) the upload is ok when uploading in CLI. 
Something like : 
` Warning: ZipArchive::extractTo(/tmp/phpc10Pcv/manifest.yml): failed to open stream: No such file or directory`

Nico said he was on it, but i don't knwo if it's done.

**Comment by ngodfraind** [comment]
This is supposed to be fixed by #436

**Comment by CPASimUSante** [comment]
ok missed that : you can close it then. i'll test it when i'll setup a brand new install
