### ISSUE TITLE
Outils en cours de refonte

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#4525]
- [x] mettre un message en travaux sur admin/open/notification_configuration
- [x] mettre un message en travaux sur admin/open/formalibre_presence_admin_tool et sur desktop/tool/open/formalibre_presence_tool
- [x] mettre un message en travaux sur l'admin des cursus
- [x] mettre un message en travaux sur /admin/open/LTI
- [x] mettre un message en travaux sur desktop/tool/open/dashboard
- [x] mettre un message en travaux sur desktop/tool/open/formalibre_reservation_agenda

Pour le message voir : admin/open/learning-objectives

- [x] supprimer desktop/tool/open/claroline_activity_tool

**Comment by ngodfraind** [comment]
- [ ] blog
- [ ] messagerie pickers
