### ISSUE TITLE
[CoreBundle] Move angular-data-table to CoreBundle

### ISSUE THREAD

**Issue by ngodfraind** [claroline/Distribution#454]
The data table library is very buggy for checkboxes with lazy loading. I did a lot of monkey patching to handle it but it needs much more than that (these patches are bad for large selections altough they won't happen a lot imo).

This library is well written with es6 so it's not that hard to read to comprehend, but still.

we either need to:
- write our own library from scratch (we could use the data-table as a baseline)
- an other library (wich could run into the same issues anyway)

To be honest, I'd rather be writing our own even if it's from scratch, because it's a pain when they don't work.

**Comment by Elorfin** [comment]
+1 for writing our own directive.
ANother problem with `angular-data-table` is that it doesn't use Bootstrap styles.

Anyway we will need to all use the same table library (for example, in exercise ti's `angular-table` which is used).

**Comment by LaurentGruber** [comment]
on remplace par le composant react
