### ISSUE TITLE
Undesired alert when redirecting to workspace after creation

### ISSUE THREAD

**Issue by kitan1982** [claroline/Distribution#4609]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.x

An alert pops up when trying to redirect to a newly created workspace.
![workspace_creation_popup](https://user-images.githubusercontent.com/3715017/44912615-173ef100-ad2b-11e8-83c2-0b7ba68f9ef3.png)

https://github.com/claroline/Distribution/blob/12.x/main/core/Resources/modules/workspace/creation/store/actions.js#L36

**Comment by Elorfin** [comment]
Corrigé en 12.5
