### ISSUE TITLE
Graphic question

### ISSUE THREAD

**Issue by david42** [claroline/Distribution#461]
If the picture is resized in the creation, the new size is not recorded, therefore the question not works correctly.

**Comment by Elorfin** [comment]
Also the mark method seems to not take into account the `circle` shape. Not tested, but as seen in the code, the validation of coords is always done in a square shape.

**Comment by charlotte42** [comment]
Maintenant lorsque l'on modifie la taille de l'image à la création d'une question graphic l'enregistrement ce fait correctement en BBD. Par contre j'ai remarqué plusieurs chose : 

- Si on modifie la taille de l'image cela impact toutes les questions où l'image est utilisé (c'est pas vraiment un problème mais il faut le savoir)

- Dans le player il ne met pas la taille définis dans le json/BBD (mais les questions et zone de réponse sont cohérente)

- Pour les zones de réponses rectangles le json renvois bien l'information rectancle mais est-ce qu'il manque autre chose ?

Du coup pour cette issue est-ce que le premier point suffit ?

**Comment by Elorfin** [comment]
- As the other modifications of a Question, so it's not a problem
- The size is used. In the player the image is responsive and the DB size is used to calculate the correct positions (areas + pointers) based on the screen size.
- The JSON export the correct shape for rectangle and circle but the API does not take into account the circle shape when calculating score.

**Comment by charlotte42** [comment]
Pour le deuxième point, du coup ça sert a rien de changer la taille de l'image si elle s'adapte automatiquement dans le player : 
![selection_054](https://cloud.githubusercontent.com/assets/11042666/16042035/e8f2d696-3238-11e6-87b5-197b3cbd5c19.jpg)
et si le résultat affiche toujours : 
![selection_055](https://cloud.githubusercontent.com/assets/11042666/16042060/0bad4db0-3239-11e6-9e4c-53df648bf0b3.jpg)

Je regarde du coup le 3eme point

**Comment by purplefish32** [comment]
Needs new ticket for circle
