### ISSUE TITLE
Ressources indisponibles d'un EA pour utilisateurs d'un autre EA

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#4623]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 11.3.15

Bonjour, 

Je souhaite rendre les ressources d'un EA disponibles pour les utilisateurs d'autres EA.
J'ai configuré les droits de ces ressources, cependant le widget "liste des ressources" ne me revoit rien depuis les autres EA lorsqu'il pointe sur ces ressources rendus public aux utilisateurs de la plateforme.

**Comment by LaurentGruber** [comment]
le widget liste des ressources sur une page d'accueil d'un ea, ne montre que les ressources de l'E.A. en questions ... et non toutes les ressources publiques ...
