### ISSUE TITLE
Pb mise à jour questionnaire

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#4631]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 11.3.12

À la demande d'un collègue, des modifications ont été apportées à la ressource (i.e. Ajout de niveaux de réponse aux questions). https://egreta.claroline.com/resource/open/ujm_exercise/20877#/test

En mode édition et en mode 'Tester le questionnaire' je vois bien apparaître les modifications.
Par contre dès que je veux utiliser le questionnaire, la plateforme me propose l'ancienne version. Dans le menu 'Ressources', quand je clique sur la ressource Questionnaire, c'est également l'ancienne version qui apparaît!
C'est comme si j'avais deux versions: une version /play et une autre /test.

Par ailleurs, quand je tente un export en CSV, je ne récupère pas l'intégralité des champs mais uniquement 5 colonnes (nom, prénom, date, score, score global) sans les en-têtes des questions.

Merci

**Comment by flow39** [comment]
@lgeschwine @LaurentGruber 
j'essaye de reproduire sur l'instance de test en 12.0.8, je me rend compte que le questionnaire est un lien vers celui en prod.
Apparemment je ne peux pas importer le questionnaire de la v11 vers la v12 pour l'instant (pas de fonctionnalité d'import sur la nouvelle interface).
Je vais essayer de remonter un questionnaire sur v12.0.8 et de voir si je reproduis.
On peut éventuellement fermer ce ticket ?
