### ISSUE TITLE
ExoBundle Affichage cassé

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#4639]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12rc10

L'affichage du questionnaire tant modification qu'en exécution est complètement foireux.

**Comment by LaurentGruber** [comment]
tu peux en dire plus, ou faire une capture ...

**Comment by clarophil** [comment]
Sur demo12, créer une question 
![image](https://user-images.githubusercontent.com/895878/45080858-1e347d80-b0f6-11e8-82b8-f8f198595793.png)

**Comment by LaurentGruber** [comment]
trouver, il y a un 404 sur https://demo12.claroline.com//themes/claroline%20ruby/claroline-distribution-plugin-exo-quiz-resource.css
je regarde, j'ai du foiré un truc à la maj ...

**Comment by clarophil** [comment]
c'est la même chose sur hevincib
