### ISSUE TITLE
IMPOSSIBILITE DE CREER UN EA

### ISSUE THREAD

**Issue by nicvallet** [claroline/Distribution#4651]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | Claroline egreta 11.3.12.

Je ne peux plus créer d'espace d'activité, depuis cette dernière version de Claroline 
Message en rouge : ECHEC DE LA CREATION
![echec creation ea](https://user-images.githubusercontent.com/36445768/45148508-b0588680-b1c7-11e8-9b61-f062d19aa2bd.jpg)

**Comment by LaurentGruber** [comment]
que dis le log d'erreur ?

**Comment by nicvallet** [comment]
comment accéder au log d'erreur ?
