### ISSUE TITLE
impossible de retrouver l'aspect initial des widgets dans un EA déjà créé

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#4662]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.0

Je souhaite reproduire un EA conçu sur une V11.3.12
![image](https://user-images.githubusercontent.com/32478422/45202470-34734280-b28a-11e8-9057-4499d08d18ea.png)
Je restructure l'accueil avec une V12.0.0, je déplace les widgets dans les colonnes pré-déterminées puis je supprime les widgets qui restent présents.
J'enregistre et j'obtiens ça :
![image](https://user-images.githubusercontent.com/32478422/45202821-40abcf80-b28b-11e8-9f95-5658a842f40b.png)
Impossible de supprimer l'ancienne organisation ou de restructurer l'EA, j'ai même perdu des éléments.
Est-ce un problème de méthode ? Doit-on supprimer les anciens widgets après les avoir déposés dans la nouvelle section?
Merci

**Comment by jbbrosset** [comment]
On rencontre le même soucis.
En fait tu peux supprimer des widgets, les déplacer ... ça marche bien, mais tu ne peux pas supprimer des sections.

Cependant:
- Tu peux déplacer tes widgets dans les nouvelles sections que tu as créées 
- Ensuite du efface le nom de la section précédemment vidée
![image](https://user-images.githubusercontent.com/35995165/45212795-1c092500-b296-11e8-881d-ba8c40478b2b.png)
- Tu enregistres

Ca te fait un petit espace vide à l'affichage mais en attendant mieux ...

![image](https://user-images.githubusercontent.com/35995165/45212835-3fcc6b00-b296-11e8-8041-d84ff05792aa.png)

**Comment by jbbrosset** [comment]
La suppression des sections semble fonctionner sur la v12.0.3 

MAIS .... il faut supprimer une seule section à la fois, sinon les modif ne sont pas prises en compte au moment de l'enregistrement.
