### ISSUE TITLE
Gestionnaire d'utilisateur - Impossible d'attribuer un rôle

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4666]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.0-rc10

Problème spécifique à notre gestion des utilisateurs.

“Se connecter en tant que” un utilisateur possédant le rôle “gestionnaire de MFR” pour tester sa gestion des utilisateurs.
C’est un rôle spécifique qui peut gérer et créer des utilisateurs au sein de son organisation. (l’utilisateur exemple est laurent boy)
Lorsque je lance la gestion des utilisateurs avec le bouton administration, j’ai un message d’erreur. 
(403 Forbidden)

Il se trouve que je voudrais vérifier si il peut bien créer des comptes user avec le rôle “alternant”.

Cette fonctionnalité conditionne la mise en place de ntre plateforme à grande échelle pour cette rentrée  et ne fonctionne pas actuellement sur notre V11.

**Comment by LaurentGruber** [comment]
il faut utiliser le rôle gestionnaire d'organisation (si c'est celui-là que vous avez renommez ça devrait être ok). C'est ce rôle là qui donne les droits de créer des user dans une orga, il faut également être mis gestionnaire d'une organisation spécifique.
