### ISSUE TITLE
Modèles non fonctionnels

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4667]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.0-rc10

Quand on crée un espace à partir d'un modèle, l'espace créé est vide de tout contenu.
Aucun élément du modèle n'est repris.

**Comment by LaurentGruber** [comment]
lié au point 3 de https://github.com/claroline/Distribution/issues/4698 ?
à retester ...
