### ISSUE TITLE
Barre de Menu horizontale

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4684]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.3

![image](https://user-images.githubusercontent.com/35995165/45297305-44e32180-b505-11e8-88c3-e2a14de67358.png)

- [x] Disparition du bouton "Ressources" alors qu'il est bien coché comme visible.
- [x] Doublon entre l'option "Messagerie" (cochée visible non modifiable mais qui ne s'affiche pas) et l'option "messaging" (paramétrable visible/invisible mais qui marche)

![image](https://user-images.githubusercontent.com/35995165/45297474-ca66d180-b505-11e8-81a3-a08803278506.png)

- [x] Impossible de revenir au Bureau depuis une page de configuration/paramètre plateforme: le collapsible avec les derniers espaces fonctionne de telle façon qu'on est obligé de passer par "Accueil" pour revenir à "Bureau"

**Comment by LaurentGruber** [comment]
la messagerie va être gérer comme les notifications, cela va devenir un centre de contact de l'utilisateurs... L'icone de notification change et la cloche est remplacé par https://fontawesome.com/icons/mail-bulk?style=solid 
Voir à partir de la 12.0.6

Chaque outil va avoir un seul emplacement possible et la configuration pour l'admin va être lié au rôle (tu pourras donc activé un outil pour un rôle mais pas pour un autre) ... on doit encore le faire ...
