### ISSUE TITLE
Widget Liste de ressources

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4686]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.3

![image](https://user-images.githubusercontent.com/35995165/45298549-2121da80-b509-11e8-8e60-afc584a9ae30.png)

- [x] Quel est le rapport entre "Nombre de résultats à afficher" et "Résultats par page" ?
- [x] Une fois validé de toute façon aucun des deux champs n'est pris en compte dans l'affichage des résultats (ici 5 résultats demandés, 41 affichés) - A priori c'est pareil sur tous les widgets listes ( bug déjà remonté)
- [x] Pagination non foncitonnelles : ici 41 résultats - Page 1 sur 41 ... en fait il n'y a qu'une page (j'ai testé, si j'affiche une liste avec X résultats, il y a X pages)
![image](https://user-images.githubusercontent.com/35995165/45298919-3d724700-b50a-11e8-970a-aa0df4f04168.png)

- [x] Toujours pas de possibilité de choisir d'afficher les ressources d'un seul dossier de l'EA, fonction qui existait dans la V11 ...

**Comment by Elorfin** [comment]
> Quel est le rapport entre "Nombre de résultats à afficher" et "Résultats par page"

Le nombre de résultats à afficher sera le nombre maximum de résultats de votre liste par exemple pour limiter la récupération aux 50 premiers résultats. Le Résultats par page permet de choisir combien de résultats seront affichées à la fois. Avec vos 50 résultats vous pouvez faire 5 pages de 10, 3 pages de 20, etc.

> Une fois validé de toute façon aucun des deux champs n'est pris en compte dans l'affichage des résultats (ici 5 résultats demandés, 41 affichés) - A priori c'est pareil sur tous les widgets listes ( bug déjà remonté)

Pour "Nombre de résultats à afficher", c'est normal la fonctionnalité n'est pas encore implémentée. J'ai masqué le champ en attendant qu'elle le soit pour éviter toute confusion.

Pour la pagination, OK, il faut qu'on teste.

> Toujours pas de possibilité de choisir d'afficher les ressources d'un seul dossier de l'EA, fonction qui existait dans la V11 ...

En effet, il manque le filtre sur le parent dans la liste. En attendant, il est toujours possible d'ouvrir un dossier directement avec le widget Ressource.

**Comment by Elorfin** [comment]
Il est maintenant possible d'ajouter un filtre "Parent" et de choisir le dossier voulu.
