### ISSUE TITLE
Resource restrictions are not shown to users

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#4695]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.x

It seems the restrictions page with all the alerts are not displayed when you are a standard user (aka can read without `administrate` right or being the creator).

Check if the bug is still here. You can also check that all restrictions are correctly executes.

- [x] Restrict by start date
- [x] Restrict by end date
- [x] Restrict by code
- [x] Restrict by IP
- [x] hide

**Comment by Pauooo** [comment]
Restriction by IP works just with IPv4
