### ISSUE TITLE
Paramètres du portail de ressources 

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4699]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.0.3

![image](https://user-images.githubusercontent.com/35995165/45308233-4884a180-b521-11e8-88bf-3bb5aebb2c87.png)

.... C'est pas clair.

**Comment by Elorfin** [comment]
La fonctionnalité n'existe plus.
