### ISSUE TITLE
[Forms] Consider using the built-in bootstrap theme

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#470]
We currently use zenstruck as a basis for bootstrap form layouts, but since the 2.6 version, Symfony has built-in support for it: 

http://symfony.com/blog/new-in-symfony-2-6-bootstrap-form-theme

It might be a good idea to make the replacement and --possibly -- get rid of the zenstruck dependency.

**NOTE**: that bundle also provides an integration of select2, which isn't handled by the Symfony theme.

**Comment by LaurentGruber** [comment]
on remplace plus par des composants react
