### ISSUE TITLE
Tables pas responsives dans widgets/ressources texte

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4702]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.3

![image](https://user-images.githubusercontent.com/35995165/45347485-811d8d00-b5ac-11e8-8528-68441f5305e2.png)

Ça fout en l'air la présentation des widgets dans l'accueil

**Comment by LaurentGruber** [comment]
Au mieux on pourra empêcher la table de sortir du cadre.
Mais on n'a pas la main sur le code de la table en elle même, elle est soit créé dans le html, soit généré par tinymce or c'est la que devrait être géré le responsive...
Je regarde ce qu'il y a moyen de faire ...

**Comment by jbbrosset** [comment]
déjà si elle ne dépasse pas le cadre ça sera plus cohérent.

Les tables générés par TinyMCE ne sont pas responsive de base de toute façon, je suis obligé de tweek à la main dans le code (moi ça me dérange pas, mais les users ne savent pas faire ça)
