### ISSUE TITLE
Impossible d'ajouter une image dans un widget Texte

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#4733]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.5

Modifier le widget
+ Ressource
Sélectionner une image
Sauver

L'image n'apparaît pas ni en édition ni après sauvegarde.
Dans le code html on voit 
<p>Image</p>
<p><span id="resource-picker-9133de29-f7eb-496a-b363-065c0c62d9a8" style="display: none;">Ressource</span></p>

**Comment by LaurentGruber** [comment]
tu as le même problème quand tu crée un nouveau widget texte ?

**Comment by clarophil** [comment]
Avec un nouveau widget 
- le lien vers le pdf apparaît et fonctionne
- l'image apparaît en édition mais disparaît après la sauvegarde
[https://demo12.claroline.com/workspaces/3/open/tool/home#/tab/eddd03f0-1c1c-47aa-9d79-4e729f0877e8](url)
