### ISSUE TITLE
Ouverture des ressources open/files/

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#4742]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.6

Les liens avec open/file engendre une erreur 500
[](https://claco.vinci.be/resource/open/file/16128 )

**Comment by LaurentGruber** [comment]
remapper ancienne url sur le nouveau controller

**Comment by LaurentGruber** [comment]
on peut avoir un lien précis pour pouvoir tester
