### ISSUE TITLE
Utilisateurs de l'espace : recherche dans la liste échoue

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#4745]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      |  12.0.6

Dans un espace
Utilisateurs
Recherche sur le nom ou le code ... donne Echec du chargement

**Comment by LaurentGruber** [comment]
Voici le message d'erreur : 
An exception occurred while executing \u0027SELECT COUNT(*) as count FROM (SELECT DISTINCT c0_.id , c0_.first_name , c0_.last_name , c0_.username , c0_.password , c0_.locale , c0_.salt , c0_.phone , c0_.mail , c0_.administrative_code , c0_.creation_date , c0_.last_login , c0_.initialization_date , c0_.reset_password , c0_.hash_time , c0_.picture , c0_.description , c0_.hasAcceptedTerms , c0_.is_enabled , c0_.is_removed , c0_.is_mail_notified , c0_.is_mail_validated , c0_.hide_mail_warning , c0_.last_uri , c0_.public_url , c0_.has_tuned_public_url , c0_.expiration_date , c0_.authentication , c0_.email_validation_hash , c0_.uuid , c0_.workspace_id , c0_.options_id FROM claro_user c0_ LEFT JOIN claro_user_role c2_ ON c0_.id = c2_.user_id LEFT JOIN claro_role c1_ ON c1_.id = c2_.role_id LEFT JOIN claro_workspace c3_ ON c1_.workspace_id = c3_.id WHERE UPPER(c0_.first_name) LIKE ? AND c3_.uuid IN (\u002765CEC1EA-6D43-4A7B-8A06-576D7BCACF40\u0027) AND c0_.is_removed = 0 UNION SELECT DISTINCT c0_.id , c0_.first_name , c0_.last_name , c0_.username , c0_.password , c0_.locale , c0_.salt , c0_.phone , c0_.mail , c0_.administrative_code , c0_.creation_date , c0_.last_login , c0_.initialization_date , c0_.reset_password , c0_.hash_time , c0_.picture , c0_.description , c0_.hasAcceptedTerms , c0_.is_enabled , c0_.is_removed , c0_.is_mail_notified , c0_.is_mail_validated , c0_.hide_mail_warning , c0_.last_uri , c0_.public_url , c0_.has_tuned_public_url , c0_.expiration_date , c0_.authentication , c0_.email_validation_hash , c0_.uuid , c0_.workspace_id , c0_.options_id FROM claro_user c0_ LEFT JOIN claro_user_group c2_ ON c0_.id = c2_.user_id LEFT JOIN claro_group c1_ ON c1_.id = c2_.group_id LEFT JOIN claro_group_role c4_ ON c1_.id = c4_.group_id LEFT JOIN claro_role c3_ ON c3_.id = c4_.role_id LEFT JOIN claro_workspace c5_ ON c3_.workspace_id = c5_.id WHERE UPPER(c0_.first_name) LIKE ? AND c5_.uuid IN (\u002765CEC1EA-6D43-4A7B-8A06-576D7BCACF40\u0027) AND c0_.is_removed = 0) AS wathever\u0027:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \u0027? AND c3_.uuid IN (\u002765CEC1EA-6D43-4A7B-8A06-576D7BCACF40\u0027) AND c0_.is_removed = \u0027 at line 1

Il semble qu'il y a un échapement en trop sur les uuid
