### ISSUE TITLE
Agenda - fermer la modal d'édition impossible

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#4749]
impossible de fermer la modal d'édition d'un event dans l'agenda d'un WS ...

Log console quand je clique sur la croix de la modal :   Error: modalId is required

**Comment by kitan1982** [comment]
Modal call : https://github.com/claroline/Distribution/blob/12.x/plugin/agenda/Resources/modules/components/agenda.jsx#L223

Modal component :
https://github.com/claroline/Distribution/blob/12.x/plugin/agenda/Resources/modules/components/modal/components/event.jsx
