### ISSUE TITLE
workspace thumbnail

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#4764]
mettre 2 miniatures à un espace fait planter les listes d'espaces contenant cet espace ...

**Comment by LaurentGruber** [comment]
A tester aussi sur les ressources ...

**Comment by kitan1982** [comment]
J'ai pas réussi à reproduire le bug.
Je ne vois pas comment on peut mettre 2 miniatures à un espace.

**Comment by LaurentGruber** [comment]
@clarophil tu as fais comment pour mettre 2 miniatures à un espace, on n'arrive pas à reproduire ...

**Comment by clarophil** [comment]
On en a mis une puis sauver la page puis une autre et sauver



Envoyé depuis mon mobile.


-------- Message d'origine --------
De : Gruber Laurent <notifications@github.com>
Date : 18/09/2018 08:56 (GMT+01:00)
À : claroline/Distribution <Distribution@noreply.github.com>
Cc : Philippe DEKIMPE <philippe.dekimpe@ecam.be>, Mention <mention@noreply.github.com>
Objet : Re: [claroline/Distribution] workspace thumbnail (#4764)


@clarophil<https://github.com/clarophil> tu as fais comment pour mettre 2 miniatures à un espace, on n'arrive pas à reproduire ...

**Comment by LaurentGruber** [comment]
j'ai essayé ça et il a remplacé la première par la deuxième (sur demo12)
