### ISSUE TITLE
Crash Parcours si suppression étape

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4780]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.6

Si je copy/paste une étape => no problem
Je supprime une étape => Crash plateforme, plus rien ne répond, obligation de refresh

**Comment by LaurentGruber** [comment]
reproduit ici : https://demo12.claroline.com/resources/show/innova_path/19fcbded-0c52-4937-87b0-c6bbc4f7497d#/edit/0002baf0-90c3-4937-b3db-4356c85950ad

**Comment by Elorfin** [comment]
Oui c'est juste qu'il ne redirige pas à la suppression et donc il essaye d'afficher une step qui n'existe plus.

**Comment by jbbrosset** [comment]
Fixed in 12.0.11 non ?
Je n'ai pas eu le problème quand j'ai retesté.
