### ISSUE TITLE
[Collecticiel]Bug when I display any "Collecticiel"

### ISSUE THREAD

**Issue by ericvincenterv** [claroline/Distribution#480]
It is not possible to display any Collecticiel Resource.

**Comment by ericvincenterv** [comment]
@LaurentGruber : it's a bug fix, I think the right milestone is 16.05.1. It's not correct ?

**Comment by LaurentGruber** [comment]
@ericvincenterv l'issue est fermée donc je suppose que ça a été intégré dans la version de hier non ? sinon il faut réouvrir et mettre 16.05.1

**Comment by ericvincenterv** [comment]
@LaurentGruber : l'issue a été créée peut de temps après la version d'hier :-(
