### ISSUE TITLE
La miniature de l'espace ne s'efface pas

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#4804]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.10

Ouvrir l'espace
Configurer
Paramètre d'affichage
Ajouter une miniature
Sauver

Configurer
Paramètre d'affichage
La miniature est toujours là !
On peut en ajouter une autre
Sauvegarder indique un échec

Mais si on recharge la page après la suppression alors tout fonctionne parfaitement, donc c'est la modale qui ne se recharge pas correctement après la sauvegarde.

**Comment by ngodfraind** [comment]
C'est pas que pour la miniature. Aucune props de la modale n'est raffraichie.

**Comment by clarophil** [comment]
Je viens de tester dans la v 12.0.19 et le bug est toujours présent

**Comment by clarophil** [comment]
On a remarqué le même comportement dans l'import csv dans l'administration, il garde le fichier.  Il faut forcer le rechargement de la page pour pouvoir mettre un autre fichier.

**Comment by clarophil** [comment]
Ce problème n'est pas résolu

**Comment by Elorfin** [comment]
Corrigé en 12.5.
