### ISSUE TITLE
Navigation dans le gestionnaire de ressources

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#4805]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.0.11

Dans le gestionnaire de ressources lors de la navigation dans les dossiers si on clique sur la flèche retour du navigateur, on retourne à la racine

-> ajouter un bouton précédent dans la modale

Idem sur la fil d'ariane, si on clique sur un dossier dans le fil, on retombe à la racine

-> prendre en compte le dossier cliqué dans le fil dans l'affichage de la modale
-

**Comment by WalterMFR** [comment]
Bonjour,

Nous rencontrons aussi ce problème.
Lorsque l'on utiliser le fil d'Ariane dans le navigateur de ressources, on est redirigé vers la racine des espaces auxquels on est inscrit.
