### ISSUE TITLE
Le graphique de l'outil Suivi d'un espace est vide 

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#4808]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.10

Le graphique de l'outil Suivi d'un espace est vide 

![image](https://user-images.githubusercontent.com/895878/45864525-8633c680-bd7a-11e8-9fef-522f38ca0d10.png)

**Comment by ngodfraind** [comment]
Reproduit sur l'estp.

**Comment by clarophil** [comment]
- [ ] dans l'onglet Suivi des utilisateurs, le pager est absent, on ne peut donc voir que les 20 lignes

**Comment by ngodfraind** [comment]
Reproduit (tjrs). Par contre j'ai le pager.

**Comment by clarophil** [comment]
@ngodfraind  C'est dans l'onglet Suivi des utilisateurs 
Pager absent dans la 12.3.1

**Comment by Elorfin** [comment]
Corrigé dans la 12.5
