### ISSUE TITLE
Effacement des messages reçus en échec

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#4809]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Dans Message recus 
Cocher quelques messages
Cliquer sur la poubelle

En tant que Admin ça marche
Pour les autres échecs

![image](https://user-images.githubusercontent.com/895878/45864816-98623480-bd7b-11e8-92be-ec73bb5a3919.png)

**Comment by ngodfraind** [comment]
Pas pu reproduire. Tjrs d'actualité ?

(en local, j'ai pris un compte user avec l'impersonation et ça s'est bien supprimé - même manip que sur le screen).

**Comment by clarophil** [comment]
ok ça marche en 12.0.16
