### ISSUE TITLE
PDF téléchargement par défaut

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#4811]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.0.10

Le lecteur PDF n'est pas très confortable mais je comprends que dans certains cas il peut être intéressant

Serait-il possible de modifier le comportement par défaut des PDF dans un espace, soit téléchargement, soit affichage en ligne ?

**Comment by jbbrosset** [comment]
En attendant tu peux mettre manuellement un argument dans le code de ton lien : 
'<a href="/file/fichier.pdf" download>' au lieu d'un simple '<a href="/fil/fichier.pdf">' télécharge le fichier au moment du clic.

De plus en plus souvent, j'associe le lecteur PDF à un bouton dans une zone de texte proche qui permet de télécharger directement.

**Comment by clarophil** [comment]
C'est dans le gestionnaire de ressources que cela pose problème
