### ISSUE TITLE
Widget Ressource : Comportement des dossiers

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#4813]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.10

Le comportement des dossiers dans le widget Ressource est très différent de l'outil Ressource
Je suis gestionnaire (pas admin)
Si j'ouvre un dossier à widget 

- [x] Je coche un fichier -> la barre de bouton ne s'affiche pas

- [ ] Je vois des ressources Step que je ne vois pas dans le gestionnaire de ressource 

- [ ] J'ajoute un fichier dans un sous dossier d'un dossier, il arrive dans le dossier parent

**Comment by LaurentGruber** [comment]
Quand je rentre dans un dossier via le widget liste des ressources, je coche des éléments et les actions n'apparaissent pas ...

**Comment by clarophil** [comment]
- [ ] si on clique sur un dossier dans le widget, Ressource dans le fil d'ariane devient actif et si on le clique Erreur 404
