### ISSUE TITLE
Widget annonce sur le bureau :

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#4816]
- on ne voit pas de quel WS vient l'annonce, ni la date
- à gauche une énorme case grise sans intérêt

**Comment by ngodfraind** [comment]
Ça été changé non ? J'ai testé en local et tout est propre.

**Comment by clarophil** [comment]
Le mode tableau est bien mais il ne permet pas de voir grand chose du contenu.
C'est le mode liste pourrait être améliorer 
![image](https://user-images.githubusercontent.com/895878/46213690-8f540300-c339-11e8-87e0-23a30eb83fef.png)

**Comment by ngodfraind** [comment]
Vu et reproduit.

**Comment by clarophil** [comment]
Comment enlever la zone avec l'icone tout à fait inutile puisqu'il s'agit d'un widget annonce ?
![image](https://user-images.githubusercontent.com/895878/48257392-b1e63b00-e412-11e8-9219-192eae512d67.png)
