### ISSUE TITLE
Page d'accueil plateforme ajout fichier impossible

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#4817]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.11

Edition de la page d'accueil de la plateforme
Cliquer + Ressource ou Fichier
la roue de chargement tourne indéfiniment

**Comment by clarophil** [comment]
Ce problème n'est pas résolu dans la 1.12.28

**Comment by LaurentGruber** [comment]
si, tu dois aller dans les paramètres généraux > accueil et choisir new
Par contre il faudra refaire les pages d'accueil (d'où le faite qu'il ne le fait pas tous seul)

**Comment by clarophil** [comment]
Parfait, c'est nettement mieux.
