### ISSUE TITLE
Equipe nombre d'inscrits

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#4836]
| Q             | A
| ------------- | ---
| Bug report?   | régression
| Version?      | 12.0.13

Avant la v12, on avait une colonne avec le nombre d'inscrits mais cette colonne a disparu dans la v12
Nous avons des espaces avec plusieurs dizaines d'équipes, l'étudiant doit ouvrir la liste de membre de chaque équipe pour voir où il reste de la place alors qu'avant il suffisait de regarder la colonne du nombre d'inscrits.

suggestion : remettre la colonne nombre d'inscrits

**Comment by clarophil** [comment]
autre suggestion : ajouter dans le tableau qui liste les équipes un menu inscription aux équipes qui ont encore de la place

**Comment by clarophil** [comment]
Le tri sur la nouvelle colonne Nombre d'inscrit génère un échec de chargement.

**Comment by clarophil** [comment]
Le tri du nombre d'inscrits continue à avoir un comportement erratique.

**Comment by WalterMFR** [comment]
Bonjour, 

Je confirme rencontrer des problèmes d'affichage dans la liste des équipes.
En effet, j'ai une équipe autorisant 3 personnes maximum remplie avec 2 utilisateurs mais la liste affiche 3/3 au lieu 2/3.

**Comment by ngodfraind** [comment]
Y a moyen de m'envoyer un lien vers un listing qui ne fonctionne pas ?
Je n'arrive pas à reproduire le problème.

**Comment by clarophil** [comment]
[https://claco.vinci.be/workspaces/105/open/tool/claroline_team_tool#/teams](url)
Si je clique sur Utilisateurs inscrits la série 8 disparaît et le tri n'est pas bon
Si je clique sur la flèche vers le haut ou le bas, les tris sont corrects

Si je clique plusieurs fois sur Nombre max d'utilisateurs, le tri est parfois bon parfois pas
Si je clique sur la flèche vers le haut ou le bas, les tris sont tous mauvais
