### ISSUE TITLE
V12 - Contenu manquant

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4855]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.6

Dans le bureau, tous les contenus ne sont pas encore repris pour l'utilisateur Marie Bluteau : 
https://mfrb.claroline.com/desktop/tool/open/home#/tab/bba74646-bca2-11e8-8607-0cc47a960f96

alors que dans l’original: https://w-alter.mfr.asso.fr/desktop/tool/open/home#/tab/1756

**Comment by jbbrosset** [comment]
J'ai un autre cas :  
après https://mfrb.claroline.com/desktop/tool/open/home#/tab/0c8d471f-c5b7-11e8-a47b-0cc47a960f96

avant https://w-alter.mfr.asso.fr/desktop/tool/open/home#/tab/457

**Comment by jbbrosset** [comment]
![image](https://user-images.githubusercontent.com/35995165/46370483-fcdb9880-c685-11e8-8884-1a7df3364727.png)

**Comment by jbbrosset** [comment]
Plus Embêtant : 
Des packages Scorm ont carément disparu des ressources, ceux restant ne sont pas accessibles.
sur la V12 (dossier "ressources de biologie"): https://mfrb.claroline.com/workspaces/443/open/tool/resource_manager#/
sur la V11: https://w-alter.mfr.asso.fr/workspaces/443/open/tool/resource_manager#resources/3445 

![image](https://user-images.githubusercontent.com/35995165/46370738-b9cdf500-c686-11e8-9535-e8c7de7df37b.png)
![image](https://user-images.githubusercontent.com/35995165/46370746-c2263000-c686-11e8-8fa2-85e2d0561236.png)
![image](https://user-images.githubusercontent.com/35995165/46370755-cb170180-c686-11e8-9758-9f4f4b005c09.png)

**Comment by lgeschwine** [comment]
même problème de Scorm sur la 12.1.14 pour des scorm 2004
pour des scorm 1.2, j'ai un affichage différent  mais toujours un bug :
![image](https://user-images.githubusercontent.com/32478422/48614322-651cda00-e9a7-11e8-9a06-8655ca566a4e.png)
