### ISSUE TITLE
Widget - liste des ressources

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#4861]
Le widget « Liste de ressources » pose problème. Il semble en fait n’afficher que les ressources du type demandé qui se situent au niveau du répertoire racine de l’espace d’activité et pas celles de ce type figurant dans des répertoires de niveau inférieur. J’ai testé cela avec les parcours et avec les dossiers.

**Comment by ngodfraind** [comment]
Je ferai quand #4856 sera mergée pour éviter les conflits.

**Comment by ngodfraind** [comment]
Ou plutot je repars de #4856
