### ISSUE TITLE
Messagerie nombre non

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#4867]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.16

- [x] Le nombre de messages non lus dans la zone de notification n'est pas correct, il comprend le nombre de messages envoyés

- [x] quand on efface des messages envoyés, l'affichage n'est pas mis à jour mais la suppression a bien eu lieu
- [x] tri sur lu ne fonctionne pas

**Comment by ngodfraind** [comment]
Pas pu reproduire le dernier, peut être une erreur de js.
