### ISSUE TITLE
Annonces

### ISSUE THREAD

**Issue by AnneZarka** [claroline/Distribution#4869]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Bonjour,
Sur la V11.3.12
Lorsque je crée une ressource Annonces, je peux créer des annonces mais impossible ensuite de les modifier ou supprimer (même par l'auteur de l'annonce). Quand je clique sur "sauvegarder", il ne se passe rien.

Sur la V12, lorsque je modifie une annonce, la plateforme prend les modifications mais le message d'échec apparaît tout de même.

**Comment by flow39** [comment]
testé sur 12.0.8 :
Après la première connexion à la plateforme, je crée une ressource annonce et je publie une annonce à l'intérieur. l'annonce publiée à "inconnu" pour auteur :
![image](https://user-images.githubusercontent.com/7293233/46281414-e1319e80-c56e-11e8-9686-988822329ec3.png)
Lorsque j'édite, j'ai une erreur
![image](https://user-images.githubusercontent.com/7293233/46281448-feff0380-c56e-11e8-925b-5b5cf6bac965.png)
Si je sors de la ressource et que je rentre dedans pour éditer à nouveau l'annonce, ça fonctionne.

**Comment by alainertveldt** [comment]
testé sur 12.0.8
Le widget liste d'annonces ne fonctionne pas sur le bureau ... 
![image](https://user-images.githubusercontent.com/31481850/46302174-b5330f00-c5a8-11e8-99b1-65f317dd0c43.png)

mais bien dans les espaces d'activités
![image](https://user-images.githubusercontent.com/31481850/46302209-ca0fa280-c5a8-11e8-8fa1-a132a716d6ef.png)
