### ISSUE TITLE
Cours : bouton "Créer un chapitre" accessible sans les permissions d'édition

### ISSUE THREAD

**Issue by rudzboy** [claroline/Distribution#4880]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.18

Dans un cours :

Le bouton "Créer un chapitre" est accessible alors que l'utilisateur n'a pas les droits d'édition sur cette ressource.
Cependant, l'opération est effectivement refusée par l'API au final mais ce bouton ne devrait pas s'afficher.

![2018-10-01_14h24_22](https://user-images.githubusercontent.com/8886118/46288452-febe3280-c585-11e8-8454-8149f0c8bffc.png)

**Comment by LaurentGruber** [comment]
https://github.com/claroline/Distribution/pull/5472
