### ISSUE TITLE
Cours : souci de responsive design

### ISSUE THREAD

**Issue by rudzboy** [claroline/Distribution#4881]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.18

Souci d'affichage d'un cours sur une largeur d'écran < 991px

OK (> 991px)
![2018-10-01_14h32_08](https://user-images.githubusercontent.com/8886118/46288665-c834e780-c586-11e8-9ab2-5cc8ca871879.png)

KO (< 991px)
![2018-10-01_14h33_09](https://user-images.githubusercontent.com/8886118/46288707-ed295a80-c586-11e8-8afe-2a2c57d0dbee.png)

**Comment by Elorfin** [comment]
Il s'agit en réalité du fonctionnement normal. Il n'est pas possible d'Epingler le sommaire sur les petits écrans car la colonne réservée au contenu serait alors trop petite. Il suffit de fermer le sommaire.

A noter que c'est le même mode de fonctionnement dans le Gestionnaire de ressources et les Parcours.
