### ISSUE TITLE
Widget liste de tâches

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#4884]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.0.8

le widget liste des tâches renvoie des tâches d'EA dont on n'est pas membres...
![image](https://user-images.githubusercontent.com/31481850/46302577-ab5ddb80-c5a9-11e8-8ba4-6f87ed1a326d.png)
je ne suis membre d'aucun EA sciences
l'erreur vient du widget annonces

**Comment by jbbrosset** [comment]
On rencontre le même problème sur la 12.0.18 sauf qu'aucune tâche n'est affichée.
Idem sur le widget évènement
