### ISSUE TITLE
Icone de la ressource cliquable

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#4888]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.0.19

Très souvent dans les OS un clic sur l'icône ouvre la ressource

Suggestion : rendre l'icône de la ressource cliquable
![image](https://user-images.githubusercontent.com/895878/46334672-3b8d3680-c625-11e8-90a6-7994cef0aa47.png)

**Comment by rudzboy** [comment]
Instinctivement on a tendance à vouloir cliquer sur l'icône, je confirme ce besoin ;)
