### ISSUE TITLE
Ressource : impossible de déplacer une ressource à la racine d'un espace

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#4889]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.0.19

Pour déplacer une ressource il faut sélectionner un dossier 
Problème : il n'est pas possible de sélectionner un dossier racine d'un espace dans le picker
Suggestion : voir dans le picker les dossiers racines comme c'est déjà le cas dans l'outil Ressource du bureau

**Comment by Elorfin** [comment]
Il est maintenant possible de remonter à la racine pour voir tous les dossiers d'espace (grâce au fil d'Ariane) dans le picker.
