### ISSUE TITLE
Restriction par rôle de l'affichage des onglets sur l'accueil et les bureau d'EA non fonctionnel

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#4904]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.8

Il n'est plus possible de restreindre l'affichage des onglets bureau d'accueil / accueil EA à un rôle :

![image](https://user-images.githubusercontent.com/7293233/46350898-4613f400-c656-11e8-9037-aebd26f36aa9.png)
Quand je veux activer une restriction, je coche "restreindre par rôle" puis le rôle souhaité. Après avoir enregistré, la coche "restreindre par rôle" disparait.

Le problème est similaire dans les espaces d'activités, impossible de restreindre l'affichage d'un onglet d'accueil à un rôle..

**Comment by LaurentGruber** [comment]
duplicate of https://github.com/claroline/Distribution/issues/4898
