### ISSUE TITLE
Walkthrough : Pack de bugs / comportements

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4908]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.18

Bon, c'est le premier ticket sur les walkthrough alors quand-même : 
Un gros bravo ! C'est super classe ! 👍 

Sur les walkthrough j'ai noté quelques comportements a revoir : 
- [ ] Chargement long sur la modal de choix du type de widget. Rien ne se passe si on clique sur "Suivant" pendant le chargement, ça limite la casse. (à la limite c'est pas un bug, plutôt une remarque)
![image](https://user-images.githubusercontent.com/35995165/46369253-b3d61500-c682-11e8-9998-96cc09423058.png)

- [ ] Parfois une étape est sautée. J'ai essayé de trouver une raison mais je ne reproduit pas à tous les coups...
![image](https://user-images.githubusercontent.com/35995165/46369358-07e0f980-c683-11e8-9cc8-c333b3bcafeb.png)

- [ ] Le plus gênant : le premier walkthrough de widget marche bien sur le premier widget créé dans un onglet. Que ce soit contenu ressource ou liste. Par contre si on relance un walkthrough derrière le tooltip se met derrière la zone en surbrillance et on est bloqué. CE qui est très bloquant c'est que même un F5 ne résout pas le problème, il faut sortir de l'édition en modifiant L’URL de la page ou cliquer sur le bouton accueil. (Re-bonjour z-index ?)
![image](https://user-images.githubusercontent.com/35995165/46369794-3e6b4400-c684-11e8-9179-94505c297f76.png)

**Comment by jbbrosset** [comment]
Sur la v12.0.21:

- [ ] Quand je lance le walkthrough de la topbar, la première étape n'a pas de traduction 
![image](https://user-images.githubusercontent.com/35995165/46618473-e454fd80-cb1f-11e8-9901-3bc7c40eebec.png)

**Comment by Elorfin** [comment]
Le système a complètement été remplacé donc je clôture.
