### ISSUE TITLE
Position des onglets sur le bureau

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#4912]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.0.19

j'essaie depuis que nous sommes passés en version 12 de changer l'ordre des onglets sur le bureau... mais impossible de mettre autre chose que les espaces d'activités en N° 1 même s'il enregistre un autre onglet à la place de n° 1 .. on dirait que ce n'est pas possible.... rrrhhh
![image](https://user-images.githubusercontent.com/31481850/46389053-25888000-c6d0-11e8-98e6-a6a18bb02c2f.png)

l'onglet mes espaces revient systématiquement à la place 1

**Comment by jbbrosset** [comment]
Nous avons le même problème sur la 12.0.21, l'ordre des onglets n'est pas gardé à la sauvegarde.

**Comment by jbbrosset** [comment]
Pour préciser : 
- Je fais la modif de position sur les onglet en sauvegardant à chaque modif.
- Je valide, je quitte. A ce moment là tout va bien et s'affiche selon les modifs faites. Le bandeau d'enregistrement est bien vert.
- Je reload, et pouf l'ordre des onglets est revenu comme il était à l'origine.

**Comment by jbbrosset** [comment]
Update : il est 11h41, les onglets ont décidés de s'afficher dans l'ordre ....

**Comment by jbbrosset** [comment]
Update : 13h47 , les onglets ont à nouveau changés de position. Je pense qu'ils ont une volonté propre.... Nous tentons de communiquer avec eux....

**Comment by jbbrosset** [comment]
Update 09/10/18 14h12 : A chaque refresh/reload les onglets changent de place, nous tentons de trouver le code caché derrière ce fonctionnement. 
Nous penchons pour des coordonnées GPS.
