### ISSUE TITLE
Fonctionnalités qui ont disparu de la version 12

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#4913]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.0.19

Voici une liste non exhaustive de fonctionnalités qui ont disparu de la version 12 et qui étaient bien présentes dans la version 12:

**Bureau**: 
l'agenda du bureau qui reprend les agendas de tous les EA
**Messagerie**:
ce serait bien d'avoir les messages du plus récent au moins récent par défaut
plus moyen de faire une recherche sur un utilisateur en appuyant sur la tête dans nouveau message
plus moyen (ou pas trouvé) d'écrire à un EA (bon là il y a l'annonce) ou à un groupe..
**Annonces**
des soucis lors de l'envoi de mail

**Ressources**:
plus de ressources type Résultats (et plus de widget résultats non plus)
plus de ressources types sondages

bon je m'arrête là pour ce matin... je compléterai dès que je verrai d'autres soucis

**Comment by LaurentGruber** [comment]
doublon, il y a déjà des tickets pour tous ça
