### ISSUE TITLE
Ressources Picker 

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4938]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.21

- [ ] Le picker auquel on accède depuis la création d'un widget "Ressource" effectue une recherche sur le nom des espaces et pas les noms des ressources. Je trouve celà étrange comme comportement étant donné l'endroit où il se trouve et la possibilité de chercher par "Type", en tout cas c'est contre intuitif.
![image](https://user-images.githubusercontent.com/35995165/46569715-3c8dd300-c959-11e8-8b74-7ba2a25e3957.png)
- [x] L'utilisation de la fonction "Trier par"- "Type" me renvoie une erreur "Echec de chargement" et bloque le picker, obligé de reload. L'erreur se produit quand on est à la racine avec tous les dossiers d'espace, mais pas quand je suis dans un espace donnée (une fois que j'ai cliqué un dossier)
- [x] En essayant de revenir en arrière via le sommaire, ou d'accéder à un autre dossier d'espace on rencontre un "Échec de chargement", crash du picker, reload mandatory.

**Comment by jbbrosset** [comment]
- [ ] Le sommaire n'affiche pas tous les dossiers / espaces auxquels ont a normalement accès (je n'ai que la fin de la liste)

**Comment by Elorfin** [comment]
Le dernier point à traité possède son propre ticket : #5941
