### ISSUE TITLE
Suppression d'onglets

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4939]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.21

Que ce soit sur le Bureau ou dans un Espace, une suppression d'onglet affiche le message "Chargement en cours" mais ne réussit jamais. On est renvoyé vers l'onglet N°1 mais la page Crash.
Reload obligatoire pour se sortir du Crash.

**Comment by ngodfraind** [comment]
Reproduit (mais pas compris pourquoi encore)
