### ISSUE TITLE
Questionnaire ; accès, durée, page d'accueil, tri résultats

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#4956]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

**Accès par date** 
- [x] Ne fonctionne pas (reste inaccessible)
- [x] La date manque dans l'écran d'accueil
![image](https://user-images.githubusercontent.com/895878/46664437-53cef980-cbc1-11e8-9afd-914ecfb4918d.png)

**Dans Paramètres / Passation**
- [x] La durée n'est pas respectée, on est éjecté de façon aléatoire

**Page d'accueil et fin**
- [x] L'écran d'accueil n'apparaît pas alors qu'on a tout cocher dans paramètres d'affichage
- [x] La page de fin est manquante également

**Dans Liste des résultats**
- [x] Le tri sur l'utilisateur, ne trie ni sur le nom ni sur le prénom

**Comment by jbbrosset** [comment]
v12.0.27 : 

- [ ] Disparition de la fonctionnalité de remise à zéro des résultats ?

**Comment by clarophil** [comment]
Pour la durée on perd directement 52 secondes, exemple si on met 3 minutes on directement à 2:08, après le temps s'écoule normalement.

**Comment by Elorfin** [comment]
>Disparition de la fonctionnalité de remise à zéro des résultats ?
@jbbrosset : en effet, par contre il y a la possibilité pour un gestionnaire de supprimer des résultats depuis la liste des résultats.

Pour le reste c'est corrigé dans la 12.4.10.
