### ISSUE TITLE
Ressource Wiki : Export PDF

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4965]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.25

- [ ] lorsqu'on tenter d'exporter une page wiki en PDF pour l'imprimer, on est renvoyé sur une erreur 500
exemple ici : https://w-alter.mfr.asso.fr/resources/show/icap_wiki/2fbb9229-b462-4b69-b0b8-aaa881c2f053#/

**Comment by ngodfraind** [comment]
La config du serveur est réglée, du coup c'est corrigé.
