### ISSUE TITLE
Insérer un lien /  Cible

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4971]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.25

La liste déroulante du Choix de cible passe derrière la fenêtre active : 
![image](https://user-images.githubusercontent.com/35995165/46737623-4470ae80-cc9c-11e8-94a0-f19097bcfa80.png)

**Comment by jbbrosset** [comment]
Valide à plusieurs autres endroits.
En fait c'est visible à chaque fois qu'il y a un menu déroulant dans une modal on dirait.

**Comment by jbbrosset** [comment]
Non résolu en 12.2.5

**Comment by LaurentGruber** [comment]
remplacé par https://github.com/claroline/Distribution/issues/5509
