### ISSUE TITLE
Accès plateforme depuis safari

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4974]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.25

Accès impossible au bureau avec le navigateur Safari depuis un Mac ou un IPhone.
L’accueil à du mal à se charger et quand on tente un accès bureau on a juste une page blanche sans rien.
Le bouton de connexion ne s'affiche même pas sur Iphone.

Sur windows avec safari 5.1.7 (dernière version dispo pour windows) j'arrive à me connecter mais l'affichage est complètement foireux (à mon avis c'est parce que le navigateur est dépassé)

En attendant on a demandé aux utilisateurs sous Mac de passer par Chrome mais ..... les vielles habitudes tout ça tout ça...

**Comment by LaurentGruber** [comment]
j'ai fais quelque test : 
- iphone X (ios 11) sous safari, j'accède sans souci
- iphone 6s (ios11) safari, j'accède sans souci
- iphone 6s (ios 9) safari, j'accède sans souci
- mac os, safari 11, j'accède sans souci

donc quel version ? maintenant si c'est une trop vieille on ne pourra probablement rien y faire ...

**Comment by jbbrosset** [comment]
Je fais la Maj en iOS 12 sur mon Iphone 8 pour le test mais sous iOS11 ça charge pas, j'ai une page vide avec juste le fil d'arianne et le fond des menu top et side bar...
![img_3856](https://user-images.githubusercontent.com/35995165/46789048-e09dc280-cd3b-11e8-9d8c-abda7c729de3.PNG)

**Comment by jbbrosset** [comment]
ok trouvé
J'ai vidé le cache de safari sur mon tel et ça marche bien (le boulet)
Tu peux fermer
