### ISSUE TITLE
Glisser les étapes d'un parcours pour les déplacer ?

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#4979]
| Q             | A
| ------------- | ---
| Bug report?   | ???
| Version?      | 12.0.23

![image](https://user-images.githubusercontent.com/14308826/46797461-84449e00-cd4f-11e8-95d0-8da3b9588496.png)

Question: on ne peut plus déplacer les étapes d'un parcours en les glissant ?

**Comment by LaurentGruber** [comment]
pas pour le moment

**Comment by om64** [comment]
Un autre moyen pour contourner le problème?
