### ISSUE TITLE
Personnalisation incomplète

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4981]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.25

Le jeu d'icônes personnalisées n'est pas repris dans la modal de création de widget 
- Texte
- Ressource

Pas de picto pour liste mais on pourrais reprendre : 
- Dossier
- Agenda
- Forum
- Annonce 
- Blog

**Comment by Elorfin** [comment]
Duplicate #5244
