### ISSUE TITLE
Droits et rôles partiellement pris en compte

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#4987]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.27

Je viens d'avoir le cas d'un user (Stéphanie NOEL pour ne pas la citer) qui rencontre un problème d'Upload lors de l'import de comptes utilisateurs.
Elle a bien le rôle de gestionnaire d'orga, elle a accès à l'outil , mais au moment ou elle dépose le fichier la plateforme renvoie un bandeau rouge d'échec.
Si je me connecte "en tant que" j'obtiens le même soucis. Je n'arrive pas à identifier si c'est un mauvais paramétrage sur ces droits ou si il s'agit d'un bug.

En fait ce qui me fait douter, c'est que le bureau réservé au rôle "@mfr.asso.fr" ne s'affiche pas quand on se connecte avec son compte, comme si elle n'avait pas le rôle alors qu'elle le possède bien.

Ce qui est encore plus flippant c'est ce matin j'ai une admin plateforme qui a rencontré le soucis : 
Pas d'affichage du bureau réservé aux "@mfr.asso.fr", comme si elle ne possédait pas les droits nécessaires.

**Comment by Elorfin** [comment]
Le second point est corrigé par : https://github.com/claroline/Distribution/pull/5004.

**Comment by greg49** [comment]
Même problème #5014
