### ISSUE TITLE
Widgets | Nombre de résultats minimum

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#4993]
| Bug report?   | no
| Version?      | 12.0.26

L'affichage de **15 résultats** minimum par widget fait que nous ne pouvons avoir une page d'accueil de bureau avec 4 blocs (2 + 2) sans un ascenseur immense. Peut-on disposer d'un paramétrage à 5 résultats afin que l'accueil tienne sur un seul écran PC d'un seul coup d'oeil sans scroll ?

![image](https://user-images.githubusercontent.com/33163723/46873942-3b1c4900-ce38-11e8-9367-261cd86f3800.png)

![image](https://user-images.githubusercontent.com/33163723/46874287-1bd1eb80-ce39-11e8-84e2-0559c15343c5.png)

NB ergonomie sur smartphone : le bandeau et les hauts de widgets prend 90% de l'écran. Un bandeau plus petit en hauteur?
![image](https://user-images.githubusercontent.com/33163723/47659683-c2d2b900-db95-11e8-8ad8-f70156a64591.png)

**Comment by LaurentGruber** [comment]
duplicate : https://github.com/claroline/Distribution/issues/4691
