### ISSUE TITLE
EA | Fil d'Ariane

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#4994]
| Bug report?   | yes/ 
| Version?      | 12.0.26

Mes tentatives de remontée à la racine des "Ressources" des EA par le lien hypertexte du fil d'Ariane me génère une erreur 404.

![image](https://user-images.githubusercontent.com/33163723/46874746-280a7880-ce3a-11e8-9d20-acd5a8d6c96b.png)
![image](https://user-images.githubusercontent.com/33163723/46874776-39ec1b80-ce3a-11e8-9967-0df93dacf4db.png)

**Comment by npaille** [comment]
![image](https://user-images.githubusercontent.com/33163723/46947504-4ca16300-d07b-11e8-895c-b225f3fdbd70.png)

Je reproduis l'erreur 404 aux autres niveaux du fil d'ariane

**Comment by greg49** [comment]
même problème  avec la V12.1,0
Oops! An Error Occurred
The server returned a "404 Not Found".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
