### ISSUE TITLE
Barre de menu supérieure | Outils > Message = page vide

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#4996]
| Bug report?   | yes 
| Version?      | 12.0.26

Le menu Outil> Messages du bandeau supérieur mène à une page vide pour tous types d'utilisateurs.
Peut-on le masquer ou afficher un résultat ?

![image](https://user-images.githubusercontent.com/33163723/46876033-8d139d80-ce3d-11e8-9a12-59a95bd7a6e7.png)

![image](https://user-images.githubusercontent.com/33163723/46876056-9bfa5000-ce3d-11e8-8558-417031ade427.png)

**Comment by Garakotxea** [comment]
Je confirme, page vide sur notre 12.0.27.
Bien à vous

**Comment by LaurentGruber** [comment]
il va disparaitre de la dans les jours à venir

**Comment by npaille** [comment]
Bonjour,
Le bouton message vide est encore présent même après la mise à jour.
Bien cordialement
