### ISSUE TITLE
Widget | Mode de vue Grille large : non illustré pour les annonces

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#4997]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      |  12.0.26

Le mode de vue "Grille large" affiche toujours un visuel, excepté pour les listes d'annonces.
- Peut-on disposer d'un champ pour ajouter un **visuel dédié** par annonce, géré par le widget ?
- Et si le champ n'est pas rempli, prendre **PAR DEFAUT** la miniature associé à chaque espaces d'activité.
 
![image](https://user-images.githubusercontent.com/33163723/46878414-89831500-ce43-11e8-9557-c119a815067d.png)

**Comment by Elorfin** [comment]
Le 1er point est possible dans la dernière version.

**Comment by npaille** [comment]
Merci bien !

**Comment by npaille** [comment]
Pour le moment, je peux charger une image mais je ne peux enregistrer.
Le fameux message "Echec de mise à jour"

![image](https://user-images.githubusercontent.com/33163723/47578755-7f383f00-d94a-11e8-92bc-02e7e362ab5f.png)
