### ISSUE TITLE
Widget Liste d'espaces d’activités

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#4999]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.0.27

Le widget Liste d'espaces d'activités ne renvoie rien sauf une erreur
Vue admin:
![image](https://user-images.githubusercontent.com/31481850/46913904-76cd2500-cf96-11e8-9336-0003f4f58fc9.png)

Vue utilisateur:
![image](https://user-images.githubusercontent.com/31481850/46913911-9b290180-cf96-11e8-99ef-300ed518a6f7.png)

**Comment by LaurentGruber** [comment]
| [Semantical  Error] line 0, col 127 near 'created DESC': Error: Class  Claroline\CoreBundle\Entity\Workspace\Workspace has no field or  association named meta.created
-- | --
