### ISSUE TITLE
Exclude dev/test files from prod archives

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#5]
This can be easily achieved using [git attributes](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes#Exporting-Your-Repository). It would include:

- dev commands
- test directories
- dev tools configs
- fake data used in tests
- any code and resources aimed at dev only (like generators, hooks, etc.)

**Comment by ngodfraind** [comment]
@stefk 
Maybe update the scripts/release.sh to achieve this ?

**Comment by stefk** [comment]
@ngodfraind, we already have the [.gitattributes](https://github.com/claroline/Distribution/blob/master/.gitattributes) file, that's the most simple/effective way IMO.

**Comment by ngodfraind** [comment]
I know but we currently generate release from the script/release.sh script.

2016-05-31 15:19 GMT+02:00 Stéphane Klein <notifications@github.com>:

> @ngodfraind <https://github.com/ngodfraind>, we already have the
> .gitattributes
> <https://github.com/claroline/Distribution/blob/master/.gitattributes>
> file, that's the most simple/effective way IMO.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/claroline/Distribution/issues/5#issuecomment-222685638>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABVSthPmArkrhlMmlidg3DbdHjFxXRDaks5qHDV9gaJpZM4IBE5k>
> .
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by stefk** [comment]
The release script uses composer which retrieves tarballs from github. Those tarballs are generated with `git archive` and that command takes .gitattributes into account.

**Comment by ngodfraind** [comment]
Do we talk about the same script ?

https://github.com/claroline/Claroline/blob/master/scripts/release.sh#L39

**Comment by ngodfraind** [comment]
That one is nice because we can pick a branch.

**Comment by stefk** [comment]
https://github.com/claroline/Claroline/blob/master/scripts/release.sh#L53

That's where the source are fetched (there's not much to exclude in the root repo).

**Comment by ngodfraind** [comment]
Ok, got it.
