### ISSUE TITLE
Collecticiel-Enseignant-Evaluation notation-Mise en page

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#500]
@ericvincenterv : mise en page problématique

![image](https://cloud.githubusercontent.com/assets/16414632/15717946/780f5102-2829-11e6-86a6-1b6463f28985.png)

**Comment by ericvincenterv** [comment]
@jj-quintin Est-ce mieux ainsi ? ![modal-notation](https://cloud.githubusercontent.com/assets/5363344/15738711/cf755486-28ac-11e6-89ac-0ae0e795d7ee.png)

**Comment by jj-quintin** [comment]
Parfait :+1: 

Quelques remarques supplémentaires sur cette saisie d'écran : 
- Possible que le document soit activable (lien) quand c'est pertinent (fichier, ressource...) ? (nouveau ticket)
- On voit bien ici que les champs commentaires/critères ne sont pas les bons. Ce sont tjs les mêmes et proviennent tjs du même collecticiel (celui que j'avais créé il y a qque temps (ticket déjà déposé)
- Les consignes devraient se présenter de la même manière qu'ailleurs en pareilles circonstances (bloc avec le titre, fermé et déployable à la demande) (nouveau ticket ?)

**Comment by ericvincenterv** [comment]
@jj-quintin 

> * Possible que le document soit activable (lien) quand c'est pertinent (fichier, ressource...) ? (nouveau ticket)

C'est possible. Est-ce que l'enseignant cliquerait à ce niveau, il peut le faire quand il est sur la liste complète.


> * On voit bien ici que les champs commentaires/critères ne sont pas les bons. Ce sont tjs les mêmes et proviennent tjs du même collecticiel (celui que j'avais créé il y a qque temps (ticket déjà déposé)

Oui, j'ai lu le ticket.


> * Les consignes devraient se présenter de la même manière qu'ailleurs en pareilles circonstances (bloc avec le titre, fermé et déployable à la demande) (nouveau ticket ?)

A priori, c'est bien le fonctionnement actuel. Si tu cliques sur "Consigne" dans la modale, celle-ci s'ouvre et se ferme à volonté.

**Comment by jj-quintin** [comment]
@ericvincenterv 

Possible que le document soit activable (lien) quand c'est pertinent (fichier, ressource...) ? (nouveau ticket)
C'est possible. Est-ce que l'enseignant cliquerait à ce niveau, il peut le faire quand il est sur la liste complète.

oui, il pourrait le faire d'ici aussi (mais ce n'est pas urgent)

**Comment by jj-quintin** [comment]
@ericvincenterv 

Les consignes devraient se présenter de la même manière qu'ailleurs en pareilles circonstances (bloc avec le titre, fermé et déployable à la demande) (nouveau ticket ?)
A priori, c'est bien le fonctionnement actuel. Si tu cliques sur "Consigne" dans la modale, celle-ci s'ouvre et se ferme à volonté.

Ok alors
