### ISSUE TITLE
Ressource Web : plus lisible en ligne -> téléchargement proposé par le navigateur

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#5001]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.0.27

Bonjour,
Lorsqu'on clique sur la ressource Web (.zip) les navigateurs FireFox et Chrome proposent de la télécharger (pas testé les autres).
Bien à vous.

**Comment by ngodfraind** [comment]
J'ai pas pu reproduire. Un exemple quelque part ?

**Comment by Garakotxea** [comment]
Bonjour Nicolas,
Je t'ai envoyé un ZIP par mail vers midi, l'as-tu reçu ?
Veux-tu un accès sur notre plateforme par un compte utilisateur ? Si oui je t'envoie sur la même adresse?
Bonne journée.

**Comment by ngodfraind** [comment]
Je veux bien l'adresse.

**Comment by Garakotxea** [comment]
OK, j'ai essayé de t'envoyer les identifiants par mail mais l'adresse claroline.com que j'ai tenté prenom.nom n'a pas fonctionné.
Je te mets un id temporaire puisqu'en public
https://baiona-sio.greta-sud-aquitaine.academy/ 
id : test
pass : TEST

Espace SISR, il n'y en a qu'un.

Je ne trouve pas la banque de questions dans cette V12 avons-nous loupé quelque chose à l'installation ?

**Comment by Garakotxea** [comment]
Bonjour Nicolas,

Voici l'exemple qui fonctionne sur la 10.5.8 mais pas sur la 12.1.1

Bonne journée.



Jakes Irazoqui
claroline@ent-st-joseph-hasparren.fr
 
expéditeur: Godfraind
Envoyé: 2018-10-22 11:54
A : claroline/Distribution
Cc : Garakotxea; Author
Sujet: Re: [claroline/Distribution] Ressource Web : plus lisible en ligne -> téléchargement proposé par le navigateur (#5001)
 
J'ai pas pu reproduire. Un exemple quelque part ?

**Comment by Garakotxea** [comment]
Tu peux voir ça à https://baiona-sio.greta-sud-aquitaine.academy/ 
id : test
pass : TEST

Espace SISR, il n'y en a qu'un.

Je ne trouve pas la banque de questions dans cette V12 avons-nous loupé quelque chose à l'installation ?



Jakes Irazoqui
claroline@ent-st-joseph-hasparren.fr
 
expéditeur: Godfraind
Envoyé: 2018-10-22 17:38
A : claroline/Distribution
Cc : Garakotxea; Author
Sujet: Re: [claroline/Distribution] Ressource Web : plus lisible en ligne -> téléchargement proposé par le navigateur (#5001)
 
Je veux bien l'adresse.
