### ISSUE TITLE
Ressource Web : inaccessibles

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5003]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.27

Les ressources web affichent un message semblables aux wikis en début de V12 : 
![image](https://user-images.githubusercontent.com/35995165/46948841-a86deb00-d07f-11e8-8273-4cd82434d2eb.png)

Les tentatives de téléchargement résultent sur une Error 500

**Comment by LaurentGruber** [comment]
tu peux donner un ou deux lien ?

**Comment by ngodfraind** [comment]
reproduit
