### ISSUE TITLE
Gestion des espaces : duplication / suppression Broken

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5005]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.27

- [x] Lorsqu'on tente de dupliquer un espace d'activité, la plateforme renvoie une erreur de chargement.
![image](https://user-images.githubusercontent.com/35995165/46952113-449cef80-d08a-11e8-9616-2c1cc410d5bc.png)

- [x] Message d'erreur aussi lors de la suppression d'espace (bandeau rouge) pour les espaces 12244 et 12051. Ca semble marche sur d'autres espace qui sont plutôt vide.

**Comment by npaille** [comment]
Aujourd'hui les performances (serveur?) ne sont pas au rendez-vous, j'ai des erreurs de chargement fréquentes.
![image](https://user-images.githubusercontent.com/33163723/47017247-0d921100-d152-11e8-939f-c226b67f634a.png)

**Comment by jbbrosset** [comment]
Ce ticket devient urgent de notre côté.
