### ISSUE TITLE
erreur lors de la copie une ressource

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#5008]
| Q             | A
| ------------- | ---
| Bug report?   | yes/
| Version?      | 12.0.27
Tout est dans le titre..;
![image](https://user-images.githubusercontent.com/31481850/46991669-245f4600-d107-11e8-957f-60cac11a0633.png)
Et en même temps, je n'ai pas accès dans la liste à tous mes espaces ( mon espace perso entre autre), il n'y en a que 20, et lorsqu'on ouvre la liste, ça cache les répertoires les plus à gauche (ça c'est moins grave, c'est de l'ergonomie)...
![image](https://user-images.githubusercontent.com/31481850/46991770-946dcc00-d107-11e8-9d3b-7e9f1efc25a7.png)

**Comment by alainertveldt** [comment]
une ressource **cours** que j'ai essayé de copier
![image](https://user-images.githubusercontent.com/31481850/46996865-57f99a80-d11e-11e8-9a8c-bc45af66a291.png)
l'espace math_p a été créé avec une version antérieure à la v12
j'ai essayé de copier des ressources évaluation, pdf et texte et là pas de problème

**Comment by LaurentGruber** [comment]
ok, on a corrigé la copie des cours hier, donc ça sera dans la prochaine mise à jour ...
