### ISSUE TITLE
[Collecticiel]Enseignant-Evaluation notation-Validation-Message parasite

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#501]
@ericvincenterv : message après clic sur enregistrer (la notation d'un document)

![image](https://cloud.githubusercontent.com/assets/16414632/15718008/b71802e0-2829-11e6-8f6c-99d5407b4345.png)

**Comment by ericvincenterv** [comment]
@jj-quintin : peux-tu en dire plus sur le contexte afin que je puisse reproduire ?

**Comment by jj-quintin** [comment]
Je devine donc que cela ne se produit pas de ton côté, correct ?
Quand j'enregistre une évaluation (ici par notation), mon navigateur affichait ce message

**Comment by ericvincenterv** [comment]
Je n'arrive pas à reproduire en local, effectivement.

**Comment by jj-quintin** [comment]
Tu as essayé sous chrome ?

**Comment by ericvincenterv** [comment]
J'ai testé sous Chrome et en demo-v6, je ne reproduis pas.

**Comment by jj-quintin** [comment]
Tu as une idée de ce qui a pu produire ça de mon côté (de manière assez systématique) ?

**Comment by ericvincenterv** [comment]
@jj-quintin : on en parle lors de ta prochaine visite dans le bureau.

**Comment by ericvincenterv** [comment]
Reproduit localement lors de la mise à jour de la note.
