### ISSUE TITLE
Collecticiel-Enseignant-Evaluation Paramètre appréciation

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#502]
@ericvincenterv bug : lorsque paramètre choisi = appréciation et sauvegarde, ce paramètre n'est pas enregistré si l'on passe avant sur "Gérer les évaluations" (cela ne fonctionne qu'avec la séquence a) choisir Appréciation b) sauvegarder et seulement c) Gérer les évaluation et encore d) sauvegarder

![image](https://cloud.githubusercontent.com/assets/16414632/15718362/4f3443da-282b-11e6-922b-e3bfc8f8d25f.png)

**Comment by ericvincenterv** [comment]
@jj-quintin : reproduit en local.
