### ISSUE TITLE
Accès par date à une ressource bloque l'accès même si on est dans la plage de dates

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#5024]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Sur n'importe quelle ressource
Configurer
Restriction d'accès
Par date
Mettre une date passée et une date future
Sauver

-> la ressource n'est pas accessible aux collaborateurs

**Comment by npaille** [comment]
Info d'un utilisateur : une restriction d'accès par date dans les évaluations bloque aussi l'ouverture même quand la date n'est pas échue.
