### ISSUE TITLE
Impossible de supprimer des espaces d'activités

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#5029]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.27

Après le passage de la version 11 à 12, impossible de supprimer des espaces d'activités créés sous la version 11. Un message de succès apparaît, mais l'espace d'activités n'est pas supprimé.

**Comment by npaille** [comment]
Idem mais sans message de succès

![image](https://user-images.githubusercontent.com/33163723/47150352-9d60c800-d2d6-11e8-94bb-7baa3e17abae.png)

**Comment by alainertveldt** [comment]
idem avec certains anciens EA.... j'ai essayé de supprimer à la main le contenu de l'un d'eux... j'ai réussi à presque tout supprimer sauf un dossier... si ça peut aider à résoudre le bug
