### ISSUE TITLE
[Collecticiel]Enseignant-Evaluation Appréciation - Erreur de paramètre

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#503]
@ericvincenterv Bug : 

1) ai enregistré paramètre appréciation, en mode d'évaluation j'obtiens la modale relative à la notation

2) Erreur de champs critères/commentaires : ce ne sont pas ceux que j'ai créés (ils proviennent d'un autre collecticiel)

![image](https://cloud.githubusercontent.com/assets/16414632/15718555/40057162-282c-11e6-8a4d-0fd5c7b822f6.png)

![image](https://cloud.githubusercontent.com/assets/16414632/15718565/54927ff8-282c-11e6-86ce-a680591e432d.png)

**Comment by ericvincenterv** [comment]
@jj-quintin : ok. J'ai reproduit en local. Je corrige.

**Comment by ericvincenterv** [comment]
https://github.com/claroline/Distribution/issues/499
