### ISSUE TITLE
Bouton CONNEXION

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#5033]
| Question
| ------------- | ---
| Bug report?   | yes
| Version 12.1.0

Bonjour,
on a quelques difficultés à résoudre un problème avec le bouton Connexion (en haut à droite) depuis un certain temps - pas depuis la V12 - le lien est : 
https://www.ourss.fr/claroline-16.09/web/login
Nous avons trouvé une parade en intégrant un autre bouton dans la page dont le lien est : 
https://ourss.fr/claroline-16.09/web/app.php/login

Si parmi vous, une possible solution émerge, je suis preneur...

**Comment by LaurentGruber** [comment]
Une petite config apache2 : 
```
<IfModule mod_rewrite.c>
Options -MultiViews
RewriteEngine On
 RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ app.php [QSA,L]
</IfModule>
```
