### ISSUE TITLE
Lien : affichage d'un menu déroulant d'ouverture de page en arrière plan

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#5045]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.0.23

Il y a un problème lors d'un ajout de lien, l'affichage du menu déroulant de choix de type d'ouverture de page en arrière plan et donc non-sélectionnable.
![image](https://user-images.githubusercontent.com/32478422/47352900-f44a1100-d6cb-11e8-8cc8-18f378af0c05.png)

**Comment by flow39** [comment]
@lgeschwine @LaurentGruber 
Si il s'agit bien de la modal pour insérer une ressource "url" dans un ea, elle à été retravaillée.
![image](https://user-images.githubusercontent.com/7293233/48843687-076a0280-ed98-11e8-9442-85217d0f1482.png)
Je n'ai pas de problèmes d'affichage particulier.

**Comment by LaurentGruber** [comment]
remplacé par : https://github.com/claroline/Distribution/issues/5509
