### ISSUE TITLE
copie de ressources impossible

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#5046]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | egretab 12.0.23

![image](https://user-images.githubusercontent.com/32478422/47353241-cdd8a580-d6cc-11e8-9526-b271281232cc.png)
impossible de copier une ressource d'un EA vers un autre
![image](https://user-images.githubusercontent.com/32478422/47353334-0ed0ba00-d6cd-11e8-9a3f-c85c9c7a0f0e.png)
Pourtant j'ai le message création réussie
![image](https://user-images.githubusercontent.com/32478422/47353407-42abdf80-d6cd-11e8-9615-18d3923fbe2f.png)

**Comment by flow39** [comment]
@lgeschwine @LaurentGruber 
J'ai re-testé en v12.1.14. La copie d'un fichier ou d'une ressource fonctionne. La copie d'un dossier échoue (avec notification d'échec) :
![image](https://user-images.githubusercontent.com/7293233/48847486-f2926c80-eda1-11e8-8189-e961c2039260.png)
Ce qui est déroutant lors d'une copie, c'est que la liste des ressources dans l'EA d'origine se transforme en liste des espaces d'activité :

avant copie :
![image](https://user-images.githubusercontent.com/7293233/48847713-7cdad080-eda2-11e8-868d-31af1814b00c.png)

après copie :
![image](https://user-images.githubusercontent.com/7293233/48848545-72213b00-eda4-11e8-9e39-21eb5961c0ff.png)
