### ISSUE TITLE
Liens "Broken"

### ISSUE THREAD

**Issue by Garakotxea** [claroline/Distribution#5051]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.1.5

Bonjour,
Mauvaise surprise ce matin après la MAJ presque tous les liens sont morts, sauf ceux que j'avais fait hier après-midi.
Je remonte l'info au cas où d'autres auraient le souci car je pense qu'il n'y a rien à faire malheureusement, si ce n'est refaire tous les liens de tous les onglets. A ce propos on est chauqe fois ramené à la racine des ressources lors l'ajout de fichiers, ce qui rend le travail très long. L'explorateur ne sait pas rester dans le dossier courant.
Les liens pointent vers des N° de file maintenant au lieu de pointer vers un N° de ressource https://baiona-sio.greta-sud-aquitaine.academy/resource/open/file/247 (lien brisé)
https://baiona-sio.greta-sud-aquitaine.academy/resources/show/file/372c025c-8b7d-45ad-b18f-a9c9e5d4c8d1 (lien OK)
Bien à vous
![image](https://user-images.githubusercontent.com/22524770/47413275-23b15a00-d76e-11e8-89b2-e3f9903acf36.png)

**Comment by Garakotxea** [comment]
Ah, OK, ça serait bien:) car j'ai déjà tous du les reprendre quand un nom de domaine a été affecté à notre CC. J'avais tout créé sur un CC joignable par son @IP (lien en "dur").

**Comment by LaurentGruber** [comment]
tu avais une commande pour ça : php app/console claroline:rich_text:update qui aurais pu te le faire en 1 minutes... Je sais que ça ne te sers plus à rien maintenant mais si ça se reproduit ...

**Comment by Garakotxea** [comment]
Merci :), je m'en souviendrai :)
Bonne journée.

**Comment by LaurentGruber** [comment]
Voilà tu refais une maj dans 5 min (le temps que packagist se mette à jour) et ça devrait être ok ...

**Comment by Garakotxea** [comment]
Ca marche, je vois si ça ne gène pas mon collègue. Je te tiens au courant du résultat.
Merci par avance en tout cas.

**Comment by Garakotxea** [comment]
Ca n'a pas fonctionné mais le problème tient à notre plateforme je pense.
Pour gagner du temps - à cause de l'explorateur de ressource qui revient à la racine à chaque ajout de lien et au copier/coller qui me créé des False si j'ajoute plusieurs ressources à la fois et que je veux les réordonner - j'avais remplacé l'@IP des liens par le nom de domaine https://baiona-sio.greta-sud-aquitaine.academy/ . Cela avait fonctionné mais plus maintenant. Je vais peut-être attendre pour mettre les liens à jour que l'explorateur de ressources soit aussi performant que pour les versions précédentes.
Merci en tout cas pour le coup de main.
Bonne journée.

**Comment by Garakotxea** [comment]
Juste pour info, rien dans les logs 
erreur 500. Logs apache access.log. Pas de logs dans error.log
 
192.168.150.254 - - [24/Oct/2018:09:55:48 +0200] "GET
/resource/open/file/129 H│
TTP/1.1" 500 1157
"https://baiona-sio.greta-sud-aquitaine.academy/workspaces/4/│
open/tool/home" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0)
Gecko/20100│
101 Firefox/62.0"
