### ISSUE TITLE
Suppression de raccourcis impossible

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#5053]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.1.2

Impossible de supprimer des raccourcis
![image](https://user-images.githubusercontent.com/31481850/47414427-38432180-d771-11e8-8586-a0a4d5fc4b4b.png)
il s'agit d'un pdf de mon espace perso

**Comment by Elorfin** [comment]
C'est corrigé dans la dernière version.
