### ISSUE TITLE
Ressource : la barre de recherche n'est plus fonctionnelle

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#5054]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.3

Dans Ressource
On entre un critère de recherche
Aucune réaction, aucun résultat

**Comment by clarophil** [comment]
Le paramétrage de la barre de recherche est extrêmement lourd car il faut le faire pour chaque dossier et sous-dossier d'un espace, je propose :
- [ ] activer la barre de recherche par défaut

- [ ] si la barre de recherche est activée ou désactivée, reporter ce paramètre sur tous les sous-dossiers

**Comment by Elorfin** [comment]
Tu dois pas être sur la dernière version : on a changé la config par défaut des dossiers.

Dans la dernières version, à la création on active la recherche avec les filtres "Publié", "Type de ressource" et "Nom".

**Comment by clarophil** [comment]
On a la 1.12.28

**Comment by Elorfin** [comment]
Bizarre.

Je viens de retester chez moi (12.1.29) et : 
- La barre de recherche est bien activée par défaut.
- Les filtres fonctionnent (j'en ai testé quelques uns)

Pour les points :
> si la barre de recherche est activée ou désactivée, reporter ce paramètre sur tous les sous-dossiers

> sur les sous dossiers, pas de récursivité

Ce n'est pas implémenté.

**Comment by clarophil** [comment]
Ok ça marche pour les nouveaux dossiers mais qu'est-ce que je fais pour les centaines de dossiers existants ?

**Comment by Elorfin** [comment]
On peut l'activer pour tous les dossiers existants avec (il faudra par contre sur les dossiers où on en veut vraiment pas) :

> UPDATE claro_directory SET filterable = 1, availableFilters = '["name","published","resourceType"]'  WHERE filterable = 0;

**Comment by clarophil** [comment]
@Elorfin  merci
@LaurentGruber peux-tu exécuter la commande?

**Comment by Elorfin** [comment]
C'est fait. 187 dossiers mis à jour.

**Comment by clarophil** [comment]
ça n'a pas marché pour tous  les espaces et pour aucun sous-dossiers...

**Comment by Elorfin** [comment]
En fait ça a marché, c'est un autre problème.
