### ISSUE TITLE
Problème avec le bouton "Quitter"

### ISSUE THREAD

**Issue by OLIVIERISRPP** [claroline/Distribution#5063]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

**Comment by OLIVIERISRPP** [comment]
> Q	A
> Bug report?	yes/no
> Version?	master/7.0/etc.
Bonjour,

Lorsque nous modifions des choses sur le bureau (exemple l'emplacement du titre, le mode de vue des widgets ...) on enregistre et ensuite lorsque nous cliquons sur le bouton "Quitter" tous nos changements s'annulent !!!
et en plus, nous n'avons pas la possibilité d'ajouter une section.
merci pour votre aide
Olivier

**Comment by LaurentGruber** [comment]
Quel version ?

**Comment by OLIVIERISRPP** [comment]
Sur la Version 12.1.6
