### ISSUE TITLE
Import en échec

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5067]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.0.27

Je tente d'importer un fichier pour ajouter des utilisateurs à un workspace.
J4arrive à uploader le fichier sans problème mais quand je lance l'import, j'ai un bandeau d'échec pour le bandeau changement qui clignote 
![image](https://user-images.githubusercontent.com/35995165/47529222-7fcbc980-d8a7-11e8-9cb3-b79663fa1794.png)

J'ai d'importer les users dans un group mais j'ai le même soucis.
Si joint le fichier que je tente d'import (remis en xlsx car git supporte pas le csv)
[AjoutEspace.xlsx](https://github.com/claroline/Distribution/files/2516668/AjoutEspace.xlsx)

**Comment by jbbrosset** [comment]
Après passage en 12.1.14 : 
Toujours échec sur les imports ... 
![image](https://user-images.githubusercontent.com/35995165/48091144-31082300-e209-11e8-8e8f-2168b36553ea.png)

**Comment by LaurentGruber** [comment]
il manquait le role dans le csv
