### ISSUE TITLE
Equipe échec de la sauvegarde de la configuration

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#5073]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.2

Outil Equipe
Configuration
![image](https://user-images.githubusercontent.com/895878/47555265-a7ed1400-d90b-11e8-8e59-fb6433ee38d7.png)

**Comment by ngodfraind** [comment]
Reproduit.
