### ISSUE TITLE
[Collecticiel]Enseignant-Evaluation transmise

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#508]
@ericvincenterv 

Après avoir transmis une évaluation, il n'est plus possible de modifier l'évaluation en question
Permettre à l'enseignant d'y accéder (ce qui n'est pas possible actuellement) pour en prendre connaissance **sans** lui permettre de modifier l'évaluation
L'icône est bleue (car active, c'est ok)
mais l'infobulle devrait être adaptée dans ce cas précis (Consulter l'évaluation)

![image](https://cloud.githubusercontent.com/assets/16414632/15720232/be6a9918-2833-11e6-911c-9d062161ba38.png)

**Comment by ericvincenterv** [comment]
https://github.com/claroline/Distribution/issues/508
