### ISSUE TITLE
Impossible d'envoyer un message privé

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#5080]
| Q 
| Bug report?   | yes
| Version?      | V12.1.8

Aucun message d'erreur mais le bouton Envoyer reste inactif

![capture 2018-10-28 a 10 16 07](https://user-images.githubusercontent.com/21193255/47614108-90906100-da9a-11e8-9c7b-9b2dd4480386.jpg)

**Comment by npaille** [comment]
Même problème à l'ESTP, signalé par mes utilisateurs

**Comment by Elorfin** [comment]
Corrigé en 12.5.
