### ISSUE TITLE
Impossible de supprimer un Widget

### ISSUE THREAD

**Issue by OLIVIERISRPP** [claroline/Distribution#5081]
| Q             | A
| ------------- | ---
| Bug report?   | oui
| Version?      | 12.1.8

Bonjour,
Impossible de supprimer un widget présent dans une section
Bouton présent mais pas actif
Merci
Olivier

**Comment by LaurentGruber** [comment]
Voir commentaire : https://github.com/claroline/Distribution/issues/5084
