### ISSUE TITLE
Impossible de changer les droits

### ISSUE THREAD

**Issue by OLIVIERISRPP** [claroline/Distribution#5082]
| Q             | A
| ------------- | ---
| Bug report?   | oui
| Version?      | 12.1.8

Bonjour,
Je n'arrive pas à changer les droits. (Exemple passer en droit « tout le monde »...)
Pour moi il doit y avoir un problème .

**Comment by LaurentGruber** [comment]
Sur quel type de ressource ?
Dans quel contexte ?
Comment reproduire ?
