### ISSUE TITLE
[Collecticiel]Enseignant - Evaluation (tableau général)

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#509]
@ericvincenterv 

- Activer les infobulles prévues pour les en-têtes de colonnes évaluation et transmettre une évaluation
- Centrer l'icône noire en largeur qui correspond à l'état "Evaluation transmise"

![image](https://cloud.githubusercontent.com/assets/16414632/15720397/851f78c6-2834-11e6-8949-05cf39c38ec9.png)

**Comment by ericvincenterv** [comment]
Reproduit en local.
