### ISSUE TITLE
[Collecticiel]Enseignant-Evaluation-Transmettre évaluation 

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#510]
@ericvincenterv 

Erreur : cette évaluation  a déjà été transmise (doc Test.pptx)

![image](https://cloud.githubusercontent.com/assets/16414632/15720762/1950394e-2836-11e6-8329-be8358d69472.png)

Comme cette saisie le montre : 
![image](https://cloud.githubusercontent.com/assets/16414632/15720777/234380d2-2836-11e6-9ded-c41db94f93e3.png)

**Comment by ericvincenterv** [comment]
@jj-quintin : 
En fait, c'est peut-être le texte qui n'est pas correct ?

Soit il y a un "x" (pas de notation/évaluation)
soit il y a une flèche cliquable et là, une modale s'ouvre (celle indiquée dans ce ticket)
soit il y a une flèche non cliquable qui indique que la notation/évaluation a été transmise.

**Comment by jj-quintin** [comment]
Il me semble plutôt qu'ici l'erreur vient du fait que la flèche pour transmettre l’évaluation est encore activable alors qu'elle ne le devrait pas (car l'évaluation a déjà été transmise). C'est ce que je voulais dire

**Comment by ericvincenterv** [comment]
Ok, compris.

**Comment by ericvincenterv** [comment]
@jj-quintin : logiquement, la correction a été apportée sur cette issue : https://github.com/claroline/Distribution/issues/509
