### ISSUE TITLE
Agenda: tâches sur deux mois

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#5103]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.1.11

Une tâche qui commence au mois d'octobre et qui se termine en novembre n'apparait dans l'agenda qu'en octobre...
![image](https://user-images.githubusercontent.com/31481850/47897477-3dd7f000-de72-11e8-8afe-d20510d9f2f8.png)
![image](https://user-images.githubusercontent.com/31481850/47897485-4b8d7580-de72-11e8-923e-09652f32685e.png)

**Comment by jbbrosset** [comment]
Nous rencontrons le même problème en 12.1.22.

**Comment by alainertveldt** [comment]
Pour info: Le problème est toujours présent sur la 12.3.3

**Comment by Elorfin** [comment]
Corrigé en 12.5.
