### ISSUE TITLE
Collecticiel - Enseignant - Evaluation (tableau général)

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#511]
@ericvincenterv 

Situation : test.docx n'a pas encore été évalué, il n'y a donc pas d'évaluation à transmettre
Enlever l'infobulle "Evaluation transmise"

![image](https://cloud.githubusercontent.com/assets/16414632/15720861/82093ba2-2836-11e6-89a0-ac13c68fa22c.png)

**Comment by ericvincenterv** [comment]
@jj-quintin : reproduit en local. Je corrige.
