### ISSUE TITLE
problème d'affichage d'onglet en fonction du role

### ISSUE THREAD

**Issue by lgeschwine** [claroline/Distribution#5111]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.0.23 egretab

Dans l'EA suivant, j'ai un affichage différent de l'ordre des onglets en fonction du profil qui l'ouvre
https://egretab.claroline.com/workspaces/2540/open/tool/home#/tab/62a3e61d-f7dc-448f-acac-e69aebfabcf8
Affichage "gestionnaire" normal/souhaité
![image](https://user-images.githubusercontent.com/32478422/47916492-d3e63780-debf-11e8-9fa7-c8fa8127c377.png)
Affichage "collaborateur"
![image](https://user-images.githubusercontent.com/32478422/47916454-b87b2c80-debf-11e8-859b-e58420aed8a9.png)

J'ai pourtant vidé le cache mais rien n'y fait.

**Comment by LaurentGruber** [comment]
je ne reproduit plus.
