### ISSUE TITLE
[Collecticiel]Enseignant - Demandes adressées-Enregistrement/Sauvegarde évaluations

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#512]
@ericvincenterv 
Dysfonctionnement dans l'enregistrement/sauvegarde des évaluations (la sauvegarde a fonctionné qu'une seule fois dans ma situation, c'est donc très aléatoire)

**Comment by ericvincenterv** [comment]
@jj-quintin : quels dysfonctionnements tu as pu constater concrétement ?

**Comment by jj-quintin** [comment]
Je parviens pas à enregistrer les évaluations : 

- Je clique sur l'icône chapeau, la modale s'ouvre
- Je mets une notes
- Je clique sur enregistrer
- Je clique à nouveau sur ce chapeau pour vérifier, la modale s'ouvre
- le champ de la note est vide deux fois sur trois

**Comment by ericvincenterv** [comment]
@jj-quintin : à reproduire de mon côté.

**Comment by ericvincenterv** [comment]
@jj-quintin : compris et reproduit.

**Comment by ericvincenterv** [comment]
The correction is in this branch : https://github.com/claroline/Distribution/tree/collecticiel-16-09
