### ISSUE TITLE
Messagerie : nombre de non lus manquant

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#5120]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.1.11

Voir les messages a été remplacé par Messagerie, ce qui est un e bonne chose mais le nombre de message non lus n'apparaît plus alors qu'il est comptabilisé dans la bannière du bureau avec les notifications.

![image](https://user-images.githubusercontent.com/895878/47985983-a1b12180-e0db-11e8-90b2-84fcf8f0931c.png)

**Comment by om64** [comment]
Autre problème du même ordre: dans le header, il semble que l'utilisateur ait une notification, mais il n'en est rien.

![image](https://user-images.githubusercontent.com/14308826/48933108-5b432b80-eeff-11e8-883a-7c17a8cc5c8a.png)
