### ISSUE TITLE
Roue crantée 

### ISSUE THREAD

**Issue by OLIVIERISRPP** [claroline/Distribution#5129]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.1.14
Bonjour,

J'ai créé un utilisateur "Stagiaire" avec des droits très précis (juste consulter les documents) et ce qui me gêne c'est que sur son EA il y a la roue crantée bleue qui lui permet d'accéder au paramètre des onglets et de pouvoir les modifier (exemple: supprimer l'image).
Pouvez vous me dire si c'est normal ? ou alors me dire comment je peux faire pour que cette roue n'apparait pas.

![roue crantee](https://user-images.githubusercontent.com/44365920/48080376-c85f7d00-e1ed-11e8-94a5-f8f6e3abe02c.jpg)

Merci beaucoup
Olivier

**Comment by LaurentGruber** [comment]
je ne reproduit pas. Sur un E.A. sans droit d'édition sur l'accueil la roue n'apparait pas.
Par contre sur le bureau elle apparait et c'est normal, ça reste son bureau.
