### ISSUE TITLE
Problème dans les suivis des EA

### ISSUE THREAD

**Issue by OLIVIERISRPP** [claroline/Distribution#5131]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.1.14

Bonjour
On rencontre un problème dans les suivis "Par utilisateurs" dans les EA.
Message d'erreur...

Merci
Olivier

**Comment by LaurentGruber** [comment]
An exception has been thrown during the rendering of a template (\u0022Parameter \u0022postSlug\u0022 for route \u0022icap_blog_post_view\u0022 must match \u0022[^\/]++\u0022 (\u0022\u0022 given) to generate a corresponding URL.\u0022)."

**Comment by ngodfraind** [comment]
Reproduit.
