### ISSUE TITLE
Notification et copie messages sur boite mail

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5134]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.14

Les utilisateurs ne reçoivent plus de copie des messages de la messagerie interne sur leurs boite mail malgré qu'ils aient l'option cochée dans les configs.

De mon côté en tant qu'admin je les reçoit sans problème.

Bug ou config qui a changé de place ?

**Comment by LaurentGruber** [comment]
S'ils n'ont pas valider leur courriel c'est normal qu'ils ne reçoivent pas de mail ...
Sinon non, tu pourrais me donner en mp un utilisateur exemple pour lequel tu as le souci ?
