### ISSUE TITLE
Problème Fichier .zip

### ISSUE THREAD

**Issue by OLIVIERISRPP** [claroline/Distribution#5145]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.1.15

Bonjour,
Dans la version 11 on avait la possibilité d'importer dans une ressource un fichier .zip, et on pouvait ,lors de l'import, le dézipper.
Sur la version actuelle, lorsque j'importe un fichier .zip il me met un message d'erreur.
Pouvez vous me dire si cette fonction existe encore ?

Merci beaucoup
Olivier

**Comment by clarophil** [comment]
Non ce n'est plus possible dans la version 12 mais on peut télécharger plusieurs fichiers à la fois dans le menu contextuel "Ajouter des fichiers"

**Comment by greg49** [comment]
ok merci pour l'info.
