### ISSUE TITLE
Annonce : une annonce envoyée par email ne peut plus être effacée

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#5147]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.11

Si on a envoyé une annonce par email, on ne sait plus l'effacer ensuite.
![image](https://user-images.githubusercontent.com/895878/48252001-cc64e800-e403-11e8-8bca-cfae5dc7b2e3.png)

https://claco.vinci.be/resources/show/claroline_announcement_aggregate/9cff4fc3-6a94-42e0-8dbe-df73e87c4c30#/

**Comment by ngodfraind** [comment]
Reproduit.
