### ISSUE TITLE
Fil d'ariane : paramétrage

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#5149]
| Q             | A
| ------------- | ---
| Bug report?   | no ?
| Version?      | 12.1.11

Je vois qu'il est possible de configurer dans un espace le fil d'ariane mais comment appliquer le paramétrage à plusieurs espaces en même temps ?  
J'ai essayé dans l'administration / gestion des espaces / sélection / configurer mais l'enregistrement ne se fait que sur le 1er espace de la liste.

**Comment by LaurentGruber** [comment]
ce n'est pas possible, c'est espace par espace
