### ISSUE TITLE
Fontawesome

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#5153]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.14

L'icône "Blogger" de Fontawesome ne fonctionne pas.

![blogger](https://user-images.githubusercontent.com/14308826/48315736-55ce1300-e5da-11e8-827f-2b3cc74bf5dd.JPG)

**Comment by LaurentGruber** [comment]
soit tu as pris un icone de la version pro (payante) soit d'une mauvaise version de fontawsome

**Comment by om64** [comment]
Quelle version faut-il prendre ?
