### ISSUE TITLE
Raccourcis et fil d'ariane==> confidentialité

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#5155]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Bon il s'agit d'un soucis de confidentialité... 
Avant, quand on mettait un raccourci dans un espace d’activités vers notre espace personnel, les élèves ne savaient pas que ça venait de notre espace personnel. Maintenant ils le savent.. ça ce n'est pas gênant.... 
Ce qui est plus gênant, c'est qu'en utilisant le fil d'arianne ils arrivent à la racine du dossier où se trouvent toutes les ressources auxquelles ils ont accès via les droits, car c'est au dossier qu'on a donné les droits... Or il y a les réponses des évaluations, mais ils ne peuvent y avoir accès qu'après avoir effectué celle-ci en classe.
Avant ça ne posait pas de problème, le fil d'arianne ne montrait pas l'espace perso via un raccourci... ce serait d'ailleurs bien que ce soit encore le cas, car finalement ça ne les regarde pas où sont stockées les ressources que nous leurs proposons. 
Et c'était simple dans la gestion des droits... on donnait les droits à un dossier et le contenu hérite des droits... j'espère que ça restera comme avant sinon ça complique vraiment tout et ça prendra beaucoup plus de temps...
En images: 
![image](https://user-images.githubusercontent.com/31481850/48341133-95ddd600-e66c-11e8-91eb-30eba7d07381.png)
![image](https://user-images.githubusercontent.com/31481850/48341202-c6be0b00-e66c-11e8-9326-54d8dbd5b6f4.png)
![image](https://user-images.githubusercontent.com/31481850/48341277-eead6e80-e66c-11e8-92a6-e526b97e6e0e.png)

![image](https://user-images.githubusercontent.com/31481850/48341333-11d81e00-e66d-11e8-97f2-71cd070ad05f.png)
![image](https://user-images.githubusercontent.com/31481850/48341382-32a07380-e66d-11e8-9d0b-eab5aebb1ad6.png)
![image](https://user-images.githubusercontent.com/31481850/48341492-76937880-e66d-11e8-9a8d-0e9d20bcecd2.png)

**Comment by LaurentGruber** [comment]
tu peux aux choix, masquer le fil d'ariane dans ton espace perso, ou le configurer pour qu'ils ne voient pas la racine, dans les param du WS
