### ISSUE TITLE
Dossiers Invisibles en Collaborateur

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5165]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.14

Malgré des droits d'ouverture et de vision par défaut pour les collaborateurs, les dossiers situés à la racine de l'espace ne sont pas visible dans la navigation des ressources. LE sommaire est accessible et on arrive bien a atteindre les dossiers par ce dernier sans problème...
Espace : https://w-alter.mfr.asso.fr/workspaces/12282/open/tool/resource_manager?view_as=exit#/44e5c3bd-cd65-46cc-b346-00b186b72f01 

Vue Admin/gestionnaire:
![image](https://user-images.githubusercontent.com/35995165/48440163-71771c00-e788-11e8-8f0f-b80b5edc4db7.png)
Vue Collaobrateur : 
![image](https://user-images.githubusercontent.com/35995165/48440175-7c31b100-e788-11e8-96e9-a9cc2b4429ef.png)

**Comment by clarophil** [comment]
J'ai déjà eu ce problème, c'est parce que le dossier racine n'est pas publié.

**Comment by jbbrosset** [comment]
Oh Yes, problème résolu, j'avais pas vu que le bouton affichait un oeil non barré.
Merci.
