### ISSUE TITLE
Ajouter un fichier dans un dossier : destination erronée

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#5190]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.22

Dans les ressources
Aller dans un dossier
+ Ajouter un fichier
Télécharger réussi 
Mais le fichier est à la racine de l'espace et pas dans le dossier ouvert

**Comment by LaurentGruber** [comment]
Je ne reproduis pas, ni sur une autre plateforme, ni sur la tienne (tester sur dkptest)

**Comment by clarophil** [comment]
Cela ne se produit qu'avec certaines extensions, exemple .mlx
Fichier ci-joint qu'il faut dézipper
[GL2.zip](https://github.com/claroline/Distribution/files/2603602/GL2.zip)

**Comment by LaurentGruber** [comment]
fixed by https://github.com/claroline/Distribution/pull/5205
