### ISSUE TITLE
Duplication d'espace en erreur

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5193]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.22

Lorsque j'essaye de dupliquer un espace depuis l'interface de gestion, je tombe sr un message d'erreur.
Espace : https://w-alter.mfr.asso.fr/workspaces/12601/open/tool/home 
![image](https://user-images.githubusercontent.com/35995165/48832804-5143f000-ed7a-11e8-8ef0-39aee64351f9.png)

**Comment by jbbrosset** [comment]
Update : des copies sont créés malgré l'erreur. Seul le premier onglet est copié par contre....

https://w-alter.mfr.asso.fr/workspaces/13092/open/tool/home#/tab/d95d35b4-e1ee-48df-b89e-4b546e8a87d7

**Comment by ngodfraind** [comment]
Reproduit.

**Comment by ngodfraind** [comment]
J'ai corrigé en live sur mfr.claroline.com et j'ai pu faire une copie.
