### ISSUE TITLE
Upload d'un fichier depuis widget texte | à quoi correspondent les dossiers de destination ?

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5200]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.1.14

Depuis un widget texte, lorsque j'essaye d'uploader un fichier avec tinyMCE :

![image](https://user-images.githubusercontent.com/7293233/48893008-9d0c9d00-ee3f-11e8-80fc-f47284f8cea8.png)

Je déroule la liste de dossier pour choisir une destination :
![image](https://user-images.githubusercontent.com/7293233/48893135-e4932900-ee3f-11e8-919d-6f51589be0eb.png)

Je ne comprends pas ce qui conditionne l'affichage des éléments de cette liste. Si c'est la liste de mes EA, elle est incomplète.

**Comment by clarophil** [comment]
C'est dans l'outil Ressources de l'espace d'activité qu'on peut le paraméter
![image](https://user-images.githubusercontent.com/895878/48933488-b6295280-ef00-11e8-87bc-e340bb17f94a.png)

**Comment by flow39** [comment]
@clarophil Merci ! Je clos le ticket.
