### ISSUE TITLE
plusieurs problèmes lors de la duplication d'un EA modèle

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5202]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.14

En lien avec #5193 

J'essaye de dupliquer un modèle d'EA :
![image](https://user-images.githubusercontent.com/7293233/48898814-0c898900-ee4e-11e8-8079-008cc47117ed.png)

J’obtiens une notification d'erreur :
![image](https://user-images.githubusercontent.com/7293233/48898774-f2e84180-ee4d-11e8-8239-60f49fd41607.png)

L'EA est quand même dupliqué, mais, lorsque je rentre dans l'EA dupliquée :

Les icônes des ressources ont disparues
![image](https://user-images.githubusercontent.com/7293233/48898986-90437580-ee4e-11e8-9fb5-41f80b81dfe5.png)

les permissions affectées aux sous-dossiers dans les ressources ont disparues (affectation aux seuls gestionnaire)
![image](https://user-images.githubusercontent.com/7293233/48899090-d8fb2e80-ee4e-11e8-8b41-6acaac03c967.png)

Les restrictions par rôle affectées aux onglets de l'accueil de l'EA ne sont pas conservées. La fonction reste cochée mais pas le rôle
![image](https://user-images.githubusercontent.com/7293233/48899483-ff6d9980-ee4f-11e8-93aa-48070c931727.png)

**Comment by om64** [comment]
Les problèmes relevés dans l'issue #5201 doivent être du même ordre puisqu'il s'agit aussi d'un EA dupliqué.
