### ISSUE TITLE
Icones des ressources disparues

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5203]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.22

Depuis quelques temps (MAJ en 12.1.22 ?) les icônes de ressources ne s'affichent plus dans le navigateur de ressource des espaces.
Dans le ressource picker qui s'ouvre dans une modal (ajouter une ressource dans un widget/texte enrichi) les icones des dossiers racine de l'espace s'affichent mais pas les autres niveaux.

![image](https://user-images.githubusercontent.com/35995165/48904888-29c75300-ee60-11e8-8dd7-5b310c649168.png)

![image](https://user-images.githubusercontent.com/35995165/48904911-482d4e80-ee60-11e8-9fae-785d69bfce50.png)

**Comment by LaurentGruber** [comment]
tu vas dans le crayon sur le dossier ou tu n'as pas les icones et tu coche icone dans la partie carte et ils seront là ...

**Comment by jbbrosset** [comment]
Du coup c'est un paramètre par défaut "Sans icône" ?
Et il faut l'activer sur chaque dossier et chaque sous dossier ?
C'est super lourd....

**Comment by LaurentGruber** [comment]
On a changer le param par defaut à avec icone, il y a quelque jour, ça arrive avec la prochaine maj, mais pour ceux créé entre temps oui il faut passer dessus...
