### ISSUE TITLE
Widget Liste de ressources : Erreur 500

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5209]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.22

Chez certains utilisateurs (mais pas tous), le chargement du widget Liste de ressources situé sur le bureau plateforme renvoie une erreur. 
Vers le bureau : https://w-alter.mfr.asso.fr/desktop/tool/open/home#/tab/2e3e6a69-c80d-11e8-a47b-0cc47a960f96
Utilisateurs en erreur (par exemple) : chaigne.emmanuel ; pascal.aballea

![image](https://user-images.githubusercontent.com/35995165/48938814-9b5fd980-ef12-11e8-8628-fa9978268008.png)

**Comment by LaurentGruber** [comment]
An exception occurred while executing 'SELECT DISTINCT c0_.license, c0_.creation_date, c0_.modification_date, c0_.showIcon, c0_.name, c0_.hidden, c0_.lvl, c0_.path, c0_.value, c0_.mime_type, c0_.published, c0_.author, c0_.active, c0_.fullscreen, c0_.closable, c0_.closeTarget, c0_.accesses, c0_.views_count, c0_.deletable, c0_.id, c0_.uuid, c0_.thumbnail, c0_.poster, c0_.description, c0_.accessible_from, c0_.accessible_until, c0_.resource_type_id, c0_.icon_id, c0_.parent_id, c0_.workspace_id, c0_.creator_id F…FD-FD-UNMFR_F5EB8697-8A39-4794-A194-10624039608F", "ROLE_WS_SALARI\u00e9S_MFR-FD-FD-UNMFR_06F4A528-5EF0-44CF-B0A0-A3B844E35E0D", "ROLE_WS_COLLABORATOR_5ba374213e6c47.78336041", "ROLE_USER_CHAIGNE.EMMANUEL", "ROLE_WS_COLLABORATOR_5bf2baa48a4117.75323145", "ROLE_WS_COLLABORATOR_5bf686c8e2b296.37672192", "ROLE_WS_COLLABORATOR_5bf6a93d77b6a8.72147537", "ROLE_WS_COLLABORATOR_5bf6ab7963d4c8.46584511", "ROLE_PREVIOUS_ADMIN"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'resourceType' in 'order clause'

**Comment by ngodfraind** [comment]
corrigé sur le serveur mais le fix est pas joli

**Comment by ngodfraind** [comment]
Le réouvre car j'ai une piste de fix plus joli. Mais bon le truc pas beau fonctionne quand même.
