### ISSUE TITLE
Collecticiel-Demandes adressées-Bug

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#521]
@ericvincenterv 

Après avoir fixé les paramètres, voici le message obtenu en accédant aux demandes adressées

![image](https://cloud.githubusercontent.com/assets/16414632/15742109/378e9b9e-28bd-11e6-9089-712aa38a27ca.png)

**Comment by ericvincenterv** [comment]
See this issue : https://github.com/claroline/Distribution/issues/480
