### ISSUE TITLE
Ressource Base de Données

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5221]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.28

- [ ] Dans la base de donnée https://w-alter.mfr.asso.fr/resources/show/27/f19c3ce8-f9c5-4d72-ab6e-467b32217430#/menu , j'ai paramétré des catégories qui s'affectent automatiquement selon les réponses au formulaire. Chaque catégorie a des modérateurs qui sont chargés de remplir certaines informations visibles uniquement par eux. Le personnel de l'établissement à changé depuis et je voulais modifier les personnes identifiées en tant que modérateurs sur les catégories.
A l'édition, la case est grisée et le bouton "User" inactif.
![image](https://user-images.githubusercontent.com/35995165/49065905-b89cec80-f21f-11e8-9611-72231f9f0234.png)

**Comment by jbbrosset** [comment]
- [ ] Créer une nouvelle catégorie ne solutionne pas, on ne peux pas ajouter de gestionnaire à la catégorie

**Comment by jbbrosset** [comment]
- [ ] l'attribution automatique de catégorie fonctionne mais l'ajout ou le retrait manuel est impossible.
- [ ] L'utilisateur Marie Bluteau (admin) n'arrive pas à accéder aux champs réservés aux gestionnaires d'un fiche catégorisée en "Pédagogie et Numérique" alors qu'elle est déclarée comme gestionnaire de cette catégorie.

**Comment by LaurentGruber** [comment]
tester sur la 12.3.1 et non reproduit
