### ISSUE TITLE
erreur de traduction dans le menu actions de la gestion des EA

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5224]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.1.14

Dans le menu "voir plus d'actions" disponible dans la gestion des EA, l'intitulé "dupliquer" n'est pas traduit et apparait en anglais ("duplicate") :
![image](https://user-images.githubusercontent.com/7293233/49076762-0a527080-f23a-11e8-9734-46916c309e19.png)

**Comment by Elorfin** [comment]
Corrigé dans la dernière version.
