### ISSUE TITLE
menu d'administration caché quand connecté "en tant que"

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5225]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.14

Le menu d'administration est caché par le bandeau orange lorsque l'on est connecté "en tant que" :
![image](https://user-images.githubusercontent.com/7293233/49080347-99b05180-f243-11e8-9ce7-8ccd8153f56d.png)

Est il possible de l'afficher par dessus comme c'était le cas sur la version 11 ?

**Comment by om64** [comment]
Ou en bas de page ?

**Comment by Elorfin** [comment]
Corrigé en 12.5.
