### ISSUE TITLE
Agenda : affichage tronqué d'un évenement de plus de 2 jours

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5229]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.28

Bonjour, 

Un évènement de plus de deux jours ne s'affiche que sur 2 jours.
Cela porte à confusion.

![image](https://user-images.githubusercontent.com/24249636/49087256-cfab0100-f256-11e8-8168-7932f5515852.png)

Merci.

**Comment by Elorfin** [comment]
Corrigé en 12.5.
