### ISSUE TITLE
Ressource Scorm : Version

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5239]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.28

A l'import d'un Scorm, bandeau d'erreur de chargement.
Il semble que ce soit un erreur de version.
Quelle version de Scorm est attendu par la plateforme ?

![image](https://user-images.githubusercontent.com/35995165/49218399-9a2a2300-f3d0-11e8-9425-73e2c3fa376c.png)

**Comment by LaurentGruber** [comment]
1.2 ou 2004
