### ISSUE TITLE
Espace en erreur

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5240]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.28

L'espace  https://w-alter.mfr.asso.fr/workspaces/13184/open est en erreur à l'ouverture et à la suppression.
Erreur 500 à l'ouverture.
La suppression renvoie une erreur 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
workspace_management#/workspaces:1 Uncaught (in promise) 
message: "More than one result was found for query although one row or none was expected."
trace: (16) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]

**Comment by LaurentGruber** [comment]
fixé direct en db
