### ISSUE TITLE
Administration > Apparence > Icônes

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5244]
| Q             | A
| ------------- | ---
| Bug report?   | Yes
| Version?      | 12.2.25

Bonjour,
![image](https://user-images.githubusercontent.com/24249636/49284115-e68a6700-f493-11e8-9ee8-e8a9e4dcc74c.png)
On ne peut plus (ou pas):
- modifier les icônes unes par une
- charger un nouveau set d’icônes avec un fichier zip

En effet, je souhaiterais corriger/changer des icônes sur ces deux écrans pour rester cohérent avec la charte proposée aux utilisateurs.

- Création de ressources
![image](https://user-images.githubusercontent.com/24249636/49284278-6284af00-f494-11e8-964f-e5f519ce52cd.png)

- Création de widget
![image](https://user-images.githubusercontent.com/24249636/49284301-73352500-f494-11e8-8471-fa6381d3b157.png)

Merci.

**Comment by ngodfraind** [comment]
Je regarde tout de suite, il y avait des problèmes dessus pour le choix de la configuration des icones que j'ai corrigé. La manière dont le set d'icone est définie a changé. J'pense que c'est juste une erreur de config (c'est plus dans la db mais dans un fichier).

**Comment by LaurentGruber** [comment]
le choix du set d'icone est corrigé par : https://github.com/claroline/Distribution/pull/5589
Pour le reste il faut d'abord qu'on réécrive le système d'icone ...
