### ISSUE TITLE
Page wiki : Modération et Sommaire

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5245]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.28

Bonjour,

Dans une page Wiki, lorsque l'on modifie les options de modération, l'option choisie ne reste pas cochée. Le type de modération utilisé n'est pas indiqué (pas de case ou puce cochée)
Cependant, la modification du type de modération est validée.

![image](https://user-images.githubusercontent.com/24249636/49287240-03776800-f49d-11e8-8852-2d527dba816f.png)

Concernant le sommaire, son design est visuellement très pauvre et se distingue peu du reste de la page.
![image](https://user-images.githubusercontent.com/24249636/49287370-87c9eb00-f49d-11e8-9cb1-00404bfaca42.png)
Pourrait-on avoir le sommaire dans un cadre plus contrasté, foncé avec les liens en blanc par exemple?

Merci.

**Comment by Elorfin** [comment]
Le wiki a été redessiné dans la dernière version.
![wiki](https://user-images.githubusercontent.com/5363219/49935174-a33aea00-fed0-11e8-8708-0c205e9cbbf6.png)

Le problème à l'édition persiste. C'est en effet juste un problème d'affichage, l'option est bien changée.

**Comment by om64** [comment]
Top! Merci @Elorfin !
