### ISSUE TITLE
Ressources | "Ressources Web" (export SCENARI) - Page vide

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#5256]
| Bug report?   | yes 
| Version?      | 12.1.28

Les cours/exercices intégrés de l'ESTP Paris "Ressources Web" issus de la suite éditoriale Opale/ScenariChain ne s'ouvrent plus.
Comment les diffuser?

![image](https://user-images.githubusercontent.com/33163723/49461814-e3290f80-f7f4-11e8-8c76-2ec7828ee7cb.png)

**Comment by LaurentGruber** [comment]
fixed by https://github.com/claroline/Distribution/pull/5259
