### ISSUE TITLE
PB Modification page Accueil

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#5264]
| Q 
| Bug report?   | no
| Version?      | 12.1.34

Petit problème sous Firefox dernière version - Lorsque l'on est en mode édition de la page Accueil, impossible de descendre avec la barre de défilement qui reste bloquée et qui empêche de visualiser le bouton de sauvegarde. voir pj
![capture 2018-12-06 a 16 30 13](https://user-images.githubusercontent.com/21193255/49594142-830da700-f975-11e8-917c-8ef56b80b21b.jpg)

**Comment by greg49** [comment]
Je rajoute qu’il est impossible d'ajouter un fichier ou une ressource dans la zone d'édition.
La roue crantée tourne sans cesse...
![capture 2018-12-06 a 18 16 20](https://user-images.githubusercontent.com/21193255/49600334-3fba3500-f983-11e8-987b-c2df58157831.jpg)

**Comment by LaurentGruber** [comment]
dans administration > paramètre généraux > accueil : tu choisi new, tu seras sur la nouvelle page d'accueil mais tu devras refaire tes contenus ...
Pour les modes de vues, le formulaire est un peu complexe, insiste un peu en décochant, recochant la case de choix par exemple, voir les autres param du form ... ça finira par passer ...
