### ISSUE TITLE
Barre du menu utilisateur : 

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5270]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.1.28

Bonjour,

Le tutoriel dynamique de présentation de la barre du menu utilisateur accessible depuis le profil utilisateur présente des erreurs de traduction.

![image](https://user-images.githubusercontent.com/24249636/49726194-b8fca500-fc6d-11e8-92b6-a13293710e83.png)

- [ ] Remplacer "Header Intro title" (titre) par "Découvrons la barre du menu utilisateur ensemble !" et remplacer "Header Intro title" (texte) par "Cette barre donne propose différents outils et raccourcis pour bien naviguer dans les espaces d’activités." (panneau 1)

- [ ] Retirer le "e" après "principale" dans le titre et dans le texte (panneau 2)

- [ ] Remplacer le "A" majuscule du texte par un "a" minuscule dans le titre. (panneau 3)

- [ ] Retirer le "s" de "communications".  (panneau 4)

- [ ] Remplacer le "U" majuscule du texte par un "u" minuscule dans le titre. (panneau 5)

- [ ] Retirer le "e" de "profile".  (panneau 5)

Merci.

**Comment by jbbrosset** [comment]
"Cette barre ~~donne~~ propose différents outils et raccourcis pour bien naviguer dans les espaces d’activités." (panneau 1)"

**Comment by Elorfin** [comment]
C'est corrigé dans la dernière version.
