### ISSUE TITLE
Evaluation | Téléchargement de copies - nombre limité

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#5271]
| Bug report?   |  no
| Version?      | 12.1.28

663 copies à récupérer par des enseignants. Équivalent de 663 PDF de 56 ko.
PB : ça bloque car peut-être une limitation du nombre de copies max. 
Est-ce possible d'augmenter pour que la requête download passe...  pour ne pas pousser les formateurs à procéder en 6 morceaux de 120 ?

![image](https://user-images.githubusercontent.com/33163723/49728232-7d180e80-fc72-11e8-86a1-77b46d30a301.png)

![image](https://user-images.githubusercontent.com/33163723/49728323-b0f33400-fc72-11e8-9277-afa9e70aa688.png)

![image](https://user-images.githubusercontent.com/33163723/49728347-bcdef600-fc72-11e8-906a-c3945fa51880.png)

**Comment by ngodfraind** [comment]
Ça bloque car l'url est trop longue, mais il a d'autres manière de faire de notre coté.
