### ISSUE TITLE
Evaluation | Classement prénom/nom (au lieu de nom/prénom)

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#5272]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

La récupération des copies d'évaluation oblige à beaucoup de travail évitable.
En cause : le classement prénom/nom par défaut. Les recherches de copie/d'étudiant se fait par NOM DE FAMILLE. 
Ainsi pour chaque éval, on doit passer par EXCEL avec Convertir/délimité... pour redispatcher les colonnes et faire un classement alphabétique par nom de famille.
Inverser le classement ? un autre méthode?

Autre post : https://github.com/claroline/Distribution/issues/1596

![image](https://user-images.githubusercontent.com/33163723/49729251-3677e380-fc75-11e8-8a8a-025730a42464.png)

**Comment by clarophil** [comment]
C'est le même problème pour l'export des travaux [https://github.com/claroline/Distribution/issues/4917](url)

**Comment by ngodfraind** [comment]
C'est partit.

**Comment by clarophil** [comment]
Dans Evaluation / Voir toutes les évaluations

- [ ] Afficher la liste triée sur Nom Prénom et PAS Prénom nom
