### ISSUE TITLE
Names don't appear correctly in the dashboard

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#5276]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.28

Names don't appear correctly in the dashboard.

![image](https://user-images.githubusercontent.com/14308826/49789884-54088400-fd2d-11e8-8728-a98796d7c42b.png)

**Comment by Elorfin** [comment]
If this is because of `lastname#18 firstname#18`, it's not a bug, it's deleted users which have been anonymized.
