### ISSUE TITLE
Ajouter des trous via l'éditeur d'équations ?

### ISSUE THREAD

**Issue by om64** [claroline/Distribution#5277]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.1.28

Je voudrais composer un exercice de simplification de fractions. J'ai utilisé l'éditeur d'équations et je voudrais ajouter des trous à l'exercice. Dans l'exemple ci-dessous, l'élève devrait remplir les 1 et le 2 de la deuxième fraction comme réponse. Comment faire ?

![image](https://user-images.githubusercontent.com/14308826/49791703-510f9280-fd31-11e8-955f-2d859fc024db.png)

**Comment by LaurentGruber** [comment]
ce n'est pas possible et je ne suis pas sur qu'il y ai de solution à ça.
