### ISSUE TITLE
Base de données, impossible d'ajouter un fichier dans un champ fichier

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5282]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.14

Je crée un ressource base de données ainsi qu'une fiche. Dans cette fiche, je crée un champ fichier et j'insère un fichier texte :
![image](https://user-images.githubusercontent.com/7293233/49878979-3e788480-fe29-11e8-8195-4bcb59e7d5ef.png)
Après avoir enregistré, je consulte la fiche et le fichier inséré n'apparait pas.
![image](https://user-images.githubusercontent.com/7293233/49879200-c068ad80-fe29-11e8-8ac1-8848a2606173.png)

**Comment by Elorfin** [comment]
Je viens de tester RAS sur la dernière version.

Par contre, le 1er screen que tu montres c'est le formulaire de configuration de la Base de données. Ce qui est différent du formulaire de création/édition d'une fiche.

Le champ fichier que tu vois dans le form, est une juste une "preview" du champ qui sera affiché, c'est normal qu'il ne soit pas fonctionnel.

Il faut que tu utilises l'action Ajouter une ficher ou aller sur une fiche et l'éditer.
