### ISSUE TITLE
Gestion des formations : Impossible de créer une Session

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5286]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.28

J'essaye de créer une session pour une formation dans le module "gestion des formation"
J'ai pu créer la formation sans problème mais quand j'essaye de créer une session j'ai un message d'erreur indiquant 'code Column cannot be null'. J'ai pourtant essayé avec pleins de codes différents...

![image](https://user-images.githubusercontent.com/35995165/49930336-a62fdd80-fec4-11e8-9d7e-018fef37f8e8.png)

**Comment by kitan1982** [comment]
The fix is here :
https://github.com/FormaLibre/ClarolineBundle/pull/24
