### ISSUE TITLE
Questionnaire : Enregistrement des modifications

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5305]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.2.2

Le bug est expérimentable dans ce questionnaire : https://w-alter.mfr.asso.fr/resources/show/0cb4cb18-8670-4390-b611-13c208754cf6

- [ ] J'édite des questions (notamment la question de l'étape 3), j'enregistre et tout semble validé. Quand je teste le questionnaire, aucun changement n'a été pris en compte.
- [ ] La question d'appariement de l'étape 3 m'affiche 20 emplacements de paires au lieu de 10. J'ai refait une nouvelle question et j'arrive à en afficher que 10 mais je ne sais pas d'ou viens l'affichage de 20 paires dans l'original.

Pour contourner le soucis j'ai fais une copie de la ressource et je vois les dernières modifications dans la ressource. (la copie : https://w-alter.mfr.asso.fr/resources/show/ujm_exercise/3b9c4067-c83b-4e8c-832c-054ab33563ef#/test)

**Comment by LaurentGruber** [comment]
Tu as choisi de garder les mêmes questions entre chaque copie ?

**Comment by LaurentGruber** [comment]
fermé au profit de https://github.com/claroline/Distribution/issues/5376
