### ISSUE TITLE
Configuration de l'espace : Changement de nom 

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5306]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.2.2

Attention Remontée spéciale pour Spécialiste des bugs bizarres : 

Quand on essaye d'éditer le titre d'un espace, si on essaye d'ajouter ou supprimer une lettre au milieu du texte existant, le curseur est renvoyé à la fin du titre après chaque frappe.

Pas moyen de faire de capture, le curseur disparaît sur un impr. écran.

**Comment by jbbrosset** [comment]
Plus grave, et ça doit être lié : 
Impossible de changer le nom d'un espace, même en temps qu'admin, via la fenêtre de configuration.

![image](https://user-images.githubusercontent.com/35995165/50098882-1ae47e00-021d-11e9-83b0-f99cabc41e94.png)

**Comment by jbbrosset** [comment]
Idem via la gestion des espaces  : 
![image](https://user-images.githubusercontent.com/35995165/50099003-5aab6580-021d-11e9-83f3-63d41d781601.png)

**Comment by jbbrosset** [comment]
Le problème est en fait le même quelle que siot la configuration qu'on souhaite changer, avec le meme message d'erreur

**Comment by Elorfin** [comment]
J'ai corrigé le problème de sauvegarde des params du WS.
Par contre pour le problème de curseur qui saute, je connais et c'est pas spécifique à ce formulaire là. Je ne peux rien faire pour le moment.
