### ISSUE TITLE
[ExoBundle] Dysfonctionnement-Retour-Etape-antérieure

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#531]
J'ai terminé les deux étapes de cet exerice, j'ai utilisé le menu déroulant pour revenir à la première étape.

Deux anomalies : 
1) le menu de navigation entre les étapes est inactif
2) le bouton Valider cette étape est actif alors que j'ai terminé/déjà répondu correctement à cette étape
3) Il en va de même pour le bouton flèche suivant

Je dois valider pour me sortir de la situation

![image](https://cloud.githubusercontent.com/assets/16414632/15756380/5a757dc8-2901-11e6-8c7d-a9e141e95281.png)

**Comment by eldoniel** [comment]
Fixed by https://github.com/claroline/Distribution/issues/794
