### ISSUE TITLE
Annonce : une annonce envoyée par email et effacée toujours visible (widget annonce)

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#5318]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      | 12.2.5

Une annonce (si envoyée en notif email) peut à présent être supprimée.
Toutefois, dépubliée et/ou supprimée, je la vois encore sur mon bureau sur le widget des annonces.

https://github.com/claroline/Distribution/issues/5147#issue-379071828

![image](https://user-images.githubusercontent.com/33163723/50230163-6d07d980-03ac-11e9-8b92-7081e8529b2f.png)

![image](https://user-images.githubusercontent.com/33163723/50230328-b6f0bf80-03ac-11e9-84a4-28aced749f3d.png)

**Comment by ngodfraind** [comment]
Reproduit pour la dépublication.

**Comment by npaille** [comment]
Bonjour,
la suppression d'annonces toujours bloquée
![image](https://user-images.githubusercontent.com/33163723/53336657-3e076a00-38ff-11e9-8c69-f282939ae529.png)

**Comment by clarophil** [comment]
ça marche pour nous dans la v 12.3.4

**Comment by npaille** [comment]
J'ai trouvé la cause.
C'est quand je rebondis par le widget "Liste" des annonces que je ne peux la supprimer.
En repassant par l'EA dans Annonces, je peux. Au moins j'ai une solution de contournement.
Merci.
Nathalie

**Comment by ngodfraind** [comment]
Y a moyen de m'expliquer la procédure plus en détail ?
Comme ça je ne vois pas trop.

**Comment by npaille** [comment]
Sur le bureau pour tous, j'ai le widget vers les annonces. Si on clique sur une annonce en particulier,

>> Voici le lien vers une annonce (à partir du widget) = ANNONCE NON SUPPRESSIBLE : 
https://ecampus.estp.fr/resources/show/338d4f7d-0095-45f0-b4a6-3d25d7f02da4#/68ba7fdf-156c-4d3d-a1db-e2cd0f004228 
>> Voici le lien Via l'EA dans Ressources = ANNONCE SUPPRESSIBLE
https://ecampus.estp.fr/resources/show/claroline_announcement_aggregate/338d4f7d-0095-45f0-b4a6-3d25d7f02da4#/

**Comment by ngodfraind** [comment]
merci

**Comment by ngodfraind** [comment]
Reproduit
