### ISSUE TITLE
Création Espaces d'Activités impossible

### ISSUE THREAD

**Issue by Sarcasthik** [claroline/Distribution#5328]
| Q             | A
| ------------- | ---
| Bug report?   | maybe ?
| Version?      | 12.2.7.

Bonjour, 

j'ai suivi le tuto pour l'installation from scratch sans trop de souci, tout s'est bien passé j'ai pu créé mon premier utilisateur admin et me connecter sur la plateforme pour tester. 

Je rencontre deux soucis dont un majeur lors de son utilisation : 
 - quand je créer un utilisateur j'ai un message d'erreur
![image](https://user-images.githubusercontent.com/43416863/50453863-f175d180-0943-11e9-8e96-5b0af030cfbb.png)
Pour autant, l'utilisateur est bien créé, tout comme son espace perso

 - quand je souhaite créer un espace d'activité j'ai aussi une erreur
![image](https://user-images.githubusercontent.com/43416863/50453714-ecfce900-0942-11e9-8119-8301813604e8.png)
Par contre cette fois, l'espace n'est pas créé, quoi que je fasse l'erreur apparaît. Je peux cependant supprimer un espace personnel sans problème..

J'ai eu beau fouiller partout je ne trouve pas la solution à mon problème qui est sans doute pas très compliquée, enfin je l'espère ^^ Si besoin je peux fournir un accès à la plateforme 

D'avance merci à qui prendra le temps de m'éclairer de ses lumières !

EDIT : j'ai oublié de mentionner une erreur aussi lors de la création du premier admin, peut-être est-ce lié..
![image](https://user-images.githubusercontent.com/43416863/50458513-ef236f80-0963-11e9-9b71-8b63d9d4e77f.png)

**Comment by LaurentGruber** [comment]
dans app/logs/ il y a bien un dossier workspace et un transfert avec les droits en écriture dessus  ?

**Comment by Sarcasthik** [comment]
Non le dossier app/logs/ contient seulement deux fichiers "console.log" et "prod.log"..

**Comment by LaurentGruber** [comment]
il faut donc créer les répertoires et donner les droits en écriture au serveur web dessus.

**Comment by Sarcasthik** [comment]
Après avoir créé les répertoires "workspace" et "transfert" dans app/logs/ avec les droits en écriture/lecture, le problème persiste malheureusement.. voici le error.log d'apache de mes essais de ce matin si ça peut aider : 

[Wed Jan 02 10:22:36.044077 2019] [mpm_prefork:notice] [pid 6654] AH00169: caught SIGTERM, shutting down
[Wed Jan 02 10:22:37.052958 2019] [mpm_prefork:notice] [pid 25678] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Wed Jan 02 10:22:37.053018 2019] [core:notice] [pid 25678] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jan 02 10:23:49.775181 2019] [php7:warn] [pid 25706] [client 193.248.52.50:59335] PHP Warning:  file_get_contents(/var/www/claroline/Claroline/app/logs/workspace/01.json): failed to open stream: No such file or directory in /var/www/claroline/Claroline/vendor/claroline/distribution/main/core/Controller/APINew/LoggerController.php on line 43, referer: http://claroline.sarcasthik.ovh/admin/open/workspace_management
[Wed Jan 02 10:24:15.940196 2019] [mpm_prefork:notice] [pid 25678] AH00169: caught SIGTERM, shutting down
[Wed Jan 02 10:24:16.098070 2019] [mpm_prefork:notice] [pid 25741] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Wed Jan 02 10:24:16.098117 2019] [core:notice] [pid 25741] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jan 02 10:24:48.574950 2019] [php7:warn] [pid 25745] [client 193.248.52.50:59348] PHP Warning:  file_get_contents(/var/www/claroline/Claroline/app/logs/workspace/01.json): failed to open stream: No such file or directory in /var/www/claroline/Claroline/vendor/claroline/distribution/main/core/Controller/APINew/LoggerController.php on line 43, referer: http://claroline.sarcasthik.ovh/admin/open/workspace_management
[Wed Jan 02 10:25:02.279027 2019] [mpm_prefork:notice] [pid 25741] AH00169: caught SIGTERM, shutting down
[Wed Jan 02 10:25:02.450947 2019] [mpm_prefork:notice] [pid 25781] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Wed Jan 02 10:25:02.451009 2019] [core:notice] [pid 25781] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jan 02 10:26:07.411939 2019] [mpm_prefork:notice] [pid 25781] AH00169: caught SIGTERM, shutting down
[Wed Jan 02 10:26:07.549881 2019] [mpm_prefork:notice] [pid 25830] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Wed Jan 02 10:26:07.549923 2019] [core:notice] [pid 25830] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jan 02 10:26:10.205579 2019] [mpm_prefork:notice] [pid 25830] AH00169: caught SIGTERM, shutting down
[Wed Jan 02 10:26:10.340701 2019] [mpm_prefork:notice] [pid 25848] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Wed Jan 02 10:26:10.340744 2019] [core:notice] [pid 25848] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jan 02 10:26:18.861419 2019] [php7:warn] [pid 25849] [client 193.248.52.50:59368] PHP Warning:  SessionHandler::read(): Session data file is not created by your uid in /var/www/claroline/Claroline/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 59
[Wed Jan 02 10:26:19.827836 2019] [php7:warn] [pid 25849] [client 193.248.52.50:59368] PHP Warning:  session_write_close(): Failed to write session data with Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\NativeFileSessionHandler handler in /var/www/claroline/Claroline/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 254
[Wed Jan 02 10:26:20.344189 2019] [php7:warn] [pid 25852] [client 193.248.52.50:59370] PHP Warning:  SessionHandler::read(): Session data file is not created by your uid in /var/www/claroline/Claroline/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 59, referer: http://claroline.sarcasthik.ovh/
[Wed Jan 02 10:26:20.402230 2019] [php7:warn] [pid 25852] [client 193.248.52.50:59370] PHP Warning:  session_write_close(): Failed to write session data with Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\NativeFileSessionHandler handler in /var/www/claroline/Claroline/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 254, referer: http://claroline.sarcasthik.ovh/
[Wed Jan 02 10:26:23.338963 2019] [php7:warn] [pid 25857] [client 193.248.52.50:59380] PHP Warning:  SessionHandler::read(): Session data file is not created by your uid in /var/www/claroline/Claroline/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 59, referer: http://claroline.sarcasthik.ovh/
[Wed Jan 02 10:26:23.736886 2019] [php7:warn] [pid 25857] [client 193.248.52.50:59380] PHP Warning:  session_write_close(): Failed to write session data with Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\NativeFileSessionHandler handler in /var/www/claroline/Claroline/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 254, referer: http://claroline.sarcasthik.ovh/
[Wed Jan 02 10:26:24.173981 2019] [php7:warn] [pid 25849] [client 193.248.52.50:59381] PHP Warning:  SessionHandler::read(): Session data file is not created by your uid in /var/www/claroline/Claroline/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 59, referer: http://claroline.sarcasthik.ovh/login
[Wed Jan 02 10:26:24.218985 2019] [php7:warn] [pid 25849] [client 193.248.52.50:59381] PHP Warning:  session_write_close(): Failed to write session data with Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\NativeFileSessionHandler handler in /var/www/claroline/Claroline/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php on line 254, referer: http://claroline.sarcasthik.ovh/login
[Wed Jan 02 10:26:31.853751 2019] [php7:warn] [pid 25853] [client 193.248.52.50:59383] PHP Warning:  SessionHandler::read(): Session data file is not created by your uid in /var/www/claroline/Claroline/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 59, referer: http://claroline.sarcasthik.ovh/login
[Wed Jan 02 10:26:54.246055 2019] [php7:warn] [pid 25853] [client 193.248.52.50:59402] PHP Warning:  file_get_contents(/var/www/claroline/Claroline/app/logs/workspace/02.json): failed to open stream: No such file or directory in /var/www/claroline/Claroline/vendor/claroline/distribution/main/core/Controller/APINew/LoggerController.php on line 43, referer: http://claroline.sarcasthik.ovh/admin/open/workspace_management
[Wed Jan 02 10:29:27.049354 2019] [mpm_prefork:notice] [pid 25848] AH00169: caught SIGTERM, shutting down
[Wed Jan 02 10:29:27.212910 2019] [mpm_prefork:notice] [pid 25986] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Wed Jan 02 10:29:27.212954 2019] [core:notice] [pid 25986] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jan 02 10:30:42.543568 2019] [php7:warn] [pid 26011] [client 193.248.52.50:59443] PHP Warning:  file_get_contents(/var/www/claroline/Claroline/app/logs/workspace/03.json): failed to open stream: No such file or directory in /var/www/claroline/Claroline/vendor/claroline/distribution/main/core/Controller/APINew/LoggerController.php on line 43, referer: http://claroline.sarcasthik.ovh/admin/open/workspace_management
[Wed Jan 02 12:45:48.373037 2019] [mpm_prefork:notice] [pid 25986] AH00169: caught SIGTERM, shutting down
[Wed Jan 02 12:48:19.139753 2019] [mpm_prefork:notice] [pid 1222] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Wed Jan 02 12:48:19.173063 2019] [core:notice] [pid 1222] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jan 02 13:00:42.557031 2019] [php7:warn] [pid 2149] [client 192.168.1.52:50486] PHP Warning:  file_get_contents(/var/www/claroline/Claroline/app/logs/workspace/undefined.json): failed to open stream: No such file or directory in /var/www/claroline/Claroline/vendor/claroline/distribution/main/core/Controller/APINew/LoggerController.php on line 43, referer: http://claroline.sarcasthik.ovh/admin/open/workspace_management
[Wed Jan 02 13:23:38.384142 2019] [php7:warn] [pid 2149] [client 192.168.1.52:50568] PHP Warning:  file_get_contents(/var/www/claroline/Claroline/app/logs/workspace/a1.json): failed to open stream: No such file or directory in /var/www/claroline/Claroline/vendor/claroline/distribution/main/core/Controller/APINew/LoggerController.php on line 43, referer: http://claroline.sarcasthik.ovh/admin/open/workspace_management
[Wed Jan 02 13:26:05.895695 2019] [php7:warn] [pid 1345] [client 192.168.1.52:50592] PHP Warning:  file_get_contents(/var/www/claroline/Claroline/app/logs/workspace/a1.json): failed to open stream: No such file or directory in /var/www/claroline/Claroline/vendor/claroline/distribution/main/core/Controller/APINew/LoggerController.php on line 43, referer: http://claroline.sarcasthik.ovh/admin/open/workspace_management
[Wed Jan 02 13:26:06.894629 2019] [php7:warn] [pid 1342] [client 192.168.1.52:50593] PHP Warning:  file_get_contents(/var/www/claroline/Claroline/app/logs/workspace/a1.json): failed to open stream: No such file or directory in /var/www/claroline/Claroline/vendor/claroline/distribution/main/core/Controller/APINew/LoggerController.php on line 43, referer: http://claroline.sarcasthik.ovh/admin/open/workspace_management
[Wed Jan 02 13:26:06.913699 2019] [php7:warn] [pid 2158] [client 192.168.1.52:50594] PHP Warning:  file_get_contents(/var/www/claroline/Claroline/app/logs/workspace/a1.json): failed to open stream: No such file or directory in /var/www/claroline/Claroline/vendor/claroline/distribution/main/core/Controller/APINew/LoggerController.php on line 43, referer: http://claroline.sarcasthik.ovh/admin/open/workspace_management
[Wed Jan 02 13:27:53.168632 2019] [php7:warn] [pid 1346] [client 192.168.1.52:50605] PHP Warning:  file_get_contents(/var/www/claroline/Claroline/app/logs/workspace/h.json): failed to open stream: No such file or directory in /var/www/claroline/Claroline/vendor/claroline/distribution/main/core/Controller/APINew/LoggerController.php on line 43, referer: http://claroline.sarcasthik.ovh/admin/open/workspace_management

**Comment by LaurentGruber** [comment]
il n'arrive pas à créer de fichier dans le dossier, c'est un problème de droit sur le serveur

**Comment by Sarcasthik** [comment]
Pour information, le problème venait seulement du fait que "Organisation principale (optionnel)" n'était pas défini sur 'default' dans le profil utilisateur : 

![image](https://user-images.githubusercontent.com/43416863/51489458-a87d3580-1da8-11e9-873c-fe7fa1cf1a6c.png)

J'espère que ça en aidera d'autres.

**Comment by txomin666** [comment]
Merci à toi.
En effet ça m'aide vraiment, car j'avais laissé tombé puisque le thread avait été sèchement clos alors que non résolu (je précise par rapport à la dernière réponse que les droits sur le système de fichiers était bons).
Merci encore.

**Comment by txomin666** [comment]
Bonjour,
Je tente une install fraîche et je vois que TOUS les bugs rapportés dans ce thread ont été corrigés : 
- php app/console claroline:user:create -a qui s'éxécute sans messahe d'erreur (1er message)
- création du répertoire app/log/workspace (pas transfert mais à priori ça marche bien sans)
- possibilité de créer un EA sans le workaround du message précédent.
Merci aux devs :-) !

**Comment by txomin666** [comment]
Bonjour,
Je tente une install fraîche et je vois que TOUS les bugs rapportés dans ce thread ont été corrigés :

    php app/console claroline:user:create -a qui s'éxécute sans messahe d'erreur (1er message)
    création du répertoire app/log/workspace (pas transfert mais à priori ça marche bien sans)
    possibilité de créer un EA sans le workaround du message précédent.
    Merci aux devs :-) !

**Comment by Sarcasthik** [comment]
Bien ! On pourrait croire que ça aura été utile ce thread, cela dit ça me rend pas mes heures de bidouillage des droits sur ces fameux dossiers et autres configurations alors que tout était bon.

Je vais tenter la même chose de mon côté histoire de confirmer ça. 

Merci pour l'info !
