### ISSUE TITLE
Explorateur de ressources : Erreur lors de la copie d'un dossier

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5343]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.2.5

Lorsque j'essaye de copier un dossier contenant des ressources vers un autre espace j'obtiens une erreur [Syntax Error] line 0, col 257: Error: Expected Literal, got 'AND'

Pas de problème quand je copie une seule ressource à la fois, ni quand je copie plusieurs ressources à la fois.

![image](https://user-images.githubusercontent.com/35995165/50772641-c6b64200-128e-11e9-9106-db20027035a5.png)

**Comment by LaurentGruber** [comment]
non reproduit
