### ISSUE TITLE
Agenda - Echec création événement

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#5346]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      | 12.2.5

Je n'arrive plus à créer un événement dans l'agenda d'un EA.
![image](https://user-images.githubusercontent.com/33163723/50819040-2e20d000-1329-11e9-9d7e-2b9e81d858c6.png)

**Comment by LaurentGruber** [comment]
"A new entity was found through the relationship \u0027Claroline\\CoreBundle\\Entity\\Workspace\\Workspace#defaultRole\u0027 that was not configured to cascade persist operations for entity: []ROLE_COLLABORATOR. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={\u0022persist\u0022})."

**Comment by ngodfraind** [comment]
J'ai vu ou ça n'allait pas dans le code, reste à trouver comment corriger (y a le ws qui essaye de se mettre à jour avec le role par défaut et on en veut pas).

**Comment by ngodfraind** [comment]
J'ai déjà mit le fix sur le serveur.

**Comment by npaille** [comment]
Merci ! Tout refonctionne.
Nathalie
