### ISSUE TITLE
[ExoBundle] Terminologie

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#535]
Propositions : 

Dans les étapes, remplacer "Valider l'étape" par "Valider" (ou "Valider les réponses")
Dans l’exercice, remplacer "Essai" et "Correction" par "Tentative" (pour réserver le terme essai aux étapes

![image](https://cloud.githubusercontent.com/assets/16414632/15756903/90c7b056-2903-11e6-9fe9-c5185d0cec74.png)

**Comment by eldoniel** [comment]
Je n'ai pas compris pour "Correction".

**Comment by jj-quintin** [comment]
Lors de l'accès à une copie on affiche "Correction" n°x pour signifier "Tentative n°x (Correction)" je suppose (si le terme tentative vous convient, de manière à distinguer essai (niveau étape) et tentative (niveau exercice). Je place que ce serait plus clair pour les enseignants et les étudiants


![image](https://cloud.githubusercontent.com/assets/16414632/15777040/b59dee8e-298c-11e6-9770-912eb92c913c.png)

**Comment by jj-quintin** [comment]
Même si on affiche "Tentative n°x (Correction)" ?
