### ISSUE TITLE
Création d'évènement : Erreur

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5353]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.2.5

A la création d'un évèment dans l'agenda du workspace ici : https://w-alter.mfr.asso.fr/workspaces/2205/open/tool/agenda_#/

L'erreur renvoie : 

A new entity was found through the relationship 'Claroline\CoreBundle\Entity\Workspace\Workspace#defaultRole' that was not configured to cascade persist operations for entity: []ROLE_@MFR.ASSO.FR. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).

J'ai déjà eu cette erreur à d'autres endroit, avec le même rôle cité.
A priori il y a eu des bugfix dans la version à venir ce soir, donc je referais un test demain pour voir si ça persite.

**Comment by LaurentGruber** [comment]
duplicate et déjà corrigé (dans la maj de hier)
