### ISSUE TITLE
URGENT Forum echec de réponse au sujet

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5355]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.2.10

Bonjour,

J'ai reproduit plusieurs fois sous plusieurs rôles, dans plusieurs forums l'échec de réponse à un sujet.
Ce problème bloque totalement les forums.
![image](https://user-images.githubusercontent.com/24249636/50959803-1598ed00-14c4-11e9-8bbd-98d9e56549c0.png)

Merci de votre attention.

**Comment by jbbrosset** [comment]
Détails de l'erreur quand on essaye de répondre en étant connecté en admin sur la plateforme (mais sont inscription sur l'espace en question) : 
*"An exception occurred while executing 'INSERT INTO claro_tagbundle_tagged_object (object_id, object_class, object_name, tag_id) VALUES (?, ?, ?, ?)' with params ["f5c4a093-f63e-4600-bff8-acd60e3ea8c5", "Claroline\\ForumBundle\\Entity\\Subject", "TEST JSD connect\u00e9 en tant que collaborateur", 1328]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'f5c4a093-f63e-4600-bff8-acd60e3ea8c5-Claroline\ForumBundle\Entit' for key 'unique'"*

**Comment by jbbrosset** [comment]
Si j'essaye de répondre en étant connecté "en tant que collaborateur de l’espace"

Uncaught Error: Container ".app-header-container" for app can not be found.
    at app.3d51609875a6dbcf3a59.js:1
    at a (app.3d51609875a6dbcf3a59.js:1)
    at Module.Gi0Y (claroline-distribution-main-app-header.1fdcb36b784942defc9d.js:1)
    at t (runtime.82aec39b667bace1a035.js:1)
    at c (runtime.82aec39b667bace1a035.js:1)
    at Array.a [as push] (runtime.82aec39b667bace1a035.js:1)
    at claroline-distribution-main-app-header.1fdcb36b784942defc9d.js:1
/forum/apiv2/forum_subject/f5c4a093-f63e-4600-bff8-acd60e3ea8c5/message:1 

Failed to load resource: the server responded with a status of 500 (Internal Server Error) home#/tab/d49187dd-9298-469e-8cf5-fc9b848f5d19:1 
Uncaught (in promise)
message : An exception occurred while executing 'INSERT INTO claro_tagbundle_tagged_object (object_id, object_class, object_name, tag_id) VALUES (?, ?, ?, ?)' with params ["f5c4a093-f63e-4600-bff8-acd60e3ea8c5", "Claroline\\ForumBundle\\Entity\\Subject", "TEST JSD connect\u00e9 en tant que collaborateur", 1328]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'f5c4a093-f63e-4600-bff8-acd60e3ea8c5-Claroline\ForumBundle\Entit' for key 'unique'

**Comment by LaurentGruber** [comment]
Il semble y avoir le même problème sur le blog : 
"An exception occurred while executing \u0027INSERT INTO claro_tagbundle_tagged_object (object_id, object_class, object_name, tag_id) VALUES (?, ?, ?, ?)\u0027 with params [\u0022dbe6146b-4699-4a81-8f01-726f629f0475\u0022, \u0022Icap\\\\BlogBundle\\\\Entity\\\\Post\u0022, \u0022Claroline Version 12\u0022, 1]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry \u0027dbe6146b-4699-4a81-8f01-726f629f0475-Icap\\BlogBundle\\Entity\\Post\u0027 for key \u0027unique\u0027"

**Comment by ngodfraind** [comment]
Reproduit en local.
