### ISSUE TITLE
Espace dupliqué et rôle manager

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5367]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.2.11

J'ai un espace d'activités qui est une copie d'un autre dans lequel il y avait des équipes.
Dans la copie, les équipes n'ont pas été dupliquées mais les rôles oui.
La suppression des rôles "manager" est impossible et ne peut pas être contournée.
![image](https://user-images.githubusercontent.com/24249636/51115196-d2ae8080-1807-11e9-999c-e0e627a3c94c.png)

Je vous remercie.

**Comment by ngodfraind** [comment]
Reproduit.
