### ISSUE TITLE
[ExoBundle] Vue d'ensemble-Informations supplémentaires

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#537]
Proposition : 

En version formative du moins, placer toutes les informations du tableau dans les informations supplémentaires pour ne garder que la description de l’exercice et ce qui se trouve sous le tableau

![image](https://cloud.githubusercontent.com/assets/16414632/15757186/ad9eaf44-2904-11e6-9519-dee8618657c1.png)

**Comment by pitrackster** [comment]
- Hide all informations by default for all exercise type
- Change button label to "display details"

**Comment by Pauooo** [comment]
When metadata_visible is checked, it display a table with the info of the exercise in the overview.
This table has a third column "visible in player" with radio button. 
If the radio button is checked, the info will be visible in the table of the player. 
The default choices depends on the exercise type (formative, evaluative, summative).
The admin can change and choose which info he wants to display.

**Comment by Pauooo** [comment]
- if metadata_visible is checked (in exercise parameters), the overview (admin mode) display a table with some of the parameters of the exercise. (some are hidden and some are visible by default)
- if not all parameters will be hidden in the admin and player view 
- each exercise type has default param visibility values
- in the admin exercise overview you will be able to check any param you want to display or uncheck those you want to hide
- all checked params will be visible in the player and in the admin view
- all unchecked params will not

**Comment by LaurentGruber** [comment]
done
