### ISSUE TITLE
SCORM : Unable to create Directory

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5371]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.2.11

Le scorm est en version 2004 2nd édition, on obtient le même message en 3ème et 4ème édition ainsi qu'en 1.2.
L'erreur intervient au moment de l'upload.
"Unable to create the "/home/mfr/www/app/../files/scorm/5c251fa455bc02.19585692" directory"

![image](https://user-images.githubusercontent.com/35995165/51168418-8156cd80-18a9-11e9-9718-3b1594b97ba9.png)

**Comment by LaurentGruber** [comment]
c'est corrigé direct sur le serveur, tu peux retester ?

**Comment by jbbrosset** [comment]
J'ai réussi à uploader le fichier. 
J'ouvre le SCORM et j'arrive à le suivre.

Par contre il m'affiche les mêmes résultats quel que soit mon niveau de progression dans le scorm (mais la je suis pas sur que ce soit de la faute de la plateforme parce que ce n'est pas moi qui ai produit le scorm en question)
