### ISSUE TITLE
Questionnaire : Impossible d'ajouter une question (erreur 500)

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5376]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.2.11

![image](https://user-images.githubusercontent.com/35995165/51245024-dc122700-1986-11e9-8956-cc724c54f9f3.png)

J'essaye d'ajouter une question texte à trou, à la base la volonté était de transformer une question "Texte à trou" simple en proposant plutôt une liste de réponses.
J'ai essayé plusieurs méthodes pour ajouter la question et à chaque fois j'ai ce message d'erreur : 
```
"An exception occurred while executing 'INSERT INTO ujm_interaction_hole (htmlWithoutValue, question_id) VALUES (?, ?)':
SQLSTATE[HY093]: Invalid parameter number: no parameters were bound"
```

Visible ici : https://w-alter.mfr.asso.fr/resources/show/ujm_exercise/3b9c4067-c83b-4e8c-832c-054ab33563ef#/

Quand j'essaye d'insérer une question QCM standard, une question ouverte ...... : 
```
"An exception occurred while executing 'INSERT INTO ujm_interaction_qcm (multiple, numbering, shuffle, question_id) VALUES (?, ?, ?, ?)':
SQLSTATE[HY093]: Invalid parameter number: no parameters were bound"
```

**Comment by jbbrosset** [comment]
Après copie de la ressource les paramètres semblent être pris en compte.
Contournement trouvé donc.

Mais ce questionnaire en particulier à déjà rencontré des problèmes similaires et à déjà été dupliqué pour résoudre...
Si A chaque modification on doit dupliquer la ressource ça va devenir compliqué.

**Comment by jbbrosset** [comment]
Pour Info, le même problème (avec la même erreur) apparait ici lorsqu'on souhaite ajouter des questions : https://w-alter.mfr.asso.fr/resources/show/ujm_exercise/03482808-bd55-48f4-9a7c-5e1dd18f6e03#/

- Je viens hélas de reproduire le bug avec cet exercice: https://w-alter.mfr.asso.fr/resources/show/ujm_exercise/db1fa03b-8acf-4946-a5e0-28d36b7950f6#/
La manip que je veux faire consiste à modifier un texte à trous en proposant une liste de réponses et non une réponse libre. La sauvegarde se fait mais l'exercice n'est pas modifié. Il faut le copier pour voir apparaître la modification. C'est très pénible. J'ai aussi ajouté des mots clés à d'autres endroits, du coup je ne sais pas si ça a marché.
- Autre bug: on ne peut plus avoir la réponse attendue sur les exercices d'association, rien ne s'affiche. Vous pouvez essayer avec le même exercice qu'au dessus.
- Enfin, il y a toujours le problème de la taille des trous (https://github.com/claroline/Distribution/issues/5298). C'est surtout gênant au moment de la correction, car la réponse attendue ne s'affiche pas correctement. Du coup les apprenants n'ont pas la réponse complète et ne comprennent pas leur erreur.

**Comment by jbbrosset** [comment]
Selon mes premiers tests : 
Résolu : 
- La modification / ajout de question fonctionne sans erreur (passage de remplissage de trous à liste de choix)
- La taille des trous semble bien prise en compte, la réponse attendu s'affiche bien.

Non résolu à ce jour : 
"Autre bug: on ne peut plus avoir la réponse attendue sur les exercices d'association, rien ne s'affiche. Tu peux essayer avec le même exercice qu'au dessus."

**Comment by ngodfraind** [comment]
C'est en cours. Je l'ai pas encore reproduis en local par contre =/.

**Comment by ngodfraind** [comment]
Je vois tout dans l'exo d'association.
![assoc](https://user-images.githubusercontent.com/1397430/51322212-14883280-1a65-11e9-8d58-a2010de0d621.png)

C'est ici ou ailleurs ? J'suis un peu perdu.

**Comment by jbbrosset** [comment]
Moi j'arrive pas à l'afficher.... 
![image](https://user-images.githubusercontent.com/35995165/51322796-bbb99980-1a66-11e9-831b-e2157dd55404.png)

Quand je clique sur l'onglet "Réponse attendue" rien ne se passe (Chrome 71.0.3578.98)

**Comment by jbbrosset** [comment]
Oh .... si je ne fais AUCUNE association, j'arrive à l'afficher.
Mais c'est pas fini, si je fais toutes les associations en erreur (j'ai lié les items directement les uns en face des autres) alors il m'affiche UNIQUEMENT les réponses attendues mais pas "Mes réponses"
