### ISSUE TITLE
Improvement-Ergonomy : Easier selection of user for userlist in WS to delete role

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#538]
A workspace manager registers several list of users (say 3 list of 50 user per course : first year, second year and third year students) in a WS. 
When the course is done for some user (third year) won't have access to this WS, so the ws manager has to remove those 50 students.
He has to uncheck the role collaborator for every user (50 out 150)
This is more than tedious. There is no (gui) tool to batch remove 

I see several way of making this easier : 
1 - filter for specific field in student profile (ex : administrative code, or any facet) 
then have a checkbox before each user + a "select all" checkbox => the manager check it
then have a button : "remove roles for these"
2 - if the filter is overkill, at least have a checkbox before each student + a select all 
and a js enhancement like [this checkbox drag select](http://cross-browser.com/x/examples/clickndrag_checkboxes.php), to avoid having to click

**Comment by Elorfin** [comment]
fixed with new management tool.
