### ISSUE TITLE
URGENT - Configuration EA : comment desactiver globalement "auto-inscription"?

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5389]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.2.11

Bonjour,
tout est dans le titre : un utilisateur peut créer un espace avec la possibilité de créer un compte automatiquement à la personne qui utilise le lien qui mène à l'espace.
La création d'un compte utilisateur est censée être limitée aux utilisateurs ayant des droits (un rôle) d'administration/gestion des utilisateurs.
Ca va vite devenir ingérable.

Est-il donc possible de désactiver cette option pour tous les espaces ?
Je n'ai pas trouvé comment faire.

Merci de votre attention.

**Comment by jbbrosset** [comment]
La fonction existe il semblerait, mais le paramètre de l'EA supplante celui défini au niveau global de la plateforme ?
![image](https://user-images.githubusercontent.com/35995165/51540493-dae56c00-1e56-11e9-918d-3409a4d10f44.png)

**Comment by ngodfraind** [comment]
C'est possible que le param de l'EA le supplante mais je pense que ça ne devrait pas être le cas. Je regarde.
