### ISSUE TITLE
Widget Liste de ressource : Non fonctionnel si dossier parent hors de l'EA

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5390]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.2.11

Le widget "Liste de ressource" ne renvoie aucun résultat si il est paramétré pour filtrer les fichier d'un dossier parents appartenant à un autre EA.
Ci dessous à gauche : j'affiche bien le contenu d'un dossier de l'EA ou le Widget se trouve, à gauche : même config sauf que le "Parent" est situé dans un autre EA.
![image](https://user-images.githubusercontent.com/35995165/51539152-92787f00-1e53-11e9-96f7-54d6c6f6778a.png)

Par contre je sélectionne "Afficher une ressource" et que je sélectionne les dossier, le widget me renvoi bien leur contenu dans les deux cas.
![image](https://user-images.githubusercontent.com/35995165/51539363-17639880-1e54-11e9-9257-307fb4097eab.png)

**Comment by ngodfraind** [comment]
Reproduit.
