### ISSUE TITLE
Widget Liste Message Forum : Filtre par sujet non fonctionnel

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5393]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.2.11

Le filtre sur un terme contenu dans le sujet n'est pas pris en compte dans l'affichage du widget.
J'ai testé sans activer le champ de recherche et avec ça ne change rien.
![image](https://user-images.githubusercontent.com/35995165/51600706-de363180-1f02-11e9-8836-e7c9b9f67de5.png)

Au sein même du forum par contre, j'arrive à faire une recherche et appliquer un filtre mais le titre du champs sur lequel porte la recherche n'est pas le même ("Titre" et plus "Sujet")
![image](https://user-images.githubusercontent.com/35995165/51600801-1b022880-1f03-11e9-97f0-1094736f4271.png)

**Comment by ngodfraind** [comment]
Corrigé sur #5413 (je crois)
