### ISSUE TITLE
Questionnaire : Erreurs de Duplication, déplacement ou création de question

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5397]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.2.11

Bonjour,

J'ai constaté un bug que j'ai reproduit plusieurs fois dans un questionnaire.
Lorsque l'on duplique ou déplace une question vers une étape plusieurs fois d'affilée, si on tente d'enregistrer il y a un bandeau rouge d'erreur.

Le contournement est simple, il faut sauvegarder successivement après chaque duplication ou déplacement de question. Ca peut être bloquant et faire peur si on ne le sait pas...

Merci.

**Comment by WalterMFR** [comment]
Attention, je rencontre de plus un bug similaire très bloquant qui a peut être déjà été signalé mais que j'arrive à contourner.

Lorsque je créé une question sur une étape qui n'est pas en dernière position, je ne peux pas non plus enregistrer.
Par exemple : 
J'ai 2 étapes avec chacune 2 questions.
Je veux rajouter une question à l'étape 1 mais je ne peux pas enregistrer.

Si je rajoute une question à l'étape 2 (qui est à la fin) je peux maintenant enregistrer.
Après je contourne en déplacant la question vers l'étape de mon choix.

C'est très tordu mais ca marche...

**Comment by LaurentGruber** [comment]
duplicate
