### ISSUE TITLE
BLOQUANT | Organisation principale et création de WS

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5399]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.2.12

Les comptes users sont créés depuis notre BDD de mails pro hébergés par la société Wangarden. L'API ne leur permet pas d'affecter d'organisation principale à la création de compte. Les users ont donc 2 organisations mais rien dans le champ MainOrganization.

Jusqu'ici ça ne posais pas trop de problème, j'attend un échange avec eux pour faire un fix global sur tous les users mais il n'y avait rien d'urgent. Le champs MainOrganization est censé être optionnel CEPENDANT s'il est vide l'user ne peux pas créer de WS.
*(temp1
"Type error: Argument 1 passed to Claroline\CoreBundle\Entity\Workspace\Workspace::addOrganization() must be an instance of Claroline\CoreBundle\Entity\Organization\Organization, null given, called in /home/mfr/www/vendor/claroline/distribution/main/core/API/Crud/WorkspaceCrud.php on line 82"
temp2
"The Response content must be a string or object implementing __toString(), "boolean" given.")*

Dans les cas ou ça arrivait, j'ajoutais manuellement une MainOrganization à l'utilisateur en question. Solution temporaire évidement.

MAIS, depuis la 12.2.12, le paramètre d'Organisation Principale n'est plus gardé en mémoire !
J'ajoute une Orga, je valide, le bandeau vert apparaît me signalant que tout s'est bien passé... Mais si je quitte et reviens sur l'utilisateur il n'a pas d'Organisation Principale.

Ce bug à pour effet direct d’empêcher TOUS mes nouveaux utilisateurs de créer un WS.

**Comment by ngodfraind** [comment]
J'ai refait une install fraiche et j'ai toujours mon orga principale par défaut. Je peux également la changer.
Je vais voir sur le serveur.

**Comment by ngodfraind** [comment]
En revanche j'ai pu reproduire sur la plateforme.
