### ISSUE TITLE
Page de gestion de plugin

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#54]
_From @LaurentGruber on March 30, 2016 7:41_

- [ ] Permettre de désactiver un plugin en le mettant à false dans le bundle.ini
- [ ] Permettre cette opération depuis une page de gestion de plugin
- [ ] Permettre l'accès aux options des plugins depuis la même page

_Copied from original issue: claroline/Claroline#734_

**Comment by ngodfraind** [comment]
Fixed by #125.
