### ISSUE TITLE
[ExoBundle] Afficher les statistiques

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#540]
J'ai sélectionné dans les paramètres de l'exercice "Afficher les statistiques" à la fin du "test"

Mais ne les ai pas obtenus (après la dernière étape, la seule possibilité est de cliquer sur Terminer , avec pour effet d'être orienté vers la page d'accueil de l'exercice)

![image](https://cloud.githubusercontent.com/assets/16414632/15757568/753158da-2906-11e6-9b24-c070daa7817f.png)

**Comment by Elorfin** [comment]
Les statistiques sont intégrées dans l'affichage des corrections. 
Ce n'est pas une vue à part entière.

D'après ta configuration, tu aura accès aux stats quand tu auras fini ton 5ème essai.
