### ISSUE TITLE
Questionnaire : Appariement > afficher les outils > page blanche 

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5401]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.2.12

![image](https://user-images.githubusercontent.com/24249636/51669488-e35bb500-1fc4-11e9-94e9-d2a64c601796.png)
Bonjour,
lorsque l'on créé une question de type "appariement", si l'on appuie sur le bouton "+" pour accéder au texte riche, ça plante avec une page blanche.
Je n'ai pas trouvé de contournement.
Je vous remercie.

**Comment by ngodfraind** [comment]
Pas pu reproduire en local, j'essaye sur le serveur.
