### ISSUE TITLE
[ExoBundle]Paramètre-Adaptation en fonction du type (formatif etc.)

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#541]
Amélioration suggérée : 

Adapter les paramètres proposés en fonction du type (c'était l'idée de départ, tous les paramètres n'étant pas utiles pour tous les types)

![image](https://cloud.githubusercontent.com/assets/16414632/15757648/f125ead2-2906-11e6-8ac4-2a75b2507944.png)

**Comment by eldoniel** [comment]
Il faudrait nous dire quels paramètres seraient à retirer pour quels types.

**Comment by jj-quintin** [comment]
Si on est d'accord sur le principe, on le fera, après discussion et en fonction de la milestone. Dès qu'on a le feu vert, on s'y penche

**Comment by Pauooo** [comment]
To connect with #898

**Comment by Pauooo** [comment]
Added to #898
