### ISSUE TITLE
[FYI] Ressource Vidéo : Affichage et lecture sous Safari non fonctionnel

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5417]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.1.14

Pour info (absolument pas urgent de notre côté) 
Le lecteur vidéo interne à la plateforme ne fonctionne pas sous Safari.
![image](https://user-images.githubusercontent.com/35995165/52044942-a3a44880-2543-11e9-91f4-e52dbe2391c0.png)

Page Blanche que ce soit dans un widget ou directement dans les ressources

**Comment by Elorfin** [comment]
On a réglé le problème.
