### ISSUE TITLE
[ExoBundle] Paramètres-Terminologie

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#542]
Propositions

Remplacer : 

- **Définition de l’exercice** par **Vue d'ensemble**  
- **Questions** par **Tirage aléatoire** 
- **Ordre des questions aléatoires** par **Ordre aléatoire des étapes** (il me semble que suite à notre discussion à ce propos, il s'agissait plutôt des étapes et non plus des questions)
- Dans le titre de la rubrique "**A la fin du test**" par "**Résultats**"
- Adapter idéalement en fonction du type, pour le formatif : **Disponibilité de la correction** par **Affichage de la solution** (mais ce paramètre ne me semble pas utile en formatif)
- **Disponibilité de la note** par **Affichage du score**
- **Passage** par **Passation**
- **Sortie du test** par **Permettre d'interrompre l'exercice**
- **Nombre d'essai maximum** par **Nombre de tentative maximum**
- **Verrouiller le test** par **Verrouiller l’exercice**

![image](https://cloud.githubusercontent.com/assets/16414632/15757731/4f3b25f6-2907-11e6-8cfc-8c1a4013714b.png)

**Comment by eldoniel** [comment]
@UJM-dev @david42 @charlotte42 @marion42  Êtes-vous d'accord avec ces modifs?

**Comment by LaurentGruber** [comment]
fermé en faveur de #811
