### ISSUE TITLE
Ressource JPEG export impossible

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5420]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.2.14

Bonjour,

J'ai certaines ressources, en fichier JPEG que je n'arrive pas à exporter même en administrateur.
Les droits d'accès en export sont biens cochés.
lien : https://w-alter.mfr.asso.fr/resources/show/file/bfad4ba3-047c-4a8b-9d3d-35a03b9b8317#/
Quand j'appuie sur exporter j'ai un message d'erreur : 

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 

Merci de votre attention.

**Comment by ngodfraind** [comment]
```[2019-01-31 16:11:01] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The filename and the fallback cannot contain the "/" and "\" characters." at /home/mfr/www/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/ResponseHeaderBag.php line 290 {"exception":"[object] (InvalidArgumentException(code: 0): The filename and the fallback cannot contain the \"/\" and \"\\\" characters. at /home/mfr/www/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/ResponseHeaderBag.php:290)"} []
[2019-01-31 16:11:01] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
```

**Comment by ngodfraind** [comment]
Ça veut dire que c'est le '/' dans le nom du fichier, je vais faire en sorte qu'ils soient remplacé par des `_`
