### ISSUE TITLE
Widget contenu simple : plus d'un ajout de ressource mène à une page blanche

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5425]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.2.14

Bonjour,

J'ai reproduit plusieurs fois l'erreur suivante dans un widget contenu simple :
1 : je vais piocher une première ressource avec le bouton "ressource" > ca fonctionne parfaitement.
2 : je vais piocher une seconde ressource avec le bouton "ressource"  > page blanche.

Contournement possible : Sauvegarder le widget et l'accueil puis actualiser après chaque action. C'est très fastidieux...

Merci de votre attention.

**Comment by LaurentGruber** [comment]
Autre contournement possible, créer une ressource texte, et utiliser le widget ressource pour l'afficher sur l'accueil ...

**Comment by Elorfin** [comment]
Je ne reproduis plus sur la 12.3.3. Testé en local et sur https://demo12.claroline.com.

**Comment by txomin666** [comment]
Bonjour,
En effet ça marche sur le site demo, mais le problème est présent sur une install fraîche de la 12.3.4.
Par contre je n'ai pas trouvé de contournement, je n'arrive pas à insérer la moindre ressource, pas de message d'erreur, le lien vers la ressource ne s'affiche pas.
