### ISSUE TITLE
[ExoBundle] Edition-Terminologie

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#543]
Dans l’édition des questions, proposition de remplacer : 
- Feedback général par Commentaire (c'est en effet l'information qui va accompagner la correction en fin d'exercice)
- Commentaire par Feedback (c'est en effet la rétroaction qui accompagne chacune des propositions de réponse)

**Comment by eldoniel** [comment]
@UJM-dev Etes-vous d'accord?

**Comment by CPASimUSante** [comment]
Et si on veut franciser, on pourrait mettre Retour au lieu de Feedback

**Comment by jj-quintin** [comment]
Si on veut franciser (perso je ne suis pas contre), le terme en pédagogie est alors "Rétroaction"

**Comment by eldoniel** [comment]
Le terme de "Rétroaction" ne me semble pas assez clair pour une majorité de gens (moi inclus, je n'aurais jamais interprété ce terme comme un synonyme de "Feedback").

**Comment by jj-quintin** [comment]
On choisit feedback alors, ok ?
