### ISSUE TITLE
[exo] message de réussite ou d'échec

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#5438]
ajouter un message de réussite ou d'échec selon le param de % de réussite à la fin du questionnaire.

**Comment by Elorfin** [comment]
On l'affiche où ?
Je vois 3 endroits qui peuvent être pertinents : 
- Sur la page d'accueil du quiz
- Sur la page de fin des tentatives
- Dans le détail de la correction

**Comment by LaurentGruber** [comment]
Sur la page de fin
