### ISSUE TITLE
[ExoBundle] Appariement-feedback spécifiques

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#544]
Afficher, comme dans les autres types de questions, le x ou le v (dans le coin supérieur droit, au-dessus de la loupe par exemple). C'est sur ce x ou v que le curseur entraîne l'affichage de l'infobulle contenant le feedback spécifique

![image](https://cloud.githubusercontent.com/assets/16414632/15760094/fa961c44-2911-11e6-822c-0ab368bfa0ad.png)

**Comment by eldoniel** [comment]
Au-dessus de la loupe, ça risque d'être non seulement assez disgracieux, mais en plus ça va décaler l'icône de la loupe.
En l'état ça me semble plus intéressant, d'autant qu'une icône fera doublon avec la couleur de la case.
Mais si vraiment il faut mettre une icône, je suggèrerais plutôt de la mettre à côté de la proposition, à l'intérieur.

**Comment by jj-quintin** [comment]
> Mais si vraiment il faut mettre une icône, je suggèrerais plutôt de la mettre à côté de la proposition, à l'intérieur.

Où ça ? Désolé, j'ai pas compris

**Comment by eldoniel** [comment]
A l'intérieur de la partie grise, entre les boutons retour et loupe.

**Comment by jj-quintin** [comment]
oui, mais là il y a le contenu de l'élément déplacé (qui peut être du texte, de la vidéo, que sais-je). Dans la saisie on ne voit que deux mots, mais si c'est plus "costaud" comment vois-tu les choses ? Admettons qu'il y ait une image ou une vidéo par exemple, tu la mettrais où ? Au-dessus, centrée en largeur ? C'est une idée mais tu en as peut-être une autre en tête.

**Comment by eldoniel** [comment]
Ben mon idée de départ c'était de mettre la case entière en rouge ou en vert, et le feedback spécifique qui apparait au passage de la souris sur l'ensemble de la case, ce qui le rend difficile à louper... C'est comme ça que je l'ai fait parce que ça me semblait en même temps le plus simple et le plus esthétique.
Mais bon après c'est pas tellement à moi de décider de ça...

**Comment by jj-quintin** [comment]
Non, mais cela donne très bien ce que tu fais, juste que cela n'incite pas l'utilisateur à passer le curseur sur la zone rouge/vert dans l'intention de voir le feedback et que partout ailleurs on a les x et v. Je voulais savoir si tu avais une idée de l'endroit où placer le x ou v _en plus_ de ton système de cadre rouge/vert

**Comment by eldoniel** [comment]
Tried to work on it. I can't find any good solution to add an icon on pairing questions.

The major problem, I think, is that wrong feedbacks are indicated with a red cross, which looks like a closing button (see screenshot below).
![screen-feedback-icon](https://cloud.githubusercontent.com/assets/7665692/18505207/85ca69f0-7a66-11e6-819b-d63321cffdd4.png)

The other solutions that I can think of also look bad to me:
- setting the icon at the place of the left button (the one to reinitialize the drop, which is deactivated if feedback is shown). It would place the feedback icon on the left of the div, which seems weird to me.
- intervert the right and left buttons, so we can set the icon on the right, in place of the deactivated button. But then we would grab the div from the right and not from the left.

**Comment by Elorfin** [comment]
@eldoniel : Will it be possible to include it in the release planned next week ?

If no can you move the milestone to 16.12 please ?

**Comment by eldoniel** [comment]
It could, if anyone would tell me one right and precise way to do it.

If not, the specific feedbacks on pairing are working anyways, this ticket would be a minor enhancement, so it should not be a big deal if this is not implemented for 16.09.
