### ISSUE TITLE
Questionnaire : Si champ incomplet impossible d'enregistrer les actions

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5444]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.1

Bonjour,
Dans le questionnaire, lorsque l'on créé des questions, si l'on oublie de remplir un champ, nous avons un pop up de rappel "Questionnaire non valide".
Après avoir fermé ce pop up, impossible d'enregistrer les dernières actions, le bouton disquette reste gris/transparent.
![image](https://user-images.githubusercontent.com/24249636/52398212-a0b3d580-2ab8-11e9-9945-970fb9c87dde.png)
Bug reproduit sur plusieurs espaces d'activités depuis 8H ce jour.

Tout le contenu de la question et les autres actions non enregistrées sont donc perdues car on doit réactualiser sans pouvoir enregistrer. C'est bloquant pour cet outil.
Je n'ai pas trouvé de contournement.

Je vous remercie de votre attention.

**Comment by ngodfraind** [comment]
C'est reproduit.

**Comment by LaurentGruber** [comment]
https://github.com/claroline/Distribution/pull/5466
