### ISSUE TITLE
[ExoBundle] Affichage des feedback spécifique en HTML (éditeur riche)

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#545]
Voir l'affichage du feedback spécifique ci-dessous

![image](https://cloud.githubusercontent.com/assets/16414632/15760238/841874c6-2912-11e6-88f7-df477c82d4d0.png)

**Comment by eldoniel** [comment]
On a une solution, mais ça impliquerait de cliquer sur l'icône et non plus seulement de passer la souris au-dessus. Est-ce que ça conviendrait?

**Comment by jj-quintin** [comment]
Clic sur l'icône (X ou V) et affichage... dans quoi/où ? Infobulle (mais ce n'est pas l'usage associé aux infobulles, et comment fait-on disparaître ce feedback ?) Donc ? Modale ? (mais c'est "lourd" : cliquer pour ouvrir, puis fermer). Si il n'y a pas de solution technique pour afficher l'HTML dans la solution actuelle (infobulle au passage du curseur), je ne vois pas de bonne solution, niveau usage

Proposition ultime : ne pas afficher de l'HTML dans ce type de feedback

Cela peut peut-être se défendre pour des feedback spécifiques dont la vocation est de fournir une information simple, rapide et courte en retour d'une proposition de réponse

Qu'en pensez-vous ?

**Comment by eldoniel** [comment]
Ce serait une infobulle au clic. On affiche l'infobulle au clic, on la fait disparaître en cliquant de nouveau.

**Comment by Elorfin** [comment]
You can see a live example of the solution proposed by @eldoniel here : http://getbootstrap.com/javascript/#live-demo-1

**Comment by jj-quintin** [comment]
ok, j'ai vu. Merci. Ca marche

**Comment by Elorfin** [comment]
@eldoniel : Will it be possible to include it in the release planned next week ? 

If no can you move the milestone to 16.12 please ?

**Comment by Pauooo** [comment]
Comme la solution de la popover est retenue, ne faudrait-il pas avoir une icône ou un texte à côté du X ou V qui explicite qu'il faille cliquer pour avoir le feedback spécifique ? Je ne suis pas sûre que sans cela les utilisateurs cliqueront d'eux-même sur le X ou le V.
