### ISSUE TITLE
Auto inscription à un espace public impossible 

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#5450]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.1

En tant que **collaborateur** 
Dans le top menu / Espace d'activité publics
On ne voit que quelques espaces alors qu'il devrai y en avoir des centaines
Les étudiants ne peuvent donc pas s'y inscrire puisqu'ils ne sont pas affichés

En tant qu'administrateur, je vois tous les espaces publics.

Ce problème a déjà été reporté et résolu par @ngodfraind  dans la version 12.2.14 mais réapparaît dans la version 12.3.1.
Nicolas peux-tu repatcher notre plateforme car c'est urgent ? merci d'avance

**Comment by LaurentGruber** [comment]
Il n'y a pas de bug, les utilisateurs voit les espaces des organisations auxquels ils sont lié. Ce qui est le comportement voulu.
Il faut lié tous les utilisateurs à l'organisation par defaut.

**Comment by clarophil** [comment]
Je ne sais pas éditer l'organisation par défaut vinci et donc ajouter des espaces
Echec de téléchargement
Error 500 
https://claco.vinci.be/apiv2/organization/b2c638cf-c079-11e7-a06f-0cc47a960f96/workspace?page=0&limit=30

**Comment by LaurentGruber** [comment]
c'est un e.a. qui a une double racine dans la db, on va corriger la db, mais il n'y a pas de bug

**Comment by clarophil** [comment]
Peux-tu corriger la db ?  Merci
