### ISSUE TITLE
Widgets/ Liste > Ressources - Dysfonctionnement

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#5452]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      | 12.3.1

Depuis ce jour, le widget Liste des Ressources d'un EA affiche des informations erronnées pour tous les publics. Il n'affiche pas toutes les ressources d'un EA mais ceux de la plateforme.
Pouvez-vous intervenir pour masquer cela.

**Comment by ngodfraind** [comment]
Je pense que c'est corrigé. A vérifier.

**Comment by LaurentGruber** [comment]
fixed by https://github.com/claroline/Distribution/pull/5454
