### ISSUE TITLE
[Ressources] - Bugs tests V12

### ISSUE THREAD

**Issue by FlorianV54** [claroline/Distribution#5457]
| Q             | A
| ------------- | ---
| Bug report ?   | yes
| Version ?      | 12.2.14 / 12.3.1

### Cours
- [x] **Création d'un chapitre**
Si la position n'est pas spécifiée (ou placer le chapitre) erreur à l'enregistrement car le champ par défaut est vide ('échec de la création')
---
### Poubelle de ressources
- [x] **Restauration d'une ressource**
Impossible de restaurer une ressource supprimée. Pas de bouton 'Restaurer' ou équivalent. Normal ?
---
### Ressource Texte
- [x] **Export PDF**
Pas d'export PDF possible. Normal ?
---
### URL
- [x] **Affichage 'iFrame'**
Egalement, le bouton 'modifier' ne fonctionne pas. Il faut retourner dans les ressources pour modifier la ressource URL.

- [x] **Affichage 'Redirect'**
Si l'on choisi l'option d'affichage 'redirect', le lien s'ouvre dans la page courante.
En terme de praticité, il faudrait pouvoir choisir l'ouverture dans un nouvel onglet.

---
### Bade de données
- [x] **Enregistrement suite ajout d'une catégorie à une fiche**
Impossible de sauvegarder la modification d'une fiche suite à l'ajout d'une catégorie à celle-ci.

**Comment by LaurentGruber** [comment]
Non, il n'y a pas d'export pdf sur la ressource texte (et il n'y en avait pas avant)

**Comment by LaurentGruber** [comment]
ceci : est une demande d'amélioration, pas un bug : 
Lorsqu'on veut afficher dans une iframe, ça ne fonctionne pas si le site est sécurisé contre le 'cross origin framing' (ex. https://www.sncf.com/fr). Il faudrait un message qui prévient l'utilisateur que le site en question ne peut pas être affiché dans une iframe.
