### ISSUE TITLE
Organisation impossible de supprimer un utilisateur

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#5458]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.1

Dans l'administration / Gestion des utilisateurs
Cliquer sur un utilisateur
Ouvrir Organisation
Supprimer une organisation pour cet utilisateur
Pas d'erreur affichée ni dans la console 
Mais l'organisation est toujours là !

Comportement identique dans l'onglet Organisation
Sélectionner une organisation
Ouvrir Utilisateurs 
Cocher et supprimer un utilisateur
Pas d'erreur
Mais il est toujours là

**Comment by LaurentGruber** [comment]
doublon
