### ISSUE TITLE
[ExoBundle] Affichage des feedback spécifique négatif (réponse incorrecte)

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#546]
@eldoniel 

Cas de toutes les questions ouvertes (texte à trous, réponse ouverte...) et dans les associations, autrement dit dans toutes les questions qui ne sont pas des QCM je pense

Le souci que l'on rencontre dans cette situation (l'éditeur de question ne permet pas d'inclure deux feedback pour une même réponse est que le seul feedback disponible est affiché quelle que soit la qualité (bonne ou mauvaise de la réponse). Donc le seul feedback disponible (généralement destiné à une bonne réponse) s'affiche également dans le cas d'une mauvaise réponse

Proposition : 
Afficher toujours le même texte : "Réponse non acceptée" en cas de mauvaise réponse (avec bien sûr le x rouge) dans ce type de question non QCM

![image](https://cloud.githubusercontent.com/assets/16414632/15760514/d6dee086-2913-11e6-9d49-dba806bc99cb.png)

**Comment by eldoniel** [comment]
@Elorfin Je passe sur celle-ci pour perdre le moins de temps possible dessus. Je n'arrive pas à intégrer une traduction dans la condition, dans la ClozeQuestionDirective.

J'ai essayé un truc comme ça:
feedbackHtml.attr('title', '{{ clozeQuestionCtrl.holes["' + hole.id + '"].valid ? clozeQuestionCtrl.getHoleFeedback(clozeQuestionCtrl.holes["' + hole.id + '"]) : "unaccepted_answer"|trans:{}:"ujm_sequence" }}');
Mais il me met "unaccepted_answer" et non sa traduction.
