### ISSUE TITLE
Questionnaire : Impossible de répondre

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5462]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.1

Bonjour, 
Il est impossible de "commencer" ou de "répondre à un questionnaire".

Le message "Veuillez patienter pendant le chargement du questionnaire... " s'affiche puis on reste sur une page vide.
Le questionnaire en question https://w-alter.mfr.asso.fr/resources/show/ujm_exercise/ed203ad7-ae93-4fce-8310-eaba9ea7408d#/play

Merci de votre attention.

**Comment by LaurentGruber** [comment]
Les images dans la colonne de droites ont été mise via copié / coller ce qui génère un questionnaire très lourd.
Mettez les images dans les ressources et puis via un lien dans le champ et le questionnaire passera.

On réfléchit à une solution pour interdire le copier/coller d'image dans ces champs ...
