### ISSUE TITLE
[Gestion des Contenus] - Bugs tests V12

### ISSUE THREAD

**Issue by FlorianV54** [claroline/Distribution#5469]
| Q             | A
| ------------- | ---
| Bug report ?   | yes
| Version ?      | 12.2.13/12.2.14/12.3.0

### Publication d'une ressource par date
- [x] **Manque la plage de date dans le message qui explique inaccessibilité**
Message: la ressource n'est pas encore accessible? veuillez patienter jusqu'...
---
### Gestion de droits de ressources par lot
- [x] **Page blanche**
La gestion de ressources par lot demeure impossible, on coche les fichiers puis 'picto cadenas' (fermé) et page blanche. La gestion n'est opérationnelle qu'individuellement. 
Le griser temporairement le temps que la fonctionnalité soit opérationnelle si c'est prévu. [ TypeError: 'e.resourceNode.meta is undefined' ]
---
### Dépôt de document
- [x] **le dépôt de fichier par simple glisser-déposer n'est pas opérationnel.**
Le traditionnel glisser-déposer pour uploader des document ne fonctionne pas. Pas de cadre de dépôt. Fonctionnalité supprimée ?
---
### Widget
- [x] **la dé-publication d'une section ne fonctionne pas**
On décoche,il ne se passe rien et si on actualise la page la section n'est pas dé-publiée.
---
### Parcours
- [x] **Création du parcours**
Lors de la création du parcours : message non traduit: *start_disabled_empty*

**Comment by LaurentGruber** [comment]
non le glisser déposer a disparu
