### ISSUE TITLE
Feature : Reactivate the bundle management page

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#547]
In admin mode, the page with the bundle list has been removed and also the pages for managing the options of those bundle, when any.
It would be useful to have, at least, the latest back, because it is needed for some bundle to work

**Comment by LaurentGruber** [comment]
il est présent dans admin > paramètre généraux > plugins

**Comment by CPASimUSante** [comment]
ok, i hadn't seen the page.
But, then, there are 2 things in that page : 
1 - When i hover the icons : they are greyed out (without alt text => i don(t knwon which info it should be, and why i can't click) these are download (what ?), info (version ?)
2 - when i click on the cogwheel for those where i can (to manage the plugin), i have an error 500 :
```No listener is attached to the 'plugin_options_undefined' event``` (for anyone which is avalable)

**Comment by stefk** [comment]
Bug confirmed and +1 for first remark.
