### ISSUE TITLE
[Gestion des Contenus] - Améliorations tests V12

### ISSUE THREAD

**Issue by FlorianV54** [claroline/Distribution#5470]
| Q             | A
| ------------- | ---
| Bug report ?   | yes
| Version ?      | 12.2.13/12.2.14/12.3.0

### Publication par date
- [ ] **Aucun visuel sur vignette ressources présent (picto)**
Il n'est actuellement pas possible d'identifier visuellement parlant sur la vignette d'une ressource si elle se trouve publiée par date. L'enseignant doit constamment accéder à ses paramètres 'Configurer>Restriction d'accès' pour s'en rendre compte -> pénalisant. 
Un picto 'chronomètre' serait indispensable, et une bulle de précision des dates concernées dans une bulle au survol de la vignette serait un plus. 
D'ailleurs, la case à cocher 'Publier' accessible dans les Paramètres>Informations n'est absolument pas accessible, il serait intéressant de la placer dans la partie 'Restrictions d'accès' à proximité de la Restriction par date de façon à faire comprendre à l'enseignant que cette restriction va concerner une action obligatoire de publication ou dé-publication (l'un ne va pas sans l'autre), l'une des raisons pour laquelle il est important que ces deux fonctionnalités soient présentes dans le même onglet des Paramètres.
---
### Publication ressources
- [x] **la publication/dépublication d'une ressource n'est pas suffisamment visible**
D'un seul coup d’œil il est très difficile de savoir si une ressource est publiée ou non (grisement).
26/02/2019 => case décochée pour revoir ce point - car "pas assez clair" sur le fonctionnement.
---
### Accueil
- [x] **Création Onglet - Icone Font-Awesome**
Les enseignants ne connaissent pas Font-Awesome donc n'utiliseront pas à moins d'avoir un picker ou un lien vers une librairie.

**Comment by LaurentGruber** [comment]
Pour la publication il y a un icone d'oeil barré ou pas, ça me parrait clair.

**Comment by FlorianV54** [comment]
D'accord mais il faut cocher une ressource. Pour une "visu globale" au niveau de toutes les ressources, ce n'est pas forcément parlant.

**Comment by LaurentGruber** [comment]
Non, il ne faut pas cocher de ressources c'est directement sur les cartes des ressources.
Je te montre lundi, si tu veux

**Comment by FlorianV54** [comment]
Ok. Parce que pour nous l’œil sur les carte des ressources correspond aux nombre de vues de la dite ressource. Puis cet œil ne change pas d'état (barré).
