### ISSUE TITLE
[Gestion des Organisations] - Bugs tests V12

### ISSUE THREAD

**Issue by FlorianV54** [claroline/Distribution#5471]
| Q             | A
| ------------- | ---
| Bug report ?   | yes
| Version ?      | 12.2.14/12.3.0

### Rajouter un utilisateur à une organisation
- [ ] **Le gestionnaire de l'organisation ne voit pas l'utilisateur rajoutée à son organisation**
L'administrateur de la plateforme rajoute un utilisateur dans une organisation. impossible pour le gestionnaire de l'organisation de voir la personne.
---
### Créer un utilisateur dans son organisation
- [ ] **L'utilisateur n'est pas vu dans l'organisation**
L'utilisateur créé n'est pas visible dans l'organisation. Pourtant il fait bien parti de l'organisation.
---
### Se connecter en tant que
- [ ] **Impossible pour un gestionnaire d'organisation de se 'connecter en tant que'**
un gestionnaire d'une organisation ne peut pas usurper le compte d'un utilisateur.
---
### Organisation
- [x] **Impossible de supprimer un utilisateur de l'organisation par défaut**
L'utilisateur est automatiquement affilié à l'organisation par défaut. impossible de l'enlever de cette organisation même si il fait partie d'une autre organisation.
21/02/2019 => Affiche pop-up "Suppression réussi" mais l’utilisateur est supprimé puis re-listé dans la foulée.

**Comment by ngodfraind** [comment]
J'ai pas vraiment compris les points 1 & 2. C'est un refresh des données qui manquent ?
J'ai pu reproduire les point 3 et 4 (je vais donc les corriger).

**Comment by ngodfraind** [comment]
Impossible de faire le point 3. Il faut faire la maj vers symfony 4 pour ça.

https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Security/Http/Firewall/SwitchUserListener.php#L133

https://github.com/symfony/symfony/blob/4.2/src/Symfony/Component/Security/Http/Firewall/SwitchUserListener.php#L135

Le paramètre user est important. D'ailleurs y a de la doc pour implémenter ce genre de fonctionnalité sur la sf4, mais pas sur sf3. C'est pas encore supporté. J'ai créé le Voter en attendant, mais il faudra attendre la mise à jour de symfony pour que ça fonctionne.

**Comment by clarophil** [comment]
v12.3.5 la suppression d'une utilisateur d'une organisation ne fonctionne pas et il y des infos discordante
Exemple 
à partir de l'utilisateur 18999 je vois qu'il n'a pas d'organisation
![image](https://user-images.githubusercontent.com/895878/53557597-8ebcd400-3b46-11e9-83d4-d1d0852f8eb1.png)

mais dans l'organisation je vois cet utilisateur
![image](https://user-images.githubusercontent.com/895878/53557663-b4e27400-3b46-11e9-94d0-9daed5821d0a.png)
