### ISSUE TITLE
Gestion des espaces dans les organisations

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#5477]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.1

Dans la gestion des organisations / Espace d'activité
Tout fonctionne en sélectionnant un seul espace mais dès qu'on en sélectionne 5 ou 6

- [ ] echec à la suppression, erreur 500

- [ ] échec à l'insertion, erreur 500

**Comment by ngodfraind** [comment]
Impossible à reproduire en local. C'est possible d'avoir plus de détails ? c'est possible qu'un EA en particulier fasse tout planter ?

**Comment by clarophil** [comment]
Oui puisqu'il y a une organisation qui ne veut pas afficher ses espaces, Laurent m'a dit que c'était un espace qui a une double racine en db [https://github.com/claroline/Distribution/issues/5450](url)
Ce serait bien de corriger notre db.

**Comment by ngodfraind** [comment]
C'est réglé

**Comment by clarophil** [comment]
Merci Nicolas
