### ISSUE TITLE
le gestionnaire d'une sous-organisation ne peut pas gérer les utilisateurs de cette sous-organisation

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5480]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.1

Testé sur demo12 :
Je crée une organisation et une sous-organisation :
![image](https://user-images.githubusercontent.com/7293233/52563866-d7645580-2e02-11e9-8023-ca9de1d1278f.png)
J'ai défini l'utilisateur app_test en tant que gestionnaire de cette sous-organisation :
![image](https://user-images.githubusercontent.com/7293233/52563963-1c888780-2e03-11e9-835b-e6cb2a544da6.png)
J'ai également crée un autre compte affecté comme utilisateur dans cette sous-organisation :
![image](https://user-images.githubusercontent.com/7293233/52564043-59ed1500-2e03-11e9-8b80-0544627b6752.png)

Je me connecte ensuite avec le compte app_test (administrateur d'organization)
Ce compte utilisateur ne voit pas les utilisateurs inscrits dans la sous-organisation :
![image](https://user-images.githubusercontent.com/7293233/52564260-03340b00-2e04-11e9-9d74-3dd5f71c9b14.png)
Les utilisateurs sont quand même visibles dans liste des utilisateurs de la sous-organisation :
![image](https://user-images.githubusercontent.com/7293233/52564306-22329d00-2e04-11e9-8172-f4f6f444ae4f.png)

**Comment by ngodfraind** [comment]
J'ai reproduit la manip. J'ai le même problème.
