### ISSUE TITLE
impossible de modifier un bureau d'accueil si on est pas administrateur

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5487]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.3.1

Testé sur demo12 :
Je crée un utilisateur auquel j'affecte le rôle système "gestionnaire de l'accueil". Ce rôle possède "bureau et accueil" comme outils d'administration.

En testant ce compte, je n'arrive ni à créer, ni à modifier un onglet sur l'accueil de l'application (via administration / bureau et accueil)

**Comment by LaurentGruber** [comment]
Le rôle gestionnaire de l'accueil gère l'accueil de la plate-forme pas le bureau
