### ISSUE TITLE
problème d'affichage organisations et sous-organisation

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5489]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.1

Sur instance egreta : lorsque je suis connecté avec un compte utilisateur administrateur d'une organisation de niveau 0, certaines sous-organisations apparaissent à la fois en tant qu'enfant et niveau 0 dans la liste des organisations :
![image](https://user-images.githubusercontent.com/7293233/52641967-56788d00-2eda-11e9-913b-5a84640f002d.png)

**Comment by ngodfraind** [comment]
J'ai pas réussi à reproduire. Je suis allé sur la plateforme, j'ai essayé avec admins de Paris.

**Comment by flow39** [comment]
Merci Nicolas. Effectivement, je n'arrive pas non plus à reproduire sur une autre instance pour l'instant. Je vais tâcher de faire d'autres essais.

**Comment by nicvallet** [comment]
Bonjour, je rencontre aussi ce problème sur l'academie d'Aix Marseille qui était aussi présent dans la version précédente.
