### ISSUE TITLE
[ExoBundle] Bug si recommencer exercice

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#549]
Situation rencontrée après avoir recommencer un exercice (donc déjà réalisé une première fois), ici un texte à trous. ce qu'on obtient au premier essai avant même d'avoir introduit ou valider une réponse (voir la saisie d'écran ci dessous). A noter que les lacunes/trous ne peuvent pas non plus être complétés

Cas d'un texte à trous : 
![image](https://cloud.githubusercontent.com/assets/16414632/15761733/1ce9f7c2-291a-11e6-977d-592a542b262a.png)

Autre cas (QCM) : 

![image](https://cloud.githubusercontent.com/assets/16414632/15762404/e454b47a-291d-11e6-8708-2cba0f36be87.png)

**Comment by Elorfin** [comment]
This has been fixed by @eldoniel but not referenced in the PR.
I close it as it's available in the 7.x branch.
