### ISSUE TITLE
message d'erreur sur configuration de l'accueil de l'application

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5491]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.1

Dans les paramètres généraux, je configure le type de redirection de l'accueil sur old :
![image](https://user-images.githubusercontent.com/7293233/52646032-44025180-2ee2-11e9-917a-75a7bc02b58f.png)

Lorsque je veux éditer l'accueil, j'ai un message d'erreur :

![image](https://user-images.githubusercontent.com/7293233/52645988-28974680-2ee2-11e9-873a-7be5f1b76534.png)

**Comment by LaurentGruber** [comment]
Il Faut Choisir New et refaire l'accueil. Old n'est la que pour garder un accès au contenu et est déprécier
