### ISSUE TITLE
Bug d'affichage sur la liste des ressources d'un EA si barre de recherche désactivée

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5493]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | demo12 - 12.3.1

Dans un EA sur lequel la barre de recherche à été désactivée :
![image](https://user-images.githubusercontent.com/7293233/52649261-4798d700-2ee8-11e9-90ec-c3aac383ae05.png)

A l'affichage des ressources de l'espace, la barre de recherche apparait brièvement avant de disparaitre.

**Comment by LaurentGruber** [comment]
Ce n'est pas un bug, c'est le temps que la config se charge
