### ISSUE TITLE
EA - Accueil - configuration : Perte de données si plusieurs gestionnaires

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5494]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.1

Bonjour, 

J'avais connaissance de ce problème depuis les premiers jours de la V12 mais j'ai cru que c'était quelque-chose d'insolvable.

Je m'explique avec un exemple :
2 utilisateurs gestionnaires d'un même espace configurent l'accueil et travaillent chacun sur un onglet différent, au même moment.
Le gestionnaire 1 modifie l'onglet A pendant que le gestionnaire 2 modifie l'onglet B.
Le gestionnaire 1 créé des choses, travaille longtemps et enregistre tout : l'onglet A rempli et l'onglet B vide > tout se passe bien.
Juste après, le gestionnaire 2 créé des choses, travaille longtemps et enregistre tout : l'onglet B rempli et l'onglet A vide > Il écrase les données et le travail précédents du gestionnaire 1.

Il serait donc utile d'afficher un message/signal/fenêtre qui informe et bloque l'accès à la configuration au même moment par plus d'un gestionnaire à la fois.

Merci de votre attention.

**Comment by LaurentGruber** [comment]
@Elorfin il va falloir qu'on en discute
