### ISSUE TITLE
Ressource : Auteurs et licence Suggestion

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5495]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Bonjour,

Dans la configuration d'une ressource, partie "Auteur et Licence", il serait intéressant à l'avenir de proposer un menu déroulant avec des valeurs prédéfinies pour remplir le champ.
Exemple via la capture ci-dessous : 
![image](https://user-images.githubusercontent.com/24249636/52653017-69e22300-2eef-11e9-910a-48530161c547.png)

Merci de votre attention.

**Comment by LaurentGruber** [comment]
L'erreur de traduction a été corrigée, j'ai donc supprimé cette partie du ticket.

Pour la seconde partie, outre faire une liste déroulante, il faudra aussi faire un outil permettant de choisir les licences qu'on souhaite rendre disponible via cette liste.

**Comment by WalterMFR** [comment]
Merci beaucoup.
