### ISSUE TITLE
menus déroulants cachés dans l'éditeur de texte / propriété d'un tableau

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5498]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.1

j'ai crée un tableau dans un widget texte. J'accède aux propriétés du tableau :
![image](https://user-images.githubusercontent.com/7293233/52702071-d276e180-2f7b-11e9-9e1a-d7e95ba4425e.png)
Tous les menu déroulants sont cachés derrière la fenêtre de propriété :
![image](https://user-images.githubusercontent.com/7293233/52702132-f9351800-2f7b-11e9-87e7-0e244f2783e0.png)

Merci.

**Comment by LaurentGruber** [comment]
duplicate
