### ISSUE TITLE
TinyMCE

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#5509]
- [x] **Dans un widget, lorsque l'on veut faire un lien hypertexte, le champ pour choisir la cible passe en dessous de la popup**
On ne peut pas choisir le type d'ouverture

- [x] **Le tinyMCE en mode avancée freeze quand on annule le picker de ressources ou fichiers**
 En mode avancé du tinyMCE, quand on ouvre les outils d'insertion de ressources ou de fichiers, si on veut annuler l'action et fermer la popup du picker, le tinyMCE devient alors grisé et inaccessible, il faut rafraîchir la page pour le débloquer

- [ ] **Éditeur TinyMCE**
Une fois que l'on a créé un tableau, difficulté pour écrire en dehors du tableau (en dessous par exemple).

- [ ] **Plein écran**
Quand on passe en plein écran, la première ligne n'est plus visible.

- [ ] **Ajout fichier**
Quand on utilise la fonctionnalité ajouter fichier et que l'on décide de la quitter (clic en dehors ou croix), on ne peut plus rien faire si ce n'est enregistrer et/ou quitter. Quand on revient sur l'annonce, on ne peut plus écrire dedans.

- [ ] **Problème d'affichage du menu déroulant (bouton +)**
(Sur n'importe quel outil) les menus déroulants ne se déroulent pas correctement, il devrait s'afficher en dessous du clic, pas à la place.

- [ ] **Rendu Texte libre**
Dans le rendu Texte libre, les fichiers importés n'apparaissent pas.

- [x] **Insertion d'un tableau > menu contextuel des propriétés caché derrière**
Lors de l'insertion d'un tableau, le menu contextuel des propriétés (général et avancé) est cachée derrière.

**Comment by WalterMFR** [comment]
Bonjour,

    * **Le tinyMCE en mode avancée freeze quand on annule le picker de ressources ou fichiers**

Erreur reproduite chez nous aussi, "chargement en cours" tourne indéfiniment.

Merci.

**Comment by LaurentGruber** [comment]
Remplace https://github.com/claroline/Distribution/issues/4971 , https://github.com/claroline/Distribution/issues/5045

**Comment by greg49** [comment]
>
    * **Dans un widget, lorsque l'on veut faire un lien hypertexte, le champ pour choisir la cible passe en dessous de la popup**
      On ne peut pas choisir le type d'ouverture

en attendant, je rentre l'url et le titre depuis l'interface. ensuite je valide et pour changer la cible (target) j'affiche le code source et j'insère le target à la main.
<a title="Site Claroline" href="https://claroline.net/" target="_blank">
