### ISSUE TITLE
Duplication d'un EA : bug au niveau des ressources

### ISSUE THREAD

**Issue by SophieGuillemin** [claroline/Distribution#5517]
Dans le gestionnaire des espaces d'activités, lorsqu'on clique sur "copier" un EA, les ressources liées au nouvel EA sont dupliquées plusieurs fois.

**Comment by LaurentGruber** [comment]
Je viens de tester sur un espace au hazard, je n'ai aucune ressource dupliquée.

**Comment by SophieGuillemin** [comment]
Les espaces dupliqués pour lesquels j'ai rencontré ce problème sont :+1: > https://padint.intefp.fr/workspaces/3011/open/tool/home (espace qui existait avant la V12)
Tous les espaces FormationM_Lutte contre le travail illégal en interinstitutionnel_Module créées il y a quelques semaines exemple : https://padint.intefp.fr/workspaces/3734/open/tool/home#/tab/f0026861-fefd-4bf8-99c9-61af7bd3ec45

**Comment by LaurentGruber** [comment]
Qu'ont-ils en commun ? Quelle ressource sont dupliquer ? Comment reproduire depuis un espace originellement vide ? Que faut-il y ajouter comme ressouce ?

**Comment by SophieGuillemin** [comment]
LSP et LTI n'ont rien en commun.
LSP est donné en exemple pour vous permettre de reproduire le bug et identifier le probème.
LTI, pour certains ils ont des ressources e-learning commun, dupliqué via des parcours.

**Comment by SophieGuillemin** [comment]
Lorsqu'on copie les espaces suivants :+1: https://padint.intefp.fr/workspaces/2074/open/tool/home#/tab/20c5de10-dd42-11e8-a47b-0cc47a960f96
https://padint.intefp.fr/workspaces/3011/open/tool/home#/tab/20c95031-dd42-11e8-a47b-0cc47a960f96
Les ressources sont dupliqués plusieurs fois

**Comment by SophieGuillemin** [comment]
Idem lors de la copie de l'EA https://padint.intefp.fr/workspaces/2910/open/tool/home
Les doublons des ressources dans l'espace dupliqué apparaissent de manière alétoire

**Comment by SophieGuillemin** [comment]
Idem lors de la copie de l'EA https://padint.intefp.fr/workspaces/2075/open/tool/home#/tab/20c5e0a8-dd42-11e8-a47b-0cc47a960f96

**Comment by LaurentGruber** [comment]
Remplacé par : https://github.com/claroline/Distribution/issues/5581
