### ISSUE TITLE
Absence de ressources dans un EA spécifique

### ISSUE THREAD

**Issue by SophieGuillemin** [claroline/Distribution#5518]
Dans l'espace La 36e Session Nationale https://padint.intefp.fr/workspaces/2606/open/tool/home#/tab/20c7e128-dd42-11e8-a47b-0cc47a960f96 l'ensemble des ressources ne sont plus accessibles. 
Lorsqu'on essaie de les ouvrir (via les liens proposés par les onglets) un message d'erreur apparait.
Ce bug a déjà été signalé.
nous sommes en attente d'un retour
Merci

**Comment by LaurentGruber** [comment]
Les fichiers ne sont plus présent sur le serveur, ils ont du être supprimer courant début du mois de décembre, ce qui est trop éloigné pour qu'on puisse réellement analyser les choses

**Comment by SophieGuillemin** [comment]
Le problème est que personne n'a supprimé ces fichiers

**Comment by SophieGuillemin** [comment]
Tu me dis que les fichiers ont été supprimé pourtant, les pictos des ressources sont visibles ce qui montrent qu'ils n'ont pas été supprimés. Lorsqu'on clique sur ceux-ci, le message suivant apprait Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Ce qui est problématique et dérangeant pour nous c'est que ce sont des contributions de l'extérieur et que la PadINT était le moyen de centraliser les informations. Un gros travail a été demandé à tous et finalement ils ne peuvent rien consulter.
