### ISSUE TITLE
Bug ressources base de données EA spécifique

### ISSUE THREAD

**Issue by SophieGuillemin** [claroline/Distribution#5519]
La ressources "Votre avis sur la formation à distance" (base de données) est enrichie par les collaborateurs mais pas accessibles pour les gestionnaires ni l'administrateur.
URL de l'EA : https://padint.intefp.fr/resources/show/claroline_claco_form/34c73338-763d-4b1d-a70a-b6f27b349f46#/

**Comment by LaurentGruber** [comment]
Type error: Argument 1 passed to Claroline\CoreBundle\Library\Normalizer\DateRangeNormalizer::normalize() must be an instance of DateTime or null, string given, called in /home/intefp/www/vendor/claroline/distribution/plugin/claco-form/Serializer/ClacoFormSerializer.php on line 127
