### ISSUE TITLE
[ExoBundle] Affichage de la solution texte à trous : texte superflu

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#552]
@eldoniel 

La partie sous le texte à trous dans Réponse attendue, qui comme par Zone de réponse 1 est à supprimer il me semble

![image](https://cloud.githubusercontent.com/assets/16414632/15762121/556499fc-291c-11e6-872a-84e5bf0d26f2.png)

**Comment by charlotte42** [comment]
On ne verra pas toute les possiblités et les commentaire pour la zone de réponse 1 si on la supprime.
![selection_052](https://cloud.githubusercontent.com/assets/11042666/15771411/d7bacc20-296a-11e6-8cc0-ae2d3c78677c.jpg)
