### ISSUE TITLE
Problème sur le nom des expéditeurs de message via Claroline

### ISSUE THREAD

**Issue by SophieGuillemin** [claroline/Distribution#5520]
Le nom des expéditeurs envoyant des messages via Claorline sont faux. C'est le cas avec mon compte ainsi que plusieurs comptes gestionnaires.

**Comment by LaurentGruber** [comment]
Impossible à reproduire avec si peu d'information

**Comment by SophieGuillemin** [comment]
Lorsque j'envoie un message ou une annonce via PadINT, ce n'est pas mon nom qui apparaît en tant qu'expéditeur quand je vais dans "Mes messages envoyés" mais celui d'une collègue ou des noms d'autres utilisateurs

**Comment by LaurentGruber** [comment]
On a corrigé un problème similaire il y a une semaine ou deux, c'est toujours le cas aujourd'hui ?

**Comment by SophieGuillemin** [comment]
C'est le cas pour les messages envoyés la semaine dernière. Je regarde cette semaine et reviens vers toi sur ce point à la mi-semaine.
