### ISSUE TITLE
Widget Contenu simple : lien hypertexte dans nouvelle fenêtre

### ISSUE THREAD

**Issue by SophieGuillemin** [claroline/Distribution#5523]
Dans un espace d'activités, dans un onglet dans lequel on ajoute une section avec un widget de contenu simple. Lorsque l'on souhaite ajouter un lien hypertexte, une fenêtre s'ouvre : "Insérer un lien", le choix de la cible n/a ou nouvelle fenêtre via le menu déroulant est impossible car le menu déroulant apparaît derrière la fenêtre "Insérer un lien".

**Comment by LaurentGruber** [comment]
Doublon

**Comment by SophieGuillemin** [comment]
Merci Laurent pour l’info, pourrait-tu me dire où est ce bug remonté ?
Merci

De : Gruber Laurent [mailto:notifications@github.com]
Envoyé : lundi 18 février 2019 14:02
À : claroline/Distribution
Cc : GUILLEMIN Sophie (INTEFP); Author
Objet : Re: [claroline/Distribution] Widget Contenu simple : lien hypertexte dans nouvelle fenêtre (#5523)


Doublon
