### ISSUE TITLE
Ressources > Diaporama - Lancer le diaporama 

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#5524]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.3.3

Bonjour,
Un enseignant a créé un diaporama de cours. En visuel étudiant, il n'est pas intuitif pour le lancer.
Il faut aller dans "..." puis "Commencer". 
Cliquer sur le 1er slide pour ouvrir le diapo serait une bonne chose.

![image](https://user-images.githubusercontent.com/33163723/52952401-ae087400-3384-11e9-9b21-4da8f14ae252.png)

**Comment by greg49** [comment]
Bonjour, j’ajouterai l'importance d'insérer plusieurs images en simultané. Il ne me semble pas possible d'aller au-delà d'un fichier à la fois, ce qui sur une diapo de 50 images peut s'avérer décourageant.
De plus, récupérer ou non de manière auto le nom du fichier pour le mettre dans le titre serait un plus. Et de proposer d'afficher ou non le titre de la diapo avec sa description en dessous, au-dessus, sur la diapo avec une bande semi-transparente...
