### ISSUE TITLE
[ExoBundle] Graphique : Où est le pointeur ?

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#553]
Le ou les pointeurs devraient être visibles dès le démarrage de la question

![image](https://cloud.githubusercontent.com/assets/16414632/15762714/9adc6084-291f-11e6-8869-96f71668944b.png)

**Comment by charlotte42** [comment]
Il faut clicker sur l'image pour placer le pointeur

**Comment by eldoniel** [comment]
C'est plus simple, tant en terme fonctionnel qu'en terme d'utilisation, de faire ainsi. En revanche, on pourrait afficher un texte du style "cliquez sur l'image pour placer un pointeur" pour que ce soit plus clair.

**Comment by jj-quintin** [comment]
Pour ma part, ok pour l'ajout (quelque part) du texte ""Cliquez sur l'image pour placer un pointeur"
