### ISSUE TITLE
Absence de ressources dans un EA spécifique

### ISSUE THREAD

**Issue by SophieGuillemin** [claroline/Distribution#5531]
Je republie ce post sur l'espace "36e session nationale" car de notre côté les ressources qui se trouvent dans les sous-répertoires "Module 1'" et "Module 2" sont corrompus.
Les pictos des fichiers déposés sur la PadINT sont visibles lorsqu'on clique dessus voici le message qui apparaît : 

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

De notre côté, nous pouvons affirmé ne pas avoir supprimé les ressources. Ces ressources ont été déposées pour certaines depuis les Etats-Unis, nous ne disposent pas de sauvegarde. Formalibre peut-il nous fournir les documents ? 

Est-il possible de vérifier si certaines de ces ressources sont sur l'ancienne plateforme ?

**Comment by LaurentGruber** [comment]
L'erreur 500 est là car il ne trouve pas le fichier

**Comment by SophieGuillemin** [comment]
Ok et comment faire pour le retrouver étant donné que nous ne les avons ni supprimés ni déplacés ?

**Comment by LaurentGruber** [comment]
cela fait 2 mois et demi qu'ils ne sont plus là, mon backup ne remonte pas si loin ...
Je clos ce ticket, car je ne sais pas reproduire la cause et donc en l'état ce n'est pas un bug.
A nouveau, cela s'étant passé il y a plus de 2 mois, je sais difficilement investiguer plus. Si vous le voulez vraiment ça peut se faire dans le cadre d'un contrat de support.
