### ISSUE TITLE
Widget éléments à venir

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#5535]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.3
Lors de l'affichage des entrées de l'agenda dans un widget, lorsqu'on demande d'afficher les tâches, le widget affiche toutes les tâches de tous les EA, même de ceux dont on n'est pas membre..

![image](https://user-images.githubusercontent.com/31481850/53011519-d6ee3f00-3440-11e9-8ec4-b015e8316f59.png)

je ne suis pas membre des espaces Fran ou Sciences

**Comment by ngodfraind** [comment]
J'ai pu le voir sur la plateforme aussi.

**Comment by ngodfraind** [comment]
Pas reproduit en local.
