### ISSUE TITLE
[ExoBundle] Edition question ouverte - largeur champ commentaire

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#554]
Réduire la largeur/longueur de ce champ (problème avec le champ des réponses)

![image](https://cloud.githubusercontent.com/assets/16414632/15762922/c48520dc-2920-11e6-82c5-77fd828b3258.png)

**Comment by eldoniel** [comment]
Note: Le souci ne se présente que sous Chrome, ça fonctionne correctement sous Firefox.
