### ISSUE TITLE
Evaluation : affichage du profil de l'utilisateur

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5540]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.3.3

Bonjour, 
Lorsque l'on vérifie les productions/réponses faites par des utilisateurs à une évaluation, le nom d'utilisateur s'affiche bien, les fichiers remontés aussi.
Est il envisageable de pouvoir aussi afficher le profil de l'utilisateur?
Ce serait pour faciliter le suivi sans passer par le menu "utilisateurs" de l'espace.

Merci de votre attention.

**Comment by kitan1982** [comment]
Vous désirez afficher certaines données particulières du profil ou simplement un lien vers celui-ci ?

**Comment by WalterMFR** [comment]
Nom, prénom et organisation dans l'idéal.
Merci.

**Comment by kitan1982** [comment]
On parle bien de la nouvelle ressource Evaluation ?
Parce que sur la page "Voir toutes les évaluations" et sur la page d'une évaluation particulière, le nom et le prénom sont déjà présents (Copie de «X Y»).
