### ISSUE TITLE
[evaluation] Bug divers

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#5556]
### Évaluation + Évaluation par les pairs
- [x] **Les points des critères de notation ne s'affichent pas**
Les points des critères de notation ne s'affichent pas mais les points sont automatiquement pris en compte pour les vues gestionnaires et collaborateurs

- [x] **Bug dans l'ajout des documents de type**
Si l'on ajoute un document de type Lien internet > un message de réussite s'affiche, mais le lien nous envoie sur un message d'erreur (500 internal server error)

- [x] **Bug dans l'ajout des documents de type Ressource de l'EA**
Si l'on ajoute un document de type Ressource de l'EA > un message de d'échec de la création s'affiche.

- [x] **Bug dans la soumission de la participation**
Si l'on soumet sa participation, un message d'échec de la MàJ s'affiche.

- [x] **La sauvegarde fait planter la ressource**
Quand on sauvegarde les documents à soumettre, la ressource plante, impossible d'éditer à nouveau.

- [x] **Pourcentage de progression**
Le pourcentage de progression en haut à gauche reste à 0%, au début, après l'envoie des données et après la correction. Je ne vois pas comment le faire progresser..

- [x] **Refus de correction**
Il est possible de faire un refus de correction mais il n'est pas pris en compte.

---

**Comment by clarophil** [comment]
- Dans la grille d'évaluation, on ne voit pas ce qu'on encode (laquelle des bullets) on a choisie. Ensuite si on veut visualiser le résultat, à nouveau on ne voit pas quelle bullet est cochée.
![image](https://user-images.githubusercontent.com/895878/53332522-da2b7400-38f3-11e9-8efc-85b98d2eeffb.png)

**Comment by ChristeleGouy** [comment]
ÉVALUATION
Il est possible de faire un refus de correction mais il n'est pas pris en en compte. 
![eval-refuscorrection](https://user-images.githubusercontent.com/48215349/53744743-e4beae00-3e9d-11e9-9f27-b494d8349fcd.PNG)

**Comment by ChristeleGouy** [comment]
La durée de suivi de la ressource n'est pas indiquée de manière systématique. Cette fonctionnalité est utile pour le suivi des apprenants par les financeurs. Est-ce normal?
![suivi-eval](https://user-images.githubusercontent.com/48215349/53788501-54767c80-3f22-11e9-81e4-e5f224d20d7e.PNG)
