### ISSUE TITLE
[ExoBundle] problème de tag

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#5557]
- [x] à chaque fois que je tag une question, il me fait sortir du questionnaire
- [x] il retient le tag pour la question mais quand je veux l'attribuer à une autre question il ne me le propose plus...

**Comment by nicolasjacquemet** [comment]
A priori doublon du point "Ajout d'un tag" de l'issue #5459.
Le problème n'intervient que sous Firefox et IE, pas de souci sous chrome.
