### ISSUE TITLE
[ExoBundle] Edition question ouverte - Ajout mot clé

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#556]
Quand on revient sur l'édition d'une question ouverte, il n'est plus possible d'ajouter un mot clé

![image](https://cloud.githubusercontent.com/assets/16414632/15763117/f8eb2370-2921-11e6-8393-c5e5dd24883f.png)

**Comment by charlotte42** [comment]
De david42 pour l'issue #557  -> 'Je pense que cette question est liée à une copie contenant cette question.
Si c'est le cas, certains paramètres de la question ne sont plus modifiables afin de rester cohérent.
Si les copies appartiennent à un exercice non publié, il suffit de supprimer les copies et la question seara totalement modifiable.'

**Comment by jj-quintin** [comment]
Peut-être que dans ce cas et à l'avenir un petit texte d'information serait utile (mais ce n'est pas forcément urgent)

**Comment by david42** [comment]
Normalement le "crayon" d'édition devrait apparaître en rouge (+ info bulle) pour repérer les questions liées à des exercices. Ce n'est visiblement pas le cas.
Il faudrait qu'on le fasse "ré-apparaitre".

**Comment by Pauooo** [comment]
Duplicate Red pen #1068
