### ISSUE TITLE
PB inscription utilisateur groupe

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#5560]
| Q 
| Bug report?   | yes
| Version?      | 12.3.4

GESTION UTILISATEURS
Lorsque j'inscris un utilisateur et que je l'affecte à un groupe - pas de problème.
Quand je clique sur l'ongle Groupes, son nom puis Utilisateurs, je ne vois pas les personnes dans la liste qui reste vide.

**Comment by LaurentGruber** [comment]
en faite il faut recharger la page et c'est là ...
