### ISSUE TITLE
[Ressources] - Améliorations tests V12

### ISSUE THREAD

**Issue by FlorianV54** [claroline/Distribution#5564]
| Q             | A
| ------------- | ---
| Bug report ?   | yes
| Version ?      | 12.2.13 / 12.3.x

### URL
- [x] **Modification**
Le bouton 'modifier' ne fonctionne pas. il faut retourner dans les ressources pour modifier la ressource URL.
---
### Ressource
- [ ] **[OEIL] visuel de l'état de publication de ressource**
Nécessité d'une modification graphique de l’œil (par ex œil barré). le changement de couleur ne suffit pas
---

**Comment by LaurentGruber** [comment]
doublon est déjà corrigé
