### ISSUE TITLE
Messagerie : impossible d'effacer ses propres messages

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#5567]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.4

Messagerie
Messages envoyés
Cocher un message
Cliquer sur la poubelle

Erreur 500
Méthode PUT
[https://claco.vinci.be/clarolinemessagebundle/apiv2/message/softdelete?ids[]=d66f3ed4-2fcc-11e9-99e0-0cc47a960f96](url)

**Comment by ngodfraind** [comment]
Reproduit
