### ISSUE TITLE
[ExoBundle] Edition question ouverte - Suppression mot clé (bug)

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#557]
Lorsqu’on revient sur l'édition d'une question ouverte courte, on perd la possibilité de supprimer un mot clé

![image](https://cloud.githubusercontent.com/assets/16414632/15763156/2803d3b4-2922-11e6-9158-e72d7a7aa336.png)

**Comment by charlotte42** [comment]
Bonjour,
Est-ce que ta question ne serais pas liée à des copies d'un exercice ?

**Comment by david42** [comment]
Je pense que cette question est liée à une copie contenant cette question.
Si c'est le cas, certains paramètres de la question ne sont plus modifiables afin de rester cohérent.
Si les copies appartiennent à un exercice non publié, il suffit de supprimer les copies et la question seara totalement modifiable.

**Comment by jj-quintin** [comment]
Petit texte explicatif souhaité à l'avenir précisant que certains paramètres ne peuvent modifiés car des copies ont déjà été rendues. Ok ?

**Comment by david42** [comment]
Normalement le "crayon" d'édition devrait apparaître en rouge (+ info bulle) pour repérer les questions liées à des exercices. Ce n'est visiblement pas le cas.
Il faudrait qu'on le fasse "ré-apparaitre".

**Comment by Elorfin** [comment]
Duplicate #556.
