### ISSUE TITLE
Annonce :  impossible de modifier l'ordre ou le tri

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#5578]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.3.4

Il n'est pas possible de modifier le tri ou l'ordre des annonces dans l'outil Annonce.
Quand on clique sur Modifier ou sur le crayon de l'outil, on a cet écran
![image](https://user-images.githubusercontent.com/895878/53493003-8dce6880-3a9a-11e9-98d8-3bb1f08cffc7.png)

Alors que devrait avoir les options d'affichage comme pour les dossiers

**Comment by Elorfin** [comment]
Là tu es sur le détail d'une annonce, c'est normal qu'il n'y ait pas de fonction de tri.
Quand tu retournes sur la liste des annonces, il y a moyen de trier par date.

Ce qui me semble le seul tri pertinent dans ce cas.

**Comment by clarophil** [comment]
Oui effectivement.
Un autre petit soucis de navigation, si on édite une annonce à partir de la liste, après sauvegarde, on revient sur l'annonce et pas sur la liste.  Il faut renaviguer dans les ressources pour retrouver la liste.
Donc, à mon avis, soit on revient sur la liste, soit il faut avoir un bouton qui permet de revenir sur la liste.
