### ISSUE TITLE
[ExoBundle] Question ouverte courte : erreur dans l'analyse de la réponse

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#558]
Il y a deux mots clés : "Kili" et "Kilimandjaro"

![image](https://cloud.githubusercontent.com/assets/16414632/15763241/d59321ba-2922-11e6-9b3f-1b061c6d5447.png)

Voici le résultat de l'analyse de la réponse : 

![image](https://cloud.githubusercontent.com/assets/16414632/15763214/ac68a86e-2922-11e6-84b3-9817f703a7ed.png)

Avec les mots clés "1" et "1", résultat : 

![image](https://cloud.githubusercontent.com/assets/16414632/15763278/1cb3cd4c-2923-11e6-8d0a-8cfec3d5121b.png)

**Comment by eldoniel** [comment]
Pour le deuxième cas, il vaudrait probablement mieux empêcher les doublons de mots-clé au niveau de l'éditeur. Mais on verra probablement ça au moment de le passer en angular.

**Comment by jj-quintin** [comment]
Juste pour info, dans le premier cas, je n'avais introduit que deux mots-clés Kilimandjaro et Kili

**Comment by eldoniel** [comment]
Fixed by https://github.com/claroline/Distribution/pull/871
