### ISSUE TITLE
[ExoBundle] Question ouverte courte et mot - Quelle différence ?

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#559]
Désolé si qque chose m'a échappé, mais au vu de l'analyse de réponse et au vu de ce que j'ai pu voir dans l'éditeur, il n'y a apparemment pas de différence fonctionnelle entre ces deux formes de questions ouvertes : 

![image](https://cloud.githubusercontent.com/assets/16414632/15763547/f74c53e2-2924-11e6-8a2e-6f9fe881c008.png)

**Comment by charlotte42** [comment]
Bonjour, 
Pour la question à un mot, il peut y avoir plusieurs mots justes, mais on ne peut pas cumuler les points, vu que l'on attend bien qu'un seul mot en réponse.

Pour la question courte, on peut cumuler les réponses correctes. Elle est plus subtile à construire, car il faut penser à tous les cas de figure. Tout les mots clé saisie dans la réponse donnera le nombre point choisi.
![selection_051](https://cloud.githubusercontent.com/assets/11042666/15771248/ae85dc6a-2969-11e6-8ee1-34c3ba2aac8d.jpg)

**Comment by jj-quintin** [comment]
Oui, c'est subtil. Je réalise qu'il serait utile d'apporter une aide contextuel pour expliquer ces différences. Ceci dit, il me semble que dans le cas dont j'ai fait une saisie d'écran, logiquement si les deux réponses à la question mot sont marquées comme correctes (deux V vert), je devrais obtenir un score égal à 2. Ou alors le souci vient de l'analyse des réponses pour cette question "mot"

**Comment by eldoniel** [comment]
The problem is, indeed, in the analysis of the answers for "one word" open questions. For now it works similar to the "short" open questions.
I'm getting to work on it.

**Comment by Elorfin** [comment]
Question has been answered ans the bug for score is referenced in #560.
