### ISSUE TITLE
Disparition des icônes personnalisés

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#5597]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      | 12.3.5
Les icônes personnalisées pour mon établissement dans les ressources ont disparu, remplacé par le par défaut.

![image](https://user-images.githubusercontent.com/33163723/53651416-e80c2c80-3c46-11e9-85fc-71031675ae56.png)

**Comment by LaurentGruber** [comment]
déjà corrigé
