### ISSUE TITLE
Message personnalisé du mode maintenance

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#56]
_From @clarophil on March 23, 2016 14:57_

Il serait intéressant de pouvoir personnaliser dans l'admin le message qui s'affiche quand on est dans le mode maintenance par exemple pour dire combien de temps durera approximativement la maintenance.

_Copied from original issue: claroline/Claroline#732_

**Comment by ngodfraind** [comment]
Il faut voir un cas d'utilisation.
Pour le moment, il suffit d'éditer le fichier web/maintenance.php à la main.

**Comment by LaurentGruber** [comment]
@clarophil tu peux expliquer ton cas d'utilisation ?

**Comment by LaurentGruber** [comment]
Pouvoir préciser le temps de la maintenance, mettre une phrase qui prévient les utilisateurs. Pouvoir éditer le message depuis l'inteface d'admin
