### ISSUE TITLE
Accueil d'un EA vide

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5602]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.5

Bonjour,
Sur l'EA suivant, j'ai une page blanche quand j'affiche la page d'accueil :
https://egreta.claroline.com/workspaces/576/open/tool/home#/

Est-ce un problème de paramétrage ou un bug ?
Merci

**Comment by Elorfin** [comment]
Le problème est corrigé en 12.5.
