### ISSUE TITLE
Bug : disparition de ressources

### ISSUE THREAD

**Issue by SophieGuillemin** [claroline/Distribution#5603]
Dans l'espace d'activités https://padint.intefp.fr/workspaces/2443/open/tool/home#/tab/20c77cc4-dd42-11e8-a47b-0cc47a960f96 
Les liens proposés via le widget "Synthèse des bilans" (onglet : outils et ressources), renvoient vers ressources corrompues; elles semblent avoir été supprimées mais on me confirment que personne ne les a supprimer. Est-ce que cela est en lien avec le bug de décembre récemment identifié ?

**Comment by LaurentGruber** [comment]
Je ne reproduit, pas, je n'ai aucune erreur quand je clique sur les liens synthèses des bilans ...

**Comment by SophieGuillemin** [comment]
Ok. Je pense que la collègue a remplacé tout les fichiers.
