### ISSUE TITLE
Impossible d'ajouter section et widget dans un EA spécifique

### ISSUE THREAD

**Issue by SophieGuillemin** [claroline/Distribution#5605]
Dans l'espace https://padint.intefp.fr/workspaces/500/open/tool/home#/tab/b58f260e-249d-44b9-89f9-22bc5d2d5734  quand je clique sur nouvelle section, que j'ajoute (par exemple un widget de type texte) à la nouvelle section, lorsque je clique sur enregistrer, le message d’échec dans le cartouche rouge apparaît. Je ne peux donc pas enrichir ou modifier l'onglet de cet espace.

**Comment by LaurentGruber** [comment]
A new entity was found through the relationship 'Claroline\CoreBundle\Entity\Widget\WidgetInstance#container' that was not configured to cascade persist operations for entity: Claroline\CoreBundle\Entity\Widget\WidgetContainer@0000000003838db700000000355bc267. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Claroline\CoreBundle\Entity\Widget\WidgetContainer#__toString()' to get a clue.
