### ISSUE TITLE
Affectation d'une sous-organisation comme organisation principale non persistante

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5607]
| Q             | A
| ------------- | ---
| Bug report?   | yes / no
| Version?      | 12.3.5

Je souhaite crée un utilisateur et lui affecter une sous-organisation en tant qu'organisme par défaut (organisation principale) :
![image](https://user-images.githubusercontent.com/7293233/53799719-5436ab00-3f3b-11e9-90b8-3627ca3e4662.png)

Quand j'enregistre, la sous-organisation est remplacée par l'organisation "racine" :
![image](https://user-images.githubusercontent.com/7293233/53799817-952ebf80-3f3b-11e9-8f46-861ace3592b6.png)

Si j'ajoute manuellement l'utilisateur à la sous-organisation :
![image](https://user-images.githubusercontent.com/7293233/53799868-babbc900-3f3b-11e9-8293-2237d46f91c7.png)
Je peux alors modifier l'organisme principale et le changement est bien persistent :
![image](https://user-images.githubusercontent.com/7293233/53799909-d921c480-3f3b-11e9-8106-7ac0cf35bbdc.png)

Est-ce un bug ou est-ce que je ne comprend pas quelque chose ?

Merci

**Comment by ngodfraind** [comment]
C'est tjrs d'actu ? je peux pas reproduire.
