### ISSUE TITLE
Création d'une Ressource à la volée dans le Sélecteur de Ressources. Possible or not ?

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#5608]
| Q 
| Bug report?   |no
| Version?      | 12.3.5

Sur la page d'accueil d'un espace d'activité, lorsque l'on crée un Onglet, on doit ensuite insérer un Widget et le dispositif nous renvoie vers les ressources. 
Le problème c'est qu'il faut anticiper la création de cette ressource à afficher sinon il faut ressortir de la conception de page pour aller créer la ressource en question.
Ce qui serait pratique, c'est de trouver un lien dans la fenêtre Sélecteur de Ressources nous permettant ainsi d'accéder à l'ajout d'une ressource directement.
Qu'en pensez-vous ?

**Comment by LaurentGruber** [comment]
ce n'est pas aussi simple, on est pas dans le même context applicatif, mais ça arrivera un jour.
