### ISSUE TITLE
Parcours : comment imposer l'ordre des étapes ?

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#5615]
| Q   
| Bug report?   | no
| Version?      | 12.3.5

La ressource Parcours permet d'éditer des étapes que le collaborateur parcourt librement. 
Comment imposer le parcours et la réalisation des étapes d’évaluation et de formation dans l'ordre choisi ?
j'aimerai imposer un test de positionnement en étape 1
puis quelques rappels en étape 2 sauf si le résultat de l'étape 1 est supérieur au niveau choisi.
à la fin, test d'évaluation pour validation des acquis
etc...

**Comment by LaurentGruber** [comment]
Le principe même de claroline est de proposer un parcours aux apprenants non de le leur imposer ...
S'ils veulent commencer par la fin à ce jour personne n'a pu me donner de raison pédagogique allant dans le sens de favoriser l'apprentissage justifiant d'empêcher l'apprenant de le faire ...
Ce n'est donc à priori pas une fonctionnalité qu'on souhaite ajouter ...
Cependant on peut déjà en masquant le sommaire, fortement guider l'apprenant.
