### ISSUE TITLE
impossible de créer des ressources dans les EA depuis le passage en 12.3.6

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5622]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.6

Bonjour,
depuis le passage en 12.3.6, nous n'arrivons plus a créer des ressources dans nos EA sur l'instance e-greta ni modifier les ressources existantes.

Merci.

**Comment by LaurentGruber** [comment]
corrigé
