### ISSUE TITLE
Questionnaire : Création impossible

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5627]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.6

Message d'erreur à la création : 
"An exception occurred while executing 'INSERT INTO ujm_exercise (description, correction_mode, date_correction, mark_mode, interruptible, show_overview, show_end_page, show_end_confirm, end_message, attempts_reached_message, end_navigation, metadata_visible, statistics, minimal_correction, published, anonymous, type, show_feedback, totalScoreOn, success_score, numbering, max_papers, all_papers_stats, mandatory_questions, time_limited, progression_displayed, uuid, picking, random_order, random_pick, pick, duration, max_attempts, max_day_attempts, resourceNode_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["", 1, "2019-03-07 15:24:22", "1", 0, 1, 0, 1, "", "", 1, 1, 0, 0, 0, 0, "summative", 0, 100, 50, "none", 0, 1, 0, 0, 1, null, "standard", "never", "never", 0, 0, 0, 0, null]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'uuid' cannot be null"

**Comment by LaurentGruber** [comment]
déjà corrigé
