### ISSUE TITLE
Parcours : Création impossible

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5628]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.6

Message d'échec de la création (Jaune/orange). Détails : 

![image](https://user-images.githubusercontent.com/35995165/53963440-a0295180-40ed-11e9-9f3d-58aefe04a44c.png)

**Comment by LaurentGruber** [comment]
déjà corrigé
