### ISSUE TITLE
Un user peut modifier le profil d'un autre user

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5629]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.6

Bonjour,

Un utilisateur peut modifier tous les champs du profil d'un autre.
Ce n'est pas bloquant mais ca ne doit pas être toléré par le RGPD à mon avis.
C'est probablement urgent? 
Je vous laisse le soin d'en décider.

Merci de votre attention.

**Comment by kitan1982** [comment]
Un administrateur peut effectivement modifier le profil de tous les utilisateurs.
C'est le seul cas où le profil peut être modifié par un autre utilisateur, il me semble.

En tout cas, je n'arrive pas à reproduire le problème avec un non-admin.
