### ISSUE TITLE
EA : difficultés pour supprimer des widgets

### ISSUE THREAD

**Issue by SophieGuillemin** [claroline/Distribution#5630]
Dans l'EA https://padint.intefp.fr/workspaces/3963/open/tool/home#/edit/tab/e9dd102d-3343-4761-92f0-6f4b9307dcc3 il faut s'y reprendre à plusieurs fois pour supprimer les widgets et en créer de nouveaux dans des sections existantes.
Cet EA est une copie d'un EA existant (crée il y a quelques semaines)

**Comment by LaurentGruber** [comment]
normalement ceci : https://github.com/claroline/Distribution/pull/5621 corrige le problème.
Tu pourras me confirmer demain après la mise à jour ?
