### ISSUE TITLE
impossible de modifier un parcours

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5634]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.3.7

Bonjour,
Nous avons un parcours que nous n'arrivons pas à modifier. L'enregistrement échoue.
https://egreta.claroline.com/resources/show/4b135e71-e13c-4f6a-b6b2-5818a6fb7841
J'ai remarqué un message d'erreur dans la configuration d'une étape du parcours :
![image](https://user-images.githubusercontent.com/7293233/54016354-e2e93900-4182-11e9-8c23-dde8b6aba6cb.png)
Si j'essaye de supprimer cette étape, le message d'erreur apparait dans l'étape suivante.
Merci.

**Comment by LaurentGruber** [comment]
un truc pourri dans la db, ça devrait être ok ...
