### ISSUE TITLE
Dysfonctionnement d'un espace d'activités

### ISSUE THREAD

**Issue by SophieGuillemin** [claroline/Distribution#5635]
Dysfonctionnement de l'espace https://padint.intefp.fr/workspaces/3819/open/tool/home#/tab/21c7477e-832d-4d70-8340-20e754a3fd49 Parcours Mobilité_PTR_Nancy_1103160519
Ce dysfonctionnement n'est visible qu'en étant connecté en tant que collaborateur (moise). En effet aucun souci lorsqu'on est connecté en tant qu'admin.
Lorsqu'il est dans cet espace en tant que moise, et que l'on clique sur "Mes parcours", cela tente d'ouvrir un nouvel onglet qui disparait et réapparait sans cesse sans parvenir pour autant à ouvrir l'onglet "Mon parcours", le bug se répète à chaque fois que le collaborateur clique sur un lien hypertexte.
j'ai une vidéo du bug a dispo si besoin, 
Merci

**Comment by LaurentGruber** [comment]
Il n'y pas de dysfonctionnement, soit c'est une question de droit sur un ou plusieurs des scorms embarqué, soit une question d'authentification dans un des scorms (a priori plus les droits ...)
