### ISSUE TITLE
Gestion du support : Pas de notification

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5639]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.7

Les utilisateurs identifiés dans la gestion du support ne reçoivent pas de notification d'un nouveau ticket.
L'option est pourtant cochée.
![image](https://user-images.githubusercontent.com/35995165/54033104-b699e080-41b3-11e9-9418-8d5e4af7ebce.png)

**Comment by kitan1982** [comment]
Je pense que c'est parce qu'il n'y a pas de templates pour la création d'un ticket.
Il faut en créer un dans l'outil admin "Gestion des templates".

**Comment by kitan1982** [comment]
Il faut définir le Template comme "Template par défaut" pour qu'il puisse être utilisé automatiquement.
C'est une action dans le tableau avec la liste des templates.

**Comment by jbbrosset** [comment]
ah ok, vu en effet.
Pas évident sans sans savoir ou aller.
J'ai réussi avec le template de création de Ticket mais pas avec le template de nouveau commentaire.

Améliorations possibles : 
- [ ] Par contre la plateforme met du HTML dans le titre du mail, c'est pas propre.
- [ ] Le bouton de "définir comme Template par défaut" pourrait être également sur la page de création ?

**Comment by jbbrosset** [comment]
Thanks ;)

**Comment by kitan1982** [comment]
Pour les commentaires, seuls le créateur du ticket et les utilisateurs assignés au ticket sont notifiés.
C'est un choix qui a été fait afin de limiter le nombre de notifications reçues.

**Comment by jbbrosset** [comment]
Alors ça doit se comporter bizarrement parce que sur un ticket que j'ai créé et ou je fais un commentaire en tant qu'admin depuis la "Gestion" je ne reçoit pas de mail.


Merci pour l'info en tout cas.
