### ISSUE TITLE
EA : Inscription publique et lien d'inscription Erreur 500

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5641]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.7

Les liens d'inscription vers des espaces publics renvoient systématiquement vers des pages 'Erreur 500'.
J'ai également testé en copiant le lien vers la page d’accueil, j'arrive sur la page qui m'annonce:
"L'action home n'a pas pu être effectuée sur l'espace d'activité [Nom de l'EA]" 
suivi d'un bouton "inscription".

Quand je clique sur le bouton, je suis envoyé vers une erreur 500.

J'ai fait le test avec un compte User ayant la même orga et un autre sans orga en commun et j'ai les mêmes résultats dans les deux cas.

**Comment by greg49** [comment]
bonjour, même problème
https://colearning.claroline.com/ws/espaceb/subscription

![CAPTURE 2019-03-13 à 15 01 43](https://user-images.githubusercontent.com/21193255/54284934-36072580-45a1-11e9-8487-7c169a1f403b.jpg)

**Comment by LaurentGruber** [comment]
c'est toujours d'actualité ? Je pourrais avoir le nom de l'espace ?

**Comment by jbbrosset** [comment]
J'ai fait le test avec un user test, ça semble marcher, pas d'erreur 500.
Par contre il faut cliquer 2 fois sur le bouton inscription pour que ça marche bien, c'est un peu contre-intuitif (ou alors changez le message comme ça c'est clair).

J'ai test avec : https://w-alter.mfr.asso.fr/workspaces/13604/open
&                    https://w-alter.mfr.asso.fr/workspaces/13541/open
