### ISSUE TITLE
Bug : ouverture et fermeture d'onglet dans EA

### ISSUE THREAD

**Issue by SophieGuillemin** [claroline/Distribution#5643]
Plusieurs utilisateurs me font remonter un bug sur PadINT. Lorsqu'ils tentent d'ouvrir une ressource bloquée en date au lieu d'avoir un message leur indiquant que la ressource n'est pas visible cela ouvre et ferme un nouvel onglet empêchant la navigation dans l'espace. Ce problème a déjà été signalé la semaine dernière, il n'est visible qu'en étant connecté en tant que collaborateur.
Exemple : https://padint.intefp.fr/workspaces/3400/open/tool/home#/tab/20ca71fc-dd42-11e8-a47b-0cc47a960f96 visible avec le rôle ITS_FilièreNE onglet Filière non Exp. lien hypertexte 014. PRP 1 11/03/19 au 15/03/19
Merci

**Comment by SophieGuillemin** [comment]
Ce bug devient très handicapant dans l'utilisation de la plateforme car nous partageons des espaces avec des utilisateurs ayant différents rôles. Le fait que ces utilisateurs est des rôles différents et des accès aux ressources différents génèrent ce problème. Les ressources ne sont donc plus accessibles pour un grand nombre d'utilisateus

**Comment by ngodfraind** [comment]
Reproduit

**Comment by WalterMFR** [comment]
Bonjour,
J'ai plusieurs utilisateurs qui ont reproduit cette erreur.
Apparemment, cette erreur sévit depuis la semaine dernière mais il nous a été remonté qu'hier.
Je n'ai pas réussi à la reproduire localement même avec les comptes correspondants.

J'ai réussi à contourner le problème sur Firefox :
- mettre firefox à jour
- flush dns et supprimer les historique de navigation
- installer un blocker de pop-up et les refuser la première fois qu'ils sont proposées sur Claco.

Voici le bug en question (il est méchant quand même!)
`<iframe src='https://mfr.inwicast.tv/videos/?video=MEDIA190315115341124' width='640' height='360'  frameborder='0' scrolling='no' marginwidth='0' marginheight='0' allowfullscreen='true' webkitallowfullscreen='true' mozallowfullscreen='true' ></iframe>`

**Comment by LaurentGruber** [comment]
https://github.com/claroline/Distribution/pull/5656
