### ISSUE TITLE
Echec d'enregistrement des modifs dans quizz et parcours de formation

### ISSUE THREAD

**Issue by CEsbri** [claroline/Distribution#5646]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 

J'ai un bandeau "échec de la mise à jour " pour toute modification d'un parcours de formation ou d'un Quizz dans les Espace "Prépa AG 2019" et "Sport Santé"

**Comment by LaurentGruber** [comment]
Je ne reproduis pas le souci, sur aucun des 2 espaces, sur chaque fois un parcours pris au hazard ...

**Comment by CEsbri** [comment]
Dans l'espace AG 2019 / Dossier Séquence 2 / Parcours de formation Lettre de l'AG #1 : je ne peux pas enregistrer l'ajout d'une sous étape...

Dans l'espace Sport Santé Oct 2018 / Dossier Quizz sur Cours présentiel / Quizz :  je ne peux pas augmenter le nombre de tentatives à 5

Je viens de retenter l'ensemble et ça refuse l'enregistrement des modifications

**Comment by LaurentGruber** [comment]
je viens de le faire ici AG 2019 / Dossier Séquence 2 / Parcours de formation Lettre de l'AG, tu verras étape 1.2 test
Je n'ai pas eu d'erreur ...

**Comment by CEsbri** [comment]
Effectivement, maintenant ça marche! T'as fait quelque chose, ça ne marchait pas il y a 5' ...
Et le Quizz, je viens de tester... toujours echec de l'enregistrement...

**Comment by CEsbri** [comment]
Il y a toujours de pb d'enregistrement des modifications sur l'espace BAFA, j'ai voulu supprimer une section et idem!!!
