### ISSUE TITLE
PE : Gestion des couleurs - charte graphique

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#5655]
**Proposition Évolution PE**  
| Bug report?   | no
| Version?      | 12.3.7

ça serait sympa de pouvoir épingler ses couleurs (charte graphique) dans la bibliothèque. 
![CAPTURE 2019-03-14 à 09 47 56](https://user-images.githubusercontent.com/21193255/54345428-55568f00-4643-11e9-9c66-3e1779c0c5d1.jpg)

**Comment by Elorfin** [comment]
C'est prévu, mais ce ne sera pas pour tout de suite.
