### ISSUE TITLE
evolution : déléguer la fonctionnalité "se connecter en tant que"

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5662]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.3.7

Serait il possible de déléguer la fonctionnalité "se connecter en tant que", disponible à partir de la gestion des utilisateurs, à un autre rôle que celui d'administrateur ?

**Comment by LaurentGruber** [comment]
Cela pose plusieurs problèmes : 
- technique, il faut passer à symfony 4 pour pouvoir le faire (prévu pour la V13 qui n'arrivera pas avant 2020)
- RGPD, c'est une fonctionnalité très intrusive, quid du RGPD ...
