### ISSUE TITLE
zoom sur un pdf limité

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5664]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.7

Lorsqu'on affiche le pdf suivant : 
https://egreta.claroline.com/resources/show/file/0be672fa-3326-4b02-92ba-a04fdd32376f#/
Le zoom est limité à la largeur du viewer.

**Comment by LaurentGruber** [comment]
je ne comprends pas le problème ...

**Comment by flow39** [comment]
J'ai fait un screencast pour illustrer ma question :
https://youtu.be/Ng5FjADMdJA
On ne peut pas zoomer dans le fichier au delà de la largeur de la zone de visualisation du pdf. J'ai une utilisatrice qui voudrait utiliser un pdf qui semble énorme (cf lien précédent)
