### ISSUE TITLE
modification de l'affectation à une organisation impossible dans un profil utilisateur

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5666]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.7

Sur l'instance e-greta :
Pour deux comptes utilisateurs (cponsignon / ssolennel)
Si j'essaye de les détacher d'une organisation depuis la gestion des utilisateurs, l'application m'indique que la suppression est réussie mais l'organisation est toujours affecté.
![image](https://user-images.githubusercontent.com/7293233/54445685-8f0fbe80-4745-11e9-8a97-118e91a3dbb3.png)
![image](https://user-images.githubusercontent.com/7293233/54445696-98992680-4745-11e9-9168-f167252188e5.png)

**Comment by jbbrosset** [comment]
Nous rencontrons le même problème sur tous les utilisateurs rattachés à l'orga par défaut.
