### ISSUE TITLE
problème de restriction pour l'affichage d'un bureau d'accueil

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5667]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.7

Sur l'instance e-greta, nous avons un bureau d'accueil paramétré pour être restreint au rôle "académie de Clermont-Ferrand"
![image](https://user-images.githubusercontent.com/7293233/54445878-02193500-4746-11e9-8274-946b8cce17c1.png)
L'utilisateur ssolennel, qui n'a pas ce rôle, voit ce bureau.
![image](https://user-images.githubusercontent.com/7293233/54446031-53c1bf80-4746-11e9-8f90-8619aca670fa.png)

**Comment by Elorfin** [comment]
Corrigé en 12.5.
