### ISSUE TITLE
Ajouter champ URL dans ressource Base de Données

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#5681]
| Bug report?   | no
| Version?      | 12.3.8

ça serait bien d'ajouter un champ URL pour insérer des adresses web dans les fiches ?

**Comment by LaurentGruber** [comment]
Tu peux le mettre dans un champ texte simple, qu'apporterait en plus un champ spécifique ?

**Comment by greg49** [comment]
à l’instar du champ email, ça rendrait le lien actif.
Sinon comment fais tu pour rendre le lien actif ?

**Comment by jbbrosset** [comment]
Avec un champ texte riche ? 
Celui qui saisi peut mettre en forme son URL (il me semble que ça se fait auto à la validation, ou en copier coller)

**Comment by greg49** [comment]
j'ai fini par utiliser un champ HTML qui permet dans l'éditeur d'insérer un lien
