### ISSUE TITLE
Déplacement de widget impossible 

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5688]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.3.8

Dans l'EA suivant, sur le bureau "parcours formation" :

https://egreta.claroline.com/workspaces/969/open/tool/home#/edit/tab/9dd122ea-3885-47cd-97e3-276fd239eee7

![image](https://user-images.githubusercontent.com/7293233/54835989-92fe8c00-4cc3-11e9-8ad9-017333d22aa1.png)

Je n'arrive pas à déplacer un widget de la 2ème section vers la 1ère section

Est-ce un bug ou est-ce que je loupe quelquechose ?
Merci.

**Comment by ngodfraind** [comment]
J'ai une erreur 500 lorsque je le fais en local, donc j'imagine que j'ai reproduit.
