### ISSUE TITLE
Impossible de Supprimer ou Dépublier des fiches dans BDD

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#5693]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.8

je tente de supprimer des fiches mais impossible.
https://colearning.claroline.com

![CAPTURE 2019-03-26 à 16 33 46](https://user-images.githubusercontent.com/21193255/55010719-fb5fad00-4fe4-11e9-9e9f-3127da54d1fb.jpg)

**Comment by Elorfin** [comment]
Je ne reproduis pas en 12.4.5.
