### ISSUE TITLE
Ressource Collecticiel (ou autre Outdated) bloque la suppression des espaces

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5695]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.8

Je rencontre une erreur lorsque je tente de supprimer un ancien espace (https://w-alter.mfr.asso.fr/workspaces/356/open/tool/home#/tab/2e3eb8ee-c80d-11e8-a47b-0cc47a960f96)

Code erreur : 
An exception occurred while executing 'DELETE FROM claro_workspace WHERE id = ?' with params [356]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mfr`.`icap__portfolio_widget_badges_badge`, CONSTRAINT `FK_25D41B98F7A2C2FC` FOREIGN KEY (`badge_id`) REFERENCES `claro_badge` (`id`))"

Impossible de supprimer les collaborateurs de la liste des utilisateurs également... le bouton est grisé.

**Comment by jbbrosset** [comment]
J'ai une erreur sur cet autre espace: https://w-alter.mfr.asso.fr/workspaces/2437/open/tool/resource_manager#/36416FB2-F9C7-4867-8883-DA7801D3D7B5

"An exception occurred while executing 'DELETE FROM claro_resource_node WHERE id = ?' with params [29070]:
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mfr`.`innova_collecticielbundle_drop`, CONSTRAINT `FK_71757239A8C6E7BD` FOREIGN KEY (`drop_zone_id`) REFERENCES `innova_collecticielbundle_dropzone` (`id`))"

En effet, il y a un collecticiel dans l'espace et impossible de le supprimer, le bouton n’apparaît pas en fait.
(https://w-alter.mfr.asso.fr/resources/show/innova_collecticiel/DCC83C6E-7452-4E89-A1D8-D097BD60FA2E#/)

**Comment by LaurentGruber** [comment]
La commande php app/console claroline:clean:resource-type nettoie la base et règle donc le problème.

**Comment by jbbrosset** [comment]
Pour info, j'ai toujours l'erreur lorsque j'essaye de supprimer cet espace :
https://w-alter.mfr.asso.fr/workspaces/356/open/tool/home#/tab/2e3eb8ee-c80d-11e8-a47b-0cc47a960f96
An exception occurred while executing 'DELETE FROM claro_workspace WHERE id = ?' with params [356]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mfr`.`icap__portfolio_widget_badges_badge`, CONSTRAINT `FK_25D41B98F7A2C2FC` FOREIGN KEY (`badge_id`) REFERENCES `claro_badge` (`id`))"

**Comment by ngodfraind** [comment]
Je pense que c'est une vieille table qui aurait déjà du disparaitre.

https://github.com/claroline/Distribution/blob/12.x/plugin/portfolio/Installation/Updater/Updater060200.php#L25

**Comment by ngodfraind** [comment]
Corrigé en lancant la commande: php app/console claroline:test_update IcapPortfolioBundle 6 7
