### ISSUE TITLE
[Evaluation] Bugs tests V12

### ISSUE THREAD

**Issue by FlorianV54** [claroline/Distribution#5696]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.3.x

### Évaluation
- [x] **Consultation de sa correction (équipe)**
La note ne s'affiche pas dans le widget et interface de la ressource (rond).
Participation des équipes non prise en compte dans l'interface de la ressource(même si les copies apparaissent et peuvent être corrigées).

- [x] **Date de soumission**
Date de soumission non prise en compte dans l'interface (affiché : "non soumis") pour l'utilisateur.

- [x] **Date de participation**
Date de participation non prise en compte dans l'interface.

- [x] **Pas de nom de l'équipe affichée (pour le correcteur)**

- [x] **Pas de note de l'équipe affichée**

- [x] **Refus de correction**
Message d'échec lors du refus de correction mais quand même pris en compte.

- [x] **Pourcentage de progression**
Le pourcentage de progression reste à 0%, en début, après l'envoie de données et correction, et après que l'évaluation soit terminée.
Case cochée dans https://github.com/claroline/Distribution/issues/5556, pourquoi ?

- [ ] **Score à la correction** (toujours NOK en 12.4.2)
Le barème du score durant la correction d'une copie (ex. barème /20) ne tient pas compte du barème de score total appliqué dans les paramètres de notation (ex. celui-ci est sur 20). 
Exemple à la correction d'une copie on peut appliquer la note de 61/20. On est techniquement pas bloqué ou avertie au-delà de 20/20.

**Comment by kitan1982** [comment]
Le problème de barème vient du fait que l'on modifie celui-ci alors que des corrections avaient déjà été faites.
A présent, lorsque l'on modifie le barème, tous les scores sont recalculés en fonction de sa nouvelle valeur.
Malheureusement, il n'est pas possible de corriger les évaluations où un changement de barème a été effectué avant ce fix, car son ancienne valeur est inconnue.

**Comment by FlorianV54** [comment]
Le problème de pouvoir techniquement mettre une note par exemple de 28/20, n’est pour moi pas lié au faite qu'il y ai déjà eu ou non des corrections déjà faites.
Je viens de créer une nouvelle éval vierge avec une notation (score total) sur 20, avec un autre utilisateur j'ai déposé une copie, puis avec le gestionnaire de l'éval j’ai corrigé cette copie. Et c'est là au moment de la correction que techniquement j’ai pu mettre une note 28/20 par exemple . A aucun moment je n'ai été bloqué ou avertie que le score total était de 20/20, et que donc je ne pouvais pas mettre une note au-dessus.

**Comment by LaurentGruber** [comment]
Ce n'est pas un problème de pouvoir mettre 28/20, quand j'enseignais il m'arrivait de noter 22 sur 20 car il y avait une question bonus, ou que c'était vraiment bien ... Je ne vois pas de raison de l'empêcher ....

**Comment by FlorianV54** [comment]
Donc c’est une réel volonté d’avoir fait comme ça en V12 ? car en V10 ce n'était pas le cas.
![Bureau 1_014](https://user-images.githubusercontent.com/20820725/55962908-13386180-5c72-11e9-903f-719579d5a9a4.png)
