### ISSUE TITLE
Widget liste des ressources d'un dossier

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#57]
_From @clarophil on March 23, 2016 14:55_

Il serait intéressant de disposer d'un widget permettant de liste les ressources contenues dans un dossier, si on clique sur une ressource on y accède, si on clique sur un dossier on voit son contenu dans le gestionnaire de ressources

_Copied from original issue: claroline/Claroline#731_

**Comment by CPASimUSante** [comment]
Au 28/11, le widget existe.
Cependant, le widget n'est pas user friendly : 
Si un gestionnaire à 2 Espaces d'Activité : EA1 et EA2 et dans chaque espace il a des ressources :

User 1 
---EA1
------fichier1
------blog1
------rep1EA1
---------fichierrep1
---------parcours1
---EA1
------rep2EA2
---------fichierrep2
---------parcours2

Au niveau de la page d'accueil de EA1, on met un widget "Liste des ressources"
=> il n'y a pas d'indication : 

- il peut accéder aux répertoires de EA1, EA2, EA1rep1 et EA2rep2
Or,  EA1 et EA2 (les racines) sont cochables mais pas sélectionnables (=> pb: pas de possibilité de lister les ressources qui s'y trouvent)
- il peut cocher et sélectionner EA2rep2 : cela n'affiche aucune ressource.
il semble que ce widget n'autrorise le listing que des ressources dans les répertoires de l'EA dans lequel il est créé.

Il faudrait :
- soit un message, qui indique ce qui peut être sélectionné, 
- soit empêcher de sélectionner ce qui est "impossible" (les racines, les répertoires des autres EA)
- soit modifier le fonctionnement pour autoriser ces cas
