### ISSUE TITLE
ERROR : ouvrir une ressource de l'espace d'activités

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#5706]
| Bug report?   | yes
| Version?      | 12.3.8

Impossible de paramétrer l'option "Ouvrir une ressource de l'espace d'activités"
![CAPTURE 2019-04-01 à 09 31 45](https://user-images.githubusercontent.com/21193255/55310704-6c79e700-5461-11e9-85f0-1b1dd1310ab3.jpg)

**Comment by Elorfin** [comment]
C'est corrigé en 12.3.9.

**Comment by greg49** [comment]
Extra Merci
