### ISSUE TITLE
[ExoBundle] Imposssible d'ajouter une ressource ou un fichier dans la question

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#5722]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.0

Pour les questions de types ouverte, texte à trous (et probablement d'autres)
Dans la case Question
Ouvrir le menu d'édition
Le bouton + ne réagit pas donc impossible d'ajouter une image

**Comment by Elorfin** [comment]
Je ne reproduis pas chez moi.
Tu pourrais me donner un lien où je pourrais tester stp ?

**Comment by clarophil** [comment]
J'ai vidé le cache, j'ai changé de user mais toujours rien.
Attention ça fonctionne avec le qcm mais pas les autres types de question
[https://claco.vinci.be/resources/show/ujm_exercise/98d360de-1d83-4d3d-bfcb-8d7200f3b973#/edit/f129f495-03c7-48d7-b7a3-cb012c7be7fe](url)

**Comment by Elorfin** [comment]
Merci.
C'est bon j'ai compris. En fait ça marche sur les choix parce que c'est le 1er déclaré.
