### ISSUE TITLE
[ExoBundle] & Banque de question

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5726]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.0

Le bouton "Importer des questions" renvoi sur une page blanche et oblige un refresh pour revenir à la page précédente.
A mon avis le soucis viens de la banque de question qui affiche ce message d'erreur :
Cannot read property 'SHUFFLE_NEVER' of undefined
TypeError: Cannot read property 'SHUFFLE_NEVER' of undefined at Object.0CIW (https://w-alter.mfr.asso.fr//dist/quiz-item-choice.3db48786a75c3d4b3812.js:1:592) at t (https://w-alter.mfr.asso.fr/dist/runtime.a07d29cd44d17d076f66.js:1:518) at Object.SjU+ (https://w-alter.mfr.asso.fr//dist/quiz-item-choice.3db48786a75c3d4b3812.js:1:11712) at t (https://w-alter.mfr.asso.fr/dist/runtime.a07d29cd44d17d076f66.js:1:518) at Object.NFjZ (https://w-alter.mfr.asso.fr//dist/quiz-item-choice.3db48786a75c3d4b3812.js:1:9967) at t (https://w-alter.mfr.asso.fr/dist/runtime.a07d29cd44d17d076f66.js:1:518) at Module.jffi (https://w-alter.mfr.asso.fr//dist/quiz-item-choice.3db48786a75c3d4b3812.js:1:16473) at t (https://w-alter.mfr.asso.fr/dist/runtime.a07d29cd44d17d076f66.js:1:518) at async Promise.all (index 0)

**Comment by Elorfin** [comment]
Pour le moment je ne reproduis pas chez moi.
On doit corriger toute une série de choses sur les exos dans les jours à venir. Je verrai si ça persiste après la prochaine maj.

**Comment by Elorfin** [comment]
C'est réparé.
