### ISSUE TITLE
[ExoBundle] Paramètres : échec de la mise à jour

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5730]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.0

Bonjour,
Je n'arrive pas à enregistrer aucun paramètre du questionnaire.
L'erreur se reproduit :
- pour toutes les actions
- sur chrome et firefox
- même sur une nouvelle ressource questionnaire

Voici l'erreur :
![image](https://user-images.githubusercontent.com/24249636/55545610-dd253b80-56cd-11e9-8eb4-111aaa3ad270.png)

Je vous remercie.

**Comment by Elorfin** [comment]
Je pourrais avoir l'url svp ? Je n'ai pas les infos suffisante dans le screenshot.

**Comment by jbbrosset** [comment]
Url du questionnaire en question :

https://w-alter.mfr.asso.fr/resources/show/ujm_exercise/d1ab0f19-56db-4c3d-bfa6-090c5f42ff62#/
Je n'arrive pas à reproduire en fait sur ce questionnaire

Mais je reproduit sur un questionnaire tout neuf qui n'a pas encore de question : 
https://w-alter.mfr.asso.fr/resources/show/ujm_exercise/eed224c8-8a27-4e98-b53b-bb962fc813a1#/edit/parameters
![image](https://user-images.githubusercontent.com/35995165/55554463-216f0680-56e3-11e9-89ce-736b2987affa.png)

A partir du moment ou je créé une question, même si je la supprime après, je ne rencontre plus le soucis.
