### ISSUE TITLE
PB : sélection du type de Quizz

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#5741]
| Bug report?   | yes
| Version?      | 12.4.1

Lorsque je choisis un type de quizz, par ex: Certification, la validation se passe bien. Mais le module ne garde pas mon choix en mémoire. Il bascule sur Questionnaire personnalisé. Si on change de nouveau le type dans la liste déroulante, il y a un Echec à la mise à jour. 

![CAPTURE 2019-04-06 à 16 10 25](https://user-images.githubusercontent.com/21193255/55670622-0fc66400-5887-11e9-80fd-bff84271d82e.jpg)
![CAPTURE 2019-04-06 à 16 10 45](https://user-images.githubusercontent.com/21193255/55670623-11902780-5887-11e9-92e5-d8cc3c8c99dc.jpg)
![CAPTURE 2019-04-06 à 16 11 17](https://user-images.githubusercontent.com/21193255/55670629-2c629c00-5887-11e9-9891-7636613b5ad4.jpg)

**Comment by LaurentGruber** [comment]
doublon
