### ISSUE TITLE
Forum - Nom de EA pied de page dans la notification 

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#5743]
| Q             | A
| ------------- | ---
| Bug report?   |  no
| Version?      | 12.4.1

Bonjour,

Si abonné aux notifications Forum, on reçoit des messages sans savoir la provenance, c'est-à-dire de quel EA il s'agit. Pouvez-vous rajouter le même pied de page que pour les notifications des annonces?

_claroline/Distribution Forum - Nom de EA dans la notification Notification enhancement
#5085_

**Comment by jbbrosset** [comment]
Hello,

Idéalement, on pourrait pas ajouter ça aux templates et faire en sorte de personnaliser les notifications ?

**Comment by Elorfin** [comment]
Les nouveaux messages des forums sont maintenant envoyés en utilisant un template (forum_new_message / Nouveau message dans un forum).

Dans le template on donne accès, au Forum / Sujet et Espace dans lequel le message a été posté.
