### ISSUE TITLE
[ExoBundle] Page blanche au changement d'étape et End Page

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5744]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.1

Avec le compte "Sébastien Viel"

Questionnaire 1 : https://w-alter.mfr.asso.fr/resources/show/ujm_exercise/97da1ff0-c509-4911-8a77-7cdc67bca9ab#/
**Page blanche à l'étape 2**

Questionnaire 2 : https://w-alter.mfr.asso.fr/resources/show/ujm_exercise/a50e7d20-dd3b-42fe-8279-1e7793454068#/
Questionnaire 3 : https://w-alter.mfr.asso.fr/resources/show/ujm_exercise/07b740be-1043-44cb-ad33-dc389c2c03c0#/play
**Page blanche dès le lancement du questionnaire**

Avec le Compte "Admin"
Les Pages de fin des questionnaires ne s'affichent pas, donc pas d'affichage des résultats et pas de retour possible.
![image](https://user-images.githubusercontent.com/35995165/55706851-8a57c680-59e2-11e9-9056-9686587b26b8.png)

**Comment by Elorfin** [comment]
Corrigé par https://github.com/claroline/Distribution/pull/5738.
