### ISSUE TITLE
URGENT - Page blanche sur la ressource " Questionnaire"

### ISSUE THREAD

**Issue by OLIVIERISRPP** [claroline/Distribution#5748]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4

Bonjour,
Je rencontre le problème suivant:
Lors de l'enregistrement de mon questionnaire, un message d'erreur apparait.
et lorsque je fais un questionnaire, à la fin de celui-ci, avant j'avais soit la possibilité de le refaire ou de voir les résultats... maintenant j'ai une page blanche.
Merci beaucoup

**Comment by LaurentGruber** [comment]
déjà corrigé

**Comment by OLIVIERISRPP** [comment]
Bonjour 

Je suis désolé mais le problème est toujours présent 

Je reste à votre disposition pour de plus amples renseignements.

Cordialement 

Olivier DELEFLIE 
ISRPP Formation 
www.isrpp-formation.com
06 21 75 20 11
