### ISSUE TITLE
Fiche Utilisateur : retour à la liste

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#5750]
| Bug report?   | no
| Version?      | 12.4.1
Dans un EA, au niveau des utilisateurs, lorsque l'on clique sur un utilisateur, on ouvre sa fiche.
Je propose de faire apparaitre le fil d'Ariane à ce niveau pour permettre un retour à la liste des utilisateurs ou un bouton retour.

![CAPTURE 2019-04-10 à 11 02 06](https://user-images.githubusercontent.com/21193255/55866384-89f53200-5b80-11e9-97eb-4664e5450fd3.jpg)

**Comment by LaurentGruber** [comment]
On peut y arriver de trop d'endroit différent, ça ne pourra pas se faire sans une refonte complete de la navigation, donc ça ne viendra pas pour le moment.
