### ISSUE TITLE
import d'utilisateur par csv, groupe non attribué

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5755]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.4.1

Bonjour, 

J'essaye d'importer un utilisateur par csv, et le groupe que je renseigne sous l'intitulé groups.name n'est pas attribué.
[test-florian - Copie.txt](https://github.com/claroline/Distribution/files/3064218/test-florian.-.Copie.txt)

**Comment by ngodfraind** [comment]
Reproduit
