### ISSUE TITLE
Widget Espaces d'activité publics

### ISSUE THREAD

**Issue by philmercen** [claroline/Distribution#5757]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.4.2

A l'instar du widget Mes espaces d'activité, serait-il possible de disposer aussi d'un widget Espaces d'activité publics?

Pour info, lorsque j'utilise le widget Liste d'espaces, les trois points permettant d'accéder à l'inscription n'apparaissent pas.

**Comment by LaurentGruber** [comment]
il existe déjà, je te montrerai
