### ISSUE TITLE
Ressource questionnaire : plantage affichage résultats

### ISSUE THREAD

**Issue by AnneZarka** [claroline/Distribution#5758]
Urgentissime : sur le questionnaire 
https://egreta.claroline.com/resources/show/0c08c681-66ef-41a7-943d-7619d8161bb5
Impossible d'accéder à la page des résultats.
Pour les utilisateurs : lorsqu'on clique sur "terminer", page blanche 
Pour les gestionnaire : Impossible d'accéder aux résultats ("voir les résultats")
On a tenté : la suppression d'une question ouverte + le changement de paramètre dans le type de questionnaire (de "eval" à "personnalisé"), sans succès.
NB : test effectué sur d'autres questionnaires également ; la plupart des autres questionnaires testés fonctionnent. Le pb, c'est que c'est celui-là qui est mis en prod en ce moment sur une formation de prise en main de la plateforme !!!!!!!

| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

**Comment by Elorfin** [comment]
Problème de migrations.
> Error: Unknown item type application/x.boolean+json

Il faut transformer les questions Vrai/Faux dans les papers.

**Comment by AnneZarka** [comment]
Bonjour, fausse joie, ça ne fonctionne toujours pas pour les gestionnaire malgré la modification. Le participant a accès à sa page de résultats mais pas les gestionnaires. En outre, les scores n'ont pas l'air de remonter... (je suis passée par "voir les résultats" en me connectant "en tant que")
