### ISSUE TITLE
[Plugin][VideoPlayer] Download audio resource

### ISSUE THREAD

**Issue by pitrackster** [claroline/Distribution#576]
When attempting to download an audio file (one recorded with AudioRecorder plugin) the file has no extension...

**Comment by pitrackster** [comment]
might be an AudioRecorder plugin problem!

**Comment by pitrackster** [comment]
The problem is in `ResourceManager->download()` method.

The method checks if the ressource is a `'file'` with the `resource->resourcetype->name` property. If not the mime type is set to `plain/text`. It seems that every other resource (ie all but not files) have a mime type set to `custom/my_plugin`, or a file mime type (this is the case with audio recorder and video recorder, they are not files but generates files from recorded stream so there mime type is set artificially)

I do not now if my solution could generate side effects but we could do something like this : 

Replace : 

`$data['mimeType'] = $nodes[0]->getResourceType()->getName() === 'file' ? $nodes[0]->getMimeType() :  'text/plain';`

With : 

`$data['mimeType'] = !strpos($nodes[0]->getMimeType(), 'custom') ? $nodes[0]->getMimeType() : 'text/plain';`

@claroline/core What do you think ?

**Comment by stefk** [comment]
That could work but the mime type logic used in the core is flawed IMO, so it might be a good occasion to fix it, at least partially.

1. we shouldn't return `text/plain` if we don't know the mime type of the resource. That's against the spec and can be a security hole. We shouldn't send any content-type header if we don't know the type.
2. introducing `custom/xyz` mime types was an error (as there's a standard/ way to define custom types) but if we can't get rid of them now, at least we could use a more robust way to detect them. The class `Symfony\Component\HttpFoundation\File\MimeType\MimeTypeExtensionGuesser` should help here.

**Comment by pitrackster** [comment]
So I changed the manager method as follow 
`
$guesser = ExtensionGuesser::getInstance();
$data['mimeType'] = $guesser->guess($nodes[0]->getMimeType()) !== null ?  $nodes[0]->getMimeType() : null;`

And in the controller `downloadAction` added the condition 

`if ($mimeType !== null) {
            $response->headers->set('Content-Type', $mimeType);
  }`

It seems to work properly.
Something that I don't understand it's that every kind of resource is "downloadable" but when I download a Forum (for exemple) I get an empty HTML file...

**Comment by stefk** [comment]
> Something that I don't understand it's that every kind of resource is "downloadable" but when I download a Forum (for exemple) I get an empty HTML file...

ping @ngodfraind

**Comment by stefk** [comment]
Fixed in #597.
