### ISSUE TITLE
EA - Utilisateurs : desinscription impossible

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5763]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.1

Bonjour,
J'ai reproduit une erreur signalée par un gestionnaire d'espace d'activités dans la gestion des utilisateurs.
En effet, il est impossible de supprimer/desinscrire des utilisateurs.
Voici une capture :
![image](https://user-images.githubusercontent.com/24249636/56190721-25781e00-602b-11e9-9b22-1ebe855732b7.png)
Lien : https://w-alter.mfr.asso.fr/workspaces/2379/open/tool/users#/users
Me contacter par mail pour la liste des utilisateurs à supprimer.

Merci de votre attention.

**Comment by LaurentGruber** [comment]
ils n'ont pas été inscrit via un groupe par hazard ?

**Comment by WalterMFR** [comment]
Hum, bien vu! ;-) J'avais oublié ce facteur qui était plus facile à repérer avec la couleur d'utilisateur de la V11.
Merci beaucoup!

**Comment by LaurentGruber** [comment]
de rien
