### ISSUE TITLE
Enhancement : Administration > gestion du support > Commentaire

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5766]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.4.1

Bonjour,
Je me permets de remonter une suggestion concernant les commentaires de gestion du support.

![image](https://user-images.githubusercontent.com/24249636/56198737-ce2e7980-603b-11e9-8471-c870f8e51430.png)

Lorsque l'on échange via les commentaires avec l'utilisateur qui a envoyé un ticket, il n'y a pas, sauf erreur de ma part, d'information de date et heure d'envoi du message.

C'est une information qui pourrait être utile pour le suivi.

Je vous remercie de votre attention.

**Comment by Elorfin** [comment]
En fait il s'agit d'un bug.

**Comment by Elorfin** [comment]
C'est corrigé en 12.5.
