### ISSUE TITLE
Erreur MaJ

### ISSUE THREAD

**Issue by Sarcasthik** [claroline/Distribution#5767]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.3.4

Lors de la mise à jour de la plateforme, j'exécute sans souci "composer update --no-dev" puis   
"npm install" par contre arrivé à la 3ème commande "composer build" j'ai cette erreur qui apparait : 

Entry module not found: Error : Can't resolve '/var/www/Claroline/vendor/innova/audio-recorder-bundle/Resources/modules/public/js/audio-recorder' in /var/www/Claroline' 

Erreur que je ne saurai résoudre malheureusement, mais voici le log si ça peut aider :

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'webpack' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prewebpack', 'webpack', 'postwebpack' ]
5 info lifecycle claroline@1.0.0~prewebpack: claroline@1.0.0
6 info lifecycle claroline@1.0.0~webpack: claroline@1.0.0
7 verbose lifecycle claroline@1.0.0~webpack: unsafe-perm in lifecycle true
8 verbose lifecycle claroline@1.0.0~webpack: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle$
9 verbose lifecycle claroline@1.0.0~webpack: CWD: /var/www/Claroline
10 silly lifecycle claroline@1.0.0~webpack: Args: [ '-c',
10 silly lifecycle   'webpack --config=vendor/claroline/distribution/webpack.config.prod.js --progress $
11 silly lifecycle claroline@1.0.0~webpack: Returned: code: 1  signal: null
12 info lifecycle claroline@1.0.0~webpack: Failed to exec webpack script
13 verbose stack Error: claroline@1.0.0 webpack: `webpack --config=vendor/claroline/distribution/webpac$
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/$
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/$
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid claroline@1.0.0
15 verbose cwd /var/www/Claroline
16 verbose Linux 4.18.0-17-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "webpack"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error claroline@1.0.0 webpack: `webpack --config=vendor/claroline/distribution/webpack.config.prod.j$
22 error Exit status 1
23 error Failed at the claroline@1.0.0 webpack script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Si quelqu'un a une idée pour éclairer ma lanterne je suis preneur ! Merci d'avance !

**Comment by LaurentGruber** [comment]
essayer un composer bundles
Si ça ne suffit pas aller dans app/config/bundles.ini et chercher la ligne avec quelque chose du genre de InnovaAudioRecorder et la mettre à false voir la supprimer ...

**Comment by Sarcasthik** [comment]
J'ai testé "composer bundles" puis à nouveau "composer build" mais la même erreur survient.

J'ai donc suivi vos conseils en me rendant directement dans app/config/bundles.ini pour modifier la ligne Innova\AudioRecorderBundle\InnovaAudioRecorderBundle en false puis à nouveau "composer build" et même résultat. 

Même résultat en la supprimant complètement du fichier bundles.ini, l'erreur est identique au premier post.

**Comment by LaurentGruber** [comment]
Vider node_modules et supprimer package-lock.json avant de recommencer le composer build

**Comment by Sarcasthik** [comment]
Je vide l'intégralité de /Claroline/node_modules/ ou /usr/lib/node_modules/npm/node_modules/ ?

La question est sans doute bête mais je préfère demander car en supprimant le contenu de l'un ou l'autre en plus de package-lock.json voici le log de l'erreur qui survient au moment du "composer build" : 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'webpack' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prewebpack', 'webpack', 'postwebpack' ]
5 info lifecycle claroline@1.0.0~prewebpack: claroline@1.0.0
6 info lifecycle claroline@1.0.0~webpack: claroline@1.0.0
7 verbose lifecycle claroline@1.0.0~webpack: unsafe-perm in lifecycle true
8 verbose lifecycle claroline@1.0.0~webpack: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle$
9 verbose lifecycle claroline@1.0.0~webpack: CWD: /var/www/Claroline
10 silly lifecycle claroline@1.0.0~webpack: Args: [ '-c',
10 silly lifecycle   'webpack --config=vendor/claroline/distribution/webpack.config.prod.js --progress $
11 info lifecycle claroline@1.0.0~webpack: Failed to exec webpack script
12 verbose stack Error: claroline@1.0.0 webpack: `webpack --config=vendor/claroline/distribution/webpac$
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/$
12 verbose stack     at ChildProcess.emit (events.js:189:13)
12 verbose stack     at maybeClose (internal/child_process.js:970:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid claroline@1.0.0
14 verbose cwd /var/www/Claroline
15 verbose Linux 4.18.0-17-generic
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "webpack"
17 verbose node v10.15.3
18 verbose npm  v6.4.1
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error claroline@1.0.0 webpack: `webpack --config=vendor/claroline/distribution/webpack.config.prod.j$
23 error spawn ENOENT
24 error Failed at the claroline@1.0.0 webpack script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by LaurentGruber** [comment]
c'était claroline/node_modules 

le npm install est bien passé ?

**Comment by Sarcasthik** [comment]
ok donc dans le doute j'ai revidé node_modules et supprimé package-lock.json puis "npm install" qui passe bien mais j'ai toujours la même erreur lors du "composer build" j'ai revérifié le bundles.ini pour voir si la ligne Innova\AudioRecorderBundle\InnovaAudioRecorderBundle était toujours bien supprimée et c'est bien le cas.

Entry module not found: Error : Can't resolve '/var/www/Claroline/vendor/innova/audio-recorder-bundle/Resources/modules/public/js/audio-recorder' in /var/www/Claroline'

Voici le log, il n'a pas l'air différent du premier mais au cas ou :  [log.txt](https://github.com/claroline/Distribution/files/3094327/log.txt)

**Comment by LaurentGruber** [comment]
tu es sur quel version de claroline ?

**Comment by Sarcasthik** [comment]
La version 12.3.4, j'ai du l'installer en février de cette année je crois

**Comment by LaurentGruber** [comment]
ton composer.json est bien équivalent à https://github.com/claroline/Claroline/blob/12.x/composer.json
et ton package.json à https://github.com/claroline/Claroline/blob/12.x/package.json
Si oui, je retenterais tout depuis le début ...

**Comment by Sarcasthik** [comment]
J'ai donc comparé les composer.json qui sont identiques à priori. Plutôt que de me battre j'ai simplement réinstallé une plateforme toute neuve comme recommandé, version 12.4.4. 
Cela dit nous rencontrons un autre problème sur la 12.4.4 au niveau du SQL : 

![1](https://user-images.githubusercontent.com/43416863/56883797-07b5aa80-6a68-11e9-8fcb-2f0720219c2d.jpg)

J'imagine que je pourrai simplement ajouter la colonne mais est-ce que ca sera suffisant ?

**Comment by Sarcasthik** [comment]
Bonjour,

Finalement après environ un an sur la version 12.4.5, j'ai souhaité mettre à jour vers la version la plus récente, histoire de corriger quelques bugs, à l'aide des mêmes commandes qu'il y a un an mais je rencontre un nouveau souci lié à OauthManager.php à la commande _php app/console claroline:update 12.x.xx 12.y.yy_

![image](https://user-images.githubusercontent.com/43416863/79013147-57519100-7b68-11ea-9499-c178fca9b34d.png)

J'ai déjà tenté de vider node_modules et supprimer package-lock.json puis de refaire la manipulation comme la dernière fois mais le problème persiste.. 

Toute aide sera la bienvenue !
