### ISSUE TITLE
Questionnaire : impossible de déplacer une question choix multiple

### ISSUE THREAD

**Issue by SophieGuillemin** [claroline/Distribution#5779]
Version 12.4.2.
Utilisation de la ressource questionnaire.
Au total 15 questions ont été créées (principalement de type choix multiple) dans une seule et même étape. Je souhaite déplacer la question 6 (qui se trouve être la dernière question), mais lorsque je clique sur "Plus d'actions"> "Déplacer", la plateforme se bloque et je ne parviens pas à effectuer la manip. Je travaille sur Google Chrome (Version 73.0.3683.103)
Lien vers le questionnaire :https://padint.intefp.fr/resources/show/ujm_exercise/f7d92cd2-20e8-46cf-8fdd-6b6cbf1c4552#/edit/04a98fe1-31bb-415a-b1e0-fad8983541a1
Merci

**Comment by LaurentGruber** [comment]
c'est déjà corrigé et ça sera là lors de la prochaine mise à jour.
