### ISSUE TITLE
page sur conultation des résultats dans des questionnaires

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5780]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.4

Bonjour,
Sur l'instance e-greta, dans les questionnaires suivants, la consultation des résultats bloque sur une page blanche :
https://egreta.claroline.com/resources/show/0c08c681-66ef-41a7-943d-7619d8161bb5#/
https://egreta.claroline.com/resources/show/ujm_exercise/fcb1d065-55bf-4fa4-b783-8ffe4dd59e59#/

**Comment by LaurentGruber** [comment]
j'ai accès à la liste des résultats sans souci ...

Peut être vider le cache ? ou j'ai mal compris le souci ?

**Comment by flow39** [comment]
Bonjour,
Voici des captures d'écran pour illustrer ma question :
Sur le questionnaire https://egreta.claroline.com/resources/show/ujm_exercise/fcb1d065-55bf-4fa4-b783-8ffe4dd59e59#/
Je vais sur "voir les résultats"
![image](https://user-images.githubusercontent.com/7293233/56884687-d7234000-6a6a-11e9-9a1f-bbdd8f2c8eb9.png)

La liste s'affiche :
![image](https://user-images.githubusercontent.com/7293233/56884792-22d5e980-6a6b-11e9-9b18-06de8111da86.png)

Quand je clique sur le lien de la colonne # (nbr de tentatives?) pour voir les réponses dans le détail, j'ai une page banche :
1ère entrée de la liste
![image](https://user-images.githubusercontent.com/7293233/56884917-70eaed00-6a6b-11e9-85c6-d4735f902802.png)

**Comment by Elorfin** [comment]
C'est corrigé par : https://github.com/claroline/Distribution/pull/5806.

**Comment by flow39** [comment]
Ok merci. Ce sera inclut dans la 12.4.6 ?

**Comment by Elorfin** [comment]
Oui
