### ISSUE TITLE
Widget liste de ressource > filtre parent : aucun résultat

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5781]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.4

Bonjour,

J'ai une erreur que je reproduis dans seulement un espace, pas ailleurs mais je ne comprends pas ce qui cloche.
Il s'agit d'un widget liste de ressource utilisant le filtre "parent", un dossier et sélectionné mais il n'y a aucun résultat.
![image](https://user-images.githubusercontent.com/24249636/56424892-561db900-62b2-11e9-9cda-221443f11430.png)
Lien : https://w-alter.mfr.asso.fr/workspaces/13372/open/tool/home#/tab/05af3f3d-df46-4ba9-88b9-eefdeee36ff4
Pour info, en bas de page, il s'agit du premier widget à gauche, qui fait appel au sous dossier "documents" contenu dans le dossier "critères 1" des ressources du même espace.
Lorsque je reproduis la même démarche dans un autre espace cela fonctionne.

Merci de votre attention.

**Comment by WalterMFR** [comment]
Bonjour, je me permets de bumper ce sujet.

En effet, sur la 12.4.7, le problème persiste, malgré mes vérifications (re-création, gestion des droits...)

Je vous remercie.

**Comment by LaurentGruber** [comment]
Je ne vois pas le widget en question, mais une solution pourrait être de mettre un widget de type ressource qui pointe vers le dossier en question non ?

**Comment by WalterMFR** [comment]
Bonjour,

Il s'agit des widgets listes de ressources en bas de page sur l'onglet "critère 1".
![image](https://user-images.githubusercontent.com/24249636/57433369-97154780-7238-11e9-8b5d-520f98b54eb2.png)
L'intérêt ici est de pouvoir afficher directement les documents car le dossier auquel on fait référence est une boîte de dépôt qui sera alimentée régulièrement.
Si on pointe juste vers le dossier, on va perdre l'utilisateur à naviguer dans les nombreuses ressources de l'espace.

Merci.

**Comment by jbbrosset** [comment]
@LaurentGruber J'ai testé le contournement via afficher une ressource, ça fonctionne bien.
Du reste il y a bien un bug sur le widget "Liste de ressource" qui n'affiche pas correctement les ressources contenus dans le dossier paramétré en "Parent".

On met en place le contournement mais pour coup c'est beaucoup plus long que de paramétrer un widget liste.

**Comment by jbbrosset** [comment]
Bon, j'ai réussi à rétablir l'affichage des ressources dans le widget liste.
Source du soucis : Les ressources étaient configurées en "Cacher" 

Je laisse ouvert le ticket parce que le comportement me pose question malgré tout : 
- Si on coche la config "Cacher" une ressource s'affiche pour le gestionnaire mais pas pour le collaborateur, pour ça OK
- Si on cherche a afficher une ressource cachée dans un widget "Ressource" le comportement est identique, pour ça OK
- mais si on l'affiche dans un widget "liste de ressources" les ressources cachées ne sont affichées pour personne. Pour le coup c'est plus cohérent.

L'utilisateur s'occupe d'enlever la config "cacher" sur toutes ses ressources et je reviens vous dire si on a encore des soucis ou clôturer si il faut.
