### ISSUE TITLE
PB Création Onglet Bureau v12.4.4

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#5782]
| Q 
| Bug report?   | yes
| Version?      | 12.4.4
Impossible de créer un autre onglet sur le bureau.
Erreur à l'enregistrement sur plusieurs plateformes
![CAPTURE 2019-04-20 à 16 17 22](https://user-images.githubusercontent.com/21193255/56458570-dd3d6080-6388-11e9-8031-ebaaa730838e.jpg)

**Comment by ngodfraind** [comment]
Reproduit (je crois).
