### ISSUE TITLE
Questionnnaire : évaluation par les pairs - Echec lors de la sauvegarde d'une correction

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#5783]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.4

Cela fonctionnait avec la 12.4.2 

**Outils Evaluation**
_Une grille de critères est prévue_
Corriger une copie
Echec de la création à la sauvegarde
Réponse XHR "Class \u0027\u0027 does not exist"
[https://claco.vinci.be/resources/show/claroline_dropzone/79c4cba7-488e-4182-b22e-c6e1b19c5bb7#/](url)
![image](https://user-images.githubusercontent.com/895878/56561125-95942000-65a6-11e9-8402-1271ab86d4c4.png)

**Comment by clarophil** [comment]
J'ai un autre message à présent
"Call to a member function setUuid() on null"

**Comment by LaurentGruber** [comment]
on ne reproduit pas sur l'eval que tu as mis en lien ... On a pu corriger sans souci ...

**Comment by clarophil** [comment]
ok en tant que collaborateur ça marche mais en tant que gestionnaire ça ne fonctionne pas.   J'ai inscrit Kitan comme gestionnaire dans cet espace.

**Comment by kitan1982** [comment]
Je viens de tester avec Kitan et j'ai pu sauvegarder ma correction.
C'est bien à la sauvegarde ? Ou à la soumission ?

**Comment by clarophil** [comment]
Ok j'ai trouvé le cas, c'est quand on est gestionnaire et qu'on n'a pas déposer de copie.  Pour moi, un prof doit pouvoir corriger une copie sans en déposer une sinon elle sera proposée aux étudiants à la correction.
Donc pour tester tu dois effacer ta copie avant d'essayer la correction.
