### ISSUE TITLE
[Urgent] Onglet | Création impossible

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5787]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.4

A la création d'un nouvel onglet dans un espace, on peux créer les contenu mais si on essaye d'enregistrer la modification l'erreur suivante apparaît : 
![image](https://user-images.githubusercontent.com/35995165/56579290-1582b000-65d0-11e9-8fc1-1601d7758610.png)

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
home#/edit/tab/50af60c6-0b5a-4039-b3dd-75208231de5b:1
{message: "Class '' does not exist", trace: Array(16)}

**Comment by jbbrosset** [comment]
Je viens de voir le doublon après coup ... https://github.com/claroline/Distribution/issues/5782

**Comment by jbbrosset** [comment]
En fait ça marche pas du tout...
Et pour le coup c'est plutôt du genre urgent...

**Comment by LaurentGruber** [comment]
déjà corrigé, ça sera dans la maj de ce soir
