### ISSUE TITLE
Web.claroline.com | Echec du commentaire sur blog

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5798]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.5

Je voulais juste ajouter un commentaire au billet de blog signifiant qu'on ne voyais plus apparaître les correctifs apportés par la MAJ hebdomadaire dans ces articles. 
Moi je trouvais que c'était une bonne idée.

Et là paf ! Censure :) 

![image](https://user-images.githubusercontent.com/35995165/56721097-792dea00-6744-11e9-9c46-22175a2e64c2.png)

**Comment by LaurentGruber** [comment]
Attempted to load class \u0022Options\u0022 from namespace \u0022Icap\\BlogBundle\\Serializer\u0022.\nDid you forget a \u0022use\u0022 statement for e.g. \u0022Symfony\\Component\\OptionsResolver\\Options\u0022, \u0022Fabiang\\Xmpp\\Options\u0022, \u0022FOS\\RestBundle\\Controller\\Annotations\\Options\u0022, \u0022Claroline\\OpenBadgeBundle\\Serializer\\Options\u0022, \u0022Claroline\\CoreBundle\\Entity\\Contact\\Options\u0022 or \u0022Claroline\\AppBundle\\API\\Options\u0022?"
