### ISSUE TITLE
Widget liste des ressources d'un tag

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#58]
_From @clarophil on March 23, 2016 14:52_

Il serait intéressant de disposer d'un widget permettant de lister les ressources qui ont un certain tag, par exemple j'ai tagué 2 fichiers, une vidéo et un forum "chapitre 1", dans l'onglet de l'espace je peux ajouter un widget qui listent toutes les ressources taguées chapitre 1, si je tague une nouvelle ressource elle vient s'ajouter au widget.

_Copied from original issue: claroline/Claroline#729_

**Comment by CPASimUSante** [comment]
Est-ce que ce n'est pas le cas avec le widget d'un WS : "Liste des tags sur les ressources" ?
![liste-des-tags](https://cloud.githubusercontent.com/assets/14015697/18585594/284f5728-7c18-11e6-8a7e-cdb902947a65.jpg)
