### ISSUE TITLE
 PB liste des EA incomplète pour copier ou deplacer des ressources

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#5800]
| Bug report?   | yes
| Version?      | 12.4.5
J'ai créé des EA dans hdv-press.fr
je souhaite copier ou déplacer une ressource dans ces nouveaux EA mais la liste n'affiche pas les nouveaux EA.
Sur le bureau, le widget Liste des EA n'affiche pas tous les EA que j'ai créés.
Y'a un truc qui cloche...

**Comment by LaurentGruber** [comment]
c'est que tu n'es pas inscrit à l'ea en question

**Comment by greg49** [comment]
ah je pensais qu'on était automatiquement gestionnaire quand on créait un EA... c'était bien le cas avant non ?
