### ISSUE TITLE
PB copie d'une ressource d'un EA à l'autre

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#5805]
| Bug report?   | yes
| Version?      | 12.4.5

sur hdv-press.fr, j'essaie de copier la ressource QCM -CQP dans EA DUCRETET vers le dossier Evaluation dans EA RESEAU DUCRETET 

J'ai une erreur ECHEC
![CAPTURE 2019-04-26 à 18 03 34](https://user-images.githubusercontent.com/21193255/56821516-d4e49a00-684e-11e9-8bd2-d82afefc00c4.jpg)

**Comment by SophieGuillemin** [comment]
Bonjour, 

Même souci (version 12.4.5).
Depuis l'EA https://padint.intefp.fr/workspaces/4071/open/tool/resource_manager#/d25ee974-d0bc-4ba6-86d5-dd510786f55c tentative de copier le dossier "Module e-learning" vers https://padint.intefp.fr/workspaces/3234/open/tool/resource_manager#/3f790ebf-9a21-4172-b588-e55e8af21c15 (dans un dossier Ressources e-learning), message d'échec de la création.
