### ISSUE TITLE
Création d'un EA perso lors de la création d'un utilisateur par csv ?

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5808]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.4.5

Bonjour,
Apparemment ce n'est pas possible de créer un EA perso lors de la création d'un compte utilisateur par fichier csv.
Est-ce que c'est une erreur de ma part ou est-il possible d'implémenter ça ?
Merci.

**Comment by ngodfraind** [comment]
Reproduit
