### ISSUE TITLE
avertissement "objet en cours de modification"

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5811]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.4.5

Bonjour,
Je rencontre parfois le message suivant lorsque j'essaye de modifier un EA appartenant à un autre gestionnaire :
![image](https://user-images.githubusercontent.com/7293233/56906042-c3df9700-6aa1-11e9-894f-48367181acf1.png)

Quand le message apparait alors que ce gestionnaire est déconnecté, est-ce qu'il y a un risque de perte de données si je clique sur "modifier quand même" ?

Merci

**Comment by LaurentGruber** [comment]
non, si le gestionnaire ne quitte pas correctement l'édition, on ne peut pas savoir qu'il est parti, c'est pour cela que le message affiche la date ...
