### ISSUE TITLE
Urgent | Copie de parcours 

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5813]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.5

Je dois absolument copier le parcours suivant :  https://w-alter.mfr.asso.fr/workspaces/3970/open/tool/resource_manager#/460744bf-bb05-4fb9-a30a-a43b4c1ba286

dans cet espace là : https://w-alter.mfr.asso.fr/workspaces/13645/open/tool/resource_manager#/17a1f58b-e61a-4ad6-8677-335c21e05fe0

Problème : il me fait une erreur de cascade. 
**"A new entity was found through the relationship 'Innova\PathBundle\Entity\Step#path' that was not configured to cascade persist operations for entity: Innova\PathBundle\Entity\Path\Path@000000001ca94081000000007b058b27. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Innova\PathBundle\Entity\Path\Path#__toString()' to get a clue."**

![image](https://user-images.githubusercontent.com/35995165/56947763-6ba2a680-6b2e-11e9-8a4b-381cf42431d1.png)

Est ce que c'est possible de fix, au moins pour cette copie là en particulier, très rapidement avant de réparer plus globalement ?

**Comment by Elorfin** [comment]
On est dessus.
