### ISSUE TITLE
Ressources | Erreurs lors de la copie 

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5816]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.5

Je profite du boulot lancé sur le parcours dans https://github.com/claroline/Distribution/issues/5813 pour faire une liste des erreurs que l'on rencontre lorsqu'on tente de copier une ressource :

**Wiki** *(exemples : https://w-alter.mfr.asso.fr/workspaces/247/open/tool/resource_manager#/142fe405-fe8f-45ba-b4f5-31dd8e5f8629 vers n'importe quel dossier)*
"An exception occurred while executing 'INSERT INTO claro_resource_node (license, creation_date, modification_date, showIcon, name, hidden, lvl, path, materializedPath, value, mime_type, published, author, active, fullscreen, closable, closeTarget, accesses, views_count, deletable, comments_activated, uuid, thumbnail, poster, description, accessible_from, accessible_until, resource_type_id, icon_id, parent_id, workspace_id, creator_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "2019-04-30 14:36:44", "2019-04-30 14:36:44", 1, "W-@lter tutoriel integrer Flux RSS~1", 0, null, null, "S'approprier W-@lter%B4809B15-5E9C-41F2-A8E3-F72FD0556497\/Tutoriels%3803BB8C-348C-4614-9B4F-723165BFC2FA\/W-@lter tutoriel integrer Flux RSS 1%033e0f98-57c5-42c3-ac01-695b56ec5b88\/", null, "custom\/icap_wiki", 1, null, 1, 0, 0, 0, "{\"code\":null,\"ip\":{\"activateFilters\":false,\"ips\":[]}}", 0, 1, 0, "033e0f98-57c5-42c3-ac01-695b56ec5b88", null, null, null, null, null, 7, null, 17935, 247, 16]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '033e0f98-57c5-42c3-ac01-695b56ec5b88' for key 'UNIQ_A76799FFD17F50A6'"

**Fichier PDF/image :** *(exemple : https://w-alter.mfr.asso.fr/workspaces/13627/open/tool/resource_manager#/84e8d8d0-62bf-451a-aac1-bc939fb62d34 )*
"Call to a member function setCommentsActivated() on null"

**Ressource Texte** *(exemples: https://w-alter.mfr.asso.fr/workspaces/247/open/tool/resource_manager#/B4809B15-5E9C-41F2-A8E3-F72FD0556497 vers n'importe quel dossier)*
"An exception occurred while executing 'INSERT INTO claro_resource_node (license, creation_date, modification_date, showIcon, name, hidden, lvl, path, materializedPath, value, mime_type, published, author, active, fullscreen, closable, closeTarget, accesses, views_count, deletable, comments_activated, uuid, thumbnail, poster, description, accessible_from, accessible_until, resource_type_id, icon_id, parent_id, workspace_id, creator_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "2019-04-30 14:52:53", "2019-04-30 14:52:53", 1, "ESPACE D'ACTIVITE~1", 0, null, null, "S'approprier W-@lter%B4809B15-5E9C-41F2-A8E3-F72FD0556497\/Tutoriels%3803BB8C-348C-4614-9B4F-723165BFC2FA\/ESPACE D'ACTIVITE~1%122a90f5-0694-438e-af77-2153b1a220a9\/", null, "custom\/text", 1, null, 1, 0, 0, 0, "{\"code\":null,\"ip\":{\"activateFilters\":false,\"ips\":[]}}", 0, 1, 0, "122a90f5-0694-438e-af77-2153b1a220a9", null, null, null, null, null, 3, null, 17935, 247, 16]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '122a90f5-0694-438e-af77-2153b1a220a9' for key 'UNIQ_A76799FFD17F50A6'"

**Questionnaire** *(ça devient répétitif)*
"An exception occurred while executing 'INSERT INTO claro_resource_node (license, creation_date, modification_date, showIcon, name, hidden, lvl, path, materializedPath, value, mime_type, published, author, active, fullscreen, closable, closeTarget, accesses, views_count, deletable, comments_activated, uuid, thumbnail, poster, description, accessible_from, accessible_until, resource_type_id, icon_id, parent_id, workspace_id, creator_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "2019-04-30 14:57:45", "2019-04-30 14:57:45", 1, "Questionnaire d\u00e9mo~1", 0, null, null, "Bac \u00e0 sable%5362B1CF-1087-402B-A126-9BC33682CF8B\/Questionnaire d\u00e9mo~1%8559302E-9910-494B-9F10-18BE28E6805E\/", null, "custom\/ujm_exercise", 1, null, 1, 0, 0, 0, "{\"code\":null,\"ip\":{\"activateFilters\":false,\"ips\":[]}}", 0, 1, 0, "8559302E-9910-494B-9F10-18BE28E6805E", null, null, null, "2015-09-24 23:50:38", null, 16, null, 5795, 841, 16]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '8559302E-9910-494B-9F10-18BE28E6805E' for key 'UNIQ_A76799FFD17F50A6'"

**Annonce** 
"Attempted to call an undefined method named "deserialize" of class "Claroline\AnnouncementBundle\Serializer\AnnouncementAggregateSerializer".
Did you mean to call "serialize"?"

**Forum**
"An exception occurred while executing 'INSERT INTO claro_resource_node (license, creation_date, modification_date, showIcon, name, hidden, lvl, path, materializedPath, value, mime_type, published, author, active, fullscreen, closable, closeTarget, accesses, views_count, deletable, comments_activated, uuid, thumbnail, poster, description, accessible_from, accessible_until, resource_type_id, icon_id, parent_id, workspace_id, creator_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "2019-04-30 15:01:58", "2019-04-30 15:01:58", 1, "Forum d'aide~1", 0, null, null, "Bac \u00e0 sable%5362B1CF-1087-402B-A126-9BC33682CF8B\/Forum d'aide~1%074C3B49-5DD4-40C1-AAF4-9D463902E8B0\/", null, "custom\/claroline_forum", 1, null, 1, 0, 0, 0, "{\"code\":null,\"ip\":{\"activateFilters\":false,\"ips\":[]}}", 0, 1, 0, "074C3B49-5DD4-40C1-AAF4-9D463902E8B0", null, null, null, null, null, 9, null, 5795, 841, 16]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '074C3B49-5DD4-40C1-AAF4-9D463902E8B0' for key 'UNIQ_A76799FFD17F50A6'"

**Cours**
"An exception occurred while executing 'INSERT INTO claro_resource_node (license, creation_date, modification_date, showIcon, name, hidden, lvl, path, materializedPath, value, mime_type, published, author, active, fullscreen, closable, closeTarget, accesses, views_count, deletable, comments_activated, uuid, thumbnail, poster, description, accessible_from, accessible_until, resource_type_id, icon_id, parent_id, workspace_id, creator_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, "2019-04-30 15:03:07", "2019-04-30 15:03:07", 1, "Cours D\u00e9mo~1", 0, null, null, "Bac \u00e0 sable%5362B1CF-1087-402B-A126-9BC33682CF8B\/Cours D\u00e9mo~1%3778e3a7-4830-451d-b475-041f232fddd4\/", null, "custom\/icap_lesson", 1, null, 1, 0, 0, 0, "{\"code\":null,\"ip\":{\"activateFilters\":false,\"ips\":[]}}", 0, 1, 0, "3778e3a7-4830-451d-b475-041f232fddd4", null, null, null, null, null, 14, null, 5795, 841, 16]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3778e3a7-4830-451d-b475-041f232fddd4' for key 'UNIQ_A76799FFD17F50A6'"

**Comment by Elorfin** [comment]
je penses que c'est également lié au ticket : https://github.com/claroline/Distribution/issues/5805.

**Comment by Elorfin** [comment]
Il reste 1 erreur qui n'est pas corrigée imo : 

Annonce
"Attempted to call an undefined method named "deserialize" of class "Claroline\AnnouncementBundle\Serializer\AnnouncementAggregateSerializer".
Did you mean to call "serialize"?"

**Comment by jbbrosset** [comment]
C'est passé dans la 12.4.7 ? 
Parce que ça nous fait toujours l'erreur, et pareil pour https://github.com/claroline/Distribution/issues/5813 on a toujours une erreur sur les parcours (Integrity failed au lieu de Cascading Failed mais bon ça bloque quand même )

On retrouve l'erreur de Serializer quand on tente une copie d'espace.

**Comment by jbbrosset** [comment]
Pour le parcours, j'ai l'erreur sur celui-ci : 
https://w-alter.mfr.asso.fr/workspaces/3970/open/tool/resource_manager#/460744bf-bb05-4fb9-a30a-a43b4c1ba286

J'essaye de copier cet espace là qui bloquait hier (qui devrait fonctionner grâce à https://github.com/claroline/Distribution/issues/5695, mais a priori c'est le SCORM qui bloque) : https://w-alter.mfr.asso.fr/workspaces/3970/open/tool/home#/tab/2e4d0f59-c80d-11e8-a47b-0cc47a960f96

"No serializer found for class "Claroline\ScormBundle\Entity\Scorm2004Resource" Maybe you forgot to add the "claroline.serializer" tag to your serializer."

**Comment by ngodfraind** [comment]
merci, je teste ça tout de suite

**Comment by ngodfraind** [comment]
J'ai pu exporter l'EA et le réimporter en local sur ma plateforme de dev.
La copie directe par contre, il y a une erreur. J'ai pas encore compris d'ou elle sort.

**Comment by ngodfraind** [comment]
Et puis comme par magie, ça refonctionne -_-.

**Comment by ngodfraind** [comment]
Copie effectuée depuis la ligne de commande (c'est un peu long sur les gros EA il a fallu 10s ici).
Le nouveau. Faut vérifier que c'est correct.

https://w-alter.mfr.asso.fr/workspaces/13664/open/tool/home#/tab/17fa655f-1121-4b0d-946a-bb992f2b0e7a

**Comment by jbbrosset** [comment]
J'ai transmis au responsable de l'espace afin qu'il jette un oeil.
A la copie, aucun utilisateur conservé dans le nouvel espace, ce n'est pas risqué ? 
Si un user sans droit d'admin ou de gestion d'orga fait une copie, il ne pourra pas retrouver l'espace non ?

**Comment by ngodfraind** [comment]
C'est une bonne remarque. Pour le moment c'est uniquement depuis l'administration. Je vais rajouter l'utilisateur qui fait la copie en tant que gestionnaire.

**Comment by jbbrosset** [comment]
La copie s'est bien passée apparement, seul détail, si je fais la copie ou lui en tant que user ou admin, le parcours est copié et un dossier est créé au nom du parcours, toutes les ressources afférents sont placées dedans.

Si vous faites la copie depuis la ligne de commande, l'espace est copié tel quel et les ressources restent à l'endroit ou elles sont, aucun dossier n'est créé.

**Comment by ngodfraind** [comment]
la copie par l'ui est faite avec la copie d'un EA ou la copie de la ressource directement ?

**Comment by LaurentGruber** [comment]
tu as copié juste le parcours ou tout l'espace ?

**Comment by jbbrosset** [comment]
J'ai retesté en effet ça ne le fait que si tu copie la ressource parcours, pas pour l'espace.
Il nous semblait que ça le faisait aussi lors de la copie d'espace dans les précédentes version.

Rien d'important en tout cas.
Copie parcours et copie espace fixed en tout cas pour nous.

Me semble que tout est bon on peut clôturer si c'est ok pour vous.
