### ISSUE TITLE
WS | Restriction / Cacher : Erreur + Comportement de l'option

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5834]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.8

Quand j'essaye de mettre un espace en "Caché" (Dans les configurations, puis "Restriction d'accès"), j'obtient un bandeau orange et l'erreur : "instance must be of type array"

J'essayais de tester si cette option avait toujours le même comportement : 
- Jusqu'à présent l'espace était bien caché des listes si l'option était cochée, mais seulement de la liste des espaces publics. 
- L'espace était toujours présent dans la liste "Mes espaces" si l'utilisateur était inscrit nominativement ou via un groupe.
- De mémoire, l'espace apparaissait aussi dans le ressource picker si l'utilisateur est inscrit nominativement (ou via un groupe).

Ces comportements sont normaux ? 
Si oui, comment faire pour donner accès à une ressource ou un espace à une partie dans Users sans utiliser le rôle "Utilisateurs" (qui est trop vaste, ça donnerait accès aux élèves et je ne veux donner accès qu'aux salariés)?

Merci d'avance,
PS : ![image](https://user-images.githubusercontent.com/35995165/57225207-0823e780-700c-11e9-806d-55d4f47cf706.png)

**Comment by LaurentGruber** [comment]
En ajoutant le rôle plateforme "salarié" sur la ressource en question et en lui donnant les droits.

**Comment by jbbrosset** [comment]
Cool cool cool
J'essaye ça et je vous fait un retour.

**Comment by jbbrosset** [comment]
ça marche très bien au niveau de la ressource.

Pour rendre l'espace visible, j'ai ouvert la lecture de l'accueil au rôle "Utilisateur" et j'ai coché "Cacher" dans les configurations.
