### ISSUE TITLE
Questionnaires - Bugs

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#5842]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      |12.4.8

Je ne parviens pas à faire des questionnaires avec des propositions sous forme d'images malgré une heure d'essais multiples.
Cad: 
- Dans un questionnaire de type **classement** : impossible de saisir toutes mes propositions, impossible d’enregistrer et l’ajout d'un intrus fait une page blanche
- Dans un choix multiple, le paramètre de présentation horizontale se désactive systématiquement et je ne vois pas ce que j'enregistre.

**Le timer** : Petite erreur sur le timer qui confond minutes et secondes

![image](https://user-images.githubusercontent.com/33163723/57295973-0ae61180-70cc-11e9-9cc6-ae3268c9b85f.png)
![image](https://user-images.githubusercontent.com/33163723/57295986-15081000-70cc-11e9-87c8-9cb5de8dd5d2.png)

**Comment by Elorfin** [comment]
Le bug sur la disposition des choix est corrigé par #5764

**Comment by Elorfin** [comment]
Idem pour le timer.
