### ISSUE TITLE
PB AGENDA - Affichage des événements

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#5851]
| Bug report?   | yes
| Version?      | 12.4.9

J'ai créé des événements sur une période de 2 mois ou plus.
Le bandeau de couleur s'affiche bien sur le premier mois mais pas les suivants.
![CAPTURE 2019-05-10 à 17 59 34](https://user-images.githubusercontent.com/21193255/57540850-f87b0a80-734d-11e9-84de-f0eabcd89114.jpg)
![CAPTURE 2019-05-10 à 17 59 48](https://user-images.githubusercontent.com/21193255/57540858-fa44ce00-734d-11e9-9e1f-8fc8751e79b3.jpg)
![CAPTURE 2019-05-10 à 17 59 56](https://user-images.githubusercontent.com/21193255/57540866-fb75fb00-734d-11e9-9f3c-9b977a593d63.jpg)

**Comment by LaurentGruber** [comment]
doublon
