### ISSUE TITLE
impossible de restreindre l'accès à un EA par date pour un créateur d'espace

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5857]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | 12.4.9

Bonjour,

Un utilisateur ayant le rôle créateur d'espace ne peut pas restreindre l'accès à ses EA par dates. Seul l'option "cacher" est disponible.

L'ensemble des restrictions est apparemment disponible que pour les administrateurs.

**Comment by LaurentGruber** [comment]
En effet, c'est volontaire. Si les créateur d'espace utilisais cette restriction, il n'aurait plus non plus accès à l'espace, seul les admins peuvent by-passer la restriction donc ce n'est disponible que pour les admin.
