### ISSUE TITLE
Evaluation | Copie en erreur 

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5867]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.9

Nouvelle erreur lors de la copie d'une ressource évaluation  :
"Binding entities to query parameters only allowed for entities that have an identifier."

La ressource en question est là : https://w-alter.mfr.asso.fr/workspaces/12304/open/tool/resource_manager#/6bb3bfe3-7c16-4e57-8b55-194e0dd3af38

**Comment by ngodfraind** [comment]
J'ai pas encore reproduit en local mais j'ai trouvé la source de l'erreur sur le serveur.

Il s'agit de la méthode deserializeParameters du DropzoneSerializer. Commenter l'appel résout le pb. Reste à trouver ce qu'il y a sur le serveur que j'ai pas en local.
