### ISSUE TITLE
Export ressource fichier PDF vers PDF

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5872]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.9

Bonjour,
Lorsque je télécharge (exporte) des ressources PDF vers mon ordinateur, le document téléchargé n'est pas reconnu (icône de fichier blanc ou vierge)

Le contournement est de rajouter une extension de fichier .pdf en renommant le fichier.

Je vous remercie de votre attention.

**Comment by ngodfraind** [comment]
J'arrive pas à reproduire. Possible d'avoir un lien ?

**Comment by WalterMFR** [comment]
Oui, bien sûr :
 https://w-alter.mfr.asso.fr/workspaces/2205/open/tool/resource_manager#/7a2e2994-e086-4e9a-9834-0fe73d9c8c00

**Comment by Elorfin** [comment]
Quand je vais dans le dossier en question je n'ai aucun problème pour télécharger les fichiers PDF. Le problème est-il toujours d'actualité?

**Comment by jbbrosset** [comment]
On les télécharge bien mais ceux qui ont un espace dans le nom se retrouve avec un nom tronqué et donc l'extension disparait. 
Du coup il faut rajouter l'extension manuellement une fois le fichier DL.
Corrigé en 12.5 me semble t il

**Comment by Elorfin** [comment]
La PR en question fixe des probs de téléchargement dans les documents uploadés des Evaluations.

C'est bon j'ai trouvé, le soucis c'est Firefox. Avec Chrome je ne reproduis pas, il gère bien les charactères spéciaux et les espaces.

**Comment by Elorfin** [comment]
C'est en effet corrigé en 12.5.
Je l'ai mis aussi sur la 12.x pour que vous puissiez l'avoir sans attendre la 12.5.
