### ISSUE TITLE
Questionnaire : page blanche au lancement pour répondre

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5875]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.9

Bonjour,

Dans un questionnaire créé hier, dans deux espaces différents le bug suivant a été reproduit plusieurs fois :
- ressource questionnaire créée avec une étape et une question.
- lancement pour répondre au questionnaire donne une page blanche pour le gestionnaire

![image](https://user-images.githubusercontent.com/24249636/58181765-ac648a00-7cac-11e9-8113-6a8dbb381786.png)

Le questionnaire se trouve sur le lien ci-dessous :
https://w-alter.mfr.asso.fr/resources/show/ujm_exercise/e24934fd-10ba-4abe-962b-29d2eb9bf5b5#/play

L'erreur ne se produit pas pour un administrateur.
Contournement possible : utiliser se connecter en tant que collaborateur, la le questionnaire marche.

Merci de votre attention.

**Comment by Elorfin** [comment]
Il y a des chances que ce soit corrigé par : https://github.com/claroline/Distribution/pull/5764.
A restesté après passage en 12.4.0.

**Comment by Elorfin** [comment]
Le problème persiste. Il doit y avoir un bug dans la vérification des restrictions d'accès : les admins peuvent passer parce que cette partie est bypassé pour eux.
