### ISSUE TITLE
[UrlBundle] Add parameter to open the URL  in another window

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#588]
Actually, the target of the URL is opened in the same window, it should be nice to set a parameter of the resource to be opened in another window or tab of the browser.

**Comment by stefk** [comment]
There's an open PR for that (#910) but it has flaws IMO. I've proposed a more general solution (https://github.com/claroline/Distribution/pull/910#issuecomment-240958322). We need to agree on it or something else.
