### ISSUE TITLE
TinyMCE : Image blob

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5906]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no ?
| Version?      | 12.4.12

Quand je copie/colle une image directement dans un champ de saisie de texte (ça m'est arrivé dans la création de ticket) rien ne se passe si le menu éditeur de texte riche n'est pas déployé.

Une fois que je clique sur l'icone "+" et que le menu apparaît, l'image se colle sans problème.

Bug or Feature ?

**Comment by LaurentGruber** [comment]
feature. Si le texte riche n'est pas déployé, c'est juste un champ texte simple... Il faut charger tinymce pour obtenir ses fonctionnalitée.
