### ISSUE TITLE
URGENT : Questionnaire - modifier mène à une page blanche

### ISSUE THREAD

**Issue by WalterMFR** [claroline/Distribution#5907]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.12

Bonjour, j'ai une erreur bloquante, reproduite plusieurs fois sur plusieurs questionnaires.
Lorsque je veux modifier/configurer le questionnaire j'ai une page blanche.

Je n'ai pas trouvé de contournement et j'ai testé sur Firefox et Chrome.

Je vous remercie de votre attention.

**Comment by LaurentGruber** [comment]
un ou deux lien ?

**Comment by WalterMFR** [comment]
Oui bien sûr :
https://w-alter.mfr.asso.fr/resources/show/ujm_exercise/20f34bf7-51b3-49cf-b72e-745e9b139811#/

**Comment by LaurentGruber** [comment]
ok c'est parce que tu n'as pas choisi le type de questionnaire, on doit forcer ce choix ...

**Comment by LaurentGruber** [comment]
c'était autre chose, c'est corrigé, le patch arrivera ce soir.

**Comment by WalterMFR** [comment]
Super, merci!
