### ISSUE TITLE
PB Gestion des droits - Comment identifier les personnes derrière leur statut

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#5909]
| Bug report?   | no
| Version?      | 12.4.12

J'ai un problème d'identification rapide des utilisateurs que je sélectionne dans les droits d'accès. En effet, seul le statut apparait (Gestionnaire, Collaborateur...) mais pas leur nom.
Du coup, je me retrouve avec plein de gestionnaires ou collaborateurs dans la liste et je ne sais plus qui est derrière ce statut ou rôle
![CAPTURE 2019-06-11 à 11 14 49](https://user-images.githubusercontent.com/21193255/59259751-a3773080-8c3a-11e9-9193-19f00a3c076c.jpg)

**Comment by LaurentGruber** [comment]
Ce sont des rôles e.a qui ont été ajouté par quelqu'un, je ne sais pas pourquoi, mais ce n'est vraiment pas une bonne utilisation ... On en parle quand on est en visio un de ces jours ...

**Comment by greg49** [comment]
ok mais la liste ci-dessus présente 3 gestionnaires. ils sont rattachés à quel EA ?On ne peut pas le voir d'ici ? Comment faire?
