### ISSUE TITLE
resource questionnaire : impossible de décocher le 1er choix dans question à choix multpiles

### ISSUE THREAD

**Issue by flow39** [claroline/Distribution#5915]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.12

Bonjour,
Dans une ressource questionnaire, nous avons crée des questions à choix multiples.
Lorsque je pratique le questionnaire, sur toutes les questions, j'ai le comportement suivant :

Je coche une réponse
![image](https://user-images.githubusercontent.com/7293233/59343197-95451500-8d0b-11e9-8f35-d762e59ba574.png)

Je ne peux plus décocher pour modifier ma réponse. Cela ne se produit que sur la première case que je coche. Si je coche d'autres cases (toujours dans la même question), j'arrive à les décocher.

Un des questionnaires qui pose problème : 
https://egreta.claroline.com/resources/show/ujm_exercise/8deed8ad-5bc7-4a7f-ac68-b0ae6eda0a28#/play

Une vidéo illustrant le souci : 
https://youtu.be/QfNjFTFukls

Merci

**Comment by lauramzz** [comment]
Bonjour
Il est toujours impossible de décocher 1° option qui a été coché dans un QCM dans la v12.4.14.
En mode « Commencer ». Je sélectionne une première réponse, puis une deuxième. 
Je valide pour passer à l’étape suivante, puis je reviens sur le QCM. Je peux décocher toutes les réponses sauf celle que j’ai cochée en premier, mais du coup je ne peux plus valider et passer à l’étape suivante.
Merci
