### ISSUE TITLE
Mise en forme des ressources : Echec de la mise à jour

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#5916]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.12

Lorsque qu'on rentre dans le menu "Modifier" d'un dossier et qu'on tente d'en modifier la mise en page (Grille / tableau, afficher le sommaire on / off, ...) un bandeau d'échec Orange apparaît, sauvegarde impossible.

L'erreur apparaît sur tous les espaces que j'ai pu tester

L'erreur :
Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
0: {path: "/id", message: "instance must be of type string"}
length: 1
__proto__: Array(0)

**Comment by LaurentGruber** [comment]
c'est typiquement une erreur de validation qui ne montre pas correctement ce qui ne va pas.

Mais c'est que avec la modif que tu as fais, il y a des champs obligatoire du formulaire que tu n'as pas rempli ...

**Comment by jbbrosset** [comment]
Je m'en doutais mais je n'arrive pas à identifier ce qui manque...
J'ai testé plein de config différentes et j'obtiens toujours le même message même en cochant tout.

**Comment by Elorfin** [comment]
C'est bon je reproduis.
ça vient de chez nous, je penses que je peux corriger facilement.
