### ISSUE TITLE
[PathBundle] Improve summary

### ISSUE THREAD

**Issue by Elorfin** [claroline/Distribution#594]
As stated by @eddymarques, the summary of path is not very comprehensible for Users.
We need to rethink it to make it more intuitive.

In a short time, I'm able to fix the responsive problem which cause the summary can not be closed on a small screen (the summary hides the button).
- [ ] Make propositions to a new summary system (which can be used in any modules, like lesson). This part is for you @eddymarques ;) 
- [ ] At least, make the summary more responsive (for @Elorfin).

**Comment by purplefish32** [comment]
This shouldent be mergend into 7.x

**Comment by Elorfin** [comment]
A new version of the summary have been integrated to the master branch.
