### ISSUE TITLE
Sélecteur de ressources qui retourne à la racine des espaces

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#5941]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.4.14

Ajouter un widget
Ressource

Le sélecteur présente toutes les racines des espaces et pas l'espace courant

**Comment by Elorfin** [comment]
Toujours présent en 12.5.
Il s'agit bien d'un bug car l'espace courant est bien ramené jusqu'au tinyMCE.
