### ISSUE TITLE
[Audio] EAE dans questionnaire

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#5990]
Permettre que le type contenu audio choississe un audio enrichi et l'affiche complètement.

**Comment by lauramzz** [comment]
Améliorations complémentaires pour l’Écoute Active Enrichie

Amélioration de l’affichage :
Quand  l’Ecoute Active Enrichie sera intégrée en tant que Contenu Audio dans le questionnaire, il serait souhaitable de :
•	Ne pas faire apparaitre le nom du fichier 
•	Ne pas faire apparaitre les icones « plein écran » et « plus d’options »
 
<img width="454" alt="image" src="https://user-images.githubusercontent.com/37373660/64120155-c3cb0d00-cd9b-11e9-99f6-6940eec13bc2.png">


Affichage de la transcription :
Lors de la lecture de l’audio, quand le curseur de lecture passe d’une zone sans aide/sans transcription à une zone avec transcription, le champ transcription « saute » 
Il faudrait que l’espace dédié à la transcription soit toujours visible même si elle n’est pas activée, afin d’éviter ce problème d’affichage, qui peut distraire l’étudiant
 
<img width="454" alt="image" src="https://user-images.githubusercontent.com/37373660/64120163-ca598480-cd9b-11e9-96b3-464e419fad4d.png">
