### ISSUE TITLE
Switch to claroline namespace

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#6]
PHP namespaces, route/services prefixes, etc.
- [ ] PresenceBundle
- [ ] ReservationBundle
- [ ] SupportBundle
- [ ] NotificationBundle
- [ ] CompetencyBundle
- [ ] FavouriteBundle
- [ ] UrlBundle
- [x] BadgeBundle
- [ ] BlogBundle
- [ ] WikiBundle
- [x] DropZoneBundle
- [ ] LessonBundle
- [ ] PortfolioBundle
- [ ] SocialMediaBundle
- [ ] WebsiteBundle
- [ ] oAuthBundle
- [ ] PathBundle
- [x] CollecticielBundle
- [ ] ExoBundle

**Comment by ngodfraind** [comment]
I can tell you this is going to mess up the updates again because we won't be able to detect if a plugin is already installed or not easily.

**Comment by stefk** [comment]
Right. And there's also stuff in db that would need to be updated, like resource types, bundle/entity names, etc. It's doable but not trivial. I just opened this as a reminder of what has been decided. In the long run this is the way to go IMO.
