### ISSUE TITLE
Questionnaire : Petit bug de calcul du score

### ISSUE THREAD

**Issue by jbbrosset** [claroline/Distribution#6011]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.14

Une image valant mieux que mille mots.
Normalement ça devrait afficher 22.
Le questionnaire en question : https://w-alter.mfr.asso.fr/resources/show/ujm_exercise/4bd412fb-9853-40d1-ac8a-533873cf6e1b#/

![image](https://user-images.githubusercontent.com/35995165/61218839-3eb86580-a713-11e9-8e47-05486f4187f1.png)

**Comment by Elorfin** [comment]
Il doit y avoir un problème d'arrondi sur la page d'accueil.
Si on regarde la tentative en question : https://w-alter.mfr.asso.fr/resources/show/ujm_exercise/4bd412fb-9853-40d1-ac8a-533873cf6e1b#/papers/22a9682f-7c19-4c2d-94f7-b1621de262ab, le score s'affiche correctement (pareil dans la liste des résultats).
