### ISSUE TITLE
[Exo Bundle] [Ordonnancement] Suppression impossible et dédoublement des items lors de la passation du questionnaire.

### ISSUE THREAD

**Issue by lauramzz** [claroline/Distribution#6021]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.14

Ce comportement s’est produit dans chaque type de questionnaire, à la fois dans des espaces personnel et dans des espaces communs. 
EA : PAA Italien, Questionnaire « Test Bugs Questionnaire», Testé avec un Rôle Admin et/ou Gestionnaire (Tester ou Commencer) et un Rôle Collaborateur.
https://innovalangues.claroline.com/resources/show/e8adfaa8-1d26-42af-9ab6-6d33265f7c98 
Description : Les boutons pour  supprimer les items ne fonctionnent pas. Les items ne s’effacent pas mais ils se dédoublent.

Si je supprime un des items (3), il se duplique, un retourne dans la colonne de gauche, l’autre s’est transformé en celui d’en-dessus (2). Si je supprime un autre item (1) il se transforme en un autre item (2). Si je continue à essayer de supprimer des items, ils se dupliquent à l’infini.

**Comment by LaurentGruber** [comment]
doublon
