### ISSUE TITLE
Widget agenda, impossible pour un utilisateur de consulter l'événement 

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#6029]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.15

Lorsqu'un utilisateur clique sur un événement du widget agenda le message suivant apparait :

L'action agenda_ n'a pas pu être effectuée sur l'espace d'activité . **ESPACE ACTIVITE**. Cet espace d’activité requiert une inscription par un gestionnaire. 

Pourtant l'utilisateur est bien inscrit dans cet espace.

**Comment by ngodfraind** [comment]
Il faut aussi que l'utilisateur ai accès à l'agenda de cet espace. Je viens d'essayer et la redirection ouvre directement l'outil. Je pense que si on ouvre la liste d'utilisateurs de l'EA => onglet roles => sections outil et qu'on coche l'agenda (puis qu'on sauve) pour le role incriminé le problème devrait se régler.

**Comment by l-matt** [comment]
Merci bien
