### ISSUE TITLE
Ajout d'un utilisateur dans des groupes

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#6033]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.15

Lors de l'ajout d'un utilisateur dans des groupes via la gestion des utilisateurs ET lorsque la liste des groupes est sur plusieurs pages, seuls les groupes cochés sur la première page (par exemple) sont sauvegardés. 
Il faut donc recommencer l'opération afin de sélectionner les groupes sur la deuxième page puis valider.

**Comment by LaurentGruber** [comment]
c'est le comportement normal, il n'y a pas de sauvegarde entre les pages ...
