### ISSUE TITLE
[CoreBundle] Profile Widget bug after removing "getVisibleFieldFacets" from FacetManager

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#606]
The problem is that in ```ProfileController -> myProfileWidgetAction```, in order to show the profile widget there's a call to the method ```getVisibleFieldFacets``` that is deleted and another one to ```getVisibleFacets``` that is deprecated. The result is a widget that throws a bug.

**Comment by ngodfraind** [comment]
Fixed by #671
