### ISSUE TITLE
Les EA ne sont plus affichés

### ISSUE THREAD

**Issue by l-matt** [claroline/Distribution#6099]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.17

Bonjour, 

Après avoir mis à jour de la 12.4.16 à la 12.4.17, les espaces d'activités ne sont plus affichés dans l'outil admin "Gestion des EA" et via le wigdet.
Ils apparaissent uniquement dans l'historique pour les derniers consultés et sont accessibles

**Comment by l-matt** [comment]
Suis-je le seul à avoir ce problème en 12.4.17 ?

**Comment by l-matt** [comment]
Avec le dernier commit pour archiver les EA, toutes les entrees de la table claro_workspace.archived se sont mis sur NULL et le script semble n'afficher que les entrées dont le champ archived est à 0

**Comment by ngodfraind** [comment]
Je change ça tout de suite.

**Comment by ngodfraind** [comment]
https://github.com/claroline/Distribution/pull/6104
