### ISSUE TITLE
"Disparition" des espaces d'activités

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#6120]
Depuis le passage à la version 12.4.17  la liste des espaces d'activités est vide, hormis ceux créés depuis cette version. 
![image](https://user-images.githubusercontent.com/31481850/64341310-5e1f9080-cfe8-11e9-8026-fa7b76814fe0.png)
C'est très gênant...

Même depuis la console d'administration c'est vide...
![image](https://user-images.githubusercontent.com/31481850/64341456-ab9bfd80-cfe8-11e9-9a0d-b34bb468af7c.png)

**Comment by l-matt** [comment]
Bonjour, Ca a été corrigé dans le #6105

**Comment by alainertveldt** [comment]
Super, pouvez-vous ou un membre de votre équipe mettre notre plate-forme à jour? D'avance merci

**Comment by l-matt** [comment]
Je passais par là voir les nouvelles, je suis juste un utilisateur.
