### ISSUE TITLE
[Enregistreur audio et vidéo] Exportation extension du fichier

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#613]
Placer automatiquement l'extension lors du téléchargement d'un fichier enregistré par enregistreur audio et enregistreur vidéo. En la plaçant manuellement, cela marche

![image](https://cloud.githubusercontent.com/assets/16414632/15935732/a02bee8a-2e68-11e6-83d1-6d7682d9d7f0.png)

**Comment by jj-quintin** [comment]
Idem  #576 à ceci près que ceci est également valable pour les vidéos créées avec l'enregistreur vidéo (pas seulement l'audio)

**Comment by pitrackster** [comment]
Already done for both video and audio via https://github.com/claroline/Distribution/pull/597
