### ISSUE TITLE
[Lecteur vidéo] MP4 lu avec flash

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#615]
Il semblerait que les vidéos MP4 soient lus avec flash. Est-ce normal ?

![image](https://cloud.githubusercontent.com/assets/16414632/15938227/9f148f16-2e72-11e6-9ad9-9ac937183c7b.png)

**Comment by pitrackster** [comment]
@jj-quintin je pense que ça vient des codecs (audio et ou vidéo) utilisés pour l'encodage de ton mp4 (le mp4 est un conteneur).

**Comment by ngodfraind** [comment]
Je pense que le lecteur vidéo utilise flash par défault (et html5 s'il ne
trouve pas flash).

2016-06-10 9:16 GMT+02:00 Guillou Patrick <notifications@github.com>:

> @jj-quintin <https://github.com/jj-quintin> je pense que ça vient des
> codecs (audio et ou vidéo) utilisés pour l'encodage de ton mp4 (le mp4 est
> un conteneur).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/claroline/Distribution/issues/615#issuecomment-225110481>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABVStpwig3lcHYySCpDhepZTnYk-aFpaks5qKQ9HgaJpZM4IyLkB>
> .
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by pitrackster** [comment]
@ngodfraind c'est pas sensé être un fallback ? Donc si je trouve pas le bon codec sur la machine cliente j'utilise flash ?

**Comment by ngodfraind** [comment]
Il y a moyen de changer l'ordre, mais il me semble que ça posait problème dans le temps (c'est peut-être plus le cas maintenant par contre).

**Comment by ngodfraind** [comment]
Je viens d'essayer en inversion l'ordre mais le lecteur flash reste bien meilleur sur firefox par contre (ça se lance tout de suite).
