### ISSUE TITLE
[ExoBundle] Descripteurs (référencement) des exercices

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#619]
@clarophil : Peut être également valable pour les parcours, voire l'ensemble des ressources  @LaurentGruber me dit que vous avez le même type de demande

Pouvoir référencer la ressource, ici les exercices, de manière à pouvoir générer une offre de formation qui correspond à la situation de l'étudiant ou à sa demande. Ceci dépasse le système de tag actuel (il s'agit d'avoir un système descripteurs, hiérarchique, en arborescence). Le référencement se ferait bien au niveau de l'édition de la ressource

Détail dans le fichier ci-joint

[Exobundle-Descripteurs.pdf](https://github.com/claroline/Distribution/files/308670/Exobundle-Descripteurs.pdf)

**Comment by clarophil** [comment]
On a déjà une échelle de niveaux dans les compétences et cela devrait nous suffire pour créer dans parcours dynamique.

**Comment by LaurentGruber** [comment]
@clarophil mais cela pourrait répondre au besoin de faire des parcours orienté référentiel métier non ?

**Comment by clarophil** [comment]
Finalement la partie métier ne servira que pour le test de positionnement et permettra de déterminer le niveau des compétences en passant par des tâches complexes, ensuite on bascule sur l'arbre de compétences pour la remédiation.

**Comment by stefk** [comment]
En tous cas, il est déjà possible de créer, depuis une ressource, une ou plusieurs associations avec des nœuds d'un référentiel, voire de référentiels différents, et ceux-ci sont bien sûr arborescents. Comment le parcours peut être généré en fonction de ces liaisons, cela reste à déterminer... Les besoins pourraient d'ailleurs varier d'un projet à l'autre.

**Comment by jj-quintin** [comment]
Ce dont on a besoin en réalité c'est que l'enseignant puisse (en toute indépendance, sans référentiel donc), à partir d'un exercice, le renseigner selon des champs pré-définis (langue = ...., niveau = ... discours =... genre = ...). Vous voyez ? Ce n'est pas un arbre hiérarchique. Et, si un champ manque, n'est pas renseigné, cela devrait encore fonctionner. 

Sur cette base (avec ce système de descripteurs), on développera un moteur qui permettra de proposer une offre de formation sur la base de ces exercices et de leurs descripteurs (une liste d'exercices, mais on pourrait faire la même chose pour les parcours ou autre ressources éventuellement, pq pas)

On en avait discuté avec Donovan à l'époque. Il disait que les Tag ne suffisaient pas, qu'il fallait adopter un système similaire mais plus structuré (de mémoire, je ne sais plus quel terme il avait utilisé en réalité)

**Comment by LaurentGruber** [comment]
c'est en cours via les compétences, le merge arrive dans quelques semaines, je ferme déjà pour ne pas oublier
