### ISSUE TITLE
Widgets | Nombre de résultats minimum = 30 au lieu de 15 cochés

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#6241]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      | 12.5.4

Le problème est toujours là depuis sept18 : on coche 15 on a 30 par défaut et un long ascenseur
https://github.com/claroline/Distribution/issues/5183

![image](https://user-images.githubusercontent.com/33163723/66061094-06206f00-e53f-11e9-90dc-95c7af713b2c.png)

![image](https://user-images.githubusercontent.com/33163723/66060992-de310b80-e53e-11e9-918c-e1ba3954b9e2.png)

**Comment by Elorfin** [comment]
C'est corrigé. Il faudra juste attendre la prochaine mise à jour pour l'avoir.

**Comment by npaille** [comment]
Merci !
