### ISSUE TITLE
Gestion communauté | affichage sablier infini

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#6258]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.4

L'affichage des communautés en passant par : 
- Administration > Communauté > Utilisateurs
- ou dans Communauté via un EA
donne un sablier infini (sauf F5) 

![image](https://user-images.githubusercontent.com/33163723/66290873-ad572a80-e8e0-11e9-8d51-776b89a48604.png)

![image](https://user-images.githubusercontent.com/33163723/66291045-16d73900-e8e1-11e9-8719-a940ccec1a32.png)

**Comment by Elorfin** [comment]
C'est corrigé.
