### ISSUE TITLE
Improvement : display TinyMCE Menu in non fullscreen view

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#626]
I was lloking for inserting image, adding a table and couldn't find it until @ptsavdar told me those buttons where "hidden" : several menus are accessible only when in fullscreen mode !
- Is it possible to display those menu in normal mode ?
- or add the buttons of almost mandatory tools (image, table, special char...) in normal mode
- or at least add a hint, that those features are displayable only in fullscreen

**Comment by jj-quintin** [comment]
Oui, c'est une demande des utilisateurs de notre côté aussi. Assez incompréhensible pour l'utilisateur de devoir agrandir l'éditeur pour obtenir plus de boutons, alors que le bouton "Tous les outils" pourrait être accessible directement, sans devoir passer par le plein  écran

**Comment by Elorfin** [comment]
Fixed.
