### ISSUE TITLE
Evaluation  | ajouter un document (suite)

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#6263]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      | 12.5.5

https://github.com/claroline/Distribution/issues/6257 
Je rouvre pour une petite finalisation, il subsiste un petit problème d'affichage
-quand on joint un doc, on ne le voit pas apparaître
-Idem quand on supprime, cela ne se rafraîchit pas.

![image](https://user-images.githubusercontent.com/33163723/66311710-5d438c80-e90f-11e9-82bb-bcb85f166315.png)

**Comment by Elorfin** [comment]
Le 2ème point a été corrigé aujourd'hui.

**Comment by npaille** [comment]
merci

**Comment by npaille** [comment]
L'absence d'affichage du fichier joint demeure
