### ISSUE TITLE
Ressource : export de dossier alors qu'il est caché

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6281]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.7

Créer un dossier
Créer un sous-dossier
Caché le sous-dossier
Ajouter un fichier dans le sous-dossier
Exporter le dossier principal

Le zip contient le dossier caché et le fichier alors qu'il ne le devrait pas

**Comment by LaurentGruber** [comment]
J'ai un peu réfléchi à la question et pour moi c'est juste le comportement normal.

L'option caché, est un param d'affichage qui masque l'élément des listes mes n'affecte pas ses droits. Pour empêcher ça, il faut soit décocher l'export, soit ne pas publier la ressource à priori.
