### ISSUE TITLE
Questionnaire : impossible d'ajouter un trou

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6282]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.7

Ajouter une question type Texte à trous
Sélection un mot
Ajouter un trou se positionne mal puis impossible de sauver la question
![image](https://user-images.githubusercontent.com/895878/66471039-fcd95a00-ea8a-11e9-832a-c08796775fb5.png)

**Comment by kitan1982** [comment]
Je n'arrive pas à reproduire le bug.

**Comment by clarophil** [comment]
C'est en fait quand on essaie de supprimer ou de modifier le trou que les problèmes commencent.
