### ISSUE TITLE
[Administration Paramètres] Non sauvegarde/application des changements

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#629]
Changements de paramètres sans effet et non sauvegardés pour

Général
Apparences
et suivante apparemment

![image](https://cloud.githubusercontent.com/assets/16414632/15968072/b7d6332a-2f2a-11e6-9029-57067d18e40d.png)

![image](https://cloud.githubusercontent.com/assets/16414632/15968141/0364f466-2f2b-11e6-96fe-209e89f51a94.png)

**Comment by LaurentGruber** [comment]
c'est le logo que tu voulais modifier ? après l'avoir téléchargé il faut cliquer dessus pour le sélectionner et puis sur ok. J'ai déjà eu l'impression que ça ne changeait rien parce que j'oubliais ça.

Cela résoud le souci ? Si c'est le cas. Il faudrait probablement permettre de sauter cette étape en faisant que quand on télécharge un logo il est automatiquement sélectionné.

Sinon tu peux préciser ?

**Comment by jj-quintin** [comment]
C'est peut-être de notre côté serveur. Bien sûr, je sélectionne le logo ;-) Mais comme indiqué, ce n'est pas seulement l'apparence : aucun des paramètres n'est sauvegardé. je modifie, je sauve, j'y retourne, les paramètres avant changement sont remis

**Comment by ngodfraind** [comment]
Impossible de reproduiire.
C'est toujours d'actualité ? Ça a plutôt l'air d'être un problème de permission sur le serveur.

**Comment by jj-quintin** [comment]
C'est très certainement du côté du serveur, du temps où je testais sur une instance de test chez nous

J'ai testé sur Master, c'est ok, je ferme
