### ISSUE TITLE
Agenda - Affichage des agendas des EA (sans être inscrit)

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#6307]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      | 12.5.7

Les collaborateurs voient l'agenda d'un espace non public auquel ils ne sont pas abonnés.
Pouvez-vous modifier les droits pour masquer cette information.

**Comment by LaurentGruber** [comment]
il le voit où ?

**Comment by npaille** [comment]
Bureau > Agenda
