### ISSUE TITLE
Agenda | Saisie d'un nouvel événement page vide

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#6313]
| Q             | A
| ------------- | ---
| Bug report?   | yes  
Version?      | 12.5.7

Depuis MAJ, plus de possibilité de saisie d'événements. Blocage sur page vide.
Erreurs console
![image](https://user-images.githubusercontent.com/33163723/66647232-a6098700-ec28-11e9-9ce2-4ba3ef3c40ff.png)

**Comment by ngodfraind** [comment]
L'erreur se produit lorsque l'ont clique exactement sur le numéro du jour dans l'agenda (sinon ça fonctionne).

**Comment by npaille** [comment]
Avec la saisie par "+", je n'obtiens pas plus de résultat avec mon compte
![image](https://user-images.githubusercontent.com/33163723/66808728-24697000-ef2c-11e9-9094-95f0f728caef.png)
