### ISSUE TITLE
[Exo Bundle] Questionnaire contenant un « Contenu Ressource » est bloqué pour Collaborateurs 

### ISSUE THREAD

**Issue by lauramzz** [claroline/Distribution#6319]
| Q             | A
| ------------- | ---
| Bug report?   | Yes
| Version?      | 12.5.7

Suite du bug https://github.com/claroline/Distribution/issues/6268

**Questionnaire contenant un « Contenu Ressource » est bloqué pour les Collaborateurs de l'EA** 

**En tant que Collaborateur de l’EA.**

- Accès au Questionnaire via un lien =>Bloqué sur Page Blanche à l'écran, rafraîchir ne sert à rien https://innovalangues.claroline.com/#/desktop/workspaces/open/test-paa-it/resources/new/play
Voici la console :
![bugContenuRessource3](https://user-images.githubusercontent.com/37373660/66746762-009e1f80-ee83-11e9-8560-09c81069814d.PNG)

- Si le Questionnaire est intégré au un parcours, celui-ci ne s'ouvre pas. https://innovalangues.claroline.com/#/desktop/workspaces/open/test-paa-it/resources/parcours-test-1/play/etape-1

- Exception : Mais si le questionnaire contenant le Contenu Ressource est intégré dans un widget dans un Onglet de l’EA, il est visible par le collaborateur...
![Collaborateur-QuestionnaireDansWidget](https://user-images.githubusercontent.com/37373660/66746478-3a225b00-ee82-11e9-8b0a-49ba4a7c009b.PNG)

**Comment by kitan1982** [comment]
Je n'arrive pas à reproduire ce bug.
La ressource utilisée comme contenu provient-elle bien du même espace que le questionnaire ?
Les droits d'accès à cette ressource ont-ils été donnés aux collaborateurs ?

**Comment by lauramzz** [comment]
Après plusieurs tests, je viens de découvrir ce qui bloquait :
Dans les paramètres du Rôle Collaborateur, nous avions décoché "Ouvrir" pour les Ressources, pour que les étudiants n'aient pas accès aux Ressources depuis le menu latéral. 

![ress](https://user-images.githubusercontent.com/37373660/66824390-77512080-ef48-11e9-9991-cfecaa633485.PNG)
![ress1](https://user-images.githubusercontent.com/37373660/66824732-2261da00-ef49-11e9-95f3-21366f61bcf1.PNG)

Maintenant que "Ouvrir" est coché, ça fonctionne, les Contenus Ressources dans les questionnaires sont visibles. 
Ce que je ne comprenais pas était que toutes les autres ressources (images, vidéos, audio) déjà intégrées dans les questionnaires et parcours, étaient toujours visibles pour le collaborateur, bien que "Ouvrir" était décoché.

Merci pour votre disponibilité
