### ISSUE TITLE
Navigation dans les outils.

### ISSUE THREAD

**Issue by ngodfraind** [claroline/Distribution#6326]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Il y a un bug reproductible sur l'estp. Les annonces ne se chargent pas et on a une erreur dans le navigateur. En tant normal ça fonctionne.

La procédure pour le reproduire est:

- aller dans les widgets des outils

![les outils](https://user-images.githubusercontent.com/1397430/66768888-f7797680-eeb3-11e9-8190-86bd8927ec53.png)

- Cliquer sur home

![erreur](https://user-images.githubusercontent.com/1397430/66768895-fc3e2a80-eeb3-11e9-9842-cf7cd38c398f.png)

Je crois que les annonces se chargent pas mais je suis pas sur.
Accéder à l'outil home par un autre endroit fonctionne bien.

**Comment by Elorfin** [comment]
Je ne reproduis plus.
