### ISSUE TITLE
Media credits

### ISSUE THREAD

**Issue by Pauooo** [claroline/Distribution#633]
Has something been thought to quote media credits (author, licence and origin) when the media is used (not only in the ressources) ? Legally we have to quote the author, the licence and the link to the original media.
It would be interesting that the credits of a media would be automatically shown. Could we imagine that when the user upload a media (image, video, sound) he has to fill in three fields (free-text field): author, licence and origin. When this media is used, this information would be shown under the media or in a tooltip ?

**Comment by jj-quintin** [comment]
Il y a déjà deux champs accessibles depuis le ss-menu de la ressource : Licence et auteur. Il faudrait d'ailleurs voir si ces champs suffisent, s'il ne faut pas les regrouper sous le terme crédits par exemple pour obtenir une modale avec plus de champs, s'il ne faut pas un champ supplémentaire et comment présenter le champ licence  (je pense que, en général, le choix se présente ss la forme d'une liste de licences). 

Actuellement, ces informations ne sont pas affichées ou accessibles depuis le player de la ressource (elles sont uniquement accessibles depuis ce sous-menu ressource dans l'espace des ressources).

Pour ne pas encombrer l'écran avec un affichage immédiat de ces informations (solution "sous la ressources" et éviter d'utiliser l'infobulle (ne fonctionnerait pas avec toutes les ressources et puis autant réserver l'infobulle pour un usage plutôt orienté vers l'aide, ce qui est sa vocation première en général), il reste je pense la solution d'un bouton, d'une icône, Crédits, à placer quelque part (à voir)
