### ISSUE TITLE
Ressources | message utilisateur ressource non publiée

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#6349]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      | 12.5.8

Dans un parcours, une ressource non publiée est liée (elle est grisée).
Quand un collab clique dessus, il n'y a plus le message indiquant que la ressource n'est pas encore été publiée (ou équivalent). Au lieu de cela, page grise.

![image](https://user-images.githubusercontent.com/33163723/67200833-1a041600-f405-11e9-9a74-5f51a1c210f8.png)
![image](https://user-images.githubusercontent.com/33163723/67200845-20928d80-f405-11e9-9dec-bbd943acc9dd.png)

**Comment by Elorfin** [comment]
Je n'arrive pas à reproduire le comportement et sur l'exemple en question il à l'air de fonctionner maintenant sur votre plateforme.

Mais d'après l'erreur que je vois, je penses plus qu'il y avait un problème avec le fichier lié et que ça ne concerne pas forcément le statut non publié.

Aurais-tu un autre exemple à me donner ?

**Comment by npaille** [comment]
Le problème est réglé.

**Comment by Elorfin** [comment]
OK dans ce cas je clôture.

**Comment by npaille** [comment]
Je peux te joindre pour un Pb

**Comment by Elorfin** [comment]
Oui. Tu peux aller sur https://gitter.im/ avec ton compte GitHub.
