### ISSUE TITLE
Problème à rajouter des questions à un parcours

### ISSUE THREAD

**Issue by cmhilairehwc** [claroline/Distribution#6352]
Bonjour,

En essayant d'ajouter des questions (Multiple Choices, Association...) à une étape d'un parcours, j'ai eu cette erreur retournée par Ajax. 
Pourriez-vous m'aider à trouver la cause du problème? Est-ce que c'est une erreur de manipulation?

![image](https://user-images.githubusercontent.com/56847884/67242735-20ee5100-f424-11e9-8f3d-1e6ac5c40f8b.png)

![image](https://user-images.githubusercontent.com/56847884/67242621-e1c00000-f423-11e9-9c28-ff07de4aa445.png)

Merci.

**Comment by LaurentGruber** [comment]
quelle version de la plateforme ?

**Comment by cmhilairehwc** [comment]
Version 9.1.0

**Comment by cmhilairehwc** [comment]
> 
> 
> quelle version de la plateforme ?

Version **9.1.0**

**Comment by LaurentGruber** [comment]
nous sommes à la version 12.5 et ne pouvons malheureusement pas supporter les versions antérieurs car nous n'en avons pas les ressources. Il faudrait envisager la mise à jour, mais vu le nombre de version à passer, elle ne sera pas simple non plus, désolé.
