### ISSUE TITLE
Equipe : configurer en échec

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6388]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Créer une équipe dans un espace
Cliquer sur l'équipe
Cliquer sur configuer
Changer un paramètre
Sauver

Url [https://claco.ecam.be/#/desktop/workspaces/open/3c0d39a1-b721-11e8-b44d-0cc47a960f96/claroline_team_tool/edit](url)
Echec
Erreur code 500
Réponse
{"message":"Call to a member function getUuid() on null","trace":[{"file":"\/home\/hevinci\/www\/vendor\/claroline\/distribution\/main\/app\/API\/SerializerProvider.php","line":161,"function":"serialize","class":"Claroline\\TeamBundle\\Serializer\\WorkspaceTeamParametersSerializer","type":"-\u003E","args":[{},[]]},{"file":"\/home\/hevinci\/www\/vendor\/claroline\/distribution\/main\/app\/API\/Crud.php","line":127,"function":"serialize","class":"Claroline\\AppBundle\\API\\SerializerProvider","type":"-\u003E","args":[{}]},{"file":"\/home\/hevinci\/www\/vendor\/claroline\/distribution\/main\/app\/Controller\/AbstractCrudController.php","line":384,"function":"update","class":"Claroline\\AppBundle\\API\\Crud","type":"-\u003E","args":["Claroline\\TeamBundle\\Entity\\WorkspaceTeamParameters",{"id":"025b03bd-fef8-4fb8-9b07-7c448abcb541","selfRegistration":false,"selfUnregistration":false,"publicDirectory":false,"deletableDirectory":false,"allowedTeams":1,"workspace":{"uuid":"11EA2E0F-2552-41F7-8619-43D0EBB52843"}},[]]},{"file":"\/home\/hevinci\/www\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/HttpKernel.php","line":151,"function":"updateAction","class":"Claroline\\AppBundle\\Controller\\AbstractCrudController","type":"-\u003E","args":["025b03bd-fef8-4fb8-9b07-7c448abcb541",{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},"Claroline\\TeamBundle\\Entity\\WorkspaceTeamParameters"]},{"file":"\/home\/hevinci\/www\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/HttpKernel.php","line":68,"function":"handleRaw","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1]},{"file":"\/home\/hevinci\/www\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/Kernel.php","line":200,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1,true]},{"file":"\/home\/hevinci\/www\/web\/app.php","line":37,"function":"handle","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"-\u003E","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]}]}

**Comment by kitan1982** [comment]
As-tu plus d'informations sur la marche à suivre (paramètres utilisés, rôles,...) ?
Je n'arrive pas à reproduire.

**Comment by clarophil** [comment]
Avec un rôle admin, ça plante quel que soit le paramètre changé.
Tu as essayé en local ou sur l'url envoyée ?

**Comment by clarophil** [comment]
C'est le même comportement dans tous les espaces de notre plateforme.

**Comment by kitan1982** [comment]
J'ai essayé en local et ça fonctionnait.
Sur l'URL plus haut, j'ai eu le souci effectivement.
Mais lorsque j'ai essayé sur un autre espace d'activités, fraîchement créé sur votre plateforme, je n'ai pas eu de problèmes.

**Comment by clarophil** [comment]
Ok mais qu'est-ce que je fais avec tous les espaces existants ?

**Comment by kitan1982** [comment]
Si le problème est juste lié aux anciens espaces, il faudra investiguer plus au niveau de la DB et peut-être faire un updater pour fixer le souci.
