### ISSUE TITLE
CLI CSV import

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#639]
- [x] lors de la création des user en CSV permettre l'ajout optionnel de l'organisation
- [x] lors de la création des WS en csv permettre de choisir de façon optionnel le modèle
- [x] permettre la création d'onglet de page accueil de WS via un csv [code WS, Titre onglet, Position (optionel) ]
- [x] permettre la crétion de widget depuis un csv [ code WS, titre onglet, titre widget, type widget, contenu (lien vers JSON - optionnel) ] + update contenu
- [x] permettre de créer des dossiers dans un WS depuis un csv [ code WS, titre dossier ]

**Comment by ngodfraind** [comment]
Voir #659 

- [x] lors de la création des user en CSV permettre l'ajout optionnel de l'organisation

**Comment by ngodfraind** [comment]
Voir #659 

- [x] lors de la création des user en CSV permettre l'ajout optionnel de l'organisation
- [x] déjà implémenté

**Comment by ngodfraind** [comment]
see #659

**Comment by clarophil** [comment]
Pour l'import des onglets, peux-tu ajouter quel workspace n'existe pas si j'ai le message  "workspace_not_exists" ?

**Comment by ngodfraind** [comment]
Juste, j'ai oublié les chaines de traduction. Je vais les rajouter.

**Comment by ngodfraind** [comment]
C'est fait.

**Comment by clarophil** [comment]
php app/console claroline:csv:workspace
Absolute path to the workspace file: /mnt/partage/ea.csv
  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Undefined index: copies

**Comment by clarophil** [comment]
php app/console claroline:csv:directorie

Le début du fichier fonctionne puis j'ai une erreur doctrine

[info] 06-21-16 08:57:40: Directory Laboratoire de techniques digitales already exists for workspace 2O4080
[info] 06-21-16 08:57:40: Create directory Systèmes digitaux for workspace 2O4080
[info] 06-21-16 08:57:40: Create directory Laboratoire de systèmes digitaux for workspace 2O4080
                                                                                  
  [Doctrine\DBAL\Exception\UniqueConstraintViolationException]                       
  An exception occurred while executing 'INSERT INTO claro_resource_type (name, is_  
  exportable, defaultMask, plugin_id) VALUES (?, ?, ?, ?)' with params ["directory"  
  , 1, 1, null]:                                                                     
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'directory'  
   for key 'UNIQ_AEC626935E237E06'                                                                                                                                        

                                                                                  
  [Doctrine\DBAL\Driver\PDOException]                                                
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'directory'  
   for key 'UNIQ_AEC626935E237E06'                                                   
                                                                                     
  [PDOException]                                                                     
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'directory'  
   for key 'UNIQ_AEC626935E237E06'

**Comment by ngodfraind** [comment]
Je sais d'ou ça sort, c'est le clear de doctrine.

**Comment by ngodfraind** [comment]
@clarophil ton fichier fait plus de 100 lignes ?

**Comment by clarophil** [comment]
oui

**Comment by clarophil** [comment]
@ngodfraind à part ces 2 problèmes là j'ai testé tout le reste

**Comment by ngodfraind** [comment]
J'm'occupe de ça tout de suite.

**Comment by ngodfraind** [comment]
Bon, j'ai compris d'ou ça venait pour le clear/merge de doctrine. Je peux pas simplement merge l'entité, je dois recharger depuis le dépot avant.

**Comment by ngodfraind** [comment]
Pour le widget, c'est effectivement la copie du widget depuis le modèle.

**Comment by ngodfraind** [comment]
@clarophil 
C'est bon.

**Comment by clarophil** [comment]
@ngodfraind j'ai tout testé aussi, ça marche
Est-ce que tu pourrais ajouter à l'import de widget text en option la largeur et la hauteur du widget ?

**Comment by clarophil** [comment]
Tous les scripts renvoient la réussite pour chaque ligne sauf php app/console claroline:csv:workspace qui ne renvoient rien

**Comment by ngodfraind** [comment]
Je vais te le rajouter alors; Il est plus ancien que les autres et a été écrit quand le logger n'existait pas encore.

**Comment by clarophil** [comment]
Pour home_text_widget, il faut traiter le fichier même si il y a des erreurs et faire un reporting des lignes erronées.
