### ISSUE TITLE
Accès restreint par IP aux excercie

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#64]
_From @LaurentGruber on March 22, 2016 13:26_

@david42 @marion42 @charlotte42
Active un filtrage par plages d’IP ou seuls les postes contenus dans ces plages seront autorisés à répondre au questionnaire. Les autres verront un message leur interdisant l’accès, empêchant de voir les questions.
Le filtrage est utilisé pour des passages d’examens en salles de TP en présentiel.

_Copied from original issue: claroline/Claroline#723_

**Comment by Elorfin** [comment]
Implémenté au niveau des ResourceNodes
