### ISSUE TITLE
Comportement après l'authentification Office 365

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6401]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.5.9

L'authentification Office365 fonctionne mais l'utilisateur n'a pas le fonctionnement normal, il manque 
- le message d'accueil
- la date de dernière connexion ne se met pas à jour
- si on met une page d'accueil à la plateforme, le chargement du bureau ne se fait pas toujours correctement
- après réauthentification, on retombe sur le bureau et pas à l'endroit où on était, c'est le plus embêtant

Une unification des comportements après authentification me semble indispensable

**Comment by livarkhal** [comment]
Bonjour,

Je vous réponds par une question qui n'a pas de rapport avec votre demande.
Nous sommes en train d'essayer de configurer l'authentification Office 365 dans notre organisation mais nous n'arrivons pas à le faire fonctionner ...

Pouvez-vous nous indiquer les étapes de configuration que vous avez suivi?

Un grand merci d'avance.

**Comment by clarophil** [comment]
Bonjour,

Oui on utilise Office365 comme SSO depuis plusieurs années, voici comment faire :
Dans /app/config/platform_ootions.yml  il faut paramétrer office 365:

o365active: true
o365client_id: xxxxxxxxxxxxxxxxxxxxx
o365domain: xxxxxxxxxxxxxxxx
o365pw:  xxxxxxxxxxxxxxxx

Il faut donc créer une application dans Azure
[https://aad.portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade](url)
![image](https://user-images.githubusercontent.com/895878/70053008-d50efa00-15d4-11ea-9d1b-68834b8747fc.png)

![image](https://user-images.githubusercontent.com/895878/70053034-de986200-15d4-11ea-964f-4ddab47edfd4.png)

![image](https://user-images.githubusercontent.com/895878/70053054-e6580680-15d4-11ea-8908-eec3353b090d.png)

![image](https://user-images.githubusercontent.com/895878/70053075-efe16e80-15d4-11ea-9e5a-a2cefebdd039.png)

Et ici on a le secret (o365pw)
![image](https://user-images.githubusercontent.com/895878/70053193-320ab000-15d5-11ea-8b47-6b2b49bfbe1d.png)

**Comment by clarophil** [comment]
@LaurentGruber peux-tu confirmer les paramètres dans platform_options.conf pour office365 ?

**Comment by Elorfin** [comment]
C'est dans /app/config/platform_options.json dpuis plusieurs versions :

```
"external_authentication": {
     "office_365": {
            "client_active": true,
            "client_id": "####",
            "client_secret": "####",
            "domain": "####"
     }
}
```

**Comment by livarkhal** [comment]
@clarophil Bonjour, et merci pour votre réponse.
Nous n'avons pas les accès aux fichiers du serveur pour le moment ... Nous essayons de contacter l'administrateur du serveur et nous allons essayer :D
