### ISSUE TITLE
Evaluation : téléchargement d'une production - fichier sans extension

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6403]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.9

Déposer un document PDF comme production d'une évaluation
Lors du chargement d'une seule production, on récupère un seul fichier sans extension donc illisible

Si on sélectionne plusieurs productions alors on reçoit un zip qui contient bien les fichiers avec extensions.

**Comment by kitan1982** [comment]
Tu le fais via le menu "Voir toutes les productions" ?
Sur cette page, j'ai d'office un zip avec un dossier (nommé selon l'utilisateur) contenant le fichier dedans.

**Comment by clarophil** [comment]
Effectivement, ça a dû être résolu depuis.
C'est résolu donc, je ferme le ticket
