### ISSUE TITLE
Bug Widget Liste de ressources via Fil d'Ariane

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#6409]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      | 12.5.12

Le widget Ressources ne s'affichage pas quand retour à un accueil d'EA via le fil d'ariane.
Pouvez-vous résoudre ce point car nos utilisateurs ne connaissent pas F5

![image](https://user-images.githubusercontent.com/33163723/68754076-5e4e9480-0606-11ea-8947-824db5eed4cf.png)

**Comment by npaille** [comment]
Ce bug perdure.
Lorsque l'on navigue, toutes les informations ne s'affichent pas

![image](https://user-images.githubusercontent.com/33163723/69612315-bdad9b00-102f-11ea-8f5a-0e858414cc2f.png)

**Comment by LaurentGruber** [comment]
je ne reproduit plus depuis la dernière maj, tu le reproduis encore ? et comment ?

**Comment by npaille** [comment]
Bonjour Laurent,
En effet, ce matin, je ne reproduis plus cet erreur. J'attends de voir mais cela semble réglé. merci

**Comment by LaurentGruber** [comment]
Je ferme le ticket, si tu retombe dessus, remet un commentaire ici et je le rouvrirai.
