### ISSUE TITLE
Forum : page blanche à l'ouverture

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6434]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.12

On ne sait plus ouvrir de ressource forum
[https://claco.ecam.be/#/desktop/workspaces/open/3c0d39a1-b721-11e8-b44d-0cc47a960f96/resources/test%20de%20forum-9905](url)

**Comment by clarophil** [comment]
Dès qu'il y a un sujet dedans

**Comment by LaurentGruber** [comment]
d'où vient l'url que tu donne, elle n'est pas correct ?

**Comment by clarophil** [comment]
Dans l'espace test3 le forum "test de forum"
[https://claco.ecam.be/#/desktop/workspaces/open/3c0d39a1-b721-11e8-b44d-0cc47a960f96/resources/test-de-forum](url)
