### ISSUE TITLE
Question  ouverte : impossible de sauvegarder le commentaire

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6437]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.12

Créer une questionnaire
Créer une question ouverte
Répondre à la question
Menu du questionnaire / Corriger
Ajouter un commentaire

Le bouton Sauvegarde est inactif, impossible de sauver
![image](https://user-images.githubusercontent.com/895878/69325654-c32f6d80-0c4a-11ea-9f78-e3fec16b790b.png)

**Comment by kitan1982** [comment]
Il y avait bien un souci avec l'enregistrement du commentaire.
Par contre, sur l'image en exemple, c'est normal que le bouton "sauvegarder" ne soit pas activé car la valeur du score n'est pas valide.
Il doit être inférieur ou égal au score max.
