### ISSUE TITLE
Widget Liste des événements - Bug Lien vers page blanche

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#6439]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      | 12.5.12

Le widgets événement conserve un bug. Le lien renvoie vers une page blanche et le retour arrière n'est pas possible (impasse)

![image](https://user-images.githubusercontent.com/33163723/69346535-3e0c7e80-0c73-11ea-9721-803f978f8084.png)

![image](https://user-images.githubusercontent.com/33163723/69346413-fede2d80-0c72-11ea-94a7-f41ffbefed30.png)

**Comment by LaurentGruber** [comment]
le problème est toujours d'actualité ?

**Comment by npaille** [comment]
Oui.
Regarde, j'ai crée un accueil événements.
Quand on clique sur les élements, on a une mauvaise route... ou une page blanche. Pour le moment, elle n'est pas encore "carrée". 


![image](https://user-images.githubusercontent.com/33163723/69856248-80464900-128d-11ea-9ddf-7d24d9b3fd34.png)

**Comment by LaurentGruber** [comment]
j'ai pas réussi à avoir de page blanche. Et j'ai chaque fois été redirigé vers l'agenda de l'espace en question. Il faut qu'on modifie pour arriver directement sur l'event, ça c'est dans la ToDo list.

Par contre j'aimerais reproduire le cas de la page blanche, donc si tu as plus d'info je suis preneur...

**Comment by npaille** [comment]
je suis en train de modifier tous les events pour voir si ça vient d'avant la correction.

Avec Firefox sur un compte eleve, j'ai la page blanche


![image](https://user-images.githubusercontent.com/33163723/69857065-5857e500-128f-11ea-935f-875a6383da82.png)

**Comment by npaille** [comment]
j'essaie sur smartphone sur le 1er événement.
Page blanche

![image](https://user-images.githubusercontent.com/33163723/69857617-9a355b00-1290-11ea-91e0-9b4732e2f4b8.png)

![image](https://user-images.githubusercontent.com/33163723/69857635-a3bec300-1290-11ea-814d-db082bd50681.png)

**Comment by npaille** [comment]
No found, c'est quand on clique dans espace d'activité.

![image](https://user-images.githubusercontent.com/33163723/69857911-2e072700-1291-11ea-86b2-d02b5d368569.png)

**Comment by Elorfin** [comment]
C'est juste parce que le rôle Collaborateur avait pas les droits d'ouverture sur l'outils Agenda.
Je l'ai rajouté et ça fonctionne comme il faut avec eleve1.

Il faudra que je vois pour gérer correctement l'erreur.

**Comment by Elorfin** [comment]
En fait il aurait du être redirigé sur l'outils par défaut de l'espace dans ce cas là. C'est corrigé.

**Comment by npaille** [comment]
Merci. J'ai déjà fait mes interfaces. Je testerai les liens quand votre go après MAJ
- Le 3 e onglet d'accueil
- et les widgets events dans les EA
Les miniatures fonctionnent bien par contre.
![image](https://user-images.githubusercontent.com/33163723/69867550-6ca7dc00-12a7-11ea-815c-e5e46fb53375.png)

**Comment by npaille** [comment]
De : Axel Penin [mailto:notifications@github.com]
Envoyé : mardi 10 décembre 2019 15:03
À : claroline/Distribution <Distribution@noreply.github.com>
Cc : PAILLE Nathalie <npaille@estp-paris.eu>; Author <author@noreply.github.com>
Objet : Re: [claroline/Distribution] Widget Liste des événements - Bug Lien vers page blanche (#6439)


Closed #6439<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fclaroline%2FDistribution%2Fissues%2F6439&data=01%7C01%7Cnpaille%40estp-paris.eu%7Ca628d83c477c48dfd1f008d77d79b5cc%7C5bdbdf70f06549628b63ab35ed7880b0%7C1&sdata=dFJfnWjCWMTADPH1OYCSotVqnpmmWh0RPQ8qMAqADbk%3D&reserved=0>.
