### ISSUE TITLE
Impossible de charger les notifications

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#6441]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      |12.5.12

 
![image](https://user-images.githubusercontent.com/33163723/69409851-19afb100-0d0a-11ea-83a5-9f79422c58d6.png)

**Comment by ngodfraind** [comment]
reproduit

Attempted to load class "LogSocialmediaLikeEvent" from namespace "Icap\SocialmediaBundle\Listener
