### ISSUE TITLE
Pb de chargement des Ressources d'un EA (aléatoire)

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#6467]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      | 12.5.16

Quand on souhaite voir les ressources d'un EA, régulièrement ce sont toutes les ressources s'affichent. D'ailleurs, dans ce cas, l'icône ressources est grisé. F5 pour rétablir la situation.  Voici la console si jamais ceci est explicable

![image](https://user-images.githubusercontent.com/33163723/69900353-413df380-1372-11ea-8020-25ecd770b413.png)

app.b4d8a9598e7e5b74f80d.js:1 
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
load_domain_file @ app.b4d8a9598e7e5b74f80d.js:1
/#/desktop/home/ecampus-bienvenue:1 Mixed Content: The page at 'https://ecampus.estp.fr/#/desktop/home/ecampus-bienvenue' was loaded over HTTPS, but requested an insecure image 'http://www.salonsimi.com/wp-content/uploads/2019/02/presentation.png'. This content should also be served over HTTPS.

**Comment by LaurentGruber** [comment]
met l'image ici : http://www.salonsimi.com/wp-content/uploads/2019/02/presentation.png en https au lieu de http ...

**Comment by npaille** [comment]
je ne comprends pas

**Comment by npaille** [comment]
Le problème subsiste (cf Screencasting de ce matin)

**Comment by Elorfin** [comment]
C'est corrigé depuis la 12.5.20.
Peux-tu me confirmer que tu n'as plus le problème ?

**Comment by Elorfin** [comment]
Je penses qu'on peut clôturer si tu confirmes @npaille.

**Comment by npaille** [comment]
Bonjour,
Oui tu peux le faire.
bonne journée

**Comment by npaille** [comment]
Quoi que je rencontre encore le problème par moment...
encore ce matin
