### ISSUE TITLE
Forum | non affichage widget liste questions forum

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#6482]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      | 12.5.18

j'ai un forum, avec un message à l'intérieur.
Pourtant le widget Liste de données > **liste des msgs du forum** reste vide. 
Ou alors c'est une cascade de message d'erreur dans la console.
EA concerné : https://ecampus.estp.fr/#/desktop/workspaces/open/biblio26/home/forum
![image](https://user-images.githubusercontent.com/33163723/70526059-05144b00-1b49-11ea-9b6b-d5663e7f1412.png)

![image](https://user-images.githubusercontent.com/33163723/70526297-9388cc80-1b49-11ea-974d-9c32a9ec315b.png)

**Comment by LaurentGruber** [comment]
j'ai remis le widget en question et j'ai bien un message qui s'affiche et pas d'erreur ...

**Comment by Elorfin** [comment]
Je penses qu'on peut clôturer si tu confirmes @npaille.

**Comment by npaille** [comment]
oui, merci!
