### ISSUE TITLE
Agenda - Bug affichage événement

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#6492]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      | 12.5.19

Suite à votre correction, mes collaborateurs ne voient plus les événéments.
Ex : compte eleve1    et superviseur
Pouvez-vous corriger ceci
https://github.com/claroline/Distribution/issues/6466

![image](https://user-images.githubusercontent.com/33163723/70725778-48171f80-1cfd-11ea-9bb5-f77b949febd8.png)

**Comment by Elorfin** [comment]
Corrigé par #6494.
