### ISSUE TITLE
Comment rajouter un rôle à un compte?

### ISSUE THREAD

**Issue by Batier** [claroline/Distribution#6500]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.4.14

j'ai essayé
 https://youtu.be/ngYDsAd4nEM

**Comment by Elorfin** [comment]
Depuis le form du User : 

![Sans titre](https://user-images.githubusercontent.com/5363219/71097851-ff55df80-21b0-11ea-9a05-b7d3ae3b3e22.png)

Depuis le form du rôle (qui s'ouvre comme les utilisateurs en cliquant sur son nom) : 

![Sans titre2](https://user-images.githubusercontent.com/5363219/71097878-10065580-21b1-11ea-9288-78e545cd5ab4.png)

A noter qu'en 12.5, le "+" est directement accessible dans le panel (plus de sous menu).
