### ISSUE TITLE
Bug claroline:update install 12.4.25

### ISSUE THREAD

**Issue by Tx0666** [claroline/Distribution#6502]
| Bug report?   | yes
| Version?      |  12.4.25  

Bonjour,

Install fraîche à présent d'une 12.x suivant la procédure sur github.

Tout se passe bien jusqu'au composer build compris, mais :

root@claroline12:/var/www/Claroline# php app/console claroline:install

In FileLocator.php line 71:
                                                                                                                                                   
  The file "services.yml" does not exist (in: /var/www/Claroline/vendor/claroline/distribution/main/dev/DependencyInjection/../Resources/config). 

Ma dernière install d'une 12.x date d'il y a bien 6 ou 7 version précédentes et je n'ai jamais eu une telle erreur.

Par contre la mise à jour d'une version existante marche bien.

**Comment by txomin666** [comment]
AH je n'avais pas vu qu'avec un git clone on tombe désormais dans la branche 12.5.x et que le composer.json avait été mis à jour e, conséquence.
Le bug concerne donc une install     12.5.x

**Comment by LaurentGruber** [comment]
j'ai fais une install propre à l'instant sans reproduire ...

**Comment by txomin666** [comment]
C'est bien avec une 12.5 que vous avez testé ?
(je me suis trompé dans le titre, cf mon 2ème message, no problem avec une 12.x)

De mon côté je reproduis bien l'erreur de nouveau maintenant.
Il manque donc le fichier Claroline/vendor/claroline/distribution//main/dev/Resources/config/services.yml
Par contre il y a main/app/Resources/config/services.yml et main/core/Resources/config/services.yml.

J'ai donc copié  main/core/Resources dans main/dev  et là ça marche.
