### ISSUE TITLE
[Announcements] Announcements by mail for the team in the workspace

### ISSUE THREAD

**Issue by charlotte42** [claroline/Distribution#651]
To send an ad to one or more teams in the workspace.

Ex : Dans un espace d'activité on va inscrire toute une formation (180 étudiants) et on va faire 6 groupes (équipes) de 30 personnes. On aimerait pouvoir communiquer avec un ou plusieurs de ces groupes.

**Comment by clarophil** [comment]
Ce serait bien aussi de pouvoir envoyer une annonce vers des utilisateurs, un groupe ou un rôle.  Il faudrait alors que le groupe ou le rôle soit dans les utilisateurs de l'espace.
Je verrais bien un système de filtre comme pour l'agenda.
![image](https://cloud.githubusercontent.com/assets/895878/16458975/6d035084-3e21-11e6-9b46-a201072d9a89.png)

**Comment by clarophil** [comment]
- [ ] Nouvelle annonce -> Désactiver la notification aux utilisateurs si on complète le champ DU

- [ ] Dans le widget annonce 
- faire une présentation plus condensée des 
- le lien pointe vers l'espace et pas vers la ressource annonce
