### ISSUE TITLE
Ressource dossier : gestion des droits - impossible d'enlever le cadenas

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6554]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Ressource
Dossier /  un cadenas est visible 
Gestion des droits
![image](https://user-images.githubusercontent.com/895878/73362418-16571980-42a7-11ea-8707-745a808b46fe.png)
Si on sélectionne Utilisateurs de l'espace, Gestionnaire reste sélectionné
![image](https://user-images.githubusercontent.com/895878/73362580-5f0ed280-42a7-11ea-9659-5e1851ec229e.png)
Sauvegarder ne change rien aux droits
https://claco.ecam.be/#/desktop/workspaces/open/m3090/resources/m3090-conception-et-developpement-informatique

**Comment by Elorfin** [comment]
Cette vue ne sait gérer que les rôles "standard" (rôles plateforme User / Anonyme, rôles Workspace Gestionnaire / Collaborateur).

Dans l'espace en question, le rôle standard Collaborateur n'existe plus, ce qui rend le bouton "Utilisateurs de l'espace" non fonctionnel.

Il doit être possible de modifier le droit simple "Utilisateurs de l'espace" pour prendre en compte tous les rôles de l'espace.

**Comment by clarophil** [comment]
Si le rôle collaborateur existe toujours, il a juste été renommé en membre.
Ne serait-il pas intéressant dans la gestion des droits de pouvoir remettre les droits par défaut ?
