### ISSUE TITLE
Forum : notification par email d'un nouveau sujet

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6558]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5

Forum
Si on a choisit de recevoir les notifications du forum par email (menu contextuel)
On reçoit par email les nouveaux messages postés dans les sujets 
Mais PAS les nouveaux sujets

**Comment by Elorfin** [comment]
C'est corrigé dans la dernière version.
