### ISSUE TITLE
Tableau de bord dans communauté ne fonctionne pas

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6567]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.29

Adminsitration
Communauté
Menu contextuel 
Tableau de bord
![image](https://user-images.githubusercontent.com/895878/74219567-74bfc700-4cad-11ea-9603-8c8442eb5d8f.png)

**Comment by Elorfin** [comment]
Duplicate https://github.com/claroline/Distribution/issues/6404.
