### ISSUE TITLE
Bug Suppression image de couverture

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#6595]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      | 12.5.31

Depuis peu, il n'est pas possible de supprimer une image de couverture dans un EA (ex: code elearn21). Il ne se passe rien.

![image](https://user-images.githubusercontent.com/33163723/75427910-9ffe1380-5947-11ea-85d9-85cc53f13a28.png)

**Comment by Elorfin** [comment]
Il me semble que c'est corrigé en 12.5.38 (en tout cas RAS chez moi). Peux-tu me le confirmer stp ?

**Comment by npaille** [comment]
Oui, merci. Tu peux clore. 
Tb journée
