### ISSUE TITLE
Exportation de fichier : mauvaise extension / ouverture impossible

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6597]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.33

Lors de l'export d'un fichier, le point qui précède l'extension est remplacé par un tiret
Les utilisateurs ne savent donc plus ouvrir l'export.

**Comment by clarophil** [comment]
Le problème de tiret à la place sur point qui précède l'extension est réapparu

**Comment by Elorfin** [comment]
Tu pourras retester quand tu seras passé à la 15.5.34 stp ? Il me semble qu'il te manque une partie du fix.
Si tu as encore le problème, un lien vers un des fichiers qui pose problème serait le bienvenu.

**Comment by clarophil** [comment]
C'est bien résolu depuis la 12.5.34
Merci
