### ISSUE TITLE
Problem to import WS

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#66]
_From @david42 on April 7, 2016 14:27_

I try import a workspace with a zip archive and I get this error : 

An exception occurred while executing 'INSERT INTO claro_workspace (name, description, code, maxStorageSize, maxUploadResources, maxUsers, displayable, guid, self_registration, registration_validation, self_unregistration, creation_date, is_personal, start_date, end_date, is_access_date, workspace_type, user_id, options_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["ts3", "", "ts3", "1 TB", 10000, 10000, 0, "53D06B2F-FE82-458F-A260-32C1802030C4", 0, 0, 0, 1460038860, 0, null, null, 0, null, null, null]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'ts3' for key 'UNIQ_D902854577153098' 

_Copied from original issue: claroline/ClaroSupport#47_

**Comment by ngodfraind** [comment]
Can you send me the zip file. It's not enough data for debugging.
