### ISSUE TITLE
Questionnaire : impossible de créer une question

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6600]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

Ouvrir un questionnaire en édition
Etape 1
Créer une question (quel que soit le type) 
-> Aucune réaction
-> dans la console TypeError: e.score is null
plugin-exo-quiz-resource.0159f525ed4aadc1b6ed.js:1:483811
    create https://claco.ecam.be/dist/plugin-exo-quiz-resource.0159f525ed4aadc1b6ed.js:1
    handleSelect https://claco.ecam.be/dist/plugin-exo-quiz-resource.0159f525ed4aadc1b6ed.js:1
    callback https://claco.ecam.be/dist/app.560f438dacc1e3503da7.js:1
    value https://claco.ecam.be/dist/app.560f438dacc1e3503da7.js:1
    value self-hosted:876
    A https://claco.ecam.be/dist/vendor.933b89c6ffa1e2a7c482.js:257
    b https://claco.ecam.be/dist/vendor.933b89c6ffa1e2a7c482.js:257
    E https://claco.ecam.be/dist/vendor.933b89c6ffa1e2a7c482.js:257
    E https://claco.ecam.be/dist/vendor.933b89c6ffa1e2a7c482.js:257
    S https://claco.ecam.be/dist/vendor.933b89c6ffa1e2a7c482.js:257
    M https://claco.ecam.be/dist/vendor.933b89c6ffa1e2a7c482.js:257
    L https://claco.ecam.be/dist/vendor.933b89c6ffa1e2a7c482.js:257
    xn https://claco.ecam.be/dist/vendor.933b89c6ffa1e2a7c482.js:257
    le https://claco.ecam.be/dist/vendor.933b89c6ffa1e2a7c482.js:257
    Sn https://claco.ecam.be/dist/vendor.933b89c6ffa1e2a7c482.js:257
    kn https://claco.ecam.be/dist/vendor.933b89c6ffa1e2a7c482.js:257
    Ln https://claco.ecam.be/dist/vendor.933b89c6ffa1e2a7c482.js:257
    bind_applyFunctionN self-hosted:1054
    Ln self-hosted:1018
    unstable_runWithPriority https://claco.ecam.be/dist/vendor.933b89c6ffa1e2a7c482.js:9
    Ko https://claco.ecam.be/dist/vendor.933b89c6ffa1e2a7c482.js:257
    se https://claco.ecam.be/dist/vendor.933b89c6ffa1e2a7c482.js:257
    Mn https://claco.ecam.be/dist/vendor.933b89c6ffa1e2a7c482.js:257
    Mn self-hosted:977

​

**Comment by greg49** [comment]
Maintenant on peut créer des questions, mais impossible de les tester : page blanche

**Comment by clarophil** [comment]
Chez moi tout fonctionne parfaitement à présent

**Comment by greg49** [comment]
ah je vais retester. suis sur Firefox sous MAcos

**Comment by clarophil** [comment]
j'ai testé sous firefox windows

**Comment by greg49** [comment]
zut, rien sur Safari, rien sur Chrome (voir PJ)
![CAPTURE 2020-03-03 à 18 50 41](https://user-images.githubusercontent.com/21193255/75804400-29ff0f80-5d80-11ea-95b0-29c04d64c0a0.jpg)

**Comment by greg49** [comment]
je suis sur la version 12.5.33 et toi ?

**Comment by clarophil** [comment]
oui 12.5.33
j'ai aussi testé sous chrome et edge, tout fonctionne bien
