### ISSUE TITLE
Menu inactif sur la Home page

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#6603]
| Bug report?   | yes
| Version?      | 12,5,33

Menu inactif (burger) en haut à gauche lorsque l'on se trouve sur la page d'accueil (une fois connecté) : à cette adresse https://.............fr/#/home/

**Comment by clarophil** [comment]
Sous windows, chrome, firefox et edge aucun problème constaté

**Comment by greg49** [comment]
merci. effectivement le menu fonctionne bien maintenant mais bizarrement je n'accède plus à l'Accueil. Dès que je tape l'adresse dans le navigateur, il commute sur login
Peux tu me dire si tu as la même chose sur : https://hdv-press.fr

**Comment by greg49** [comment]
Quand je clique sur mon logo en haut à gauche, je ne reviens plus sur la page d'accueil... sur mac comme sur windows

**Comment by clarophil** [comment]
Pas de soucis de mon côté.  Il faudrait vider le cache de ton navigateur.

**Comment by greg49** [comment]
Impossible, j'ai essayé sur 3 machines différentes et une à distance en virtualisation sur Citrix. Sur 6 navigateurs différents, l'adresse me renvoie systématiquement sur le login... Je pige pas
![CAPTURE 2020-03-06 à 21 50 35](https://user-images.githubusercontent.com/21193255/76121723-97b37180-5ff4-11ea-9a21-d97c10337899.jpg)

**Comment by Elorfin** [comment]
Il n'y a pas de menu sur l'accueil général de la plateforme, la page de login et la page d'inscription. C'est pour ça que le bouton est inactif sur ces pages.

Pour ce qui est de ta page d'accueil, je penses que la config a sauté. Si tu vas dans Administration > Paramètres > Informations générales > Accueil. Le champ type doit être sur Outil (pour avoir les widgets) ou sur HTML.

**Comment by greg49** [comment]
Super merci Elorfin et Clarophil pour votre aide.
Effectivement la page d’accueil avait sauté. J'ai remis sur Outils... cool
