### ISSUE TITLE
Pb pour accéder au formulaire d'inscription

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#6610]
Bug report?   | yes
| Version?      | 15.5.33

Bonjour,
j'ai activé l'accès à un espace d'activité par inscription mais lorsque je clique sur le bouton m'inscrire, la fenêtre popup de connexion vient bloquer le processus d'inscription. voir PJ
![CAPTURE 2020-03-06 à 14 30 07](https://user-images.githubusercontent.com/21193255/76088089-b6dfde00-5fb7-11ea-8a06-7ff75b30ecc6.jpg)
![CAPTURE 2020-03-06 à 14 31 15](https://user-images.githubusercontent.com/21193255/76088092-b9423800-5fb7-11ea-8fdf-bbc8afde2c68.jpg)

**Comment by LaurentGruber** [comment]
je viens de tester et quand je clique sur m'inscrire j'ai bien le formulaire d'inscription la sur la capture on dirait que tu as cliquer sur connecter.
Tu l'as fais sous safari ?

**Comment by greg49** [comment]
Je clique bien sur M'inscrire, bouton blanc et la fenêtre connexion vient de suite s'afficher sur Chrome sous Macos

**Comment by greg49** [comment]
![ScreenFlow](https://user-images.githubusercontent.com/21193255/76342248-98068200-62fe-11ea-8c80-a19be98e8b26.gif)

**Comment by LaurentGruber** [comment]
l'auto inscription n'est pas autorisé sur la plateforme donc c'est normal.
