### ISSUE TITLE
Ajout de plusieurs fichiers en erreur 500

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6626]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.36

Dans les ressources
Menu contextuel 
Ajout de plusieurs
Sélectionner un ou plusieurs fichiers
Erreur 500
{"JSON":{"message":"Attempted to call an undefined method named \"setName\" of class \"Claroline\\CoreBundle\\Entity\\Resource\\File\".\nDid you mean to call \"getName\"?","trace":[{"file":"/home/hevinci/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php","line":151,"function":"resourceFilesCreateAction","class":"Claroline\\CoreBundle\\Controller\\APINew\\Resource\\ResourceNodeController","type":"->","args":[{},{},{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"/home/hevinci/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php","line":68,"function":"handleRaw","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1]},{"file":"/home/hevinci/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php","line":200,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1,true]},{"file":"/home/hevinci/www/web/app.php","line":37,"function":"handle","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]}]},"Charge utile de la réponse":{"EDITOR_CONFIG":{"text":"{\"message\":\"Attempted to call an undefined method named \\u0022setName\\u0022 of class \\u0022Claroline\\\\CoreBundle\\\\Entity\\\\Resource\\\\File\\u0022.\\nDid you mean to call \\u0022getName\\u0022?\",\"trace\":[{\"file\":\"\\/home\\/hevinci\\/www\\/vendor\\/symfony\\/symfony\\/src\\/Symfony\\/Component\\/HttpKernel\\/HttpKernel.php\",\"line\":151,\"function\":\"resourceFilesCreateAction\",\"class\":\"Claroline\\\\CoreBundle\\\\Controller\\\\APINew\\\\Resource\\\\ResourceNodeController\",\"type\":\"-\\u003E\",\"args\":[{},{},{\"attributes\":{},\"request\":{},\"query\":{},\"server\":{},\"files\":{},\"cookies\":{},\"headers\":{}}]},{\"file\":\"\\/home\\/hevinci\\/www\\/vendor\\/symfony\\/symfony\\/src\\/Symfony\\/Component\\/HttpKernel\\/HttpKernel.php\",\"line\":68,\"function\":\"handleRaw\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\HttpKernel\",\"type\":\"-\\u003E\",\"args\":[{\"attributes\":{},\"request\":{},\"query\":{},\"server\":{},\"files\":{},\"cookies\":{},\"headers\":{}},1]},{\"file\":\"\\/home\\/hevinci\\/www\\/vendor\\/symfony\\/symfony\\/src\\/Symfony\\/Component\\/HttpKernel\\/Kernel.php\",\"line\":200,\"function\":\"handle\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\HttpKernel\",\"type\":\"-\\u003E\",\"args\":[{\"attributes\":{},\"request\":{},\"query\":{},\"server\":{},\"files\":{},\"cookies\":{},\"headers\":{}},1,true]},{\"file\":\"\\/home\\/hevinci\\/www\\/web\\/app.php\",\"line\":37,\"function\":\"handle\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"-\\u003E\",\"args\":[{\"attributes\":{},\"request\":{},\"query\":{},\"server\":{},\"files\":{},\"cookies\":{},\"headers\":{}}]}]}","mode":"application/json"}}}

**Comment by Elorfin** [comment]
corrigé par https://github.com/claroline/Distribution/pull/6624.
