### ISSUE TITLE
Raccourci sur Dossier

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#6643]
A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.5.36

Je m'interroge sur l'outil Raccourci.
J'ai tenté de faire un raccourci d'un dossier de mon espace perso vers un autre espace d'activité.
Le dossier apparait mais pas le contenu du dossier avec les fichiers dedans.
Est-ce un bug ou une restriction de la plateforme ?

**Comment by alainertveldt** [comment]
Il faut donner les droits aux utilisateurs de l'autre espace sur le dossier de votre espace perso.
L'intérêt de raccourci est de partager dans plusieurs espaces un même contenu qu'on ne mettra à jour que depuis un seul espace... Au début ça demande de faire plusieurs raccourcis (un par espace cible) mais ensuite c'est pratique, car la mise à jour ne se fait que d'un seul endroit et pas dans chaque espace cible...

**Comment by alainertveldt** [comment]
Bon alors je reviens @greg49 sur votre commentaire. En effet depuis le passage en version 12.5.43 (avant on était encore en 12.4 et ça marchait comme expliqué dans ma première réponse) le raccourci sur dossier est vide ... Ce serait donc intéressant de corriger cela. Je vais poster le bug

**Comment by Elorfin** [comment]
Duplicate #6726.
