### ISSUE TITLE
voir en tant que - Reconnexion obligatoire

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#6650]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.5.38

le "voir en tant que" dans les EA fonctionne mais pénible de revenir ensuite : il faut se reconnecter. Cette contrainte n'existait pas dans la version précédente où nous reprenions le profil d'origine.

![image](https://user-images.githubusercontent.com/33163723/78979670-9eb23000-7b1c-11ea-9485-0d81d8ed1001.png)

**Comment by Elorfin** [comment]
Corrigé en 13.0.
