### ISSUE TITLE
Q : Comment mettre à disposition des fichiers PDF sur l'Accueil (hors connexion)

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#6652]
| Q   
| Bug report?   | no
| Version?      | 12.5.36

J'essaie en vain de permettre aux internautes d'ouvrir des PDF sur mon portail public.
Quelqu'un a t'il réussi cette démarche et pourrait-il m'aider à configurer ?
[Voici le lien](https://maitecornil.demo.claroline.com/#/home/formations) qui affiche des fiches programmes mais quand on clique, il faut s'authentifier pour ouvrir le fichier PDF.
Petites précisions sur les réglages actuels :
![RoleAnonyme](https://user-images.githubusercontent.com/21193255/79120461-420c7a80-7d93-11ea-8e0f-3b74ec95b254.JPG)
![DroitBibliotheque](https://user-images.githubusercontent.com/21193255/79120474-4a64b580-7d93-11ea-80ca-9edd029000c9.JPG)

**Comment by alainertveldt** [comment]
Peut-être en cochant la case appliquer au contenu ..... ;-) car là c'est simplement le dossier qu'on peut ouvrir pas le contenu
