### ISSUE TITLE
Bug Administration / Tableau de bord - Clarté affichage

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#6667]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      | 12.5.40

Illisibilité du tableau de bord
![image](https://user-images.githubusercontent.com/33163723/80076353-606d3580-854c-11ea-9685-0bad7ae71a01.png)

**Comment by Elorfin** [comment]
Corrigé en 12.5.41
