### ISSUE TITLE
Export Tableau de Bord | Export des actions impossible

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#6668]
| Q             | A
| ------------- | ---
| Bug report?   | yes 
| Version?      | 12.5.40

Mon export s'arrête au 2017-09-07 à 6000 lignes et rien après 

![image](https://user-images.githubusercontent.com/33163723/80079622-d2477e00-8550-11ea-87f1-56f6c6bd6829.png)

![image](https://user-images.githubusercontent.com/33163723/80079509-acba7480-8550-11ea-8e47-5c28757e9086.png)

**Comment by Elorfin** [comment]
Corrigé en 12.5.41.

**Comment by npaille** [comment]
L'export est possible mais pas jusqu'au bout. Il me manque les 20 derniers jours
