### ISSUE TITLE
Expiration session | durée timeout 

### ISSUE THREAD

**Issue by npaille** [claroline/Distribution#6669]
| Q             | A
| ------------- | ---
| Bug report?   |  no
| Version?      | 12.5.40

Lors des examens (questionnaire), nous constatons des déconnexions en raison d'une période d'inactivité. Influence pour les quiz avec une seule tentative. Est-ce possible de régler le temps d'expiration de session ?

**Comment by Elorfin** [comment]
Oui.
Dans Administration > Paramètres > Technique > Sessions > Durée de vie du cookie. La valeur est en seconde.

**Comment by npaille** [comment]
Dans la réalité, même en augmentant
il faut se reconnecter dans 5 à 10 min sans bouger la souris
Tu peux que le paramètre timeout peut ne pas fonctionner (j'ai une bonne connexion et fibre)?

![image](https://user-images.githubusercontent.com/33163723/80132926-b7026000-859c-11ea-9e0b-9eaeda9b1da7.png)

**Comment by greg49** [comment]
Bonjour,
je confirme avoir le même problème avec BigblueButton.
Le système se déconnecte

**Comment by clarophil** [comment]
Oui je confirme également qu'il y a un soucis sur la durée de connexion.
Hier dimanche, j'ai fait un essai et la session a tenu une heure comme prévu
Ce lundi, nouvel essai et là plus que 20 minutes et c'est aléatoire.

Je me demande s'il n'y a pas une autre paramètre dans php.ini  qui vide les sessions si il y en a trop ?

**Comment by npaille** [comment]
à l'ESTP le temps de connexion est réduit à quelques minutes si on ne bouge pas la souris

**Comment by npaille** [comment]
Information dispo quand déconnexion
![image](https://user-images.githubusercontent.com/33163723/80915741-88cb1000-8d54-11ea-9695-690d90219d9a.png)
