### ISSUE TITLE
Questionnaire : affihage des réponses attendues dans le menu contextuel

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6675]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.41

Dans le cadre d'un questionnaire certificatif, on ne souhaite pas donner les réponses à l'étudiant
Donc dans les paramètres on a tout décoché
![image](https://user-images.githubusercontent.com/895878/80216281-1a909a00-863e-11ea-9ee4-dad054243fb9.png)

Mais l'étudiant peut voir les réponses attendus dans le menu contextuel / Voir les résultats

**Comment by Elorfin** [comment]
L'accès est restreint uniquement au niveau de l'api pour le moment. C'est à dire que les utilisateurs verront quand même la liste des essais qu'ils ont faits, mais ne pourront pas charger leur copie.

La gestion des erreurs/masquage des liens dans l'ui est encore à faire.

**Comment by clarophil** [comment]
Si l'étudiant va voir les résultats dans les secondes qui suivent la fin du questionnaire, il a accès à tout, questions, réponses attendues et résultats.

**Comment by LaurentGruber** [comment]
fixed
