### ISSUE TITLE
Questionnaire : score par étape plante si contenu présent

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6683]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.41

Dans un questionnaire
Ajouter un texte dans une étape
Dans les paramètres "Page de fin"
cocher per_step
![image](https://user-images.githubusercontent.com/895878/80710458-11e10d80-8aef-11ea-83e5-74b25c50f8b0.png)

A la fin du questionnaire -> Page blanche
Je pense que ça plante car il n'y pas de score sur un contenu texte et donc le score de l'étape ne peut pas être calculé.

Ressource test

https://claco.ecam.be/#/desktop/workspaces/open/3c0d39a1-b721-11e8-b44d-0cc47a960f96/resources/exo052019/edit/parameters

**Comment by Elorfin** [comment]
Corrigé en 12.5.43
