### ISSUE TITLE
[ExoBundle] Exercice "Player" sous IE

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#67]
_From @eddymarques on April 1, 2016 13:21_

Lors de la réalisation d'un Exercice, IE affiche une alerte à chaque changement de page "Suivant"
![image](https://cloud.githubusercontent.com/assets/3414956/14207964/46c03e4a-f81d-11e5-8f75-ff6e0e6a57fe.png)

Problème similaire avec un compte connecté ou sans être identifié.
Ce problème n’apparaît pas sous Chrome et Firefox.

IE v. 11.0.9600

_Copied from original issue: claroline/ClaroSupport#44_

**Comment by purplefish32** [comment]
A tester

**Comment by eddymarques** [comment]
Se produit sur la version PHP du player, mais pas sur la version Angular.

Par contre, sous le player Angular:
 - 1ere question : QCM
 - 2ème question: Ouverte
En avançant avec les flèches, le bouton Terminer l'Exercice n’apparaît pas alors qu'on est à la fin du questionnaire.
![image](https://cloud.githubusercontent.com/assets/3414956/14488625/68e218fe-0169-11e6-85f0-62218fc90b60.png)
On peut forcer l'apparition du bouton "Terminer" en recliquant sur l'étape 2/2 dans la liste déroulante.
Testé sous IE11 et Chrome 49 Win8

**Comment by Elorfin** [comment]
I think this is fixed long ago.
I have no problem in chrome with the master branch.
