### ISSUE TITLE
Questionnaire : export des réponses et résultats

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6715]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.5.42

Dans questionnaire
Menu contextuel

- [ ] Export des résultats en csv ou json, serait-il possible d'avoir le nom du questionnaire comme nom de fichiers ?

- [x] Dans l'export des réponses, serait-il possible d'avoir le titre de la question, c'est important si on a un tirage aléatoire des questions 

- [ ] les réponses contiennent les entités html, il faudrait les convertir en caractères avant l'export

- [x] il manque les titres de colonnes dans la 1ère ligne

**Comment by Elorfin** [comment]
> Dans l'export des réponses, serait-il possible d'avoir le titre de la question, c'est important si on a un tirage aléatoire des questions

Dispo dans la 15.5.44.

**Comment by clarophil** [comment]
super @LaurentGruber tu sais faire la maj ?

**Comment by clarophil** [comment]
- [ ] les réponses contiennent les entités html, il faudrait les convertir en caractères avant l'export
