### ISSUE TITLE
Questionnaire : la page de fin n'est plus affichée et retour intenpestif au début du questionnaire

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6722]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.44

Questionnaire
Paramètres
cocher page de fin

A la fin du questionnaire, on n'affiche plus la page de fin et on retourne au début du questionnaire

**Comment by Elorfin** [comment]
C'est disponible en production.
