### ISSUE TITLE
Questionnaire: réponses attendues non disponibles en fin de test

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#6729]
| Bug report?   | yes
| Version?      | 12.5.44

Voilà une vidéo qui montre le souci

https://youtu.be/K2uyhbrexD4

Les réponses attendues ne sont plus visibles en fin de test.
D'avance merci

**Comment by LaurentGruber** [comment]
Tu dois cocher afficher la page de fin, et il y aura un bouton voir ma copie, dans laquelle il devrait y avoir les réponses attendue.
