### ISSUE TITLE
Insertion d'une ressource dans un widget contenu simple marche aléatoirement

### ISSUE THREAD

**Issue by Tx0666** [claroline/Distribution#6753]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.48

Comme indiqué dans le titre, j'insère une ressource dans un widget "contenu simple".
Parfois le lien vers la ressource s'affiche bien, parfois rien n'est inséré.
Pas de message d'erreur dans la console navigateur ni dans les logs apache.
Certes je peux contourner le problème en insérant un lien avec l'url de la ressource mais c'est plus pénible.

Une idée du problème ?

Merci.

**Comment by clarophil** [comment]
Ce bug est toujours d'actualité dans la 12.5.53
