### ISSUE TITLE
Est-il possible de connecter Claroline à un Active Directory ?

### ISSUE THREAD

**Issue by txomin666** [claroline/Distribution#6759]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.5.48

Bonjour,

Comme indiqué dans le titre, est-il possible de se loguer en connectant Claroline à un Active Directory ?
Je ne vois pas d'option dans Administration / Technique ou ailleurs.

Merci d'avance .

**Comment by LaurentGruber** [comment]
Directement à l'A.D. non mais on peut utiliser SAML2 pour mettre en place du SSO
