### ISSUE TITLE
[ExoBundle] Liste des copies > Recherche par nom

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#68]
_From @eddymarques on April 1, 2016 8:57_

La recherche par nom dans la liste des copies provoque une erreur.
Le problème se pose dans la version PHP, pas dans la version Angular.
Mais il n'est pas possible d'ouvrir les copies depuis la version Angular

![image](https://cloud.githubusercontent.com/assets/3414956/14202472/71eb611e-f7f8-11e5-8897-89ecf6615f2b.png)

_Copied from original issue: claroline/ClaroSupport#43_

**Comment by purplefish32** [comment]
_From @charlotte42 on April 5, 2016 14:18_

J'ai corrigé pour la version php (pas encore push) mais par contre je comprend pas ton soucis sur la version angular?

**Comment by eddymarques** [comment]
Je n'ai pas détecté de problème dans la recherche de copies (par nom) dans la version Angular.

Par contre les copies sont bien listées, mais il n'y a pas debouton ou de lien permettant de consulter "l'intérieur" des copies. Point qui a peut être évolué depuis la création de mon billet.

**Comment by charlotte42** [comment]
Si tu cliques sur "correction" tu dois voir tes questions avec les réponses de l'étudiant et la notes (sur la dernière version)

**Comment by eddymarques** [comment]
En effet le lien Correction permettant de consulter les copies est bien présent sur la dernière version. Merci !

**Comment by charlotte42** [comment]
Je clos alors :)

**Comment by eddymarques** [comment]
Je le ré ouvre :)

Dans la recherche Angular cette fois-ci, dans la liste des copies dans Résultats(Angular) ou dans mes propres copies (Répondre(Angular)), si je tape un nom existant, aucun problème la recherche filtre les copies à l'écran en temps réel.

Si par contre je fais une faute de frappe ne correspondant à rien, ou si je cherche un nom qui n'est pas dans la liste, le champs de recherche disparaît et je ne peux pas corriger ma saisie.
Je ne peux que revenir à l'accueil de l'exercice.
