### ISSUE TITLE
La mise à jour 12.5 échoue

### ISSUE THREAD

**Issue by txomin666** [claroline/Distribution#6801]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.x

Bonjour,

Le problème existe aussi pour la maj 12.5.48 --> 49

php app/console claroline:update  12.5.48 12.5.50
PHP Fatal error:  Uncaught InvalidArgumentException: '/var/www/Claroline/app/../files/config/bundles.ini' does not exist in /var/www/Claroline/vendor/claroline/distribution/main/kernel/Manager/BundleManager.php:103
Stack trace:
#0 /var/www/Claroline/vendor/claroline/distribution/main/kernel/Manager/BundleManager.php(36): Claroline\KernelBundle\Manager\BundleManager->__construct(Object(AppKernel), '/var/www/Clarol...')
#1 /var/www/Claroline/vendor/claroline/distribution/main/kernel/ClarolineKernelBundle.php(39): Claroline\KernelBundle\Manager\BundleManager::initialize(Object(AppKernel), '/var/www/Clarol...')
#2 /var/www/Claroline/app/AppKernel.php(14): Claroline\KernelBundle\ClarolineKernelBundle->__construct(Object(AppKernel))
#3 /var/www/Claroline/app/console(25): AppKernel->__construct('console', true)
#4 {main}
  thrown in /var/www/Claroline/vendor/claroline/distribution/main/kernel/Manager/BundleManager.php on line 103

**Comment by LaurentGruber** [comment]
crée le dossier config dans files et ça devrait passer.

**Comment by txomin666** [comment]
It works :-)
Je voyais que le dossier config n'existait pas, mais  ne connaissant pas bien symfony je ne voulais pas faire de bêtise, et aussi vous signaler le problème.
Merci, bonne continuation dev v13 !
