### ISSUE TITLE
PDF non lisibles

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#6806]
Voilà le soucis depuis que nous sommes passés en 12.5.50

Les pdf ne s'affichent plus 
![image](https://user-images.githubusercontent.com/31481850/91875446-c6489700-ec7b-11ea-93db-20082b9d80a5.png)

Ce n'est pas un raccourci. Ils restent heureusement téléchargeables mais bon..... pfff

**Comment by Elorfin** [comment]
C'est corrigé en production.

**Comment by alainertveldt** [comment]
Merci @Elorfin , cela signifie-t-il qu'à la prochaine mise à jour cela fonctionnera?

**Comment by Elorfin** [comment]
Oui.
