### ISSUE TITLE
Image de couverture et miniature

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#6807]
Bonjour,

soucis depuis le passage en 12.5.50 avec les images de couverture et miniatures.
Elles s'uploadent bien comme le montre la capture d'écran
![image](https://user-images.githubusercontent.com/31481850/91930380-fd04c880-ece0-11ea-8383-ae4c11bc7080.png)
mais ..... soucis
rectangle orange avec echec de la mise à jour....

D'avance merci

**Comment by LaurentGruber** [comment]
Ok, le problème n'est pas lié au miniature directement, mais au maxStorage, je ne sais pas pourquoi mais l'ui essaye de mettre 1099511627776 comme valeur par défaut dès qu'on veut modifier le form ...

Object { path: "/restrictions/maxStorage", message: "instance does not match any of the expected types" }
