### ISSUE TITLE
Transfert messagerie vers mail

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#6812]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.50

Bonjour, 

depuis le passage en 12.5.50 (venant d'une 12.5.47) outre les bugs déjà signalés, il y a aussi les transferts vers les mails qui ne se font plus.
Peut-être n'est-ce qu'un paramètre à changer, mais je ne sais pas ni où ni quoi mettre. 
estl.claroline.com

C'est assez urgent comme les pdf's qui ne sont plus lisibles dans la plate-forme. C'est la base de ce qu'utilisent mes collègues dans la plate-forme.

D'avance merci.

**Comment by Elorfin** [comment]
Il s'agissait bien d'un problème de config, je l'ai restauré et tout devrait fonctionner comme il faut maintenant.

**Comment by alainertveldt** [comment]
Super rapide et super merci @Elorfin
