### ISSUE TITLE
Perte de session à l'inscription ou à la créatin dans un espace

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6824]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.51

**En tant que simple utilisateur** 
Aller dans Espaces d'activité publics 
Menu contextuel M'inscire à un espace
Actualiser la page ou retour sur le bureau
-> la session est perdue et claco redemande le login
Après le reconnexion
Pus de soucis pour entrer dans l'espace

**En tant qu'administrateur**
Espaces gérés
Plus pour ajouter un espace 
Encoder les infos
Sauver, l'espace est créé et il s'ouvre 
Mais il affiche :
_Vous n'êtes pas inscrit à cet espace d'activités.
Veuillez contacter un gestionnaire si vous pensez que vous devriez avoir accès à cet espace d'activités._
Si on clique sur le bureau 
-> la session est perdue et claco redemande le login
Après le reconnexion
On dois encore faire CTRL F5 pour entrer dans l'espace et là on a accès

**Comment by LaurentGruber** [comment]
fixed by https://github.com/claroline/Distribution/pull/6825

**Comment by clarophil** [comment]
Il y a le même problème si on se désinscrit d'un espace, on doit se relogger

**Comment by Elorfin** [comment]
Le problème est corrigé dans l'une des dernières versions de la 12.5.
