### ISSUE TITLE
Inscription dans un espace impossible

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6853]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.53

Comme utilisateur
Outils
Espaces d'activité publics
M'inscrire
-> erreur 403
C'est généralisé à tous les utilisateurs et tous les espaces !

![image](https://user-images.githubusercontent.com/895878/94162848-72e6f480-fe87-11ea-92c0-205240677b24.png)
![image](https://user-images.githubusercontent.com/895878/94162878-7c705c80-fe87-11ea-86cb-73a252369bee.png)

**Comment by Elorfin** [comment]
On l'a corrigé aujourd'hui.
