### ISSUE TITLE
Plus moyen de créer une ressource Raccourci

### ISSUE THREAD

**Issue by alainertveldt** [claroline/Distribution#6859]
| Bug report?   | yes
| Version?      | 12.5.52

Voilà comme dit dans le titre, plus moyen de créer une ressource Raccourci. Elle est bien visible quand on appuie sur le + bleu mais lorsqu'on clique sur Raccourci, rien ne se passe.

**Comment by Elorfin** [comment]
Duplicate https://github.com/claroline/Distribution/issues/6843.

**Comment by txomin666** [comment]
Bonjour,

Le 27/09/2020 à 11:17, alainertveldt a écrit :

> Voilà comme dit dans le titre, plus moyen de créer une ressource 
> Raccourci. Elle est bien visible quand on appuie sur le + bleu mais 
> lorsqu'on clique sur Raccourci, rien ne se passe.

Comme Axel Penin a répondu, le problème est corrigé dans le code mais il 
n'y pas encore eu la publication de "Update distribution".
C'est pour cela que vous ne constatez pas sa résolution.

--
Manu
