### ISSUE TITLE
Voir en tant que ne fonctionne plus sur les rôles de l'espace

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6864]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 12.5.53

Dans un espace
Ouvrir un outil
Cliquer sur Voir en tant que / Collaborateur
Claco redemande l'authentification, il n'y plus moyen d'entrer dans la plateforme sauf si on recharge le bureau

Dans l'admin, le Voir en tant que sur un utilisateur fonctionne toujours

**Comment by Elorfin** [comment]
Corrigé en 13.0.
