### ISSUE TITLE
Déploiement derrière un reverse-proxy (nginx)

### ISSUE THREAD

**Issue by NPavie** [claroline/Distribution#6895]
| Q             | A
| ------------- | ---
| Bug report?   | no
| Version?      | 12.5-dev

Bonjour,

Lors du déploiement derrière un reverse proxy (nginx), l'application ne se charge pas.
(Aucun code d'erreur n'est renvoyé, mais aucun contenu n'est affiché, le résultat est une page blanche).

Le problème viendrait de la configuration de la requête avec symfony, pour laquelle il faut spécifier l’adresse du proxy.
J'ai résolu le problème en suivant la solution détaillé dans la [documentation de symfony](https://symfony.com/doc/current/deployment/proxies.html).

**Comment by LaurentGruber** [comment]
Normalement ce n'est pas nécessaire, si le domain, l'url et l'activation du ssl sont bien renseigné dans le plateform_options.json cela fonctionne sans souci derrière un reverse proxy en tout cas dans tout mes tests...
