### ISSUE TITLE
ExoBundle : Pouvoir supprimer un exercice

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#69]
_From @charlotte42 on April 1, 2016 8:55_

Pouvoir supprimer un exercice qui à des copies

_Copied from original issue: claroline/ClaroSupport#42_

**Comment by purplefish32** [comment]
_From @charlotte42 on April 5, 2016 8:49_

Du coup c'est ok mais en remettant l'ancien code en utilisant 'doctrine.orm.enty_manger' et un exit... A voir pour faire mieux

**Comment by charlotte42** [comment]
it's ok for next tag
