### ISSUE TITLE
Improve automatic checkstyle on PRs

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#693]
As a significant amount of time is still lost on minor style details when reviewing PRs, I'd like to propose enforcements/enhancements to our existing setup:

- [x] Force PHP shortand array notation (there's a `short_array_syntax` fixer in php-cs-fixer's contribs for that)
- [x] Force PHP strict comparisons (~~see `strict` contrib in php-cs-fixer~~)
- [x] Force ordering use statements (idem, see `ordering_use_statements`)
- [ ] Find a way to detect wrong indents (current standard isn't severe enough)
- [x] Add a checkstyle for js files, at least for the es6 files living in *Resources/modules* (that check could be based on a full ruleset like [standard](http://standardjs.com/) or begin as a minimal [eslint](http://eslint.org/) config that would be improved along the way)

 **EDIT**: strict comparisons shoudn't be handled by phpcs-fixer (see below)

**Comment by CPASimUSante** [comment]
Is there a reason other than gaining 5 characters to use [] instead of array() ?

**Comment by purplefish32** [comment]
@CPASimUSante : consistancy

**Comment by stefk** [comment]
No, it's just shorter and easier to spot. That notation can also be found in many other languages.

**Comment by purplefish32** [comment]
LGTM

**Comment by arnaudbey** [comment]
:+1:

**Comment by ngodfraind** [comment]
LGTM

2016-06-20 13:09 GMT+02:00 Arnaud Bey <notifications@github.com>:

> 👍
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/claroline/Distribution/issues/693#issuecomment-227113878>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABVStrT9Dh8Xa2vpzhl0FR59WcUFyiqYks5qNnTOgaJpZM4I5inx>
> .
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by Elorfin** [comment]
> Force PHP strict comparisons (see strict contrib in php-cs-fixer)

This can introduce bugs for code which use loose comparison to handle different types (generally used for inconsistent booleans).

IMHO, this should be spotted but not automatically replaced.

**Comment by stefk** [comment]
@Elorfin, it won't be replaced after the PR is submitted, but it's true that if people apply php-cs-fixer locally without caution it could introduce bugs. We'll have to find another way to enforce that rule. I don't see anything in phpmd but I started working on a tool that could easily implement that check (https://github.com/stefk/md).

**Comment by stefk** [comment]
Regarding es6 style, we could start with the recommended eslint rules (everything checked [✓] in [that list](http://eslint.org/docs/rules/)) and just add two rules:
- no semi-colons
- two-spaces indents

Is everybody ok with that?

**Comment by Elorfin** [comment]
OK for me.

> no-console: disallow the use of console

Can be problematic as sometimes the console is not used as a debug tool (I personnally use it to really log info or errors in Path and Exo).
Maybe we will need our own interface to log things (so we will be able to disable the output on prod env).

**Comment by stefk** [comment]
> Maybe we will need our own interface to log things

I think there's a logger service in angular. There're also other libs (e.g. https://github.com/visionmedia/debug) that wrap raw console statements and make easy to enable/disable logs for debugging purposes. Using one of these wrappers could solve the problem.

**Comment by Elorfin** [comment]
Yes, it's built in Angular : [https://docs.angularjs.org/api/ng/service/$log](https://docs.angularjs.org/api/ng/service/$log).
I will think to switch to it. Thanks.

The library you point out is nice but IMHO it seems a little overkill to include a new dependency just to manage console.

**Comment by stefk** [comment]
All points have been dealt with, except the indent problem, but I'm not aware of an easy way to solve it. Feel free to open a dedicated issue.
