### ISSUE TITLE
WS création d'un onglet

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#6993]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.0.0

Dans un espace 
En tant GESTIONNAiRE
Créer un onglet 
Sélectionner Widget
-> ERROR 500

Comme admin on n'a pas l'erreur

**Comment by LaurentGruber** [comment]
ça sera corrigé par la prochaine mise à jour.
Au passage les tickets peuvent être créé ici : https://github.com/claroline/Claroline/issues dorénavant, le dépot distribution va disparaitre.
