### ISSUE TITLE
[FlashCardBundle] Error at card creation (Chrome)

### ISSUE THREAD

**Issue by stefk** [claroline/Distribution#708]
JS error when creating a card:

> Cannot read property 'id' of null

Can be reproduced [here](http://pr-706-1466588210.travis-build.claroline.net/claroline/resource/open/claroline_flashcard/113#/create_note) (just click on "Créer").

**Comment by Elorfin** [comment]
The JS is broken in Chromium/Chrome.

If you try to create a card in FF, you will that if you choose a "Note model", 2 more fields are added.
They aren't displayed in chrome.

**Comment by ngodfraind** [comment]
"page not found" when I click on your link.

**Comment by stefk** [comment]
@purplefish32 has destroyed all the running docker instances ;)

**Comment by stefk** [comment]
Closing. @ngodfraind, feel free to reopen if this wasn't solved by #723.
