### ISSUE TITLE
Error importing announcement & survey from Workspace

### ISSUE THREAD

**Issue by ptsavdar** [claroline/Distribution#712]
Tried to import a Workspace previously exported that contained announcements and surveys. Everything worked fine except of the announcement and survey resources that weren't imported. However they are well exported and present in the manifest.yml file of the exported zip file. Here is the zip file: 
[Modele+MOOC+Lyon+1.zip](https://github.com/claroline/Distribution/files/327939/Modele.MOOC.Lyon.1.zip)

Version 7.x-dev #645 hash https://github.com/claroline/Distribution/commit/874000c5e735b1ae837c028cafb9e68e2644b0ff

**Comment by kitan1982** [comment]
There is no importer/exporter implemented for that for the moment.
In the manifest.yml file only the generic datas associated to the resource are present.
The datas related to the resource type are absent.
That's why the resource is not imported.

**Comment by kitan1982** [comment]
Announcements import/export is implemented in this PR #1239
