### ISSUE TITLE
[ResourceManager] Problème de droits d'accès

### ISSUE THREAD

**Issue by eddymarques** [claroline/Distribution#714]
Dans un espace d'activités, j'inscris des utilisateurs pour qu'ils puissent avoir accès aux onglets de l'accueil.
Si je désactive pour les utilisateurs l'accès aux Ressources (donc l'icone n’apparaît pas dans la barre latérale) et si je pointe sur l'URL /workspaces/123456/open/tool/resource_manager j'ai bien un message m'indiquant que je n'ai pas les droits.

Mais si ce même utilisateur utilise l'icone "Ressources" dans la topbar horizontale, il voit le dossier de l'espace auquel il est inscrit, et peut accéder à la racine en voyant les tous fichiers présents dans les ressources.
Alors qu'il devrait aussi avec l'interdiction d'accès
![image](https://cloud.githubusercontent.com/assets/3414956/16271938/3361dd1c-389c-11e6-8333-aafa2e792730.png)
/desktop/tool/open/resource_manager#resources/123456

**Comment by ngodfraind** [comment]
De quelle manière l'accès aux ressource tu as désactivé l'accès aux ressources ?

Modification des droits d'accès sur l'outil outil ou modification des droits sur les ressources ? Si tu as retiré l'accès à l'outil, je pense que c'est normal qu'elles s'affichent toujours dans le bureau.

**Comment by LaurentGruber** [comment]
@eddymarques ping

**Comment by eddymarques** [comment]
Mes excuses en effet j'ai oublié ce ticket là ! :x

== Dans l'Espace d'activité > Paramètres > Outils
L'outil Ressources est en rouge en lecture et modification pour les utilisateurs
== Dans l'Espace d'activité > Paramètres > Ressources
Donner l'accès aux membres de cet espace est coché (car la page d'accueil est une liste de liens mis en forme qui pointe vers un grand nombre d'objets dans l'espace d'activité)

Si on tente l'accès via les URL de l'outil Ressources pour obtenir le listing, j'ai bien le message m'indiquant que je n'ai pas les droits 
/workspaces/123456/open/tool/resource_manager

Mais via l'icone en forme de dossier dans la topbar horizontale, j'ai accès à tout le listing et peut me balader dedans sans problème.

Je déduis, par rapport à la précision que tu me demandes Nico, que techniquement il semble y avoir une logique. Mais par rapport à l'usage il y a une incohérence: on interdit l'accès au listing dans l'ES, mais on peut l'avoir sans problème autre part.

Sinon cela implique d'enlever les droits sur le listing aussi, mais devoir passer sur l'ensemble des documents de l'ES et appliquer sur chacune des Ressources les droits d'accès pour les utilisateurs concernés, et devoir le faire pour chaque nouvel élément?

**Comment by ngodfraind** [comment]
@eddymarques 

En fait, il faut effectivement retirer les droits sur le listing. Éventuellement on peut le faire automatiquement lorsqu'on ajoute/retire l'outil. C'est sans doute ça qu'il manque.

**Comment by eddymarques** [comment]
Je ne pense pas que ce soit ça qu'il faut faire.
Car si on retire les droits sur le listing "[..]cela implique de devoir passer sur l'ensemble des documents de l'EA et appliquer sur chacune des ressources les droits d'accès pour les utilisateurs concernés, et devoir le faire pour chaque nouvel élément". Et sur plusieurs centaines d’éléments c'est difficilement envisageable.
Sachant que c'est notre cas à nous.

Pour moi la page qui donne accès directement aux dossiers Ressources dans la topbar horizontale doit vérifier le même droit que celui qui montre l'icône Ressource dans la barre latérale des EA, géré ici
== Dans l'Espace d'activité > Paramètres > Outils

**Comment by ngodfraind** [comment]
Dans ce cas, on pourrait juste donner l'accès à la racine. Il faudrait configurer manuellement le reste à la main mais il n'y aurait d'erreur de permission en tout cas, et pas d'accès autorisé à des objets privés.
