### ISSUE TITLE
[PathBundle] Import/Export of paths is broken

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#720]
Essai d'exportation - importation d'une ressource
Test sur parcours, forum et exercice
- Exercice : la ressource est correctement placée dans le dossier ad-hoc, le contenu est récupéré mais il crée un dossier QTI_SYS dans la racine (le placer dans le dossier depuis lequel on effectue l'importation)
- Parcours et forum : contenu vide après importation. 
- Dans le parcours, la structure est bien présente, mais vide de titre et de contenu, cf. saisie d'écran : 

![image](https://cloud.githubusercontent.com/assets/16414632/16305505/73b93d24-395a-11e6-9759-968c78b8073e.png)

**Comment by Elorfin** [comment]
The activities are not included in the export.
I will investigate further.

**Comment by LaurentGruber** [comment]
not reproduce
