### ISSUE TITLE
Parcours - Publication - Alerte

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#724]
Bug déjà communiqué

On a beau sauvegarder le parcours, on ne parvient pas à échapper à cette (fausse) alerte 

![image](https://cloud.githubusercontent.com/assets/16414632/16310133/a72926d6-396b-11e6-9c26-49671179eb62.png)

**Comment by ptsavdar** [comment]
Je ne pense pas que cette alerte est "fausse" parce que meme si t'as sauvegarder tes modifications, il faut quand-meme les publier pour les voir dans le mode "visualisation" du parcours. Du coup le message previent l'utilisateur de ce fait-ci.

**Comment by jj-quintin** [comment]
Je me suis mal exprimé

Ce message apparaît après publication, le parcours est donc publié. 

Le message me dit qu'il ne l'est pas

Or il l'est (en vérifiant le résultat du parcours dans le player par exemple)

Ce message apparaît systématiquement, quoi qu'on fasse

**Comment by ptsavdar** [comment]
Dacord. Parce que moi quand je sauvegarde et je publie mes modifications je l'ai pas le message.

**Comment by Elorfin** [comment]
Duplicate #504.
