### ISSUE TITLE
Parcours conditionnel Bug

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#725]
Message d'erreur après publication : 
An exception occurred while executing 'INSERT INTO innova_stepcondition (step_id) VALUES (?)' with params [274]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '274' for key 'UNIQ_C6D7069F73B21E9C', 

dans : 
![image](https://cloud.githubusercontent.com/assets/16414632/16311457/01f7d81e-3971-11e6-82b8-3227948d28e8.png)

**Comment by Elorfin** [comment]
Fixed in master.
