### ISSUE TITLE
[Administration] Gestion des Utilisateurs

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#73]
_From @eddymarques on April 1, 2016 8:30_

Claroline v6.8.4
La nouvelle interface de la Gestion des Utilisateurs côté Administrateur affiche une liste vide sous IE11 (et probablement sous Edge aussi)
![image](https://cloud.githubusercontent.com/assets/3414956/14201846/c7b77816-f7f4-11e5-8963-2a4e4984946d.png)

IE v11.0.9600.18231

_Copied from original issue: claroline/ClaroSupport#39_

**Comment by purplefish32** [comment]
_From @ngodfraind on April 1, 2016 8:32_

Ouch. Il va falloir que j'installe une vm... J'essaye de régler ça début de
semaine prochaine.

2016-04-01 10:30 GMT+02:00 eddymarques <notifications@github.com>:

> Claroline v6.8.4
> La nouvelle interface de la Gestion des Utilisateurs côté Administrateur
> affiche une liste vide sous IE11 (et probablement sous Edge aussi)
> [image: image]
> <https://cloud.githubusercontent.com/assets/3414956/14201846/c7b77816-f7f4-11e5-8963-2a4e4984946d.png>
>
> IE v11.0.9600.18231
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/ClaroSupport/issues/39>
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by ngodfraind** [comment]
Sous Edge ça fonctionne.
Sous IE11 c'est vide. 

Je n'ai pas encore compris pourquoi.

**Comment by ngodfraind** [comment]
Trouvé.

object doesn't support property or method 'assign'

Probablement une des deps angular.

Maintenant pour corriger ça va être une autre paire de manche car les outils de debugs d'angular sont pas géniaux en dehors de chrome.

**Comment by stefk** [comment]
Could be `Object.assign`. According to this [table](http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign), IE11 is the only one that doesn't support it. If that's a case, a simple polyfill could be enough.

**Comment by ngodfraind** [comment]
I'm not comfortable enough with babel / webpack to do it (yet).
