### ISSUE TITLE
[ExoBundle] Import IMS QTI et affichage question associative

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#733]
Après l'import, je vois ceci à partir de la banque de questions
![image](https://cloud.githubusercontent.com/assets/895878/16340470/9b806048-3a28-11e6-898f-c0c91d5adb10.png)
 et ceci à partir de l'exercice
![image](https://cloud.githubusercontent.com/assets/895878/16340493/bcab2e06-3a28-11e6-84b9-272f957c3c1e.png)

**Comment by david42** [comment]
Bonjour,

Je pense que c'est un problème lié au player mais qui a été corrigé

**Comment by david42** [comment]
Oups j'ai envoyé ma réponse sans l'avoir terminée.
Sur la branche 7.x-dev pas de problème, je n'ai pas testé en 7.0.0.
