### ISSUE TITLE
[ExoBundle] Category is required

### ISSUE THREAD

**Issue by ngodfraind** [claroline/Distribution#737]
On commit a36c3606bafde56bf0bb720226bdf49b58fe1325

500 error is triggered if a question doesn't have a category.

```
Catchable Fatal Error: Argument 1 passed to Proxies\\__CG__\\UJM\\ExoBundle\\Entity\\Question::setCategory() must be an instance of UJM\\ExoBundle\\Entity\\Category, null given
```

**Comment by stefk** [comment]
That can't be related to the commit you linked to.

**Comment by ngodfraind** [comment]
I know, but it's the commit my platform currently is. I don't know where it come from. It may already have been fixed.

**Comment by Elorfin** [comment]
I need to test it because I've never add this problem. And I never set a category for questions.

**Comment by ngodfraind** [comment]
It happened after an update I think.

**Comment by Elorfin** [comment]
Have you tried to create the question from an Exercise or from the Bank ?

**Comment by Gatomlo** [comment]
Il s'agit d'une question partagée créée avant la mise à jour. Elle a été créée depuis l'exerciseur. Si on n'indique pas de catégorie lors d'une modification, ça plante. D'autre part cela ne fonctionne qu'avec la catégorie "défault" j'ai essayé d'ajouter une nouvelle catégorie depuis la question mais l'enregistrement plante. Par contre j'ai retrouvé la catégorie que j'avais essayé de créer dans une autre question. Elle a donc bien été générée.
