### ISSUE TITLE
Changes in PathBundle

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#738]
@jj-quintin suggested some slight and some more heavy changes in Path : 
- [ ] display conditionnally the condionnality : 
Add a checkbox in the path management (hence a "condition" field in the Path entity). If that checkbox is unchecked, the condition block is not displayed.
- [ ] more explicit ("user friendly") texts :
- "Condition d'accès pour Nom Step suivante" would become "Condition d'accès à l'étape Nom Step suivante"
- "Attention, l'activité que vous avez choisi est en évaluation manuelle : vous ne pouvez utiliser les critères relatifs à une évaluation pour cette étape" would become "Pour cette étape, vous avez choisi un type d'évaluation manuel. Les conditions disponibles se limitent dans ce cas aux utilisateurs (groupe ou équipe)" (=> positive feedback)
- "Nombre de fois où l'activité a été effectuée" would become "Nombre de fois où l'activité doit être réalisée"
- "Statuts de l'activité" would become "État de l'activité"
- "Vous n'avez pas rempli les conditions pour accéder à l'étape Step 4.1 parce que : l'activité doit être tentée 2 fois, actuellement vous l'avez effectuée 0 fois : non" would become "Vous n'avez pas rempli les conditions pour accéde à l'étape Step 4.1 parce que l'activité doit être réalisée à 2 reprises et que, actuellement, vous l'avez effectuée 0 fois : non" (or rather add a icon for failure or success instead of yes/no
- [ ] align to the left the text for the warning messages

**Comment by Elorfin** [comment]
The translations have been validated and fixed recently, so the requests are no longer needed.
Texts are corretly aligned in the `master`.
After discussions, the checkbox for conditions will not be added because it's usesless and will just complicate things (the conditions are enough hidden in the current version).

This issue can be closed.
