### ISSUE TITLE
ExoBundle : Passage d'un exercise sans étre connecté (anonyme)

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#74]
_From @charlotte42 on March 31, 2016 13:4_

Pouvoir passer un exercice sans être connecté à la plateforme. 
Existant dans la version Php

_Copied from original issue: claroline/ClaroSupport#38_

**Comment by Elorfin** [comment]
It's the implementation of Anonymous mode

**Comment by LaurentGruber** [comment]
faire en sorte que le paramconverter accepte les anonymes et dans angular pour afficher la correction de l'anonyme, il va falloir voir ...

**Comment by Elorfin** [comment]
There is a first implementation of this feature in the master branch.
It can be improved, but it's working.

I postpone it for the 16.12, I will have no time to check it for the 16.09.
