### ISSUE TITLE
[CollecticielBundle] Can't submit evaluation

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#748]
Le bouton Enregistrer enregistre mais le pop up reste gelé.
Le bouton Transmettre ne fonctionne pas 
![image](https://cloud.githubusercontent.com/assets/895878/16444732/ce7b5092-3ddf-11e6-83ca-43847491cca1.png)

**Comment by ericvincenterv** [comment]
What version did you use ?

If the button "Transmettre" in the modal doesn't work, it is ok in the list of documents ?

**Comment by jj-quintin** [comment]
Et dire que je ne peux même tester cette version (pas installée chez nous), donc je ne peux pas apporter ma contribution ici

@clarophil : tu as une solution qui me permettrait de tester les choses en utilisant une instance qui, chez vous, est mise à jour plus régulièrement que chez nous ?

**Comment by ericvincenterv** [comment]
@clarophil : I can not reproduce this bug locally

**Comment by ericvincenterv** [comment]
@clarophil : do you try to to the same thing with the latest release ?

**Comment by clarophil** [comment]
Tested on master branch
When I want to "Manage this evaluation"  I have this bug so I can't test this issue

Notice: Undefined offset: 2 in /var/www/master/vendor/claroline/distribution/plugin/collecticiel/Controller/DropzoneController.php on line 706

Notice: Undefined offset: 1 in /var/www/master/vendor/claroline/distribution/plugin/collecticiel/Controller/DropzoneController.php on line 706

Notice: Undefined offset: 2 in /var/www/master/vendor/claroline/distribution/plugin/collecticiel/Controller/DropzoneController.php on line 709

Notice: Undefined offset: 1 in /var/www/master/vendor/claroline/distribution/plugin/collecticiel/Controller/DropzoneController.php on line 709

Fatal error: Call to a member function format() on a non-object in /var/www/master/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/DateTimeType.php on line 53

**Comment by ericvincenterv** [comment]
@clarophil : this bug is probably not the same thing. This time, I reproduiced it.

**Comment by ericvincenterv** [comment]
I create this issue https://github.com/claroline/Distribution/issues/852 for your daily comment.

**Comment by ericvincenterv** [comment]
@clarophil : 
yours remarks are solved in this issue : https://github.com/claroline/Distribution/issues/852

> Tested on master branch
> When I want to "Manage this evaluation" I have this bug so I can't test this issue
> 
> Notice: Undefined offset: 2 in /var/www/master/vendor/claroline/distribution/plugin/collecticiel/Controller/DropzoneController.php on line 706
> 
> Notice: Undefined offset: 1 in /var/www/master/vendor/claroline/distribution/plugin/collecticiel/Controller/DropzoneController.php on line 706
> 
> Notice: Undefined offset: 2 in /var/www/master/vendor/claroline/distribution/plugin/collecticiel/Controller/DropzoneController.php on line 709
> 
> Notice: Undefined offset: 1 in /var/www/master/vendor/claroline/distribution/plugin/collecticiel/Controller/DropzoneController.php on line 709
> 
> Fatal error: Call to a member function format() on a non-object in /var/www/master/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/DateTimeType.php on line 53
>

**Comment by ericvincenterv** [comment]
@clarophil : I think now it's ok.
