### ISSUE TITLE
[CoreBundle] La réorganisation de l'ordre des ressources non visible par les collaborateurs

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#752]
Si je change l'ordre des ressources, le nouvel ordre est visible pour les gestionnaires mais pas pour les collaborateurs.

**Comment by jj-quintin** [comment]
Oui, déjà présent en V5 et déjà signalé. Je pense qu'il y a déjà un ticket à ce propos

**Comment by ngodfraind** [comment]
Reproduit

**Comment by ngodfraind** [comment]
Fixed by #1240
