### ISSUE TITLE
ExoBundle : Exercice copie question / banque de questions

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#76]
_From @charlotte42 on March 31, 2016 8:47_

Lorsqu'une question est liée à une copie, la question de ne doit plus être supprimable dans la banque de question et le bouton pour l'éditer doit être en rouge.

_Copied from original issue: claroline/ClaroSupport#36_

**Comment by Elorfin** [comment]
@claroline/ujm 

do we need to lock the edition of the Question in the Exercise too ?
because if we need, please reopen the issue and assign it to @claroline/innova.

**Comment by marion42** [comment]
Yes, it must be done. Thanks, I haven't seen this.

**Comment by Elorfin** [comment]
@claroline/ujm : is that normal in th bank that you only color the edit button in red and not lock the action (I can still edit my questions even if they have papers) ?

**Comment by Pauooo** [comment]
@claroline/ujm : when a question is linked to a paper (red pen) is all type of edition locked or is it possible to edit some type of fields (text ?). For example, we can imagine that a teacher needs to reformulate the question seeing that none of his students is understanding the aim of the question.
