### ISSUE TITLE
Access psersonal work space

### ISSUE THREAD

**Issue by david42** [claroline/Distribution#769]
Many users have error to access their personal workspace :

Uncaught PHP Symfony\Component\Debug\Exception\FatalErrorException Exception: "Error: Call to a member function getRoles() on null" at /webapps/claroline-connect/vendor/claroline/distribution/main/core/Manager/WorkspaceManager.php line 464

URL : https://claroline-connect.univ-st-etienne.fr/web/app.php/workspaces/3/open
Referer : https://claroline-connect.univ-st-etienne.fr/web/app.php/desktop/tool/open/home

**Comment by ngodfraind** [comment]
C'est possible que le workspace n'ai plus de "creator" ?

**Comment by LaurentGruber** [comment]
@david42 ?

**Comment by LaurentGruber** [comment]
need info @david42

**Comment by LaurentGruber** [comment]
no info
