### ISSUE TITLE
Validité compte utilisateur

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#770]
- [x] possibilité de rendre un compte utilisateur inactif (impossible de se connecté mais toujours présent)
- [x] possibilité de définir une période de validité du compte utilisateur avec une date à partir de laquelle compte serait actif et une date à partir de laquelle le compte deviendrait automatiquement inactif

**Comment by CPASimUSante** [comment]
:+1:

**Comment by ngodfraind** [comment]
C'est déjà là. Il existe un paramètre de durée des comptes utilisateurs dans l'administration.
Une fois l'utilisateur créé, il n'y a pas d'interface pour changer ces données mais c'est bien présent en db.
Dans l'entité User:
- expirationDate
- isEnabled (mais pour le isEnabled je ne suis pas sûr de comment ça se comporte derrière. Si la validation des compte par email est activé, il est a false et l'utilisateur ne peut se connecter tant qu'il n'a pas répondu au mail d'inscription. Ça à le même effet.
