### ISSUE TITLE
[Collecticiel] Paramètre évaluation

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#774]
Modifier le titre Evaluation (notation) par Evaluation

![image](https://cloud.githubusercontent.com/assets/16414632/16559571/f5a806da-41ed-11e6-99f3-6d41d244cada.png)

**Comment by ericvincenterv** [comment]
Ok. Difficulty : XS

**Comment by ericvincenterv** [comment]
https://github.com/claroline/Distribution/commit/13dde85ee5d4190e57be10f17793e2a68d5420e7
