### ISSUE TITLE
[Collecticiel] Paramètre Notation Critères d'évaluation

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#775]
Implémenter l'ajout de critères pour la modalité notation

Ajouter le bouton bleu crayon + Gérer l'évaluation pour accéder à l'écran permettant d'ajouter les critères d'évaluation

![image](https://cloud.githubusercontent.com/assets/16414632/16559606/5789ad68-41ee-11e6-8aeb-b405093b9cde.png)

**Comment by ericvincenterv** [comment]
See this issue : https://github.com/claroline/Distribution/issues/507

**Comment by ericvincenterv** [comment]
See this issue too :  https://github.com/claroline/Distribution/issues/789
