### ISSUE TITLE
[Collecticiel] Rédiger un texte

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#777]
Le titre du document ne devrait pas être obligatoire

Le champ texte est obligatoire

Dans le cas où ce dernier champ (le champ principal) n'est pas renseigné, afficher le message d'alerte "Veuillez renseigner ce champ" en  relation avec ce champ

![image](https://cloud.githubusercontent.com/assets/16414632/16559756/7d836274-41ef-11e6-999b-52f349495f16.png)

**Comment by ericvincenterv** [comment]
OK. Difficulty : XC

**Comment by jj-quintin** [comment]
si c'est XC, reporter à plus tard

**Comment by ericvincenterv** [comment]
Vu avec @jj-quintin : à faire plus tard.
