### ISSUE TITLE
[Collecticiel] Transmettre une demande - Curseur main

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#778]
Utiliser la version curseur main pour tous les cas où le lien est actif (vérifier partout)

Deux exemples dans lesquels ce n'est pas encore le cas : 

Version commentaire (sans évaluation), espace de l'étudiant, Transmettre une demande de commentaires

![image](https://cloud.githubusercontent.com/assets/16414632/16559873/2d8b091a-41f0-11e6-97d6-88d39074c47b.png)

Version appréciation, Demandes adressées, Transmettre une évaluation

![image](https://cloud.githubusercontent.com/assets/16414632/16560943/acfa9908-41f6-11e6-95b5-834e2449be42.png)

**Comment by ericvincenterv** [comment]
Ok. Difficulty : XS
