### ISSUE TITLE
[Collecticiel] Demandes adressées - Bug nombre d'opérations

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#779]
Il devrait y en avoir 4 opérations en attente (de commentaires) ici et non 7 (à noter que pour les accusés de réception de cette saisie d'écran cela fonctionne correctement)

![image](https://cloud.githubusercontent.com/assets/16414632/16560083/7264ebfe-41f1-11e6-8be3-18a5ae5c943f.png)

Même après avoir apporté un commentaire, le compteur d'opérations en attente reste bloqué sur 7 : 

![image](https://cloud.githubusercontent.com/assets/16414632/16560193/1dbb8166-41f2-11e6-9bb4-6786cb2f5ceb.png)

**Comment by ericvincenterv** [comment]
OK. Difficulty : C
