### ISSUE TITLE
[Collecticiel] Demandes adressées - Bug nom du "demandeur"

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#780]
Quand l'enseignant dépose lui-même un document dans un collecticiel d'un étudiant, qu'il transfet une demande pour ce document (qu'il dépose lui-même), c'est le nom de celui qui a déposé qui devrait apparaître dans les demandes adressées (règle = le nom de celui qui a déposé le document), pas le nom de l'étudiant

**Saisie 1** (je suis enseignant, j'ai déposé le document facette.csv et j'ai adressé une demande pour ce même document)

![image](https://cloud.githubusercontent.com/assets/16414632/16560418/a7b4c232-41f3-11e6-9d8b-99bfc6ea9ded.png)

**Saisie 2** (dans les demandes adressées, c'est donc mon nom qui devrait apparaître en face de facette.csv, et non celui du propriétaire de l'espace, Etu1)

![image](https://cloud.githubusercontent.com/assets/16414632/16560392/66140252-41f3-11e6-8dcf-683de8c5aa23.png)

**Comment by ericvincenterv** [comment]
OK. Difficulty : C
