### ISSUE TITLE
[Collecticiel]Appréciation

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#781]
Bug après avoir fait ceci : 

- Choix de l'appréciation
- Clic sur le bouton bleu Gérer les évaluations
- Construction de l'échelle
- Suppression du critère proposé par défaut
- Ajout de trois critères
- Clic sur Sauvegarder

Après multiples tests, ceci se produit lorsqu’on supprime le critère proposé par défaut (Commentaire)

Message d'erreur : 

Notice: Undefined index: criteriaName in /var/www/demo-v6.innovalangues.net/vendor/claroline/distribution/plugin/collecticiel/Manager/GradingCriteriaManager.php on line 48

Erreur interne du serveur. Veuillez contactez l'administrateur de la plateforme.

**Comment by ericvincenterv** [comment]
Non reproduit en local.

**Comment by ericvincenterv** [comment]
Message d'erreur obtenu : 
"Notice: Undefined variable: gradingCriteriaData in /var/www/demo-v6.innovalangues.net/vendor/claroline/distribution/plugin/collecticiel/Manager/GradingCriteriaManager.php on line 56"
