### ISSUE TITLE
[Collecticiel] Appréciation - Gérer les évaluations - Non sauvegarde formulaire de base

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#782]
Si l'on accède à la gestion des évaluations et que l'on sauvegarde les informations de cette dernière, au retour au formulaire de départ (paramètres), le choix de l'évaluation (échelle d'appréciation) est bien sauvegardé mais pas le reste : types de documents, ouverture, Publication, accusé de réception etc.

![image](https://cloud.githubusercontent.com/assets/16414632/16560634/f2a609da-41f4-11e6-8404-9e287d10a70d.png)

**Comment by ericvincenterv** [comment]
OK. Reproduced locally.
Difficulty : M.
