### ISSUE TITLE
[Collecticiel] Appréciation - Gestion des évaluations - Boutons + degré d'appréciation

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#783]
remplacer "+ Ajouter un degré d'apréciation" par "+ Ajouter un degré d'appréciation" (2 p à appréciation)

![image](https://cloud.githubusercontent.com/assets/16414632/16560755/9afd5336-41f5-11e6-90c4-a07e6ccbab95.png)

**Comment by ericvincenterv** [comment]
@LaurentGruber : please, let me to assign myself the multiple issue.

**Comment by ericvincenterv** [comment]
OK. Difficulty : XS
