### ISSUE TITLE
[Collecticiel] Appréciation - Message alerte parasite

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#784]
Après avoir apporté une évaluation par appréciation à un document (ici 1 et 2)

![image](https://cloud.githubusercontent.com/assets/16414632/16561017/31965814-41f7-11e6-89b5-f3a7a59677b9.png)

![image](https://cloud.githubusercontent.com/assets/16414632/16561027/3f036d70-41f7-11e6-9843-b07b63426223.png)

**Comment by ericvincenterv** [comment]
Duplicate issue with this : https://github.com/claroline/Distribution/issues/501

**Comment by jj-quintin** [comment]
ok, supprimer/fermer ce ticket et régler le problème tant pour la notation que pour l'appréciation de ce fait

**Comment by ericvincenterv** [comment]
https://github.com/claroline/Distribution/issues/501 est fermé.
Je laisse donc ce ticket ouvert.
