### ISSUE TITLE
[Collecticiel] Demandes adressées - Menu actions - Transmettre les évaluations

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#785]
Implémenter l'option "Transmettre les évaluations" dans le menu des actions qui permet, après sélection d'un ou de plusieurs documents, de transmettre les évaluations 

![image](https://cloud.githubusercontent.com/assets/16414632/16561078/8a17d29c-41f7-11e6-8882-7506125b60c8.png)

**Comment by ericvincenterv** [comment]
OK. Difficulty : C
