### ISSUE TITLE
[Collecticiel] Transmettre évaluation - Message de confirmation

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#787]
Remplacer

Communication d'une demande d'évaluation
Voulez-vous transmettre une demande d'évaluation pour ce document ?

Communication de l'évaluation aux étudiants
Voulez-vous transmettre l'évaluation ? Cette action est irréversible et vous ne pourrez plus modifier l'évaluation. 

![image](https://cloud.githubusercontent.com/assets/16414632/16561371/1e263496-41f9-11e6-805e-19b88e2cd446.png)

**Comment by ericvincenterv** [comment]
OK. Difficulty : XS.
