### ISSUE TITLE
[Collecticiel] Notation - Après transmission notation

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#788]
A adapter d'après la suite de l'implémentation des critères dans la notation (non encore visible)

Changement et visualisation de l'évaluation sans changement possible : adopter les mêmes principes que pour l'appréciation : 

Info-bulles : 
- Pas encore d'évaluation ajoutée : "Ajouter une évaluation"
- Evaluation ajoutée mais pas encore transmise : "Consulter/Modifier l'évaluation"
- Evaluation ajoutée et transmise : "Consulter l'évaluation"

![image](https://cloud.githubusercontent.com/assets/16414632/16561578/3330cc06-41fa-11e6-9f3e-4f7bdb7e622a.png)

**Comment by ericvincenterv** [comment]
OK. Difficulty : XS.

**Comment by ericvincenterv** [comment]
@jj-quintin : 
Ces info-bulles  : 
- Pas encore d'évaluation ajoutée : "Ajouter une évaluation"
- Evaluation ajoutée et transmise : "Consulter l'évaluation"
sont déjà effectives, non ?

**Comment by jj-quintin** [comment]
Pour l'instant, comme le montre la saisie d'écran ci-avant, lorsque l'évaluation a été transmise à l'étudiant, on a "Consulter/Modifier l’évaluation" dans l'info bulle alors que l'on devrait avoir "Consulter l'évaluation" (puisqu'on ne peut plus la modifier)

Je rappelais les règles suivantes pour l'affichage des infos-bulles à ce niveau, règles valables pour la notation et l'appréciation : 

- Pas encore d'évaluation ajoutée : "Ajouter une évaluation"
- Evaluation ajoutée mais pas encore transmise : "Consulter/Modifier l'évaluation"
- Evaluation ajoutée et transmise : "Consulter l'évaluation"

**Comment by ericvincenterv** [comment]
@jj-quintin : fonctionnement décrit non reproduit.

**Comment by ericvincenterv** [comment]
@jj-quintin : 
en fait, ceci se produit quand on transmet l'évaluation par le choix de la colonne "Transmettre l'évaluation" et non pas quand on le fait via la modale de saisie de l'évaluation.
