### ISSUE TITLE
[Collecticiel] Appréciation - Infobulle ""Consulter/modifier une évaluation"

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#789]
Détail : plutôt l'évaluation que "une" évaluation

Infobulle : 

remplacer "Consulter/modifier une évaluation"
par "Consulter/modifier l'évaluation"

![image](https://cloud.githubusercontent.com/assets/16414632/16561910/fce28dea-41fb-11e6-8596-ee17655826f6.png)

**Comment by ericvincenterv** [comment]
OK. Difficulty : XS
