### ISSUE TITLE
[MessageBundle] Checkbox d'envoi par courriel disparue

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#791]
Dans la messagerie, la checkbox et la phrase 
 Je veux recevoir les notifications sur xxx@ecam.be 
ont disparu dans la V7

Le groupe ergonomie de la remettre et de la remplacer, par
Recevoir une copie des messages sur xxx@ecam.be

**Comment by ngodfraind** [comment]
Je viens de regarder sur le master et la checkbox s'y trouve bien. Le serveur mail est-il configuré ? (rien ne s'affiche si ce n'est pas le cas).

Je change le message de la checkbox.

**Comment by clarophil** [comment]
Sur hevinci  qui vient de passer sur le master toujours pas de checkbox
![image](https://cloud.githubusercontent.com/assets/895878/18005546/e853f10c-6b9a-11e6-9854-5d4edfdfad87.png)

**Comment by clarophil** [comment]
Effectivement le serveur de mail n'est pas bien configuré
