### ISSUE TITLE
[ExoBundle] Player - Terminer l'exercice (vs. Interrompre)

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#798]
Actuellement, on peut terminer un exercice après avoir terminé une étape
Alors qu'il existe le bouton Interrompre pour arrêter un exercice en cours de route

**Terminer vs. Interrompre**
La proposition est de simplifier : 
1) Interrompre uniquement activable quand l'exercice n'est pas complètement terminé
2) Terminer uniquement activable quand l'exercice est totalement terminé

**Alerte**
Actuellement : 
Êtes vous sûr de vouloir terminer l'exercice ? Vous ne pourrez plus modifier vos réponses.
Cancel Ok

Le texte "Vous ne pourrez plus modifier vos réponses" laisse penser qu'on peut le faire (dans la version formative que je teste du moins ce ne semble pas être possible)

Si la proposition ci-dessus convient (cf. Terminer vs. Interrompre), on pourrait supprimer cette alerte (qui fait "peur")

Si pas possible ou pas indiquée, modifier le texte par : 

Voulez-vous terminer l'exercice ?

**Remplacer Cancel par Annuler**

**Comment by Elorfin** [comment]
No longer relevant.
