### ISSUE TITLE
[ExoBundle] Player - Navigation entre étapes - Bug

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#806]
Il y a deux étapes, j'ai terminé la première

Impossible de passer à la suite (bouton flèche suivan inactif/grisé et menu avec seulement l'étape 1

![image](https://cloud.githubusercontent.com/assets/16414632/16589813/09217f7e-42d5-11e6-877c-830d0000293d.png)

**Comment by Elorfin** [comment]
That's because your paper has been created before you add the second step to the Exercise (so it doesn't contain the second step).

There was a bug on the step count in the menu (counf of the Exercice's steps instead of Paper's ones) which is fixed in the last version.
