### ISSUE TITLE
[ExoBundle] Player - texte à trou - Bug dans l'analyse de la réponse

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#807]
Cf. Saisie ci-dessous, la réponse est incorrecte (X rouge) et impossible de passer à l'étape suivante mais elle est correcte d'après le feedback général

![image](https://cloud.githubusercontent.com/assets/16414632/16589909/8e06398c-42d5-11e6-9907-867a7de043f3.png)

**Comment by eldoniel** [comment]
I was unabled to reproduce the bug.

In this example, was the answer "!" supposed to be the right answer or not? If not, what was the right answer?

**Comment by eldoniel** [comment]
Fixed by #833
