### ISSUE TITLE
[ExoBundle] Player - Bug retour à l'étape précédente

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#808]
Je viens de l'étape 2 via le menu déroulant
J'arrive dans l'étape 1
Je dois valider à nouveau une question déjà répondue et correcte

![image](https://cloud.githubusercontent.com/assets/16414632/16589987/eff16e8c-42d5-11e6-8630-27df1c530cb6.png)

**Comment by eldoniel** [comment]
This issue was already mentioned in https://github.com/claroline/Distribution/issues/531

Please avoid creating duplicate issues.
