### ISSUE TITLE
[ExoBundle] Player - Texte à trous - Bug dans l'analyse des réponses (suite)

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#809]
Réponse correcte considérée comme incorrecte

![image](https://cloud.githubusercontent.com/assets/16414632/16590082/542dba18-42d6-11e6-866b-675b2e82f193.png)

Comme le montre l'éditionde cette question

![image](https://cloud.githubusercontent.com/assets/16414632/16590127/80210396-42d6-11e6-9f85-f1c58f610767.png)

**Comment by eldoniel** [comment]
Fixed by #833
