### ISSUE TITLE
[ExoBundle] Après "Terminer l'exercice" - Normal ?

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#810]
J'ai beau changer les paramètres de cet exercice (et ne pas demander la correction après le "test"), j'obtiens toujours la liste complète de la correction après avoir terminé un exercice (cf. saisie d'écran)

![image](https://cloud.githubusercontent.com/assets/16414632/16590385/a42c203a-42d7-11e6-821e-f3b5b977aa8d.png)

Paramètres de l'exercice : 

![image](https://cloud.githubusercontent.com/assets/16414632/16590446/e4385a4a-42d7-11e6-8c82-865ad882f22e.png)

**Comment by Elorfin** [comment]
That's not a bug.
The administrators of an Exercise have always access to the corrections and scores.
