### ISSUE TITLE
[ExoBundle] Paramètres - Adapter la terminologie (new)

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#811]
en référence à #542 que l'on peut fermer pour ouvrir ce ticket plus récent et plus actuel (des changements mineurs étant apparus depuis)

Remplacer, dans les paramètres de l’exercice les termes suivants. La situation actuelle n'est plus tjs adaptée vu l'évolution de l'exercice

Définition de l’exercice par **Vue d'ensemble**(_il me semble qu'il s'agit en effet bien d'éléments affichés dans la vue d'ensemble_)
Questions par **Tirage aléatoire** (_il s'agit bien de ça et uniquement du tirage aléatoire. Question de plus n'est plus conforme, il s'agit bien de tirer aléatoirement des étapes_)
Ordre des étapes aléatoire par **Ordre aléatoire des étapes** (ma préférence, mais c'est un détail)
Dans le titre de la rubrique "A la fin du test" par "**Résultats**"
Disponibilité de la note par **Affichage du score**
Passage par **Passation**
Sortie du test par **Permettre d'interrompre l'exercice** (_voir également le ticket #798 Terminer vs. Interrompre_)
Nombre d'essai maximum par **Nombre de tentatives maximum**
Verrouiller le test par **Verrouiller l’exercice**

**Comment by eldoniel** [comment]
@UJM-dev Do you agree to these modifications?

**Comment by LaurentGruber** [comment]
ok for me

**Comment by eldoniel** [comment]
Done with https://github.com/claroline/Distribution/pull/871
