### ISSUE TITLE
[PathBundle] Ressources complémentaires, ordre d'affichage (Bug)

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#828]
(7.x-dev)
Dans la situation ci-dessous, pas moyen de placer la ressource complémentaire "Déposer son projet de scénario" à droite de "Equipe". Je supprime Déposer son projet de scénario, l'ajoute à nouveau. Elle apparaît bien à l'extrême droite, sauvegarde (ok, elle reste bien à droite). Après publication, la ressource en question est replacée à l'endroit initial (cf. saisie)

![image](https://cloud.githubusercontent.com/assets/16414632/16691045/348140ca-452b-11e6-8d92-95057d6d0eb1.png)

**Comment by Elorfin** [comment]
That's not a bug because this feature simply does not exist.

**Comment by Elorfin** [comment]
What you want can not be done without keeping the order of the Resources.

#1457 replaces this one (it's a new feature, not a bug).
