### ISSUE TITLE
Orthographe : "Il y a 1 années"

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#83]
_From @LaurentGruber on March 23, 2016 12:31_

_From @purplefish32 on January 18, 2016 10:42_

Constaté sur la v5 :
Sur un widget de page d'accueil on peut voir "Il y a 1 années" , quand c'est au singlulier il faut enlever le "s"

_Copied from original issue: claroline/Claroline#715_

_Copied from original issue: claroline/ClaroSupport#1_

**Comment by ngodfraind** [comment]
Je pourrais mettre la date de création du widget à la place.

**Comment by LaurentGruber** [comment]
Personnellement je pense qu'on peut juste supprimer complètement la phrase, je ne pense pas que ça soit super util comme information...
