### ISSUE TITLE
small bug in Resource manager

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#830]
Since a very long time : 6.x i think, there is this error in the js console when you are in the resource manager :
error 500 http://app_dev.php/workspaces/2/open/tool/grayscale.svg
by the name, i'd say it's a background.

Doesn't seem to break any functionnality though...but who knows. I report it because it says 500 and not 404 (or else)

**Comment by Elorfin** [comment]
It says 500 because `http://app_dev.php/workspaces/2/open/tool/` calls a symfony controller, it's not just file loading.

I can not reproduce it on the `master` branch.

What kind of Resource do you have in your workspace ? It might be related to it.

**Comment by ngodfraind** [comment]
I'm unable to reproduce aswell.
