### ISSUE TITLE
bug for text resource creation

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#831]
I have a 7.0.x that i branched then on master, so maybe something went wrong.
When i'm on the resource manager, when i try to create a text resource, i fill the form but then i have an error 500 when i submit : 

```
Error: Call to a member function getText() on array

In vendor/claroline/distribution/main/core/Listener/Resource/TextListener.php at line 87   -
            $published = $form->get('published')->getData();
            $event->setPublished($published);
            $revision = new Revision();
            $revision->setContent($form->getData()->getText());
            $revision->setUser($user);
            $text = new Text();
            $text->setName($form->getData()->getName());
```

**Comment by LaurentGruber** [comment]
On master : Uncaught PHP Symfony\Component\Debug\Exception\FatalThrowableError Exception: "Fatal error: Call to a member function getText() on array" at /var/www/html/claroline/vendor/claroline/distribution/main/core/Listener/Resource/TextListener.php line 87
