### ISSUE TITLE
small bug in webpack loading

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#838]
When i install a dev-master, i have this error thrown at the end of the webpack log when i do 
`npm run watch`

```
ERROR in ./vendor/claroline/distribution/plugin/exo/Resources/modules/paper/module.js
Module not found: Error: Cannot resolve module 'at-table/dist/angular-table' in /home/user/www/claroline/claroline-path-lock/claroline-16.05/vendor/claroline/distribution/plugin/exo/Resources/modules/paper
 @ ./vendor/claroline/distribution/plugin/exo/Resources/modules/paper/module.js 11:0-38
```

But after that, it says `webpack: bundle is now VALID`
so it must not be a big bug

**Comment by Elorfin** [comment]
That's because you haven't updated client libraries.
Just run `npm update` to grab the at-table library and all will be fine.

**Comment by CPASimUSante** [comment]
when i do npm update nothing happens and the message is still there... maybe a silent error

**Comment by Elorfin** [comment]
Do you have `at-table` in `web.packages` ?
You can try to do a `npm install` instead.

**Comment by CPASimUSante** [comment]
No i don't have it in the web/packages.
i just tried `npm install` but it doesn't add it.

If it's just me it's okay, must be the way i installed Claroline : from 7.0x branched to master

**Comment by Elorfin** [comment]
Sorry my bad, you need to run bower and not npm to grab the lib :s.

**Comment by CPASimUSante** [comment]
yes npm run bower did the trick. thanks.
