### ISSUE TITLE
Bug : potential problem for IE 

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#84]
_From @LaurentGruber on March 23, 2016 12:31_

_From @CPASimUSante on December 12, 2015 11:36_

there is a remaining `console.log(home.path);` in  /vendor/claroline/js/libraries.js that is loaded on every page.
This can be a problem for older IE that does not recognize console.log() and thus beak the use of js

Seen on latest 6.6.7 (don't know about previous versions)

_Copied from original issue: claroline/Claroline#714_

_Copied from original issue: claroline/ClaroSupport#2_

**Comment by ngodfraind** [comment]
#180 removes most console.log.
