### ISSUE TITLE
[ExoBundle] Association "A lier" Souci d'affichage

### ISSUE THREAD

**Issue by jj-quintin** [claroline/Distribution#851]
Après tentative de déplacer un lien déjà positionné, le résultat est le suivant :  
![image](https://cloud.githubusercontent.com/assets/16414632/16809202/aae210da-491f-11e6-90a4-56723a2f5863.png)

**Comment by Elorfin** [comment]
Can not be reproduce, neither with Firefox nor Chrome on the `master` branch.
