### ISSUE TITLE
[ExoBundle] Erreur à l'export CSV des résultats

### ISSUE THREAD

**Issue by eddymarques** [claroline/Distribution#869]
Erreur non spécifique qui se produit sur tous les exports des Exercices à l'heure actuelle
Avec ce log:

{"error":{"code":500,"message":"Internal Server Error","exception":[{"message":"Attempted to call an undefined method named \"get\" of class \"UJM\\ExoBundle\\Controller\\Api\\ExerciseController\".","class":"Symfony\\Component\\Debug\\Exception\\UndefinedMethodException","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/data\/claroline\/vendor\/claroline\/distribution\/plugin\/exo\/Controller\/Api\/ExerciseController.php","line":187,"args":[]}]}]}}

**Comment by CPASimUSante** [comment]
It seems that the problem lies in the fact that the translator service is not available : 
`$rowCSV[] = $this->get('translator')->trans('no_finish', [], 'ujm_exo');`
whether the class should extend Controller, or add the translator service as a dependency injection.

To be confirmed
