### ISSUE TITLE
Bug : Drag and drop not available in Resource manager

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#87]
_From @LaurentGruber on March 23, 2016 12:34_

_From @stmolivier on October 15, 2015 13:28_

When i create, upload new ressource (from the Desktop > Resource) in any workspace, i can't drag and drop after they are created/uploaded. I have to change page several times and come back so that i can drag and drop.

_Copied from original issue: claroline/Claroline#710_

_Copied from original issue: claroline/ClaroSupport#5_

**Comment by LaurentGruber** [comment]
@stmolivier @CPASimUSante c'est toujours d'actualité ?

**Comment by CPASimUSante** [comment]
Je viens de tester sur le build travis pr-855-1468911289. A priori j'ai toujours le même problème : 
Quand j'arrive dans l'"espace 1", je ne peux pas faire de DND sur les ressources (déjà créées ou pas). Si je fais F5, ça fonctionne.

**Comment by CPASimUSante** [comment]
When i create ressources or when i come for the first time on a WS ressource manager
![sortable1](https://cloud.githubusercontent.com/assets/14015697/18558862/08ffa7f4-7b75-11e6-9614-eff5f642a9c1.jpg)

then if i refresh  (F5)
![sortable2](https://cloud.githubusercontent.com/assets/14015697/18558872/134e03c2-7b75-11e6-84f0-38a80d84e505.jpg)
i can drag

**Comment by ngodfraind** [comment]
Fixed by #2301
