### ISSUE TITLE
Login method can return 2 users, and crash 

### ISSUE THREAD

**Issue by eddymarques** [claroline/Distribution#873]
Method checks :
> WHERE u.username LIKE :username
> OR u.mail LIKE :username
> OR u.administrativeCode LIKE :username

Some users put their email address in [username] in one account, and the same email address in [mail] field for another.

Method matchs 2 accounts but its not allowed.

On account creation, these 3 fields should be checked to avoid duplication

![image](https://cloud.githubusercontent.com/assets/3414956/17129062/224f4840-5311-11e6-87ae-d861b3bd9b7c.png)

> 2.	at AbstractQuery ->getSingleResult () 
> in vendor/claroline/distribution/main/core/Repository/UserRepository.php at line 45    
> 3.	at UserRepository ->loadUserByUsername ('amel.corny@univ-lyon1.fr') 
> in vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/Security/User/EntityUserProvider.php at line 61    
> 4.	at EntityUserProvider ->loadUserByUsername ('amel.corny@univ-lyon1.fr') 
> in vendor/claroline/distribution/main/core/Library/Security/ExternalAuthenticator.php at line 58    
> 5.	at ExternalAuthenticator ->authenticateToken (object(UsernamePasswordToken), object(EntityUserProvider), 'main') 
> in vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/SimpleAuthenticationProvider.php at line 37    
> 6.	at SimpleAuthenticationProvider ->authenticate (object(UsernamePasswordToken)) 
> in app/cache/dev/classes.php at line 153    
> 7.	at AuthenticationProviderManager ->authenticate (object(UsernamePasswordToken)) 
> in vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/UsernamePasswordFormAuthenticationListener.php at line 96    
> 8.	at UsernamePasswordFormAuthenticationListener ->attemptAuthentication (object(Request)) 
> in vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AbstractAuthenticationListener.php at line 146    
> 9.	at AbstractAuthenticationListener ->handle (object(GetResponseEvent)) 
> in app/cache/dev/classes.php at line 68    
> 10.	at Firewall ->onKernelRequest (object(GetResponseEvent), 'kernel.request', object(TraceableEventDispatcher)) 
> 11.	at call_user_func (array(object(Firewall), 'onKernelRequest'), object(GetResponseEvent), 'kernel.request', object(TraceableEventDispatcher)) 
> in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php at line 61    
> 12.	at WrappedListener ->__invoke (object(GetResponseEvent), 'kernel.request', object(ContainerAwareEventDispatcher)) 
> 13.	at call_user_func (object(WrappedListener), object(GetResponseEvent), 'kernel.request', object(ContainerAwareEventDispatcher)) 
> in app/cache/dev/classes.php at line 4433    
> 14.	at EventDispatcher ->doDispatch (array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(GetResponseEvent)) 
> in app/cache/dev/classes.php at line 4362    
> 15.	at EventDispatcher ->dispatch ('kernel.request', object(GetResponseEvent)) 
> in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php at line 124    
> 16.	at TraceableEventDispatcher ->dispatch ('kernel.request', object(GetResponseEvent)) 
> in app/bootstrap.php.cache at line 3098    
> 17.	at HttpKernel ->handleRaw (object(Request), '1') 
> in app/bootstrap.php.cache at line 3071    
> 18.	at HttpKernel ->handle (object(Request), '1', true) 
> in app/bootstrap.php.cache at line 3222    
> 19.	at ContainerAwareHttpKernel ->handle (object(Request), '1', true) 
> in app/bootstrap.php.cache at line 2444    
> 20.	at Kernel ->handle (object(Request)) 
> in web/app_dev.php at line 28    
> 
>

**Comment by ngodfraind** [comment]
It should have been fixed by #881
