### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#877]
Lors de l'export d'un WS : 
http://claco.univ-lyon1.fr/app.php/workspaces/10373/export --> ça passe, en quelques petites secondes

ALORS QUE :
http://claco.univ-lyon1.fr/workspaces/10373/export --> error suivante

> [2016-07-15 15:19:34] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 2 passed to Claroline\CoreBundle\Library\Transfert\ConfigurationBuilders\Tools\ResourceManagerImporter::getResourceElement() must be an instance of Claroline\CoreBundle\Entity\Workspace\Workspace, null given, called in /data/www/clarolineconnect/claroline/vendor/claroline/distribution/main/core/Library/Transfert/RichTextFormatter.php on line 181 and defined" at /data/www/clarolineconnect/claroline/vendor/claroline/distribution/main/core/Library/Transfert/ConfigurationBuilders/Tools/ResourceManagerImporter.php line 802 {"exception":"[object](Symfony\Component\Debug\Exception\ContextErrorException%28code: 0%29: Catchable Fatal Error: Argument 2 passed to Claroline\CoreBundle\Library\Transfert\ConfigurationBuilders\Tools\ResourceManagerImporter::getResourceElement%28%29 must be an instance of Claroline\CoreBundle\Entity\Workspace\Workspace, null given, called in /data/www/clarolineconnect/claroline/vendor/claroline/distribution/main/core/Library/Transfert/RichTextFormatter.php on line 181 and defined at /data/www/clarolineconnect/claroline/vendor/claroline/distribution/main/core/Library/Transfert/ConfigurationBuilders/Tool/ResourceManagerImporter.php:802)"} []

En activant le debug de rewrinting nginx, il y a ceci (double slash)

2016/07/15 16:09:48 [debug] 7424#0: *127536 http finalize request: 0, "/app.php//workspaces/10373/export?" a:1, c:1

Je suis peut-être sur la bonne piste, ou pas !

Une idée ? une variable de type URL mal formatée dans la conf ? dans le code ?

**Comment by ngodfraind** [comment]
Il y a un workspace qui n'existe pas à un endroit. Je regarde pour un fix.

**Comment by ngodfraind** [comment]
Je laisse cette issue ouverte car c'est bizarre. Vous avez testé avec le fix ?

**Comment by LaurentGruber** [comment]
@eddymarques @ptsavdar c'est ok ?

**Comment by ptsavdar** [comment]
@LaurentGruber La plateforme n'est pas a jour. Du coup on a pas teste.

**Comment by Pauooo** [comment]
Sur la master (V8.0.0) lors de l'export j'ai ce message d'erreur : 

Uncaught PHP Symfony\Component\Debug\Exception\FatalThrowableError Exception: "Type error: Argument 1 passed to Claroline\CoreBundle\Listener\Transfer\ImgFormatListener::export() must be an instance of Claroline\CoreBundle\Event\RichTextFormatEvent, instance of Symfony\Component\EventDispatcher\Event given" at /var/www/html/claroline/vendor/claroline/distribution/main/core/Listener/Transfer/ImgFormatListener.php line 56

J'ai l'impression que ce n'est pas le même mais peut-être que je me trompe.

**Comment by ngodfraind** [comment]
J'ai reproduit @Pauooo

**Comment by ngodfraind** [comment]
Oupa (j'ai eu autre chose) mais que tu remontes n'a pas de sens dans le code que j'ai.

**Comment by LaurentGruber** [comment]
@ptsavdar any test ? it's ok ?
