### ISSUE TITLE
bug in plugin management

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#891]
In the plugin management : admin/plugins/ when i click on the configuration (the cogwheel), i have this error 500, for any bundle with this possibility (ClarolineCursusBundle, FormaLibreSupportBundle, ...) : 
```
No listener is attached to the 'plugin_options_undefined' event
500 Internal Server Error - MandatoryEventException
```

PS : I installed a fresh version with 
```
curl packages.claroline.net/releases/latest/claroline-16.05.tar.gz | tar xzv
cd claroline-16.05
php scripts/configure.php
composer fast-install
```

This had been corrected once, but i don't know why this has not been kept/merge on this version

**Comment by LaurentGruber** [comment]
@CPASimUSante toujours sur le master ?

**Comment by CPASimUSante** [comment]
a priori c'est corrigé sur le master actuel.
