### ISSUE TITLE
Exo bundle : several points for the exercise type

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/Distribution#898]
- [x] Define somewhere (tooltip, text, help document) what means the different exercise types : "sommative", "evaluative" and "formative", because everyone using the exo is not an expert in pedagogy terminology, and theses are not self explanatory.
- [x] More important, define what each of these type implies in term of functionnality (score or not, retry or not...)
- [x] small correction : in the list of exercise type, "evaluative" is not translated.
- [ ] in the list of exercise type, by default there is "type". If it is not a type shouldn't it be removed ? Is it the equivalent of "Your choice" ? In that case, one shouldn't be able to submit the form if "type" is selected. ATM, we can.
- [ ] according to the type of exercise, the exercise parameters and the question forms are different (some fields are displayed, other not => to specify)

**Comment by eldoniel** [comment]
Can somenone give me the texts that I should use as descriptions to each exercise type?

**Comment by Pauooo** [comment]
Could it be more visible ? (it's a higher level than "exercise_definition" but less visible)

**Comment by Pauooo** [comment]
@eldoniel is it normal to be able to do an evaluative exercise several times ? is there a strict definition of what each of these type implies ?
