### ISSUE TITLE
Missing activity field for ActivityParameters entity

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#90]
_From @purplefish32 on March 30, 2016 9:28_

_From @kitan1982 on November 2, 2015 14:16_

When parameters (ActivityParameters entity) are generated for a step, its activity field has to be set.

I think it can be done in StepManager.php > updateParameters method.

_Copied from original issue: InnovaLangues/PathBundle#292_

_Copied from original issue: claroline/ClaroSupport#8_

**Comment by Elorfin** [comment]
In fact, this is normal as the instance of `ActivityParameter` is created for the `Step` in order to not override the Activity parameters if the Activity is shared between paths.
