### ISSUE TITLE
[Collecticiel]Rédiger un texte : comportement du texte par défaut dans champ texte

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#91]
_From @purplefish32 on March 30, 2016 9:32_

_From @jj-quintin on February 17, 2016 17:14_

Le texte par défaut "Votre texte ici" doit se comporter de la même manière que le titre : dès la saisie d'un caractère, le texte "Votre texte ici" s'efface 

![image](https://cloud.githubusercontent.com/assets/16414632/13117799/af962798-d5a1-11e5-89bd-6e07698ce3c6.png)

_Copied from original issue: InnovaLangues/CollecticielBundle#269_

_Copied from original issue: claroline/ClaroSupport#9_

**Comment by ericvincenterv** [comment]
See this issue : https://github.com/claroline/Distribution/issues/44

**Comment by jj-quintin** [comment]
Fermer ce ticket. Le problème évoqué ici a été réglé d'après ce que je vois (le texte consigne ancien "Tapez votre texte ici", ne s'affiche plus dans le champ texte principal)
