### ISSUE TITLE
Amélioration lecteur pdf

### ISSUE THREAD

**Issue by LaurentGruber** [claroline/Distribution#916]
Nous avions déjà signalé ce point : les ressources pdf quand elles s'ouvrent via le lecteur de Claroline ne sont parfois pas très lisibles. Ne serait-ce pas envisageable d'avoir comme sur le net un lecteur qio ouvre le pdf directement dans le navigateur ?

**Comment by Garakotxea** [comment]
Bonjour Laurent,
En effet je furetai dans les problèmes posés par les pdf pour voir si quelque chose était ressorti. Les docs techniques à petit caractères ou comportant des schémas - parfaitement lisible sur Claroline 1.11.10 sont carrément illisibles sur le lecteur intégré à Claroline Connect ver8.0.4, comme si la résolution était fortement dégradée lors de la conversion.
Le problème serait réglé dans la version 17.06 ? 
Bien à vous
