### ISSUE TITLE
[Collecticiel]Page suivante ne fonctionne pas

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#92]
_From @purplefish32 on March 30, 2016 9:32_

_From @ericvincenterv on September 30, 2015 12:30_

Dans "espace partages", la pagination ne redirige pas vers la suivante.

_Copied from original issue: InnovaLangues/CollecticielBundle#139_

_Copied from original issue: claroline/ClaroSupport#10_

**Comment by jj-quintin** [comment]
Testé sur 7x-dev avec 47 étudiants : la pagination n'apparaît pas. S'il se confirme que la pagination a été désactivée, ce ticket serait donc une amélioration future (activation de la pagination et correction du bug recensé)

**Comment by ericvincenterv** [comment]
En milestone 16-12.
