### ISSUE TITLE
[Collecticiel]Attention aux droits

### ISSUE THREAD

**Issue by purplefish32** [claroline/Distribution#93]
_From @purplefish32 on March 30, 2016 9:34_

_From @ericvincenterv on July 15, 2015 8:15_

Une ligne gérant les droits a été mise en commentaire pour les tests.

Bien penser à le remettre.

Fichier : CorrectionController.php
Méthode : dropsDetailCommentAction

_Copied from original issue: InnovaLangues/CollecticielBundle#66_

_Copied from original issue: claroline/ClaroSupport#11_

**Comment by jj-quintin** [comment]
@LaurentGruber Si c'est un bug, c'est un peu gênant de le déplacer en milestone 16.09, non ? A ce propos, je viens de faire le tour des tickets collecticiel et je vois que tu les généralement déplacés en 16.9. N'est-ce pas une stratégie risquée ? Peut-on en discuter ?

**Comment by LaurentGruber** [comment]
@jj-quintin @ericvincenterv tout ce qui n'avait pas pu être fait en 16.05 à été mis en 16.09 avant que le milestone 16.05.1 soit créé. Pour ce qui est du collecticiel, je n'ai pas de vision de ce qui se passe donc comme je le disais à la réunion hier, n'hésitez pas à modifier. Pour passer un ticket en 16.05.1 il doit être fini d'ici 10 jours et il ne doit pas modifier la base de donnée... Donc si ça peut être fait pour la 16.05.1 go go go

**Comment by ericvincenterv** [comment]
@jj-quintin : il faut discuter des tickets à faire d'ici la fin du milestone "16.05.1"  @LaurentGruber : si un ticket modifie la définition d'une colonne d'une table ?

**Comment by jj-quintin** [comment]
@ericvincenterv @LaurentGruber 

Oui, il faut en parler. Tu me diras ce qui est rapidement faisable. On peut tout envisager du moment que ce qu'on livre fonctionne parfaitement (= sans dysfonctionnement, même si pas parfait dans les détails de l'ergonomie qu'on verrait pour 16-09).

Du minimum au maximum : 

1- Désactiver l'évaluation et se contenter de l'accusé de réception avec commentaire (version d'il y a qques mois, je ne sais plus de mémoire, mais je pense qu'on a bien vérifier ce fonctionnement)
2- Un mode d'évaluation (notation ou appréciation, celui qui est le plus avancé et le plus stable)
3- Les deux modes d'évaluation

Dis-moi ce que tu en penses. Je propose que l'on ne prenne pas trop de risques (en terme de stabilité de fonctionnement et fiabilité) pour la livraison 16.05.1

**Comment by jj-quintin** [comment]
@ericvincenterv 

Quand on sera décidé, je te laisserai changer les milestones en fonction, ok ?

**Comment by ericvincenterv** [comment]
@jj-quintin : je pense que le mieux est de faire un document qui regroupe les tickets/issues puis de mettre des priorités. Je m'occupe du document.

**Comment by jj-quintin** [comment]
@ericvincenterv  
ok, je reste à ta disposition au besoin
