### ISSUE TITLE
Compte à durée limitée

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#940]
Ils serait pratique de pouvoir mettre une limite temporelle à la validité d'un compte. On pourrait indiquer cette valeur à la création d'un compte utilisateur ( + possibilité de la mettre dans le csv). La valeur par défaut serait celle pour une durée illimitée. A la fin du délais, le compte est désactivé ( pas supprimé). => suggestion du forum Claroline.net

**Comment by LaurentGruber** [comment]
duplicate of https://github.com/claroline/Distribution/issues/944
