### ISSUE TITLE
Question graphique

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#942]
Possibilité de joindre les zones avec un trait. CF les dessins d'enfant numérotés où l'on dessine en reliant les nombres.

**Comment by LaurentGruber** [comment]
Tu peux être plus explicite ?

**Comment by LaurentGruber** [comment]
Le monsieur veut pouvoir tracer des polygones comme exercice

**Comment by Gatomlo** [comment]
Bein oui, c'était tout de même clair... non ?

**Comment by Elorfin** [comment]
Nope, et ça l'est toujours pas pour moi :p (je pensais que tu voulais qu'on développe les dessins à relier). 

T'as un exemple de question ? Pour avoir une idée plus précise de ce qui est attendu comme fonctionnalité ?

**Comment by Gatomlo** [comment]
Bein par exemple dessiner un carré...
