### ISSUE TITLE
AMÉLIORATION DE LA GESTION DES UTILISATEURS

### ISSUE THREAD

**Issue by greg49** [claroline/Distribution#944]
Voir les utilisateurs connectés par un point de couleur (vert en ligne - gris déconnecté - rouge : bloqué) - penser à ajouter un filtre pour n'afficher que les utilisateurs connectés par exemple

- [ ] Permettre de bloquer un utilisateur sans effacer son compte de manière automatique ou manuelle - forcer sa déconnexion

- [ ] Définir une période d'accès à la plateforme CC - par exemple un utilisateur démo a accès  pendant 3 mois à la plateforme et ses contenus.

**Comment by LaurentGruber** [comment]
Le premier point est prévu pour plus tard et est lié au chat, les 2 autres sont prévu dans les jours qui viennent.
