### ISSUE TITLE
Problem with rights

### ISSUE THREAD

**Issue by david42** [claroline/Distribution#953]
The problem is commented in this [video](https://filezemp.univ-st-etienne.fr/ia00sd)

**Comment by stefk** [comment]
The video is missing.

**Comment by david42** [comment]
Oups, the link is now visible

**Comment by LaurentGruber** [comment]
il faudrait plus d'information, Il y a un log d'erreur ? quelque chose de particulier en db ? Quels sont les conditions qui nous permettrait de reproduire le bug ? Comme ça je ne sais pas le reproduire

**Comment by LaurentGruber** [comment]
can't reproduce
