### ISSUE TITLE
[CoreBundle]  Ajout de 2 boutons publier / dépublier dans la barre d'outils du gestionnaire de ressources

### ISSUE THREAD

**Issue by clarophil** [claroline/Distribution#982]
Dans la barre d'outils du gestionnaire de ressources, il serait intéressant d'jouter 2 boutons qui permettrait de publier ou dépublier une ressource sur un ensemble de ressources sélectionnées.

Actuellement, il faut une par une ouvrir le menu contextuel puis Editer les propriétés puis décocher Publier puis OK

**Comment by Elorfin** [comment]
Ne faudrait-il pas également le mettre dans le menu contextuel de la ressource ?

**Comment by jj-quintin** [comment]
Si on a ce que propose Philippe cela me paraît suffisant. La liste des options du menu contextuel est déjà longue
