### ISSUE TITLE
Création de badge avec ressource résultat

### ISSUE THREAD

**Issue by Gatomlo** [claroline/Distribution#998]
Pouvoir attribuer automatiquement un badge selon les points obtenus dans la ressource résultat.

**Comment by ptsavdar** [comment]
@Gatomlo @stefk J'ai commencé à regarder le développement de cette fonctionnalité mais je me suis vite rendu compte qu'il y a certains problèmes. Je m'explique : l'attribution des badges se base sur le système des logs. Déjà le ResultBundle ne gère pas la création des logs pour les notes des étudiants sur lesquels on pourrait se baser. Mais même si je crée des logs spécifiques à l'attribution des notes, ceci ne sera pas suffisant. Supposons que l’enseignant a noté Toto  avec un 15. Un badge est attribué à toutes personnes ayant une note supérieure à 10. Toto du coup obtient le badge le moment où l'enseignant lui donne le 15. Plus tard l'enseignant décide de changer la note de Toto pour 9 parce qu'il s’est trompé. Toto a déjà obtenu le badge mais il le garde toujours parce que les badges ne se retirent pas automatiquement. Même si on effectue un recalcule de l’attribution de ce badge, Toto l'aurait toujours parce que dans les logs à un moment donnée il a eu 15 (donc >10, donc la condition est remplie). Pareil en cas de suppression de la note (le log d’obtention du 15 est toujours présent).
De mon côté, ce que je peux faire c'est attribuer le badge au moment de l'obtention d'une note mais après ça reste à l'enseignant de retirer le badge manuellement en cas de modification ou suppression d’une note. Si vous préférez un fonctionnement différent ou plus avancé, il serait préférable que ce soit à quelqu'un qui connaît mieux le ResultBundle et son fonctionnement, de développer cette fonctionnalité.

**Comment by stefk** [comment]
@ptsavdar, effectivement la création de logs n'a pas été prise en compte au départ dans le plugin résultats. En ce qui concerne l'autre problème dont tu parles, je crois qu'il n'est pas spécifique à ce plugin. Les badges se basent sur les logs et ceux-ci ne sont jamais supprimés, par conséquent les modifications de règles ne sont pas rétroactives. 

S'il y a une solution générale à ce problème, je crois qu'elle est plutôt du côté des badges. Je vois par exemple qu'il y a un champ "version" dans l'entité badge. Est-ce qu'une modification des règles ne devrait pas entraîner la création d'une nouvelle version du badge ?

Si ce n'est pas souhaitable, on pourrait ajouter une date de dernière modification aux badges et faire en sorte que cette date soit mise à jour chaque fois qu'un enseignant modifie les règles d'attribution. Ainsi il serait possible à tout moment de recalculer les attributions en excluant les logs dont la date est antérieure à celle de la modification du badge.

Bien sûr, dans un premier temps, laisser le prof corriger son erreur comme tu le proposes me convient tout à fait ;)

**Comment by ptsavdar** [comment]
@stefk 

> par conséquent les modifications de règles ne sont pas rétroactives.
Oui en effet, les modifications des règles ne sont pas rétroactives et n'incitent pas un recalcule des badges. Toutefois, l'utilisateur à l'option de recalculer lui même après avoir porté des changements sur les règles (bouton recalculer les attributions).

Le champ version c'est d’abord pour être conforme avec la norme OpenBadge et après ça peut avoir plusieurs utilités (ça peut indiqué l'année académique d'obtention, le changement des règles etc.). Mais le changement des règles ne signifie pas aussi changement de version.

Par contre, quand je parlais de changements, je parlait pas des changements des règles d'attribution. Dans mon exemple la règle est toujours la même mais la condition n'est plus remplie (vu qu'il a 9 et non plus 15). Même si on permet le recalcule d'un badge après une date précise cela ne résout pas forcement notre problème. Cela peut aussi retirer le badge de quelqu'un qui remplie la condition mais qui a eu sa note avant la date précise. 

Ok dans un premier temps je fais la version "simple" et on verra plus tard pour la version avancée.

**Comment by stefk** [comment]
Tu as raison, j'ai parlé trop vite. Une autre solution serait de ne considérer que les logs les plus récents lorsqu'on recalcule les attributions (e.g. l'étudiant a eu 15 un moment mais il y a un log postérieur qui indique 9 et c'est celui-là qui est pris en compte). Ça aurait du sens pour la ressource résultats, peut-être aussi pour les exercices, mais sans doute pas pour les autres. Je ne sais pas dans quelle mesure on peut modifier le calcul en fonction du type.

**Comment by stefk** [comment]
Est-ce que ça ne pourrait pas être une option de la fonctionnalité existante de recalcul ? Par exemple, une case à cocher du genre "Ne prendre en compte que la dernière activité enregistrée".

**Comment by ptsavdar** [comment]
Moi non plus je ne suis pas sur dans quelle mesure est possible de modifier le calcul en fonction du type. J'ai trop peu touché le plugin des badges. Par contre il y a une autre ploblematique après, supposons qu'on peut prendre que la dernière activité enregistrée pour le update si le nom de l'action/evenement est le même ça peut marcher mais dans le cas de la suppresion d'une note par exemple on fait comment? Là la dernière activité sera toujours la "avant-dernière".

**Comment by stefk** [comment]
Dans ce dernier cas, il n'y a pas de solution, à part ignorer complètement les logs... Mais c'est vraiment un cas limite à mon avis. Si l'ajout d'une nouvelle note ou la modification d'une note existante peuvent être pris en compte, ça me paraît déjà bien. On pourra en parler aux autres mercredi éventuellement.

**Comment by ptsavdar** [comment]
Ok pas de souci. Je vais commencer à developper la functionnalité à partir de la semaine prochaine. Je vais en profiter pour ajouter des logs dans le ResultBundle.
